### ISSUE TITLE
Es sollte nicht möglich sein, dass Filme Einkaufslisten > oder < 1  anbieten

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#100]
Nach der letzten Debugversion bieten die meisten Filme unbegrenzte Einkaufslisten an. Ein Film sollte nur eine Einkaufsliste bieten, der Film nach dem Dreh verschwunden sein. 

In einem Fall wird ein Film ganz ohne Einkaufsliste angeboten. 
![noEL](https://user-images.githubusercontent.com/57690824/68755848-6956f400-0609-11ea-8d90-2dfe7a5ab460.png)

**Comment by GWRon** [comment]
Neues Spiel oder alter Speicherstand?
Alter Speicherstand = anderer gesetzter Standardwert ("keine Begrenzung").

**Comment by GWRon** [comment]
Tritt mit neuen Spielen in der aktuellen Version nicht mehr auf
