### ISSUE TITLE
Localization: For some not yet translated text entries, the resource key/name appears instead of the English fallback

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1005]
Playing with language set to Spanish, in some instances where the Spanish text is not yet defined in the resource files, the resource key or variable name appears instead of the fallback English text.

![supermarket-spanish](https://github.com/TVTower/TVTower/assets/123826268/641abae0-633d-48f1-b716-2ae51984cd4b)

While in other places the English text *does* appear (still playing in Spanish):

![office-spanish](https://github.com/TVTower/TVTower/assets/123826268/f0cbe887-f33b-41b8-b676-551f4906cb83)

I can see no difference in the resource files in these instances, they're both out-commented in the same way.

**Comment by GWRon** [comment]
Hmm dialogues might use the "choose amongst one of the options" approach to allow variation.

The tooltip might not use that.

**Comment by nittka** [comment]
TLocalizationLanguage#HasSub is buggy. It returns True even if the key is not known causing the fallback to the default language to break.
