### ISSUE TITLE
Produktionsstudios erhalten keine XP

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#101]
Im aktuellen Spielstand habe ich ca. 25 Folgen von 3 Serien sowie diverse Filme und Shows im selben Produktionsstudio drehen lassen. Aktuell laufen darüber 2 Filme und 1 Serie mit 6 Folgen. Die XP Bar bewegt sich nicht. Das Studio verbleibt seit Spieltagen auf Lvl 3 mit geringen XP. Das ging in der 2018er Live Version noch. 

![prodfirma](https://user-images.githubusercontent.com/57690824/68756255-1f224280-060a-11ea-96be-a5c197b97efd.png)

**Comment by GWRon** [comment]
Nach Abschluss einer Billigproduktion:
```[14:12:41] DBG      | TPRODUCTIONCOMPANY: Finish production and gained experience. Experience: 127->138  level: 1->1  LevelXP: 1.27->1.38%  XP: 1.27->1.38%
```

Firmen koennen pro Produktion bis zu "100 Punkte" bekommen:
```BlitzMax
		'100 perfect productions would lead to a 100% experienced company
		local baseGain:float = 100 * programmeData.GetQualityRaw()

		'the more XP we have, the harder it gets
		if currentXP <  500 then return 1.0 * baseGain
		if currentXP < 1000 then return 0.8 * baseGain
		if currentXP < 2500 then return 0.6 * baseGain
		if currentXP < 5000 then return 0.4 * baseGain
		return 0.2 * baseGain
```

**Comment by GWRon** [comment]
In der "Augustversion" sollte es entsprechend schon gleich reagiert haben - seit "0.6.1" hingegen hat sich da was geaendert - und eventuell ist der Levelindikator fehlerhaft (erinnere mich, dass da daran gearbeitet wurde)

**Comment by GWRon** [comment]
Fixed in f47042a190684dde0b53c6ea8dcfa43839a7281e
