### ISSUE TITLE
Minderjährige Schauspieler

### ISSUE THREAD

**Issue by nsalomon** [TVTower/TVTower#1011]
Wäre es möglich zu verhindern, das minderjährige Schauspieler für Erotikproduktionen engagiert werden können?

**Comment by nittka** [comment]
Das Thema ist bekannt aber noch nicht adressiert (siehe #850). Die API für das Filtern der möglichen Besetzungen ist da nicht so einladend.

**Comment by nittka** [comment]
Bei den aktuell offenen "Balancing-Problemen" fände ich Altersbeschränkungen in den Datenbankdefinitionen Overkill. Einerseits müsste man die Werte überhaupt erst pflegen, andererseits spielt das Alter sonst auch keine Rolle. Man könnte aktuell einen Action-Film mit ausschließlich über 80-Jährigen drehen und es würde bei gleichen Werten für die Schauspieler keinen Unterschied im Ergebnis zu ausschließlich 10-Jährigen machen.

Der PR beschränkt ausschließlich GUI-seitig die mögliche Besetzung, hat also gar keinen Einfluss auf KI-Produktionen (die aktuell gar nicht von der KI selbst besetzt werden).

**Comment by nsalomon** [comment]
Salü,

Es gibt diverse Filme ab 18, in denen U18 Jährige mitspielen. No issue!
Es geht schlicht um das Erotik-genre. Würde dies, wenn vom Code her möglich, für das Erotikgenre sogar hardcoden.
Will auch keinen Bezug zur Realität ziehen, es geht auch darum, das Spiel von Interpretationsspielraum zu schützen. Braucht nur einen Streamer, der sich damit nen Spass macht.
Es rückt niemanden in ein gutes Licht ein 12 Jähriges Mädchen als "Erotik-Darstellerin" zu bezeichnen. Passiert z.B. wenn Leihendarsteller ohne Altersangabe an Erfahrung gewinnen.

Ueber die Prio kann man sich sicher streiten, aber früher oder später würde ich persönlich empfehlen, diese Problematik anzugehen.

**Comment by scr0llbaer9000** [comment]
> Eventuell koennte man dem dahingehend auch entgegenwirken, dass einem "Job" (also die Eintraege der Besetzungsliste im Drehbuch) eine Altersgrenze (min UND max?) mitgegeben werden kann.

Hab ich mir auch schon oft gedacht und fände schon gut wenn das als (zusätzliches) Feature irgendwann mal kommt, damit sich das Game eben auch "realistischer" "anfühlt". Braucht auch kein Anreizsystem, Besetzung mit nicht passendem Alter sollte man dann gar nicht erst auswählen können? Den Pflegeaufwand im bisherigen Datenbestand halt ich jetzt auch nicht für allzu problematisch.

**Comment by GWRon** [comment]
Leute wuerden aber eventuell nicht nur "gesetzliche Limits" setzen - sondern auch "Wunschvorstellungen". Also "Hauptcharakter ist alter Mann".

Wenn dies nun die Auswahl "beschraenkt", steht dies im Gegensatz zu den "kreativen Entscheidungen" von uns Produzenten. Gleiches gilt andersherum. Sprich: Kann ein alter Arnie noch den Terminator spielen?
Oder man bedenke die 00er Komoedien wie "Big Mama's Haus". 

Sprich wir haben "Legalgrenzen" und "Kreativgrenzen". Ersteres wird "Jungdarsteller in Erotikfilmen" sein, letzteres Dinge die der Drehbuchschreiber "vorsieht" ("Bitte aelterer Schauspieler").

In der heutigen Zeit gaebe es neben dem "Alter" im Uebrigen noch die "Diversitaet" zu beachten ("Black Panther" sollte dann eventuell aus einem passenden Land stammen). Allerdings wuerde ich das gern ignorieren wollen - "Hautfarben ignorieren" usw. da wir sonst echt ein Riesenfass aufmachen (und derzeit noch "wichtigere" Baustellen haben)

**Comment by nsalomon** [comment]
Das wiederum ist ein Fass ohne Boden und hat meiner Meinung nach nichts mit dem sehr spezifischen Issue mit dem Erotikgenre zu tun.

**Comment by scr0llbaer9000** [comment]
> Das wiederum ist ein Fass ohne Boden und hat meiner Meinung nach nichts mit dem sehr spezifischen Issue mit dem Erotikgenre zu tun.

Klar, aber einfach `minAge` und `maxAge` für eine Rolle angeben können wär *glaube ich* relativ einfach zu implementieren und würde schon mal vieles was man so haben will erschlagen, inkl dem Issue im OP.

**Comment by nittka** [comment]
Ja, angeben können ist einfach. Die korrekte Umsetzung für den Supermarkt ist aber nicht trivial, da man die Besetzung nicht nur aus der Auswahlliste holen, sondern auch Personen zwischen den Slots verschieben kann, bei unterschiedlichen Beschränkungen muss auch das unterbunden werden.
UND die Rollen in der Datenbank müssten entsprechend gepflegt werden (und für Templates möchte man ggf. nicht immer Rollen, die ja einen Namen verlangen, der zwischen unterschiedlichen Instanzen eines Templates ggf. gar nicht gleich bleiben soll).
Das Problem dieses Tickets über eine erweiterte Rollendefinition lösen zu wollen, funktioniert meiner Ansicht nach nicht gut.

**Comment by scr0llbaer9000** [comment]
Ich war sloppy, `minAge` und `maxAge` sollte an den `job` gebunden werden.

(Denn eine Rolle, wie etwa theoretisch z.B. "Indiana Jones", sollte global nur einmal definiert werden müssen, und dieselbe Rolle kann dann in verschiedenen Verfilmungen von sehr unterschiedlichen Altersstufen zu besetzen sein, wie im Beispiel "Die Abenteuer des jungen Indiana Jones").

Somit wäre das losgelöst von irgendwelchen Problemen, die mit verlangten Namen zu tun haben.

Ein bestimmter Index in der Besetzungsliste ist dann für ein bestimmtes Alter reserviert, und da kann man dann halt keinen Schauspieler mit falschem Alter drauf-droppen.
