### ISSUE TITLE
Font: Some characters are not rendered

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1013]
Some characters like the German simple quotation marks (`‚`, `‘`), or the trademark symbol `™` are not rendered in programme or other descriptions, and more spacing appears in their place.

Applying the respective HTML encoding like `&trade;` does not help either.

When I applied HTML encoding I once even ran into a strange bug where the movie would not be available anymore at all, it would just disappear from the archive, but I can't reproduce it for now, it didn't happen again when testing.

**Comment by scr0llbaer9000** [comment]
If this issue can't be reproduced, I figure it may be particular to my linux installation which might lack some required fonts, but I'm not sure, and I have no Windows or other distro to double-check.

**Comment by GWRon** [comment]
Fonts are shipped with the game. Must be something different.
