### ISSUE TITLE
Wenn man ein Drehbuch verkauft, werden die angeforderten Einkaufslisten nicht gelöscht

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#102]
S. Issue #100 : 

Für die Reise-Show hatte ich testweise von den 8 erstellbaren Einkaufslisten alle 8 angefordert, 2 davon abgedreht. Nach dem 2. Dreh habe ich das Drehbuch beim Händer verkauft. Die übrigen Einkaufslisten werden im Supermarkt weiterhin angezeigt. 

![el_dbverkauf](https://user-images.githubusercontent.com/57690824/68756974-71179800-060b-11ea-861f-5bf4efdfdd79.png)

**Comment by GWRon** [comment]
Kann ich nicht nachvollziehen.

- Drehbuch gekauft
- 3 von 3 Einkaufslisten besorgt
- 2 davon ausgefuellt und fertig produziert
- Drehbuch in den Koffer gelegt und in der Agentur verkauft
- in den Supermarkt gegangen: keine Einkaufsliste mehr zu sehen

Gleiches auch, wenn ich die dritte Liste bereits "vorgeplant und angezahlt" habe

**Comment by Nalindir** [comment]
Betroffenes Savegame beigefügt. 

[fortschritt_tag42.zip](https://github.com/TVTower/TVTower/files/4059980/fortschritt_tag42.zip)

**Comment by nittka** [comment]
Ich konnte das Problem bei mir reproduzieren. Meine Vermutung ist, dass es bei Serien aus derselben Schablone auftritt, die man bereits produziert hat. Also z.B. Dramen im Hochhaus alle Folgen produziert, Drehbuch Fehler im Hochhaus gekauft, eine Folge abgedreht und dann das Drehbuch verkauft - Einkaufslisten bleiben. Interessanterweise sagt der Studiochef auch, dass 12/12 Produktionen erfolgt sind, wenn ich die erste Folge des zweiten Drehbuchs bringe. ID-Duplikats-Problem?
