### ISSUE TITLE
Supermarkt: EL Ansicht springt auf "TOP" wenn eine Produktion abgeschlossen wurde

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#103]
Schließt man eine Produktion im Supermarkt ab, springt die Einkaufslistenansicht wieder auf den obersten Eintrag. 
Das ist besonders dann ärgerlich, wenn man eine Serie mit der "Einstellungen übernehmen" Option durchproduzieren möchte. Man muss dann immer wieder runterscrollen zur nächsten Folge. Die EL Ansicht sollte auf der Position verbleiben.

**Comment by nittka** [comment]
Ich glaube, dieses Verhalten beobachtet zu haben, selbst wenn ich mehrere Einkaufslisten geholt habe, und eine der unteren für die Bearbeitung selektiere; nicht erst beim Abschluss. Das muss ich aber nochmal verifizieren.
