### ISSUE TITLE
Neu erworbene Filme werden nur gehighlighted, wenn der Computer offen ist. 

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#104]
Wenn man einen Film beim Filmhändler kauft, wird dieser beim ersten Betreten des Büros im Computer nicht mehr blau gehighlighted. 
Gleiches gilt, wenn eine Produktion beendet wird, während man nicht im Büro ist. 

Ist man in der Programmplanung und eine Produktion wird abgeschlossen, dann wird die entsprechende Kategorie und der neue Film korrekt gehighlighted.

**Comment by GWRon** [comment]
Du moechtest also, dass ein Film, der im Archiv vom "Koffer" wieder zum "Typen" gezogen wird, als "neu" ("blau" hervorgehoben) markiert wird? Richtig verstanden?

Eigenproduktion: ok, schau ich mir an.

**Comment by Nalindir** [comment]
Nein, nicht richtig verstanden. Habe den Fehler in der Ausgangsbeschreibung korrigiert. 

Mir gehts um den Use-Case: Kaufe einen Film beim Fiklmhändler, verlasse den Filmhändler, gehe ins Büro, öffne den PC: 

IST: Das Genre und der Film werden nicht gehighlighted.

 Tatsächlich ist das von dir vermutete Verhalten bereits implementiert. Ziehe ich einen Film im Archiv in den Koffer und lege ihn zurück ins Archiv, wirds gehighlighted.

**Comment by GWRon** [comment]
Ok. Vermerkt.

**Comment by GWRon** [comment]
Kann ich lokal nicht nachvollziehen.

- Film gekauft und ins Buero -> blau hervorgehoben
- Eigenproduktion gestarted, abgeschlossen und ins Buero -> blau hervorgehoben.

**Comment by Nalindir** [comment]
Fixed in latest Dev Version (07.01.2020). Closed.
