### ISSUE TITLE
Schwierigkeitsgrade und Senderausbau

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1048]
Bei KI-Spielen mit der angepassten Logik für die Aktualitätserholung etc. ist aufgefallen, dass die KI selbst im Schwierigkeitsgrad normal Probleme mit dem Senderausbau bekommt, wenn die Antennenreichweite zurückgeht (Startjahr 1992). Wenn die Senderkosten hochgehen und gleichzeitig die Reichweite runter, wird es schwer, genug Ersparnisse anzusammeln, um in anderes Bundesland zu expandieren.

Mein aktueller Vorschlag wäre, die Modifier für die Sendegenehmigung tatsächlich umzudrehen. Bei leicht wird die Genehmiung deutlich teurer (man hat ja höhere Werbeeinnahmen, geringere Filmpreise und geringere Senderkosten) wohingegen die Genehmigugn bei schwer billiger wird (durch geringere Werbeeinnahmen, höhere Filmpreise und höhere Senderkosten ist das Ansparen für die Ausdehnung deutlich anstrengender).

**Comment by GWRon** [comment]
Ich verstehe das jetzt noch nicht ganz.

Also die KI hat Probleme Ersparnisse für die Expansion anzulegen ("Genehmigung Preis X ist zu hoch")

Wenn wir nun bei "leicht" die Genehmigung teurer machen, fressen doch eben die Genehmigungskosten die Mehreinnahmen durch Werbung wieder auf?

**Comment by nittka** [comment]
Die Argumentation für die Änderung wäre: Genehmigungskosten sind Einmalkosten. D.h. bei grundsätzlich höheren Einnahmen und geringeren Kosten sind die leichter zu stemmen. Im Level schwer ist der Senderausbau ohnehin schwieriger, da die Gewinnmarge kleiner ist und die laufenden Kosten stärker steigen. Daher wäre es vertretbar, dort die Einmalkosten geringer zu halten.

**Comment by GWRon** [comment]
Klar koennte es teurer sein, wenn man eh Probleme an anderer Stelle haben wird.

Aber welchen Vorteil hat man davon ..bzw was erleichtert sich dadurch fuer die KI?

**Comment by nittka** [comment]
In #1057 sind schon Balancin-Anpassungen, die auch den Senderausbau betreffen, enthalten. Wie dort im Kommentar steht, ist ein schwerwiegenderes Problem aber wohl die z.T. sich schnell und stark ändernde Zuschauerverteilung zwischen Antenne, Kabel und Satellit.

**Comment by nittka** [comment]
Das Thema Zuschauerentwicklung sollte separat diskutiert werden. Wie oben geschrieben sind Balancing-Anpassungen bezüglich der Senderkosten zusammen mit der langsameren Filmerholung erfolgt.
