### ISSUE TITLE
VV: Tooltip der Werbung sollte die Anforderungen zum aktuell laufenden Programm als erfüllt/nicht erfüllt markieren

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#105]
ch würde es begrüßen, wenn ich im Tooltip der Werbeschaltfläche sehen würde, ob die Anforderungen im aktuellen Programm erfüllt werden. Oftmals ist ja doch so, dass man Stunde für Stunde experimentiert und anpasst. Aber gerade bei den Zuschauergruppen verliert ich schnell den Überblick - reicht das, reicht das nicht. Finde das sehr unkomfortabel, nicht nur über die Zahlen zu gehen, sondern insbesondere wegen der Zuschauergruppen dann die Detailansicht einzublenden und notfalls zu fixieren. Wenn ich mit der Maus drübergehe und das Feld mit den Anforderungen schon farblich rot/grün eingefärbt wäre, dass es für das aktuelle Programm nicht reicht/reicht, fände ich das sehr hilfreich.

**Comment by Nalindir** [comment]
![VV_anforderungenerfüllt](https://user-images.githubusercontent.com/57690824/68759017-37e12700-060f-11ea-9aa3-302c5d85e039.png)

**Comment by nittka** [comment]
Ich habe jetzt erst gesehen, dass schon eine Hervorhebung gemacht wird. Der Unterschied ist aber so dezent, dass er nicht auffällt, wenn man nicht genau weiß, wonach man sucht.

**Comment by GWRon** [comment]
Die war absichtlich so... unaufdringlich... Sollte ich das rote sichtbarer machen oder pulsieren lassen?

**Comment by nittka** [comment]
Ich denke tatsächlich ja. Da das Ticket noch nicht geschlossen war, dachte ich, es wäre noch gar nichts gemacht (hatte den Commit ignoriert). Ich hatte mich dann im Code vorgehangelt und gesehen, dass es bereits ein Flag für das Hervorheben gibt.
Als ich dann im Testspiel zwei Werbungen gegeneinander ausgetausch hatte, habe ich (erst) bei genauem Hinsehen den Unterschied bemerkt.
Also ja, noch etwas deutlicher wäre toll. Wenn geplant ist, den Werbeblock im Planer leicht pulsieren zu lassen (wie in meinem Ticket geschrieben), wäre es konsequent, auch hier Pulsieren einzusetzen: man sieht den Block pulsieren, hovert drüber und sieht warum.

**Comment by GWRon** [comment]
Die dazugehoerige Grafik ist in 
res/gfx/misc/datasheet_general.png
"zweite Zeile rechts"

Da ist noch Platz ... ich koennte also:
Zwei staerker eingefaerbte Varianten hinzufuegen und in "game.programme.adcontract.bmx : ShowAdvertisementSheet()" 
```
		'minAudience
		If minAudienceHightlightType = 1
			skin.RenderBox(contentX + 5, contentY, 100, -1, TFunctions.convertValue(GetMinAudienceForPlayer(forPlayerID), 2), "minAudience", "goodHint", skin.fontBold)
		ElseIf minAudienceHightlightType = -1
			skin.RenderBox(contentX + 5, contentY, 100, -1, TFunctions.convertValue(GetMinAudienceForPlayer(forPlayerID), 2), "minAudience", "badHint", skin.fontBold)
		Else
			skin.RenderBox(contentX + 5, contentY, 100, -1, TFunctions.convertValue(GetMinAudienceForPlayer(forPlayerID), 2), "minAudience", "neutral", skin.fontBold)
		EndIf
```
anpassen. Oder ich koennte

`datasheet.renderBox` noch um ein Overlay erweitern - dann koennte man das relativ beliebig und "individuell" einfaerben. 
Oder wir zeichnen haendisch ein entsprechendes Sprite (9Patch - dynamische Groessen) drueber. Das Sprite waere wie der BG der Messageboxen - nur halt an allen anderen Stellen "transparent".
Waere wohl das "einfachste" Vorgehen - und liesse sich auch bequem "einfaerben".

**Comment by nittka** [comment]
Zu den Optionen kann ich nicht viel sagen. Beziehen sie sich auf das Pulsieren oder allein auf ein stärkeres Hervorheben? Ich könnte mir nämlich vorstellen, dass der Farbton gar nicht viel kräftiger sein muss, wenn die Box "blinkt". Dann reagiert das Auge schon auf die Änderung.
Wenn es beim reinen Hervorheben nicht "schön" aussehen müsste (Farbverläufe etc.), wäre eine API, die direkte Farbdefinitionen erlaubt, natürlich am "bequemsten" und flexibelsten (Textfarbe, Hintergrundfarbe).

**Comment by GWRon** [comment]
Die Farbe geht.. einfach ein graues halbtransparentes Overlay mit "setcolor r,g,b" vorm Zeichnen einfärben).

**Comment by GWRon** [comment]
Ich kann den Boxen ja eine Overlayfarbe und einen Effekt beibringen...

**Comment by nittka** [comment]
Aktuell wird die Werbung sofort beim Nehmen als "nicht erfüllt" markiert, selbst wenn man sie gar nicht dem aktuellen Programm zuordnen will (weil da schon längst eine passende Werbung ist). Sie sollte diese Markierung erst bekommen, wenn man sie auf den entsprechenden aktuellen Block bewegt - dann fällt die Änderung von neutral nach roter Hintergrund vielleicht auch schon so auf (ohne dass die Farbe intensiver wird).

**Comment by nittka** [comment]
Stand Ist im Programmplaner:
* hovert man über dem schon geplanten Werbeblock für die aktuelle Sendung, ist die Zuschauerzahl leicht grün oder leicht rot umrandet, je nachdem ob die Zuschauerkriterien erfüllt sind
* hovert man über oder nimmt man eine neue Werbung, um sie im Programm zu platzieren, wird im Datenblatt dieselbe Markierung entsprechend dem aktuell laufenden Programm angezeigt
* der Werbeblock zum aktuell laufenden Programm ist neutral grau und schaltet direkt auf rot, wenn die Werbung startet und die Bedingungen nicht erfüllt sind

Die Hervorhebungen sind dezent und könnten übersehen werden. Wenn man aber einmal weiß, worauf man achten muss, fällt es auch auf.

Verbesserungsvorschläge (z.T. aus dem verlinkten Ticket #151).
* Man kann argumentieren, dass die Hervorhebung einer neuen Werbung erst gemacht werden sollte, wenn sie über den entsprechenden Werbeblock bewegt wird (vielleicht sollte die Werbung ohnehin woanders hin, dann verwirrt die Färbung ggf.). Damit erschwert man aber den Fall, *dass tatsächlich* der aktuelle Block geplant werden soll. Je nach Implementierungsaufwand wäre folgende Zwischenvariante denkbar: Wenn der aktuelle Werbeblock leer ist (keine Werbung geplant), wird wie im aktuellen Implementierungsstand die Hervorhebung gemacht, da es wahrscheinlich ist, dass man genau diesen Block besetzen möchte. Wenn der aktuelle Werbeblock schon besetzt ist (und das Zuschauerkriterium erfüllt ist, also kein Werbeausfall droht), erfolgt keine Hervorhebung, da wahrscheinlich ist, dass man einen anderen Block plant
* Eine Hervorhebung erfolgt in jedem Fall, wenn die genommene Werbung über den aktuellen Werbeblock bewegt wird, da eine Planung wahrscheinlich ist (ein Klick entfernt). Damit bekommt man frühe Rückmeldung.
* Der aktuell geplante Werbeblock könnte leicht rot pulsieren (oder ein Warnschild bekommen), wenn Nichterfüllung droht. Damit bekommt man ein schnelle schnelle optische Rückmeldung zum laufenden Programm.
* (langfristig kann man auch überlegen, ob diese/solche Hilfen in der Spielstufe schwer entfallen sollten)

**Comment by nittka** [comment]
Ich schließe das Ticket mal. Insb. die Sonderbehandlung bezüglich "aktueller Werbeblock ist schon geplant oder nicht" macht die Sache nicht nur für die Implementierung unübersichtlich. Schließlich kann es ja auch sein, dass man eine sichere Werbung geplant hat, nun aber noch das Optimum rausholen möchte. D.h. Punkt 1 würde ich verwerfen. Punkt 2 erledigt sich damit. Gegen Punkt 3 könnte sprechen, dass man schon aktiv schauen muss - das geht mit Hover über dem Fernseher oder über dem Werbeblock.
