### ISSUE TITLE
Review Werbeverträge

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1054]
Im Zusammenhang mit dem PR für die Datenbankerweiterung (inklusive neuer Werbeverträge) habe ich mal die bestehende Übersicht der Werbeverträge aus dem Debug-Bildschirm für einen leichteren Vergleich angepasst. Angehängt ist die Liste der Bestandsverträge sortiert nach "normalisierter" benötigter Zuschauerzahl.

[currentAds.ods](https://github.com/TVTower/TVTower/files/13260259/currentAds.ods)

Ich habe noch keine genauere Analyse gemacht, aber schon mal grundsätzlich problematische Verträge markiert:

 Die "billigen" am Anfang werden überhaupt nicht angeboten, vermutlich weil bei diesen nur Verträge ohne Zielgruppe überhaupt zum Zuge kommen. Hier müsste geklärt werden, ob diese Einschränkung entfallen sollte.

Die teuren am Ende müssen meiner Ansicht nach überarbeitet werden, da die Zuschauerzahlen praktisch gar nicht erreichbar sind. Ausnahme dürfte sein, wenn man im Gegensatz zu allen anderen Spielern das gesamte Sendegebiet hat und einen Superfilm sendet. Bei den 1.2Mio Zuschauern, auf denen die Zahlen in der Tabelle beruhen, sind zur Hauptsendezeit schon 60% mögliche Zuschauer hoch. Um dann auf 500K zu kommen, benötigt man eine "unmögliche" Einschaltquote. Und das dann, um 70000 für einen Block zu bekommen - unrealistisch.

Aufgabe wäre dann nochmal, die "Blöcke" ähnlicher Zuschauerzahlen durchzugehen und auf Konsistenz zu prüfen. Bei den Einnahmen pro Spot fallen schon ein paar Ungereimtheiten auf (die natürlich auch gewollt sein können). Bsp: 
* SOS Artritis - "35K Zuschauer" 4 Spots in 3 Tagen gibt 23000 pro Block (Rentner, die relativ viel fernsehen)
* Schniggo - 39K Zuschauer 6 Spots in 3 Tagen nur 17000 pro Block
* ESCAL - 55K Zuschauer 7 Spots in 3 Tagen auch 23000 pro Block

**Comment by GWRon** [comment]
Bei der Betrachtung sollte nicht nur auf Erloes pro Block geachtet werden.

Vertraege mit vielen Spots belegen trotzdem nur einen Kofferplatz. Man kann sich also den zweiten Besuch beim Makler ersparen bzw um einige Stunden verschieben.

Auch koennten manche Vertraege durch geringe Konventionalstrafen strategische Vorteile bringen.

Die Laufzeit der Vertraege sorgt fuer "Druck". Gerade bei denen mit hohen Anforderungen, nur 1-2 Tagen Laufzeit aber mehr Spots als Primetimeslots pro Tag zur Verfuegung stehen.

Auch koennte Werbung ja Einfluss auf Lobbies haben. Sprich mehr Geld bei gutem Standing...oder besseres Image bei erfolgreichem Abschluss...
(Das ist natuerlich noch nicht implementiert)

**Comment by scr0llbaer9000** [comment]
Ich hab mich mit Werbung noch nicht beschäftigt, aber möchte anmerken, dass es bei Mad TV einige absichtliche gewaltige Ausreißer gab.

Es gab etwa eine BP-Werbung, die war 5-6 mal lukrativer als vergleichbare, wollte zwar Liebesfilm, aber sowas kann man managen. Auf die hat man immer gelauert, wenn man schnell durchspielen wollte.

Vielleicht ist 5-6 mal etwas zu krass, aber es ist wohl auch Teil von Spieldesign und Spielpsychologie, nicht immer alles so geradlinig zu gestalten und solche vereinzelten "Schatzsuche"-Gelegenheiten bereit zu stellen.

**Comment by nittka** [comment]
Für gewollte Ausreißer braucht es aber auch ein halbwegs konsistente Basis. Aktuell ist ein Problem, dass der Bonuseffekt für Zielgruppenwerbung sowohl in der Datenbank als auch nochmal im Berechnungscode steckt ("alle Zielgruppenwerbung erzeugt Ausreißer"). Mein Vorschlag wäre daher, zunächst die Datenbankeinträge eher anzugleichen (geht, indem man den berechneten Zielgruppenbonus rausnimmt) und danach dann schaut, welche Ausreißer man (inkl. berechnetem Bonus) haben will. Die können dann in der Datenbank entsprechend angepasst werden.
