### ISSUE TITLE
News thread shouldn't start a new instance before the last instance has ended

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1055]
Okay, maybe there is an issue with (years-) long running news threads after all. Or maybe I just had the wrong expectation, afair it isn't explicitly documented after all if a new instance of a news thread can start only after the last instance of the same thread has ended.

In any case, this has happened during playtesting:

![Screenshot from 2023-11-03 19-59-19](https://github.com/TVTower/TVTower/assets/123826268/e660e4ba-8a40-4205-9ca8-5357f077237f)

The "AvW" news items are from the same thread, the "stellt Antrag" is the first entry, the "wählt neuen Vorsitzenden" is the last entry (after running several years), but it appeared later a few hours later that day, so two instances of the same thread were active at the same time.

I don't know if there ever actually was such a "rule" that two instances of a thread can't be active at the same time, or if there is a problem with such years-long running threads, but my expectation definitely was that there can only be one instance at a time, and I made the news thread intentionally that way. (My) Long-term goal with news items is / should be that if they can't be made variable enough with templating (because the "joke" is too specific), they at least shouldn't show up too often, and I thought making the thread long-running is one way of achieving this.

**Comment by GWRon** [comment]
News for now get made available again if the news events of that genre are "running out". So the "already used" elements are made available again.

We could add a new news flag ... which makes news "unique" until the last news of the thread is created ... BUT: what is the last, what is the first .... ?
News (events) can be triggered by other threads too ... they could even be triggered by two different sources (or "tried to get triggered by two"). 

You will have some "races".


What I suggest is to have - in this desired case - the first successor news making their "ancestors" (at best the "thread starter") no longer available. And the last news (or each "final news" if there are branches) would set the first news as available again. They could even "schedule" it - so the news thread would decide "how often" it is run.

**Comment by nittka** [comment]
I still think, the framework support could be improved here. First, when looking for a new template the threshold for "not used recently" is 4 days which could be raised. TNewsEventTemplateCollection#ResetUsedTemplates only considers the initial template's use time. It really should also consider currently active threads and hide those templates as well.

Jumping across news genres should not be a problem as long as the thread id is the same. I would draw a line (for framework support) at jumping across thread ids (triggering news with different thread ids). For those cases the manual availability effects can be used.

The "bigger problem" is: We need more news templates with variables - e.g. many one-time news without triggered news (which makes writing them harder). Something like "Archaeological sensation in <city>: <somebody> found <something> while doing <something> in <somewhere>..." Given a number of such patterns, news will be more varied automatically. We need to review the existing news. For many a generalization is possible (introducing variables).
We need more seasonal news that will automatically appear only during certain times of the year.
And foremost, we need somebody to dive into this topic. I am not very creative and *we* can't work on all topics simultaneously.

**Comment by scr0llbaer9000** [comment]
> is 4 days which could be raised

does that mean (to achieve my desired behavior without fiddling around with availability) that for now, a thread shouldn't go longer than 4 days (months) in total, or does it mean that there shouldn't be a pause longer than 4 days (months) between news items in that thread?

**Comment by nittka** [comment]
Can't give a definite answer, the first should work but is not desirable. The problem is quite involved, as there are different versions of "active thread" to consider
* a news item is currently available
* a thread was started, no news item is currently available, but a trigger has been fired, so the item will appear in the future

The number of days from above is a "counter" reduced until a fresh initial template (not used for x days) is found. It starts with four unused days (with more news available, this value could be increased).
