### ISSUE TITLE
Effekt modifyAvailability für Programme (und Drehbuchvorlagen)

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1058]
Bislang noch nicht benötigt, aber für Serien mit mehreren Staffeln und Drebuchvorlagen für Fortsetzungen sinnvoll einsetzbar, sollte der Effekt modifyAvailability nicht nur für Nachrichten verfügbar sein.

**Comment by nittka** [comment]
Ich habe einen Prototypen für happen+modifyAvailability für Programme. Allerdings ist das Zielverhalten nicht ganz trivial. Das availability-Flag wird beim Einlesen der Datenbank sowohl für die Lizenz als auch für die Daten gesetzt. Um eine Lizenz verfügbar zu machen, müssen also zwingend beide Flags umgesetzt werden, damit das gewünschte Ergebnis erreicht wird.
Soll die Verfügbarkeit einer Lizenz allerdings zurückgezogen werden, wäre die Frage, ob dafür ausschließlich das Lizenzflag gesetzt werden sollte (falls andere Lizenzen dieselben Programmdaten enthalten).

Außerdem hängen die Effekte aktuell an den Programmdaten (Datenbankeinlesen). Wäre es nicht sinnvoller, das auf die Lizenz umzustellen. Die Auswirkungen beim Vererben von Daten sind mir suspekt.

**Comment by GWRon** [comment]
Das Problem ist ja der Tatsache geschuldet, dass damals eine TProgrammedata einer Lizenz entsprach und in der DB keine Unterscheidung stattfand.

Heute beduerfte es da wohl entweder einer Unterscheidung mittels zweier "sub-Bloecke" (effects_licence und effects) oder einer Moeglichkeit die Lizenzen ebenfalls zu definieren (also Erweiterung der DB).

Ich vermute, letzteres ist der sinnstiftendere Weg, auch im Hinblick auf Lizenzpakete und variierende Lizenzen die nicht dynamisch sondern vordefiniert ausgestaltet werden.
Allerdings muesste da dann sichergestellt werden, dass dann vorher schon automatisch generierte Licences (durch Einladen der "programmes") geloescht wuerden, sobald mindestens eine manuelle Licence in der xml definiert wuerde.
Ist nicht trivial umzusetzen (ausser per "Flag" die die Entstehungsursache definiert).

Ersterss (sub-Bloecke) ist einfach umzusetzen...allerdings "unsauberer"/verwirrender.

**Comment by nittka** [comment]
Der Implementierungsvorschlag ist, dass beim Verfügbarmachen sowohl Daten als auch Lizenz verfügbar gemacht werden - sonst würde die Lizenz nicht verfügbar werden. Beim Entfernen der Verfügbarkeit wird das Flag allerdings nur für die Lizenz gesetzt.
Wenn die komplette Verfügbarkeit entfernen will, könnte man über eine Erweiterung der Effekt-Syntax nachdenken. Neben enable, könnte es ein Tag "includeData" geben, das standardmäßig mit "false" belegt ist. Ist das Feld "true" würden auch die Programmdaten das Flag bekommen und ggf. weitere Lizenzen mit ändern...
