### ISSUE TITLE
Tracking: Speicherfresser in den letzten Dev Versions

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#106]
Die letzten Dev Versionen schrauben den Speicherbedarf kontinuierlich hoch. Während bei der 64bit noch unklar ist, ob sich das nur bis zu einem bestimmten Grad hochschraubt (dennoch auf weniger performanten Rechnern die Leistung merklich abnimmt und das Spiel anfängt zu ruckeln),  lässt sich bei der 32bit Version der Speicher in wenigen Minuten auf über 1 GB hochschrauben. 

Issue überführt aus Discord. ;)

**Comment by GWRon** [comment]
Legacy Compiler: Threads fuer die KI enthalten wohl einen Fehler, tritt nicht beim NG-Compiler (und dessen Libs) auf

NG: Einladen von Spielen erhoeht RAM-Verbrauch
NG: Neues Spiel - Zurueck zum Hauptmenue - Neues Spiel ... erhoeht RAM-Verbrauch auch. Anscheinend werden Spielobjekte nicht korrekt geloescht und duempeln im RAM herum.
