### ISSUE TITLE
Cast preselections

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1065]
As discussed there should be the feature that allows a pre-selected cast for productions.

For one, it might be confusing for a player why a musician should be cast here when the musician is already in the title. Is the female musician to cast a support act?

![Screenshot from 2023-11-21 01-25-36](https://github.com/TVTower/TVTower/assets/123826268/f8230393-37f3-4401-8a56-d288a3ed9e34)

In this example script, the main act "Ivanka Bloomberg" is just a name generated from variables, but we could change that and reference an actually defined musician. That main act musician would then be pre-selected in the cast list and be also read-only, the player can't change it. (But optionally there still can be the additional support act.)

This would be "better" for gameplay "immersion" and "semantics" because that musician and the shows they've been in will carry their history through the game.

Another example would be "Kultur Heute". In TVTower, that's just a one-time show. In Mad TV, it was a show for which a new edition popped up every view days in the auctions. It was more like a live show (always with a 0% rating though). We don't have such a recurring shows mechanic in TVTower, but "Kultur Heute" could be a producible show with Betty pre-selected and read-only. (Though in this special case of course debatable which player should "own" this show, and if that player should then get more Betty love. Or if the "Kultur Heute" script should be available for every player.)

The feature "Einstellungen übernehmen" is already a great progress compared to Mad TV, where it was tedious to cast the same roles for each episode of a series, but it would be nice if the game could also remember globally which roles had been played by which actors and pre-select those roles with these actors (so that it works also across seasons, different films of the same franchise, etc). In this case, the pre-selection should not be read-only of course, the player should still be able to change the pre-selected actor.

Similarly with talk-shows and the like, the game could remember the last host, moderator, reporter etc of an episode of a particular show. Only the guest stars should not be carried over from episode to episode by default.

**Comment by nittka** [comment]
This issue depends somewhat on the new variable implementation, because I would want to make the preselected cast depend on a variable as well (different musicians, different directors...).

**Comment by GWRon** [comment]
> This issue depends somewhat on the new variable implementation, because I would want to make the preselected cast depend on a variable as well (different musicians, different directors...).

The new script expression stuff is next after I finally achieve to complete the stationmap overhaul task :)

**Comment by nittka** [comment]
TPersonProductionJob could get a script/preselect field filled by the database. When a script is created from the template this field could be evaluated (fixed GUID, variable evaluating to a GUID).
The supermarket would have to lock a slot with a preselected cast. Also the expressions would have to allow "cast" for templates in order to reference names.

I am a bit concerned about the current TPersonProductionJob code. When extending the type for a random role, the code for copying and (de-)serialization was not adapted.
