### ISSUE TITLE
[DB] Scripts: studio_size used for min/max

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#1078]
Derzeitiger Code:
```
		If data.Has("studio_size")
			scriptTemplate.studioSizeMin = data.GetInt("studio_size")
			scriptTemplate.studioSizeMax = data.GetInt("studio_size")
			scriptTemplate.studioSizeSlope = 0.5
		Endif
```
Docs:
https://github.com/TVTower/Documentation/blob/master/database_de/scripts.md

Das sollte wohl auf "studio_size, studio_size_min, studio_size_max" ausgebaut werden.

**Comment by nittka** [comment]
Ich glaube es gibt zwei Stellen, an denen die Größe definiert werden kann. In data (wo es nur einen Wert gibt - im obigen Beispiel werden also min und max auf diesen Wert gesetzt). Und dann kann analog speed etc. die Studiogröße auch noch als Intervall definiert werden.
In der Datenbank ist es natürlich nicht sinnvoll, an beiden Stellen zu definieren.

**Comment by nittka** [comment]
Ist schon umgesetzt. Der Min-Max-Block wird um Zeile 1740 nochmal ausgewertet.
