### ISSUE TITLE
[ScriptAgency] Startdrehbücher oft mit Studiogröße > 1

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#1080]
Eventuell sollten Drehbücher am Anfang gehäuft für Studiogröße 1 geeignet sein.

Auch auffällig ist, dass viele Startangebote Drehbücher für Shows mit 100 Produktionen sind, oder Serien (mit Folgen).

**Comment by scr0llbaer9000** [comment]
Wär durchaus wohl gut wenn am Anfang ein größerer Teil der Angebote nur Studiogröße 1 benötigen würde (zumal der Spieler in der Drehbuchagentur die Angebote hier nicht so leicht "austauschen" und durchrotieren kann), aber ab und zu darf 2 oder 3 schon auftauchen zum "Ansporn".

Die 100-Produktionen-Shows sind oft "billig" und für den Anfang durchaus geeignet (ob wirtschaftlich für den Spieler sei dahingestellt).

**Comment by nittka** [comment]
Ich finde es prinzipiell richtig, dass man nicht leicht durch die Drehbücher durchrotieren kann (egal ob am Anfang des Spiels oder später).

Die Frage wäre, woran man festmachen soll, ab wann ein größeres Studio OK ist: Tag 1-10 in 90% der Fälle doch nicht, Tag 11-20 in 60% der Fälle, ab Tag 21 kein Filter? Analog könnte ein zu hoher Preis oder ein zu großer nötiger Cast ausgefiltert werden, da man sich das am Anfang ohnehin nicht leisten kann...
