### ISSUE TITLE
Plötzlicher Imagesprung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1094]
In Testspielen kam es sehr selten (aber nicht nur einmal) zu unplausiblen Imagesprüngen bei einem Spieler (plötzlicher Zuwachs um 40 bis 80 %). Im Log war folgender Text zu finden (unklar, ob wirklich Zusammenhang besteht):
```
[18:33:59] DBG      | TGAMEMODIFIERPUBLICIMAGE_MODIFY.RUN(): increase image for a broadcasting channel not being caught
[18:33:59] DBG      | CHANGEPUBLICIMAGERELATIVE(): Change player3's public image: Sum = 70  ( C:5/5 / T:5/5 / H:5/5 / E:5/5 / U:5/5 / M:5/5 / P:5/5 )
[18:33:59] DBG      | TGAMEMODIFIERPUBLICIMAGE_MODIFY.RUN(): increase for broadcasting channel
[18:33:59] DBG      | CHANGEPUBLICIMAGERELATIVE(): Change player3's public image: Sum = 28  ( C:2/2 / T:2/2 / H:2/2 / E:2/2 / U:2/2 / M:2/2 / P:2/2 )
```

**Comment by GWRon** [comment]
Also die Logeintraege entstehen, wenn der Terrorist ein "anderes Zimmer" erwischt.

`increase image for a broadcasting channel not being caught`
-> sollte fuer Spieler auftauchen, die NICHT am Schildertausch beteiligt waren (5% Imagegewinn)

`increase for broadcasting channel`
-> sollte fuer Spieler auftauchen, die beteiligt waren (aber mutig genug, darueber zu berichten - um den Malus `decrease image for all caught channels` zu mitigieren).

**Comment by GWRon** [comment]
Ich glaube - ungeprueft - der Fehler liegt dort:
(game.publicimage.bmx)
```
	Method ParamConditionsFulfilled:Int(params:TData)
		If Not paramConditions Then Return True

		Local broadcastingPlayerID:Int = params.GetInt("playerID", 0)

		'broadcaster specific conditions
		If broadcastingPlayerID > 0
			'as long as playerIDs are < 10 we simply could check the string...
			Local playerIDs:String = paramConditions.GetString("broadcaster_inPlayerIDs", "")
			If playerIDs and playerIDs.Find(String(broadcastingPlayerID)) = -1
				Return False
			EndIf

			Local notPlayerIDs:String = paramConditions.GetString("broadcaster_notInPlayerIDs", "")
			If notPlayerIDs and notPlayerIDs.Find(String(broadcastingPlayerID)) >= 0
				Return False
			EndIf
```

Erster trigger-Effekt hat `broadcaster_notInPlayerIDs` (aber nicht `broadcaster_inPlayerIDs`) und playerID = 0

damit wird der "if" False sein und nicht durchgefuehrt. Resultat ist: "True".


Kurzum: ich vermute das 
```
			'use playerID of broadcasting player
			data.AddInt("playerID", 0)
```
noch nicht funktioniert.

Entweder muesste also beim Ausfuehren des Triggers die jeweilige SpielerID mitgegeben und interpretiert werden - oder ein Trigger-Effekt fuer jeden Spieler generiert werden.

**Comment by nittka** [comment]
Ich spiele gerade ein wenig rum. Aktuell scheint nur der letzte Spieler, der das Schild verschoben hat, "gefangen" zu werden. Die obige Konstellation konnte ich so noch nicht wieder reproduzieren. Ich gehe mal davon aus, dass die Änderungen relativ zum aktuellen Image bleiben sollen (weniger Gewinn/Verlust, wenn das Image sowieso schon gering ist).
Die Wahrscheinlichkeit für diese Kette ist ziemlich gering (weshalb es wohl auch noch keine Beschwerden gab) - randRange(0,90)<90 für die Standardnachricht, d.h. nur wenn die 90 gewürfelt wird, hat die Polizei überhaupt Anhaltspunkte und es gibt die Imageanpassungen. Sollte das vielleicht auf randRange(0,100) <90 (oder 95) geändert werden?

**Comment by GWRon** [comment]
Ja randrange(0,100) war wohl beabsichtigt. Kam noch nicht weiter zum debuggen, aber bin auch an der Funktion dran - Familie kam aber dazwischen ;-)

**Comment by GWRon** [comment]
Ich denke du musst auch die Werte mit 0.01 multiplizieren - da es ein Multiplikator, kein Summand ist.
