### ISSUE TITLE
Drehbuchautor und erster Schauspieler vertauschen sich beim Uebernehmen der Einstellungen bei Serien

### ISSUE THREAD

**Issue by nsalomon** [TVTower/TVTower#1102]
Im angefügten Savegame vertauschen sich beim Uebernehmen der Einstellungen bei Serien jeweils der Drehbuchautor und der erste Schauspieler.

Im angefügten Savegame gut zu beobachten bei "Mieten, Kaufen, Wohnen - Staffel 2".

1) Im Shop auf eine fertig vorbereitete folge von "Mieten, Kaufen, Wohnen - Staffel 2" klicken, bspw. Folge 2.
2) Vergewissern das der Haken zum übernehmen der Einstellungen gesetzt ist.
3) Auf die nächste Folge klicken. Resultat: Drehbuchautor und erster Schauspieler wird vertauscht.

Disclaimer: Spiele mit modifizierten Daten der aktuellen Version: Originalnamen der Schauspieler und Filme sowie eigene Daten von https://github.com/nsalomon/TVTower-ariksan-DB

[bbgame9.zip](https://github.com/TVTower/TVTower/files/14100737/bbgame9.zip)

**Comment by nittka** [comment]
Das Auffüllen erfolgt nach Berufsgruppen. Allerdings ist die Reihenfolge der Berufgsgruppen beim Besetzen im Supermarkt leicht anders als die bei beim automatischen Übernehmen. In der Liste kommen die Drehbuchautoren vor den Hauptdarstellern, beim Auffüllen kommen sie danach. Dadurch das Vertauschen.

Etwas problematisch ist dieses Vorgehen auch, wenn man an mögliche Serien mit Rollen denkt, wo die Rollen zwischen Haupt- und Nebendarsteller wechseln. Hier würde man erwarten, dass die Rollen immer gleich besetzt bleiben. Soweit ich weiß, ist die "Rollenkonsistenz" allerdings nicht relevant für das Produktionsergebnis.

**Comment by nsalomon** [comment]
Von meinen Beobachtungen glaube ich auch nicht, das die Rollenkonstistenz relevant ist, das ist richtig.
Aber wenn der Drehbuchautor mit Erfahrung als Drehbuchautor als Schauspieler eingesetzt wird und umgekehrt, ist das denke ich schon relevant, zumindest gemäss meinen Beobachtungen.

![Beispiel_Drehbuchautor-Schauspieler-Switch_marked](https://github.com/TVTower/TVTower/assets/325042/9a4bd20b-0e3a-4e09-b786-2c481826860d)

**Comment by nittka** [comment]
Beim direkten Vergeleich wäre ich aktuell etwas vorsichtig. Da spielt noch Zufall mit rein - sowohl beim Produktionsergebnis selbst als auch bei den Zuschauerzahlen der Ausstrahlung. Wirklcih vergleichbar wäre das nur, wenn sämtliche andere Parameter identisch sind (inklusive dessen, was die KI sendet).

Die "Balken" liefern jedenfalls kein eindeutiges Bild (Tempo/Kritik/Zuschauer immer besser in der einen oder anderen Variante).

**Comment by nsalomon** [comment]
In der Tat, Die Attribute der Schauspieler haben 0 Einfluss auf das Produktionsergebnis.
Ich nehme an, das dies als Feature noch in Arbeit ist?

Somit hat der Bug, das bei automatischer Uebernahme der Einstellungen die Rollen vertauscht werden, im Moment zwar keinen Einfluss - ist aber trotzdem Unschön und würde, wenn die Attribute der Personen nicht nur zum Spass angezeigt werden, andere Ergebnisse verursachen.

![Beispiel1](https://github.com/TVTower/TVTower/assets/325042/937c6067-45b8-460a-9dbe-75363120ab27)
![Beispiel1_ergebnis](https://github.com/TVTower/TVTower/assets/325042/085afa47-7c34-4e19-afcd-3e7a6faec2be)
![Beispiel2](https://github.com/TVTower/TVTower/assets/325042/4dfdf2ff-4151-4ff8-9022-a9e045f3f8ed)
![Beispiel2_ergebnis](https://github.com/TVTower/TVTower/assets/325042/92f6a250-82b4-4482-86f5-27bdd75c17b7)

**Comment by nittka** [comment]
Das Balancing bezüglich Eigenproduktionen ist ein komplett separates Thema und sollte nicht in diesem Ticket diskutiert werden. Ich habe einen Reparaturvorschlag bereitgestellt. Der berücksichtigt aktuell auch noch keine Rollen-IDs, wohl aber den pro Slot geforderten "Beruf".
