### ISSUE TITLE
Plötzlicher Senderimage-Reset (mit Spielstand)

### ISSUE THREAD

**Issue by nsalomon** [TVTower/TVTower#1107]
Im angehängten Spielstand wird um 16:00 das Senderimage von MadTV (aktiver Spieler) aus mir unerklärlichen Gründen auf 0 zurückgesetzt.
Spielstand ist kurz vor 16:00.
[Senderimage_16Uhr.zip](https://github.com/TVTower/TVTower/files/14277748/Senderimage_16Uhr.zip)

**Comment by nittka** [comment]
Dieser Bug sollte mit Commit 63453e8a546e5b8c225af5c04702c616c9d271b4 bereits für das nächste Release behoben worden sein. Grund für die Reduzierung des Images ist, dass die Polizei Hinweise für die Übeltäter beim Schilderumhängen gefunden hat. Die zum Zeitpunkt der Bombenexplosion erzeugte Nachricht hat die Reduktion als Wirkung bei der Ausstrahlung der Nachricht. Allerdings war die Wahrscheinlichkeit für den Fahndungserfolg bislang nur 1:90 und der Wert für die Reduktion vor der Reparatur falsch...

Es lässt sich nur mutmaßen, ob das Problem so selten auftrat oder nur nicht gemeldet wurde.

**Comment by nittka** [comment]
siehe #1094
