### ISSUE TITLE
Einkaufslisten können nicht gelöscht werden

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#111]
Im Studio können generierte Einkaufslisten nicht gelöscht werden. Nimmt man eine Einkaufsliste hoch und drückt rechte Maustaste, wird die Liste abgelegt. Ein Löschen ist nicht möglich. 

Der Mülleimer würde sich dafür anbieten, so könnte man das Ablegen mit RM beibehalten und das Löschen mit dem Eimer verbinden.

**Comment by GWRon** [comment]
Rechtsklick ist drin. Eimer kommt noch.
