### ISSUE TITLE
Generic "various-xyz" staff placeholders show up in places where they shouldn't

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1111]
Now this is a baffling one, why do the "various musicians" show up in the cast list?

![Screenshot from 2024-01-18 20-31-48](https://github.com/TVTower/TVTower/assets/123826268/965dd99f-ec62-4df8-927a-2b1faf71bdca)

And where does the idea come from they're a director?

They're set with `castable="0"`.

It's very very rare that this happens. Maybe the language files "overwrite" the castable value? Or other weird explanation: Could it be that the name generator takes hints from such entries? If so, non-castable entries should be ignored.

Another place where these show up more frequently now is in news items. E.g.:

> Bald im Kino: John Doe in „Blablabla“. versch. Stimmkünstler ist schon voll des Lobes für den Film.

(Not "only" "my" fault, entries like "common-amateur-actors" existed before, so this happened probably before too, just less frequently.)

So I guess we need a flag to know that these entries should be ignored when constructing these news messages. Alternative dirty hack is to check if the ID starts with `common-` or `various-` or `unnamed-`.

**Comment by nittka** [comment]
This bug was introduced when refactoring the database from bookable to castable. The castable-flag is set correctly, but the filters for selecting the persons actually look only on the bookable flag and ignore the castable flag.

I must admit, I did not expect that and did not test too thoroughly. There are not too many fictional persons that are not castable...

**Comment by nittka** [comment]
In my opinion, it is not worth the effort. With the bug-fix the "various"-persons cannot be casted. For movies in the database they should not be used used as actor one (or two). And in the latter case that movie would still have to be selected for news AND select the only one of five descriptions that uses both actors.

For the filtering logic see https://github.com/TVTower/TVTower/blob/033079ba195fe412b90d4b0eda40c40b5485b21f/source/game.newsagency.base.bmx#L520 and following.

**Comment by scr0llbaer9000** [comment]
> For movies in the database they should not be used used as actor one (or two).

That's the whole point these items exist, to show at least *some* information when there's no actors worth mentioning, for informational purpose that the field is not blank through error.

**Comment by nittka** [comment]
(various-actors will not be mentioned in news)
