### ISSUE TITLE
antennaStationsRequireBroadcastPermission bei jedem Spielstart neu berechnen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1125]
Ob für Antennen eine Sendegenehmigung benötigt wird, muss bei jedem Spielstart neu berechnet werden, nicht nur beim initialen Laden der Karte.
* neues Spiel 1985 (Sendegenehmigung nötig) -> OK
* Hauptmenü
* neues Spiel 2005 (Sendegenehmigung nötig) -> nicht OK

Umgekehrt genauso.

**Comment by GWRon** [comment]
Das ist doch derzeit rein vom "Standard-Antennenradius" abhaengig?

Und das wird mit jedem Einlesen der Senderkarte berechnet - sofern `If station And antennaStationRadius = ANTENNA_RADIUS_NOT_INITIALIZED`.

Wenn Du das "immer" willst, dann braucht ja an sich nur bei einem "Neuem Spiel" der Wert wieder auf `ANTENNA_RADIUS_NOT_INITIALIZED` gesetzt werden.

Falls es das ist, dann gerne einfach die Aenderung durchfuehren und im Master einspielen.

**Comment by GWRon** [comment]
Ups, da hatte ich master noch nicht aktualisiert und mich schon gewundert, wieso der Code noch "anders" aussah, als in meinem Kopf :D ...
