### ISSUE TITLE
Anpassung Antennenradius bei geladenem Spielstand

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1127]
Wegen der neuen Kartenlogik passen die Radien der Antennen aus alten Spielständen nicht. Aktuell wird beim Laden ein fester Radius gesetzt. Das dürfte insb. für Spielstände mit späten Spieljahren schiefgehen, bei denen der Ausgangsradius schon deutlich größer war.
Hier muss eine dynamischere Aktualisierung gefunden werden. Eine Option wäre neu = max(alt+x, 50), wobei ein geeignetes x gefunden werden muss.

**Comment by GWRon** [comment]
Da jede Antenne "field built:Long" hat - man koennte also eine Tabelle mit Jahres"multiplikatoren" heranziehen und das irgendwie nutzen (klappt aber nur, wenn man nicht dadurch in einen Ballungsraum "reingeraed").

Auch koennte man sich um die persistierten "Reach"-Felder kuemmern ... sie also nutzen um einen Radius zu ermitteln, der ungefaehr diesen "Reach" wieder ergibt.

**Comment by nittka** [comment]
Ich wäre hier für eine 80%-Lösung (für das Einlesen der Spielstände der Vorgängerversion). Für ein Spiel ist der Antennenradius ja konstant. Wenn man also pro Spielstand eine Radiusdifferenz ermittelt und draufaddiert, sollte das reichen. Die tatsächlich problematischen Werte sind die Startjahre zwischen 1990 und 1997.

**Comment by GWRon** [comment]
Dazu musst Du aber die Bevoelkerung "fuers Jahr" kennen.

Mein anderer Ansatz (den ich gerade umsetze) waere nun gewesen, durch alle Antennen durchzugehen und deren Radius anpassen, bis der alte Reach-Wert wieder erreicht wird.
Man haette dann evtl variierende Radien (durch die neue Bevoelkerungsdichte - und evtl angrenzende und nun erreichte "Ballungsgebiete"). Aber ok.

**Comment by nittka** [comment]
Ich habe auch nichts gegen einen alternativen Ansatz. Es wirkt nur seltsam, wenn in einem neu gestarteten Spiel immer alle Antennen dieselbe Reichweite haben und nach dem Laden eines Spielstands die Bestandsantennen plötzlich unterschiedliche Radien haben. Auch könnte durch eine komplexere Logik, in der die Überlappung zwischen benachbarten Antennen nicht berücksichigt wird, das Endergebnis viel schlechter für den Spieler sein: Antenne hat zwar die Reichweite von vorher, es gibt aber riesige Überlappungen, die zu höheren laufenden Kosten führen...

Daher wäre ich eher für eine kleine Lösung - (Beschwerden wird es ohnehin geben, egal wieviel Aufwand man reinsteckt). Die Holzhammermethode wäre natürlich, gar keine alten Spielstände zuzulassen.

**Comment by nittka** [comment]
Ein anderer Ansatz wäre auch noch, die Radien überaupt nicht anzupassen! Bzw. nur so, dass der alte Radius (pixel) in Kilometer (?) umgerechnet wird. Die Überlappungen wären dann identisch zu vorher.
Wenn die Kaufpreise und laufenden Kosten ordentlich angepasst werden, sollte es sich auch vernünftig weiterspielen lassen.

**Comment by GWRon** [comment]
Wenn wir nur den Radius "konstant" vergroessern, verlieren einige Sendemasten ordentlich an Reichweite (da die neuen Bevoelkerungsdichtewerte "korrekter" sind - und da einfach niemand gross wohnt :D).
Andere bekommen ordentlich Zuwachs, weil sie ploetzlich Ballungsgebiete erreichen.

Ich denke, wenn meine Methode "ungefaehr funktioniert", sollten wir die nehmen - und wem das dann doof aufstoesst, der kann gerne ein neues Spiel starten.

**Comment by GWRon** [comment]
Alt (v0.82):
![image](https://github.com/TVTower/TVTower/assets/2625226/aa392deb-0956-4269-a9d1-faa1710f3e46)

Konvertiert:
![image](https://github.com/TVTower/TVTower/assets/2625226/57492e9a-ca14-4d4a-9370-84951228dd2a)

Das ist ein Extrembeispiel, weil einfach in der Gegend von Bayern ... wenig Leute wohnen.
Die Konvertierung ist gerade beim Radiuszuwachs gedeckelt auf "originalRadius + 28"

**Comment by GWRon** [comment]
![image](https://github.com/TVTower/TVTower/assets/2625226/ccee5e88-636f-46ee-9836-d12812fe2b06)
Aus einem anderen Speicherstand ... Klar, hoehere Ueberlappungen, aber "besser als nix" denke ich.
