### ISSUE TITLE
Performanceanalyse neue Kartenlogik

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1131]
In den Hochgeschwindigkeitsspielen gibt es bei mir schon in frühen Tagen Zeitruckler. Früher kam das erst später im Spiel, wenn es mehr Antennen und Filme bei den Lua-Spielern gab. Vielleicht gibt es hier noch "Caching"-Potential.
Ich habe noch nicht analysiert, welche Berechnungen ursächlich sind.

**Comment by GWRon** [comment]
An sich sollte weit weniger berechnet werden und es dadurch auch kaum zu Rucklern kommen - die Berechnungen sollten um mehrere 100% schneller sein.

**Comment by GWRon** [comment]
Hast Du hierzu Neuigkeiten beizutragen?

Die CPU-Last im KI-Schnellspiel (Speed 14400) liegt bei mir auf etwa gleichem Niveau wie die v0.82 vom Dezember. Die Lastspitzen fallen jetzt geringer aus und die CPU-Last des Prozesses (laut "top") liegt unter v0.82 (75 statt 80%, also nichts "bemerkenswertes").

**Comment by nittka** [comment]
Ich habe die letzte Woche gar nichts machen können. Bei Neuigkeiten melde ich mich. (Auf meinem Entwicklerrechner ist um 5000 die maximal möglich Geschwindigkeit überhaupt, ansonsten schaffen die LUA-Spieler überhaupt keine aussagekräftige Programmplanung mehr).

**Comment by nittka** [comment]
... wobei zu beachten ist, dass ich für die Schnellspiele ja Multithreading deaktivieren muss, da sonst innerhalb kurzer Zeit Segmentation-Faults auftreten (praktisch nie später als Tag 20, normalerweise deutlich davor).

**Comment by nittka** [comment]
Nochmal mit dem aktuellen Stand probiert und mit letztem Releasestand verglichen (Schnellspiel 3600 mit Multithreading). Die kleinen Ruckler früh im Spiel (Beobachtung der Uhr im Interface) gab es auch im alten Stand schon. Und sie verschwinden auch nicht vollständig, wenn sämtliche KIs deaktiviert werden.
Ich mache das Ticket zu.
