### ISSUE TITLE
Yellow indicators disappear for the target day with live shows scheduled for 23:00

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1151]
Probably long-standing bug previously undiscovered, here the check towards midnight seems to be going wrong:

	<programme id="f9d119e7-7875-475a-97b8-300cdc7ed3cd" product="1" licence_type="1" creator="9551" imdb_id="tt0728164" comment="general imdb_id: tt0103569 | TODO: Maybe could be a daily format once that feature is available">
		<title>
			<de>The LateNight Stage with [0|Full]</de>
			<en>The LateNight Stage with [0|Full]</en>
		</title>
		<title_original>
			<de>The Tonight Show with Jay Leno</de>
			<en>The Tonight Show with Jay Leno</en>
		</title_original>
		<description>
			<de>Debüt des Nighttalks mit Kultmoderator [0|Full]. Diesmal zu Gast: Schauspieler und Sänger [1|Full], der gern mit Frauen über Sex nur redet und die guten alten Western-Zeiten wieder herbeisehnt.</de>
			<en>Debut of the night talk with cult presenter [0|Full]. This time's guest: actor and singer [1|Full], who likes to just talk with women about sex and who longs for the good old times of the Western.</en>
		</description>
		<staff>
			<member index="0" function="8">c479fc10-22f8-4289-8889-6495f91bf4f0</member>
			<member index="1" function="64">cd9d01a8-11b2-4811-8ca0-25f138881fa4</member>
		</staff>
		<groups target_groups="6" target_groups_optional="24" pro_pressure_groups="0" contra_pressure_groups="0" />
		<data country="USA" distribution="2" maingenre="103" subgenre="301,100" flags="1" blocks="1" price_mod="1" />
		<releaseTime year="1992" day="5" hour="23" />
		<ratings critics="55" speed="50" outcome="55" />
		<modifiers>
			<modifier name="topicality::age" value="8" />
			<modifier name="topicality::notLive" value="0.25" />
		</modifiers>
	</programme>

~~I can't place this live show in the scheduler.~~ The yellow indicators are not displayed for the target day with live shows scheduled for 23:00.

 When I change the `releaseTime` `hour` from 23 to 22 it will work fine.

**Comment by nittka** [comment]
To check: does this also happen for scripts with a live time at 23:00.

**Comment by nittka** [comment]
Could not reproduce this with setting Ariane-start to release time 1985 day 1 hour 23 no matter if it was one or two blocks long. Placement was possible. Also could not reproduce this with the above definition. Are you sure, you did not try placement on the wrong day?

**Comment by scr0llbaer9000** [comment]
You're right in that the problem is something else. I relied on the yellow markers, but they are the problem. They are gone on day 5:

https://streamable.com/6n7sfq

**Comment by nittka** [comment]
I noticed that as well. The markers do not cover the entire time until the release.
