### ISSUE TITLE
Is target_groups_optional even evaluated?

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1152]
The docu says the XML attribute `target_groups_optional` means "möglicherweise verwendete [Zielgruppe](https://github.com/TVTower/Documentation/blob/master/database_de/main.md#Zielgruppe)". It's not really clear what that means, but I *think* I read somewhere else that it's supposed to be just an additional, albeit weaker form of the `target_groups`. Though when looking at the code, it seems it is ignored entirely?

		'=== GROUPS ===
		Local nodeGroups:TxmlNode = xml.FindChildLC(node, "groups")
		data.Clear()
		If Not _programmeLicenceDataGroupsKeys
			_programmeLicenceDataGroupsKeys = [..
				"target_groups", "pro_pressure_groups", "contra_pressure_groups" ..
			]
		EndIf
		xml.LoadValuesToDataCSK(nodeGroups, data, _programmeLicenceDataGroupsKeys)
		programmeData.targetGroups = data.GetInt("target_groups", programmeData.targetGroups)
		programmeData.proPressureGroups = data.GetInt("pro_pressure_groups", programmeData.proPressureGroups)
		programmeData.contraPressureGroups = data.GetInt("contra_pressure_groups", programmeData.contraPressureGroups)

Also, given that it is implemented, it isn't really clear how to use this. To maximally boost a certain audience, can it be specified in both parameters, `target_groups` *and* `target_groups_optional`? Or should it be handled more like either-or?

**Comment by nittka** [comment]
I have checked the database code. The documentation is indeed wrong. I assumed that the target_group syntax/semantics is the same for programmes and scripts, which is not the case.
The optional variant is available only for scripts (and programme uses groups whereas script uses group). When an actual script is created from a script template, all groups from target_groups will be used as well as a random subset of the optional target_groups.

**Comment by nittka** [comment]
This also means, that the current database contains "syntax errors" the groups-tag is only supported for programmes. For scripts the target groups are read from the data-tag.
This does not affect the targetgroupattractivity-Tag.

**Comment by GWRon** [comment]
"_optional"-elements (there should be one more in the database files) are always a "random subset"
![image](https://github.com/TVTower/TVTower/assets/2625226/3de6ff15-f5c0-4484-82d2-6d5e13bfa9aa)

A bit derailing now - but dunno if we also should think about being able to modify the chances to choose one optional one (currently fixed 25%) and if it should have some kind of "limit". For now it has a 25% chance for each element - so "bigger lists" will have "bigger subsets" (most probably :D) while this might not be what people want. 
You cannot eg simulate "choose ONE/TWO/X of the subsets" (this should be rather "easy" to implement - but dunno if it is worth to do so).

**Comment by nittka** [comment]
As long as the general balancing for scripts (outcome wrt. db values and selected cast etc.) is not addressed, I would not invest here.

As the current database values for target groups in scripts are not evaluated at all (as they are in the ignored groups-tag), I would propose to rename the attributes for scripts
* target_group -> target_groups
* target_group_optional -> target_groups_optional

**Comment by scr0llbaer9000** [comment]
ah, now it kinda makes sense

**Comment by nittka** [comment]
Database and database import are fixed, update of the documentation and a new editor version will follow shortly.
