### ISSUE TITLE
add Polish Person generator

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1159]
In #1156 Polish translation were added. Those would have required a Polish person generator which does not exist, yet. See TheRob-Script-Com-EngeloderBengel in therob.xml. The first name in the title is fixed instead of generated.

**Comment by GWRon** [comment]
I thought of extending the person generator to also pass in a kind of "age" parameter - not in the sense of the actual age, but the "name age".

In German we have decades for certain names. So 80s have different "names" than 90s etc.
Of course we for now should not think of splitting it that far. But maybe we should at least split between "common for older people" and "common for younger" ones.
I want to avoid that we create 20 year old females named "Ehrentraud" or 90 year old "Ben" (they would more likely be Benjamins then...).

Dunno if it makes sense to group things here already (in young/old/all).

**Comment by pauldim** [comment]
If you need Polish names I can take care of that.

**Comment by GWRon** [comment]
You can collect that information here if you want. 

If we come to some conclusion about a potential split regarding "age groups" of names then we could already split them accordingly here.

To repeat myself you often need names for certain ages. The name of a teenager differs to the one of an oldie.
But it already can differ when playing 1985 and 2015... Albeit not so much as when comparing 1920 born and 2000 born.
This becomes especially interesting for fictional programes requiring fictional casts...

**Comment by GWRon** [comment]
@pauldim 
I set up some generator and these are some sample names:
```
-------
country: pl - male
-------
Oskar Pietrzak
Mateusz Witkowski
Arkadiusz Chrzanowski
Wiktor Walczak
Michał Malinowski
Franciszek Wojciechowski
Marcel Kowalczyk
Jacek Mikulski
Aleksander Marciniak
Franciszek Nowicki
Piotr Antczak
-------
country: pl - female
-------
Aneta Chrzanowski
Małgorzata Adamski
Katarzyna Wiśniewski
Grażyna Brzeziński
Gabriela Dudek
Weronika Wróbel
Dorota Głowacki
Teresa Szczepański
Zofia Adamczyk
Dominika Marciniak
Wiktoria Dąbrowski
-------
```

Do they sound OK?

**Comment by GWRon** [comment]
#1163 should resolve this.
