### ISSUE TITLE
Änderungen in den Drehbüchern werden nicht übernommen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#116]
Von Rauxelerritter
https://www.gamezworld.de/phpforum/viewtopic.php?pid=89018#p89018

## Änderungen in den Drehbüchern werden nicht übernommen

Ich hatte ja schon vor mehreren Wochen daraufhin gewiesen, dass bei Serien die Beschreibung der Gesamtserie nicht übernommen wird. Es erschien immer die Originalbeschreibung. Bei den einzelnen Folgen hat die Änderung funktioniert.
Jetzt scheint sich das Problem auch auf Filme übertragen zu haben. Ich habe einen neuen Spielstand gestartet (Beginn 1980) und versucht eine "Reportage aus dem Sendegebiet" zu verändern. Der neue Titel "Ist der NATO-Doppelbeschluss notwendig?" wurde übernommen, die Beschreibung der Reportage allerdings nicht.

Ich habe dann meinen Langspielstand (Tag 159) in der neuen Version geladen. Das hat zunächst prima geklappt. Als dann allerdings eine gedrehte Komödie "Sister Act 1" fertiggestellt wurde, erschien sie im Archiv mit dem Titel "Engel oder Bengel" und mit Originalbeschreibung.

**Comment by GWRon** [comment]
Wenn in der Eigenproduktionsplanung umbenannt/umgeschrieben wird, zeigt derzeit das Datenblatt (links in der Liste ueber den Eintrag gehen) noch die alten Werte an...

**Comment by GWRon** [comment]
> Ich spiele seit ein paar Tagen den aktuellen Dev-Patch! Dabei ist mir Folgendes aufgefallen:

> Ich habe mir das Live-Drehbuch für das Frühstücksfernsehen gekauft und produziert. Ich konnte 4 Einkaufslisten bekommen. Die Veränderungen des Drehbuchs wurden allerdings nur bei den ersten beiden Folgen übernommen. Folge 3 und 4 wurden mit Originaltitel produziert.

> Ähnliches ist mir bei der Serien-Produktion aufgefallen. Ich habe die Musik-Show mit 5 Folgen produziert. Im Supermarkt lief noch alles glatt. Allerdings als die erste Folge fertig war, erschien die Gesamtserie mit dem Titel der ersten Folge im Archiv.. Auch die Serienbeschreibung war nun die Beschreibung der 1.Folge geworden. Seltsamerweise wurde aber beim Hinweis, dass die Folge nun zur Verfügung steht, der neue Serientitel korrekt angezeigt.

> Die weiteren Folgen schlossen sich dann allerdings ohne Komplikationen an.

Quelle: https://www.gamezworld.de/phpforum/viewtopic.php?pid=89063#p89063

**Comment by nittka** [comment]
Im aktuellen Master-Stand ist es so, dass bei einer Serie nach dem Ändern von Titel und Beschreibung im Supermarkt diese Werte in der Auswahlliste links erscheinen.
Klickt man für dieselbe Folge den Ändernbutton erneut an, erscheinen in den editierbaren Textfeldern für die Folge die vorherigen Werte. D.h. beim erneuten Speichern würde man die bereits gemachten Änderungen wieder kaputt machen.
