### ISSUE TITLE
Some live formats appear too early / always, especially if a relative releaseTime with no specific time slot is set

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1166]
So for example this show "Die Hellseher" is available already in 1985, although it is configured as `country="D" year="1999" distribution="2"`:

![Screenshot from 2024-07-27 08-31-59](https://github.com/user-attachments/assets/23b91aec-40a4-4ffa-afdc-21c843c3e8b6)

Note that the year is missing in the info box too.

Furthermore and especially, I've been intending to change the configuration of some shows (esp. call-in-shows) to be actually live-shows, and give them relative dates so the next one would pop up every few months while the game progresses. I do not specify a time slot because it should be fully up to the player.

For example, changing "Die große Verarsche-Show" to:

	<data country="D" distribution="2" maingenre="0" subgenre="" flags="129" broadcast_limit="1" broadcast_flags="512" licence_flags="36" blocks="2" price_mod="0.9" />
	<releaseTime year_relative="1" day="5" />

Or "Ein Päuschen zum Gewinn" to:

	<data country="D" distribution="2" maingenre="0" subgenre="" flags="129" blocks="1" broadcast_limit="1" broadcast_flags="512" licence_flags="36" price_mod="0.85" />
	<releaseTime year_relative="2" day="7" />

The `broadcast_flags` is set to 512 ("Always Live") for these cases when no specific time slot is desired as the docu says.

The effect is that these shows will be available at the beginning of the game and not only after a few months as configured, often clogging the auction view on day 1, replacing more "important" and "interesting" live shows that have actually scheduled dates and time slots.

Shows that *do* have a specific time slot, e.g. changing "Talk um 10" to a live show at actually 10 pm but now with a relative date, *do* work as expected.

Another general issue with these live-when-scheduled shows (broadcast flag 512) is that they lose "Aktualität" even when they haven't been broadcast yet. It's maybe a more complex issue to discuss, but I feel it's okay that when no player picks them up they can linger around in the film agency arbitrarily long with max "Aktualität".

**Comment by nittka** [comment]
I guess there is a gap between the intention of the always-live flag and the usage described above. Originally, always live was introduced for custom productions, so that the show you pre-produce is live whenever it is broadcasted.
With an already existing licence always-live makes less sense - are there existing database entries or are you just starting to introduce them?
I guess, simply increasing the attractiveness is no workaround, as that has effect on the reruns as well...

Not showing the year for a always-live programme that has not been broadcasted is intended - as it is not clear when the first live performance will have happened. However, I am not sure, if the year is set correctly, once it is not live any more.

If we really want to support always-live programmes (and not only script templates) in the database, not respecting the release date (earliest time, it can be bought) and loss of topicality are bugs.

**Comment by nittka** [comment]
One bug is in TProgrammeData#isAvailable() and a TODO is present as well.
The alwaysLive-Case basically assumes that it is a custom production and does not check for the release date.

**Comment by nittka** [comment]
If you can compile yourself, could you check whether removing line 1835 (`If HasFlag(TVTProgrammeDataFlag.PAID) Then Return True`) in game.programme.programmedata.bmx fixes the issue?
The comment there states that paid programmes are kind of life (and therefore always available, which is not correct).

**Comment by nittka** [comment]
If relative release dates work for paid programmes, what would be the motivation to make them live as well. Is that still necessary?

**Comment by GWRon** [comment]
What do you put in question exactly?

A relative release date allows to define "when something is produced" (in this case it might be more a "invented/created/thought of/written").
An "availability" would be a bit "different". It allows to limit the "usability" (eg the programme was on the "German Index" and not usable in this "form/shape", or some legal issue disallowed broadcasting it for a decade or or or). So availability is simply "can I use it NOW" while the release date states "from when on it is theoretically usable".

Live programme is "always live" (with the approbriate flags) or it is "live in that moment" (eg on day 4 it is live, from then on it is live on tape... - eg concerts)

**Comment by nittka** [comment]
Note that up to now, the release date of a paid programme had a different meaning than for other programmes
* for isReleased() and hence typically available in the movie angency the date was completely ignored
* for maxTopicality it should also have been ignored, as the age factor set to 0

With the proposed change, a later release date would exclude the programme from the movie agency until then. Without the live flag it should still have no impact on maxTopicality (number of broadcasts only counts). With the combination of paid and live we get a new case that has to be checked wrt. maxTopicality. Both flags (paid and alwaysLive) seem to have a similar intention - high interest in the first broadcast, much less in the later ones, so the question is. What additional effect should be achieved by specifying both.

**Comment by scr0llbaer9000** [comment]
> If relative release dates work for paid programmes, what would be the motivation to make them live as well. Is that still necessary?

Call-In is, in practice, always live.

Ronny recently told me that the Call-In-Feature was developed before the Live feature, hence we have "outdated" entries in the database that are flagged as Call-In but not live.

Although "Paid Programme" does not necessarily imply Call-In, all examples we have in the database so far are described as Call-In-Shows.

Call-In-Shows *have* to be live, and also they can't rerun (otherwise the audience would not realize it's not live and call in again).

So I made changes to reflect that. To make up for the lack of reruns I created additional screenplay-script versions of the formats we have. The first programme format will then act as a kind of "pilot", to "seed" the staff (to allow them to gain some experience) and to trigger the availability of the screenplay-script.

**Comment by GWRon** [comment]
The call in shows were created with an "always live" aspect in mind.

Having to do this via "custom production" is a bit too tedious for all these cheap call in things.

So the idea is to have a licence you buy but each broadcast is simply "produced live on demand" (always live). It is produced "externally" (3rd party company) and they just cut their share from the earnings (not visible to the players...we just see a share we get per thousand viewers).


Just to not miss the idea I better note it down here: we could think about randomizing attributes (a bit) right before broadcast logging in...so on "starting the live production". This way the broadcast will be different each time (good riddles, funny moderator, nice selected clothes of the hosting men/women...)

**Comment by nittka** [comment]
... But with this intention (each broadcast is a live one, again), the current entries don't make sense either. You buy a series with three episodes that have a fixed title and description. Even if the attributes are randomized before the broadcast, the data sheet information about number of broadcast and topicality do not fit.

A game internal script produced by a game producer would be an option. But of course, currently you could not buy the entire show and get each new production automatically, as you would with a 100 productions script.

**Comment by scr0llbaer9000** [comment]
> because paid programmes are implicitly treated as always live

In reality that's not necessarily true though. A programme configured as paid but not live could mean it's Teleshopping (no examples for that in the data yet). People can call, you get $$$ per viewers, but it's not live as no interaction between show hosts and callers is necessary. Also ads placed as an Informercial implicitly means flagged as paid programme but not as live, in my point of view.

> programmes are listed in the call-in category

> programmes are listed in the live category

just tested it (without the latest code update though), live call-ins are still listed in the call-in category.

> So what would you want to achieve by combining the flags?

My motivation was, largely, just "semantic", I thought it just was an underdeveloped feature / oversight that these call-ins were not flagged live, as the live feature hadn't been developed yet at that time. And I think the live flag really communicates things to the player better in a visual way, with the yellow marker etc...

> you coud simply increase the quality attributes

I don't care much about that. The existing entries are already rated quite low, and I guess the live flag won't make too much difference.

> how about production limit 100, one broadcast only

I don't have them currently in that 100 show format, because *that* would make it too easy for the player I *guess*, you have to find them in the script agency each time.

**Comment by nittka** [comment]
Even with these arguments, I am not sure I want to open that bottle. Do we really want to be able to distinguish call-in and teleshopping in the database (with the current state paid=call-in, ads as programme=teleshopping).
A thorough review of the impact of the live-flag would be necessary (as well as a discussion of the intended behaviour). In particular the automatic removal of the always-live-flag will have to change.

If the current intention of the paid-flag is implicitly always-live (even on "reruns"), why not just add the yellow markers when the paid-flag is present?

**Comment by GWRon** [comment]
I am with @scr0llbaer9000 about call-in not always having to be "live". Just think about eg "Wer wird Millionaer" and these "call now and have a chance to win...".


Yet these shows only have this call-in feature on the first broadcast.

So similar to "live" and "always live"  this could become some kind of "paid" (paid only on first broadcast ...so live quiz shows etc) and "always paid" (not removed after first broadcast...this would be more the teleshopping stuff).

**Comment by scr0llbaer9000** [comment]
Ok, the new behavior with the changes I had in mind can now be tested (among other things). https://github.com/TVTower/TVTower/pull/1168

> Having to do this via "custom production" is a bit too tedious for all these cheap call in things.

Yes I know, but I guess the feature that an "external" program can periodically "respawn" (kinda like the screenplay-scripts) won't come too soon, so I took the pragmatic route. `;)`

> "Wer wird Millionaer"

What? That's a quiz live show, not a call-in show, as far as I know. `;)`

**Comment by nittka** [comment]
We have the decision, that a distinciton between live and non-live paid programmes should be made. Now, we have to agree on the intended behaviour (and I am not talking about quality modifers or max-topicality, yet)...

* paid + not live: additional money for call in only on the very first broadcast but the the paid-flag remains
* paid + live + not always live: does not really make sense (to me, the exact live time would have to be specified, can you call in, if the broadcast is not live?) - should be prevented
* paid + live + always live: additional money on each broadcast, live flag is not removed on broadcast (next one is always live, again)

**Comment by GWRon** [comment]
`paid + not live`
For me that is simply some pre-recorded "teleshopping" (like all these early in the morning shows some years ago ... there they sell kitchen tools, "super cleaners" etc)
-> they always give you money on each broadcast, but they are not live (no live benefit), their "topicality" should get lower as with other programmes. I would simply have these programmes with a "broadcast limit" (refilled after selling it) to avoid sending them over and over


`paid + live + not always live`
Yes, simplified this is `paid + live` which means this is a live programme which earns money via audience during its broadcast. "live" can mean it has a specific broadcast date (scheduled...) or it is simply live "on request" (just think of these "quiz"-shows on the famous "9-li..." channel years ago). You would simply put such a programme somewhere and it is "produced on the fly" (no custom production needed).
NORMALLY I would even request ("introduce") fixed "costs" per broadcast - so that you need to think before broadcasting a 20.000€-per-block-broadcast at 3:00 in the night.

So in this case I do not distinguish between `paid + live` and `paid + live + always live`. The `always live` would be identifieable by NOT having any broadcast time constraints. But if we cannot distinguish that easily, a "flag" could help.

OK I think we could use the "always_live" flag too ... for things requiring a "custom production" (so not "on request/broadcast" but something like big shows requiring pre-production etc). Of course the "naming" of the flag could be different then...

**Comment by scr0llbaer9000** [comment]
Moment, einen Schritt zurück, so weit ich mich erinnere, hatte sich doch die Bedeutung für "Always Live" mal geändert.

Man *muss* "Always Live" *immer dann* setzen, wenn man keine genaue Ausstrahlungsstunde verlangt. Eigentlich bedeutet das Flag "live when scheduled". Stand heute ist, wenn es nicht gesetzt ist und auch keine genaue Ausstrahlungsstunde, dann ist der Live-Termin 0:00 Uhr, so weit ich mich erinnere.

Es bedeutet eben *nicht*, dass eine Wiederholung auch live ist. Stand heute ist der Live-Marker im Programmplaner nach der ersten Ausstrahlung dann auch weg, auch wenn das "Always Live"-Flag gesetzt ist.

Für mich ergibt die frühere Bedeutung von "Always Live" auch allgemein keinen Sinn. Es gibt nur eine Instanz einer Sendung, eine "Wiederholung" sollte nicht für das fehlende Feature einer neuen Edition herhalten. Eine neue Edition ist für mich eine neue Sendung, die man entweder selber erneut produzieren muss oder als neues Feature irgendwann extern neu geliefert wird.

Alle live Call-Ins hab ich wie gesagt nun so konfiguriert, dass man sie nur einmal senden kann. Teleshopping-Beispiele gibt's bisher keine, aber wie die Ad-Dauerwerbesendungen dürfen die "always paid" sein.

Es verhält sich eigentlich alles bereits so wie gewünscht, ohne dass man am Code was ändern müsste (jedenfalls dachte ich das), bis auf den Bug im OP.

**Comment by nittka** [comment]
Wenn ich mich richtig erinnere, ist es nicht ganz so wie beschrieben. Die Bedeutung des Flags "Always Live" hat sich nicht geändert. Es wurde neu eingeführt, um einen variablen Live-Termin zu ermöglichen - die erste Ausstrahlung ist live, egal wann sie erfolgt; danach ist die Sendung immer eine Wiederholung.

Paid in der bisher verwendeten Variante ist mir wie oben beschrieben ein Dorn im Auge; zusätzliche Bezahlung bei jeder "Wiederholung" ist zu gut. Wenn die Datenbank so geändert wird, dass paid-Programme nur einmal ausgestrahlt werden dürfen, bevor sie zurück in die Agentur gehen, finde ich das genau richtig. Man kann die Lizenz dann ja wieder kaufen und dann wieder neu verdienen. Und eigene Call-In-Produktionen können ja analog anderer Shows auf hohes Limit bei den möglichen Produktionen aber einmalige Ausstrahlung umgestellt werden.
(Ich kann auch mit dem völligen Verschwinden nach einer Ausstrahlung leben, mit dem Zurücksetzen des BroadCastLimit bei Rückgabe in die Agentur hätte man aber sowas wie das "alte paid+always live Feature" mit Kosten für jede Ausstrahlung: es ist (annähernd) keine Wiederholung sondern eine neue Sendung, mit der man wieder Geld durch Anrufe verdient, aber man muss selbst für jede Ausstrahlung Geld in die Hand nehmen, weil man die Lizenz neu kaufen muss).

Was ist der Bug im OP - die nun behobene Problematik mit dem Erscheinungsjahr?

Was ggf. angepasst werden muss wäre die Berechnung der Max-Topicality. Die geht aktuell nach Anzahl der Ausstrahlungen; aber in der Annahme, dass man nicht nur eine Ausstrahlung machen darf.

@scr0llbaer9000: Betrachtest Du dieses Ticket damit als behoben?

**Comment by nittka** [comment]
Ich denke, das Missverständnis rührt eher daher, dass das paid-Flag mit always-live in Verbindung gebracht wurde. paid und live haben erstmal überhaupt nichts miteinander zu tun.
Die Unterscheidung zwischen always-live und always-live-on-first-broadcast ist meiner Ansicht nach auch nicht nötig. Eine einzelne Sendung (gekaufte Lizenz) KANN nicht zweimal live ausgestrahlt werden. Das wäre eben nur die Billig-Variante für eigentlich nötiges mehrfaches Produzieren.

**Comment by GWRon** [comment]
Ja, es ist nur ein Vehikel um das mehrfache Produzieren zu vermeiden.

Damit laesst sich ein extern produziertes Programm mit gemeinsamer Abnutzung ermoeglichen.

Also ich bekomme ein Programm beim Haendler:
- "Rategeier"
- Kaufpreis beinhaltet bereits Kosten der Produktion durch Fremdfirma ("ihr macht mir 10 Sendungen, egal wann ich die will")
- 10 Ausstrahlungen (broadcast limit)
- jede davon "Live" egal wann ich sie ausstrahle
- jede Ausstrahlung gibt Einnahmen durch Zuschauer 
- jede dieser Ausstrahlungen senkt die Aktualität/nutzt ab...vergleichbar mit der wachsenden Erkenntnis, dass die Sendung eigtl. immer das gleiche ist und die Leute nur abgezockt werden / anrufen sollen


Mit einer 10-Folgen-Eigenproduktion liesse sich das derzeit nicht abdecken...und der Aufwand waere fuer "Nachtprogramm" denke ich zu hoch.


Idee:
Die Alternative waere die Einfuehrung eines "collection/series"-geteilten extra-topicality-Feldes. Damit liesse sich Serientreue bzw -untreue einbauen... unabhaengig von der Ausstrahlungsreihenfolge der "Episoden".
Allerdings koennten manche Episoden einen Trigger / Effekt bekommen, der eben diese Spezial-Topicality modifiziert (bspweise eine besonders herausragende Folge mit spannendem Cliffhanger).

**Comment by nittka** [comment]
Wenn man den Rategeier wie oben konfiguriert aber das live weglässt, hat man doch jetzt schon das passende Ergebnis (ja mit Einschänkungen)...

**Comment by GWRon** [comment]
Ja ... es ist eben nicht mehr "live".
Kann also nicht fuer etwaige Werbung mit der Einschraenkung "nur live" genutzt werden - und verliert die Vorteile ("Boost") den "Live" anbietet.
Aber ja ... _davon_ abgesehen, ist es vielleicht ohne "live" umsetzbar.

**Comment by scr0llbaer9000** [comment]
> Der derzeitige Flagname ist halt doch mehrdeutig und fuehrt ..wie man sieht... Zu Missverstaendnissen.

Hatte eigentlich nur nicht auf dem Radar, dass es ja einen Unterschied gibt zwischen "Sendung beendet" und Rückgabe an den Filmverleih.

**Comment by nittka** [comment]
Ich habe mal das Label ausgewechselt. Der Fehler des zu frühen Erscheinens ist ja adressiert worden. Die paid/always-live-Problematik weiter offen.

**Comment by nittka** [comment]
Nachfolgeticket erstellt.
