### ISSUE TITLE
DB: Fehler (Skripte)

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#1178]
scr0llbaer.xml:
```
        <scripttemplate product="3" licence_type="1" guid="204d40f8-c25f-458b-a049-526c06f4661f" creator="9551" comment="Perhaps some reciprocal effect with the corresponding news genre can be implemented? TODO: I am not happy with the titles and descriptions of these.">
            <title>
                <de>%tower%: %title%%latebreaking%</de>
                <en>%tower%: %title%%latebreaking%</en>
                <pl>%tower%: %title% - %latebreaking%</pl>
            </title>
...
                <latebreaking>
                    <de> Aktuell| der Gegenwart| im aktuellen Kontext|</de>
                    <en> Up-to-date| of the Present| in a Contemporary Context|</en>
                    <pl> aktualności| wiadomości| przegląd wydarzeń kulturalnych|</pl>
                </latebreaking>
```
%latebreaking% kann auch "leer" sein, im Falle der polnischen Lokalisierung bedeutet dies bspweise:

-> script: de : "TVT: Kultur"
-> script: en : "TVT: Culture"
-> script: pl : "TVT: Kultura - "

----

ScriptTemplate: ${TITLE}  | GUID: scripttemplate-random-ron-horrormovie1
-> script: de : "Untoten: Sie kriegen Dich"

hier sollte wohl die Grammatik auf die Einzahl "Untote" umschwenken

----

ariksan.xml

ScriptTemplate: ${title} ${currentyear} Edition  | GUID: script-ariksan-storage
-> script: de : "Schrottkriege 1985 Edition Edition"
-> script: en : "Dumpster Dazzle 1985 Edition Edition"

Edition Edition

wegen:
```
			<title>
				<de>%title% %currentyear% Edition</de>
				<en>%title% %currentyear% Edition</en>
			</title>

...
				<currentyear>
					<de>%WORLDTIME:YEAR% Edition</de>
				</currentyear>
```
----

scr0llbaer_screenplays_adaptations.xml
ScriptTemplate: Miss ${.self:"role":3:"name"}s letztes Programm  | GUID: a2e54e7e-7844-4628-b12d-1a9559cacbfb 
-> script: de : "Miss Miss Effie Everns letztes Programm"
-> script: en : "Miss Miss Effie Evern's Last Show"

Miss Miss.

-----

ScriptTemplate: Sound Sister ${.self:"role":2:"name"}  | GUID: 6f362a5a-6730-4772-b964-655d6bb3b6aa
-> script: de : "Sound Sister Sister Mira"
-> script: en : "Sound Sister Sister Mira"

sister sister

mir ist weiterhin aufgefallen, dass Du Nachnamen nutzt und die _derzeit_ zu Freizeichen fuehren (Vorname + " " + Nachname -> bei leerem Vornamen). Das behebe ich im Expression-PR.

ScriptTemplate: ${.self:"role":3:"name"}s Festung  | GUID: 33239572-ffe7-4b68-81e2-86e88a6d7705
-> script: de : " LeCrucks Festung"
-> script: en : " LeCruck's Fortress"

Bzw gibt es dann auch die explizite Moeglichkeit "nur Nachnamen" zu fordern.

**Comment by GWRon** [comment]
ronny.xml (btw das ist ist kein Script von mir):
```
		<scripttemplate product="2" licence_type="3" guid="scripttemplate-ron-from-above">
			<title>
				<de>${cntry} von oben</de>
				<en>Bird's Eye View of ${cntry}</en>
				<pl>Widok z lotu ptaka na ${cntry}</pl>
			</title>
			<description>
				<de>Erleben Sie atemberaubende Luftaufnahmen von ${cntry}.|${cntry} wie Sie es noch nie gesehen haben.|${cntry} aus einer neuen Perspektive.</de>
				<en>Experience breathtaking aerial views of ${cntry}.|${cntry} as you have never seen it before.|${cntry} from a new perspective.</en>
				<pl>Doświadcz zapierających dech w piersiach widoków z lotu ptaka na ${cntry}.|Doświadcz widoków z lotu ptaka na ${cntry}, których jeszcze nigdy wcześniej nie widziałeś.|Doświadcz widoków z lotu ptaka na ${cntry}, z nowej perspektywy.</pl>
```
Diese "zufaelligen Wert aus a|b|c|d"-Raussuchen-Sache geht nicht bei title/description selbst - das wird nur bei Variablen angewendet:

Deswegen derzeitiger Fehler:
-> script: T[de] : "Kanada von oben"
-> script: D[de] : "Erleben Sie atemberaubende Luftaufnahmen von Kanada.|Kanada wie Sie es noch nie gesehen haben.|Kanada aus einer neuen Perspektive."
-> script: T[en] : "Bird's Eye View of Canada"
-> script: D[en] : "Experience breathtaking aerial views of Canada.|Canada as you have never seen it before.|Canada from a new perspective."

----

database_scripts.xml:
```
		<scripttemplate product="1" licence_type="1" guid="scripttemplate-random-ron-foodformealtime01">
				<namewoman>
					<de>%PERSONGENERATOR_NAME(unk,2)%</de>
					<en>%PERSONGENERATOR_NAME(unk,2)%</en>
				</namewoman>
				<nameman>
					<de>%PERSONGENERATOR_LASTNAME(unk,1)%</de>
					<en>%PERSONGENERATOR_LASTNAME(unk,1)%</en>
				</nameman>
```
Das definieren von mehreren Eintraegen sorgt hier dafuer, dass "en" einen anderen Namen enthaelt als "de":
-> script: D[de] : "Argyró ist Autorin vieler Groschenromane und trifft Fan, von Beruf Landschaftsmaler. Traurige Komödie."
-> script: D[en] : "Gilda is the author of many dime novels and meets Jabłoński, a landscapist. Melancholic comedy."

Weiterhin ist es dort "falsch" (inhaltlich), dass der Mann per Nachname angesprochen wird.
Auch sollte hier wohl "spaeter" die Herkunft der Leute per extra-Variable limitiert werden (Auswahl aus "en, de, ...") um ein zu "exotisches" Namensgefüge zu vermeiden. ein griechischsprachiger Spieler hat ja sicher kein Problem damit aber fuer andere sieht es halt auch ... anders aus.

Hier koennen wir auch gern diskutieren, ob ein "map" als country-name genutzt werden koennen soll um ohne "Umwege" zu sagen: Gib mir einen "lokalen" Namen der zur Senderkarte passt.

----

ScriptTemplate: ${wohnobjekt}  | GUID: script-ariksan-mkw01
-> script: T[de] : "eine gläserne Iglu-Suite"

```
				<scripttemplate index="0" product="2" licence_type="2" guid="script-ariksan-mkw01">
					<title>
						<de>%wohnobjekt%</de>
						<en>%wohnobjekt%</en>
					</title>
					<description>
						<de>Objekt: ${wohn${wohnselector}}</de>
						<en>Property: ${wohn${wohnselector}}</en>
					</description>
					<variables>
						<wohnobjekt>
							<de>ein geräumiges Einfamilienhaus|ein exklusives Anwesen|eine klassische Villa|ein idyllisches Landhaus|ein schickes Loft|
...
```
das "ein" müsste jeweils groß beginnen. Gerne "vormerken" und dann mit der neuen Expression-Engine in ein `.ucfirst` wrappen
```
<title>${.ucfirst:wohnobjekt}</title>
```

**Comment by GWRon** [comment]
@nittka 
```
Function checkScript:int(t:TScriptTemplate)
	if not hasVariable(t.GetTitle()) then return False

'return True	

	'generateFromTemplate -> protects title
	'TScript.CreateFromTemplate -> only checks vs existing protections
	Local script:TScript = GetScriptCollection().GenerateFromTemplate(t.GetID())
	if not script then print "failed to create script"

	print "ScriptTemplate: " + t.GetTitle() + "  | GUID: " + t.GetGUID() + " -> script: GUID: " + script.GetGUID()
	For Local langID:Int = EachIn script.title.GetLanguageIDs()
		Local key:String = TLocalization.GetLanguageCode(langID)
		print "-> script: T[" + key+"] : ~q" + script.title.Get(langID) +"~q"
		'print "-> script: D[" + key+"] : ORIG ~q" + t.description.Get(langID).Replace("~n", "\n") +"~q"
		print "-> script: D[" + key+"] : ~q" + script.description.Get(langID).Replace("~n", "\n") +"~q"
	Next
'	if t.GetGUID().Find("script-ariksan-mkw01") >= 0
'		end
'	endif
End Function
```
das habe ich ein wenig angepasst und in Deiner test-Datei gehe ich nicht mehr durch jede Sprache einzeln.

```
print "=== TEST 0 ================================================"
rem
for local lng:String = eachin ["de","en","pl"]
	print "LANG " + lng
	print "-------"
	TLocalization.SetCurrentLanguage(lng)
	'checkLicences()
	checkScripts()
	print "-------"
next
endrem
	checkScripts()
```

**Comment by nittka** [comment]
ungewünschet Übersetzung innerhalb einer Variable: Księżniczka „von Taug und Thunix“ - do niczego się nie nadaje? Błąd! [3|Pierwszy] 
([3|Pierwszy] -> [3|First])

**Comment by scr0llbaer9000** [comment]
Ich bau grad eh einige Sachen um und bin dran.

> Miss Miss

jo Doppel-Titel hatt ich immer auf dem Radar, aber hab ich hier voll verpasst.

> Nachnamen nutzt und die derzeit zu Freizeichen

jo is mir auch schon lang aufgefallen, wollt wohl warten bis zum Script-Feature. `:)`

**Comment by scr0llbaer9000** [comment]
> hier sollte wohl die Grammatik auf die Einzahl "Untote" umschwenken

nee, weil beides vorkommt. Ich muss eher Artikel im Titel hinzufügen. "Untoten: Sie kriegen Dich" -> "Die Untoten: Sie kriegen Dich"

> Miss Miss Effie Everns letztes Programm

> Sound Sister Sister Mira

Kommando zurück: Ich verwende ja `%ROLENAMEn%. Das bedeutet bisher, dass nur der Vorname angezeigt wird. Titel + Voller Name wäre `%ROLEn%`. Fehler liegt bei der internen Platzhalter-Konvertierung?

> geht nicht bei title/description selbst

Stimmt eigentlich, aber anscheinend hat's bisher trotzdem funktioniert, weil's nie aufgefallen ist? Ich hatte das Drehbuch bestimmt schon mehrmals, aber es wurde wohl seltsamerweise nie "falsch" in der Roh-Schreibweise angezeigt.

> Weiterhin ist es dort "falsch" (inhaltlich), dass der Mann per Nachname angesprochen wird.
> zu "exotisches" Namensgefüge zu vermeiden

Hmm, könnte hier Absicht sein. Is ja random Komödie, impliziert Kultur-Clash. Und Frau Vorname, Mann Nachname ... Tatsächlich ist mir das bei den Büchern von Umberto Eco genau so untergelaufen. Der nennt die Männer meist mit Nachnamen (Casaubon, Garamond) und die Frauen, denen sie begegnen, mit Vornamen (Amara, Lea). Interessantes Stilmittel. Andererseits unwahrscheinlich, dass bei diesem Drehbuch so weit gedacht wurde, daher evtl. eher ein Versehen. `;)` Werd ich dann wohl "fixen".

> das "ein" müsste jeweils groß beginnen

ah, deswegen hatt ich glaub ich mal das "Objekt: " davor gesetzt, aber fälschlicherweise in der Beschreibung statt im Titel.

**Comment by scr0llbaer9000** [comment]
Im Commit https://github.com/TVTower/TVTower/pull/1180/commits/b230874b1beaac69b33883feef58caad81b0a9ff addressiert.

**Comment by nittka** [comment]
TheRob-Serie-WunderderMeere-Ep003 - In der Tiefe: [1|Full] wird mit dem aktuellen Scriptstand nicht mehr aufgelöst, denn es gibt gar keinen Cast mit Index 1 mehr; ist mit content updates 2024-08 entfallen (Zusammlegen der Funktionen). Hier sollte also [0|Full] stehen.

**Comment by nittka** [comment]
@GWRon : Mit dem Mergen des Datenbankmigrations-PR könnte @scr0llbaer9000 doch jetzt weitermachen. Ich muss noch Dokumentation/Editor aktualisieren, aber die Datenbank auf dem master ist doch jetzt auf Stand.

Uppercase First in script-ariksan-mkw01 könnte jetzt wohl gemacht werden, ansonsten sollten die Punkte dieses Tickets gelöst sein, oder?

**Comment by GWRon** [comment]
Ja wir sind ja eh per discord im Gespraech...und er hat die Freigabe bereits erhalten, weiterzumachen ;-)

**Comment by nittka** [comment]
Dann mache ich dieses Ticket zu.
