### ISSUE TITLE
Moderator oder Reporter

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#118]
Von Rauxelerritter
https://www.gamezworld.de/phpforum/viewtopic.php?pid=89018#p89018

## Moderator oder Reporter

Das Fahrstuhlgeräusch ist gar nicht mehr zuhören, auch nicht die Türen. Stattdessen hat man das Gefühl, dass ein ständiges Klacken und Klicken zuhören ist,wie das Geräusch einer Schreibmaschiene, z.T. das Schließen mehrerer Türen gleichzeitig (scheinbar die Aktivitäten der Konkurrenz). Das alles war mir so bisher noch nicht aufgefallen. An den Einstellungen habe ich eigentlich auch nichts geändert.

**Comment by Nalindir** [comment]
Wohl falscher Fehlertext übernommen. Forumsmeldung: Bei der Zusammenstellung der Besetzung zu der oben beschriebenen Reportage, wurden zwei männliche Reporter gefordert. In der Besetzungsliste erschien dann allerdings einer davon als Moderator. Was dann natürlich zu einer "Fehlbesetzung" führte.

https://www.gamezworld.de/phpforum/viewtopic.php?pid=89018#p89018

**Comment by GWRon** [comment]
Reportage:
>Jetzt scheint sich das Problem auch auf Filme übertragen zu haben. Ich habe einen neuen Spielstand gestartet (Beginn 1980) und versucht eine "Reportage aus dem Sendegebiet" zu verändern. Der neue Titel "Ist der NATO-Doppelbeschluss notwendig?" wurde übernommen, die Beschreibung der Reportage allerdings nicht.

**Comment by GWRon** [comment]
![img](http://i.imgur.com/BFp7voE.png)

Sowohl Datenblatt als auch Eigenproduktion zeigen einen Moderator und einen Reporter an.
