### ISSUE TITLE
Globale Variablen in der Datenbank

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1181]
Im Zuge des Scriptexpression-Refactorings kam auch die Frage noch globalen, in allen Scripten etc. nutzbaren Variablen auf, die in der Datenbank definiert werden können. Mit dieser Möglichkeit könnten manche doppelten Definitionen verhindert werden.

Vorschlag wäre, diese Variablen in den "lang"-Datenbankdateien unterzubringen, die es aktuell schon erlauben sprachspezifische Personennamen zu definieren. Dort könnte ein weiterer Abschnitt `<globalvariables>` untergebracht werden, dessen Kindelemente bei Spielstart einmalig global registriert werden. Beispiel für "lang/de.xml"
```
<globalVariables>
  <g_tvtName>TVTower</g_tvtName>
  <g_germanCurrency>${.if:${.gt:${.worldtime:"year"}:2001}:"Euro":"${.if:${.gt:${.worldtime:"year"}:1989:"DM"}:"Mark"}"}</germanCurrency>
</globalVariables>
```

**Comment by scr0llbaer9000** [comment]
Ich hatte auch erst eine Struktur für die Datenbank vorgeschlagen, aber Ronny hatte im discord gemeint, sowas könne man über die Ressourcen-txt-files erschlagen und dann mit `getLocale`.

Wär mir aber in der Tat gar nicht sicher, ob das dann so zielführend ist, Ressourcen werden ja bereits beim Laden des Programms gelesen und die Datenbank erst beim Starten eines Spiels, oder?

Datenbank wäre mir auch lieber eigentlich. Aber Einträge sollten schon auch generell für alle Sprachen möglich sein, und für die einzelnen Sprachen nur die Abänderungen wie bei den anderen Entitätstypen auch. Brands etc sind ja meist in allen Sprachen gleich.

**Comment by nittka** [comment]
@GWRon : Die Datenbank-Einträge könnten ja für "globalvariables" auch einfach die locale-Information befüllen und dann mit getLocale abgefragt werden.
Für mich sind die txts für spielinterne Lokalisierung (Verwendung im Code). Außerdem hätte man auf diese Weise gleich das "original"-Problem mit erschlagen.

**Comment by GWRon** [comment]
Ich wollte das auch so aehnlich handhaben.

Befuellung einer "globalLocales"-map. Beim abholen durch .getLocale koennte man das natuerlich auch abrufen...

...aber ich wollte einfach beim Scriptexpression-Auswerten die Teile nachgelagert zur lokalen Variable auslesen.

Also falls die templateVariables einer xy-Instanz einen key nicht haben, schaut die GameScriptExpression-Klasse noch bei den globalLocales nach (Priorisierung lokaler "Overrides".

Allerdings waeren das halt eher "Lokalisierungen" und nicht "lokalisierte Scriptexpressions".

Wir haben ja noch Dinge wie "Mark, DM, Euro" die wir vlt auch damit erschlagen koennten.

Alternativ koennten wir aber die globalLocales verschiedene Typen enthalten lassen können... Static und Dynamic (bzw einen flag bereitstellen). Ein Locale mit ${... waere dann dynamic und koennte nach Bedarf evaluiert werden.

Aber in unserem Fall waere das nicht noetig...da die Scriptexpression ja eh ersetzte Variablen erneut parst um eben solche Ersetzungen auch gleich mit zu interpretieren. Waere nur spielintern noetig..wenn intern auf solche Locales zugegriffen werden sollte.

Vermutlich also kann eine solche globalLocale einfach Scriptexpressions beinhalten und gut.

**Comment by nittka** [comment]
Wäre die "Verortung" der globalen Variablen in den lang-Dateien in Ordnung? Ich habe mal das Beispiel in der Ticketbeschreibung angepasst und um ein Script-Beispiel ergänzt.

**Comment by nittka** [comment]
Sollen wir dieses Thema noch angehen? "Datenbankinhalte" (insb. neue, falls man die Matchbeschreibungen schon jetzt als Datenbankinhalte betrachtet) in den regulären Übersetzungsdateien wie im PR fände ich nicht gut.

**Comment by scr0llbaer9000** [comment]
ja wär schon noch wichtig

**Comment by nittka** [comment]
Vorschlag wie im PR: neuer Hauptknoten für die DB-lang-Dateien. In en.xml würde man alle Variablen definieren, die Dateien für andere Sprachen enthalten ggf. abweichende Übersetzungen. Referenziert werden die globalen Variablen analog der nromalen
`${varName}`. Ohne eine Namenskonvention sieht man also nicht sofort, ob es sich um eine explizit im Eintrag definierte Variable handelt oder um eine globale.
