### ISSUE TITLE
Falsche Beschreibungstexte in Eigenproduktionen bei anderen Sprachen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#1182]
Ein aelterer Speicherstand eines Nutzers enthaelt folgendes Programm(data):

```
ID: 403994  GUID: data-customProduction--entitybase-403991-entitybase-403993
Title:
de: "Der Weg in die Hölle"
en: "The way to hell"
Description:
de: "Ein Wissenschaftler öffnet einen Weg in ein mysteriöses Reich voller schrecklicher Wesen."
en: "A Superhero-movie from the well-known Moval-Comics. % HERO% is fighting a new super villain and is saving the world."


ID: 504286  GUID: data-customProduction--entitybase-504283-entitybase-504285
Title:
de: "Der Weg zu ewigen Qualen"
en: "The way to eternal suffering"
Description:
de: "Ein Wissenschaftler öffnet einen Weg in ein mysteriöses Reich voller schrecklicher Wesen."
en: "A Superhero-movie from the well-known Moval-Comics. % HERO% is fighting a new super villain and is saving the world."
########## MIGRATED SCRIPT EXPRESSIONS IN PROGRAMMEDATA: 2 #############
```

Das sind Eigenproduktionen aus der "kasi.xml"-DB. Der Titel entspricht einem Drehbuch, und die deutsche "Description" ebenfalls. Die "englische" Description entgegen einem anderen Drehbuch - und sie enthaelt ein Freizeichen im Platzhalter, was das Originaldrehbuch (in kasi.xml) nicht enthaelt.

Die Frage ist, wie das zustandekommt. 

Mein erster Blitzgedanke war, dass irgendwie bei einem "values takeover" oder irgendwas "un-ge-mutextem" (dazu muesste aber die KI aus einem Thread eine Eigenproduktion anschubsen und da irgendwas im Argen liegen) im Studio durcheinanderkommt und es die Texte verschiedener Drehbuecher uebernimmt. 
Aber ich vermute irgendwie, dass es das nicht sein kann / sollte.

Speicherstand:
[quicksave__senderkarte.zip](https://github.com/user-attachments/files/17304491/quicksave__senderkarte.zip)

**Comment by nittka** [comment]
Ich tippe zunächst darauf, dass es ein Copy/Paste-Fehler in der Vorlage war, der diesen Fehler verursacht. Die Datenbank hat sich ja im Laufe der Zeit stark geändert und auf korrekte Übersetzungen wurde nicht von Anfang an geachtet.
D.h. man muss sich die im Spielstand hinterlegten Vorlagen für die beiden Drehbücher anschauen. Wenn die auch schon den Fehler enthalten, ist nicht die Konvertierung oder die Drehbucherstellungslogik kaputt.

**Comment by GWRon** [comment]
Das habe ich natuerlich schob gemacht gehabt. Inklusive git blame um zu sehen, ob da Korrekturwünsche stattfanden. Die kasi.xml war ungeaendert seit 3 Jahren.

**Comment by nittka** [comment]
Kasi-Script-Wege: aktuell Zeile 662 korrigiert in Commit 1e77e14b39

-				<en>A Superhero-movie from the well-known Moval-Comics. % HERO% is fighting a new super villain and is saving the world.</en>
+				<en>A scientist opens a path to a mysterious realm full of terrible creatures.</en>

Verräterisch ist das Leerzeichen in der Variable % HERO%.

Ich denke, das Spiel wurde mit einer fehlerhfaften Datenbank erstellt...
