### ISSUE TITLE
Unterstützung gut lesbare Daten für csv-Expressions

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1187]
Ich habe ein bisschen rumgespielt und suche nach einer einfachen Verwendung für csv-Expressions (möglichst wenig fehleranfällig, gut lesbar, gut parsebar etc.). Aktuell werden Alternativen in der Datenbank immer direkt hintereinander geschrieben, da alle Zeichen (also auch Whitespaces) relevant sind. Meine Wunschsyntax (für den csv-Anwendungsfall) würde in die folgende Richtung gehen:
```
<heroData>
  <de>
    der König;des Königs;dem König;den König|
    der Prinz;des Prinzen;dem Prinz;den Prinzen
  </de>
</heroData>
<hero>
  <de>${.csv:heroData:0}</de>
</hero>
```
(Für mich zwingener) Grund für die Zeilenumbrüche in den csv-Daten ist die Lesbarkeit. Bei vielen Alternativen mit jeweils mehreren Feldern wird das Übersetzen oder Erkennen von Fehlern beim Draufschauen extrem schwer.
Das ganze funktioniert auch, wenn ich die Datensätze selbst in Anführungszeichen setze ("der König..."|...) und herodata wrappe (${.csv:${heroData}:0}}). Das muss dann aber mit jeder einzelnen Alternative gemacht werden (viele überflüssige Zeichen, Fehleranfälligkeit, da man das leicht mal vergisst). Oder man beginnt jeden Eintrag mit Semikolon und erhöht den Index bei der Auswertung um 1. Wenn sich das vermeiden ließe, fände ich das besser.

Es würde auch funktionieren, wenn die Funktion für die csv-Auswertung für Token 1 implizit ein trim machen würde (obiges Snippet funktioniert wie erwartet so wie es ist).
Damit kann man dann natürlich (ohne tweak) keine Daten definieren, bei denen führende Leerzeichen beim ersten Feld oder folgende Leerzeichen im letzten Feld relevant sind. Aktuell sehe ich dafür auch fast keinen Anwendungsfall (am ehesten im Umfeld unbestimmte Artikel im Englischen, wo der Datensatz das "n" für "an" enthält, also " minute;...|n hour;...", was sich aber durch vollständiges definieren inklusive Artikel umgehen ließe "a minute;...|an hour;...")

Änderungsvorschlag zum aktuellen PR-Stand: .csv macht trim!

Wenn man dann (im Ausnahmefall) unbedingt Whitespaces am Anfang benötigt, kann man einfach ein Dummy-Leerfeld vorne anstellen, d.h. Feld mit Index 0 markiert einfach, wo der relevante Teil der Daten losgeht. (Analog Dummfeld am Ende, d.h Semikolon hinter dem gewünschten Ende des Eintrags.)
```
<en>
  ; minute;...|
  ;n hour;...
</en>
```

**Comment by GWRon** [comment]
Die Alternative ist ein Parameter fuer .csv ...der trimmen aktiviert oder nicht.

Alternativ kann man ja auch .trimmedCsv einfuehren ...oder eben den von dir vorgeschlagenen .trim-wrapper nutzen.

Eine versteckte Aenderung der Eingabedaten halte ich fuer zwar sicherlich effektiv aber eben auch zweischneidig bzw. potentiell Unsicherheiten ("wie geht das nochmal"l hervorrufend.
Heisst aber nicht, dass man es nicht so machen kann.

**Comment by nittka** [comment]
Ich verstehe die Vorbehalte bezüglich des Änderns der Eingabedaten. Andererseits ist .csv eben eine "dokumentierte" Funktion mit einem festgelegten Verhalten. Wenn man da aufgrund des Standardanwendungsfalls ein trim vorsieht und eben dokumentiert (mit Begründung und Tweak für das Umgehen), halte ich das für OK.

.trimmedCsv ist auch sauber, wenn es aber der permandent verwendete Fall ist; dann lieber .csv und .unTrimmedCsv

Wenn man einen Paramter zum Aktivieren/Deaktivieren einführt, sollte der standardmäßig aktiviert sein, sonst schreibt man sich auch dumm und dusselig (in 99% der Fälle ${.csv:data:";":true} statt ${.csv:data})

**Comment by GWRon** [comment]
Vielleicht nicht ganz passend - aber ich habe ueberlegt, ob man die `bla|bla2`-Pipe-Logik nicht auch ausbauen kann:
```
<heroData>
  <de>
    der König;des Königs;dem König;den König|
    der Prinz;des Prinzen;dem Prinz;den Prinzen
  </de>
</heroData>
```
wuerde zu:
```
<heroData>
  <de>
    <option>der König;des Königs;dem König;den König</option>
    <option>der Prinz;des Prinzen;dem Prinz;den Prinzen</option>
  </de>
</heroData>
```
Waere das "lesbarer"? Muesste man bei Variablen dann natuerlich aehnlich einlesen. Fuer die einfachen Faelle ist das natuerlich wieder "Overkill".

**Comment by nittka** [comment]
Ich würde darüber jetzt lieber nicht nachdenken wollen. <option> statt Pipe wäre für den csv-Fall natürlich auch möglich (und wäre für Einzelwörter Overkill), aber dann kommt gleich die Frage auf, warum man nicht gleich
```
<title>
  <option><de>D1</de><en>E1</en></option>
  <option><de>D2</de><en>E2</en></option>
</title>
```
schreiben können sollte.

Der Aktuelle Ansatz erlaubt mit knapper Syntax alles, was man braucht.
