### ISSUE TITLE
Reparatur alter Spielstände bezüglich neuer Expressions unvollständig

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1196]
Ich habe den testScriptExpressions-Branch aktualisiert und die Prüfung der Collections in den Start des Spiels integriert (für neue Spiele und geladene Spiele). Weiterhin habe ich zwei Spielstände ergänzt, mit der die Konvertierung der Datenbank beim Laden geprüft werden kann.

Während beim Start eines neuen Spiels keine Ausgaben zu nicht konvertierten alten Variablen kommen, sind es beim Laden der Spielstände ziemlich viele. Die Korrektur alter Spielstände scheint also noch unvollständig zu sein.

**Comment by GWRon** [comment]
Ich muss mich wiederholen, dass ich mehr als nur versucht bin, alte Speicherstaende irgendwann einfach als inkompatibel zu bezeichnen. Also mehr in Abhaengigkeit der Zeitraeume zwischen Releases, als rein mathematisch bei Versionsspruengen.

Man steckt enorm viel Aufwand rein, damit sich eine handvoll Spieler (die sich hier nicht melden wuerden) einen alten Speicherstand einladen koennen - der dann etwaig in einer Spielversion erstellt wurde, die voellig anderes Balancing hatte, oder eine schwaechere KI oder oder.

Ich denke eines der naechsten "groesseren" PRs sollte das Ausmisten sein - die Kompatibilitaet mit "v0.6"-Spielstaenden brauchen wir einfach nicht mehr. Dann muss halt in einer v0.7 eingeladen und gespeichert werden, und das dann mit v0.8 eingeladen usw. 
Dann sollte den Spielern eher klar sein, dass evtl nicht nur der Aufwand gross ist, sondern auch die Anzahl moeglicher dadurch entstehender Bugs.

**Comment by nittka** [comment]
Ich wollte auch nicht implizieren, dass es immer so weitergehen muss. Die kommende Version hat zwei riesige Umbauten: Expressions und Kartenlogik. Da der grundsätzliche Code für die Expression-Konvertierung da ist, wäre es aber sinnvoll, die Reparatur zu vervollständigen, so dass mit der nächsten Version (0.8.3 oder eher schon 0.9.0?) alte Spielstände auf die neue "Frameworkversion" gehoben werden können. Mit der darauffolgenden kann dann sämtliche Reparaturlogik entfallen.

... (mindestens) Die Ersetzung von Expressions in Lizenzen und in schon existierenden Nachrichten (nicht nur Templates) muss noch ergänzt werden.

**Comment by nittka** [comment]
Ergänzung zum Einlesen alter Spielstände. Es scheinen nicht die existierenden Nachrichten betroffen zu sein (die prüfe ich gar nicht). Die Reparaturen geht ja nur auf Title und Beschreibung - werden dabei überhaupt alle in den Templates verwendeten Variablen mit umgewandelt? Die können ja auch wieder die alte Syntax nutzen.
Das würde nicht nur die Nachrichten sondern auch die Drehbücher betreffen.

**Comment by GWRon** [comment]
Nein, die Variablen werden derzeit noch nicht nach Platzhaltern untersucht ... muesste man noch einbauen.
