### ISSUE TITLE
Versteckte Netzwerk Option im Spielstartmenü 

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#120]
Im Bereich für die Auswahl eines neuen Spiels lässt sich eine Funktion "Nach weiteren Spielern suchen" aktivieren, die in der Maske ausgeblendet ist. Das Aktivieren/Deaktivieren wird im Chat als Ereignis angezeigt. 

![option](https://user-images.githubusercontent.com/57690824/69638297-b3ed5d00-105a-11ea-8547-722d610e7624.JPG)

**Comment by GWRon** [comment]
Bitte im naechsten DevPatch testen.

**Comment by Nalindir** [comment]
Fix confirmed
