### ISSUE TITLE
Frage zum Umbau der Rollenvariablen (indexbasiert)

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1203]
Beim Anpassen der Dokumentation und beim Testen ist mir aufgefallen, dass der Umbau von ROLE1 nach .self:"role":0 Konsistenzprobleme (zumindest Verständnisprobleme) mit sich bringt.

Beim Cast entspricht die Zahl ja genau dem index in der Datenbank, wodurch eine Zuordnung leicht möglich ist. Bei den Rollen ist die Sache wesentlich komplizierter, da sich die Logik für Lizenzen und Drehbuchvorlagen unterscheidet. Während die Zahl bei Lizenzen indexbasiert ist, werden bei Drehbuchvorlangen aus den Jobs zunächst die Einträge herausgefiltert werden, die Schauspieler oder Nebendarsteller sind. 0 wäre also der erste Job, dessen Typ Schauspieler oder Nebendarsteller ist (typischerweise index 1 da 0 der Regisseur ist).

Für alle anderen Jobarten den Vorlagen sind Rollenangaben aktuell gar nicht möglich. D.h. selbst wenn für einen Musiker eine Rolle in der Datenbank definiert ist, kann diese über die Expressions gar nicht referenziert werden. Der Musiker muss dafür ein kombiniertes function-Flag bekommen (Musiker und Nebendarsteller; was im Prinzip auch OK ist).

An sich wäre es mir am liebsten, wenn auch für die Rolle einfach der Index aus der Jobliste zählen würde (das war eigentlich auch der Hintergrund für den gewünschten Umbau auf indexbasiert). Für die neue Datenbank ließe sich das mit ziemlichem Prüfaufwand auch noch umsetzen, aber die Reparatur von alten Spielständen wäre vermutlich die Hölle, da eben kein einheitliches Mapping der Zahlen möglich ist.

Möglichkeiten:
* es bleibt wie es aktuell ist und die schauspielerindexbasierte Logik muss gut dokumentiert werden
* für alle Rollenreferenzen (in Drehbuchvorlagen) wird der "Index" doch wieder um Eins erhöht (und entsprechende Anpassung der Spielstandkorrektur) und "role":1 ist eben der erste Schauspieler. cast und role verhalten sich ohnehin unterschiedlich aber mit der Änderung ist leichter verständlich, was die Zahlen bedeuten
* (wohl keine Option): kompletter Umbau der Rollen-Referenzierung über den job-Index

**Comment by nittka** [comment]
(Ich gehe mal davon aus, dass beim Übergang von Drehbuch zu Lizenz alle Variblen komplett ersetzt werden und später im Spiel keine Auswertung von Ausdrücken mehr passert, sonst drohen bei den Rollen nämlich noch ganz andere Probleme.)

**Comment by scr0llbaer9000** [comment]
Ja, ist mir auch vorhin aufgefallen. Blöd dass es geändert wurde. Indexbasierung sollte so sein wie früher, ist intuitiver. So wie es geändert wurde ist es nur verwirrend und potenzielle Fehlerquelle.

**Comment by nittka** [comment]
Ich bin mir nicht sicher ob es früher wirklich indexbasiert war oder nur zufällig so aussah, weil immer der Regisseur index 0 hatte, es nie zwei Regisseure gab und dann zuerst alle Schauspieler kamen (und nie eine Referenz auf einen schauspielenden Regisseur existierte - dann hätte nämlich früher schon ROLE0 geschrieben werden müssen).

Auch wenn es weh tut, sollten wir uns hier nochmal auf ein Zielbild einigen.

**Comment by nittka** [comment]
Meine Prüfung hat ergeben, dass im aktuellen Datenbankbestand nur in Drehbuchvorlagen Rollenreferenzen vorkommen. Wenn man den (beim Refactoring um 1 reduzierten) referenzierten Index wieder um 1 erhöht, kommt man auch immer auf einen Job, der Schauspieler oder Nebendarsteller ist.
Ich werde jetzt noch prüfen, dass sich zwischen den Schauspielern auch keine anderen Job-Typen liegen. Dann kann "wirklich" auf indexbasierte Rollenreferenzen umgestellt werden.

**Comment by GWRon** [comment]
Auch bezugnehmend auf den PR #1205 finde ich es ebenfalls konsequenter, ueberall den "index" zu nutzen. 

Es obliegt dem Autoren des DB-Eintrages nur "X"en bei den "roleX" zu nutzen, die auch eine Rolle "dahinter" haben (deswegen gibt es ja auch das "hasrole" beim "cast" (`.self:"cast":0:"hasrole"`) - das macht es bei "koennte mal sein, dass er keine Rolle hat"-Eintraegen zwar etwas umfangreicher (if-Verschachtelungen) aber doch loesbar.
