### ISSUE TITLE
Dynamische Rollenerzeugung in Drehbüchern/Programmen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#1209]
@scr0llbaer9000 per Discord:
> emporär Rollen erzeugen kann man nicht, oder?
>
>ariksan erzeugt hier im Drehbuch Personen, aber nur in Variablen:
```XML
                <where>
                    <de>Santa Monica, 90405|San Diego 92110|Santa Cruz, 95060|Newport Beach, 92660|Huntington Beach, 92648|Long Beach, 90840|La Jolla, 92037|Santa Barbara, 93101|San Francisco, 94110|Palo Alto, 94301|Laguna Beach, 92651|Manhattan Beach, 90266|Venice Beach, 90291|San Clemente, 92672|Santa Cruz, 95060|Pacific Beach, 92109|Morro Bay, 93442|Monterey Bay, 93940</de>
                    <en>Santa Monica, 90405|San Diego 92110|Santa Cruz, 95060|Newport Beach, 92660|Huntington Beach, 92648|Long Beach, 90840|La Jolla, 92037|Santa Barbara, 93101|San Francisco, 94110|Palo Alto, 94301|Laguna Beach, 92651|Manhattan Beach, 90266|Venice Beach, 90291|San Clemente, 92672|Santa Cruz, 95060|Pacific Beach, 92109|Morro Bay, 93442|Monterey Bay, 93940</en>
                </where>
                <person1_m>
                    <de>${.persongenerator:"firstname":"us":"male"}</de>
                </person1_m>
                <person2_m>
                    <de>${.persongenerator:"firstname":"us":"male"}</de>
                </person2_m>
```
> ...die aber in den jobs nicht referenziert werden (können), was aber schöner wäre, weil man die dann auch beim casten angezeigt werden würden.
```XML
                <job index="2" function="2" required="1" gender="1" />
                <job index="3" function="2" required="1" gender="1" />
```
> Man kann zwar Rollen global anlegen und Namen generieren lassen, aber hier sollen es dynamisch immer andere sein pro Instanz.

-------

Meine Reaktion darauf:

Du kannst das gerne als Issue anlegen  -aber fuer mich stellt sich dort die Frage nach der "Verhaeltnismaessigkeit". Jedes Drehbuch wuerde dann seine "dynamischen Rollen" in die "RoleCollection" reinpacken - obwohl es der einzige ist, der die braucht (sie sollen ja nicht "wiederverwendet" werden)
die Roles sind ja an sich eher dafuer gedacht, dass man sie mehrfach verwenden kann (James Bond ...)
Alle "einmal-Rollen" sollten wohl besser einfach nur im Drehbuch erstellt werden - vielleicht auch einfach ueber den "<job"  ... dort dann als "rolename=..." (derzeit nicht unterstuetzt)
Was damit nicht geht ist sowas wie "Preisverleihung: Bester Hauptdarsteller ist XYZ in seiner Rolle als ABC"
Man KOENNTE das natuerlich auch so machen, dass wir ein `${.rolegenerator:"us":"male"}` oder so einbauen.
Der Rueckgabewert waere IMMER eine GUID (oder ID).
du wuerdest dann die Variable nutzen um die ID zu hinterlegen ... und kannst die ja dann abfragen:
```
<dynamicrole1_guid>${.rolegenerator:"us":"male"}</dynamicrole1_guid>
<title>Skullbear spielt die Rolle seines Lebens als verrückter Drehbuchautor ${.role:${dynamicrole1_guid}:"fullname"}</title>
```

Der Generator erzeugt also eine Rolle, speichert sie in der "Collection" (wo alle Rollen landen) und im <title> nutzt Du die zurueckgegebene GUID um auf die Details dieser zuzugreifen. Die Rolle wird natuerlich erst erzeugt, wenn die Variable aufgeloest werden soll (also erst, wenn "title" durchgecheckt wird)

Klingt das praktikabel?

Man koennte noch ueberlegen, wie wir diese Rollen "geloescht" bekommen, falls sie keiner nutzt. Man muesste ueber den "context" des Drehbuchs/Programmes gehen und dort die erzeugte Rolle mit "speichern" (vlt sogar NUR dort). Wenn dann ein Drehbuch wieder vernichtet wird, muessen solche Rollen eben mit geloescht werden. 

----------

Wir brauchen also einerseits eine Loesung um dynamische Rollen zu ermoeglichen. Andererseits aber auch etwas, was solche dynamisch erzeugten Rollen bei Nichtbenutzung loescht (also in Drehbuechern hinterlegen, welche dynamischen Rollen dafuer angelegt wurden).
Wenn wir dynamische Rollen nur in den Drehbuechern hinterlegen wuerden, muessten:
- dynamische Rollen bei Produktion eines Programmes "fixiert" werden (vom Drehbuch hin in die ProgrammeRoles-Collection ...)
- .role:guid/id -Lookups kontextabhaengig bei "TScript" erst in deren "field dynamicRoles:TProgrammeRoles[]" (oder wie es dann aussehen sollte) nachschaut, und dann in der ProgrammeRoleCollection.

**Comment by nittka** [comment]
Ganz früher wurde für alle Jobs, die keine Rollenreferenz hattenen automatisch eine Rolle angelegt. Beim Reduzieren der Spielstandgröße habe ich das dann umgebaut. Rollen wurden nur noch dann erzeugt, wenn es im Drehbuch einen Zugriff auf die Rolle gab.
Das dynamische Anlegen von Rollen haben wir also bereits (in den Rollen-Expressions ist das das _ensureRoleExists). Für jedes Drehbuch ist das auch eine andere. Natürlich wird diese konkrete Rolle dann auch nie "wiederverwendet", da man außer vom eigenen Titel oder der Beschreibung nicht wieder darauf zugreifen kann.

Nun kann man sich streiten, ob die Rolle nach der Filmerzeugung noch benötigt wird (in allen Sprachen Namen ersetzen, bei dynamisch erzeugten Rollen kann sich der Name ja nicht ändern) oder gelöscht werden sollte. Tatsächlich gibt es aber auch in der Datenbank selbst mutmaßlich haufenweise Rollen, die in der Datenbank nicht referenziert werden und deshalb aus der Datenbank gelöscht werden könnten.

Ich sehe aktuell keinen Grund für Änderungen. Wenn man für die Beschreibung beliebige Namen haben will, aber keine Rolle anlegen möchte, nutzt man den persongenerator. Wenn der Name im Laden mit angezeigt werden soll, referenziert man einfach die Rolle und bei jeder Drehbucherstellung wird eine Rolle angelegt. Speichermäßig sollten diese kaum ins Gewicht fallen.

Das Geschlecht für die Rolle wird aus dem job übernommen, auf das Land hat man aktuell aber noch keinen Einfluss. Zu überlegen wäre also, ob man am job noch einen Ländercode (für die Rolle) mitgeben kann (aber spielt das wirklich eine so entscheidende Rolle).

**Comment by GWRon** [comment]
Ich denke das Land ist schon wichtig. Da es halt sehr komisch klingt, wenn der US-Praesidentenschutz "Kwong Yak Sun" heisst (oder Accents ueberall hat).

**Comment by GWRon** [comment]
Ja..
Koennte ja sowas wie "role_hint_country" usw. ablaufen

Am 1. November 2024 17:27:03 MEZ schrieb Alexander Nittka ***@***.***>:
