### ISSUE TITLE
VV: Showgäste mit eigener XP Bar statt Popularität

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#121]
In der Produktionsplanung für manche Shows sind prominente Showgäste eingeplant. Aktuell haben diese einen eigenen Erfahrungsbalken. Ein guter Showgast sollte aber nicht abhängig von der Teilnahmehäufigkeit an Shows sein, sondern sich eher durch Bekanntheitsgrad bzw. eben Erfahrungsgrad in den eigenen Kategorien von schlechten Gästen abheben. 

Ein guter Darsteller mit hohem XP Grad sollte diesen Wert als positiven Einfluss in der Showkategorie "Showgast" mitbringen, auch wenns die erste Show-Teilnahme ist. Gleiches gilt, wenn man Moderatoren, Nebendarsteller oder Regisseure usw. mit Erfahrung in ihren Einsatzbereichen einsetzt.

**Comment by GWRon** [comment]
> Gleiches gilt, wenn man Moderatoren, Nebendarsteller oder Regisseure usw. mit Erfahrung in ihren Einsatzbereichen einsetzt.

Das verstehe ich nicht ganz. Welche Werte sollen fuer "Nebendarsteller", eingesetzt als "Moderator" denn rangezogen werden, wenn nicht ihre Expertise als "Moderator" ?


> Ein guter Showgast sollte aber nicht abhängig von der Teilnahmehäufigkeit an Shows sein, sondern sich eher durch Bekanntheitsgrad bzw. eben Erfahrungsgrad in den eigenen Kategorien von schlechten Gästen abheben.

Jede "Promi"-Persoenlichkeit (also alle mit "Namen" und nicht Amateure...) haben:
- fuer jeden Beruf Erfahrungspunkte ("XP")
- Fame/Beruehmtheit
- Popularitaet/Bekanntheit

Die XP fuer "Showgast" sagt aus, wie stark sie das Umfeld einer "Show" kennt, also das Konzept (Leute live unterhalten, vielleicht auch mal ein Liedchen traellern ... ) verstanden hat und es zum Besseren benutzen kann.

Die Datei config/programmedatamods.xml kann fuer Genre definieren, wie Besetzungsposten von persoenlichen Eigenschaften profitieren. Also Charisma, Humor ... 
Die Werte Beruehmtheit, Erfahrung ... kommen da generell mit rein. Ob jemand als Schauspieler beruehmt ist, oder als Saenger, ist da dann erstmal nicht weiter zu unterscheiden. Beruehmtheit und Popularitaet sind da wichtiger. "Popularitaet" ist ein Trend - der schwankt (zu oft gesehen? dann wird man der Person ueberdruessig und sie ist weniger gern gesehen. Beruehmtheit kann negativ oder positiv besetzt sein ("Beruechtigt" fuer Skandale etc, siehe Klaus Kinski)

**Comment by Nalindir** [comment]
> Das verstehe ich nicht ganz. Welche Werte sollen fuer "Nebendarsteller", eingesetzt als "Moderator" denn rangezogen werden, wenn nicht ihre Expertise als "Moderator" ?

Wollte damit nur aussagen, dass die Regelung nicht nur auf Darsteller als Gast einer Show beschränkt sein sollte, sondern auch ein "Moderator", der als Gast anwesend ist, die Qualität Gast mit seiner Moderator-Expertise erfüllt und kein Neuling im Sinne der Unterhaltseimkeit ist. So ist Thomas Gottschalk zu Gast bei Günter Jauch ein Moderator in der Rolle Gast unter keinen Umständen mit 0 Gast-XP einzustufen.

> Jede "Promi"-Persoenlichkeit (also alle mit "Namen" und nicht Amateure...) haben:
> 
>     * fuer jeden Beruf Erfahrungspunkte ("XP")
> 
>     * Fame/Beruehmtheit
> 
>     * Popularitaet/Bekanntheit

Davon sieht man aber nicht viel, wenn man jemanden hinzufügt. Es fällt lediglich die XP Bar auf. Und dass ein erfahrener Schauspieler erstmal einige Auftritte als Gast braucht um ein guter Gast zu sein, erschließt sich mir einfach nicht. 

> Die XP fuer "Showgast" sagt aus, wie stark sie das Umfeld einer "Show" kennt, also das Konzept (Leute live unterhalten, vielleicht auch mal ein Liedchen traellern ... ) verstanden hat und es zum Besseren benutzen kann.

Wir reden hier von Schauspielern, Modertoren, Reportern. Promis sind doch in den meisten Fällen Promis, weil sie gelernte Entertainer sind, die müssen nicht mehr lernen wie sie Leute unterhalten, zumindest in Abhängigkeit ihrer Erfahrung in ihrem Hauptgebiet. Ein guter Schauspieler ist doch meist auch unterhaltsam, auch wenn er kein Liedchen trällert, sondern weil er weiß, wie man sich artikuliert oder coole Anekdoten vom Set hat. (Ausnahme Till Schweiger...) Er wird auch kein besserer Gast, nur weil er häufiger in Shows einkehrt. Er wird auch nicht interessanter für Shows, weil er häufiger in Shows einkehrt, sondern durch seine Performance in Filmen.

> Die Datei config/programmedatamods.xml kann fuer Genre definieren, wie Besetzungsposten von persoenlichen Eigenschaften profitieren. Also Charisma, Humor ...
> Die Werte Beruehmtheit, Erfahrung ... kommen da generell mit rein. Ob jemand als Schauspieler beruehmt ist, oder als Saenger, ist da dann erstmal nicht weiter zu unterscheiden. Beruehmtheit und Popularitaet sind da wichtiger. "Popularitaet" ist ein Trend - der schwankt (zu oft gesehen? dann wird man der Person ueberdruessig und sie ist weniger gern gesehen. Beruehmtheit kann negativ oder positiv besetzt sein ("Beruechtigt" fuer Skandale etc, siehe Klaus Kinski)

Der Zusammenhang erschließt sich mir in diesem Spiel nicht. Da sind wir aber wieder bei der Indikation von guten Showgästen. Denn ich sehe halt nur die XP Bar - und die ist bei allen erstmal 0. Ein Laienshowgast macht keinen Sinn und ein Promi der anderen Kategorien ist halt imho ein Knallergast, wenn er der Superstar am Darstellerhimmel ist - auch wenn er vielleicht den größten Stuss aller Zeiten erzählt oder seine Witze ohne Drehbuch für'n Arsch sind und einfach nur für die Zielgruppe gut aussieht. Die Muttis schalten ein, weil da ist heute George Clooney.


Klar, man kann das noch ins endlose Treiben. Eine Stand-up Comedy wird sich nicht nen ARD-Tagesschau Moderator oder nen Kriegsgebietreporter von RTL auf die Bühne holen um dort die Kalauer aus ihrem Tagesgeschäft zu reißen, sondern eher für einen Polittalk als Gast fungieren. Aber da sind sie mit ihrer Erfahrung kein schlechter Gast, nur weil sie das erste Mal zu Gast sind. Und so eine die Bandbreite an Einzelfllen gibt die TVT Umsetzung aktuell nicht her. Die verfügbaren, unerfahrenen Gäste in der Rolle Gast einfach nur schädlich für den Sendungserfolg, obwohl sie bereits 20 echt gute Filme für mich gedreht haben. Der Ansatz ist nicht stimmig, wenn man das so vereinfacht simuliert.

**Comment by GWRon** [comment]
@ Laienshowgast
Klar ... sind halt auf der Strasse angesprochene Leute - solls geben.


> So ist Thomas Gottschalk zu Gast bei Günter Jauch ein Moderator in der Rolle Gast unter keinen Umständen mit 0 Gast-XP einzustufen.

Dann muessen aber fuer jeden Beruf Zusammenhaenge mit anderen Berufen definiert werden ("Schauspielererfahrung bringt 20% Moderatorenerfahrung..."). Also welche Berufe haben positive oder negative Effekte auf andere Berufe. Auch wenn es nur ein paar Berufskombinationen betrifft, muss das Spiel ja mit jeder Moeglichkeit umgehen koennen - wir koennen es also nicht "hardcoded" umsetzen (wuerde ich machen, wenn es nur 1-2 Kombinationen gaebe - Moderator-Showgast, Hauptdarsteller-Nebendarsteller)

@ XP-Bar
was wuerdest Du dann anzeigen wollen? Die vom Hauptberuf oder die von dem die Person die meisten XP hat (Es koennte ja ein eigentlicher Regisseur sein, der mittlerweile mehr Erfahrung als Darsteller hat - auch hier noch streitbar, ob er dann Ein schauspielernder Regisseur oder ein drehender Schauspieler ist/wird).

**Comment by Nalindir** [comment]
> Klar ... sind halt auf der Strasse angesprochene Leute - solls geben.

Ja, sind mehr Opfer und Statisten, denn "Gäste", aber letztlich nur Randformate und vor allem ist die Wiederverwendbarkeit eines Laien-Showgasts tendenziell 0 - ja auch hier gibt's Gegenbeispiele, ein Kandidat beim Bachelor ist letztlich ein Laiendarsteller/Showgast, nimmt dann am Dschungelcamp teil, dann an Love Island, dann als "Experte" beim Jahresrückblick der Mutantenstadlhitparade 2020, Promi Big Brother, uws (und weiterer scheiss...;

) ).  

Back to TVT: Derzeit hebt sich ein namentlich benannter Schauspieler mit 25 Filmen nicht von nem Laiendarsteller ab im Sinne eines Show-Gasts. 

> Dann muessen aber fuer jeden Beruf Zusammenhaenge mit anderen Berufen definiert werden

Ja, klingt alles nicht schlecht, auf jeden fall potentieller Komplexitätsgrad für die Zukunft, aber imho mit der aktuellen Implementierung übers Ziel hinausgeschossen. So weit wollt ichs für den Moment garnicht treiben. 

Hat vor allem alles nicht den Nutzen, den ich mit diesem Thread adressieren wollte ;) Mir gings nur darum, nen erfahrenen TV-Promi pauschal auch als quotengarantierenden Gast zu definieren, statt ihn wie einen Laiengast zu behandeln. 

> was wuerdest Du dann anzeigen wollen? 

Mindestens meiste XP, eventuell sogar Summe aller XP.

>  Ein schauspielernder Regisseur oder ein drehender Schauspieler ist/wird).

Deswegen tatsächlich eher die Summe aller XP, da der Entertainmentfaktor bei Multitalenten höher ist.

**Comment by GWRon** [comment]
Summe...ist ne gute Idee.

PS: hinter Laien verstecken sich nur eine Handvoll Leute. Nutze sie oft genug und es muesste irgendwann ein Promi entspringen...dessen Beruf "Gast" ist ;-)
Sollte diese Trash-Tingel-Tanten abdecken ;-)

**Comment by Nalindir** [comment]
Gast-XP wird jetzt generiert. Closed.
