### ISSUE TITLE
VV: Wenigstens ein Darsteller/Regisseuer/Nebendarsteller, etc. per Default mit Genre-Spezialisierung 

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#122]
Für die Eigenproduktionen sollten für alle Genre wenigstens ein, besser mehrere Darsteller, Regisseure, Nebendarsteller, Moderatoren, etc. verfügbar sein, die zumindest die Spezialisierung aufweisen, aber noch ohne Erfahrung sind. 

Der Einsatz von Laiendarstellern bringt zu selten Nachwuchs insbesondere, da die Auswahl an Eigenproduktionen ist im Verhältnis zur XP-Gewinnung zu gering ist. Ich habe jetzt nach 42 Spieltagen Drehbücher mit zweistelliger Titelnummer (Die Schatzsuche #12), aber immernoch kein hochwertigen Darsteller. 

Desweiteren neigt man dann dazu, z.B. Darsteller mit hoher XP aber genrefremd dann ständig einzusetzen. Genrepassend sollte aber einen deutlichen Bonus geben, während ein hoher XP Wert (z.B. in Horror) eher bescheidene Ergebnisse (z.B. bei Lovestory) geben sollte. 

Um das Problem zu entschärfen, könnte man vielleicht Mehrfachgenres oder Cluster bilden: Action, Horror, Abenteuer hohe XP = gutes Ergebnise, Comedy, Lovestory liefert dann minderwertige Ergebnisse.

**Comment by GWRon** [comment]
Ich denke hier koennte man prima ein paar fiktive Gestalten anlegen. So koennten einige Literaten (siehe Kulturnews) ja auch Drehbuchschreiber sein ...

Oder Sänger, "Gäste" (Trash-Sternchen?) ...

**Comment by nittka** [comment]
Siehe auch #130

**Comment by nittka** [comment]
Bei der Analyse der Datenbank ist aufgefallen, dass es "zu wenige" fiktive Hauptpersonen gibt, die bei Spielbeginn zur Verfügung stehen können. Lösungsansatz 1 wäre, die DB um weitere fiktive Hauptpersonen zu erweitern (manueller Aufwand). Besser würde mir aber Lösungsansatz 2 gefallen: die Menge der Hauptpersonen bei Spielstart aus den Nebenpersonen auffüllen und mit Zufallswerten versehen. Das hätte auch den Vorteil, dass nicht "alle Spiele gleich sind". Man muss sich bei der Besetzung die Werte wirklich anschauen, weil man nicht einfach anhand des Personennamens auswählen kann.

Eine passende Besetzung für jede Genre/Job-Kombination zu generieren erscheint mir zu viel. Wie wäre es denn, pro Beruf und Geschlecht mindestens 4 Personen zu fordern und darauf zu achten, dass die Genre-Mischung OK ist (max zwei haben dasselbe Genre). Ggf. kann man bei manchen Berufen weniger (2) haben - z.B. Maler und Models habe ich bisblang nie gebraucht.

**Comment by GWRon** [comment]
Ich habe eine "einfache" Funktion geschrieben, die fuer jede Berufsgruppe 3 Maenner und 3 Frauen anlegt.
Dies als "Promis" (also mit Namen in der Liste auftauchend).

Derzeit haben diese Personen noch kein "Favorisiertes"-Genre.
Ich weiss nicht, ob dies beim Erzeugen schon gemacht werden sollte - oder aber, ob in einem zweiten Schritt die Liste der (fiktiven) Celebs durchgegangen werden sollte und einfach fuer jedes Genre geschaut wird, dass mindestens X Personen eine Genre-Erfahrung vorweisen koennen.

**Comment by nittka** [comment]
Die Personenauswahl wurde mit den verlinkten Tickets und Commits erweitert. Zusätzlich zu allen Berufsgruppen noch für sämtliche Genres Spezialisten zu generieren, würde die Liste der Kandidaten übermäßig aufblähen.
Der Punkt Aufbau von Amateuren, Änderung der Attribute (Spezialisierung) durch Produktionen/Ereignisse kann separat betrachtet werden.
