### ISSUE TITLE
Generated sports programmes suddenly appear (partly) in Polish

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1223]
Now that's a curious one, how could that have happened? (Playing in German)

![Screenshot From 2024-11-12 02-49-52](https://github.com/user-attachments/assets/8b3e0772-ab8f-4002-ac41-93add63f17cd)

I think it's easily reproducible and happens for all generated sports programmes now.

**Comment by nittka** [comment]
New game started with current master or older saved game (for which there is still an open problem with the expression conversion)?

**Comment by nittka** [comment]
* new game started, fast forward to day 5, so that the matches appear in the auction
* when changing the language using "u" and fast forward, some of the texts change to the other language, (but never all texts to German)

**Comment by scr0llbaer9000** [comment]
It happened to me reproducibly or at least repeatedly when starting a game in 1985 without changing any language or pressing "u" btw.
