### ISSUE TITLE
Fehler bei .locale-Expression

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1237]
.locale in der Datenbank hat aktuell mit mehreren Problemen zu kämpfen.

* Obwohl in der Datenbank ${.locale:"key"} steht (ohne optionale Sprache), wird der Zweig für den zusätzlichen Parameter betreten (language code ist leer); das kann an einem one-off-Fehler bei der Parameterzahl liegen.
* Erwarten würde man, dass die Auflösung mit der aktuellen Sprach der Variable erfolgt, aber die ist nicht Teil des Kontexts, d.h. Für alle Spracheinträge in der Datenbank wird der Schlüssel mit der aktuell eingestellten Spielsprache aufgelöst. Workaround wäre aktuell, für jeden Eintrag die Sprache mitzugeben (`<en>... ${.locale:"key":"en"}... </en>`), was unschön ist.

**Comment by GWRon** [comment]
Ich schau mir das bereits an .

Ein weiterer Fehler ist ".added"-checks (Parameter 0,1,2 -> added=3 ... oft wird gecheckt ob "added >= 3" und dann zugriff auf Params(3)) 
Ebenfalls fehlerhaft sind die offsets die an die _Evaluate-Helper weitergegeben werden (da die intern fehlerhaft schon "2+ tokenOffset" usw. machten. Damit funktioniert das zwar - aber insgesamt gesehen, ists falsch.

**Comment by GWRon** [comment]
Ok ... der Fehler ist ... dass die meisten SEFN-Funktionsdefinitionen kein "var" an den context gepackt hatten. Und irgendwie meckerte der Compiler diesbezueglich nicht.

Nach dem ich das nun eingegrenzt hatte und das var anfuegte ... wurde korrekt lokalisiert. PR kommt dann morgen/heute frueh.
