### ISSUE TITLE
VV mit Checkliste: Geschenke/Betty an MadTV anpassen

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#124]
Geschenke werden an Betty derzeit automatisch beim Supermarktkauf übergeben. In MadTV musste man für jedes Geschenk zu Betty hochfahren. 
Dort angekommen wurde das Geschenk aus nem Koffer auf Betty gezogen, dann wuchs erst der Liebesbalken. 

VV im Sinne der Nostalgie. ;)

**Comment by Nalindir** [comment]
S. Discord vom 27.11.: Checklist für weitere Nostalgieanpassungen bzgl. Betty/Geschenke:

- [ ] Wie oft Betty ein Geschenk erhalten hat, wurde im Supermarkt als Counter auf dem Bild des Geschenks angezeigt. 1x, 2x, 3x, etc. Gezählt wurde der Kauf von jedem Spieler. 
- [ ] Entsprechend sinkt die Effektivität eines Geschenks mit jedem Kauf. Massig Kohle vorhanden ist und man den Abschluss sucht. Für ein eventuelles Multiplayerspiel wäre das vielleicht relevant?
- [ ] Geschenkeübergabe wie oben bereits erwähnt, im Koffer und dann in Bettys Büro übergeben. 
- [ ] Geschenke im Koffer können im Supermarkt per Rechtsklick und/oder per Drop auf den Verkäufer wieder zurück gegeben werden. 
- [ ] Der Koffer kann immer nur ein Geschenk auf einmal annehmen. 
- [ ] Das letzte Geschenk, derzeit die Jacht, war in MadTV die Hochzeitsreise. Diese konnte zwar jederzeit erworben werden, aber Betty hat die Reise erst akzeptiert, wenn der Liebesbalken bei 100% war. Davor hat Betty die Reise abgelehnt. 
- [ ] Mit Abgabe des Geschenks war das Spiel beendet. 
- [ ] Nach dem Abspann konnte man entscheiden, ob man weitermachen oder wirklich aufhören möchte. 
- [ ] Die Hochzeitsreise hat demzufolge auch kein <3-Bonus gegeben. 
- [ ] Die Hochzeitsreise muss vom Verkäufer natürlich notfalls wieder zurückgenommen werden können. (damit wäre "PGH" ausgeschlossen oder zumindest nicht im Sinne des Spielers. ;) ).

**Comment by nittka** [comment]
Bis auf die Punkte zur Hochzeitsreisesonderbehandlung habe ich die Punkte umgesetzt. Die Dialoge mit Betty bzgl. Geschenk sind auch noch nicht angegangen.

**Comment by GWRon** [comment]
Da kommst Du wohl noch auf die "gut"-Liste vom Weihnachtsmann.

Danke.

**Comment by GWRon** [comment]
@Nalindir 
Hast Du Dir die aktuelle Fassung mal anschauen koennen? Sind wir jetzt schon naeher an Deiner Idealvorstellung?


@nittka 
Hmm also sollten wir einen Hochzeits/Eheringe/Du-hast-Gewonnen Bildschirm einbauen und einen Dialog (nach ein paar Sekunden), ob man weiterspielen will, oder zurueck ins Hauptmenue?

**Comment by nittka** [comment]
Eine Alternative zum automatischen MadTV-Ende wäre auch, dass man nach Erreichen der 100% Betty erst noch einen Heiratsantrag machen muss, der dann das Spiel beendet... Dann hat man es selbst in der Hand, ob man weiterspielen möchte oder nicht. Heiraten und dann 24 Stunden am Tag weiterarbeiten passt irgendwie nicht zusammen ;-)

Aber egal in welcher Variante braucht es wohl ein "Abschlussbild".

**Comment by nittka** [comment]
Der letzte Punkt wird im Missionsticket weiterverfolgt.
