### ISSUE TITLE
Fehler beim Auflösen von Variablen in Drehbüchern

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#1244]
Auf dem aktuellen Masterstand werden im Spiel die Varibalen (nicht nur) für "Typentausch" nicht aufgelöst. Beim Erstellen der Drehbücher im Testscript ist das nicht aufgefallen. Die Variablendefinitionen in der Datenbank sehen OK aus.
* Testscript fehlerhaft?
* Drehbucherstellung im Spiel anders als im Testscript?

Ursache könnte die Umstellung für die globalen Variablen sein (Optimierung für lowercase-Variablen).

**Comment by GWRon** [comment]
HasVariable verhaelt sich doch wie erwartet - es schaut in "variables" nach, ob der angegebene Variablenname dort vorhanden ist.

**Comment by nittka** [comment]
Ich wollte nicht sagen, dass hasVariable falsch ist. Ich wollte sagen, dass im Kontext gameexpression nicht das erwartete Ergebnis kommt. HasVariable liefert false, obwohl die Variable mit dem Kontext aufgelöst werden kann (weil der Parent die Variable definiert).

**Comment by nittka** [comment]
Ein hotfix behebt das Problem zunächst. Die im PR angesprochenen Ansätze für eine saubere Lösung müssen geprüft werden.
