### ISSUE TITLE
Absturz bei KI-Spielerbankrott mit unfertigem Seriendrehbuch im Besitz

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#1254]
Discord-User Eggi hat einen Speicherstand bereitgestellt, der 24 Uhr / Tageswechsel abstürzt (hey, er ist an Tag 201!)

Es stuerzt ab, da "licence" hier null ist:
```
		'a series becomes tradeable only if it is completely produced (or the script is thrown away)
		if script.isSeries() And script.usedInProgrammeID
			local licence:TProgrammeLicence = GetPlayerProgrammeCollection(currentOwner).GetProgrammeLicence(script.usedInProgrammeID)
			if licence and not licence.hasLicenceFlag(TVTProgrammeLicenceFlag.TRADEABLE)
				licence.setLicenceFlag(TVTProgrammeLicenceFlag.TRADEABLE, True)
			end if
			
			'correct episode numbers and total episode count
			'(they might just have produced 1,3 and 4 of 6 episodes)
			licence.CompactSubLicences()
		endif
```

![image](https://github.com/user-attachments/assets/941604cc-68d3-4582-8524-acca30749612)

hier ist ersichtlich, dass es bei der ResetPlayer (durch den Bankrott ausgeloest) Funktion passiert.

und zwar hier:
```

		For Local script:TScript = EachIn scripts
			'remove script, sell it and destroy production concepts
			'linked to that script
			programmeCollection.RemoveScript(script, True)
			TLogger.Log("ResetPlayer()", "Sold script: "+script.getTitle(), LOG_DEBUG)
		Next
```
Das ist an sich _bevor_ es die eigenen Programmlizenzen verkauft - es scheint also vorher schon die entsprechende Lizenz nicht mehr zu haben.

@nittka 
Klar koennte ich jetzt ein `If licence Then licence.CompactSubLicences()` draus machen ... aber fraglich ist fuer mich:
- sollte der Spieler das Programm noch haben?
- wenn nein: sollten wir dann die Lizenz nicht lieber aus der ProgrammeCollection generell holen anstatt vom Spieler?
- wenn ja: wieso hat er sie nicht mehr?

Edit/PS: der Abruf ueber GetProgrammeLicenceCollection() und der Check ob "ist licence ueberhaupt existent" hat den Absturz wie erwartet behoben - bleibt offen, ob das richtig vorgegangen ist.

**Comment by nittka** [comment]
Das erste Codesnippet ist an sich "inkonsistent". Für die Flagänderung wird geprüft ob licence existiert (also wird angenommen, dass das nicht der Fall sein könnte), für compactLicence dann nicht mehr - entweder für beide prüfen oder für beide nicht.

Wenn der Spieler die Lizenz schon nicht mehr hat, sollte auch keine Aktion mehr nötig sein (muss ggf. grundsätzlich beim Verkauf einer Lizenz ein compactLicences aufgerufen werden, denn der Verkauf kann ja ggf. auch ohne Spielerbankrott erfolgen - nicht fertig produzierte Serie verkaufen).

Ich könnte mir vorstellen, dass das genau der Hergang ist. Spieler kauft Seriendrehbuch, prodiziert was und verkauft dann die Serie und geht bankrott. Das würde erklären, warum die Lizenz nicht in der Playercollection ist.
Hat die Serie denn in der GesamtCollection noch existiert? Wenn nicht, habe ich erstmal keine Idee, wie es dazu kommt (nicht handelbar nach Verkauf, darum komplett entfernt?)

Wenn eine Lizenz ganz komplett aus der Collection entfernt wird, müsste sie auch aus den "usedInProgrammeID" entfernt werden, oder das Script zur Lizenz muss auch vom Player gelöscht werden, wenn die Lizenz verkauft wird (er kann ja nicht was weiterproduzieren, was ihm nicht mehr gehört)...

**Comment by GWRon** [comment]
Die Serie ist in der ProgrammeCollection vorhanden, in der PlayerProgrammeLicenceCollection allerdings nicht.
Der Owner ist noch immer 4 (der Spieler, der bankrott geht).

Das Spiel wurde in 0.8.2 gespielt - evtl ist also ein mittlerweile gefixter Bug Schuld.


## Drehbuch entfernen wenn Lizenz verkauft/entfernt wird

Kann (bzw. koennte in der Zukunft) ein Drehbuch fuer mehrere "Einzelproduktionen" zum Einsatz kommen? Wenn wir garantieren koennen, dass dies nicht der Fall ist, dann spricht nichts dagegen, bei PlayerProgrammeLicenceCollection()-Lizenzentfernung zu schauen ob noch Drehbuecher dazu im Spielerbesitz sind - und sie zu entfernen (allerdings dann Obacht, wenn im Studio hinterlegt etc).
Allerdings: sollten diese Lizenzen denn nicht als "nicht tradeable" markiert sein? Also der Code sagt: unvollstaendige Serien sind nicht verkaufbar.

Was hier die Frage aufwirft: was passiert mit einer unfertigen Serie, wenn man das Drehbuch verkauft/wegwirft/zerstoert ? Sie ist ja dann als "nicht handelbar" markiert.
Ich bin mir nicht sicher, ob dann "compact" stattfinden sollte und die Serie als handelbar markiert werden muesste.
UND ... ich wuerde einer solchen Serie gerne einen "Daempfer" verpassen. Sie hat einen Malus bei der Attraktivitaet ("Serie mittendrin abgesetzt, Cliffhanger").

## Unfertige Serie verkauft

Das sollte an sich derzeit nicht moeglich sein - allerdings ... geht mir irgendwas durch den Kopf -- er ist an Spieltag 201. Es wird schon einige Bankrotte gegeben haben ...

Waehrend eines Resets:
```
		For Local licence:TProgrammeLicence = EachIn licences
			programmePlan.RemoveProgrammeInstancesByLicence(licence, True)
			If licence.sell()
				TLogger.Log("ResetPlayer()", "Sold licence: "+licence.getTitle(), LOG_DEBUG)
			Else
				TLogger.Log("ResetPlayer()", "Cannot sell licence: "+licence.getTitle(), LOG_DEBUG)

				'absolutely remove non-tradeable data?
				'for now: no! We want to be able to retrieve information
				'         about these licences.
				If Not licence.isTradeable()
				'	GetProgrammeLicenceCollection().RemoveAutomatic(licence)
				'	GetProgrammeDataCollection().Remove(licence.data)
				EndIf
```
Kann es sein, dass er in seinen Logs mal "cannot sell licence" gehabt hat ("vor vielen Spieltagen") ?

Eine solche Lizenz bleibt ja im .. indirekt im Besitz des Spielers ("owner = 4"), ist also zumindest dem Spieler "zugewiesen" ohne am Ende in seiner Collection (die ja eh erneuert wird) zu sein. Die generelle Lizenzcollection enthaelt also diese unfertige Serie mit "owner = 4", die Collection des Spielers aber nicht.

Aber das eroeffnet die Frage, wie der neue Spieler 4 in den Besitz des Drehbuchs gekommen sein kann.

**Comment by nittka** [comment]
Da das ursprüngliche Snippet im playercollection-Code steht, würde ich dort das Sicherheitsnetz analog des Flags einbauen. Das ist auf alle Fälle korrekt.

Ob man beim Spielerbankrottaufräumen noch was ändern müsste, ist eine andere Sache.
Du kannst ja als Aktion bei X mal schauen, welche Lizenzen/Scripte in der allgemeinen Collection einen Spieler-Owner haben, die aber in der Collection des Spielers nicht vorkommen.

**Comment by GWRon** [comment]
Das mit dem Check ist eine gute Idee...mal sehen was heute Abend rauskommt.

**Comment by GWRon** [comment]
Ich hab zur "verwaistes Drehbuch"-Suche noch hinzugefuegt:
```
						if script.usedInProgrammeID
							print "Drehbuch von Spieler " + script.GetOwner()+": " + script.GetTitle() + " -> in Programm verwendet: " + script.usedInProgrammeID
							Local licence:TProgrammeLicence = GetPlayerProgrammeCollection(script.GetOwner()).GetProgrammeLicence(script.usedInProgrammeID)
							if not licence
								print "   -> nicht in Spielersammlung"
							endif
						endif
```
und sollte somit Drehbuecher bekommen, die "usedInProgrammeID" gesetzt haben.


```
Suche verwaiste Lizenzen..
Suche beendet.
Suche verwaiste Drehbuecher..
Drehbuch von Spieler 1: 5-Sterne Frühstück Deluxe -> in Programm verwendet: 4125289
   -> nicht in Spielersammlung
Drehbuch von Spieler 1: Gegenfeuer - Weltweite Einsätze -> in Programm verwendet: 2939559
Drehbuch von Spieler 4: Reise durch Dänemark -> in Programm verwendet: 22485
   -> nicht in Spielersammlung
Drehbuch von Spieler 1: Das Nerdgeschwader -> in Programm verwendet: 4239675
Drehbuch von Spieler 1: Fables (Staffel 2) -> in Programm verwendet: 3172568
Drehbuch von Spieler 1: Das Foucaultsche Schwingen -> in Programm verwendet: 4182112
Drehbuch von Spieler 1: Die Götterwelt von Tibet -> in Programm verwendet: 4404934
Drehbuch von Spieler 1: Leather Jacket Leo, Ladykiller -> in Programm verwendet: 4064179
Drehbuch von Spieler 1: Schweden von oben -> in Programm verwendet: 4006015
Drehbuch von Spieler 3: Blickpunkt Portugal -> in Programm verwendet: 123101
Suche beendet.
```

Eggi (Spieler 1) hat also selbst ein Drehbuch, was ein "used in Programme ID" hat ...und das Programm nicht in der Spielersammlung vorhanden ist...

![image](https://github.com/user-attachments/assets/bb4a1fb9-9004-4a08-8949-20ae1a630266)

Dabei handelt es sich um eine Live-Produktion:
```
[23:52:35] DBG      | TPRODUCTION.FINISHPREPRODUCTION(): Finishing preproduction: "5-Sterne Fruehstueck Deluxe - #74"
```

Die ID von dieser Produktion und "usedinProgrammeID" ist unterschiedlich.

![image](https://github.com/user-attachments/assets/b7782861-c362-4269-b6d5-63c2e12ccb62)

Ich vermute das Problem haengt damit zusammen, dass man da 100 Folgen mit produzieren kann.

@nittka weisst Du durch Zufall, ob das eine der Baustellen war, die sich seit 0.8.2 geaendert haben - dachte da war was.

**Comment by GWRon** [comment]
Zurueck zum originalen Code-Stueck (schon ein wenig angepasst..):
```

		'a series becomes tradeable only if it is completely produced (or the script is thrown away)
		If script.isSeries() And script.usedInProgrammeID
			Local licence:TProgrammeLicence = GetPlayerProgrammeCollection(owner).GetProgrammeLicence(script.usedInProgrammeID)
			Local licence2:TProgrammeLicence = GetProgrammeLicenceCollection().Get(script.usedInProgrammeID)
			if not licence2 then debugstop
			If licence
				If Not licence.hasLicenceFlag(TVTProgrammeLicenceFlag.TRADEABLE)
					licence.setLicenceFlag(TVTProgrammeLicenceFlag.TRADEABLE, True)
				EndIf
			
				'correct episode numbers and total episode count
				'(they might just have produced 1,3 and 4 of 6 episodes)
				licence.CompactSubLicences()
			EndIf
		EndIf
```
Original wird also beim Spieler geschaut, ob er sie noch hat - und dann verkaufbar markiert - sowie die Episoden "komprimiert"

Nun sehen wir aber, dass es Drehbuecher gibt, die (dort noch ... wie gesagt, evtl war das jetzt schon geaendert) mehrere Episoden basierend auf einem einzigen Drehbuch ermoeglichten. Die Drehbuecher koennen aber nur ein "usedInProgrammeID" speichern .. sprich mit Fertigstellung (hier Ausstrahlung der Liveshow) aendert sich die "usedInProgrammeID" (getestet, ja aendert sich).

Hier kommt aber noch hinzu: die Programme haben nur eine (1x) Ausstrahlung - werden also danach auch aus der ProgrammeCollection entfernt.

-> Drehbuch besteht weiterhin (Spieler kann neue Folgen produzieren)
-> ausgestrahltes Programm (das was in "usedInProgrammeID" hinterlegt ist) wird entfernt (da nur 1 Ausstrahlung)

Fazit fuer mich waere: es kann Drehbuecher geben, die Lizenz-IDs hinterlegt haben, die nicht mehr im Spielerbesitz sind.
Wir koennen sie aber ueber die allgemeine ProgrammeLicence-Collection holen (theoretisch).
In dem Fall sollten wir nicht "tradeable" setzen (kann ja einen Grund haben ...)
Fraglich ist aber, ob wir CompactSubLicences ausfuehren sollten (in dem Fall hier, sollte es nix bringen, da ja die ausgestrahlte Lizenz eh "futsch" ist).

@nittka wie siehst Du das?
