### ISSUE TITLE
Parameters in time spans seem to be interpreted in the wrong way

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1257]
The news item "Dresdner Staatsoper wieder eröffnet" is defined with `happen_time="5,1984,1985,12,5,1,30"` but it appears (late) in the 9th month of 1985.

![staatsoper-time](https://github.com/user-attachments/assets/d61943ab-d1b4-4795-85bf-044eb0c3c309)

Also judging from other similar occurences, I think the parameters for the time parameter `5` are interpreted in the wrong way or not as expected. It seems it construes a general month span from 5 to 12 here, instead of a span from 1984-12 to 1985-5 as it would be intuitively expected.

**Comment by nittka** [comment]
Die Berechnung macht pro Attribut (Jahr, Monat, Tag) eine Auswahl zwischen Min/Max. Korrekt wäre, das minimale Datum und das maximale Datum zu berechnen und einen Zufallswert dazwischen zu nehmen.
