### ISSUE TITLE
Experimental VV: Balancing

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#126]
Wie schonmal besprochen, würde ich mich gern mal das Themas Balancing annehmen. 

Akutell kann man nach gut 30-40 Ingame Tagen selbst auf "schwer" den Status erreichen: 
- Millioneneinnahmen in einer Größenordnung, wo Werbung gecapped wird. 
- Durch das Cap lohnt sich der Ausbau der Sender nicht mehr. 
- Erhöhung des Reichweitenlevels führt nur zu einem Anstieg er Filmkaufpreise
- Der Fokus liegt auf Eigenproduktionen, aber die glänzen vor allem durch Wiederholungen (TVT: Drama im Hochhaus #22)
- Image 100% 

usw.

Gerade bei Inhalten die auf Langzeit angelegt sind, wie z.b. das Leveln von Darstellern, Studios, etc. oder dem Ziel mal ganz Deutschland zu versorgen, oder 1985 zu starten und irgendwann mal in den Genuss von Filmen in den 1990ern und 2000ern zu kommen, ist die Luft dann doch schnell mal raus. 

Ich würde daher gern mal an ein paar Schrauben drehen wollen. Dabei ist der größte Boost aktuell tatsächlich der Schnelle Ausbau der Sender. Ich habe mal ein Spiel gestartet, wo ich nur Filme gegangen bin und den Ausbau der Sender gezielt außen vor gelassen habe. Das Archiv füllt sich recht schnell mit minderwertigem Trash, was gut ist für Wiederholungen und das Non-Primetime Programm um eine Basis für die hochwertigen Filme zu legen. Das Geldniveau bleibt dabei auch nach 10 Spieltagen auf niedrigem Niveau. 

Ich denke daher, dass der Ansatz vor allem im Senderausbau zu suchen ist. Dazu kommen aber noch andere Faktoren, an denen man drehen kann. Die folgenden Stellschrauben habe ich für den Anfang identifiziert, bei denen ich die Möglichkeit sehe, im Sinne von Balancing was erreichen zu können. Nicht alle würde ich sofort einsetzen wollen. 

Mein erster Aufschlag sieht daher folgende Anpassungen, bei denen auch nach Schwierigkeitsgrad unterschieden werden soll. Mein Fokus, bzw. die gravierendsten Einschränkungen liegen dabei auf "schwer", da leichtere Modi in der Natur der Sache nicht die gleiche Langzeitbeschränkungen haben werden, wie der höchste Schwierigkeitsgrad. 

![balance1](https://user-images.githubusercontent.com/57690824/70134675-d7329080-1688-11ea-9386-7b92dee225c4.JPG)

Du wolltest mir mal nen private Branch mit den Anpassungen erstellen, mit denen ich weiter probieren kann. Hat keine Eile, aber damits auch nicht verloren geht, platzier ich das mal hier.

**Comment by nittka** [comment]
Ich habe zumindest auch Forumsartikel gesehen, aus denen hervorgeht, dass das Spiel auf Dauer nicht herausfordernd genug ist. Hier ein paar weitere Ideen, welche Stellschrauben ich grundsätzlich sehe und worin sich die Level unterscheiden könnten (Ideenliste nicht vollständig).

## Zeit
Wenn über die Dev-Keys die Zeitsteuerung nicht anpassbar ist, kann in schwereren Level die globale Zeit in jedem Tempo-Level etwas schneller laufen, die Spielerbewegung aber vergleichsweise langsamer sein.

## Senderbeliebtheit
Ich glaube, ein wichtiger Faktor für die Langzeitanreize muss die Senderbeliebtheit sein. Es muss schwerer werden, je höher der Wert ist - man muss das gute Image wahren. Schlechte Sendungen werden einem schwerer verziehen, nicht aktuelle / Nachrichten wirken sich stärker negativ auf die Einschaltquote aus.

## Programmbeliebtheit
Grundsätzlich: mit jeder Wiederholungen steigt die Aktualität langsamer wieder an. Mit steigender Senderbeliebtheit ebenfalls (beliebte Sender haben es schwerer Wiederholgungen zu senden). Weiterhin sinkt mit Wiederholungen der Maximalwert der Aktualität (Wiederverkaufswert sinkt).
Die Raten unterscheiden sich dann nach Schwere-Level (z.B. leicht=Faktor 1 - d.h. kein Aktualitätsverlust, schwer=0.8 Aktualität erholt sich mit jeder Wiederholung nur auf 80%). Nach sehr langem Nichtsenden könnte die Aktualität wieder auf das Ursprungsniveau zurückkommen.
Je beliebter man ist, desto *länger* dauert es bis dieses Niveau wieder erreicht ist.
Das erhöht den Druck, das Archiv auszubauen. Aktuell ist es eher so, dass man einmal einen Fundus aufbaut und diesen dann immer mit maximaler Aktualität ausstrahlen kann.

## Werbung
Eine tolle Verbesserung im Vergleich zum Original ist das "Aufwerten" der Werbung je nach Reichweite (selber Werbender, unterschiedliche Konditionen). Eine Erschwerung kann auch erreicht werden, wenn dieses Update mit dem Sendemastkauf kommt. Dann kann man einen Vertrag, der zu scheitern droht, nicht mit dem Erweitern der Zuschauerzahl reparieren. Im schlimmsten Fall drohen noch höhere Strafen (der Vorteil der höheren Einnahmen ist aus meiner Sicht fast vernachlässigbar). Dieses Auto-Upgrade der Werbung kann auch level-abhängig sein; nein bei leicht, ja ab mittel.

Auch unabhängig des Level-Balancing gibt es mögliche Stellschrauben bei der Werbung.
* Genre-Forderungen wie im Original (Kultur oder Live-Show, keine Kömödie, Eigenproduktion)
* geforderte Sendezeit (zw. 13 und 19 Uhr; nur prime-Time)
* maximale Anzahl von Wiederholungen der Sendung (max 3. Ausstrahlung)
* Bonus-Zahlungen für Erstausstrahlung
* Abzug für Wiederholung (0.85 hoch <Anzahl Wiederholung>)

Es wurden auch Werbeabonnements vorgeschlagen. Das finde ich einen interessanten Ansatzpunkt, aber nicht nur, um sich "gute" Werbung zu sichern, die man nicht immer neu holen muss.
Wenn man eine Werbung abonnieren will (Stellschrauben
* steigen die Strafzahlungen
* sinken die Einnahmen
* sinkt die verfügbare Zeit für die Ausstrahlung
* höhere Quote nötig
Dann muss man sich nämlich genau überlegen, welche Abonnements sich rentieren.

## Miete
Aktuell verursachen "nur" die Sender, die Studios und abonnierte Nchrichten laufende Kosten. In schwereren Levels könnte auch die Größe des Fundus zu "Mieterhöhungen" führen. Was ist mit Inflation (grundsätzlich steigende Kosten).

## "Schikanen"
"Ruhetage", reguläre Pausen für Räume. Analog des Terroristen kommte es vor, dass die Werbeagentur oder die Filmagentur für ein paar Stündchen geschlossen ist.
Geringere Zinsen für Guthaben (Negativ-Zinsen?).
Dieb (klaut Geld aus dem Tresor/Filme). Anstellung eines Sicherheitsdienstes, um das zu verhindern, der aber wieder laufende Kosten verursacht.

Eine echte Herausforderung könnte sein, dass die Werbung zu Beginn der Ausstrahlung eines Programms geplant sein muss (z.B. leicht=keine Blockierung, mittel=folgender Werbeblock blockert, schwer=nächste 2 Werbeblocks blockiert). Dann kann man nicht nachträglich optimieren, sondern muss ggf. konservativ schätzen, wie die Einschaltquote sein wird - und riskiert damit Einnahmeausfälle und Strafen. Das führt wahrscheinlich zu mehr Speichern und nochmal Laden, aber wenn man nicht schummelt, wird es echt herausfordernder.
... das ganze vielleicht sogar in Kombination mit dem Programm selbst. Dann muss man sowohl Filme als auch Werbung früher geholt haben.
Was wäre, wenn die Anzahl der vorzuplanenden Blöcke sogar mit der Beliebtheit steigt (die Leute wollen früher wissen, was kommen wird). In diesem Fall würde ich aber den Planungshorizont von Programm und Werbung voneinander trennen.

## KI
Ich habe das Verhalten der KI-Spieler nicht wirklich in den unterschiedlichen Level analysiert, aber es scheint mir nicht nötig, dass sie im Level leicht künstlich ausgebremst werden muss. Warum gehen sie im Level leicht ständig pleite, warum kommen sie im Level mittel selbst nach 60 Tagen nicht auf eine Beliebtheit >5%. Ich denke nicht, dass sie perfekt spielen sollen (genaue Vorausberechnung der Quote für jede Sendung und entsprechende Werbeplanung), aber extra-doof müssen sie auch nicht sein.

**Comment by nittka** [comment]
Bezüglich des initialen Themas scheint ein größerer Umbau nötig, da die gamerules für jeden Paramter nicht nur einen Wert, sondern einen Wert pro Schwierigkeitsgrad des jeweiligen Spielers zur Verfügung stellen müssten. Entsprechend sollte die config-Datei syntaktisch erweitert werden. Pro Knoten müsste nicht nur value sondern auch easy, normal, hard konfigurierbar sein, um testweise Anpassungen ohne Release zu ermöglichen. (Kompatibilität Altspielstände)

Unabhängig vom Experimentieren halte ich diese Anpassung für grundsätzlich sinnvoll. Diese Werte sollten also vielleicht von Rules nach PlayerDifficulty wandern (und die dort schon vorhandenen Werte analog konfigurierbar gemacht werden).

**Comment by nittka** [comment]
Ich habe in #554 eine Basis geschaffen, zumindest einen Teil der oben genannten Anpassungen in die Konfiguration der Schwierigkeitsgrade zu integrieren.

**Comment by nittka** [comment]
Mein Eindruck ist, dass das Entfernen (bzw. Erhöhen auf 10Mio) des Werbeertragsdeckels (scheinbar) gar keinen so großen Unterschied macht. Tag 1, Image auf 50 % gesetzt, Sender gekauft bis Reichweite 40 Mio erreicht waren. Selbst eine Werbung, die 9Mio Zuschauer als Mindestzuschauerzahl hat, kommt dann gerade an einen Profit von 2Mio heran.

Auch wäre es mit Deckel ggf. sinnvoll, die Reichweite weiter auszubauen, da man ja dann den Maximalertrag bei mehr Sendeblöcken erreichen kann. Wenn man Spielziele einführt, wäre der Deckel weiterhin ein valides Mittel, die Schwierigkeitsgrade zu unterscheiden (leicht 2 Mio, mittel 1Mio, schwer 800K). Ziel des Balancings wäre, die Werte so zu wählen, dass man immer optimaler Werbung platzieren muss, um das Spielziel zu erreichen aber gleichzeitig die laufenden Kosten zu decken.

**Comment by nittka** [comment]
Ich habe lokal mal die Berechnung der Werbeerträge geändert. Statt des Deckels wird ab 10% Sendegebietsabdeckung der Faktor für die Berechnung der Werbeprämie schrittweise reduziert. Damit verdoppelt sich der Gewinn nicht mehr bei Verdopplung der Reichweite.

Ich habe im Testspiel auch die Kaufpreise für Sender (Faktor 1.5) und die laufenden Kosten (20% + leichter täglicher Anstieg) erhöht. Die KI mit der suboptimalen Filmauswahl hat dennoch einen Ausbau auf das gesamte Sendegebiet geschafft, so dass man diese Werte durchaus für "normal schwer" nehmen könnte und die aktuellen für leicht.

Gleichzeitig habe ich mir eine Statistikdatei für die Auswertung durchschnittlicher laufender Kosten/Gewinne etc. ausgeben lassen. Die Auswertung lässt vermuten, dass die alternative Berechnung der Werbeerträge in dieser oder ähnlicher Form vertretbar ist. Getrübt ist die Auswertung dadurch, dass (auffällig insb. zur Prime-Time) die Berechnung der möglichen Zuschauer kaputt ist (70Mio Sendegebiet, 50% möglich = 80 Mio Zuschauer), was die Werbeeinnahmen für diese Zeit verzerrt.

**Comment by nittka** [comment]
Konfiguration der Spielstärkelevel ist nun möglich.
