### ISSUE TITLE
Release v0.8.3

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#1273]
@nittka  und @scr0llbaer9000 

Ich mache jetzt noch ein paar Weihnachtsessenvorbereitungen. Die Buildsysteme fuer Windows, Mac und Linux habe ich aktualisiert und Testkompilate durchgefuehrt.

Wenn bis sagen wir ... 16 Uhr keine Einwaende von Euch kommen, wuerde ich dann ein Release zusammenschrauben und v0.8.3 veroeffentlichen.

**Comment by scr0llbaer9000** [comment]
Ja, irgendwo muss man ja mal 'nen Cut machen.

Vergiss nicht das Jahr in `LICENCE.txt` upzudaten damit nicht ich das wieder nachholen muss `;)`

Und nicht den Cheat-/Dev-Mode by default (auf Linux?) enablen.
