### ISSUE TITLE
Prematurely abandoning / disappearing news threads

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1276]
So this problem has always been around forever. Some news threads disappear sometimes and never pop up again.

[news-test-4.zip](https://github.com/user-attachments/files/18261178/news-test-4.zip)

* News thread `48feebb0-4ef2-419b-8342-aa6376a4f246` ("${meiguwu} Top 5 Entwicklungsregion") has disappeared in savegame `news-test-4-e.zst`. Last seen instance in savegame `news-test-4-c.zst` ("${meiguwu} baut Eiffelturm nach"). It happens often, but not always that this news thread disappears, so not easily reproducible.

* News thread `cujo-news-superkerl` ("${superwoman} verliebt sich in ${superguy_acc}") also has disappeared in this campaign early on, not finishing. Maybe it can be examined what the state of these news threads is (i.e. why they are not picked up again). Although this thread usually finishes, what's reproducible with this one in *every game* is that the thread only appears once in the game, although it doesn't have `flags="2"` anymore. I think there are more threads like this which appear only once for no explicable reason, unnecessarily contributing to news scarcity.

Note: I'm fast-forward pay-testing here. Maybe it's less an issue when playing normally.

**Comment by GWRon** [comment]
file "news-test-4-e":
The news thread `48feebb0-4ef2-419b-8342-aa6376a4f246` seems to be referenced multiple times in the XML.

It will require some more indepth check to understand what is happening, and/or to check if eg the news chain won't start again as it did not "finish" yet or similar stuff.

**Comment by scr0llbaer9000** [comment]
> seems to be referenced multiple times

It's just one but very long thread and only linear.

**Comment by GWRon** [comment]
yes ... what I mean is: the news stuff defined in XML is "there", just ruled out that the data itself is purged somehow.

**Comment by GWRon** [comment]
Ok, so what do we do with the GUIDs? With the GUIDs we can check what ID is used for the newseventtemplate (this is what you define in the XML at the end).
And then we can check if there exist TNewsEvent-instances (the actually happening news event based on the template) with their templateID property corresponding to the one of the desired template.

news-test-4-c contains:
TNewsEvent: 220848bb-6820-4a72-8bc8-3976427a4d8b-instance1  (ID: 77039)
it contains the trigger for news 8f712f37-afbc-4671-97e9-513c2a23530d  (ID: 23379)

(resulting in this:)
TNewsEvent: 8f712f37-afbc-4671-97e9-513c2a23530d-instance1 (ID: 84627)
it contains the trigger for news 799c8a9a-adf5-47fd-868e-5b5441b3d20d (ID: 23380)

There is no instance yet created for this one ... so either already bugged there, or simply "not yet the time (did not check that yet).


news-test-4-e contains:
77039 - nope, not there anymore (so instance is missing)
23379 - yes, so template still there
23380 - also there.

Somehow I guess some "old news events" are purged while their "effects" were not run.


Reminder @nittka  - I think "once run one-shot-effects" should possibly be removed from TNewsEvent instances (they are not of use there at the end)

**Comment by GWRon** [comment]
@nittka it happens in the "onHour" functionality (main.bmx)

```
		'=== REMOVE ENDED NEWSEVENTS  ===
		'newsevents might have a "happenedEndTime" indicating that
		'the event is only a temporary one (eg. storm warning)

...
		'NEWSEVENTS
		'remove old news events - wait a bit more than "plan time"
		'this also gets rid of "one time" news events which should
		'have been "triggered" then
		Local daysToKeep:Int = 3
		GetNewsEventCollection().RemoveOutdatedNewsEvents(daysToKeep)
		'remove from collection (reuse if possible)
		GetNewsEventCollection().RemoveEndedNewsEvents()
```

**Comment by GWRon** [comment]
The news in savegame "4 c":
TNewsEvent: 8f712f37-afbc-4671-97e9-513c2a23530d-instance1 (ID: 84627)

NEWS EVENT: Shurankuwu: Neuer riesiger Vergnügungspark
- has happened: 0
- happen time: 25/18:05 (23.01.1987)
- now: 21/07:19 (10.09.1986)

... when now fast forwarding and observing "doHappen()" ... then this is not triggered for this news event.

And then checking when doHappened is called at all ...:
- AnnounceNewsEventToPlayers()
- ScheduleTimedInitialNews()
- PrepareNewGame() (start news)
- TNews.Create() (when a random news is choosen)

So ... seems "doHappen()" is not executed for "just happening" news at all!

**Comment by scr0llbaer9000** [comment]
It also does work other times in other campaigns and the thread finishes.

Glad then it's reproducible for this instance.

**Comment by GWRon** [comment]
Ahhh ... I understand what is happening (at least I think so):

At certain times the list "upcoming news" is invalidated / recreated. When it is recreated it only adds again the news events which return False for `HasHappened()` ...

And at certain times there is:
```
		For Local newsEvent:TNewsEvent = EachIn GetNewsEventCollection().GetUpcomingNewsList()
			'skip news events not happening yet
			If Not newsEvent.HasHappened() Then Continue
```
So if the list was invalid there ... it gets recreated in the `GetUpcomingnewsList()`.

What happens here is: The news is scheduled for 18:05, the upcoming list just was invalidated and gets recreated.
It now just contains news not having have happened at 18:05 ... but our news already happened just now.

This leads to this news being skipped.

In essence this means that the lazy getter leads to all news being "skipped" which happen between "last upcoming list invalidation" and next recreation of it (via GetUpcomingNewsList()).


A quick fix would be to recreate the list right when invalidating (but we do this to eg enable invalidating it 20 times in a row without having to recreate 20 times).
another one is to store the time of the last invalidation ... and take this as the time-to-use when checking what to readd.

**Comment by nittka** [comment]
> it happens in the "onHour" functionality (main.bmx)

(In theory) Delayed effects should already have been triggered/scheduled, so removing an outdated news event should not affect follow-up news at all.

**Comment by GWRon** [comment]
> > it happens in the "onHour" functionality (main.bmx)
> 
> (In theory) Delayed effects should already have been triggered/scheduled, so removing an outdated news event should not affect follow-up news at all.

See further replies.

In this case the cache invalidation happens there:
25/18:05 (23.01.1987) - ProcessNewsProviders, _InvalidateUpcomingNewsEvents()

And right afterwards it would recreate the upcoming news events but now the news has happened already and thus is ignored.

**Comment by nittka** [comment]
Cleanup of ended and outdated news could also happen less often - once a day could be enough (not on daybegins as too much is happening then anyways.
Cleanup of effects must be thoroughly checked:
* are the effects executed on the news event - possibly no cleanup necessary as the event will be removed at some point
* are the effects executed on the news template - no cleanup possible even for one-shot effects as they would be needed for another instance of the template
