### ISSUE TITLE
Werbung als Dauerwerbesendung schaltet nicht mehr auf x€/1k Zuschauer

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#128]
Platziert man eine Werbung als Dauerwerbesendung, sollte diese in den Modus umschalten, bei der angezeigt wird, wieviel Geld man pro 1000 Zuschauer erhält. Das passiert nicht mehr in der letzten Dev-Version (07.01.2020, Discord). Die Anzeige ist identisch zum Werbeblock. 

![grafik](https://user-images.githubusercontent.com/57690824/72346930-3ac3cb00-36d7-11ea-8737-7ee48c785a7a.png)

Getestet mit brandneuem Spielstand.

**Comment by GWRon** [comment]
Variablendreher :)

**Comment by nittka** [comment]
Ich kann den Fehler im aktuellen Masterstand nicht reproduzieren.
