### ISSUE TITLE
Followup zu Sendemastenauswahl über Karte: Highlight in Tabelle fehlt

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#129]
Follow Up zu Issue #110: Wählt man einen Sendemasten über die Tabelle, wird er gelb gehighlightet. Wählt man einen Sendemasten über die Karte, fehlt die Markierung in der Tabelle bzw. es bleibt die Markierung des zuletzt gehighlighteten Sendemasten. 

Eventuell ists mit wenig Aufwand möglich, den Tabelleneintrag zu markieren, wenn der Sendemast ausgewählt wurde und bei vielen Einträgen in der Tabelle auch zu dem markierten Eintrag zu springen?

Falls zu aufwändig, schließt den Eintrag. Ist wirklich nur Kosmetik.

**Comment by nittka** [comment]
Ist gelöst und kann geschlossen werden.
