### ISSUE TITLE
ungewollte Aktivierung der nächsten Nachrichtenkategorie

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#132]
Erstmal vielen Dank für die großartige Arbeit! Ich habe das Remake erst kürzlich entdeckt und bin begeistert. Aktuell bin ich unter lubuntu mit der letzten im Forum zu findenden Entwicklerversion unterwegs (2019-12-07).

Wenn sich der Mauszeiger im Nachrichtenbüro über einer Nachrichtenkategorie und man das Büro durch Rechtsklick verlässt, wird vor dem Verlassen noch auf das nächste Level geschaltet.
Die Kategorie-Buttons sollten ausschließlich auf einen regulären Mausklick reagieren.

**Comment by GWRon** [comment]
Schau ich mir an...

**Comment by nittka** [comment]
Behoben mit https://github.com/TVTower/TVTower/commit/52d71b7bd51c39de886551bca4ad5a874a8c61e7
