### ISSUE TITLE
Info-Icon in Finanzen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#133]
Das Info-Icon für die Sendestationen in den Finanzen ist (bei mir) abgeschnitten. Ggf. sollte es unmittelbar in der "Zeilenüberschrift" angezeigt werden.
![finanzen](https://user-images.githubusercontent.com/2562651/94665409-642b9200-030c-11eb-94fc-1b7ef2d3116a.jpg)

**Comment by GWRon** [comment]
Das ist Absicht... spart Platz und ist trotzdem noch erkennbar.

**Comment by nittka** [comment]
OK - es wirkt halt ungewollt und direkt hinter "Sendestationen" ist massig Platz.
