### ISSUE TITLE
Pfeiltasten-Steuerung für Sendemastplatzierung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#134]
In der Originalvariante fand ich die Möglichkeit, Sendemasten über die Pfeiltasten zu platzieren sehr hilfreich. Ich weiß nicht, ob sich die finale Version hier von der Entwicklerversion unterscheiden wird...
Aber eigentlich würde ich mir diese Möglichkeit grundsätzlich wünschen - für ganz feine Unterschiede ist die Maussteuerung einfach nicht so gut geeignet.
(shift-arrows oder Steuerung der Spielgeschwindigkeit auf dieser Seite nicht über Pfeiltasten?)

**Comment by GWRon** [comment]
Hmmm ...und der Mauszeiger, sollte der mitwandern oder ist das ein anderer "Modus" ("Feinjustierung")?

**Comment by nittka** [comment]
Nein, wie im Originalspiel würde der Mauszeiger mitwandern. Bewegungen um "einzelne Punkte" bekommt man mit der Maus einfach nicht so genau hin. D.h. es geht nicht um eine höhere Auflösung, als mit der Maus.

**Comment by nittka** [comment]
Die Positionierung des Sendemasten sollte nun mit den Pfeiltasten gehen. Soll die Position noch fixiert werden können? Z.B.mit Leertaste, da die Entertaste dem Chat vorbehalten ist.
Ansonsten würde ich dieses Ticket als gelöst betrachten.
