### ISSUE TITLE
Filmkategorie-Icons im Filmauswahl

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#135]
Die Markierungen der Filme nach Kategorie in der Filmagentur finde ich sehr gut. Wäre es möglich dieselbe Markierung bei der Filmauswahl im Büro anzuzeigen (um Kategorie und Icon schneller/leichter zusammenzubringen)?

**Comment by nittka** [comment]
Ich habe gesehen, dass die Sprites für die Kategorien nicht separat sind, sondern in verschiedenen Variante für die "Hochkant-Schuber" vorliegen. Der Aufwand das für die "liegende" Auswahl im Büro umzusetzen scheint mir unverhältnismäßig. Also Prio ganz niedrig.

**Comment by GWRon** [comment]
Also man koennte die zu einem "Overlay" umbauen ... und dann sicherstellen, dass sie in der Hoehe nicht groesser ausfallen, als die von den Kategorie-Slots. Dann waere das denke "machbar".

**Comment by nittka** [comment]
Ich schließe das Ticket mal. Der Umbauaufwand scheint mir nicht gerechtfertigt.
