### ISSUE TITLE
Absturz bei Beobachten der KI

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#136]
(unwesentlich) Wenn ich eine KI beobachte, stürzt das Spiel ab. Relativ zuverlässig scheint das der Fall zu sein, wenn der Spieler ins Büro geht und ich dann den Computer aufmache (das passiert scheinbar nicht automatisch, obwohl die KI das machen dürfte?)  um die Programmplanung zu sehen.
Vermutlich erfolgt dann der Absturz, wenn die KI das Büro verlassen will, ich aber noch am Computer sitze.

**Comment by GWRon** [comment]
Kann ich, denke ich, Beheben :).

**Comment by GWRon** [comment]
Hmm - ich komme gar nicht bis zum "Computer".

Spiel starten
linkes Strg + O
2

Ich beobachte nun Spieler #2. Geht er ins Buero - hab ich einen schwarzen Bildschirm (kein Raum wird angezeigt) bis zu dem Moment, wo der Spieler das Zimmer verlaesst.

**Comment by nittka** [comment]
OK. Dann war ich wohl gar nicht im Beobachtungsmodus. ich hatte einfach nur 2 (ohne Strg+O) gedrückt. Das zumindest funktioniert nun ohne Absturz. Ich sehe die Zimmer und kann sogar Werbung/Filme umsortieren.

Im Beobachtungsmodus sehe ich auch nur schwarz. Wie wichtig Dir das Thema ist, musst Du einschätzen. Prio für mich niedrig.
