### ISSUE TITLE
Shortcuts (/fast-forward) für reguläres Spiel

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#137]
Beim ersten Anspielen habe ich die Tastenkürzel für das Wechseln der Räume "zum Schummeln" verwendet, um mir schneller einen Überblick zu verschaffen oder noch schnell bessere Werbung zu besorgen...
Ich fände die Shortcuts aber auch für das normale Spielen sehr hilfreich:
Im Originalspiel hat der Fahrstuhl gewartet, bis man das Ziel ausgewählt hat. Nun muss man aber das Ziel wählen, bevor der Fahrstuhl überhaupt für einen hält. D.h. selbst wenn der Fahrstuhl gerade ein Stockwerk tiefer ist, gerade hochfährt und man schon an der Fahrstuhltür steht, ist man oft nicht schnell genug, noch das Ziel auszuwählen und mitzufahren. Das kann eine halbe Stunde oder mehr Spielzeit kosten.
(Für die KI hingegen scheint der Fahrstuhl manchmal sogar zu warten, während sie noch hinlaufen. Die Zielauswahl kostet hier wahrscheinlich gar keine Zeit.)

Hinter den Tastenkürzeln im regulären Spiel stelle ich mir ein Makro vor:
* verlasse den aktuellen Raum
* gehe zum Fahrstuhl
* wähle den entsprechenden Raum

In der 150%-Version dieses Features wäre während der Makroausführung ein Fast-Forward zuschaltbar, d.h. die Zeit vergeht rasend schnell, bis man beim gewünschten Raum ist (oder das Makro durch einen Klick an eine andere Stelle unterbrochen hat) und schaltet dann auf die vorige Geschwindigkeit zurück.
(Auf diese Weise lassen sich lästige Wartezeiten reduzieren, was man sonst durch manuelles Umschalten der Geschwindigkeiten erreichen muss.)

**Comment by GWRon** [comment]
Zwecks "Wartezeit-Fast-Forward", durchaus eine gute Idee, liesse sich (im "Rahmen") bewerkstelligen.

Ich muss hier aber noch kurz was "negativ wirkendes" erklaeren: Die KI bekommt "Ticks", an denen sie Aktionen ausfuehren kann. Diese Ticks erfolgen nach Spielminuten - und nach Echtzeit.
Es ist ein wenig wie mit menschlichen Spielern: Hast Du viel Zeit, hat auch die KI viel Zeit. Aber nun spulst Du vor - und der KI wird ein wenig die Zeit geklaut.

Oft ist das nur von geringem Einfluss - aber bei "Fast Forward" verpasst die KI eher mal einen Fahrstuhl (sie koennte ja abschaetzen, ob sie "zusteigen" kann etc). Oder sie hat eher mal Sendeausfall, da sie zu spaet "geschaut" hat.


Zum Fahrstuhl: der wartet auf niemanden "bevorzugt". Was er aber macht ist: Faehrst du vom Erdgeschoss in den 12. Stock, kann einer zusteigen, der vom 2. in den 5. fahren will ("keine Umwege"). Das geht natuerlich nur, wenn man das Ziel schon vorm "einsteigen" auswaehlt. Du kannst also nicht nur auf den Fahrstuhl klicken und hoffen, der Fahrstuhl haelt nun deswegen an. Das macht er nur, wenn du vor "Ankunft" an dieser (deiner) Etage schon das Ziel gewaehlt hast.

Zwecks "nicht schnell genug, noch das Ziel auszuwaehlen" - nun, das ist ja dann "Dein" Problem (bzw das der KI, wenn sie ebenfalls "Gedankenpausen" bei der "wo ist gleich der Raum?"-Suche machen wuerde). 

Warten kann der Fahrstuhl nicht auf den Spieler, da die KI nicht cheatet, sie "beamt" sich nicht in die Raeume. Ergo waere ein "Spielerfigur bevorzugt"-Modus absolut desastroes fuer die KI.
Das "Originalspiel" konnte das natuerlich anders handhaben ... hier wird aber weniger getrickst (KI muss selbst die Quoten abschaetzen etc).

**Comment by nittka** [comment]
Vielen Dank für die schnelle und umfangreiche Reaktion.

Ich wollte nicht unterstellen, dass der Fahrstuhl jemanden bevorzugt oder sich die Spiellogik irgendwo parteiisch verhält. Es *scheint* eben nur manchmal so, weil die KI einige Dinge viel schneller kann als ein menschlicher Spieler (Übersicht über alle angebotenen Filme/Werbung verschaffen, Fahrziel auswählen...). Insofern kann ich dem Argument, dass die fehlende Zeit "mein Problem ist" nicht vollständig zustimmen - die KI und ich haben physisch komplett unterschiedliche Voraussetzungen. Ich muss auf den Fahrstuhlknopf drücken, warten bis das Bild aufgeht, mit der Maus an die richtige Stelle und klicken. Das geht nicht in unter x ms *Realzeit*. Und für die KI ist dieses x mutmaßlich deutlich kleiner als für mich.
Die Problematik Echtzeit/Spielzeit ist mir - wenn auch natürlich nicht in allen Implementierungsdetails - durchaus bewusst. Und mir ist auch klar, dass es aktuell auch eine dramatische Benachteiligung in der anderen Richtung gibt (wenn ich einen Raum in Spielzeit lange blockiere, weil ich einfach mehr Realzeit brauche, um dasselbe Ergebnis zu erreichen wie die KI).

Zum eigentlichen Punkt: Mit Fast-Forward meine ich "Lasse die Spielzeit so schnell wie möglich vergehen, ohne dass die anderen Spieler dadurch benachteiligt sind.". D.h. alles im Spiel läuft entsprechend schneller ab (insb. Bewegungen etc.), die Rechenleistung für KI-Entscheidungsfindung darf aber nicht künstlich beschnitten werden. Im Prinzip also die Komfort-Funktion das anstrengende "Schalte auf Geschwindigkeit 3 bis ich am Ziel bin und dann wieder auf 1, damit ich in Ruhe die eigentliche Aktion machen kann".
(Nebengedanke: Analog dem Gehe-Zu-Raum-X-Makro könnte es eine "Lasse eine Spielzeit-Stunde so schnell wie möglich vergehen"-Aktion geben. Oft genug hat man seine Nachrichten und Werbung etc. für den aktuellen Block fertig und will sich ohne viel Realzeitverschwendung um den nächste kümmern - wieviele Zuschauer habe ich, kann ich noch eine bessere Werbung einsetzen.)

Und noch ein Nachtrag zum Thema Fairness: Wie gesagt ist die KI stark im Nachteil, wenn ich (selbst ohne Absicht - das wäre noch ein ganz anderes Thema) einen Raum übermäßig lange blockiere. Ein mögliche Abhilfe wäre hier, für einen Raum eine maximale Belegungszeit (in Spielzeit) zu haben. Danach hält die Spielzeit einfach an und wartet, bis der Spieler fertig ist und den Raum verlassen hat. Ich wage zu behaupten, dass die KI dadurch kaum den Spielfluss für einen menschlichen Spieler stören würden. Sie müsste aber selbst nicht zwei Spielzeitstunden warten, bis ich meine Einkaufsliste für einen Film zusammengestellt habe. Würde mir das Anhalten selbst einen Vorteil verschaffen? Möglicherweise einen kleinen, da ich z.B. in Ruhe die gesamte Werbung durchsuchen kann, um zu schauen, ob für den aktuellen Block noch was Besseres dabei ist. Mehr aber nicht, da ich keine Aktionen machen kann, als in dem Raum ohnehin möglich sind. Wenn die Zeit weiterläuft, *muss* ich mich beeilen. Insgesamt wäre es aber fair, da ich auf diese Weise auch keinen Raum "sinnlos" blockieren kann und es für alle besser planbar (=langweiliger?) ist. Max 7 Spielminuten für Werbung=max 21 Minuten warten, falls alle vor mir dran sind - lohnt es sich da nochmal loszurennen... Natürlich würde eine solche Maximalzeitbeschränkung nur für gemeinsame Räume gelten, insb. also nicht für das eigene Büro etc.
(Analog könnte die Spielzeit auch einfach anhalten, wenn ich rechtzeitig den Fahrstuhlknopf gedrückt habe, dann aber doch eine Realzeitskunde gebraucht habe, um die Maus zum richtigen Raum bewegt zu haben; das würde selbst dann funktionieren, wenn er in der anderen Richtung unterwegs ist - dann fährt er einfach weiter und nimmt mich nicht mit).

P.S.: Technisch interessieren würde mich, warum/an welcher Stelle die Ticks auch an die Realzeit gebunden sind. Rein von der Rechenpower sollte die Spielgeschwindigkeit (insb. wenn man nur die festen Level hätte) doch keine Rolle spielen dürfen. (Antwort in maximal 4 Sätzen oder durch Link auf eine Quelle ;-) Keine Lebenszeit verschwenden.)

**Comment by GWRon** [comment]
Erstmal die maximal vier Saetze...

Du kannst die Spielgeschwindigkeit ja auch langsaaaaam machen...(aber schnelle Figurenbewegung...das kann getrennt gesteuert werden).
Dann waere die KI nur selten am Zug. Deswegen gibt es den Realzeitfallback...der dann greift.


Zeit anhalten: geht nur im Einzelspieler. Fuer Mehrspieler ist noch keine praktikable Loesung eingefallen...haeufigster Vorschlag war das zeitgleiche Betreten mit individuellem Amgebot der Haendler. Aber das Raumsperren/blockieren ist ja ein Gameplay-Element.


Ich mag mich jetzt irren...aber gab es in den Spieleinstellungen nicht irgendwas zum Thema "im Raum"?



Mit den devkeys Strg plus CursorRechts mach ich den Schnellvorlauf...loslassen und wieder Normalspeed.

Koennte man auch mit Buttons loesen...


Der Idee, im Einzelspieler in "sperrbaren" Raeumen (ausser man hat Vorrang..wie eigene Zimmer) nach einer Weile die Geschwindigkeit zu drosseln ...kann man denke ausbauen.

Eine weitere Alternative ist...mehrere Filmagenturen zu haben (bzw eine Bude, die Sportprogramme verkauft, Toto-Wetten erlaubt etc). Sprich ein wenig mehr verteilen


Ebenfalls moeglich waere ein Timer...der anzeigt, dass draussen jemand angeklopft hat. Mausunteraktionen verlaengern den Timer ein wenig...so dass "vergessen" eher einen rausschmeisst als langes Durchstoebern.

**Comment by nittka** [comment]
Hm. Auch hier sind wieder zwei Aspekte in einem Ticket: Tastenkürzel und Schnellvorlauf...

Konkreter Wusch für Tastenkürzel. In der Nicht-Developer-Variante funktionieren die Tastenkürzel für die wichtigen Räume wie das Anklicken einer sichtbaren Tür (game.figure.bmx Zeilen 1098ff ?) Die Figur bewegt sich auch in eine andere Etage, ohne dass der Fahrstuhl-Raum für die Auswahl aufgeht. Durch das Ein- und Ausblenden geht vergleichsweise viel Zeit verloren, in der man es ggf. sogar geschafft hätte, noch den richtigen Raum anzuklicken. Merker für mich: entsprechender Hook könnte nach main.bmx Zeile 680.

**Comment by GWRon** [comment]
Ja ... figure.SendToDoor() koenntest du nutzen...
https://github.com/TVTower/TVTower/blob/master/source/game.figure.bmx#L963

Oder - man schaut, was die DevKeys machen:
```
If KEYMANAGER.IsHit(KEY_O) Then DEV_switchRoom(GetRoomCollection().GetFirstByDetails("", "office", GetPlayerCollection().playerID))
```
und die Funktion macht unter anderem folgendes:
```
	'a) add the room as new target before all others
	'GetPlayer().GetFigure().PrependTarget(TRoomDoor.GetMainDoorToRoom(room))
	'b) set it as the only route
	figure.SetTarget( New TFigureTarget.Init( GetRoomDoorCollection().GetMainDoorToRoom(room.id) ) )
	figure.MoveToCurrentTarget()
```

Kurzum: man holt sich den `TRoom` und kann dann mit dessen `id` die "Haupttuer" (falls es mehrere Zugaenge gaebe) ermitteln ... dann einfach alles verknuepfen ;)						

also - aus dem blauen heraus geschrieben und ungetestet:
```
local targetRoom:TRoom = GetRoomCollection().GetFirstByDetails("", "office", GetPlayerCollection().playerID)
if targetRoom
  local targetDoor:TRoomDoor = GetRoomDoorCollection().GetMainDoorToRoom(targetRoom.id)
  if targetDoor
    figure.SendToDoor(targetDoor)
  endif
endif
```

**Comment by nittka** [comment]
Ich habe mal eine aus meiner Sicht minimalinvasive Version zum Lösen dieses Tickets erstellt. Es ermöglicht zwar nicht den Raumwechsel mit automatischem fast-forward, aber man kann über das Tastenkürzel den gewünschten Raum wählen und dann durch Gedrückthalten der Rechts-Taste den Schnellvorlauf starten.
