### ISSUE TITLE
Nachrichten aus nicht abonnierten Kategorien

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#138]
Obwohl ich Politik und Wirtschaft nicht abonniert habe, werden einige Nachrichten aus dieser Kategorie zum Kauf angeboten. Das betrifft insb. (alte) Börsennachrichten und die Meldungen Botschafter-Wohnung verwüstet etc.

**Comment by GWRon** [comment]
Ein paar (die spielrelevanten) Botschafternews bekommen alle Spieler, auch ohne entsprechende Abos.

Boersenticker ist glaube aehnlich... hier koennte es aber ein Bug sein.

**Comment by GWRon** [comment]
Kannst Du das Bitte noch etwas naeher "ausfuehren" ?

**Comment by nittka** [comment]
Aktueller Masterstand. Nur Tagesgeschehen abonniert. Börsen-News werden dennoch angeboten. Mindestens die sollten es nicht in die Liste schaffen (bug).
Man könnte aber auch überlegen, dass man die Botschafternews nur mit Abonnement bekommt. Das würde den Anreiz erhöhen, diese Nachrichten zu abonnieren. Oder man muss eben bei den Kollegen ins Nachrichtenprogramm schauen, ob die was senden... Oder man wird böse überrascht. Konsistent wäre es jedenfalls.

**Comment by GWRon** [comment]
hmm also die Börsennews (in "res/database/default/kieferer.xml" - falls Du mal sehen willst, wie ich das "gescriptet" habe) sollten von den "flags" her nicht "send_to_all" haben ...
Also sie sollten nur erscheinen, wenn man das Genre "Politik/Wirtschaft" abonniert hat ...

**Comment by nittka** [comment]
Gleiches gilt für den Wetterbericht - kein Abonnement für irgendwelche Nachrichten, Börsennachrichten und Wetterbericht erscheinen trotzdem.
Meine Vermutung ist, dass es am send-immediately-Flag liegt (game.newsagency.base.bmx Zeile 885?).
Wenn ich am Wetterbericht alle Flags außer diesem ausschalte, kommt der Wetterbericht trotzdem, wenn ich das immediate-Flag ausschalte, kommt er nicht mehr.

**Comment by GWRon** [comment]
ich hab schon alles lokal umgeschrieben ... - und alles n bisschen mehr vereinheitlicht.

Wetterbericht bekommt man glaube "so oder so" (ist eine "Sondernachricht")

**Comment by GWRon** [comment]
Bitte ueberpruefe mit dem aktuellen Commitstand - zur Not machen wir das wieder auf.

Wetterbericht kommt nur bei aktiviertem Tagesgeschehenabonnement ... aber es kommt "ohne Verzoegerung" (die Level sorgen fuer geringere Verzoegerungen  - bei Sport koennten bestimmte Sachen ,wie Amateurligen, nur bei hoeheren Levels reinkommen).

**Comment by nittka** [comment]
Sieht gut aus. Die Botschafter-News kommen jetzt auch nur noch mit Abonnement. Ich gehe davon aus, dass das Absicht ist (und bin dafür).

**Comment by GWRon** [comment]
Die letzten News (Terrorist im Haus verschwunden) sollte an sich noch ankommen. Muss ich mal noch durchtesten.

**Comment by nittka** [comment]
Die Anschlag-Nachricht kommt auch, nur die Botschafter-News aus der Politik-Kategorie nicht mehr, die der Auslöser für dieses Ticket waren.
