### ISSUE TITLE
Personen-Filter bei Produktionszusammenstellung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#139]
Wenn ich im Supermarkt bei der Auswahl einer Person "alle Berufe" auswähle, funktioniert der Filter "Männer/Frauen" nicht mehr. Bei allen Einstellungen werden alle Personen angezeigt.

**Comment by GWRon** [comment]
OK. Sollte wohl nicht so sein ;-)

**Comment by nittka** [comment]
Ich schaue mir gerade den aktuellen Masterstand an. Da tritt der oben beschriebene Fehler nicht auf. Stattdessen werden bei "alle Berufe" gar keine Personen mehr angezeigt.
