### ISSUE TITLE
Zurückstellen des Monitors bei Vollbild

### ISSUE THREAD

**Issue by SICS-projects** [TVTower/TVTower#14]
Wenn man das Spiel an einem PC spielt, an dem 2 Monitore angeschlossen sind, und das Spiel im Vollbildmldus spielt, merkt sich das Spiel (Ubuntu 14.04) nicht wie die Monitore eingestellt waren, bevor man auf Vollbild ging. Lediglich die Auflösung wird zurückgestellt.

**Comment by nittka** [comment]
Kann dieses Ticket geschlossen werden? Es bezieht sich auf eine alte BlitzMax-Version. Falls es weiterhin Probleme mit diesem Setup gibt, kann ein neues Ticket mit aktualisierten Informationen aufgemacht werden.

**Comment by GWRon** [comment]
SDL ist ja nun bei uns im Einsatz - und sollte sich dem Problem annehmen.
