### ISSUE TITLE
Hinweis Level-Erhöhung bei Sendemastenkauf

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#140]
Wenn man noch nicht oft gespielt hat (oder es sich nicht merken kann), weiß man nicht, ab welcher Zuschauerzahl sich das Reichweitelevel und damit die Filmkosten etc. erhöhen. Damit man nicht böse überrascht wird, wenn es schon zu spät ist, wäre es hilfreich, wenn beim Kauf eines Sendemasten/einer Zuschaltung von Kabelnetz oder Satelliten ein entsprechender Hinweis erscheint. (z.B. als roter Text oberhalb des "Kaufen"-Knopfes).
Dann kann man sich überlegen, ob man nicht noch lieber seinen Fundus etwas preiswerter aufstocken möchte.

Alternativ wäre auch ein dauerhafter Hinweis "Anzahl Zuschauer bis zum nächsten Reichweitelevel" hilfreich.

**Comment by GWRon** [comment]
Guter Hinweis. Danke.
