### ISSUE TITLE
Markierung erreichter Erfolge

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#141]
Es werden nicht alle erreichten Erfolge in der Erfolgsstatistik mit einem grünen Haken versehen. Bei mir aktuell nur Wetterfrosch und Klatschreporter, obwohl noch andere (aber nicht alle?) erreichte Erfolge in den archivierten Nachrichten stehen.

**Comment by GWRon** [comment]
Kannst du das nochmal "anders" beschreiben?

Bei dir ist nur "wetterfrosch" und "klatschreporter" mit gruenem Haken versehen, alle anderen nicht, obwohl du andere Erfolge hattest?

**Comment by nittka** [comment]
Ich denke, das Problem ist schon behoben (mit rausnehem der Debug-1=1-Prüfung). Ich hatte fälschlicherweise angenommen, dass die unterschiedlich gefärbten Sterne nicht das Sprite für die fertig erreichten Erfolge sind, sondern dachte, dass es die Markierung unterschiedlicher Stufen desselben Erfolgstyps wären und beim Erreichen auch ein Haken hinkommt (d.h. Haken= erreicht, alle anderen Sprites=noch nicht erreicht).

Ich werde nach den vielen Commits der letzten Tage in naher Zukunft nochmal meine Tickets durchgehen, prüfen und dann zumachen.

**Comment by nittka** [comment]
Ja, Fehlinterpretation der Bilder, da immer schon ein Erfolg angezeigt wurde, obwohl er noch nicht erreicht war. Ursache dafür in 120917233399e390d06f6d8028869252dbc2bff1 behoben.
