### ISSUE TITLE
Drehbücher sporadisch nicht selektierbar

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#143]
Bei mir kommt es gelegentlich vor, dass beim Autor ein oder mehrere Drehbücher nicht auswählbar sind. Weder Hover noch Anklicken funktionieren.
Das scheint vorrangig dann der Fall zu sein, wenn ich ein oder mehrere Drehbücher gekauft habe, dann den Raum verlasse und wieder betrete.
Manchmal hilft es, an irgendeine Stelle im Raum zu klicken und dann auf das Drehbuch zu gehen.

**Comment by GWRon** [comment]
Das sollte eigentlich in den Dev-Versionen nicht mehr auftreten. Muessen wir beobachten.

**Comment by nittka** [comment]
0.6.2-dev vom 7.12.19 23:34 unter Ubuntu
* neues Spiel gestartet, alle Level normal, Spiel # 8652984, sofort alle Drehbücher gekauft, das am weitesten rechts stehende war beim ersten Wiederbetreten nicht selektierbar
* nochmal neues Spiel mit denselben Parametern gestartet; nun waren es andere Drehbücher und beim ersten Kauf aller Drehbücher trat der Fehler nicht auf, aber beim zweiten Kauf aller Drehbücher...

**Comment by nittka** [comment]
Konnte mit dem aktuellen Master-Stand nicht mehr reproduziert werden.
