### ISSUE TITLE
Gesamtproduktionskosten in die Nachricht

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#144]
Statistiken zu den Produktionen sind ggf. ohnehin auf der TODO-Liste. Eine erste kleine Variante wäre, die Gesamtkosten mit in die Produktion-Fertig-Nachricht aufzunehmen.

**Comment by GWRon** [comment]
Normale Produktionen ("nicht-live") bekommen nun noch die weitere Zeile hier spendiert:
![tooltip](https://user-images.githubusercontent.com/2625226/97986240-b82d0900-1dd9-11eb-8d3c-1de2196ec034.png)
