### ISSUE TITLE
Fenstergrößen Supermarkt

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#145]
Viel Spielraum für die Fenstergrößen scheint es für das Zusammenstellen einer Produktion nicht zu geben. Insb. bei Serien ist die Einkaufsliste mit drei Einträgen aber sehr knapp bemessen. Ein Filter zum Ausblenden bereits konzipierter Programme könnte hier helfen.
Wenn man das Fenster für die Besetzung vergrößert, die Auswahlbox für die Produktionsfirma dort integriert und den freigewordenen Platz in den Produktionsdetails rechts nutzt, um dort Kosten/Dauer und Abschließen-Button unterzubringen, hätte man für die Einkaufsliste mehr Platz...

Das Auswahlfenster für die Personen kann aber ohne große Umbauarbeiten vergrößert werden.
Wenn der gerade gewählte Film in der Einkaufsliste sichtbar bleibt (bereits anderer Bug-Report) und hervorgehoben wird, kann die Personenauswahl nach oben und unten vergrößert werden. Insbesondere bei den männlichen Regisseuren ist das Scrollen schon etwas nervig. (Eine Sortierung nach Eignung statt Namen wäre als Alternative hilfreich)

**Comment by GWRon** [comment]
Kannst du auf einem Screenshot herumkritzeln? 
Der Titel der Produktion ist sichtbar, da er dort per Klick auch bearbeitbar ist.

**Comment by nittka** [comment]
![supermarkt](https://user-images.githubusercontent.com/2562651/95953009-7a9c1800-0df9-11eb-903e-9d543493fb5b.png)

**Comment by nittka** [comment]
Eine weniger invasive Variante wäre noch, die Enkaufsliste größer zu machen, wenn die anderen Fenster nicht sichtbar sind. D.h. sie wird nur klein, wenn eine Produktion ausgewählt ist.
Problematisch ist hier wieder, dass  beim Verkleinern des Fensters die gewählte Produktion aus dem sichtbaren Bereich herausrutschen kann.
