### ISSUE TITLE
Darsteller-Geschlecht bei Einstellungen übernehmen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#146]
Die Funktion Einstellungen übernehmen für das Planen von Produktionen ist sehr hilfreich.
Aktuell gibt es aber keinen Indikator, ob das Geschlecht des übernommenen Darstellers zur Rolle passt.
Szenario:
* Film 1 mit Regisseur, erster Darsteller männlich
* Film 2 mit Regisseur, erster Darsteller weiblich

Ich wähle Film 1, setze den Einstellungen-übernehmen-Haken und besetze Regisseur und Darsteller. Dann wähle ich Film 2.
Nun sind Regisseur und erster Darsteller schon eingetragen. Ich kann aber nirgends sehen, dass der erste Darsteller hätte weiblich sein müssen. Erst wenn ich den Darsteller komplett entferne (nicht nur Anklicken und wegbewegen, sondern auch Rechtsklick um die Zuordnung aufzuheben), sehe ich, dass der Darsteller hätte weiblich sein müssen.
Ich weiß ja nicht, welchen Einfluss auf die Attraktivität es hat, eine Rolle mit dem falschen Geschlecht zu besetzen...

Vorschlag 1: Warnhinweis unten, wenn das Geschlecht nicht der geforderten Rolle entspricht (kann man ja ignorieren)
Vorschlag 2: Symbol für das eigentlich geforderte Geschlecht links oder rechts neben die "Auswahlzeile". Name und Balken für die Eignung sind kurz genug, dass man da 15 Pixel erübrigen kann.
Vorschlag 3: Bei Einstellungen übernehmen, werden Darsteller nicht übernommen, wenn das Geschlecht nicht passt.
Vorschlag 4:  Es wird nicht stur Darsteller 1->Darsteller 1, Darstleler 2 -> Darsteller 2 übernommen sondern nach Geschlecht getrennt.

**Comment by nittka** [comment]
![personen-auswahl](https://user-images.githubusercontent.com/2562651/98020251-0dc9db80-1e03-11eb-9d2c-3c5a85d926d9.png)

Eine weitere Alternative wäre, beim "Entfernen" des Darstellers (siehe Bild) nicht mehr den Darstellernamen ausgegraut anzuzeigen, sondern die ursprüngliche "Anforderung".
Auf diese Weise hätte man die Möglichkeit (auch beim regulären Zusammenstellen einer Produktion) zu prüfen, ob die Zuordnung passt: Person anklicken, kurz wegbewegen um die Anforderung zu sehen, Person wieder einsetzen.

Für mich wäre das eine sinnvolle Änderung unabhängig von der Einstellungsübernahme (separates Ticket aufmachen?)

**Comment by GWRon** [comment]
Auch koennte der Avatarhintergrund Geschlechteranforderungen andeuten, oder ein Icon, falls was abweicht

**Comment by nittka** [comment]
Kannst Du mir einen Tipp geben, an welche Codestelle ich ran muss, damit beim Entfernen einer Person aus der Liste (noch nicht wirklich remove, sondern nur das oben gezeigte Anklicken) die "Anforderung" an die Person angezeigt wird (also statt "Benny Jameson" dann "Regisseur")?

**Comment by GWRon** [comment]
Du meinst den Teil, der auf dem Untergrund gezeichnet wird?

**Comment by nittka** [comment]
Ja, im Screenshot der graue "Benny" ganz oben in der Liste.
Angenommen, ich hätte Benny als männlichen Darsteller gesetzt gehabt. Dann stünde jetzt in der zweiten Zeile immer noch der Name. Wenn aber beim "Wegbewegen" die Anforderung dasteht, könnte ich die Besetzung prüfen (auch beim Übernehmen der Einstellungen).

**Comment by GWRon** [comment]
Wie gesagt - wir koennen den Avatarhintergrund auch einfach "blau/rot" "eintuenchen".

Grau = keine Anforderung
Blaugrau = Maennlich
Rosarotgrau = Weiblich

das mit dem Beruf kann man natuerlich trotzdem machen ... dafuer musst Du die Jobinformation fuer die Slotposition nutzen

game.screen.supermarket.production.bmx:

Type TGUICastSlotList Extends TGUISlotList 
DrawContent()
```
				If MouseManager._ignoreFirstClick 'touch mode
'					TGUICastListItem.DrawCast(atPoint.GetX() + pos.getX(), atPoint.GetY() + pos.getY(), _slotMinDimension.getX(), GetLocale("JOB_" + TVTPersonJob.GetAsString(GetSlotJobID(slot))) + genderHint, GetLocale("TOUCH_TO_SELECT_PERSON"), null, 0,0,0)
					TGUICastListItem.DrawCast(GetScreenRect().GetX() + coord.GetX(), GetScreenRect().GetY() + coord.GetY(), guiEntriesPanel.GetContentScreenRect().GetW()-2, GetLocale("JOB_" + TVTPersonJob.GetAsString(GetSlotJobID(slot))) + genderHint, GetLocale("TOUCH_TO_SELECT_PERSON"), Null, 0,0,0)
				Else
					TGUICastListItem.DrawCast(GetScreenRect().GetX() + coord.GetX(), GetScreenRect().GetY() + coord.GetY(), guiEntriesPanel.GetContentScreenRect().GetW()-2, GetLocale("JOB_" + TVTPersonJob.GetAsString(GetSlotJobID(slot))) + genderHint, GetLocale("CLICK_TO_SELECT_PERSON"), Null, 0,0,0)
				EndIf
```

Sprich: Hole dir die "slotlist" und mit "list.GetSlotJobID()" kannst du den an dieser Stelle genutzten Job abfragen.

**Comment by GWRon** [comment]
Die slotlist:
TScreenHandler_SupermarketProduction.castSlotList

Man koennte auch dem Item selbst das einen anderen Text beibringen:
`if TGUIListBase.FindGUIListBaseParent(item) = TScreenHandler_SupermarketProduction.castSlotList and item.IsDragged() ...` oder so was in der Art

**Comment by nittka** [comment]
Danke. Ich denke, damit komme ich erstmal weiter.

**Comment by nittka** [comment]
Ich mache das Ticket zu. Durch das Anzeigen der Jobanforderung beim Wegbewegen einer Position, hat man die Möglichkeit, übernommene Einstellungen zu überprüfen.
