### ISSUE TITLE
Fenstergröße Filmauswahl

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#148]
Bei der Programmplanung sind aktuell 10 Filme pro Seite vorgesehen. Dann muss man umblättern. Platz wäre locker für 15 oder 20 Filme. Das sähe zwar zum Anfang des Spiels leer und traurig aus, in späteren Spielphasen wünsche ich mir aber zumindest bei Komödie und Krimi/Thriller nicht so oft umlättern zu müssen.

(Ich habe mich noch gar nicht mit der Programmiersprache befasst und kann den Aufwand daher nicht abschätzen, aber anfangs könnte das Menü ja auf 10 Einträge begrenzt sein und wenn man dann in einer Kategorie mehr als 10 Filme hat, wächst das Menü auf 15 oder 20 bevor die Umblätter-Pfeile dazukommen.)

Alternativ könnte der ungenutze Platz für eine größere Trefferfläche genutzt werden. Der Mauszeiger ist deutlich größer als die Filme und "Werbe-Ordner", so dass ich immer mal wieder das falsche erwische (besonders ärgerlich bei Werbung).

**Comment by GWRon** [comment]
Ja man kann da mehr anzeigen lassen. Ist alles dynamisch...selbst die Hintergrundgrafik.

Die Kassetten koennte man ein zwei Pixel hoeher machen...aber ob es das schon bringt?

**Comment by nittka** [comment]
Für die angezeigte Anzahl, habe ich mich mal an der Implementierung versucht.
Die Höhe der Kassetten/Vertrags-Einträge um 2 Punkte zu erhöhen, könnte schon was bringen - wenn man in 75% der Fehler-Fälle einen Pixel daneben liegt...

**Comment by nittka** [comment]
Ich mache für die Höhe der Werbevertrags-Einträge mal ein neues Ticket auf, da es inhaltlich ein anderes Problem ist.
