### ISSUE TITLE
Eintragshöhe Werbevertragsauswahl

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#151]
... Nachfolgeticket für #148. Im Vergleich zur Höhe des Mauszeiger sind die Einträge für die Auswahl eines Werbevertrags niedrig. Das führt gelegentlich dazu, dass man den falschen Vertrag im Programm plant. Folgende Ansätze könnte ich mir vorstellen:
* "Kassettenhöhe" vergrößern
* Abstand zwischen den Einträgen vergrößern
* farbliche Hervorhebung "Vertrag droht, nicht erfüllt zu werden" im Programmplaner
* analog im Interface, damit man nicht erst über dem Fernseher hovern muss (Warnlampe für Werbung fehlt bzw. Werbevertrag droht zu scheitern)

Die letzte Variante wäre natürlich hilfreich, egal wo man sich gerade befindet. Gegenargumet wäre, dass es das dem Spieler zu einfach macht, da er nicht mal aktiv nachschauen müsste... Ich wünsche es mir trotzdem.

**Comment by GWRon** [comment]
> farbliche Hervorhebung "Vertrag droht, nicht erfüllt zu werden" im Programmplaner

Das koennte man ... wohl machen - unabhaengig von den anderen Dingen.

**Comment by nittka** [comment]
Siehe auch #105. (Tatsächlich finde ich Punkt 3 mittlerweile auch am wichtigsten. Und er dürfte mit dem geringsten Aufwand umsetzbar sein.)

**Comment by GWRon** [comment]
OK ... also im Programmplaner sollte der "aktuelle Werbeblock" aufblinkern, wenn er nicht erfolgreich sein wird? (orange "glimmen" ... das Overlay dafuer haben wir ja schon ... oder wir faerben den Block der Werbung ein).

Favorisierst Du was davon?

**Comment by GWRon** [comment]
Weiss nicht wie aufdringlich es ist - aber es koennte eine "Toastmessage" erzeugt werden, wenn die aktuelle Werbung (wenn zu "Programmblockbeginn" gesetzt - danach waere ja "mutwillig" geschehen) nicht vorhanden ist, oder es zu Problemen kommt.

Toastmessage: die Teile oben links (oder rechts, oder unten links/rechts ...)


Weniger aufdringlich waere wohl, wenn der jeweilige Fernsehrknopf "pulsiert" ... vielleicht aber auch "zu wenig". Und naja ... die Aufgabe des Kanalmanagers ist nun einmal die dauernde "Kontrolle" - alle Aufgaben hier zu erleichtern kann schnell zu "Casualgame"-Empfinden fuehren

**Comment by nittka** [comment]
Ich finde den pulsierenden aktuellen Werbeblock am besten!
Die Toastmessage halte ich nicht für geeignet. Sie sollte "Ereignissen" vorbehalten bleiben.
Ich finde es auch korrekt, wenn man ausschließlich im Programmplaner explizit auf das Problem hingewiesen wird. Man kann durch Hover auf den Fernseher auch von woanders sehen, dass es ein Problem gibt.

Vielleicht kann man das Pulsieren auf x Sekunden nach dem Drop beschränken!? Bei diesem Ticket ging es ja darum, darauf hinzuweisen, dass die Werbung, die man gerade für den aktuellen Block platziert hat, wahrscheinlich gar nicht die intendierte war. Wenn man schauen will, ob eine schon länger geplante Werbung daneben geht, kann (und soll?) man wie bisher den Fernseher nutzen - so ein Dauerpulsieren wäre vielleicht auch nervig.

Die Variante aus #105 - Warnhinweis beim Hover über dem nächsten Werbeblock - halte ich zusätzlich für sinnvoll. Damit könnte man im Programmplaner, auch wenn das Pulsieren schon vorbei ist an der Werbung noch erkennen, was das Problem ist. Man hovert ja über der Werbung, um zu kontrollieren.

**Comment by GWRon** [comment]
Was ist jetzt "hiervon" noch aktuell (in Anbetracht des neuen Mauszeigers) ?

**Comment by nittka** [comment]
Der aktuelle Stand bezüglich Nehmen der Werbung ist OK. Die hier erwähnten Anpassungsmöglichkeiten, die eher zu Ticket 105 passen, könnte ich dort nochmal zusammenfassen (pulsierender aktuell gefährdeter Werbeblock). Ich werde das in Kürze machen und dann dieses Ticket schließen.
