### ISSUE TITLE
Segmentation fault bei Personenauswahl

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#153]
Ich bin auf dem aktuellen Master-Stand und versuche die Selektion/Scroll-Position in der Produktionsliste in den Griff zu bekommen. Dabei ist mir aufgefallen, dass bei der Auswahl von Laiendarstellern das Programm relativ zuverlässig mit Segmentation fault abstürzt. (Ausgangspunkt ist ein gespeicherter Spielstand relativ kurz nach dem Start mit ein paar gekauften Filmen und Drehbüchern)

Außerdem fand ich seltsam, dass die Produktionskosten mit Amateur-Firma sofort 1 Million waren, mir einer anderen vertretbare 80000. Ich habe noch nicht geprüft, mit welchem Commit dieses Problem entstanden ist.

**Comment by nittka** [comment]
Der Kommentar von Commit 622d2f56b021f44eb66bc62ad10e4a9391cd67ed klingt verdächtig und zumindest tritt der Segmentation fault vor diesem Commit noch nicht auf (Die Produktionskosten bei den Amateuren war da schon so hoch).

Außerdem scheinen die gespeicherten Spielstände vor und nach dem Commit nicht kompatibel zu sein.

**Comment by nittka** [comment]
Ich habe die anderen genannten Probleme in separate Tickets/PRs rausgezogen. In diesem Ticket bleibt als offener Punkt das ursprüngliche Problem, dass die Auswahl von Laiendarstellern aktuell zum Absturz führt.

**Comment by GWRon** [comment]
Ich danke dir fuer die Muehen.


Versuche das alles Stueck fuer Stueck abzuarbeiten.
