### ISSUE TITLE
Laden inkompatibler alter Spielstände verhindern

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#164]
Ich ziehe diesess Ticket mal aus #153 raus, da es grundlegender ist als der Fehler bei der Personenauswahl von (wahrscheinlich ohnehin selten verwendeten Laien).
Das Refactoring 622d2f5 führt zu Problemen beim Einladen eines vor dieser Änderung erstellten Spielstandes. Wie es scheint, sind nicht alle Fälle von noch nicht vergebenen IDs so abgefangen, dass die Persistenz kompatibel ist.

**Comment by nittka** [comment]
'''
[WARNING] TPersistence: field "padding" is no longer available. Created WorkAround-Storage.
[WARNING] TPersistence: field "job" is no longer available. Created WorkAround-Storage.
[WARNING] TPersistence: field "jobsDone" is no longer available. Created WorkAround-Storage.
Segmentation fault (core dumped)
'''

**Comment by nittka** [comment]
Ich weiß nicht, wie Du dieses Thema einschätzt. Speicherstände, die mit dem letzten regulären Release (0.6.1) oder dem letzten Dev-Patch (0.6.2 Dez 2019) erstellt wurden, können mit dem aktuellen Masterstand nicht mehr geladen werden.
Da schon 0.6.1-Spielstände im Dev-Patch nicht mehr gingen, ist das wahrscheinlich kein wirkliches Problem (außer für mich, da ich hauptsächlich mit der Dev-Variante gespielt hatte).

Also nur in den Release-Notes explizit darauf hinweisen (Versionssprung auf 0.7 wegen Inkompatibilität?).
Wenn Du also einen kurzen "ja bekannt und so gewollt"-Kommentar schreibst, mache ich das Ticket zu.

**Comment by GWRon** [comment]
Nur weil ich den Segfault behebe, ist nicht garantiert, dass es der Einzige war.


Problematisch sind vor allem Dinge, die es in der letzten Version noch nicht gab. Oder gar welche, die von Spielbeginn an simuliert wuerden.


Auch problematisch ist, wenn dann Spieler ihre alten Speicherstaende laden, es irgendwie funktioniert..aber komische Sachen passieren. Es kommen dann Fehlerberichte rein....ohne Angabe der alten Version. Hatte dazu glaube schon was in den Speicherstaenden hinterlegt, wenn nicht, mache ich das mal noch.

**Comment by nittka** [comment]
Ich habe das Ticket mal umgewidmet - das Laden inkompatibler alter Spielstände sollte unterbunden werden.

Wenn sich an der Persistenz entwas grundsätzlich ändert, sollte die "SaveGame"-Version erhöht werden und das Laden des Spielstands mit einer Hinweismeldung unterbunden (und dadurch Programmabstürze verhindert) werden.

**Comment by GWRon** [comment]
Die Warnmeldung... das hatte ich mir auch schon ueberlegt. Derzeit erfolgt nur in der Konsole (sozusagen fuer "Tester/Entwickler") der Hinweis, dass der Speicherstand mit einer alten Version erstellt wurde.

Ich wollte das auch auf eine art "Revision" erweitern - die bei grundsaetzlichen Aenderungen erhoeht wird und dann eine Meldung ausspuckt.

**Comment by nittka** [comment]
Geht technisch ein "try catch" um das Laden des Spielstands, der einen Segmentation-Fault-Absturz verhindert? Dann könnte man in dem Fall mit dem "Inkompatibilitätshinweis" zurück auf die Spielstandauswahl.

**Comment by GWRon** [comment]
Wenn es schon beim Einladen abstuerzt...koennen wir Entwickler das ja lokal auch gleich nachvollziehen.

Man kann es in tryCatch packen ..ja
Wichtiger sind aber die Abstuerze, die spaeter im Spiel passieren (Nullzugriffe, da ein Objekt nicht gespeichert war..aber haette sein sollen).

**Comment by GWRon** [comment]
Also "uralte" Speicherstaende von ... 2019  ... das laesst sich nicht ohne Aufwand "kompatibel" machen. Die ganze Personenklasse (und wie "Berufe" etc) funktionieren ... wurde umgeschrieben.

**Comment by GWRon** [comment]
Ich koennte Speicherstaende als "inkompatibel" im "Laden"-Dialog markieren (bzw das Einladen auch abbrechen - falls quicksave inkompatibel).

Speicherstaende enthalten schon eine "Revision" ... und es gibt eine "minRevision" ab wann ich es als kompatibel erachte. Nur hat sich bisher das Spiel nicht wirklich drum geschert, das auch optisch anzuzeigen.

**Comment by GWRon** [comment]
Der aktuellste Commit markiert inkompatible (oder fehlerhafte bzw fehlende) Speicherstaende.
F8 verweigert ebenfalls das Laden ...

(linkes) Shift + F8 ignoriert die "Kompatibilitaet" beim Quicksaveeinladen
(linkes) Shift beim Anklicken von "Spiel laden" (Hauptmenu oder Escape-Menu) umgeht die Filechecks auch.

Damit solltest du alte Speicherstaende einladen koennen - beim Speichern wird die nun notwendige Speicherstandsrevision "13" verwendet.


Also alle Speicherstaende bis vor diesem Commit : "inkompatibel" (aber mit linkem Shift zu umgehen).

**Comment by GWRon** [comment]
Bitte "close", wenn mit dem aktuellen Stand zufrieden.

**Comment by nittka** [comment]
Warum ist das Überschreiben eines alten inkompatiblen Speicherstandes verboten? Wird dabei nicht die gesamte Datei ersetzt? Ich hätte erwartet, dass nur der Name wiederverwendet wird und der gesamte Dateiinhalt vom aktuellen Spielstand bestimmt wird.

**Comment by nittka** [comment]
Beim Laden eines als kompatibel gespeicherten Spielstandes (<String id="144KYSG">v0.6.2-dev Build &quot;23.11.20 17:42&quot;</String>) kam es heute beim Laden zu Segmentation fault. Kann das an den Änderugnen zu den Attributen liegen?

[10:39:53] SAVE DBG | SAVEGAME.LOAD(): Restored TEntityBase.lastID=731, TGameObject.LastID=19239.
[10:39:53] SAVE DBG |                : Savegame was created with an older TVTower-build. Enabling basic compatibility mode.
Segmentation fault (core dumped)

Da alte Spielstände tatsächlich in jedem Fall inkompatibel sein werden, ist das vielleicht nicht so problematisch.

**Comment by GWRon** [comment]
Kannst du den Speicherstand zippen und hochladen?

Kann ich mir in einem Debugbuild mal angucken.

**Comment by GWRon** [comment]
Deine Debugmeldung dort kommt auch, wenn Du zwischen "speichern" und "laden" neu kompiliert hast ("builddate" verschieden).

Eventuell sollte man wirklich bei jeder kleinen "Aenderung" die Revision des Savegames erhoehen - und nur DANN die Meldung ausspucken. Darf man aber die Anpassung des Wertes nicht vergessen :)

**Comment by nittka** [comment]
[neu2.xml.tar.gz](https://github.com/TVTower/TVTower/files/5612021/neu2.xml.tar.gz)

Neu kompiliert habe ich zwischendurch natürlich häufig.

**Comment by GWRon** [comment]
also wenn ich den Speicherstand aus dem Hauptmenue heraus auswaehle ... laedt es den Speicherstand und das Spiel faehrt fort.

Stuerzt es jedes mal ab, oder nur spradisch?

**Comment by nittka** [comment]
Stürzt immer ab. Kann es eine WIndows vs. Linux-Problematik sein?

**Comment by GWRon** [comment]
Dachte wir beide benutzen Linux :dagger: 
Ich vermute eher, es liegt an meinen kleinen Modifikationen (lokal) am Persistenzmodul ... 
... ne, Aenderungen entfernt und laeuft trotzdem noch.


Habe viele Eintraege bezueglich:
"[WARNING] TPersistence: field "xp" is no longer available."

(weil ja nun "genreXP" und "jobXP" existieren). Weiss nur nicht, wieso es bei mir nicht abstuerzt. Leider ruckelt gerade der "Debugbuild" - denke ich hab irgendwo in der GUI was drin, an was sich die Debugbuilds verschlucken ("Einzelspieler"-Bildschirm macht nur 3 fps ...)

**Comment by nittka** [comment]
Dann lass die Spielstandproblematik erstmal liegen. Ich werde das mit den nächsten Commits weiter ausprobieren.

**Comment by nittka** [comment]
Von mir aus kann das Ticket zugemacht werden. Es sei denn, Du willst die xp-Umbenennungen noch behandeln. Da die Spielstände der Bestandsversionen aber ohnehin inkompatibel sein werden, erscheint das nicht sinnvoll.
