### ISSUE TITLE
Sortierung der Einkaufslisten im Supermarkt durcheinander

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#169]
Im aktuellen Masterstand sind nach Erstellen initialem Erstellen aller Einkaufslisten einer Serie diese im Supermarkt in der falschen Reihenfolge.
Es ist mir auch passiert, dass bei Vorhandensein der Listen für zwei Serien und Umbenennungen von Hauptserie und Folgen die Listen komplett durcheinander waren.

Letzteres könnte ggf. Folgebug des Nicht-Neuaufbauens der Gesamtliste sein.

**Comment by GWRon** [comment]
Jein.

Listen werden neuerdings (also vom Listenmodul/lib ausgehend) nach hash sortiert, nicht mehr nach alphabet...muss  ich eine Sortierfunktion reinmachen. Denke und hoffe ich mal :-)

**Comment by GWRon** [comment]
Also der Fehler liegt an 
https://github.com/TVTower/TVTower/blame/d10c287b68dca67d7291bcf9afceb80eb2d1ace6/source/Dig/base.gfx.gui.list.base.bmx#L348

Irgend ein Element im Spiel war nicht richtig sortiert - was aber eher daran liegen wird, dass dieser dort eingesetzte "Type" keine eigene "Method Compare:Int(o:object)" hat (also eine eigene Sortierungsmethode) ...
Die Einkaufslisten haben sowas aber - und sortieren dort nach Serie, Episode ... etc. Die obige Aenderung sorgte dafuer, dass "Compare()" aber nicht mehr fuer die Listensortierung herangezogen wurde.

Ich mach das jetzt rueckgaengig und vielleicht faellt Dir ja die Liste auf, die dadurch eventuell "unsortiert" ist (mir faellt sie gerade nicht ein).

**Comment by nittka** [comment]
Ich denke, es könnten die Darsteller etc. im Supermarkt sein. Die scheinen aktuell nämlich keine erkennbare Sortierung zu haben. Für die gibt es ja auch noch ein anderes Ticket (#123). Daher mache ich dieses hier mal zu.
