### ISSUE TITLE
manche Zeichen nicht für Titel/Beschreibung nutzbar

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#170]
Es gibt eine Reihe von Zeichen, die man aktuell nicht im Titel oder der Beschreibung nutzen kann - insb. den Satzendepunkt.

**Comment by GWRon** [comment]
Welche Zeichen sind Dir noch aufgefallen? Hatte nur azAZ und Umlaute probiert.

**Comment by nittka** [comment]
$%#'.
sind die einfachen Zeichen, die bei mir nicht gehen (Lubuntu 64 bit). Besondere Zeichen anderer Sprachen habe ich nicht probiert.

**Comment by GWRon** [comment]
Hmm ... also wenn ich direkt die Tasten abfrage .... bei $%& ... da zeigt es mir die Tastencodes fuer "cursor left/right" an ...komisch. Muss ich mir wohl mal im Wachzustand genauer anschauen

**Comment by GWRon** [comment]
Vielleicht ist  `GetChar()` nicht ganz geeignet - da es "nicht umgemuenzte" Codes ausspuckt. 

`GetChar()` bei Taste "A" liefert einen anderen Zahlencode, als `KEY_A`.
Wenn ich `if Keyhit(KEY_A)` mache und "A" druecke, funktioniert das aber. 

SDL mappt auch Tasten entsprechend der Layouts um etc - vielleicht ist das so "ne Sache" da.

**Comment by GWRon** [comment]
Das eine sind "Key codes" - und `GetChar()` liefert "character codes". Hmm muss ich mir anschauen.
