### ISSUE TITLE
Verkaufspreis von Seriendrehbüchern

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#171]
Aktuell bekommt man den gesamten Drehbuchpreis zurück, wenn man es verkauft - egal ob und wieviele Serienfolgen man daraus produziert hat. Für Filme ist das weniger problematisch, da man sie nach einer Produktion nicht verkaufen kann. Bei einer Serie, von der man Teile produziert hat, sollte man aber nur einen Anteil zurückbekommen.

**Comment by GWRon** [comment]
Ok.

Vorschlaege zu Drehbuechern mit mehrfach produzierbaren Shows etc?

Unverkaeuflich machen? (Dann per Muelleimer in einem Studio / Drehbuchhaendler wegwerfen?

**Comment by nittka** [comment]
Ich fände "unverkäuflich" OK. Das mag zwar ggf. ärgerlich sein, wenn das Drehbuch teuer war (z.B. selbstproduzierbare Call-In-Show - da habe ich es nicht geschafft, was draus zu machen), aber man muss sich eben genau überlegen, was man kauft.

Statt Mülleimer vielleicht einfach Dialog beim Zurückgeben an den Händler: "Kein Geld zurück - OK?"

**Comment by GWRon** [comment]
Kann das hier zugemacht werden, oder was fehlt noch?

**Comment by nittka** [comment]
Wenn noch was fehlt, gibt's ein neues Ticket. Aktuell fällt mir nichts ein.
