### ISSUE TITLE
Thematische Aufteilung Lokalisierung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#178]
Ich schlage vor, nicht zwischen allgemeiner Hilfe und In-Game-Help zu unterscheiden (F1 und F2). F1 ist die für Hilfe bekannte Tastenkombindation.
Bei F1 sollte die spezifische Hilfe aufgemacht werden, wenn welche vorhanden ist, ansonsten die allgemeine.

...natürlich könnte die spezifische Hilfe auch mal erweitert werden.

**Comment by nittka** [comment]
Die Lokalisierungsdateien sind sehr unterschiedlich vollständig. Ich könnte mir vorstellen, dass die Pflege vereinfacht und Übsichtlichkeit gesteigert werden könnte, wenn man die Dateien thematisch aufteilt. Auch dürfte es weniger demotivierend sein, wenn man 100 Einträge zu bearbeiten hat als 1000. Auch der Vergleich, welche Schlüssel noch fehlen und das Einfügen neuer Schlüssel wird vereinfacht, da die Dateien einfach nicht so groß sind.
Die Infrastruktur für das Laden der Dateien sollte damit klarkommen - eine feste Liste von Verzeichnissen unterhalb von lang, die jeweils die Lokalisierungen für dieses Thema enthalten. Diese können dann in main.bmx analog Zeile 6411 mit TLocalization.LoadLanguageFiles("res/lang/<subdir>/*.txt") geladen werden.

Natürlich müsste man initial einmal alles aufräumen. Mögliches Vorgehen für das Refactoring:
* grobe thematische Gruppen festlegen (Ziel nicht zu groß, nicht zu klein)
** allgemeines (Einstellungen, Spielsteuerung)
** einzelne lokalisierungsintensive Räume (z.B. Programmplanung, Filmproduktion)
** ...
* für jede Gruppe ein Unterverzeichnis
* neue properties-Dateien pro Sprache in dieses Verzeichnis, vorhandene Einträge aus der Original-Datei da reinkopieren
* mit einem Skript kann geprüft werden, dass sämtliche Schlüssel der Original-Datei in den neuen Dateien vorkommt und die Werte gleich geblieben sind
* Löschen der Originaldateien und Einbinden der neuen Lokalisierungsdateien

Sinnvoll erscheint ein iterativer Prozess. Man kopiert die aktuellen Dateien als Originale und verschiebt dann nach und nach Einträge in die verkleinerten Dateien (die Originale für die automatisiert Vollständigkeitsprüfung). Einbinden würde man dann die immer kleiner werdenden Bestandsdaten sowie die neu entstehenden Dateien.

**Comment by GWRon** [comment]
Koennen wir gerne machen ... werde ich der Lokalisierungsklasse einfach beibringen: ist der Pfad ein Verzeichnis, lade alle "*.txt"-Unterdateien.

Alternativ koennten wir auch XML-Dateien erlauben - in den DB-Dateien ist ja auch Lokalisierung enthalten. Dann verliert man aber eher die "welcher Eintrag ist noch nicht lokalisiert" Uebersicht und benoetigt ein entsprechendes Tool. Denke aber, da koennte sicher schon was von anderen Projekten existieren ?

**Comment by nittka** [comment]
An der Lokalisierungsklasse muss eigentlich gar nichts gemacht werden. Ich werde mal einen Prototyp-Branch aufsetzen und den hier ohne PR verlinken. Dann kannst Du Dir anschauen, wie ich mir das im Moment vorstelle. (Das wird aber noch eine Weile dauern)

Frage: Ist die Spielanleitung-RAW und ihre Transformation noch nötig oder wäre das Kürzen der Zeilen durch das wrapLines des Textarea nicht überflüssig. Die Raumspezifische Hilfe kommt über die Lokalisierung ja auch ohne vorheriges Zeilenkürzen aus. Hintergrund der Frage wäre, ob man die Spielanleitung nicht auch in ein lang/manual-Verzeichnis verschiebt, unterschiedliche Sprachen unterstützt (manual_de.txt, manual_en.txt...) und diese dann als Gesamtdatei einliest und  manual-Lokalisierungsschlüssel zuweist.

**Comment by GWRon** [comment]
Also die urspruengliche Fassung war fuer das "Lesen im Texteditor" gedacht - deswegen auch der Umbruch bei 72 oder so Zeichen.
Fuer die Ingame-Spielhilfe ist dies nicht erforderlich.

Kommt wohl darauf an, ob man auch ausserhalb des Spieles noch "lesen" koennen soll, ohne es in Word, Writer, ... oder mit virtuellem Zeilenumbruch oeffnen zu muessen.

Die Position des handbuchs ... nun, klar, wenn es mehrsprachige Fassungen gaebe, waere die "lang/manual"-Variante besser.

Bin mir da "unsicher" ... kann aber gerne beim "Aufraeumen" alles in einen "lang"-Ordner verfrachtet werden.


@ Lokalisierungsklasse
Naja, die Klasse muss nicht zwingend geaendert werden -- aber da dort schon explizite Funktionen fuer das Laden von Dateien bestehen - und die neue "TLocalizationLanguage"-Instanzen anlegen, waere es schon praktisch.
Und da wir ja selbst fuer das Framework verantwortlich sind (ist ja meines), stoert mich eine Erweiterung dort nicht :)

**Comment by GWRon** [comment]
@nittka 
Ich habe die Lokalisierungsklasse erweitert ... hoffe Du hast noch nicht all zu viel herumprobiert und geschrieben.

Du kannst nun einfach *.txt-Dateien in "lang/langcode/..." platzieren, und dann werden die geladen.
Die alten "lang_langCode.txt"-Dateien werden zuerst geladen (falls vorhanden). Die Dateien in den Verzeichnissen _erweitern_ dann die Sprachinstanz. Dort dann getaetigte Uebersetzungen ueberschreiben vorher bestehende (also kann man erweitern - und ueberschreiben).

**Comment by nittka** [comment]
Nein, ich hatte noch gar nicht angefangen. Ich bin nicht sicher, ob es besser ist, die Dateien nach Sprache oder nach Thema zusammenzuhalten.Das Argument für Sprache ist offensichtlich . Wenn es aber um die "Vergabe von Übersetzungsaufträgen" oder Vollständigkeitsprüfung geht, muss man die zusammengehörigen Dateien erst zusammensuchen.

Am Ende kommt es wahrscheinlich darauf an, auf wieviele Dateien man die Lokalisierung verteilt.

**Comment by GWRon** [comment]
Hmm ... Dein Ansatz klingt also eher nach "xml"-Dateien (aehnlich der "<title>" Bereiche in den DBs für Filme/News/...).

Waere auch machbar - waere auch "zusaetzlich" machbar.

**Comment by nittka** [comment]
Nein, bitte bloß kein XML. Das ist organisatorisch ein Alptraum. Es sieht nur so aus, als würde es sich anbieten, aber aus Sicht eines "Übersetzungsauftrags" ist das absolute Chaos vorprogrammiert. Es wird ja nie so sein, dass eine einzelne Person sämtliche Sprachen bearbeitet. Wenn man also zwei Leute hat, die gleichzeitig unterschiedliche Sprachen bearbeiten, hat man hinter ein riesiges Merge-Problem. Die Sprachen in getrennten Dateien zu halten, sollte auf alle Fälle beibehalten werden.
... Zumindest meiner Meinung nach.

**Comment by GWRon** [comment]
Naja ... was schwebt Dir denn vor - so als ... "Format" ?

**Comment by nittka** [comment]
Ich glaube, das Missverständnis wurde dadurch verursacht, dass das Ticketsystem meine spitzen Klammern (um einen Unterverzeichnis mit variablem Namen zu markieren) gleich im zweiten Kommentar verschluckt hat. Sorry, ich war davon ausgegangen, dass ich die Struktur schon eindeutig beschrieben hatte. Am Format möchte ich gar nichts ändern sondern wirklich nur an der Dateiaufteilung. Im Ordner lang gibt es statt einer alles enthaltenden Datei pro Sprache mehrere "thematische" Unterordner, die dann jeweils eine Datei pro Sprache enthalten.

lang/rooms/rooms_en.txt, lang/rooms/rooms_de.txt..., lang/productions/prods_en.txt, lang/productions/prods_de.txt

Für die Prüfung, wie es mit den Übersetzungen zu einem Thema aussieht, bewegt man sich dann immer im selben Ordner (ebenso beim Hinzufügen eines neuen Schlüssels). Idealerweise sollten die Dateinamen nicht nur lang_en.txt sein, damit man daran immer noch erkennt, wo sie hingehören. (Ich würde nicht davon ausgehen, dass jeder Übersetzungswillige ein Github-Account für Pullrequests hat).

Wie gesagt, auch die von Dir aktuell vorgesehene Verzeichnisstruktur funktioniert, wenn man nicht zu viele Themen/Sprachen hat. Es dürfte eine Geschmacksfrage sein.

Welches File-Encoding wird verwendet? Wenn man die Einträge am Gleichheitszeichen ausrichten möchte, sollen dann Leerzeichen (sicherer) oder Tabulatoren verwendet werden (von wievielen Leerzeichen pro Tabulator gehst Du aus)? Ich würde beim Aufräumen diese beiden Punkte gleich richtig und einheitlich vorbereiten wollen.

**Comment by GWRon** [comment]
Ok, Du wolltest also "Themen" und nicht "languageCode"-Verzeichnisse ... hab ich wohl falsch verstanden
Naja, Du kannst ja meinen hinzugefuegten Code trotzdem nutzen (rekursives Verzeichniseinlesen mit Filtern).


Bezueglich Fileencoding. Nun, man kann das wie INI-Dateien machen ("key = value" - eventuell auch "#" als Kommentar usw.) oder sowas wie "POT/PO" ... wobei das vielleicht auch "overkill" ist ... 
Auch JSON waere moeglich - und ist wenigstens "halbwegs" mit einem Texteditor beherrschbar

**Comment by nittka** [comment]
Nein, mit encoding meinte ich das Zeichen-Encoding: UTF-8 oder ISO-8859-1... Aktuell scheinen die Dateien UTF-8-codiert zu sind. Zumindest sind da die deutschen Umlaute OK. Bist Du mit dem Ersetzen von Tabulatoren durch Leerzeichen einverstanden? Dann spielt es keine Rolle, durch wieviele Leerzeichen der Editor die Tabulatoren bei der Anzeige ersetzt. Die (möglicherweise vorhandene) Ausrichtung an den Gleichheitszeichen sieht immer gleich ordentlich aus.

**Comment by GWRon** [comment]
Ja sie sollten UTF8 sein ... sonst hätten wir mit einigen der Lokalisierungen denke ich Probleme :)

Und ob nun Leerzeichen oder "Tab" ... ist an sich Wurst, wenn die Strings "getrimmt" wuerden.

Ob aber eine Datei "visuell ausgerichtet" werden muss ... mit jedem Hinzfuegen eines laengeren Schluessels muessten alle anderen "nachruecken" (in jede Zeile gehen, Leerzeichen hinzfuegen).

Am Besten waere halt immer ein Lokalisierungstool, was Stueck fuer Stueck durchgeht und fehlende Lokalisierungen "abfragt".

**Comment by nittka** [comment]
OK. Wegen der Leerzeichen hatte ich nur gefragt, da die Dateien aktuell schon Blöcke mit ausgerichteten Paaren haben. Ich würde nicht immer die ganze Datei ausrichten. Aber häufig macht es das Lesen solcher Blöcke einfacher. Ich glaube, jetzt habe ich alle Infos, um mich an das Anfangen des Aufräumens zu machen.

**Comment by GWRon** [comment]
Ich denke, das Ticket kann umbenannt werden (Ueberarbeitung Lokalisierung... oder so)

**Comment by nittka** [comment]
Ich bin gerade dabei mit den Aufräumarbeiten bei der Lokalisierung anzufangen. Verständlicherweise kommt ein Teil der Schlüssel aus der deutschen Variante in den anderen Sprachen nicht vor. Es gibt aber auch Schlüssel, die eingetragen sind, aber mit der falschen Sprache übersetzt sind. Das halte ich für problematisch. Hintergrund ist, dass falls kein Wert angegeben wäre, auch nichts in der GUI erscheinen würde.

Mein Vorschlag für eine Änderung an der Lokalisierungsauflösung (Quellcode):
* wenn der Schlüssel nicht vorhanden ist, Fallback auf die Standardsprache (wie bisher)
* wenn der Schlüssel vorhanden ist, aber kein Wert hinterlegt ist, Fallback auf die Standardsprache (bislang wohl Leerstring angezeigt)

Mit dieser Änderung könnte man dauerhaft die Schlüssel in allen Dateien synchron halten (neuen Schlüssel einfach überall eintragen), auch ohne sofort die Übersetzung machen zu müssen. Und jemand der beim Lokalisieren helfen will, sieht sofort, wo noch Lücken sind.
Teil des initialen Aufräumens wäre dann, die Werte zu entfernen, die in der falschen Sprache eingetragen sind. Aber das muss man ja nur einmal machen.

**Comment by GWRon** [comment]
Und was ist mit Werten, die in einer Sprache wegfallen?  Spezifische Suffixe etc?

Fuer diese muesste man wohl einen festdefinierten Wert festlegen. `!EMPTY!` oder so.

Jedenfalls ist obiges der Grund, warum bei "leer aber key da" nix angezeigt wird.

**Comment by nittka** [comment]
Gibt es außer den RandomString-Zahlen andere Suffixe, die sprachspezifisch sind?
Wie würde das denn im Code behandelt werden? Die Idee von Lokalisierung ist doch, dass die Sprache von Code-Seite keine Rolle spielt.

Aber die Random-Strings wären tatsächlich ein Fall, der in der obigen Fallunterscheidung fehlt. Vorschlag wäre hier: In die Auswahl der möglichen Random-Strings werden nur die Keys aufgenommen, für die es für die Sprache einen nichtleeren Wert gibt. Gibt es keine solchen Keys erfolgt der Fallback auf die Default-Sprache.

Zu wegfallenden Werten... Wie kann ein Wert in einer Sprache wegfallen, nicht aber in allen anderen?
