### ISSUE TITLE
GUI-Fehler Regal Drehbücher

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#181]
Aktuell scheint es ein GUI-Probklem beim Zurückstellen von Drehbüchern ins Regal zu geben.
* das am weitesten rechts stehende Drehbuch aus dem Regal  nehmen
* es direkt wieder an den alten Platz stellen (mit Linksklick)
* bei mir wird es dann vor dem links neben ihm stehenden Drehbuch gerendert

Wenn man das Drehbuch nach dem Rausnehmen mit Rechtsklick "zurückfallen" lässt, ist alles OK. Auch wenn man nach dem obigen Ablauf irgendwo in den Raum klickt, repariert sich die Ansicht wieder.

**Comment by nittka** [comment]
Dieser Fehler tritt bei mir wieder auf.

**Comment by GWRon** [comment]
Ich vermute, dass es mit dem "Fokus" (#192, #196, ... ) zu tun hat.
Ein "gefokustes" Objekt wird anders einsortiert ... das zuletzt gedroppte im Regal hat also wohl noch den fokus - und wird "obendrauf" gezeichnet.

Deswegen sortiert es sich auch, sobald man ein anderes "aufhebt" und "fallen" laesst.

**Comment by GWRon** [comment]
Es gibt eigentlich keinen (mir einfallenden Grund), fokussierte Elemente "weiter oben" einzuordnen (spaeter zu rendern, eher zu aktualisieren).

Falls doch, dann muessen die "Slotlists" in der Werbeagentur den Flag fuer "kann Fokus bekommen" entfernt bekommen. Sie werden fokussiert, wenn man "Drop" macht (drauf klickt und es somit "anvisiert").
