### ISSUE TITLE
Hilfe Dev-Kommandos

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#183]
In der Spielanleitung steht, dass man mit /dev help die möglichen Kommandos angezeigt bekommt. Bei mir hat das "nicht geklappt". Tatsächlich ist das Kommando implementiert, aber
* es werden nicht nicht für alle möglichen Kommandos Hilfezeilen erzeugt (z.B. endauctions, reloaddev); hier sollte die Vollständigkeit nochmal geprüft werden
* die Hilfetexte verschwinden wieder sofort

Die Texte werden unten erzeugt, dann wird aber sofort bis ans Ende gescrollt und alles ist weg. Klicken auf den "Hoch"-Knopf hat keine Wirkung. Scrollen mit dem Mausrad nach oben hat keine Wirkung. "Tastaturscrollen" hat keine Wirkung. Nur wenn man mit der Maus auf den Scrollbalken klickt, tut sich was. Danach geht dann auch Mausrad.

**Comment by nittka** [comment]
guiList.SetAutoScroll(True) in base.gfx.gui.chat.bmx Zeile 48 scheint die Anzeige kaputt zu machen. Wenn ich den Wert auf False setze, sehe ich die Einträge sofort. Wenn ich dann in addEntry guiList.update() guiList.ScrollToLastItem() ergänze, sehe ich dasselbe Verhalten. Meine Vermutung ist also, dass ScrollToLastItem() für diesen Anwendungsfall einen Bug enthält.

**Comment by GWRon** [comment]
Also generell wollte ich denn /dev-Teil eh irgendwann obsolet machen...und alles in den "tab"-debug/dev-Bereich integrieren (das erlaubt auch drop-down usw).

Davon abgesehen muss der Chat aber noch an die ganzen GUI-Aenderungen angepasst werden.

Ich schaue es mir bei Gelegenheit an.

**Comment by nittka** [comment]
OK. Prio bezüglich der dev-help (für mich) niedrig. Ob das ScrollToLastItem-Problem noch woanders zuschlägt, kann ich im Moment nicht sagen.

**Comment by GWRon** [comment]
Also was ich jetzt hier "erstmal" noch als unerledigt sehe:
- Vervollstaendigung der Dev-Liste
- Textabstaende (Eintraege zu "hoch")

**Comment by nittka** [comment]
Du meintest ja, dass das ggf. aus dem Chat rauswandern soll. Den Chat als Liste mit festen Höhen zu implementieren, hat auch seine Nachteile (ein Wort vs Roman, der gar nicht reinpasst), aber das ist ein komplett anderes Thema.

**Comment by GWRon** [comment]
Normalerweise sollten die Texte "passend" untereinander stehen - ohne fixe Hoehen. Das kam erst mit dem GUI-Rewrite daher.
