### ISSUE TITLE
Supermarkt: Personen-Information unvollständig

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#184]
Im aktuellen Masterstand wird für einen Darsteller in den Details (Mitwirkung an welchen Produktionen) nur noch das Jahr angezeigt, nicht mehr der Titel.

**Comment by GWRon** [comment]
Hab ich wohl die "Box" fuer den Text zu niedrig angesetzt ("Text passt nicht rein - falls maximale Charhoehe des Fonts genutzt" (wir muessen ja von anderen Zeichen bei Lokalisierung ausgehen)).

**Comment by GWRon** [comment]
Habe die Texthoehe mal angepasst und auch gleich die Schriftfamilie des "Jahres" umgestellt bzw dessen veraltete (nicht mehr noetige) "+1" bei der y-Koordinate entfernt.

**Comment by nittka** [comment]
Der Titel ist wieder sichtbar. Es sieht aber so aus, als würde der Titel etwas höher stehen als das Jahr.

**Comment by GWRon** [comment]
Eventuell ist das ... eine optische Illusion  ... da der rechte Text "dunkler" ist und intensiver wirkt ?

![cast](https://user-images.githubusercontent.com/2625226/99183826-0d084200-273f-11eb-94cb-0302cff6ff44.png)

Oder aber, die freetype-lib spielt mir wieder einen Streich (zumindest unter Windows waren manche Schriften etwas "fetter" als unter Linux). Kannst ja mal einen Screenshot machen und den Ausschnitt vergroessern - vielleicht ist es bei dir ja aehnlich.

**Comment by GWRon** [comment]
Habe nun auch die fette Schrift mit einer "normalen" ersetzt (und den Abstand verringert - passt mehr hin). Zwecks der Fettschrift und einem "y displace" bin ich trotzdem an einem Screenshot interessiert.
Falls nur eine optische Taeuschung, kannst du den Issue danach bitte zumachen :)

**Comment by nittka** [comment]
![base_line](https://user-images.githubusercontent.com/2562651/99184011-573df300-2740-11eb-9bcf-7252d2489480.png)

Keine optische Täuschung (Vergrößerungsmöglichkeit im Browser sollte ausreichen).

**Comment by GWRon** [comment]
Skalierst Du irgendwie das Spiel? Frage, da das ganze Schriftrendering irgendwie "schief" aussieht
Das "f" und "g" in "Erfahrung" sind fetter, der erste Strich vom "u" in Erfahrung ist breiter (gleiches fuer das "n").

Auch der Balken sieht "komisch aus" ....

**Comment by GWRon** [comment]
Achso ... du hast im Browser den Screenshot "gezoomt" und davon einen Screenshot gemacht ?

**Comment by GWRon** [comment]
Generell zeigt mein Bildvergleich aber, dass bei dir die "datasheet/skin . fontSmallCaption" weiter "unten" geschrieben wird (also irgendwie ein Buchstabe als "hoeher" (weiter oben anfangend) angesehen wird und alles "nachruecken" muss).

Vergleiche dazu auch meine "Balken-Texte" und deine ...Deiner ist dort auch 2 Pixel tiefer angesiedelt ... 

Du hast eine Linuxdistri am laufen oder?

**Comment by nittka** [comment]
Ich habe Lubuntu auf einem alten Notebook laufen. Wenn ich spiele, habe ich den Vollbildmodus aktiviert. Da sehen die Schriften auch etwas verwaschen aus, aber das hat mich noch nicht gestört (die Auflösung im Original war ja auch relativ klein).
Bei der Entwicklung ist das Bild kleiner, damit ich das Fenster schneller zumachen oder zu einem anderen Fenster wechseln kann.

Der Screenshot war 1:1 vom Spiel und dann zugeschnitten (keine Skalierung). Tatsächlich weiß ich aber nicht mehr, ob ich gerade dafür im Entwicklungsmodus auf Vollbild umgestellt hatte (und was überhaupt die Auflösung wäre). Wenn Dich das interessiert, kann ich ja nochmal ein bisschen mit den Auflösungen rumspielen.
