### ISSUE TITLE
Mauszeiger - neu und interaktiver

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#185]
Ich habe gestern ueber den Mittag mal ein erstes "neues" 3D-Modell der Hand erzeugt und wollte es in neuen Posen rendern.

Warum wieso weshalb?
- neue Posen erlauben neue Interpretationen
- Split von "Hand" und "Overlay"
- Animationen?

Wir koennen neue Posen nutzen - vielleicht eindeutigere?
Wir koennen andere Overlays einbinden: Geldscheine neben der Hand, wenn der Film ueberm Verkaeufer ist, blinkerende Ausrufezeichen , blaue "i" fuer Informationen (Drehbuch auf Studioleiter...).

Der Zeigefinger koennte "wackeln", wenn etwas verboten ist ("nicht dropbar") usw.

Neben diesen optischen Spielereien, koennte man dem Mauszeiger auch einen einfachen Tooltip mitgeben -- also einen Text, mit einem Schatten oder aehnliches.
So koennte der Mauszeiger untendrunter "Verkaufen" stehen haben, wenn ueberm Verkaeufer (wenn die "Geldscheine"-Idee nicht so gut angenommen wird), oder der Raumplan koennte "Shortcut __Q__" anzeigen ... 

Allerdings koennte man auch die Tooltips der jeweils interaktiven Objekte dafuer nutzen ... bin mir da also ueber den Nutzen noch nicht so sicher.

Neue Bilder und das Trennen von "Hand" und "Overlay" finde ich aber durchaus nuetzlich.

**Comment by GWRon** [comment]
Grober Erstvorschlag ... Beleuchtung etc muss ich noch anpassen, so dass es in "klein" nicht zu verwaschen aussieht.
![hand](https://user-images.githubusercontent.com/2625226/99185385-c704ab80-2749-11eb-8581-aa540c25a066.png)

**Comment by GWRon** [comment]
![curso](https://user-images.githubusercontent.com/2625226/99237969-7187d780-27f9-11eb-84aa-25e75e854048.png)

Ich hoffe es stoert sich keiner an der hellen Hautfarbe (vorher war es ein neutrales "gruenliches gelb") ... das koennte man vielleicht aber auch noch anpassen ...hmm

**Comment by GWRon** [comment]
Allgemein glaube ich, der Cursor darf ruhig etwas "groesser" werden ... oder nicht?

**Comment by nittka** [comment]
Interessant wird es bei der Interaktion mit "kleinen" Sachen - Werbung/Filme holen oder die kleinen "Kassetten" im Programmplaner auswählen. Ein Hervorheben des Objekts, das man nehmen würde, ist hilfreich.

**Comment by GWRon** [comment]
Die meisten Objekte werden doch schon "hervorgehoben" ?

**Comment by nittka** [comment]
Ich hab' so lange nicht mehr gespielt - nur noch programmiert ;-)

**Comment by GWRon** [comment]
Habe den neuen Cursor hochgeladen - und die "Reihenfolge" der Cursorsetzungen im Code aufgeraeumt.

Es wird nun unterschieden, ob ein Element "interaktiv" (mausbutton etc) ist, oder "aufhebbar".

Fuer "interaktiv" habe ich noch keinen geeigneten Cursor erstellen koennen ... das wuerde zu oft zwischen "Zeigefingercursor" und "interaktiv" wechseln .. 

Aufheben hat eine normale "flache Hand" und "nicht aufhebbar" (bzw Startsendung) bekommt ein "pulsierendes" Stoppschild obendrauf ... das ist nun losgeloest und koennte auch auf anderen Cursorvarianten platziert werden.

Das Cursorset enthaelt auch Sprites fuer eine "Waving-Stop"-Animation (zweite Reihe, Sprites 1,2,1,3,1,2, ... )  ... aber so richtig gepasst hat das nicht. Gleiches gilt fuer die "Ruhehaltung" der Hand (letzte beiden Haende)
![cursor](https://user-images.githubusercontent.com/2625226/99305104-9d37ab80-2853-11eb-87e9-180f06194987.png)

Eventuell koennte der vorletzte fuer "interaction" genutzt werden (so als "druecken" Anzeiger).

Kannst du gerne probieren: config/startup.xml - und dort bei "interact" die Koordinaten anpassen.

**Comment by nittka** [comment]
Erste Eindrücke:
* Cursor ist größer, daran kann man sich aber wohl gewöhnen (ggf.problematisch bei kleinen Interaktionsobjekten)
* statt er dritten Hand würde ich fast die letzte für das Festhalten/Aufheben von Objekten nehmen (die dritte sieht etwas nach "igitt - schmutziges Taschentuch" aus)
* die "Verboten"-Hand müsste nicht nur für die Startsendung verwendet werden, sondern auch für bereits laufende oder gelaufene Programme
* für die Auswahl einer Filmkategorie funktioniert der Zeigefinger sehr gut

Besondere Aufmerksamkeit muss noch der Auswahl von Werbung Filmen etc. an allen Stellen gewidmet werden.
* Werbeagentur: Hovern über einer Werbung in der Mitte, Maus langsam nach rechts bewegen - die Hand ist schon fast vollständig über der rechten Werbung, bevor die Selektion umspringt
* Filmagentur: analog
* Programmplaner: bei mehreren Filmen untereinander ist die Hand praktisch komplett über dem unteren Film, der darüber ist aber immer noch aktiv

Ich gehe mal davon aus, dass es das ist, was Du mit Koordinaten anpassen meinst. Bei der Zeigefingerhand muss das "Interaktionszentrum" beim Zeigefinger liegen, bei der Interaktivhand (Hand 2?) muss das Zentrum in der Handfläche liegen. Ggf. ist der Mauszeiger für die eng nebeneinander liegenden Objekte einfach zu groß (Hand liegt auf 3 Filmen gleichzeitig).

**Comment by nittka** [comment]
```
<children>
	<child name="gfx_mousecursor_point"            x="0"    y="0"    w="48"  h="50" offsetLeft="22" offsetTop="4" />
	<child name="gfx_mousecursor_interact"         x="0"    y="0"    w="48"  h="50" offsetLeft="22" offsetTop="4" />
	<child name="gfx_mousecursor_pick"             x="48"   y="0"    w="48"  h="50" offsetLeft="24" offsetTop="17" />
	<child name="gfx_mousecursor_hold"             x="190"  y="50"   w="48"  h="50" offsetLeft="24" offsetTop="17" />
	<child name="gfx_mousecursor_stop"             x="0"    y="50"   w="48"  h="50" offsetLeft="24" offsetTop="17" />
	<!-- if we wanted to use an animation: -->
	<child name="gfx_mousecursor_stop0"            x="0"    y="50"   w="48"  h="50" offsetLeft="24" offsetTop="17" />
	<child name="gfx_mousecursor_stop1"            x="48"   y="50"   w="48"  h="50" offsetLeft="16" offsetTop="7" />
	<child name="gfx_mousecursor_stop2"            x="0"    y="50"   w="48"  h="50" offsetLeft="16" offsetTop="7" />
	<child name="gfx_mousecursor_stop3"            x="96"   y="50"   w="48"  h="50" offsetLeft="16" offsetTop="7" />
	<child name="gfx_mousecursor_halfpoint"        x="190"  y="50"   w="48"  h="50" offsetLeft="22" offsetTop="8" />
	<child name="gfx_mousecursor_stop_overlay"     x="144"  y="0"    w="48"  h="50" offsetLeft="24" offsetTop="17" />
</children>
```

**Comment by GWRon** [comment]
Was ist warum geaendert? Ich hatte die offsets auf die Mitte der Finger (Zeigefinger, zeige+Daumen,...)

**Comment by nittka** [comment]
Siehe Kommentar darüber. Für den Zeigefinger habe ich Top-Offset 1 Pixel tiefer genommen. Für das Greifen habe ich alles stark Richtung Handzentrum verschoben. Insb. beim Filme-Greifen im Programmplaner ist sonst die Hand "komplett"auf einem Film, selektiert ist aber einer drüber - das finde ich total verwirrend.
Beim Zeigefinger ist optisch ersichtlich, dass der Zeigefinger die Stelle der Interaktion ist, bei der offenen Hand sollte das horizontale Zentrum eher in der Mitte liegen (das sieht man besonders gut in der FIlm- und Werbeagentur, wenn man von links nach rechts und umgekehrt über die Filme/Werbeordner hovert).
Die Greifhand habe ich auch angepasst (ausgetauscht). Das sieht für mich "schöner" aus.

Auch das Zentrum der Stop-Hand ist verschoben. Gut zu sehen ist der Unterschied am ersten Spieltag, wenn man zwischen Start-Show und erstem selbst platzierten Sendeblock hin- und herwechselt.

(Was genau geändert am leichtesten sichtbar, wenn Du das Snippet kopierst und dann das Diff anschaust.)

**Comment by GWRon** [comment]
Ja den diff meinte ich nicht... sondern eher die von dir nun angebrachten Erklaerungen.

Mit der "Hand" bin ich halt ne ganz so zufrieden gewesen.

Fuer "interact" (ueber buttons etc) koennte man die ✋ auch leicht einfaerben... Oder der Zeigefinger allein wird eingefaerbt...

**Comment by nittka** [comment]
Ich kann den Aufwand nicht abschätzen und ich hätte auch kein Problem mit der aktuellen interact-Hand (gegeben, der Fokuspunkt kann verschoben werden)... Wäre es möglich, das Interact aufzutrennen in 
* "Patschehand" für großflächige Interaktionen (auch Nehmen von großen Dingen: Einkaufszettel in Studio, Programmblock im Planer)
* eine wie ein C geformte (Finger zusammen, Daumen den Fingern gegenüber) nach vorn gerichtete Hand zum Nehmen von schmalen Dingen, die liegen (Werbung, Filme aus der Auswahl .im Programmplaner); (Form der Hand als wenn man ein in Kopfhöhe horizontal vor sich schwebendes Buch greifen wollen würde)
* selbe Form 90 Grad gedreht zum Nehmen von schmalen Dingen die stehen (Werbeagentur, Drehbuchagentur, Filmagentur)

Durch die C-Form der Hand kann man den Fokus in die Mitte zwischen Daumen und Finger legen und damit sollte auch optisch klar sein, welches Objekt gegriffen werden soll.

Wenn man gut erkennen soll, wann eine Interaktion möglich ist und wann nicht, könnte die "neutrale Hand" etwa so aussehen wie Hand 4 in der zweiten Reihe: alle Finger leicht eingeknickt und kurz wirkend (Hand entspannt, weder zur Faust geballt noch Finger ausgestreckt).
Wenn dann eine Aktion möglich wird, werden die Finger lang (Achtung ich will zupacken - bereit für die Aktion); oder die Hand formt sich entsprechend der möglichen Aktion (Zeigefinger, Greifen).

(Ich muss meine "Ich hoffe, Du empfindest das alles nicht als Meckern"-Bemerkung noch einmal unterstreichen.)

**Comment by GWRon** [comment]
Die Greifhand hatte ich schon kurz probiert...aber noch keine zufriedenstellende Pose hinbekommen. Muss vlt das Rig der Hand optimieren.

**Comment by nittka** [comment]
Wäre es eine Alternative (falls kein besserer Mauszeiger zu finden ist), für die kleinen Greif-Objekte auch den Zeigefinger zu nehmen? Dann sollte an allen Stellen (Programmplaner Werbe-/Filmauswahl, Film-/Drehbuch-/Werbeagentur) das zu greifende Objekt eindeutig (sowohl horizontal als auch vertikal ist die Zeigefingerposition offensichtlich).

**Comment by GWRon** [comment]
Ich versuche heute Abend mal meine Hand neu zu riggen... Der alte Rig war wohl zu halbherzig und bewegt die Finger nicht so, wie es soll.

**Comment by GWRon** [comment]
Habe jetzt neue Mauszeiger integriert - eventuell ist der alte "hold" (Reihe 3, Spalte 5) besser geeignet, als der von Dir favorisierte (R2,S3) den ich aktuell nutze - aber nochmal 2 Pixel nach Links verschoben habe.
![cursor](https://user-images.githubusercontent.com/2625226/99820761-7fb75a00-2b51-11eb-8cb3-4777fb31d268.png)

Neu sind nun: pick_horizontal, pick_vertical, pick_fine (den ich eigentlich als "hold" geplant hatte - wie wenn mann einen Faden oder so haelt)

**Comment by GWRon** [comment]
So bleibt als "todo" die Textunterschrift ... also "Verkaufen", "Kaufen" usw.
Ausser... das ist "zu viel des Guten" und unnoetig... ?

**Comment by nittka** [comment]
Sehr schön! Gern den alten hold-Mauszeiger (R3S5). Ich wollte nur nicht pick_fine für das Halten. 

* pick-horizontal bitte nicht nur für die Werbe-Kassetten im Programmplaner sondern auch für die Filme
* im Hilfe-Fenster wird nicht der Zeigefinger für die Tasten verwendet

Die Textunterschriften würde ich weglassen. Das ist für die erste Interaktion vielleicht nett, danach nervt es nur noch.

**Comment by GWRon** [comment]
Oh .. hatte ich wohl nur fuer Episoden den Mauszeiger geaendert.

Das Hilfefenster setzt (noch) nicht den Mauszeiger zurueck - wenn man das also ausprobiert und vorher ein "Zeigefinger" war...faellt es nicht auf.

**Comment by GWRon** [comment]
Letzter Commit behebt das erstmal "provisorisch".

**Comment by nittka** [comment]
Der Mauszeiger im Fahrstuhl sollte der Zeigefinger sein! Das horizontale Nehmen bei der Hinweistafel ist aber OK.

Bei einigen Elementen verwendelt sich der Zeigefinger nach einer Weile kurz in den Klickfinger (wohl als Hinweis auf ein interaktives Element). Wie wäre es, wenn statt dessen die letzte Hand aus Zeile 2 die neutrale Hand zu nehmen und in einen Zeigefinger zu verwandeln, wenn man über einem aktiven Element ist (Knopf, Tür, etc.) Vielleicht würde dadurch aber alles zu unruhig. Ein bisschen Erforschen muss man ja auch.

**Comment by GWRon** [comment]
Mauszeiger sollte nun im Fahrstuhl der "Zeigefinger" sein. Habe das Aendern des Cursors von "updates" nach "rendern" geschoben (bei jedem Objekt).


@ Hand und Zeigefinger
Das wird vor allem bei "Buttonreihen" oder aehnlichem schnell "unruhig".

**Comment by nittka** [comment]
Ja, ich kann mit der aktuellen Variante gut leben. Gibt es noch Punkte zu diesem Ticket, an denen Du dran bist?

Eine Frage zum Verboten-Overlay: aktuell wechselt auch die Handform, wenn eine Aktion verboten ist (z.B. Versuch ein zu teuren Film zu kaufen). Hast Du mal ausprobiert, das Verbots-Overlay einfach über den aktuellen Mauszeiger zu legen?

**Comment by GWRon** [comment]
Ja ... man koennte das "Stop" auch extra packen - ist ja ein "overlay". Habe schon ein paar Vorarbeiten dazu gemacht - "SetCursor()" braeuchte da nur noch einen neuen Parameter - und dann koennten wir "Stop" aehnlich machen, wie andere eventuell noch kommende Extras ("Geldscheine", "info-icon" ...).

**Comment by GWRon** [comment]
"Forbidden" (Stoppzeichen) ist nun ein "Extra" - und wird optional zum Cursor eingestellt.
![mauscursor](https://user-images.githubusercontent.com/2625226/99915091-ca77d400-2d01-11eb-9fcc-9becd2ca4adb.png)


Denke es gibt noch einige Bereiche im Spiel, bei denen das Extra gesetzt werden kann (habe jetzt noch den Werbemakler bzw die Werbevertraege hinzugenommen)

**Comment by nittka** [comment]
Drehbücher könnten auch noch zu teuer sein.

Aber insgesamt denke ich, dass man auf dieses Ticket einen Deckel draufmachen kann und weitere Verbesserungen in konkreten separaten Tickets erfasst.
