### ISSUE TITLE
Nachfolgeticket produktive Tastenkürzel

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#186]
In einer ersten Version wurden Tastenkürzel implementiert, die auch bei deaktivierten Dev-Keys funktionieren. Die Kürzel für die Raumauswahl ist fast aber nicht genau deckungsgleich. Für eine finale Version müssen folgende Punkte geklärt und umgesetzt werden.

* genau welche Funktionen sollen (in welcher Version) per Tastenkürzel unterstützt werden
* Sicherstellen, dass dieselbe Funktion in beiden Versionen (möglichst) dasselbe Tastenkürzel hat
* gemeinsamen Code rausziehen/wiederverwenden
* Dokumentation der Tastenkürzel in der Anleitung
* Tastenkürzel ggf. in der GUI anzeigen (Raum-Kürzel im Fahrstuhl, beim Hovern über der Tür,...)

Offen aus dem originalen PR ist, ob das Simulieren eines Rechtsklick nötig ist (nicht nur Raum verlassen per Tastendruck, sondern auch Abbruch einer Aktion, Verlassen einer Unterseite,..). Aktuell bietet der Mousemanager dafür keine öffentliche API.

Für die produktive Version, ist mir wichtig, dass die Tastenkürzel möglichst ohne shift/ctrl etc auskommen (aus diesem Grund hat der Schnellvorlauf - solange man auf die Taste drückt - auch nur die Pfeiltaste nach rechts).

**Comment by nittka** [comment]
Haben wir hier für 0.7 einen stabilen Stand? Wichtig wäre, dass die Kürzel für die bereits existierenden Aktionen stabil sind.

**Comment by GWRon** [comment]
Auch hier fehlte meine Antwort (vom 25.01.)

> Ich habe hier noch nix "eigenes" gemacht.
> Wir koennen das gern die Tage noch auf einen "allgemeinen Stand/gemeinsamen Nenner" bringen.

**Comment by nittka** [comment]
Ich frage mich, ob wir dazu übergehen sollten, (auch) "Nicht-Developer"-Versionen auszuliefern. Wenn ich es richtig sehe, bietet Blitzmax eine Release-Option für Conditional Compilation. Diese könnte man verwenden, um die Dev-Konfigurationen zwar in der config.xml drinzulassen, aber im Release-Modus zu ignorieren.

Welche Funktionen würde ich im Release-Modus entfernen?
* Beamen zum Raum via Tastenkürzel
* Debug-Screen mit Manipulationsmöglichkeiten
* Cheaten via Chat (/dev)
Welche Funktionen würde ich im Release-Modus drinlassen?
* Geschwindigkeitstastenkürzel (Zahlentasten)
* die schon vorbereiteten Gehe-Zum-Raum-Tastenkürzel
Bei welchen bin ich mir unsicher?
* Quotenbildschirm

Es könnte noch Funktionen, geben, die ich nicht kenne und die vom Releasemodus betroffen sein könnten...

Das Spiel ist zwar nicht fertig, aber der typische Spieler wird die Dev-Optionen nicht nutzen (Cheaten, Beamen) oder sollte es zumindest nicht. Die Raumwechseltastenkürzel finde ich aber extrem praktisch.

Alternativ-Vorschläge:
* Dev-Keys bei der Auslieferung per Default auf false setzen (Problem alte Spielstände würden trotdem mit debug weiterlaufen, Debug-Screen hängt bestimmt auch mit dran)
* Auftrennen der Dev-Key-Interpretation (Konfiguration für Beamen an/aus, die dann per Default false ist)

Sauberer fände ich aber den Release-Modus.

**Comment by GWRon** [comment]
"release" ist einfach nur "nicht debug". Und Debugversionen sind seeehr langsam (da jeder Funktionsaufruf, jeder Loop ... einen Debug-frame generiert, der alle Daten des aktuellen Vorgangs bereithaelt - also eine Art Debugstack).

Deswegen der Umweg ueber die "DEV.xml".
Was man aber einfach machen kann (und Du ja auch als Alternative bereits anklingen laesst), ist in den Github-Workflows die DEV.xml entsprechend "anzupassen" (bzw beim Release dann anzupassen und bei den eventuellen Nightlies drin lassen)

Die "Beamen an/aus"-Sache koennen wir aber gern trotzdem separieren (gilt fuer einige dieser Dev-Optionen + den allgemeinen "alle dev-Sachen aus"-Schalter)

**Comment by GWRon** [comment]
Ich habe bezueglich `?release` mal ein ticket im Compiler-Repo (bcc) aufgemacht ..
https://github.com/bmx-ng/bcc/issues/572

Derzeit wird das zwar in den Docs aufgefuehrt - aber wird im Compilerquellcode nicht definiert. Undefinierte Conditionals sind per se "false" (in BlitzMax NG, im alten BlitzMax muss es vom Compiler verstanden werden - bekannt sein). 

Ich habe zwar irgendwie wenig Hoffnung, dass `?release` so umgesetzt wird, wie von uns gewuenscht - oder, dass ein `?development` conditional eingefuehrt wird, aber naja ... mal schauen.

**Comment by nittka** [comment]
Doof - laut Dokumentation wären sogar nutzerdefinierte Optionen (als kommaseparierte Liste) möglich. Vermutlich kann man das nicht als Workaround nutzen (da wie Du sagst unbekannte Conditionals false sind).

**Comment by GWRon** [comment]
nutzerdefiniert sollte nicht gehen. Das hatte ich mal angefragt aber wurde nicht umgesetzt.

Du kannst theoretisch "pre.bmk" anlegen und dort was gescriptetes ausfuehren (also bspweise eine Code-ersetzung) und dann in "post.bmk" wieder rueckgaengig machen ... aber das ist nichts ganzes, nichts halbes.

Generell hab ich dadurch aber einen Bug im Compiler gefunden (der ignoriert "?release" weil "release" ein keyword ist - auch wenn ich glaube, dass es deprecated sein koennte). Mal sehen ob wir ein neues conditional bekommen, oder ob "?release" dann doch genau das wird, was wir wollen (wobei derzeit "not debug" einfach "release" bedeutet - auch von den Dateien in "/.bmx" her). Mal schauen.

**Comment by nittka** [comment]
Es geht natürlich auch, im Code die "dev"-Werte aus der Konfiguration nicht auszuwerten. Dafür müsste man aber vor/nach dem Release immer wieder den Code anpassen.

Man könnte das natürlich auch vom Versions-String abhängig machen. Wenn der auf "-dev" endet, sind die Dev-Optionen prinzipiell aktiv.

**Comment by GWRon** [comment]
Neben dem Versionsstring koennte man auch einfach eine "base.settings.bmx" oder so einfuehren, die eben solche Dinge wie dev-Schalter beinhaltet (nur ein paar Integer und eine globale Instanz). Die koennen dann von allen interessierten importiert und genutzt werden. Also so wie die GameSettings oder aehnliches.
Damit errecht man dann allerdings nichts in "/dig/..." da wir ja dort nichts spielspezifisches hinterlegen woellten.

**Comment by nittka** [comment]
Um die dev-keys nicht manuell für ein Release deaktivieren zu müssen, könnte die GitHub-Action auch automatisch eine Text-Ersetzung machen. Das fände ich als Zwischenlösung sinnvoll und würde dieses Ticket damit dann als gelöst betrachten.
