### ISSUE TITLE
[GUI] ScrollablePanel/Textarea sollte auf PgDown/Up reagieren

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#188]
@nittka schrieb:
> Hilfe-Fenster wird erweitert mit Umschaltmöglichkeit für die Anzeige der allgemeinen Spielanleitung
Kurze Nebenfrage: Ich würde gern Pos1, Ende, Bild Hoch/Runter Runter und Pfeiltaste Hoch/Runter für die HIlfe implementieren. Siehst Du das Reagieren auf diese Tasten eher in der main.bmx (Wenn Hilfe offen, dann ...) oder in der Update-Methode des TextArea (schließlich könnte es auch andere Fälle von TextArea-Verwendungen geben, wo ein Scrollen per Tastatur erwünscht wäre). Auf Mausscrollen reagiert das Area ja auch selbständig.

Ich schrieb (im Pullrequest #182):
> Ja, also die Bildlauftasten sollten dann wohl eher von der Textarea (oder ScrollablePanel) behandelt werden - kann ich vielleicht in der Mittagsschlafpause schon selbst erledigen.

**Comment by GWRon** [comment]
@nittka 
Ich habe Textareas in den Ingamehilfen und die Liste fuer Speicherstaende bei "Laden" "fokussiert", damit sollte Keyboardkontrolle in den Elementen moeglich sein, ohne, dass nach Fensteroeffnen erst noch ein "klick" notwendig ist.

**Comment by nittka** [comment]
Möglicherweise ist durch die Änderungen zum Tastaturscrollen die Reaktion auf die Dev-Keys (Prod-Keys noch nicht probiert) kaputt gegangen.
* Spielstand geladen - Raumwechsel mit Tastatur möglich
* Hilfe mit F1 geöffnet und wieder geschlossen
* Tastenkürzel gehen nicht mehr

**Comment by GWRon** [comment]
Hmm ... dann sollte wohl beim Schliessen der Hilfe (das Objekt wird nicht geloescht) der Fokus entfernt werden ...

**Comment by GWRon** [comment]
Der "Fehler" ist, dass ich DevKeys nun nur noch "ueberpruefe", wenn kein GUI-Objekt den Fokus hat (also weder "Button", noch ein aufgehobenes "Programm" im Planer).

Vielleicht sollten GUIObjekte noch ein "IsHandlingKeyboardInput()" oder so bekommen - und nur die Elemente, die Tastendruecke verarbeiten sind dann bei den DevKeys relevant...

Unabhaengig davon, sollte der "OK" Button des Modalfensters seinen Fokus verlieren (bei Entfernung des Fensters ist dies das fokussierte Objekt) ... schau ich mir aber nochmal an, wenn die Kinder Mittagsruhe machen

**Comment by GWRon** [comment]
Habe einen neuen Commit hochgeladen .... nun wird korrekt der Fokus entfernt - und es wird auch nicht mehr auf "hat ein Objekt Fokus" bei den DevKeys ueberprueft - die Ueberpruefung, ob etwas Tastendruecke verarbeitet, solltet reichen. Dazu bekamen die Listen und die Textarea nun noch den Flag, eben Tastendruecke zu verarbeiten.

**Comment by nittka** [comment]
Ich schaffe es im Moment nicht, in der Hilfe nur eine Seite weiterzuschalten. Der keyDown-Code (vs. keyHit) schlägt zu schnell ein zweites Mal an. Außerdem sollte doch ein PageDown nicht fix 10 Zeilen runterscrollen, sondern 1x Höhe des Text-Areas, oder? Sonst springt man bei kleinen Fenstern zu viel, bei großen zu wenig...

**Comment by GWRon** [comment]
Du kannst ja fuer den keywrapper die dir angenehmen Werte ermitteln.

Evtl sollten die KeyHits auch mit Keywrapper ersetzt werden?

**Comment by nittka** [comment]
Ich verstehe die Antwort nicht. Kann in einer Konfigurationsdatei gesetzt werden, wie lange die Zeit zwischen zwei Tastaturabfragen ist, bzw. in welchem Zeitintervall die Update-Methode eines GUI-Elements aufgerufen wird? Zumindest letzteres wahrscheinlich nicht.
Selbst wenn ich nur ganz schnell Bild runter drücke, laufen ggf. zwei "updates" des TextArea und es wird 20 Zeilen weitergescrollt. Bei der Tastatursteuerung für die Senderpositionierung habe ich deshalb explizit ein Warte-Intervall gesetzt, denn sonst konnte man auch nicht pixelgenau positionieren.

**Comment by GWRon** [comment]
Ab jetzt koennte man eine eigene THoldKeyInformation-Instanz aufsetzen (mit eigenen "Intervallen"), diese immer "Update()" und dann mit "IsPressed()" abfragen. Das laesst die globalen Intervalle (falls die Tasten auch in Eingabefeldern genutzt wuerden) intakt.
