### ISSUE TITLE
Supermarkt Drehbuch-Info verschwindet nicht mehr

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#189]
Wenn man aktuell im Supermarkt über einem Einkaufszettel hovert, erscheint die Information wie gewünscht, verschwindet dann aber nie wieder. Selektieren oder Wegbewegen der Maus helfen nicht.

**Comment by GWRon** [comment]
Hatte ich aus irgend nem Grund in einem der letzten Commits eine notwendige Zeile geloescht... Herrje. Danke.
