### ISSUE TITLE
Fenstergrößen Programmplaner

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#190]
Im Moment verdeckt die Information zu "gehoverten" Film den ersten Buchstaben in der Filmauswahl. Vielleicht könnte man "Dauerwerbesendung/Call-In" auf "Werbesendung/Call-In" oder "Werbung/Call-In" kürzen, die Kategorie-Auswahl dadurch ein paar Pixel schmaler machen, die Filmauswahl entsprechend nach rechts verschieben und so den vollständigen Titel sichtbar machen. Dadurch, dass der Teil der Kassette links ggf. nicht sichtbar ist, ist die Hervorhebung des gewählten Films auch weniger auffällig.

Spricht was dagegen, die Kategorieauswahl grundsätzlich 2 Pixel weiter rechts und die Filminfo 2 Pixel weiter links zu positionieren?

**Comment by GWRon** [comment]
Oft habe ich Sachen optisch ausgerichtet...also linker Rand = oberer Rand

Aber spiel ruhig damit rum.

**Comment by nittka** [comment]
Ich vermute mal, dass hier auch die Sprites angepasst werden müssten, da sich die Breite danach richtet. Das Genre-Auswahlfenster 10 Pixel (oder etwas mehr) nach rechts verschieben hat schon den geünschten Effekt. Aber an die Grafiken will ich nicht ran...

**Comment by nittka** [comment]
Als Alternativlösung wurden die Farbe der Sprites für das Hovern angepasst.
