### ISSUE TITLE
Beim Speichern wird kurzzeitig auf eine andere Bildschirmgröße umgeschaltet

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#194]
Wenn ich beim Speichern das Überschreiben einer alten Datei bestätige, wird kurzzeitig die Bildschirmgröße umgeschaltet (nicht das gesamte Bild sichtbar, nur untere linke Ecke). Wenn das Speichern beendet ist, stimmt es wieder.

Vollbildmodus ist deaktiviert, Auflösung ist etwas kleiner als die Bildschirmgröße, Vsynch aktiviert, Renderer GL2SDL.

**Comment by GWRon** [comment]
Das hat sicher was mit dem Virtuellen Grafikmodus zu tun ... also dem Skalieren

**Comment by nittka** [comment]
Bei mir findet noch immer eine "Umskalierung", nun aber nicht mehr so drastisch. Tatsächlich würde ich diesem Thema auch eine niedrige Priorität geben.
