### ISSUE TITLE
Segmentation fault bei Programmplanung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#197]
Ich habe gestern einen Spielstand gespeichert (neu angefangenes Spiel). Ich bekomme reproduzierbar einen segmentation fault, wenn ich nach dem Laden im Programmplaner versuche, die "Historisch"-Kategorie aufzumachen, um den nächsten freien Programmblock zu belegen.
[neu.xml.tar.gz](https://github.com/TVTower/TVTower/files/5579960/neu.xml.tar.gz)

**Comment by nittka** [comment]
Achtung, dieser Fehler tritt auch beim Start eines komplett neuen Spiels auf! Filme holen und versuchen zu planen. Das Problem muss also mit den letzten Commits reingekommen sein (update->render?).

**Comment by GWRon** [comment]
Fix kommt denke in Kuerze.
