### ISSUE TITLE
[Eigenproduktion] "attributeMod" falsch berechnet

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#198]
Aktuell berechnet sich "attributeMod" so:
```BlitzMax
			local attributeMod:Float = 1.0
			local attributeCount:int = 0
			'loop through all attributes and add their weighted values
			for local i:int = 1 to TVTPersonPersonality.count
				local attributeID:int = TVTPersonPersonality.GetAtIndex(i)
				local attributeGenre:Float = genreDefinition.GetCastAttribute(job.job, attributeID)
				local attributePerson:Float = personalityData.GetAttribute(attributeID)
				'skip if attribute is ~0
				if MathHelper.AreApproximatelyEqual(attributePerson, 0.0) then continue
				if MathHelper.AreApproximatelyEqual(attributeGenre, 0.0) then continue

 				attributeMod :+ attributeGenre * attributePerson
				attributeCount :+ 1
			Next
			'calc average
			if attributeCount > 1
				attributeMod :/ attributeCount
			endif
```
Es wird faelschlicherweise Bei der Durchschnittsberechnung der "Boni/Mali" die "1.0" des Startwerts mit reingezogen.
also bei nur einem "genutzten" Attribut oder "keinem", ist das kein Problem:
0: "1.0"
1: "(1.0 + 0.1)/1" = "1.1"
aber bei 2 und mehr ...
2: "(1.0 + 0.1 + 0.3)/2" = "0.7"

Damit sind derzeit in Eigenproduktionen "Amateuere" mit einem "attributeMod" von 1.0 versehen, waehrend Profis vielleicht nur 0.5 bekommen.

Kurzum: attributeMod muss mit "0" anfangen, und dann nach der Durchschnittsbildung muss "+1.0" gemacht werden.

Ist lokal schon behoben.

**Comment by nittka** [comment]
Ich störe mich etwas an den "continue"s (bzw. mindestens einem der beiden). Angenommen es gibt 2 für das Genre relevante Attribute. Ein Darsteller hat für beide 100% einer nur für eins der beiden 100% (für das andere 0). Da nun aber bei 0 das Attribut ignoriert wird bekommen beide denselben Wert bei der Durchschnittsberechnung.

Ich würde sagen, für die Durchschnittsberechnung müssen alle relevanten Attribute herangezogen werden - unabhängig vom Wert. (D.h. kein continue bei attributePerson=0?)

**Comment by GWRon** [comment]
Der gefixte Code (also mit "0" anfangen) waere:
```
			'=== ATTRIBUTES - GENRE MOD ===
			'allows to gain bonus from having the right attributes for
			'the desired job, regardless of whether you are experienced
			'in this job or not
			local attributeMod:Float = 0
			local attributeCount:int = 0
			'loop through all attributes and add their weighted values
			for local i:int = 1 to TVTPersonPersonality.count
				local attributeID:int = TVTPersonPersonality.GetAtIndex(i)
				local attributeGenre:Float = genreDefinition.GetCastAttribute(job.job, attributeID)
				local attributePerson:Float = personalityData.GetAttribute(attributeID)
				'skip if attribute is ~0
				if MathHelper.AreApproximatelyEqual(attributePerson, 0.0) then continue
				if MathHelper.AreApproximatelyEqual(attributeGenre, 0.0) then continue
 				attributeMod :+ attributeGenre * attributePerson
				attributeCount :+ 1
				'print person.GetFullName() + ":  " + TVTPersonPersonality.GetAsString(attributeID) + " : personValue="+attributePerson + " genreValue="+attributeGenre
			Next
			'calc average
			if attributeCount > 1
				attributeMod :/ attributeCount
			endif
			'add the attribute bonus/malus
			'we add the 1.0 afterwards to exclude it from "average calc"
			attributeMod = 1.0 + attributeMod
```

und da hast du recht - das `continue` bei `attributePerson` muss weg. Wenn Genre es anfordert, dann ist die Personeneigenschaft natuerlich wichtig.

Gut erkannt!

**Comment by GWRon** [comment]
```Blitzmax
			'=== ATTRIBUTES - GENRE MOD ===
			'allows to gain bonus from having the right attributes for
			'the desired job, regardless of whether you are experienced
			'in this job or not
			local attributeMod:Float = 0
			local attributeCount:int = 0
			'loop through all attributes and add their weighted values
			for local i:int = 1 to TVTPersonPersonality.count
				local attributeID:int = TVTPersonPersonality.GetAtIndex(i)
				local attributeGenre:Float = genreDefinition.GetCastAttribute(job.job, attributeID)
				local attributePerson:Float = personalityData.GetAttribute(attributeID)
				'skip if attribute is unimportant for the genre
				'(~0 as floats could be "0.00001")
				if MathHelper.AreApproximatelyEqual(attributeGenre, 0.0) then continue

 				attributeMod :+ attributeGenre * attributePerson
				attributeCount :+ 1
				'print person.GetFullName() + ":  " + TVTPersonPersonality.GetAsString(attributeID) + " : personValue="+attributePerson + " genreValue="+attributeGenre
			Next
			'calc average
			if attributeCount > 1 Then attributeMod :/ attributeCount
			'add the attribute bonus/malus
			'we add the 1.0 afterwards to exclude it from "average calc"
			attributeMod = 1.0 + attributeMod
```
Denke so muesste es passen.

**Comment by GWRon** [comment]
Weil ich das gerade ueberarbeite ... ist mir aufgefallen, dass nicht nur das "continue" falsch war.

Die Genre definieren nicht, wie wichtig ein bestimmtes Attribut ist - sondern ob es "wichtiger als normal" ist.
Also ein "humor 0.1" bedeutet, Humor wird hier 10% "groesser" bewertet. ein "power -0.2" bestraft Muskelprotze usw.

Entsprechend sollten alle Attribute nicht mit `attributeGenre * attributePerson` sondern mit `(1+attributeGenre) * attributePerson` berechnet werden. Auch waere gar kein "continue" noetig - denn bei obiger Ueberlegung waere ja auch ein "0 Power" relevant.


Allerdings muss ich sagen, dass vielleicht eine absolute Angabe in den Genres besser waere.
humor 0.8
power 0.2
...
bedeutet dann, dass 80% des "Humorwertes" einer Person zu nutzen sind. mehr als 100% gaenge dann nicht.
Werte von <100% deuten darauf hin, dass es gar nicht unbedingt auf die Attribute einer Person ankommt (keine Ahnung ... bspweise bei "Trickfilmen" - da koennte "appearance 0" sein).


Was denkst Du @nittka ? Relative oder absolute Angabe? Andere Gedankengaenge?

**Comment by nittka** [comment]
Ich wollte zu dem Gesamtthema sowieso noch was zusammenschreiben. Mal schauen, ob ich heute noch dazu komme. Für mich zur Information: willst Du die "Eignung für Aufgabe" für das kommende Release komplett überarbeiten oder erstmal nur "die groben Fehler" beseitigen. Für eine Komplettüberarbeitung scheint mir die Zeit nämlich sehr knapp (Zielbild diskutieren und festlegen, implementieren, testen...)

**Comment by GWRon** [comment]
Ich will es so ueberarbeiten, dass alle Werte in Speicherstaenden verfuegbar sind ... 

Also Formeln kann man spaeter anpassen... 

Dennoch wuerde ich hier und da einiges noch mit fixen wollen.

**Comment by nittka** [comment]
OK. Dann versuche ich, meine Gedanken zu dem Thema baldmöglichst zusammenzuschreiben. Die Grundfragen werden sein:
* welche Entitäten sind in die Berechnung involviert (Genre, Drehbuch, Person)
* welche Eigenschaften hat die jeweilige Entität (welche davon sind initial festgelegt, welche können sich ändern)
* stehen die Eigenschaften für sich (z.B. ist Erfahrung global oder ist sie vom Beruf oder Genre abhängig)
* welche Zufallseinflüsse gibt es zusätzlich

Da das wohl etwas mehr Text sein wird, erstelle ich dafür wahrscheinlich ein md-Datei unter Misc/documentation (ich fände es ohnehin gut, wenn es für bestimmte Konzepte eine Dokumentation gäbe, damit die Grunddeen nicht nur im Code stehen und aufwändig rausgelesen werden müssen)

Ich finde es übrigens gut und richtig, die Persistenzschicht jetzt festzumachen, damit bei der nächsten Änderung nicht gleich wieder die Spielstände inkompatibel werden (ein wenig kann man mit guten Default-Werten wohl abfangen, aber je weniger Änderungen desto sicherer).

**Comment by GWRon** [comment]
Also wir koennten mehrere Vorgehen ausprobieren:

- Wiki vom Repo
- ein neues Repo "TVTower/TVTower-documentation" in dem wir .md-Dateien pflegen koennen und auch per "git" eine Historie bekommen

Ich habe Dich mal ins TVTower-Team eingeladen

**Comment by GWRon** [comment]
Jetzt nochmal ein Gedanke zu den Attributen:

"Absolute Attributanforderungen" haben den Vorteil, dass einfacher von einem Standardwert ausgegangen werden kann:
Keine Angabe? Dann "absolut unwichtig" (oder vielleicht nur mit ... 5-10% belohnt).
Jeder Wert entspricht dem "finalen" Wert, es ist keine "relative Abweichung von einer Unbekannten X"

Klar, auch eine "relative Attributanforderung" koennte man mit "-1.0" (-100%) definieren. Der Vorteil hier ist aber, dass das man nicht wissen muss, wie "wichtig" ein Attribut fuer einen "Beruf" ist - man kann angeben, dass fuer ein Genre Attribut X "wichtiger" ist als fuer andere Genre.

So oder so bedarf es aber wohl "Grundannahmen"/"Basiswerte", was welches Genre an Anforderungen an die jeweiligen Berufe stellt. Dies kann wieder auf Basisannahmen bezueglich der Berufe verstanden werden.

Basisannahmen:
Schauspieler: benoetigen alle Attribute
Regisseure: benoetigen keine "appearance", wenig "power" ..

Genreannahmen:
Schauspieler bei "Liebe" brauchen mehr "appearance"

Das klingt irgendwie, als wenn die Basisannahmen "absolut" sein koennten ... eventuell sogar im Sinne von "0 _oder_ 100%".
Dann muessten aber die Genreannahmen auch absolut erfolgen (oder man erlaubt beides ... in dem man "%" im Wert erlaubt). Nur so waere es moeglich aus einem "0" dann doch noch eine "wird benoetigt" zu machen (0*x = 0...).
Dazu muessten wir aber beispiele haben, in dem ein Attribut eigentlich unwichtig ist, aber eben fuer ein spezielles Genre das Attribut dann doch relevant wird.

Mir faellt jetzt nur "Schauspieler/Nebendarsteller" und "Trickfilm" ein (im Sinne von MotionCapturing, oder "nur Stimme leihen").

**Comment by nittka** [comment]
Muss ich trotz der Einladung für das TVTower-Wiki und TVT-Documentation trotzdem einen Fork erstellen? Direktes Pushen auf diese beiden Repos geht nicht, auch nicht auf einen Branch.

Das Wiki sollte ausreichen. Ich denke eigentlich nicht, dass ein separates Repo nötig ist. Ich habe mit dem Aufschreiben schon mal angefangen (aktueller Stand unter https://github.com/nittka/TVTower/blob/doc/Misc/documentation/AttributeProduktion.md)

**Comment by GWRon** [comment]
Keine Ahnung, hatte noch nie ein "Team" und konnte nur aktuellen Mitgliedern andere Rechte zuweisen.

Wiki ... ist halt "zweischneidig". die Markdown-Dateien liessen sich vielleicht auch bequem exportieren/umwandeln.

**Comment by nittka** [comment]
So. Ich habe mal schnell runtergeschrieben, was mir eingefallen ist (Link im obigen Kommentar). Es ist kein fertiges Datenmodell. Dafür habe ich noch nicht genug Übersicht über den Ist-Stand. Gleiche die Ideen mal mit Deinen ab. Bei Fragen/Unklarheiten können wir die ja auch in der Team-Diskussion fortsetzen, dann ufern die Issues nicht so aus.
