### ISSUE TITLE
Verkaufspreis von Eigenproduktionen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#199]
Im Forum wurde angemerkt, dass sich mit der Produktion von bestimmten Drehbüchern viel Geld verdienen lässt, da der Verkaufspreis deutlich höher liegt als die Produktionskosten.

Ich denke nicht, dass es nötig ist die Berechnung des "Wertes" einer Produktion zu ändern. Wenn der Film toll ist, kann er auch teuer sein. Allerdings sollte der "erste" Verkaufspreis gedeckelt werden (z.B. maximal Produktionskosten + 10 %).

Das wäre analog dem Kauf eines Films mit Reichweitelevel 1 für 50000. In höheren Reichweiteleveln bekommt man auch nur die 50000 zurück. Will man ihn dann aber wieder kaufen, kostet er plötzlich ein Vielfaches.

**Comment by GWRon** [comment]
Eigenproduktionen sind immer "fuer alle Reichweitenlevel" (ausser man verkauft und kauft sie dann spaeter zurueck).

**Comment by nittka** [comment]
Ich konnte zu Spielbeginn einen "Don Ron"-Film für ca 600000 produzieren. Nachdem sich nach Ausstrahlung die Aktualität wieder erholt hatte, war der Film für 6 Mio zu verkaufen.
Mein Vorschlag wäre, bei Produktionsende die Produktionskosten in den Lizenzdaten (extra) zu speichern. Bei der Preisberechnung könnte man diesen Wert dann auslesen und maximal das Doppelte als Preis zurückliefern. Beim Verkauf der Lizenz werden dann die extra-Daten entfernt, so dass beim erneuten Kauf die normale Preisberechnung greift.

**Comment by GWRon** [comment]
Wenn man nur das X-Fache der Produktion reinbekommen kann ("im Bestfall") ... dann wuerde so mancher Film nicht produziert werden ;)

Ich denke es ist wichtiger, die Produktionskosten hochzutreiben (fuer "perfekte" Produktionen, die nicht nur aus "Zufall" perfekt sind - sondern eben von allem "nur das Beste" beinhalten). Gerade bei "teuren" Produktionen muss man bspweise auch mal Flops hinnehmen (Erloes < Kosten).

Auch koennte man den "priceMod" runterschrauben ... sprich man hat zwar einen richtig geilen Film, aber der kostet einfach wenig (und bringt auch im Verkauf wenig).
Hier waere noch ein trigger/event cool (noch nicht umgesetzt): Filme die dieses Event haben (oder halt einfach nur einen Flag) bekommen nach X-Y Ausstrahlungen den "Kult-Flag" (was sich in hoeheren Preisen niederschlagen koennte). Eine guenstige Produktion wird zum Ueberraschungserfolg (nach Ausstrahlung, oder einer - derzeit noch nicht moeglichen - Kinoauswertung).

**Comment by nittka** [comment]
Ich habe eigentlich noch nie was produziert, um Geld mit dem Verkauf zu verdienen sondern immer um mehr Filme/Serien zum Senden zu haben. An den Produktionskosten würde ich nicht zu stark drehen. Wenn sie nämlich zu hoch sind, werden erst recht keine Filme mehr produziert, weil es sich nicht lohnt (Risiko). Die Idee ist ja gerade, dass man "preiswert" an einen guten Film kommt. Ich würde nur verhindern wollen, dass das Prodzieren einem einfach schnelles Geld verschaffen kann.

**Comment by nittka** [comment]
Ich glaube, kritisch sind insb. die Drehbuchvorlagen mit guter Qualität und hohem Potential. Mit Glück ist Don Ron schon früh in der Drehbuchagentur. So produziert, dass der Film kurz nach Mitternacht fertig ist, kann man ihn sofort senden (Nachtprogramm) und dann noch unmittelbar mit hohem Gewinn verkaufen. Da die Produktionskosten auch bezahlt werden, wenn man das Geld eigentlich nicht hat, sind nur um 170000 an flüssigen Mitteln nötig (Drehbuch+Anzahlung), die für das Startprogramm etc. fehlen, um sofort 1Mio Gewinn zu machen.

Bei Drehbüchern mittlerer Qualität klappt das nicht, da die Produktionskosten genauso hoch sind, aber der Lizenzpreis nicht in diese Bereiche kommt. D.h. eine Option, diese Anfangsschummelmöglichkeit zu verhindern wäre auch, bei diesen Drehbücher ein Studio mit Größe 2 oder 3 zu verlangen.

**Comment by GWRon** [comment]
Ja eine bestimmte Studiogröße zu fordern ist eine gute Idee.
