### ISSUE TITLE
Compile-Error

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#200]
Compile Error: Identifier 'getgroupkey' not found.
...TVTower/source/game.production.script.bmx;1097;0

Ich habe noch nicht weiter analysiert.

**Comment by GWRon** [comment]
Hatte wohl doch eine kleine Aenderung zuviel schon mit hochgeladen.

**Comment by nittka** [comment]
Kann es sein, dass Du vergessen hast, game.misc.xpcontainer.bmx zu pushen?

**Comment by GWRon** [comment]
Ja... ic hatte nur die "zuletzt geaenderten" committed - und DEV.xml lag knapp ueber der "untracked", da ist die ausversehen mit untergegangen.
