### ISSUE TITLE
Hover Senderinfo

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#202]
In der Finanzübersicht beim Hovern über den Senderinfos werden aktuell die darunterliegenden Zahlen nicht richtig weggeblendet.
![finanzen](https://user-images.githubusercontent.com/2562651/100548911-11b91400-3270-11eb-9c22-8a95319858d7.jpg)

**Comment by GWRon** [comment]
Stimmt... weil die Grafik ja nun transparent ist
