### ISSUE TITLE
Amateurnamen im Klartext

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#205]
Wenn man eine Produktion mit Amateuren plant, werden deren Namen im Studio schon vor Produktionsbeginn im Klartext angezeigt. Ich habe kein Problem damit, habe micht nur gewundert, da im Supermarkt je extra kein Klartextname angezeigt wird.

Auch habe ich micht über das hohe Potenzial gewundert. Selbst der Studioleiter sagt, dass alle Aspekte der Planung unterirdisch sind.
![klartextnamen](https://user-images.githubusercontent.com/2562651/100645118-878ab180-333c-11eb-8655-77ebf6829187.jpg)

**Comment by nittka** [comment]
game.production.productionconcept.gui.bmx Zeile 333 rendert als Potenzial immer die Konstant 1?!

**Comment by GWRon** [comment]
Sollte da, solange "isAmateur" "besteht", der Name ausgeblendet / ersetzt werden?

Das waere einfacher, als noch fuer jedes Konzept abzuspeichern "ob" eine Rolle zu dem Zeitpunkt von einem Amateur besetzt wurde.

**Comment by GWRon** [comment]
zwecks Potential (jaa... Potenzial und Potential ist korrekt):
Wir haben ja beim "Konzept" schon die Leute - und somit nicht nur das im Drehbuch liegende Potential, sondern den "Mod".

script.GetPotential() -> das "unerkannte Vermoegen" eines Drehbuchs durch gute Besetzung besser zu werden
scriptPotentialMod - der "Faktor" um den sich Produktattribute (Tempo, Kritik, ...) durch gute Besetzung verbessert.

der "mod" ist derzeit aber nicht wirklich mit einem "schoenen" Limit versehen.

```
			local castXP:Float = THelper.LogisticalInfluence_Euler(Min(1.0, 0.1 * jobsDone), 2.5)
			castXP :* 1.0 + 0.15 * person.GetEffectiveJobExperiencePercentage(job.job)


			scriptPotentialMod = 1.0 + (castXPSum / personCount) * script.GetPotential()
```
Wir haben also fuer jeden auf der Besetzungsliste "castXP" die bis zu 1,15 erreichen koennen. Entsprechend kann der "mod" bis zu 1,15*Scriptpotential sein.

Vielleicht sollten wir statt "x/1,15" die 1,15 auf 1 limitieren (castXP auf 1 normalisieren) ?

**Comment by nittka** [comment]
Zu Potenzial - ich hatte es nur so geschrieben, weil es im Screenshot so steht.
Zu den Namen - ich fände ausblenden/ersetzen gut. Konsistent wäre, die Amateurberufsbezeichnung aus dem Supermarkt zu verwenden.
Zum Potentialbalken - vielleicht tut es im Moment auch nicht weh, den Balken erstmal wegzulassen, bis die Berechnungslogik klar ist. Die obigen Formeln sehen so aus, als ob scriptPotentialMod immer größer als 1 wäre, es sollte doch aber nur von 0 bis 1 gehen können, oder? Auch sieht es so aus, als gäbe es nur "Verbesserungen" durch die Besetzung, oder ist das nur der Ausschnitt für den Erfahrungsteil? Im Moment bin ich noch nicht gut genug informiert, um Deine Frage fundiert zu beantworten.

**Comment by GWRon** [comment]
Der Mod ist derzeit immer groesser 1.0 (also 1.15 ist 15% oben drauf).

Man koennte nun den Wert aber auch so ansetzen, dass wirklich miese Werte es sogar verschlechtern.

Also 0.9 + 0.2*xpModWert.

Durch die logistische Funktion erreicht man zuegig 1.0-1.05.



Amateur... Es war ja die Frage, ob es Nnot tut, noch Amateur-XYZ hinzuschreiben, obwohl die Person vlt mittlerweile kein Amateur mehr ist (aber bei Planungsabschluss noch war)?

Ich denke hier koennen wir einfach "isAmateur" auswerten.

**Comment by nittka** [comment]
Ja, isAmateur auswerten.
Ich fände ein mögliches Verschlechtern jedenfalls realistisch (obwohl das natürlich nicht ausschließlich von der Erfahrung abhängt).

**Comment by GWRon** [comment]
![amateur](https://user-images.githubusercontent.com/2625226/101413986-91388a00-38e5-11eb-945d-d03458a38d80.png)

**Comment by GWRon** [comment]
Bleibt "Potential" und "xpMod" offen.

**Comment by GWRon** [comment]
Wollen wir lieber fuer "potential" und "xpmod" einen eigenen Issue aufmachen?

**Comment by nittka** [comment]
Dafür.
