### ISSUE TITLE
Lokalisierung Namen Datenbank

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#216]
Für die Werbung ist zum Teil nur ein deutscher Name vorhanden. Das führt dazu, dass bei anderen Sprachen kein Titel angezeigt wird. In der Werbeagentur ist das noch nicht so schlimm, da man im Datenblatt die relevante Information sieht, aber bei der Auswahlliste in der Programmplanung stehen dann einfach keine Namen.

Dasselbe Problem besteht bei Filmen, die nur deutsche Titel/Beschreibung haben.

**Comment by GWRon** [comment]
War das vorher schon so? Deutsch war eigentlich als Fallback drin.

**Comment by nittka** [comment]
Das kann ich nicht genau sagen. Ist die Fallback-Sprache fest definiert oder hängt es davon ab, was beim letzten Spielstart eingestellt wurde.
Ich war implizit davon ausgegangen, dass Englisch die Fallback-Sprache ist. (Zumindest für alle anderen Sprachen als Englisch und Deutsch fände ich das plausibel, da es wahrscheinlicher ist, dass der Spieler dann eher Englisch als Deutsch versteht.)
Ggf. sollte man die Fallback-Sprache in den Settings definieren können.

**Comment by GWRon** [comment]
OK, war im August schon so ... also kein Regressionbug

**Comment by GWRon** [comment]
Hmm ... scheint so, als wenn ich dieses Vorgehen mal rausgehauen hatte (schon vor langer langer Zeit).

Also der Grundgedanke ist:
- definiere die aktuell genutzte Sprache ("Franzoesisch" - der Spieler spricht Franzoesisch)
- definiere eine Standardsprache ("Englisch" - viele koennen Englisch")
- definiere die Originalsprache ("Deutsch" - jeder Text ist in deutsch vorhanden)

Oder... wir machen es uns einfach und uebersetzen jeden Inhalt auch auf Englisch (was viel Arbeit ist - vor allem bei den Datenbanken ist noch einiges "nur deutsch")

**Comment by nittka** [comment]
Die Dreiteilung erscheint auch sehr aufwändig (doppelter Fallback?). Ich denke, die Definition der Standardsprache reicht vielleicht aus. Anfangs wird diese standardmäßig auf Deutsch gesetzt. Im besten Fall gibt es Unterstützung bei der Lokalisierung - auch für Englisch. Wenn Englisch dann vergleichsweise vollständig ist, kann Englisch die Standardsprache werden.

**Comment by GWRon** [comment]
OK ... nun nehmen wir mal an, jemand erstellt eine "user DB" mit nur franzoesischen und italienischen Titeln (wir koennen kein "englisch" erzwingen, solange wir selbst nicht alles 100% auch in englisch anbieten).

Der wuerde bei einem deutschen oder englischen Nutzer nix anzeigen (selbst wenn der Titel "Parfume: Le Parisean" waere).

Was haeltst Du von dem Gedanken:
- ist ein Key eines "TLocalizedString" nicht vorhanden (weder "current" noch "default"), wird der erstmoegliche genutzt (also hier franzoesisch oder italienisch)

**Comment by nittka** [comment]
Klingt vernünftig.

**Comment by GWRon** [comment]
So war es frueher auch angedacht - deswegen habe ich "Eigennamen" nicht wirklich nochmal lokalisiert gehabt: da reichte "ein" Eintrag.


Ein "Fallback" waere dennoch nicht all zu schwer zu integrieren ... man koennte hier sogar einen "array" nutzen. Also statt einer "default", legt man sowas fest wie "[englisch, deutsch, ...]" und die werden der reihe nach durchprobiert - und am Ende, falls nix gefunden, "der erste Eintrag" genutzt

**Comment by GWRon** [comment]
Das ist aber nur dann relevant, wenn bspweise der "deutsche" Titel auch im Englischen, Franzoesischen ... OK waere ---- und dann jemand "vor" dem deutschen Eintrag, noch einen voellig abweichenden hollaendischen/norwegischen/.... Eintrag hinzufuegt (der dann ja "Notfall-default" fuer alle anderen Sprachen wuerde)

**Comment by nittka** [comment]
Diesen Fall für die Datenbanken muss man beim Prüfen der Pull-Requests abfangen.

**Comment by GWRon** [comment]
Dann halten wir es einfach

alt:
```BlitzMax
			if not result and returnDefault
				local defaultIndex:Int = GetLanguageIndex(TLocalization.defaultLanguageID)
				if defaultIndex >= 0 and defaultIndex <= valueStrings.length
					result = valueStrings[defaultIndex]
				endif
			endif
```

neu
```BlitzMax
			if not result and returnDefault
				local defaultIndex:Int = GetLanguageIndex(TLocalization.defaultLanguageID)
				if defaultIndex >= 0 and defaultIndex <= valueStrings.length
					result = valueStrings[defaultIndex]
				'also default not found? return first available if possible
				elseif valueStrings.length > 0
					result = valueStrings[0]
				endif
			endif
```

**Comment by GWRon** [comment]
Wenn hier also ein "leerer" Wert hinterlegt wird, wuerde der akzeptiert werden.
Andernfalls muesste man aus dem "elseif" ein "if not result and valuesStrings.length > 0" machen ...
