### ISSUE TITLE
Ausstrahlungsqualität Satellit

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#221]
In meinem aktuellen Testspiel hat einer der Satelliten eine Ausstrahlungsqualität von 110%. Ich gehe mal davon aus, dass hier 100 eigentlich der Maximalwert sein soll.

**Comment by GWRon** [comment]
Es ist nicht direkt ein Fehler.

Satelliten starten mit "95 - 110%" ... dann gibt es ab und zu Techupgrades usw. 
Wenn dann die neuen "Verteilungsquoten" (Anteil der Bevoelkerung die Satellit X benutzt) berechnet werden, wird zwischen 0 und 100% begrenzt.

Vielleicht sollten wir einfach die 95-110 auf 85-100 setzen?

**Comment by nittka** [comment]
Wenn es ausschließlich um das Vergleichen der Satelliten geht und der Wert später dann zwischen 0 und 100 liegt, wäre ich für das Runterschrauben der Initialwerte.
