### ISSUE TITLE
Error-Meldungen beim Testspielen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#223]
Im aktuellen Testspiel bekomme ich im Log folgende Fehlermeldungen
```
ERR      | TLUAENGINE: [Engine 1] Object TStationCableNetworkUplink does not expose field "providerGUID". Access Failed.
ERR      |           : [Engine 1] Object TStationSatelliteUplink does not expose field "providerGUID". Access Failed.
```

**Comment by GWRon** [comment]
Entweder muss die KI angepasst werden (GUID -> ID) oder die GUID muss freigegeben werden.

**Comment by GWRon** [comment]
Kannst Du bitte zumachen, falls der fix https://github.com/TVTower/TVTower/commit/75c1fc830f78a5512f97cd8b0c5b81edc31e45c7

ausreichend ist?

**Comment by nittka** [comment]
Die obigen Fehler tauchen nicht mehr auf. Beim Schnellvorlauf ist noch folgender gekommen
```
[07:48:50] ERR      | TGAMEMODIFIERPOPULARITY_MODIFYPOPULARITY: cannot find popularity to trigger: ID=1248  referenceGUID=""   referenceID=0
[07:48:50] ERR      |                                         : cannot find popularity to trigger: ID=1248  referenceGUID=""   referenceID=0
[07:48:50] ERR      |                                         : cannot find popularity to trigger: ID=1053  referenceGUID=""   referenceID=0
```

Ich habe mal im gespeicherten Spielstand nachgeschaut. Es handelt sich bei 1248 um eine Person.
```
---Start des Personen-Eintrags
            <e index="1248">
              <TPersonBase id="1GJ4OTC">
                <field name="id" type="int">1248</field>
                <field name="GUID" type="String">
                  <String id="1KOUPMO">TheRob-celebritypeople-WeinWenk</String>
                </field>

---Start des Popularity-Eintrags
            <e index="122">
              <TPersonPopularity id="1EY4GF4">
                <field name="ID" type="int">122</field>
                <field name="referenceID" type="int">1248</field>
                <field name="referenceGUID" type="String" />
                <field name="longTermPopularity" type="float">-2.66518998</field>
```
Kann es sein, dass hier bei der Suche auch die ID gegen die referenceID abgeglichen werden sollte?

**Comment by GWRon** [comment]
Ich denke da fehlt noch eine Anpassung an ID statt GUID. Beim Spielstart gibt es ein paar aehnliche Meldungen ueber IDs

**Comment by GWRon** [comment]
Der Modifier ruft die falschen IDs ab ... das ist das eine.

Derzeit wird die Popularitaet der Personen nur mit der "ID" als Referenz angelegt. Es braucht aber noch die GUID-Referenz ...


Alternativ braeuchte es eine GUID->ID-Map mit der bei angegebenen GUID die aktuell genutzte ID genutzt werden kann. Das gaenge aber nur, wenn die "Aufloesung" der GUID nach dem Erstellen des "zur GUID gehoerigen Objektes" geschieht. Also der "effect" einer News erst initialisiert wuerde, wenn die dazugehoerige Person schon existiert.
