### ISSUE TITLE
Zeitpunkt Kosten Vorproduktion

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#224]
In der Nachricht für fertiggestellte Filme stehen nun die Gesamtkosten. Für Vorproduktionen (Shows?) werden diese Kosten noch nicht in die Nachricht geschrieben.

**Comment by GWRon** [comment]
Du meinst "Du hast eine Anzahlung von XXX geleistet und beglichen" ?

https://github.com/TVTower/TVTower/issues/144

**Comment by GWRon** [comment]
Fuer Vorproduktionen ergibt eine solche Meldung keinen Sinn - man bezahlt ja bei Planungsabschluss die Vorproduktion. Und wenn diese Vorproduktion abgeschlossen ist, entstehen erstmal noch keine weiteren Kosten. Die entstehen ja erst bei Ausstrahlung.

**Comment by nittka** [comment]
Ich konnte mit dem Begriff Vorproduktionen bisher noch nichts anfangen. Die Erklärung hilft schon.

Wie bei den Filmen fehlt mir aktuell noch die Möglichkeit zu überprüfen, ob sich die Produktion nun gelohnt hat. Wenn es keine Stelle gibt, an der ich die Gesamtkosten ablesen kann, weiß ich auch nicht, ob ich die Show nochmal produzieren möchte.

**Comment by GWRon** [comment]
Der Finanzbildschirm sollte es zumindest "grob" anzeigen.

Generell wollte ich im Statistikbildschirm noch Unterpunkte (ein paar gibt es ja schon) einbringen - unter anderem eine Liste mit bisherigen Produktionen (und Kosten, etc - also einer kleinen "Auswertung")

**Comment by nittka** [comment]
OK. Dann lassen wir das für später. Eine zusätzliche Nachricht für die Ausstrahlung ist zunächst nicht nötig.

**Comment by nittka** [comment]
Ich habe es gerade nochmal ausprobiert. Auch bei einer Live-Produktion werden die Gesamtkosten bereits bei (Vor-)Produktionsende abgezogen (und sie sind in der Finanzübersicht im Büro erkennbar). Im Datenblatt steht aber noch ??

D.h. mit dem aktuellen Implementierungsstand könnte man auch hier die schon existierende Nachricht um die Gesamtkosten erweitern.

In der Filmagentur kann man eine Live-Produktion korrekterweise nicht aus dem Koffer nehmen (aber es wird kein Verboten-Mauszeiger verwendet).

**Comment by nittka** [comment]
... Da die Gesamtproduktionskosten ja schon beim Abschluss feststehen, ist die "Geheimniskrämerei" um den Preis für Live-Produktionen unnötig (?? im Datenblatt). Für Filme/Serien kann der Preis ja erheblich von den Kosten abweichen.

Vorschlag: Bei Live-Produktionen kommen die Gesamtkosten auch in die Nachricht.

**Comment by GWRon** [comment]
Ich hab den PR gesehen - und an sich ist der auch gut. Nur sollten wir im Hinterkopf behalten, dass "Live"-Produktionen anders behandelt werden sollten.

Derzeit wird "production.Finalize()" aufgerufen um die Programmlizenz etc verfuegbar zu machen.
Und "Finalize()" ruft momentan "PayProduction()" auf.

Fuer Live-Programme muesste es eigentlich so ablaufen:
- Finalize() (damit ausstrahlbar)
- wenn live:
  - PayProduction() NICHT ausfuehren
  - Programmlizenz / Programmedata bei Erstausstrahlung: Produktion abrufen und "PayProduction()" ausfuehren

Damit wuerde nur die Vorproduktion bezahlt werden muessen - sobald man sich aber entscheidet, die Sendung auszustrahlen, kommen die "restlichen" Kosten ...

**Comment by nittka** [comment]
Sollte dann stattdessen die Behandlung der Live-Produktionen korrigiert werden?

**Comment by GWRon** [comment]
Ja -- ich denke das waere zielfuehrender.

Also nochmal: Der Grundgedanke ist, dass eine Live-Produktion natuerlich in der Vorbereitung Geld kostet -- "Welche Spiele werden gespielt, welche Farbe haben die Vorhaenge..."
Die Produktion der Show findet aber ja erst "live" statt ... also erst dann wird die Produktionsfirma "gefordert" (Leute stehen da und halten Kabel) und die Aktionen der Besetzung sind sichtbar ("Popularitaet", "Skills").

Entsprechend muessen wir "Verfuegbarmachen der Programmdaten/lizenzen/..." von "Auswertung der Produktion fuer Produktionsfirma, Personen, ... und Geld" trennen.

**Comment by GWRon** [comment]
Eventuell sollte "FinishProduction" ja weiterhin "FinishProduction" heissen  -aber die ganze ProgrammeData/Licence/...-Erstellung sollte in eine extra Methode wandern - die bei allen Produktionen ausgefuehrt wird, bei "normalen" kommt noch "FinishProduction" hinzu. Bei "Live" kommt "FinishProduction" erst bei Erstausstrahlung dran.

**Comment by nittka** [comment]
Da wir an anderer Stelle das Thema Kosten hatten (was muss man zahlen, wenn die angepeilte Sendezeit für eine Show abgelaufen ist). Ausgehend von der Prämisse, dass man ohnehin die gesamten Kosten zahlen muss, könnten diese auch schon zum Ende der Vorproduktion fällig werden. Das würde die Sache einfacher machen.

Wenn die Prämisse nicht stimmt, kann es noch komplizierter (gemacht) werden. Denn wenn die Sendezeit überschritten ist, könnte man argumentieren, dass den Beteiligten mehr gezahlt werden muss, schließlich mussten Sie sich länger bereit halten, als ursprünglich geplant.

Ich wäre für die einfache Variante: Gesamtkosten werden bei Abschluss der Vorproduktion fällig.

**Comment by GWRon** [comment]
Der Grundgedanke war  sozusagen eine "Anzahlung" zu leisten.
Wenn die Leistung nicht abgerufen wird, fallen dann keine 100% an. 

Diese "auf Abruf bereitstehen"-Sache...hmm machts halt kompliziert.

**Comment by nittka** [comment]
Meine Zusammenfassung des aktuellen Diskussionsstands (auch in Kombination mit #302):
* Bei Filmen/Serien wird beim Abschluss der Konzeption (Supermarkt) eine Anzahlung fällig und sofort bei Abschluss der Produktion (Studio) der Restbetrag. Bei Abschluss der Produktion wird der Spieler in einer Nachricht auch über die Gesamtkosten informiert.
* Bei Live-Produktionen ist ebenfalls bei der Konzeption eine Anzahlung fällig, die restlichen Kosten fallen aber nicht nach Abschluss der Vorproduktion (Studio) an, sondern erst bei der ersten Ausstrahlung. Hier wird der Spieler aber noch nicht per Nachricht über die Gesamtkosten informiert.
* Eine Frage war, ob das "Bereithalten" für die Live-Ausstrahlung zusätzliche Kosten verursachen sollte (die Vorproduktion allein soll ja noch nicht dazu führen, dass die Restkosten fällig werden). Oder aber dass Zusatzkosten anfallen könnten, wenn die Erstausstrahlung erst nach dem geplanten Live-Termin stattfindet - in diesem Fall hätten sich Produktionsfirma und Beteiligte länger als gedacht bereithalten müssen. Der Einfachheit halber wird dieser Ansatz nicht weiterverfolgt.

TODO ist also weiter die Prüfung, dass bei Live-Produktionen der Restbetrag zum Ausstrahlungszeitpung (d.h. dem Zeitpunkt der eigentlichen Produktion) fällig wird und der Spieler zu diesem Zeitpunkt auch per Nachricht über die Gesamtkosten informiert wird.

**Comment by GWRon** [comment]
OK ... also sollte Liveprogramm zum spaetesten Livezeitpunkt die finalen Kosten verursachen?

Beispiel:
Fruehstuecksfernsehen mit 3 Bloecken, Zeitrahmen 5 - 9 Uhr. Also Start 5 oder 6 Uhr -> spaetestens um 6 Uhr wird "abgerechnet" ?

**Comment by nittka** [comment]
Die genauen Zeitpunkte müsste man sich nichmal überlegen, aber ja. Live-Produktionen werden zum "geplanten Ausstrahlungszeitraum" produziert, egal ob sie dort unmittelbar gesendet werden, oder nicht. Sie blockieren dann auch das Studio (siehe #308) - im einfachsten Fall das Studio, in dem die Vorproduktion stattfand. Falls dort gerade etwas produziert wird, verlängert sich diese Produktion entsprechend.

Ob die Zahlung nach dem ersten Block oder nach der nach dem letzten möglichen Block (oder nach Abschluss der Ausstrahlung falls sie stattfindet) fällig ist, wäre zu diskutieren. Eine Option wäre auch direkt um 5 Uhr im obigen Beispiel. Schließlich können Filme ja auch erst ausgestrahlt werden, wenn sie bezahlt sind.

**Comment by GWRon** [comment]
Hmm also nicht zum letzten Live-Zeitpunkt sondern zu Beginn des Erstmoeglichen?

**Comment by nittka** [comment]
Mir ist es eigentlich egal. Es muss nur festgelegt werden. Ich hatte "spätestens 6 Uhr" erst falsch verstanden - das wäre der späteste Beginn der Ausstrahlung; auch plausibel. Von der Implementierung einfacher wäre es ggf. wenn die Produktion komplett unabhängig von der Ausstrahlung behandelt wird. Deshalb meinte ich Studio von 5-9 Uhr blockieren und 5 Uhr die Zahlung anstoßen, egal ob dann 5 Uhr, 6 Uhr oder gar nicht live gesendet wird.

**Comment by GWRon** [comment]
Ist zwar eine an sich "vom issue abweichende" Diskussion, aber ist ja nicht so schlimm:

wuerdest Du generell von 5-9 Uhr blockieren ("Bereitschaft")? Oder nur von 5 bis 8 (5 Uhr gestartet) bzw 5 bis 9 (wenn 6 Uhr gestartet?

Was ist mit Programmen, die jederzeit "Live" sind? Keine Restriktionen = zum Zeitpunkt der Ausstrahlung
Was ist mit Programmen, die bspweise 1 Block sind, und von 18-24 Uhr live sein koennten? ("TED am Abend"), waere ja bloed, dort 18-24 Uhr zu blockieren.

Entsprechend waere ein an die Ausstrahlung gekoppeltes Blockieren wohl vorzuziehen. Man koennte auch darueber nachdenken, dass andere Produktionen (wenn nicht auch "live") im Studio unterbrochen wuerden - vielleicht sogar noch mit Zeitaufschlag ("Umbauarbeiten").

Also Produktion X von 18-6 Uhr. 20 Uhr kommt eine 2-Block-Liveproduktion rein.  X wird 20:05 Uhr Unterbrochen und 21:55 weiter fortgefuehrt. Die Verzoegerung ist 110 Min fuer die Liveproduktion und 60, 90, 120 ... (studiogroessenabhaengig?) fuer die Umraeumarbeiten. Bei 110+120 wird also die Produktion nicht mehr 6 Uhr sondern knapp 10 Uhr fertig.

Gern kann dies auch per "Toastmessage" bekanntgegeben werden ("Produktion verzögert sich um X")

**Comment by nittka** [comment]
Programme ohne Restriktion des Ausstrahlungstages sind tatsächlich ein Problem... Mindestens hier ist eine Kopplung an die Ausstrahlung also nötig. Die Idee hinter der "Bereitschaftsblockade" - also Produktionszeit entspricht der gesamten mögliche Ausstrahlungszeit  und nicht nur der Anzahl der Blöcke - war genau der Umbauzeitaufschlag.
Wenn gerade keine andere Produktion läuft, ist das Studio blockiert, ansonsten verlängert sich die laufende Produktion.

Greifst Du hier in die Tasten?

**Comment by GWRon** [comment]
Ich baue gerade die Vorproduktion um ... also eigentlich eher die Finalisierung. Aufsplitten von "Programm/Lizenz"-Erzeugung und "Produktionsauswirkungen" (XP, Kosten...).

Die Produktionszeitauswirkungen sind davon erstmal unbetroffen - kann das aber auch uebernehmen (Falls Du da nicht schon was angefangen hast).

**Comment by nittka** [comment]
Nein, ich habe in der Richtung noch nichts gemacht.

**Comment by GWRon** [comment]
OK, dann versuch ich mir das mal auf die Agenda zu schreiben.

**Comment by GWRon** [comment]
Hmm ... also ich habe das jetzt zwar aufgesplittet ... aber da gibt es generell noch ein paar Dinge.

Liveprogramm sollte die noch anfallenden Kosten im Datenblatt erwähnen.

Wenn etwas vorproduziert ist und bspweise wie die Morgenstunden "jeden Tag 5-9" gesendet werden kann (also keinen fixen Live-Zeitpunkt hat), dann kann ich erst zum Zeitpunkt der Ausstrahlung die Kosten anfallen lassen.
Hat es einen fixen Zeitpunkt ("nächsten Dienstag 20 Uhr"), kann ich die Kosten fuer diesen Zeitpunkt festlegen.

**Comment by nittka** [comment]
Müssen die noch anfallenden Kosten wirklich ins Datenblatt? Wie wäre es, sie stattdessen in der Toasmessage zum Abschluss der Vorproduktion zu nennen? Bei einer Filmproduktion erfährt man ja die Kosten auch erst nach Fertígstellung.

Das Anfallenlassen der Kosten hat doch schon etwas mit der Produktion und damit mit dem Blockieren des Studios zu tun, oder?

**Comment by GWRon** [comment]
Also an sich hab ich dafuer schon einiges umgeschrieben  -aber ich denke ich fang das nochmal "anders/neu" an.

Der Plan ist nun, `TProduction` zu erweitern - als dort die optionale PreProduction direkt zu integrieren (derzweit hab ich das wie "aufgepfropft".
Statt wie im aktuellen lokalen Dev-Stand nur den Beginn und Ende von Produktionen (hier live...) zu ueberwachen, werden Produktionen auch "mittendrin" (inProduction-Liste) informiert (jeweils ueber ihre Update()). Dann koennen Produktionen selbst fuer Verzoegerungen sorgen ("Regisseur hat sich in den Finger geschnitten - Assistenten auf der Suche nach Pflaster mit bunten Motiven").

Momentan wirkt mir mein Code halt noch zu "aufgestöpselt", statt richtig integriert.

**Comment by GWRon** [comment]
Weiterhin habe ich ueberlegt, dass die Produktionskosten vielleicht doch schon in der Vorproduktion faellig werden.

Damit erspart man sich die notwendige Anzeige im Programmdatenblatt ("Diese Ausstrahlung verursacht einmalig Kosten i.H.v XXXXXX Euro").

Dennoch waere nach aktueller Planung die "Auswertung" von der Vorproduktion losgeloest. Das heisst, es kann sein, dass man bei Vertragsunterzeichnung einen "Amateur" reinholt (fuer guenstiges Geld). Die Vorproduktion abschliesst - und dann zwei Filme mit eben diesem "Amateur" zwischenschiebt (bzw die Produzenten oder die KI machen das) - und aus dem Amateur wird ein "Promi" (mit vlt richtig passenden Werten). Bei Live-Produktion hat man dann nun bessere Werte (oder schlechtere :)) als wenn diese schon in der Vorproduktion berechnet wuerden.

Kurzgesagt: Bezahlen / Werteberechnung / Programmplanbarkeit (Element in Planer-Liste) werden gesplittet - und bei LiveProduktion anders angesetzt als bei einer normalen.

**Comment by nittka** [comment]
Fixed by #345
