### ISSUE TITLE
Textblock-Rendering: Probleme mit manual_de.md

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#229]
Wenn man die Spielanleitung im Spiel anzeigen laesst, sieht es auf den ersten Block alles "in Ordnung" aus.

Aber irgendwie werden die letzten drei Zeilen nicht angezeigt:
```
Debugausgaben
--------------
* Alt Links + M: Debugmodifieransicht an/aus
* Q: Quoten-Debugbildschirm an/aus
* Shift Rechts + F: Finanzuebersicht aller Tage (auch nach „log.financeoverview.txt“)
* Shift Links + F: Finanzuebersicht aktueller Tag
* Shift + W: Uebersicht Werbevertraege in DB
```
Nach der Zeile mit "Q" ist Schluss.

Nehme ich aber die .txt-Datei, zeigt es alles komplett an. Ich vermute, dass meine Text-Block-Algorithmen irgendwo "durcheinander" kommen. Fuege ich kuenstlich 
```
1
2
3
```
untenran, dann zeigt es obige 3 Zeilen an, und die 1-2-3 fehlen.

**Comment by GWRon** [comment]
also es ist nicht direkt das Textrendering - bleibt noch der Cache-Algorithmus oder das ingame-widget.

Interessant ist ... dass das Softwarerendering ("textcache") langsamer ist, als einfach stupides neurendern der _kompletten_ textbox.
Wenn Render2Texture endlich "offiziell" in die Blitzmax-NG-Module wandert, waere das aber eh schnell umgestellt.

**Comment by nittka** [comment]
Bei mir bricht seltsamerweise in den Vorbemerkugnen eine Zeile auch mitten im Wort um ("diskutie-rt mit uns"). Ich habe es nicht intensiv geprüft, aber beim Überfliegen ist mir nochmal aufgefallen. Wenn es ein systematischer Fehler wäre, sollte es doch häufiger passieren, oder?

**Comment by GWRon** [comment]
Mitten im Wort sollte es nur umbrechen, wenn das Wort selbst breiter als eine Zeilenbreite ist.

Merkwuerdig.

**Comment by GWRon** [comment]
Ok ... den Zeilenumbruch konnte ich nachstellen - und nachdem ich die problematische Stelle aufgespuert hatte, ist der Fix relativ einfach ausgefallen. Zeile "12" war hier relevant ... da ich fuer 10 Zeilen "statisch" Informationen abspeichere und der Rest in dynamische Arrays gepackt wurde. Zeile 12 .. ist index 11. Und die vorherige Zeile ("ist letzter moeglicher Zeilenumbruch erst in der vorherigen Zeile?"). Landeten wir bei index 10 ... baemm.

Ok ... nun nur noch rausfinden wieso ein
"ZeichneTextBlock(text, maxBreite=509)" zwar "nutze nur 507*11110 pixel) zurueckliefert, aber dann ein
"ZeichneTextBlock(text, maxBreite=507)" anders umbricht.

Das sorgt naemlich fuer die fehlenden Zeilen in der Anleitung. Das kann ich zwar temporaer fixen, in dem einfach nicht die "wirklich genutzte Breite" uebergeben wird, sondern die initial verfuegbare (also 509 statt 507) aber hey... wir wollen das doch "richtig" fixen.
