### ISSUE TITLE
Tooltip-Aktivierung Karte

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#235]
Auf der Senderkarte kann man zwischen Sendemasten, Kabel- und Satellitenanbindung wählen. Bei allen werden bei einem selektierten Eintrag Statusinformationen (Reichweite etc) angezeigt. Diese Felder haben Tooltips.
Tatsächlich werden aber nicht nur die Tooltips der aktuellen Selektion angezeigt, sondern alle initialisierten.

* Sendemast selektieren, mal über alle Tooltips fahren
* Kabelanbindung selektieren, langsam über die Felder fahren - es werden z.T. 2 Tooltips angezeigt
* Satelliten anbindung selektieren, bis zu drei Tooltips

Beim Wechseln des "SenderTyps" sollten adie alten Tooltips deaktiviert werden.

P.S.: Einen ähnlichen Effekt hat man, wenn man die Hilfe aufmacht. Die dahinter liegenden Elemente scheinen noch auf MouseOver zu reagieren.

**Comment by GWRon** [comment]
Entweder wir machen es einfach - und rendern/aktualisieren die tooltips nur noch, wenn die entsprechenden Panels (vom "Akkordeon") auf sind (dann blenden sie aber nicht sanft aus, sollte man zuegig von "tooltip" zu "anderes Panel aufklappen" wechseln koennen).

Oder wir unterbinden die Reaktion aufs "Hovern", wenn ein Panel zu ist ...
