### ISSUE TITLE
Titel editieren bei mehreren Live-Produktionen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#238]
Für Live-Produktionen mit mehreren Folgen ist das Editieren des Titels verwirrend. Name und Beschreibung werden nur für die gerade selektierte übernommen. Wenn man dann aber bei der zweiten den Editier-Button anklickt, steht schon der geänderte Titel drin. (Beispiel `/dev givescript 1 morningshow 0` mit 4 Folgen).

**Comment by GWRon** [comment]
Der Fehler ist also, dass der "custom title" schon gesetzt ist - aber erst angezeigt wird, wenn man auf "Bearbeiten" geklickt haben sollte?

**Comment by nittka** [comment]
Das hängt auch vom gewünschten Verhalten ab. Sollen beim Bearbeiten einer Produktion alle "Folgen" der Live-Produktion umbenannt werden? Oder sollte das eher wie eine Serie modelliert sein - Haupttitel und Beschreibung der Show, jede Ausstrahlung hat aber ihr eigenes Thema? In dem Fall sollte es dann auch subScripts geben. Beide Varianten wären plausibel.

Aber falls es keine separaten Skripte für die Einzelausstrahlungen gibt, dann ist der Fehler tatsächlich, dass der Name und die Beschreibung nicht für alle verwendet wird.

**Comment by nittka** [comment]
Kann es sein, dass das Problem genau darin besteht, dass es in diesem Fall nur ein Skript für alle Produktionen gibt? Beim Öffnen des Edit-Dialogs werden nämlich nicht Titel und Beschreibung aus dem Konzept, sondern aus dem Skript verwendet. Solange da eine 1:1-Beziehung besteht, ist das kein Problem. Hier wird es eins.
Das Ändern des Titels im Skript sollte eigentlich nur für den Serientitel und die Serienbeschreibung nötig sein - damit alle Folgen denselben Serientitel bekommen. Ansonsten müsste es reichen, Custom-Titel und Custom-Beschreibung im Konzept selbst zu verwenden.

**Comment by GWRon** [comment]
Denke Du hast es absolut korrekt subsumiert. 

Also, dass fuer Filme etc nur der customTitle gesetzt werden braucht, nicht direkt die Drehbuchtitel und -beschreibung veraendert werden muessen.


Willst Du dich gleich daran versuchen?

**Comment by nittka** [comment]
Nur den Custom-Title für die Einkaufsliset zu setzen würde für Mehrfachshows nicht mehr erlauben, den Titel sämtlicher Folgen zu modifizieren (siehe Beschreibung PR). Ich denke, die aktuelle Lösung ist zunächst ein guter Kompromiss.
