### ISSUE TITLE
Überschreiben der disabledHelpGUIDs beim Laden eines Spielstands

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#241]
Ich habe noch immer ein Problem mit den Help-IDs. Ich glaube, der Spielstand ist nicht der richtige Platz, um sie zu speichern. Es ist eher eine globale Einstellung (App.config?).
Sobald ein Spieler die Hilfe gesehen und gesagt hat, dass er diesen Hinweis nicht mehr braucht, sollte das Fenster nicht wieder aufgehen - tut es aber, wenn ein Spielstand geladen wurde, in dem das Flag noch nicht gesetzt war (gleiches wahrscheinlich für "zeige keine Hinweise".
(EDIT: Das Nichtladen aus dem Speicherstand, wie ich es testweise versucht habe, hat fast den gewünschten erfolg. Beim zweiten Laden geht die Hilfe nicht mehr auf. Dafür aber bei jedem ersten Laden - auch nervig.)

**Comment by GWRon** [comment]
Du kannst die Hilfe global in den "Einstellungen" weghaken.

Ansonsten ist es "lokal"... Fuer den Fall, dass mehrere Benutzer an einem PC spielen.

**Comment by nittka** [comment]
D.h. wir würden es für einen einzelnen Spieler in Kauf nehmen, dass er in einer Session (Spiel nicht neu gestartet) bei jedem Laden des Spiels das Hilfefenster wieder sieht, obwohl er vor dem letzten Laden schon einmal gesagt hat "nicht mehr anzeigen".

Ein Workaround wäre, das Laden der Help-IDs nur beim ersten Laden zu machen und sie bei weiterem Laden nicht zu überschreiben...

**Comment by nittka** [comment]
Weiterhin funktioniert es nicht das lokale "zeige keine weiteren Hinweise" wieder rückgängig zu machen. Selbst wenn man mit F1 die Kontexthilfe aufmacht und beide Haken entfernt, geht die "automatische" Hilfe nicht wieder auf.
Ich glaube, das Abfragen der Deaktivierung über die Liste der IDs ist problematisch. Stattdessen sollten die Fenster nach ihrem Flag gefragt werden. Aktuell gibt es redundante (inkonsistente) Information.

**Comment by GWRon** [comment]
Du beziehst dich auf die "alle nicht mehr anzeigen" und nicht "dieses nicht mehr anzeigen"? Fuer den Fall koennte man das wohl aendern.

Es muesste an zwei Stellen gespeichert werden... So wie derzeit, und in einer Globalen (die fuer die session bleibt).

Deaktiviert man die Hilfe, setzt es die globale und die Gameconfigvariable.
Beim Einladen wird die gameconfig ueberschrieben
Beim ueberprüfen wird die gameconfig herangezogen... Und danach muss geschaut werden ob die globale es DEaktiviert. 

Warum nur bei Deaktivierung?

Angenommen man hat noch nicht global deaktiviert... Im Speicherstand aber schon ausgeschalten...dann waere die Einstellung des Speicherstands ignoriert.

**Comment by nittka** [comment]
Was hältst Du von der folgenden Vereinfachung. Es gibt ausschließlich die Option "keine weiteren Tipps anzeigen". D.h. jede Hilfsseite würde einmal automatisch angezeigt werden, außer der Spieler will keine automatische Hilfe mehr. Mit F1 kommt man ja überall an die Hilfe. Damit entfällt ein Haufen aufwändiger Code für den unwahrscheinlichen Fall, dass ein Spieler dieselbe Hilfe mehrfach automatisch angezeigt bekommen möchte.

**Comment by GWRon** [comment]
Klingt gut. Das kam ja eh alles aus der Zeit, in der kein F1 verfuegbar war.

Generell kann auch ein Hilfebutton unten im Interface eingefuehrt werden...fuer tablet/nur-Maus-Spieler

**Comment by nittka** [comment]
Den Hilfebutton gibt's schon. Er muss nur noch so implementiert werden, dass er nicht nur die allgemeine Hilfe aufmacht, sondern die Kontext-Hilfe.

**Comment by GWRon** [comment]
Das meinte ich. Der kann ja einfach die ingamehilfe-Anzeige erzwingen

**Comment by nittka** [comment]
Wir kommen an den Punkt, wo ich Segmentation-Faults verursache. Wohl durch Entfernen und Umbenennen von Feldern bei der Hilfe kommt es beim Laden eines alten Spielstands zum Fehler.
Kannst Du mir die Stelle nennen, an der ich eingreifen kann, wenn Werte aus einem gespeicherten Spielstand nicht mehr relevant sind?

**Comment by GWRon** [comment]
Also wenn ein Typ neue Felder bekommt und alte verliert... sind diese Null (ausser primitive wie Int, String...die sind halt 0, 0.0, "",...).

Ein segfault deutet drauf hin, dass ein Objekt nicht gefunden aber blindlings zugegriffen wurde.

Kannst Du deine derzeitigen Aenderungen mal in eine Codebox (drei backticks) hier packen?


Wenn man den Typ eines Feldes anpasst, gibt es ein paar Funktionen in denen man dies behandeln kann (in der main.bmx). 
Aber tut das denn überhaupt Not? Die Speicherstaende der alten Versionen siind eh schon inkompatibel.

**Comment by nittka** [comment]
Siehe obigen Commit.
Ich möchte schon wissen, was genau das Problem ist; worauf man aufpassen und was man lassen muss, um nichts kaputt zu machen, wo man suchen und ggf. reparieren kann.

In diesem Fall war ich überrascht, da ich angenommen hatte, dass wegfallende Felder kein Problem darstellen sollten - die können dann halt nicht gesetzt werden - aber brauchen sie hier ja auch gar nicht. Initialwerte sind ja da...

Tatsächlich ist die Inkompatibilität auch jetzt schon doof (Testspielstände, mit denen ich in den letzten Tagen gearbeitet habe).

**Comment by GWRon** [comment]
also ein wegfallendes "field" ist auch nicht das Problem. Also da sollte nix abstuerzen.

Vielleicht fang ich ja den "Array" nicht richtig ab (disabledhelpguid dingens). Den kannst Du ja testweise wieder reinmachen und schauen ob es dann noch abstuerzt.

Generell: Debug-Build und schauen wo der segfault passiert.

Gern kannst Du mir auch die Aenderung hochladen - und den Speicherstand dazu.

**Comment by GWRon** [comment]
Falls du mal aus
Field myobj:TMoveable
ein
Field myobj:TCar
machen solltest, kannst du in main.bmx dich haendisch "drum kuemmern":

```BlitzMax
Type TSavegameConverter
	Function GetCurrentTypeName:TTypeID(typeName:String)
		Select typeName.ToLower()
			Default
				print "TSavegameConverter.GetCurrentTypeName(): unsupported but no longer known type ~q"+typeName+"~q requested."
				end
		End Select
	End Function
	
	
	Method DeSerializeUnknownProperty:Object(oldType:String, newType:String, obj:Object, parentObj:Object)
		Print "DeSerializeUnknownProperty: " + oldType + " > " + newType
'<--- hier
```

**Comment by nittka** [comment]
> Debug-Build
Wenn man mit Rennen anfängt, bevor man Laufen gelernt hat. Ich hab' in MaxIDE schon die Option gesehen, aber dann...
Ich probier mal noch etwas rum.

**Comment by GWRon** [comment]
Ich hatte schon erlebt, dass ein "throw" nicht wirklich die Meldung ausspuckte ... hab deswegen mal mein  `end` entfernt, wenn ein unbekannter Typ geladen werden soll - glaub aber nicht, dass es Dir hier hilft.

**Comment by nittka** [comment]
Wenn ich das Array wieder reinnehme, gibt es keinen Segmentation-Fault. D.h. Du musst wohl bei der DeSerialisierung abfangen, dass es das Array gar nicht mehr gibt.

> siehe letzter Commit

gepusht?

**Comment by GWRon** [comment]
Ahh da waren noch offene "pulls" deswegen hat es meinen "push" nicht rausgeschickt ...  nun schlafen die Kinder wenigstens ("Grueffelo die 45te")

**Comment by GWRon** [comment]
Also ich hab das Field bei mir mal "umbenannt" -- "disabledHelpGUIDsNEW:string[]"  ... und konnte trotzdem einen alten Speicherstand einladen (auch ohne die letzte Aenderung von mir).

```
[22:02:01] SAVE DBG |                : Savegame was created with an older TVTower-build. Enabling basic compatibility mode.
[WARNING] TPersistence: field "disabledHelpGUIDs" is no longer available.
[22:02:03] SAVE DBG |                : Savegame file "savegames/quicksave.xml" loaded in 1350ms.
```

**Comment by GWRon** [comment]
Bekommst du den "segfault" sofort beim Einladen, oder erst spaeter "nach" dem Einladen?

**Comment by nittka** [comment]
Ich denke direkt beim Laden. Ich bekomme noch die Nachricht "Savegame was created with..." aber dann nicht die darauffolgenden Log-Nachrichten. Daher vermute ich, dass direkt beim Deserialisieren das Problem auftritt.
Der Fehler tritt bei Dir möglicherweise nicht auf, da Du einen Spielstand verwendest, in dem gar keine Einzel-Screens als disabled markiert waren (Spiel mit Hinweisen starten, Räume besuchen, für die einzelnen Hilfetexte sagen, dass sie nicht mehr angezeigt werden sollen, Spiel speichern).
Bis zum geänderten Converter kommt der Code wohl gar nicht erst.

**Comment by nittka** [comment]
Das Problem scheint hier zu liegen

https://github.com/TVTower/TVTower/blob/3003128118678d03c3bb471c05cc161702832215/source/Dig/external/persistence.mod/persistence_mxml.bmx#L648

fieldNode.getAttribute("type") liefert array:String[] und beim Aufruf type.ForName kommt es zum Segmentation Fault. Ein Print vor der Zeile wird ausgegeben. Der print nach der Zeile kommt nicht mehr. Durch diesen Fehler wird das nicht mehr vorhandene Feld dann auch nicht einfach ignoriert.

**Comment by GWRon** [comment]
Hab mir die Codestelle noch nicht angeguckt...aber da vor wenigen Wochen erst was aehnliches gefixr. Denke das ist das gleiche...nur fuer einen anderen Context.

Da wird kein ttypeid gefunden werden..aber blind ".name()" aufgerufen.

**Comment by nittka** [comment]
Ich bereite dann den PR erstmal vor, indem ich das Array (mit Kommentar) drinlasse.

**Comment by GWRon** [comment]
Also wenn es an der von dir verlinkten Zeile liegt ... sollte es nicht "segfaulten".
```
				Local serializedFieldTypeID:TTypeId = TTypeId.ForName(fieldNode.getAttribute("type"))
						If Not strictMode And serializedFieldTypeID
							Print "[WARNING] TPersistence: field ~q"+fieldNode.getAttribute("name")+"~q is no longer available. Created WorkAround-Storage."

							'deserialize it, so that its reference exists
							DeSerializeObject("", fieldNode)
						Else
							Print "[WARNING] TPersistence: field ~q"+fieldNode.getAttribute("name")+"~q is no longer available."
						EndIf
						Continue
```

Denn diese Zeile macht ja nur die Deserialisierung WENN der TTypeID gefunden ("nicht null") ist. Es versucht dann auch nicht, das Feld irgendwie zu "befuellen". Es deserialisiert das dahinterliegende Objekt, damit es fuer andere "vorhanden ist" (falls im Speicherstand an anderen Stellen eine direkte Referenz zu dem Objekt besteht).


Ich versuche mal einen Speicherstand mit "deaktivierter Hilfe" zu erstellen.

**Comment by GWRon** [comment]
> (Spiel mit Hinweisen starten, Räume besuchen, für die einzelnen Hilfetexte sagen, dass sie nicht mehr angezeigt werden sollen, Spiel speichern).

Also: 
- TVTower gestartet
- Einstellungen: Hilfetexte anzeigen
- Neues Spiel
- Ins Archiv "diesen nicht mehr anzeigen" ...
- In den Programmplan "diesen nicht mehr anzeigen" (also jeweils "OK")
- gespeichert
- Field disabledHelpGUIDs umbenannt
- TVTower (neu) gestartet
- Speicherstand eingeladen
- "[WARNING] TPersistence: field "disabledHelpGUIDs" is no longer available."
- Spiel laeuft weiter

**Comment by GWRon** [comment]
Aaaahhh ich habs ... ich hab da in einem BlitzMax-Modul was gefixt gehabt ... was noch nicht "official" ist.

**Comment by nittka** [comment]
Und ich habe in der Start-Methode bei main TTypeId.ForName("array:String[]") eingefügt und bekommen beim Programmstart einen Segmentation-Fault...

**Comment by GWRon** [comment]
siehe eben verlinktes issue.
Bis mein Fix "offiziell" ist, koennen wir eben diese Sache in der persistence-datei manuell abfangen.

aus
```BlitzMax
						Local serializedFieldTypeID:TTypeId = TTypeId.ForName(fieldNode.getAttribute("type"))
```

mache mal
```BlitzMax
						Local serializedFieldTypeID:TTypeId
						'for now brl.reflection has a bug - until our fix
						'is merged into official repositories, we need
						'to circumvent it
						If fieldnode.getAttribute("type").EndsWith("]")
							'this would segfault
							'serializedFieldTypeID = TTypeId.ForName(fieldNode.getAttribute("type"))
						Else
							serializedFieldTypeID = TTypeId.ForName(fieldNode.getAttribute("type"))
						EndIf
```

Wenn es damit klappt, machen wir das erstmal in den Code rein, bis offiziell gefixt.

**Comment by GWRon** [comment]
Das mit dem offiziellen Fix ist halt doof, da eigentlich die Reflection-Sache generalueberholt werden sollte (mit libffi - nur hat da @HurryStarfish noch ein Problem, wie er die Libs richtig inkludieren kann, falls DU Dich auch damit auskennst, koennte man das vielleicht mal "in Gang" bekommen, ich bin nicht so der C/C++/...-"Kenner")

**Comment by nittka** [comment]
Mit C hatte ich vor mehreren Jahrzehnten im Studium zuletzt zu tun...
Mit der Variante im PR geht es auch - die Liste bleibt zunächst drin, wird aber für nichts verwendet.

**Comment by GWRon** [comment]
Ja das geht schon so...die Anpassung im persistence-Teil ist aber denke etwas schoener ..vor allem, wenn man an anderer Stelle zufaellig was aehnliches mal aendert und wieder einen Segfault bekommt.

**Comment by nittka** [comment]
Verstehe ich. Wenn wir die Anpassung aber im Persisenz-Teil machen, müssen wir aber auch dran denken, die Sonderbehandlung nach dem Fix wieder auszubauen.

**Comment by GWRon** [comment]
Die Sonderbehandlung ist eh noch fehlerhaft...ueberarbeite ich gleich...dann funktioniert sie auch "nach dem fix" noch.

**Comment by GWRon** [comment]
Ist nicht nur die Sonderbehandlung - die waere an sich nicht noetig. Mein Code ignoriert "array:"-serialisierungen (wenn das Feld nicht mehr vorhanden ist). Liegt also an meinem Extracode im Persistenz-Teil.

Fixe ich.

**Comment by GWRon** [comment]
Ich hab zwar was programmiert - damit koennen wir auch "field-umbenennungen" "abfangen" ... aber irgendwas spinnt noch im "reflection code" (bzw im generierten C Code oder so).

Muss ich mir noch anschauen.

Davon unabhaengig werden nun Arrays "korrekt" abgearbeitet (falls dort serialisierte Elemente drin sind).

**Comment by GWRon** [comment]
Kannst du mal mit dem aktuellen Commit / "Fix" ausprobieren?

Hab da n bisschen was "vereinheitlicht" und wir koennen einfacher "Typen" und "Fields" umbenennen.

**Comment by nittka** [comment]
Der Spielstand kann mit der Änderung geladen werden. Ich habe den PR aktualisiert. Damit können wir dieses Ticket dann zumachen.
