### ISSUE TITLE
Tastatur-Scrollen in den Nachrichten

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#242]
Das Scrollverhalten bei der Nachrichtenübersicht im Büro muss geprüft werden. Wenn man keine Nachricht selektiert wird gar nicht gescrollt, wenn man eine Nachricht selektiert geht das Scrollen mit Pfeil- und den Bild-Tasten wild durcheinander.

**Comment by GWRon** [comment]
Dazu muesste man in der Update Methode der Liste immer wieder den Fokus geben. Beim droppen auf  die "rechte Liste" bekommt diese sonst den Fokus.

**Comment by nittka** [comment]
Sprechen wir über dieselbe Liste? Im Büro der Zettelhaufen mit der filterbaren Liste alle Nachrichten, Finanzen... Welchen Drop meinst Du da? Außer der Auswahl des Nachrichtentyps gibt es doch gar keine Aktionen.

**Comment by GWRon** [comment]
Ich sprach von den Nachrichten beim Nachrichtenplaner... "news".

Haben wir wohl aneinander vorbeigeschrieben.

**Comment by GWRon** [comment]
Dabei hast du ja "Buero" geschrieben....sorry..

**Comment by GWRon** [comment]
Ok ... kann es nachvollziehen. "Bild hoch/runter" funzt, aber "page" und "cursor" spinnen rum.

**Comment by nittka** [comment]
Ich vermute, es liegt an der unterschiedlichen Sortierung der zugrundeliegenden Nachrichtenliste und der angezeigten. Das Tastaturscrollen sollte auf der Anzeigeliste basieren, da hier ja auch noch gefiltert ist. (Achtung PR mit Logikänderungen für die Nachrichtenübersicht)

**Comment by GWRon** [comment]
Also ich habe die Sortierung ueberarbeitet - sowohl die gui elemente als auch die archivedmessages wuerden nun nach "time" sortiert werden (was nicht wirklich notwendig sein sollte - da die elemente ja schon "nach zeit geordnet" hinzugefuegt werden).

Das Problem ist aber an anderer Stelle zu suchen:
Listen (TListBase) reagieren auf PageUp/Down, Cursor...
Auswahllisten (TSelectList) wie eben die Archived-Message-Liste (man kann die Elemente "anklicken") ueberschreiben das und versuchen mit jedem Tastendruck "das naechste/vorherige" Element auszuwaehlen und "hinzuscrollen".

Das kam mit Commit c8f64fcf8700cfaf73c54f80621e2219cb6a49ee

Muss ich noch rausfinden, wieso es da so "rumbuggt"

**Comment by nittka** [comment]
Das Scrollen mit den Bildtasten reagiert etwas zu "schnell", wie ursprünglich bei der Spielanleitung. Ggf. kann man da aber auch auf Beschwerden anderer Spieler warten.

**Comment by GWRon** [comment]
Es scrollt immer einen "Bildschirm". Und die cursortasten scrollen ein "Element".

**Comment by GWRon** [comment]
Du kannst "scrollItemHeightPercentage" der Liste anpassen - falls Dir zu viel mit einmal gescrollt wird ?

Fuer "pageup/down" ... scrollt es dir zu VIEL oder "zu schnell hintereinander"? fuer letzteres muessen wir ein "Taste gehalten"-Objekt anlegen und ueberwachen (statt uns auf die "Default"-Werte zu verlassen - bzw die global zu veraendern).
`TKeyHoldInformation` von base.util.input.bmx

Oder - man fuehrt fuer die Listen noch eine neue Variable ein - "scrollItemHeightPercentage"-maessig. Vielleicht `pageScrollHeightPercentage` - 1.0 wuerde "1 Bild" (Contenthoehe) ergeben.

Einzufuehren waere es in "TListBase.HandleKeyboardInput()".

**Comment by GWRon** [comment]
Alternativ koennte aus "KeyWrapper.IsPressed()" auch ein "KeyManager.IsHit()" gemacht werden ... dann wuerde es nur 1x getriggert werden.
Jetzt: "gedrueckt halten ... 250ms trigger ... 250ms trigger"
mit IsHit: "gedrueckthalten ... trigger. nix weiter"

Mit IsHit() muss man also immer wieder erneut "tappen" um runter zu scrollen.

**Comment by GWRon** [comment]
Ah ich sehe ... ich habe "KeyDown" dort verwendet - kein Wunder, dass es schnell geht.
