### ISSUE TITLE
"nächstes Reichweitenlevel" auch wenn schon angebunden

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#247]
Auf der Karte wird beim Neuanlegen eines Kabelvertrags aktuell auch dann gewarnt, dass das nächste Reichweitelevel droht, wenn man die Anbindung schon gebucht hat. Tatsächlich wird in dem Fall auch gewarnt, dass der Preis zu hoch ist, wenn man gerade nicht genug Geld hat.

Vorschlag: Entweder man kann beim Neuanlegen einer Kabelanbindung, ein Bundesland gar nicht erst selektieren, wenn bereits ein Vertrag besteht oder die Preisinformation etc. werden in diesem Fall unterdrückt - nur die Reichweite steht im Hovertext.

Ich habe auf die Schnelle noch nicht rausgefunden, wie ich die Besitzverhältnisse abfragen kann (der owner und das Active-Flag sind identisch, egal ob ein Vertrag besteht oder nicht).

**Comment by GWRon** [comment]
Hoffe dir genuegt die neue Umsetzung - wenn nicht, wieder aufmachen.

**Comment by nittka** [comment]
Der Cursor wird korrekt geändert, aber die Reichweitewarnung wird noch angezeigt.

**Comment by GWRon** [comment]
Das Problem war, dass immer "temporaere" TStations angelegt wurden - die natuerlich nicht "paid" waren.

Die mouseoverstation wird nun mit einem bestehenden cablenetworkuplink besetzt (wenn vorhanden) und damit laeuft die Erkennung.
