### ISSUE TITLE
Diskrepanz Reichweite

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#251]
Ich beobachte bei mir gerade ein seltsames Verhalten. Die Reichweitezahlen im Quoten-Debug-Bildschirm (Q) und im Interface passen nicht zusammen (Gesamtzahl der erreichten Zuschauer in der Gesamtbevölkerung).
Im Interface wird für die Ermittlung `GetStationMap( GetPlayerBase().playerID ).GetReach()` verwendet, im Quoten-Bildschirm `GetBroadcastManager().GetAudienceResult( playerID ).WholeMarket`.
In einem Beispielspielstand unterscheiden sich die beiden Werte zunächst geringfügig (print im Code eingefügt um die nicht gerundeten Zahlen zu sehen). Dann bricht die Zahl im Quoten-Debug-Bildschirm um 13 Uhr manchmal (nicht immer!) um 1.2 Millionen Zuschauer ein, obwohl kein Vertrag ausgelaufen ist.

[QS2.xml.tar.gz](https://github.com/TVTower/TVTower/files/5741553/QS2.xml.tar.gz)

**Comment by GWRon** [comment]
Hmm.. muss ich mir mal anschauen.

**Comment by GWRon** [comment]
![image](https://user-images.githubusercontent.com/2625226/103169058-f0c8ec00-4838-11eb-950c-ac9a41c4b97e.png)

Interessant ... Chrome laesst mich den Download nicht machen - also es gibt nur "verwerfen" als Option. Krass.

**Comment by GWRon** [comment]
Kann es nachstellen. Quotenbildschirm "manchmal" nur noch 3.x Millionen, Quotentooltip zeigt "5." (sic!)

**Comment by GWRon** [comment]
Ok ... viele Debugausgaben und Herumcheckerei spaeter... schon nach Einlesen des Spielstandes gibt das Spiel fuer "Kabelnetze" 0 Zuschauer (fuer Spieler 1) zurueck - und 13 Uhr wird eben dies dann bei der Quotenberechnung "erkannt" und beruecksichtigt.
Es faellt dann eben um die 1.1 Millionen (oder aehnlich) zurueck.
Wird der Wert von 4.9 auf 4.95 erhoeht - ist dem eben nicht so (warum es erhoeht, weiss ich noch nicht, eine Volkszaehlung findet erst am Spieltag 16 - Speicherstand ist am Spieltag 15 - statt).

Mal sehen wo sich der Bug genau verbirgt.

**Comment by GWRon** [comment]
OK ... beim Anlegen von Kabelnetz-"Stations" wurden die sectionNames gefuellt - die werden aber nicht im Speicherstand hinterlegt (...glaube damit ich flexibel neue hinzufuegen koennte). Mit einem "Getter" werden die dynamisch abgerufen und gecachet.

Nur ... wurde nicht ueberall der Getter verwendet. Ergo konnte fuer Bayern Dein Uplink nicht gefunden werden (`if sectionName = name` ...), ein "count" ging auf 0 ... und schwupps flogen die 1,1 Millionen aus der Reichweite raus.
Je nach Aktion wurde der Cache aber erneuert (da Getter genutzt) ... und dann liefs.

**Comment by nittka** [comment]
Would it make sense to actually make all "internal" fields (currently just marked with prefix `_`) private?
```
private
Field _internalX
public
Field visibleY
```

**Comment by GWRon** [comment]
Koennte man machen... Glaube die private koennen file-intern aber genutzt werden. Was in unserem Fall also nicht geholfen haette .

**Comment by nittka** [comment]
Kompiliert aktuell nicht...

**Comment by GWRon** [comment]
Was kompiliert nicht? Hab ich was vergessen?

**Comment by GWRon** [comment]
Ah ja ... wieso auch immer das da gestern kompilierte. Hab per ForcePush aktualisiert.
