### ISSUE TITLE
Compile-Probleme Linux

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#255]
Aktuell arbeite ich in der Entwicklung mit geänderten Dateien, da es beim Sound Compile-Probleme gibt. Symptom ist die Fehlermeldung `Processing:base.sfx.soundmanager.soloud.bmx Compile Error: Can't find interface for module 'audio.soloudaudiominiaudio'`

Ich arbeite unter Lubuntu. Ich habe die Blitzmax für Linux x64 (https://blitzmax.org/downloads/) heruntergeladen und die unter https://blitzmax.org/docs/en/setup/linux/ genannten Pakete installiert.

**Comment by GWRon** [comment]
Ah - ich hatte noch die alten Verzeichnisse von dem Modul drin, deswegen konnte ich noch bequem kompilieren.

**Comment by GWRon** [comment]
Aber auf dem aktuellsten Modulstand .... spielt es mir keine Musik ab.

**Comment by GWRon** [comment]
das is der letzte audio.mod-commit der hier funktioniert, denke ich muss irgendwas anpassen, damit es mit den spaeteren "soloud"-lib-updates kompatibel bleibt.

Kurz: bis ich ein "[Dig] Audio..." Update hochlade, musst Du einfach nur "mods/audio.mod" mit dem hier ersetzen:
https://github.com/bmx-ng/audio.mod/tree/b8682df85a827811a4559ea949fed4a49638145f

**Comment by GWRon** [comment]
Ok, also ein neuerer commit:
https://github.com/bmx-ng/audio.mod/tree/c0cec8be597c9f43f14d26b4ea3da5feab7975bc
geht auch noch.

Denke ab dem "refactoring" gibt es die Probleme...

**Comment by GWRon** [comment]
Das Refactoring enthaelt eine "miniaudio.h"-Aktualisierung (>10.000 LOC) ... denke irgendwas macht dann meinen Audio-Wrapper kaputt (ich wrappe nochmals ueber den audio-wrapper herum, damit ich Crossfading, Soundloops, ... etc gekapselt habe).

Versuche mir das heute Abend mal anzuschauen. Bis dahin - aelteres Commit wie beschrieben nutzen.

**Comment by GWRon** [comment]
Kannst nun die aktuelle audio.mod nutzen.

**Comment by nittka** [comment]
Danke. Das erleichtert meinen Arbeitsablauf erheblich!
