### ISSUE TITLE
Verschwinden von Produktionen im Studio

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#263]
* Drehbuch X im Studio hinstellen
* Koffer bei Drehbuchautor komplett auffüllen
* ins Studio gehen
* (X kann nicht in den Koffer gelegt werden)
*  Drehbuch aus dem Koffer auf das vorhandene Drehbuch im Studio droppen

Bei mir ist X dann nicht mehr im Studiokoffer und kommt auch nie wieder dorthin. Im Supermarkt ist das Drehbuch noch vorhanden und kann geplant werden.

Entweder man muss verhindern, dass bei existierenden Drehbüchern in den Studios mindestens ein Platz im Koffer frei bleibt oder die Kapazität des Koffers darf nicht strikt beschränkt sein (eins wird im Studio einfach nur nicht angezeigt und erscheint wieder, wenn ein Drehbuch verkauft/abgedreht wurde...)

**Comment by GWRon** [comment]
Waere nicht die einfachste Loesung, den Slot des "gedraggten" freizumachen / zu tauschen?

Wenn wenn im Koffer 5 Buecher reinpassen - und im Studio 1 Buch, und man den Koffer + das Studio vollmacht, sind doch nur 6 Buecher gleichzeitig erreichbar. Entsprechend gibt es keines "zu viel".

Buch aus Koffer mit Drop auf den besetzten Slot: Buch vom Slot wird als Ersatz in den Koffer gedroppt und gleich wieder gedraggt. Ein Rechtsklick wuerde es dann im Koffer platzieren ... ja nein ?

**Comment by nittka** [comment]
Tauschen passt. Die Frage wäre, wie man einen Spieler unterstützt, der ordentlicherweise erst das bereits im Studio stehenden Drehbuch in den Koffer zurückpacken möchte, bevor er das nächste hinstellt...

**Comment by GWRon** [comment]
Variante 1:
- es gibt einen Slot mehr im Koffer
- wie erklaert man dem Spieler, dass er zwar das Studiobuch in den freien Slot legen kann, aber nun erst gehen darf, wenn er ein anderes im Studio platziert? Hinweisfenster sind nicht so pralle

Variante 2:
- das Studioscript "faellt ins nirgendwo" des Koffers
- nimmt man ein anderes heraus, "rutscht" es nach
- wie erklaert man dem Spieler, dass es ein "nirgendwo" gibt ?
- wie erklaert man dem Spieler, dass er nicht einfach "rausgehen" kann, waehrend es im nirgendwo ist?

**Comment by nittka** [comment]
Variante 3: Wenn man in einem Studio noch ein Drehbuch stehen hat, darf man beim Drehbuchautor nicht den gesamten Koffer vollmachen. Es muss immer noch ein "Wechsel-Slot" freibleiben. Bei mehreren Studios muss man natürlich aufpassen. Da sollte es dann aber ausreichen, das Draggen in einen bereits vollen Koffer zu verbieten. Dem Spieler sollte schon klar sein, dass er zunächst ein Drehbuch in einem anderen Studio unterbringen muss (bei einem einzelnen Studio geht das ja nicht).

**Comment by GWRon** [comment]
Die "ProgrammeCollection" hat schon die Funktionen:
MoveScriptsFromSuitcaseToArchive()
und
MoveScriptFromArchiveToSuitcase()

Der Grundgedanke war dort, dass fuer den Fall "passt nicht mehr", Drehbuecher im Archiv landen. Bisher kann man die aber nicht mehr dort "rausholen". Eventuell sollte man im Archiv automatisch die Koffer "vollmachen" - oder spaeter dem Archivar das explizite Einlagern/Auslagern ermoeglichen...

**Comment by nittka** [comment]
Die einfachste Variante dürfte tatsächlich sein, wenn man das Drehbuch in den Koffer fallen lassen kann und das Drehbuch, auf das man es hat fallen lassen, dann ins Studio kommt - also Tausch einfach in anderer Richtung. (Fallen lassen auf leeren und besetzten Slot erlauben).

Wenn das "neue" Drehbuch dann noch im Zustand dragged ist, muss der Fall des Verlassens des Studios beachtet werden. Man darf dann das Drehbuch nicht zum Ursprungspunkt (in den Koffer) fallen lassen, denn der ist ja voll, sondern muss ihn im Studio lassen.

**Comment by GWRon** [comment]
Ich bin schon dran.

Koffer->Studio waren zwei Zeilen

Aber dragndropt man studio->Koffer...da hab ich mir locker zwei Stunden die Zaehne ausgebissen...braucht wohl doch weiteren GUI code...

**Comment by GWRon** [comment]
Statt einen Fix "draufzusetzen" war es zielfuehrender, den Drop-Teil neu zu schreiben.

**Comment by nittka** [comment]
Es verhält sich noch nicht wie erwartet und bei mir verschwinden (vorläufig noch nicht 100%ig reproduzierbar) immer mal wieder Drehbücher beim Tauschen (kein Raumverlassen, nur drag/drop zwischen Koffer und Studio).

Ausgangssituation ist: Drehbuch A im Studio und Koffer ist voll, Drehbuch B ist das letzte im Koffer
* A aufheben und auf B droppen
** erwartet A im Koffer, Studioplatz leer, B in der Hand
** Zustand ist (meiner Ansicht nach falsch): A im Studio, ein Platz im Koffer leer, B in der Hand

**Comment by GWRon** [comment]
Also die "schoenere" Verhaltensweise ... ist "low priority" (da muss man mehr machen, als mit der derzeitige "Fix").


Interessanter sind eher die verschwundenen Drehbuecher - ich denke mal, dass ist wenn aus irgend einem Grund in einem Zwischenzustand aufgeraeumt wird oder so. Also Element 1 ist gedroppt (was vorher das andere draggt) und dann wird das gedraggte geloescht (warum auch immer).

Eventuell muesste man sich paar debugprints/logs einbauen.

**Comment by nittka** [comment]
Es kommt immer noch zu verschwundenen Drehbüchern. Wie gesagt, scheint die Richtung Koffer->Studio stabil zu funktionieren. Ich würde gern für das 0.7er-Release die Richtung Studio->Koffer verbieten, wenn der Koffer voll ist. Auf diese Weise können wir zumindest einen inkonsistenten Stand verhindern. Eine zweite Alternative wäre, den Kauf weiterer Drehbücher zu verbieten, wenn die Gesamtzahl der Drehbücher im Besitz des Spielers bereits der Kapazität des Koffers entspricht.

**Comment by nittka** [comment]
Ich glaube, ich kann das Verhalten reproduzieren. Ausgangssituation im Studio ist ein vorhandenes Drehbuch (S) und ein voller Koffer.
* S aus dem Studio aufnehmen (S ist in der Hand und steht weiter transparent im Studio)
* Drop auf dem unteren Kofferrand - wichtig, nicht auf einem der Drehbücher im Koffer
* das transparente S im Studio verschwindet (es ist wird aber noch festgehalten)
* Rechtsklick; es scheint, als ob S nun wieder im Studio steht
* Nehmen eines Drehbuchs auf den Koffer Drop auf den Studioplatz - S ist komplett verschwunden

Beim "Drop" des scripts auf den Kofferrand reagiert nicht die onDropScript-Methode sodern clickScript.

**Comment by GWRon** [comment]
Das klingt schonmal...sehr hilfreich. Gut gut!

**Comment by nittka** [comment]
Ursache scheint die onDropOnTarget-Implementierung in TGUIGameSlotList zu sein, die auch in diesem Fall aufgerufen wird. Entfernen aus der fromList erfolgt, Hinzufügen zur toList geht aber nicht (Koffer voll), das Wiederhinzufügen zur fromList geht dann aber schief (ich vermute mal, weil es gar keine Liste sondern eine Map ist, für die der Key an dieser Stelle gar nicht bekannt ist). Das Veto hilft dann aber auch nicht mehr.

**Comment by nittka** [comment]
Aus einem mir nicht nachvollziehbarem Grund geht es aber auch nicht die Reihenfolge umzudrehen, d.h. aus fromList nur zu entfernen, wenn das Hinzufügen zur toList erfolgreich ist.
In diesem Fall konnte ich zwar den drop auf den Kofferrand reparieren, dafür funktioniert der Drop auf ein Drehbuch im Koffer nicht mehr richtig...

**Comment by GWRon** [comment]
Wir koennten das droppen schon im ersten "trydrop"-event abfangen - der Koffer nimmt dann einfach gar nicht erst die "Drop-Anfrage" an.

Ansonsten muesste geschaut weren, wieso das hinzufuegen zur "fromList" nicht geht - sollte  ja "frei" sein.

**Comment by GWRon** [comment]
Also notwendiger Punkt 1: die Studio-Slotliste muss "SetAutofillSlots(True)" bekommen, denn nur dann akzeptiert sie ein "AddItem" ohne den sonst notwendigerweise anzugebenden Slot index.

Wenn man "haendisch" droppt, bekommt die Liste den dabei genutzten "Slot" mit - und kann entsprechend reagieren.

Droppt man aber auf der Kofferliste, weiss die Kofferliste nix ueber die genaue Herkunft ... und sagt dann einfach "hey, alte Liste, nimm mal dieses item hier".

Kann man natuerlich auch umgehen, der Liste beibringen, die alten Slotwerte zu speichern etc - aber vielleicht ruecken dort ja alle Items automatisiert nach ... also lieber die "alte Liste" mal selbst machen lassen.


Ok, ist dies gemacht, fuehrt ein "fehlgeschlagener Drop" aber dazu, dass das Studio-Skript wieder auf dem Studioplatz landet - anstatt in der Hand gedraggt zu bleiben.

Hier kommt nun Punkt 2 ins Spiel: shcon den "trydrop" abfangen.

**Comment by nittka** [comment]
Mein Vorschlag wäre: wenn der Koffer schon voll ist, beim trydrop die Richtung Studio->Koffer unterbinden. Damit sollten wir kurzfristig auf der sicheren Seite sein, ohne zu viel umbauen zu müssen, oder?

**Comment by GWRon** [comment]
hab aber schon umgebaut - bin eigentlich nur noch an der "Schoenschrift".

**Comment by nittka** [comment]
OK. Dann plane ich Zeit für's Testen am Wochenende ein.

**Comment by GWRon** [comment]
Soweit ich sehe, muss man in der Drehbuchagentur auch noch aehnliches fixen. Der aktuelle Commit sollte nun aber erstmal im Studio ein hin-und-her-tauschen ermoeglichen (mittels Strg+Tab kann man auch bequem ueberpruefen, ob alle Skripte "umgeschoben" werden, nicht nur die GUI-Elemente)

**Comment by GWRon** [comment]
Die Drehbuchagentur verbietet nun das Aufheben von Haendlerdrehbuechern, wenn der Koffer voll ist.

Vorher war das Aufheben von "nicht bezahlbaren" Drehbuechern moeglich (nur nicht das fallenlassen). Das ist jetzt gleich mit "verboten".

**Comment by nittka** [comment]
Kann es sein, dass Du vergessen hast, Änderungen zu commiten? Im Studio lässt sich nun gar kein Drehbuch (weder aus dem Koffer noch aus dem Studio) mehr aufnehmen, auch wenn der Koffer nicht voll ist.
In der Drehbuchagentur können nicht bezahlbare Drehbücher weiterhin aufgenommen werden.

**Comment by GWRon** [comment]
Muss an der Drehbuchagenturaenderung liegen - kommt wohl gleich nochmal ein Fix.

**Comment by GWRon** [comment]
Zwei Grundprobleme erkannt:
- im Drehbuchagenturcode hatte ich aus Versehen jedes TGUIScript-Event blockiert, wenn der Spieler nicht in der Drehbuchagentur war (also im Studio)
- statt das "dragging" zu verhindern, hatte ich nur das "Verboten"-Schild an den Preis gekoppelt
