### ISSUE TITLE
Aussehen Betty in Supermarkt

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#264]
Ich vermute ja mal, dass Betty Botterblom die Betty aus der 13. Etage ist. Das Aussehen der Darsteller wird ja gewürfelt. Es ist dann nur seltsam, dass Betty im Supermarkt dunkelhäutig mit dunklen Haaren ist. Sollte für sie das Aussehen fix sein?

**Comment by GWRon** [comment]
![image](https://user-images.githubusercontent.com/2625226/103457348-dc846380-4cfe-11eb-866a-62adf8dc2845.png)
(Die Frau natuerlich)
