### ISSUE TITLE
[Betty] Geschenkuebergabe auch per Dialog?

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#268]
Vielleicht sollte man das Geschenk auch per Dialog uebergeben koennen?

Also eine zweite Option, neben der "habs mir anders ueberlegt"-Antwort?

**Comment by nittka** [comment]
Keine Einwände. Sollte dann die erste Option sein.

**Comment by GWRon** [comment]
Willst du das gleich uebernehmen?

Schraube noch an der Dialoggrafik und lade die gleich hoch - Mittagsruhe der Kinder vorbei :/
