### ISSUE TITLE
Langer Klick und Scrollen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#273]
Beim Handbuch funktioniert das Scrollen bei langem Drücken der Maustaste ohne dass das am Ende auch noch als LongClick interpretiert wird (Raum verlassen).

Bei Listen (z.B. Supermarkt Personenauswahl) wird zwar erst gescrollt, wenn man dann aber die Maustaste loslässt, geht unerwartet das Popup zu oder der Raum wird verlassen.

Bekommt man das frameworkseitig behandelt, dass bei Scrollbalken der lange Klick weggefangen wird?

**Comment by GWRon** [comment]
Muss ich mal schauen...sollte machbar sein.

**Comment by GWRon** [comment]
So ... also ich habe die GUI derzeit ueberarbeitet - jetzt koennte man das "Longclick" angehen....

ich weiss nur noch nicht, wie wir das machen soellten.
Eventuell nur den "longclick" interpretieren, wenn vorher die "mousedown"-events nicht mit "accepted" als "verarbeitet" klassifiziert wurden?

**Comment by nittka** [comment]
Wenn der Fokus auf Scroll-Elementen liegt (Scrollbalken, Buttons im Scrollbalken) den long-click nie "weiterleiten"?
In diesem Fall sollte doch immer das Scrollen gemeint sein. Im schlimmsten Fall muss der Spieler an einer anderen Stelle länger klicken.

Ginge das?

**Comment by nittka** [comment]
Wurde zusammen mit #288 erledigt.
