### ISSUE TITLE
Log-Dateien in separatem Verzeichnis

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#275]
Persönlich fände ich es aufgeräumter, wenn die (zahlreichen) Log-Dateien in einem Unterverzeichnis landen würden und nicht im Wurzelverzeichnis. (logs)

**Comment by nittka** [comment]
Dabei fällt mir ein: Im Debugmodus wird doch wahrscheinlich deutlich mehr ins Log geschrieben, oder? Kann der Performance-Verfall z.T. auch daran liegen (mehr String- und File-Operationen).

**Comment by GWRon** [comment]
Im Debugmodus wird eigentlich nicht "mehr" ins Log geschrieben - da ich das unabhaengig von release/debug aktiviert habe.

Was beim Loggen "Last" erzeugt, ist das "sofort schreiben" (damit bei einem Absturz der Log auch komplett ist).

**Comment by GWRon** [comment]
Erledigt.
