### ISSUE TITLE
Segmentation fault bei Start mit Debug-Option

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#276]
Wenn ich bei mir die debug-Option aktiviere, kommt es unmittelbar beim Start zu einem Segmenation fault. Es ist kurz ein schwarzer Bildschirm zu sehen...
```
[10:02:41] DBG      | GRAPHICSMANAGER.INITGRAPHICS(): Initializing graphics.
[10:02:41] DBG      |                               : SetGraphicsDriver "GL2SDL".
GL2 (with shaders) Active
[10:02:41] DBG      |                               : Initialized graphics with "GL2SDL".
[10:02:41] DBG      |                               : Initialized virtual graphics (for optional letterboxes).
[10:02:41] DBG      | APP.CREATE(): Loading base resources.
[10:02:41] DBG      | APP.LOADRESOURCES(): Loading resources from "config/startup.xml".
[10:02:41] DBG      | TSOUNDMANAGER.GETMUSICSTREAM(): Play music: sfx_music_title
[10:02:41] DBG      | PLAYMUSICORPLAYLIST: GetMusicStream by name "sfx_music_title"
[10:02:41] DBG      |                    : start activeMusicChannel
Segmentation fault (core dumped)
``´

Edit: Das Problem scheint nicht neu zu sein. Es tritt schon mit dem Commit auf, als die Sound-Compile-Problematik repariert wurde (vorher will ich nicht testen, da ich dafür wieder Anpassungen vornehmen müsste).

**Comment by nittka** [comment]
Aus irgendeinem Grund ist in base.sfx.soundmanager.base.bmxZeile 698 `nextMusicStream.CreateChannel(musicVolume)` null obwohl `nextMusicStream` nicht null ist, wie gesagt nur wenn mit Debug compiliert wurde.

Die Frame-Rate ist bei Programmstart auch extrem niedrig.

**Comment by GWRon** [comment]
Ist mir bewusst und bekannt ...also die framerate. Ueberarbeite ja schon schritt fuer schritt sachen. Das Ersetzen von Strings mit Integer IDs brachte jetzt nicht so den Unterschied (bei 1000+ events pro Sekunde).

Und im debug geht halt irgendwie miniaudio und so ne...und wenn man bei miniaudio ein ungueltiges setaudiodriver("egal") macht...dann will es unendlich lang musik starten...weil der channel nicht laeuft.

**Comment by nittka** [comment]
Den Hinweis zur geringen Framerate hatte ich insb. hingeschrieben, da ich mich frage, ob das mit Ursache für das null ist. Falls dem aber nicht so ist, sollte einfach noch ein Guard ergänzt werden.

**Comment by nittka** [comment]
... und möglicherweise ist der dauerhafte Versuch, die Musik zu starten, Ursache für die geringe Framerate. Wenn ich mich richtig erinnere, musste ich ganz am Anfang neben dem Workaround für das Compileproblem (falsches/fehlendes Modul), auch die Musik ausschalten, weil sonst die Framerate exterm niedrig war.

**Comment by nittka** [comment]
Im aktuellen Master-Stand tritt der Fehler nicht mehr auf, wenn ich aber Commit c68cb rückgängig mache (Fix: [Dig] use audioSDL instead of miniaudio (temporary)), kommt es wieder zum Absturz.

**Comment by nittka** [comment]
Welchen Unterschied macht audioSDL versus miniaudio für die "Produktiv"-Variante?

**Comment by GWRon** [comment]
Hmm irgendwie fehlen hier ein paar Antworten, die ich per Mail erledigt hatte...

> Keinen.
> im Release-Modus geht beides.

**Comment by nittka** [comment]
Wenn es dauerhaft beim aktuellen audio-Modul bleibt, kann das Ticket zugemacht werden.
