### ISSUE TITLE
Studio Absturz beim Wegwerfen von Drehbüchern

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#282]
Aktuell kommt es zum Fehler, wenn man im Studio ein Drehbuch in den Papierkorb werfen möchte.

**Comment by nittka** [comment]
Tritt aber nur im Debug-Build auf. Die Musikspiel auch nochweiter und das Fenster ist offen, aber man landet mit einem null-Zugriffsfehler in der MaxIDE. Bislang weiß ich nicht, wie es dann dort weitergeht (außer Abbruch).

**Comment by GWRon** [comment]
Betrifft aber nicht nur den Debugmodus ... die entsprechende Klickbehandlung versucht blindlings auch konzepte zu loeschen obwohl die gar nicht gedraggt sind.
