### ISSUE TITLE
Performance Menüs Laden/Speichern (Debug-Modus)

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#283]
Aktuell fällt in einem Debug-Build die Framerate beim Öffnen eines Menüs für das Laden/Speichern eines Spielstands rapide ab und bleibt niedrig. Auch das Laden selbst dauert gefühlt deutlich länger.

**Comment by GWRon** [comment]
Ja weil im debug modus jede codezeile "ueberwacht" wird

**Comment by nittka** [comment]
Ich mache das Ticket mal als nicht wirklich relevant zu.
