### ISSUE TITLE
KI/Lua - Funktionen mit :long parameter koennen fehlschlagen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#287]
Dalli hatte mit Testversionen unerklaerliche Abstuerze mit "3x EAV". 3x --- das schreit nach KI.

Nachdem ich die Zeitmechanik von "double" auf "long" umgestellt habe und nach Lua freigegebene Methoden wie `WorldTime.GetDay(useTime:Long = -1)` bei ihm unerklaerliche Zahlen zurueckgeben (negative zahlen oder ziemlich grosse), scheint da was nicht zu funktionieren.

Bei meinen TestPCs tritt dies nicht auf - aber Dalli hatte ja auch bei den Doubles die Rundungsprobleme (15.999997 statt 16.000001)

**Comment by GWRon** [comment]
Der Fehler liegt wohl im reflection-Modul "brl.reflection" was bei 32bit-Builds und "long" (eventuell auch "double")-Parametern schlicht einen Bug hat. Wohl werden da falsche Pointer benutzt (groessentechnisch).

Workarounds waeren:
- Methoden ohne Parameter bereitstellen
- Andere Parametertypen bereitstellen
- nur 64bit Builds bereitstellen ;)

**Comment by nittka** [comment]
Für mich klingt Option 3 gar nicht so abwegig. Wenn es keinen Workaround gibt, der die Parametrisierung nicht schwächt...
Vielleicht kommt die Frage etwas spät, aber wäre die Umstellung der Zeit auf eine explizite Zeitklasse langfristig nicht vielleicht sauberer? Dann könnte man sämtliche Berechnungen und Umrechnungen dort kapseln. Im Moment wird im "Fachcode" immer noch rumgerechnet. Wenn das aber nur über Methodenaufrufe geht (ẁorldtime.plusSeconds(30), worldtime.isAfter(eventExecutionTime),...) hätte man viele Fehlerquellen schon compile-seitig erschlagen.

**Comment by GWRon** [comment]
Ich habe in commit 7f4384e1b9f04b517d362fec5b724f5eb614257d erstmal die Funktionsaufrufe der KI mit ":long"-Beteiligung (Parameter und Rueckgabewerte) umgeschrieben (und glaube gleich noch zwei kleine Bugs entfernt).

Bei 32Bit-Builds mit "Long"-Nutzung durch Lua sollte es "Warnfenster" geben ... hab das jetzt mehrfach 20 Tage spielen lassen und es kamen keine.

Theoretisch koennten die Fehler auch spielintern auftreten, wenn "longs" direkt als Parameter in einem reflection.mod-basiertem Codezwei auftauchen. Also irgendwas "entkoppeltes". Hab aber beim "durchwuehlen" noch nichts gefunden.

Rein theoretisch sollten wir also einen 32bit-Build bauen - und nutzen - koennen.

**Comment by GWRon** [comment]
Statt einem "Zeitobjekt" waere mir hier eher ein "Struct" lieber ... allerdings koennen derzeit Structs nicht mittels "reflection" erfasst werden.
Wir muessten also in "Field" hinterlegte Zeitwerte in einem Zeitobjekt "wrappen", dass wiederum braeuchte eine eigene SerializeXYZToString() um die struct-Werte fuer die Serialisierung (Speicherstaende) bereitzustellen.

**Comment by nittka** [comment]
Wenn es bislang keine weiteren Auffäligkeiten gab, sollen wird dieses Ticket dann zumachen?
