### ISSUE TITLE
[GUI] Drag von Scroll-"Button" nicht moeglich

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#288]
Dalli per Discord

Nach dem Umbau der GUI ist ein "Drag" des Buttons auf einer Scrollleiste nicht mehr moeglich

**Comment by GWRon** [comment]
Erledigt in b67d6880dcdbc99008335ca6c43a2f1608220e2c

**Comment by nittka** [comment]
Ich muss das Ticket nochmal aufmachen:
* wenn die Maus über dem Scrollbalken ist und man mit dem Mausrad scrollt, bewegt sich nur der Balken, nicht aber die Liste (Regisseur-Liste im Supermarkt, aber auch Handbuch)
* Scrollen mit Mausrad geht im Handbuch nicht
* wenn "Langer Klick" aktiv ist und man den Scroll-Positions-Indikator hoch- und runterzieht, geht hinterher das Popup zu (Regisseur-Liste im Supermarkt)
* wenn "Langer Klick" aktiv ist und man über die Scroll-Pfeil-Buttons blättert, geht hinterher das Popup zu (Regisseur-Liste im Supermarkt)

**Comment by GWRon** [comment]
OK schau ich mir an.

Jedes Widget implementiert"onMouseScrollWheel" - hab ich wohl uebersehen, drauf zu reagieren (aehnlich der Listen).

**Comment by GWRon** [comment]
Hmm... hat es beim Merge und dem ganzen Cherry-Pick was uebersehen? Das ging eigentlich alles - hab ich ja mehrfach probiert. Handbuch scrollt nun wieder - die Scrollleisten noch nicht.

Fix kommt heute Abend.

**Comment by GWRon** [comment]
Die Scroller setzen normalerweise "longclicked" schon zurueck - nur wird nach dem GUI-Umbau der Bereich nicht mehr von TGUIScroller sondern vom dort drin genutzten TGUISlider verwaltet - ergo versucht das falsche Widget, da was zu machen.
