### ISSUE TITLE
Potential Drehbücher (Studio)

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#290]
Nachfolgeticket #205.
Die Puntke Potential und xpmod müssen noch bearbeitet werden. Offen für die Version 0.7 wäre, ob das Potential des Drehbuchs im Studio ausgeblendet werden sollte, bis die Ermittlung des Werts korrigiert ist. Persönlich fände ich das besser.

**Comment by GWRon** [comment]
Ich wuerde das Potential fuer die 0.7 drin lassen. Ich hab jetzt keine "abstrusen Werte" in den generierten Drehbuechern gefunden - und es hat ja auch Auswirkungen.

Ist also nur eine Art "Balancing-Aufgabe" die spaeter noch zu erledigen ist.

**Comment by nittka** [comment]
Beim Überarbeiten der Datenbank habe ich bemerkt, dass das Potential ja auch eine Eigenschaft ist, die an der Drehbuchvorlage gesetzt werden kann. Hier fehlt mir noch etwas der Einblick, was die Auswirkung des Potentials betrifft.
Wie kommt denn ein Film an, der in allen Wertungen (critics, outcome, speed) 100% hat? Was passiert denn mit einer Vorlage, die dort auch überall 100% hat aber Potential=0; oder andersherum überall 0 aber Potential 100% (es ist so doof, dass es schon wieder Kult ist)?

**Comment by GWRon** [comment]
Potenzial ist was "draus machbar" ist. Ein Regisseur koennte also Werte verbessern...

Genaueres kann ich zuhause raussuchen.

**Comment by nittka** [comment]
Es findet schon eine Wertermittlung statt, im Datenblatt wurde aber der Wert aber nicht verwendet.
