### ISSUE TITLE
[Quote] Statistikbildschirm hat falsche Sendegebietszahlen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#291]
Rauxelerritter schrieb:
> Ich habe in diesem Spiel 2 Sendemasten (nach 5 Tagen). Für die wird ein Empfangsbereich von 1.69 Mio Zuschauern angegeben. Dann lief um 20 Uhr der Film "Schräges Duo" und ich hatte 1.61 Mio Zuschauer. Es wurde eine Quote von 44% angegeben. Als ich in die Detaileinblendung schaute, stand dort eine mögliche Zuschauerzahl von 3.32 Mio. Diese Zahl erklärt natürlich die Quote.
> Allerdings erschließt sich mir nicht, wie ich bei einem Sendegebiet von 1.69 Mio Empfängern, eine mögliche Zuschauerzahl von 3.32 Mio erreichen kann.
https://www.gamezworld.de/phpforum/viewtopic.php?pid=89319#p89319

![image](https://user-images.githubusercontent.com/2625226/105919895-b53b6080-6036-11eb-881d-643a88602172.png)

**Comment by nittka** [comment]
Auch bei mir zeigt das Sendegebiet im Statistikblidschirm und die Gesamtbevölkerung auf der Quotenübersicht (Taste q) 8.7 Mio, obwohl nur 2 Sendemasten mit einer Gesamtreichweite von 2.2 Mio Zuschauern vorliegt.

**Comment by GWRon** [comment]
Schaetze es liegt an meinen Anpassungen der Senderkarte und der Quotenresultate.

Schau ich mir zuhause mal an.

**Comment by GWRon** [comment]
Hab halt die "Wieviele Zuschauer erreichen 1 und 2, 1 und 3 ... jeweils _gesamt_" aufsummiert, statt "wieviel erreichen 1 und 2 gleichzeitig und gemeinsam". Sorry :)
