### ISSUE TITLE
Öffnen der Personenauswahl setzt die Spielgeschwindigkeit auf 0

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#292]
Wenn man im Supermarkt eine Rolle besetzen will, wird aktuell bei Öffnen des Auswahl-Popups die Spielgeschwindigkeit auf 0 gesetzt. (Besteht hier ein Zusammenhang mit dem Tastatur-Scrollen?)

**Comment by GWRon** [comment]
Hmmm in bestimmten Bildschirmen wird die Geschwindigkeit reduziert (siehe Optionen). Sollte dort aber glaube nicht so sein.

**Comment by GWRon** [comment]
OK ... das passiert, da bei Modalfenstern pausiert werden soll ... Vorrangig war das fuer Fehlermeldungen oder Meldungen wie "Nicht genug Geld" der Fall.

Koennten wir wohl auch einfach ... rausmachen.
Oder aber, wir geben den Modalfenstern die Moeglichkeit die Pause selber "festzulegen".
