### ISSUE TITLE
Listen-Scrollen und Spielgeschwindigkeit

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#295]
Wenn man aktuell mit den Pfeiltasten durch die Personenliste im Supermarkt scrollt (analog Nachrichten im Nachrichtenstudio), wird gleichzeitig die Spielgeschwindigkeit geändert. Das ist unerwartet bis problematisch.

Neben diesem "Hauptproblem" gibt es verwandte Punkte.
* ist es frameworkseitig umsetzbar, dass Tastaturscrollen prinzipiell funktioniert und nicht für jede Liste einzeln umgesetzt werden muss (z.B. Nachrichtenarchiv im Büro, Sendemastenliste)
* ist es frameworkseitig umsetzbar, dass wenn eine Liste im Focus ist, die Pfeiltasten nicht mehr zur Änderung der Spielgeschwindigkeit führen)
* Im Supermarkt werden die Details zur Person angezeigt die unter dem Mauszeiger ist (Hover). Wenn man nun eine Person sucht, indem man mit den Pfeiltasten durch die Liste gehen möchte, werden dadurch nicht immer die Daten der "selektierten" Person angezeigt. Das liegt daran, dass sich ggf. die Position des selektierten Eintrags verschiebt. Lösungsansatz 1: Setzen des Mauszeigers beim Tastaturscrollen. Lösungsansatz 2 (für diesen Fall): Details werden auch angezeigt, wenn ein Eintrag selektiert ist (dann kann man mit der Maus die erste Person wählen, sie dann wegbewegen und mit den Tasten navigieren)

**Comment by GWRon** [comment]
An sich sollte man scrollen koennen, wenn die Liste die Option dazu hat bzw es nicht deaktiviert... Und Fokus hat.


Pfeiltasten...ja gaenge, wenn man ueberprueft ob der Guimanager.GetFocus() zurueckliefert 


Personen...ja das laesst sich auch machen...aber dazu muesste man wohl auch einen time-Wert speichern, damit man weiss was "neuer" ist...die Selektion oder das Hovern.
Das neueste ist dann als Datenblatt anzuzeigen.

**Comment by GWRon** [comment]
| ist es frameworkseitig umsetzbar, dass wenn eine Liste im Focus ist, die Pfeiltasten nicht mehr zur Änderung der Spielgeschwindigkeit führen)

Erledigt in 365084e146e4e145fa255921c2ae207e3a46afad

**Comment by GWRon** [comment]
So ... zum letzten Punkt.
Mein Vorschlag (den ich gleich ausprobieren werde) ist:
- Select-Listen speichern die Zeit der letzten "Auswahl"
- MouseManager speichert Zeitpunkt letzte Mausbewegung
- der "aktuellere" Vorgang hat dann Prioritaet (Maus bewegen und es springt "zurueck" auf den "Mauscursor-Eintrag")

**Comment by GWRon** [comment]
So ... der Punkt waere nun auch drin - mit Commit 4ae801bb445cafb7e9577e0f353d2d81019246bc

**Comment by nittka** [comment]
Personenliste im Supermarkt funktioniert nun prima.

Das Tastatur-Scrollen bei den anderen Listen klappt scheinbar noch nicht ohne Probleme. Meine Vermutung ist, dass das mit dem Focus zusammenhängen köntne. Zumindest im Nachrichtenstudio geht das Scrollen jetzt nur, wenn man in "korkfarbenen" Bereich zwischen Nachrichten-Item und Scrollbar klickt.

Bei den Nachrichten im Nachrichtenarchiv (Büro) geht es gar nicht und auch bei den Sendern habe ich es nicht hinbekommen.

**Comment by GWRon** [comment]
Das geht immer nur dann, wenn der Fokus gesetzt wird - oder man sich in dem Bildschirm "sicher" ist, dass es eben diese Liste wird - und dann immer wieder den Fokus automatisiert setzt.

An sich ist das hier eh ein "Maus"-Spiel und die Cursor-Scrollerei empfinde ich nicht als sonderlich notwendig. Im Gegensatz zur Maus (die gleichzeitig den Fokus setzt) ist eine Cursortaste halt ... etwas "unspezifischer".

**Comment by nittka** [comment]
Kein Widerspruch.
Bei der Personenauswahl, war mir das Tastatur-Scrollen sehr wichtig, da das Durcharbeiten der Kandidaten mit der Maus für mich extrem nervig ist. Mit Pfeiltaste runter kann ich sicher sein, dass ich jeden Kandidaten einmal gesehen habe.

Man muss als Spieler nur aufpassen, dass man nicht glaubt, mit den Pfeiltasten scrollen zu können, das dann aber doch nicht geht und man bei Versuch aber die Spielgeschwindigkeit "kaputt" gemacht hat. In der Nicht-Dev-Variante ist aber auch das weniger relevant.

Von mir aus kann das Ticket damit geschlossen werden, außer Du hast noch Punkte, die Du anpassen möchtest.

**Comment by GWRon** [comment]
Ich glaube github fuegt Mailantworten auf issue-mails nicht mehr automatisch an ...



Zwecks Fokus ... man kann ja nichtmal auf "Maus hover" umstellen (also immer das scrollbar machen, wo die Maus drueber ist), da fuer den Spieler ja nicht immer ersichtlich ist, was eine "Liste" (bzw GUIwidget) ist -- und er eventuell nur 10% vom Bildschirm fuer "ohne Widget" haette.

Zwecks "dev keys" - ja. Wenn die ausgestellt sind, hilft das sicherlich. Der "Tab"-Dev-Panel-Bereich kann ja eventuell eh einige der Dev-Shortcuts uebernehmen (wie "T" fuer Terroristen losschicken :)).

**Comment by GWRon** [comment]
hier eine Mail noch von gestern:

> An sich sollte man scrollen koennen, wenn die Liste die Option dazu hat bzw es nicht deaktiviert... Und Fokus hat.

> Pfeiltasten...ja gaenge, wenn man ueberprueft ob der Guimanager.GetFocus() zurueckliefert

> Personen...ja das laesst sich auch machen...aber dazu muesste man wohl auch einen time-Wert speichern, damit man weiss was "neuer" ist...die Selektion oder das Hovern.
Das neueste ist dann als Datenblatt anzuzeigen.

**Comment by nittka** [comment]
Für konkrete neue Probleme wird ein neues Ticket aufgemacht.
