### ISSUE TITLE
zweites Zurückstellen in Drehbuchagentur nicht möglich

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#296]
Wenn man ein Drehbuch kauft und in den Koffer packt, kann man es einmal zurückstellen. Wenn man es sofort wieder kauft, kann man es danach nicht wieder aus dem Koffer nehmen.

Oh: und man kann sie dann auch im Studio nicht aus dem Koffer nehmen, um sie zu produzieren.

**Comment by GWRon** [comment]
Schau ich mir dann gleich an.
