### ISSUE TITLE
Drehbuechervariablen + Lokalisierung falscher Fallback

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#297]
scripttemplate-random-ron-subtilehumor01
und 
scripttemplate-random-ron-horror01

Sorgen fuer "deutsche Titel" und teils "deutsche Beschreibung" wenn auf englisch gespielt wird.
Scheinbar passiert das, weil der Titel aus Variablen besteht, die wiederum Variablen enthalten - irgendwo wird da dann die LocaleID "uebernommen", statt die angeforderte ID beizubehalten.

**Comment by GWRon** [comment]
Der Fehler ist - denke ich, dass die Eintraege ("title", "description") nur als "de" vorliegen. title/description wird als `TLocalizedString` eingelesen - und hat dann nur den "de"-Eintrag.

"title.get()" liefert also auch auf Englisch den "de"-Eintrag zurueck. Soweit kein Problem. Allerdings wird beim Ersetzen der Platzhalter jeder Eintrag des `TLocalizedString` durchgegangen und dann entsprechend der dort zugewiesenen Sprache ("de") versucht alles zu ersetzen.


Eine Loesung waere nun, dass man dem Funktionsaufruf noch die aktuell genutzte Sprache mitgibt - bzw eine Liste an "zu unterstuetzenden Sprachen". Und die wird dann als Eintrag noch hinzugefuegt (auch wenn ihr Fehlen dann "de" abruft - als Fallback).

Eine andere - ich denke das waere die bessere - ist es, alle Variablen durchzugehen und zu schauen, welche Sprachen da definiert sind. Gibt es also "en"-Variablen, gibt es wohl doch "irgendwo" im Wirrwarr Unterschiede ... und immer wenn die eigene Sprache fehlt, ist der Fallback zu nutzen.

Eine weitere ist: einfach alles "dumm doof" hinschreiben, auch wenn es an sich eine "Dublette" ist. Also wirklich fuer jede Sprache einen Eintrag bei allen Variablen etc anlegen (selbst bei identischen Inhalten). Das entspricht am ehesten dem "Datenbank"-Gedanken. Anstatt zu versuchen, alles "smart/intelligent" zu loesen... einfach stupide hinschreiben.

**Comment by nittka** [comment]
Ein paar en-Einträge hattest Du ergänzt, an andere rangeschrieben, dass die deutsche Variante ausreicht. Ich habe noch nicht ganz die Systematik verstanden, in welcher Konstellation es einen Fehler gibt. 
Ohne Testspielen nur durch Blick auf die Datenbank sieht scripttemplate-random-ron-animalseries01 noch (besonders) gefährdet aus. Die Einzelfolgen haben nur deutsche Titel, die jeweiligen Variablen liegen aber z.T in beiden Sprachen vor (vielleicht aber auch nicht, weil nur die Tiername zweisprachig sind).

Weitere Nicht-Dopplungen (Anzahl, Personenname nur in de) gibt es noch in scripttemplate-random-ron-subtilehumor01, scripttemplate-random-ron-eroticmovie1, scripttemplate-random-ron-horrormovie1, scripttemplate-random-ron-show1.

In den anderen Datenbankdateien ist mir kein Problem in diese Richtung aufgefallen.
Wenn Du also bei Deinem Commit schon alles für diese Datei geprüft hattest, kann dieses Ticket zugemacht werden.

**Comment by GWRon** [comment]
Es kann durchaus sein, dass die Aenderungen an den TLocalizedString etc irgendwo was zerbrochen haben.

An sich sollte es aber immer so sein:
- gebe mir den lokalen Wert fuer einen Key
- dieser Wert kann Platzhalter beinhalten und ist "locale"-unabhaengig (also de, en,..., ist egal)
- nun werden Platzhalter aufgefuellt, die "locale" werden wieder beachtet (also de, en, ...)


Entsprechend sollte es eigentlich alles funktionieren. Ausser...irgendwas graetscht dazwischen.

Ich schau mir das heut abend Zuhause mal an

**Comment by GWRon** [comment]
Ich habe ueberlegt, ob es praktisch waere, fuer "angefragte" aber nicht gefundene Lokalisierungen, den Fallback "reinzukopieren". Damit muessten ja beim Ersetzen der Variablen die bspweise "englischen" Texte ploetzlich da sein - und mit englischen Platzhaltern ausgetauscht werden koennen.

Dann braeuchten keine Parameter mit uebergeben werden. Allerdings fallen dann halt mehr "Strings" an, die eigentlich nicht wirklich gebraucht wuerden.

**Comment by GWRon** [comment]
```XML
		<scripttemplate product="1" licence_type="1" guid="scripttemplate-testlocales">
			<title>
				<de>%TEST%</de>
			</title>
			<description>
				<de>%DESCRIPTION%</de>
			</description>

			<variables>
				<test>
					<de>%TEST2A%|%TEST2B%</de>
				</test>
				<description>
					<de>%DESCRIPTION2A%|%DESCRIPTION2B%</de>
				</description>
				<test2a>
					<de>TEST2A_DE1|TEST2A_DE2</de>
					<en>TEST2A_EN1|TEST2A_EN2</en>
				</test2a>
				<test2b>
					<de>TEST2B_DE1|TEST2B_DE2</de>
					<en>TEST2B_EN1|TEST2B_EN2</en>
				</test2b>
				<description2a>
					<de>DESCRIPTION2A_DE1|DESCRIPTION2A_DE2</de>
					<en>DESCRIPTION2A_EN1|DESCRIPTION2A_EN2</en>
				</description2a>
				<description2b>
					<de>DESCRIPTION2B_DE1|DESCRIPTION2B_DE2</de>
					<en>DESCRIPTION2B_EN1|DESCRIPTION2B_EN2</en>
				</description2b>
			</variables>

			<jobs>
				<job index="0" function="1" required="1" />
			</jobs>

			<genres maingenre="7" />
			<blocks min="2" max="3" slope="40" />
			<price min="8000" max="12000" slope="40" />
			<potential min="50" max="70" slope="45" />
			<outcome min="25" max="35" slope="40" />
			<review min="45" max="65" slope="40" />
			<speed min="35" max="65" slope="50" />
		</scripttemplate>
```

test:
```Blitzmax
local scriptTemplate:TScriptTemplate = GetScriptTemplateCollection().GetByGUID("scripttemplate-testlocales")
Local script:TScript = TScript.CreateFromTemplate(scriptTemplate, True)


print "known raw-title and raw-description:"
print script.title.ToString() '.Replace("~n", "  -  ")
print script.description.ToString() '.Replace("~n", "  -  ")
'For local sub:TScript = EachIn script.subScripts
'	print "- " + sub.title.ToString().Replace("~n", "  -  ")
'Next


print "tests:"
TLocalization.SetDefaultLanguage("en")
TLocalization.SetCurrentLanguage("de")
print "default: en   current: de" +"  | " + LSet(script.title.Get(), 40) + " | " + script.description.Get().Replace("~n", "~~n")

TLocalization.SetDefaultLanguage("en")
TLocalization.SetCurrentLanguage("en")
print "default: en   current: en" +"  | " + LSet(script.title.Get(), 40) + " | " + script.description.Get().Replace("~n", "~~n")

TLocalization.SetDefaultLanguage("de")
TLocalization.SetCurrentLanguage("de")
print "default: de   current: de" +"  | " + LSet(script.title.Get(), 40) + " | " + script.description.Get().Replace("~n", "~~n")
```

Ausgabe:
```
known raw-title and raw-description:
de: TEST2B_DE1
de: DESCRIPTION2A_DE2
tests:
default: en   current: de  | TEST2B_DE1                               | DESCRIPTION2A_DE2
default: en   current: en  | TEST2B_DE1                               | DESCRIPTION2A_DE2
default: de   current: de  | TEST2B_DE1                               | DESCRIPTION2A_DE2
```

Denke mit dem Testszenario sollte man das gewuenschte Verhalten ueberpruefen koennen.

**Comment by GWRon** [comment]
```
[16:47:10] LOAD DBG | TGETSTATIONMAPCOLLECTION().CREATEPOPULATIONMAP: calculated a population of:80339766 in 16ms
[16:47:10] LOAD DBG | TGETSTATIONMAPCOLLECTION().ASSIGNPRESSUREGROUPS: Assigned pressure groups to sections of the map not containing predefined ones.
[16:47:10] LOAD     | TDATABASE.LOAD(): Loaded DB "../res/database/Default/database_people.xml" (version 3). Found 0 series, 0 movies, 845/265 basePersons/persons, 0 advertisements, 0 news, 0 achievements. loading time: 145ms
[16:47:10] LOAD     |                 : Loaded DB "../res/database/Default/database_scripts.xml" (version 3). Found 0 series, 0 movies, 0/0 basePersons/persons, 0 advertisements, 0 news, 0 achievements. loading time: 28ms
[16:47:10] LOAD     |                 : Loaded DB "../res/database/Default/user/ronny.xml" (version 3). Found 0 series, 23 movies, 2/0 basePersons/persons, 0 advertisements, 11 news, 0 achievements. loading time: 12ms
Template:
known raw-title and raw-description:
de: %TEST%
de: %DESCRIPTION%
Script:
known raw-title and raw-description:
de: TEST2A_DE1
en: TEST2A_EN1
de: DESCRIPTION2B_DE2
en: DESCRIPTION2B_EN2
tests:
default: en   current: de  | TEST2A_DE1                               | DESCRIPTION2B_DE2
default: en   current: en  | TEST2A_EN1                               | DESCRIPTION2B_EN2
default: en   current: fr  | TEST2A_DE1                               | DESCRIPTION2B_DE2
default: de   current: de  | TEST2A_DE1                               | DESCRIPTION2B_DE2
```
