### ISSUE TITLE
Kosten Satellit/Kabel

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#300]
Die "Verkaufskosten" für Satelliten und Kabelverträge sehen seltsam aus. Mir scheint mit der Ermittlung von Vertragsrestlaufzeit/Kündigungskosten stimmt was noch nicht.

[kostenSat.xml.tar.gz](https://github.com/TVTower/TVTower/files/6011430/kostenSat.xml.tar.gz)

**Comment by nittka** [comment]
Die Berechnung des Verkaufspreises beinhaltet gerade bei Kabelverträgen und Satelliten ein Einkommen aus dem möglichen Verkauf von Hardware. Das verstehe ich nicht. Die Hardware gehört ja dem "Vermieter". Warum sollte ich bei Vertragsabbruch etwas davon bekommen. Meiner Ansicht nach müsste der Einkommensanteil beim GetSellPrice für Kabel und Satellit komplett entfallen und nur eine Stornogebühr abhängig von der Restvertragslaufzeit gezahlt werden.

Auch der Verkaufserlös für Antennen ist "fraglich". Warum sollte man für eine alte Antenne auch noch 75% des Preises zurückbekommen. Eigentlich müsste man Rückbau-/Verschrottungs-/Entsorgungskosten zahlen.

**Comment by GWRon** [comment]
Also der Grundgedanke war, dass man fuer jeden "Uplink" die Hardware bereitstellt - und die eben wieder verkauft (Satellit/Kabel).
Die Hoehe ist natuerlich diskussionswuerdig.

Man kann auch argumentieren, dass sich darum der Kabelanbieter kuemmert ("Kanaleinspeisung") und das in der Miete enthalten ist.


Antennen: Auch hier kann die Hoehe ausdiskutiert werden. Ich hatte anfaenglich auch an Verschrottungskosten etc gedacht - auch im Hinblick auf Modernisierung (Stichwort DVB-T und Co).

**Comment by nittka** [comment]
Verstehe. Ich hatte mich nur gewundert, warum ich Tausende für einen Vertragsabbruch zurückbekommen sollte. Bei den laufenden Kosten für Satellit und Kabel empfinde ich es als verständlicher, wenn diese die Uplink-Hardware beinhalten.

Bezüglich der Antennen: Wenn es schon Geld zurück gibt, dann aber wohl nicht mindestens 75% des Kaufpreises - eher höchstens 75% und je nach Alter immer weniger.

**Comment by GWRon** [comment]
Da hast Du recht ... 75% ist n bissl "viel". Das basierte wohl noch auf der Rechnung bei den anderen Varianten (Kabel, Satellit) bei der die Formel bei den Hardwarekosten angewendet wurde.

Hier sollte wohl von weniger ausgegangen werden (viel "Stahl", wenig "Elektronik").

Koennen wir gern runterschrauben - bzw den Alterseinfluss erhoehen.

**Comment by nittka** [comment]
Gelöst durch #304. Wenn Erweiterungen an den Spielstärke-Leveln gemacht wird, können die Faktoren dann noch variiert werden.
