### ISSUE TITLE
Studio kann betreten werden, während Vorproduktion läuft

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#302]
(aktueller Master-Stand) Während die Vorproduktion zur Morgen-Show läuft, kann das Studio betreten werden.

Außerdem fällt auf, dass die Zeit für die Vorproduktion extrem kurz ist. Zwar wird als Basiszeit 60 Minuten angesetzt, aber wahrscheinlich wegen weiterer Faktoren verkürzt sich das auf wenige Minuten. Das erscheint unrealistisch.
Und während der Ausstrahlungszeit müsste das Studio dann eigentlich auch blockiert sein (2 Stunden vorher bis 2 Stunden hinterher für Auf- und Abbauarbeiten).
Wenn gerade eine andere Produktion in dem Studio läuft, müsste sich die Drehzeit entsprechend erhöhen.

**Comment by GWRon** [comment]
Hmm fuer das Issue hab ich gar keine Mail bekommen. 


Ja ... also die Vorbereitungszeit ... koennte buggy sein (eventuell noch basierend auf der Zeitumstellung von Float auf Long).


Die Blockade hingegen ... damit wuerden wir einen Rattenschwanz an Aufgaben bekommen:
- Kann eine Produktion gestartet werden, wenn eine Live-Produktion "geplant" ist?
- Werden Produktionen die in einem solchen Studio stattfinden bereits 2 Stunden "vor" _eventuellem_ Live-Programm unterbrochen? Heisst: zweiteilen wir das - Die Planung verlaengert andere Produktionen um 2 Stunden, die Ausstrahlung dann nochmals um die eigentliche Live-Sendung + 2 Bloecke Nachbereitung?
- Was ist mit Liveprogramm 2 Bloecke um 20 Uhr  - und gleich darauf Liveprogramm um 22 Uhr? Braeuchte ja 2 Studios - oder?
- Was ist mit Liveprogramm einer "Serie/Shows" - die braeuchten ja dann nur einmal die "Vorbereitung" (Kulissenaufbau etc) und koennten 20 sowie 22 Uhr produziert werden
- Was ist wenn das Studio nach der Vorproduktion aber _vor_ Ausstrahlung verkauft/gekuendigt wird?

An sich stehe ich dem "wird derweilen blockiert" ja positiv gegenueber - einfachste waere wohl, dass zumindest "andere im Studio ablaufende Produktionen" (dazu muesste dann das Liveprogramm hinterlegen, in WELCHEM Studio es stattfindet - bzw wird versucht ein "freies, geeignetes" zu finden) fuer die Zeit der Ausstrahlung "pausieren" (also pro angefangene "Live-Stunde" wird die Produktion um +60 Minuten verlaengert).

**Comment by nittka** [comment]
Ich denke auch, dass der Fehler eine Folge der Zeitumstellung ist - mein Fix hat nur nicht den vorherigen Zustand wiederhergestellt.

Das Thema Studio und Live-Ausstrahlung war mir nur eingefallen, da Du mal gesagt hattest, dass ein zu großes Studio bei einer Show dann leer aussieht und zu schlechteren Werten führen könnte. Wenn aber für die Ausstrahlung gar kein Studio gebraucht wird...

Wie wäre es mit folgender Variante:
* Wenn eine Live-Ausstrahlung erfolgt, wird ein leeres Studio blockert (und man wird ggf. rausgeschmissen).
* Wenn es kein leeres Studio gibt, wird ein anderes blockiert und die dort laufende Produktion verlängert sich.
* Wenn es gar kein Studio gibt, kommt es zum Sendeausfall!
* Das Studio bleibt auch nach der Ausstrahlung noch eine Stunde blockiert (Aufräumarbeiten).
* Die Vorbereitungszeit ignorieren wir.

Die Studiogröße kann für eine Live-Show keine Rolle spielen, solange wir nicht das Studio der Vorproduktion festhalten (ist im Moment aber vielleicht auch nicht nötig). Bzgl- Vorbereitungszeit ignorieren: das "Nichtverschiebenkönnen" von geplanten Programmen ist ja prinzipiell vorgesehen (Startshow). Wenn man also eine Live-Produktion mehr als eine Stunde vor dem Senden planen müsste (ab dem Stichzeitpunkt kann sie dann nicht mehr verschoben werden), könnte man auch die Vorbereitungszeit im Studio festlegen. Da würde ich aber erstmal den Ball flach halten.

Ach ja, und wenn man eine Show nicht sendet, sollten dennoch Zahlungen nötig sein - Moderator, Crew usw. hatten ja Aufwände und waren auf Standby, eine Aufwandsentschädigung wäre also gerechtfertigt.

**Comment by GWRon** [comment]
> Wenn es gar kein Studio gibt, kommt es zum Sendeausfall!
das muss unbedingt ins Datenblatt rein ("Kein freies Studio. Sendeausfall droht")

>Aufraeumarbeiten
Das wuerde ja bei jeglicher Produktion mit anfallen ... also normalerweise sollte eine "normale" Produktion abgeschlossen sein ("Film verfuegbar") aber die Folgeproduktion noch nicht angefangen (ausser bei "Episoden" ?) haben. Also da braucht es ja auch die "Aufraeumarbeiten" (die muss auch der Tooltip vom Raum mit beinhalten).


> Aufwand
Hmm .. man kann sie ja auch "nicht live" senden .. die Kosten sollten also so oder so zum (spaetesten) "Live-Zeitpunkt" anfallen.

**Comment by nittka** [comment]
Bei einer normalen Produktion sind die Aufräumarbeiten ja schon in der Drehzeit mit drin (zumindest ist die Drehzeit lang genug dafür). Bei einer Show reicht die Ausstrahlungszeit allein für das Aufräumen aber nicht mit aus.

Ich habe noch gar nicht ausprobiert, was bei einer Show passiert, die ich nicht zum "erlaubten" Ausstrahlungstermin sende. Ich war davon ausgegangen, dass sie dann verfällt. Ist dann nur die Quotenberechnung anders?

**Comment by GWRon** [comment]
Was ich damit meine ist:
Serie mit 2 Episoden geplant
Jede Episode hat eine Produktionszeit von 4 Stunden
Start 14:00

Derzeit ist 18:00 die erste Episode produziert und direkt verfuegbar. 18:05 oder so startet die zweite Produktion und ist 22:05 fertigproduziert und verfuegbar.
Ein weiter eingeplanter Film wuerde 22:10 gestartet werden


Wenn wir nun aber generell eine Aufraeumarbeit notwendig erachten, aendert es sich folgend:
18:00 die erste Episode produziert und direkt verfuegbar. 18:05 startet die zweite Produktion (keine Aufraeumarbeiten noetig - gleiche Serie) und ist 22:05 fertigproduziert und verfuegbar.
Der darauf eingeplante Film wuerde 23:05 seine Produktion starten.

Also : bei "gleichem Material" keine Aufraeumpausen - erst "am Ende" (wenn keine weiteren Episoden vorbereitet waren). Bei Wechsel des Materials - Aufraeumpause.

**Comment by nittka** [comment]
Das hatte ich schon so verstanden. Ich könnte aber auch ohne diese Anpassung leben.
Es läuft vielleicht auf dasselbe heraus, ist aber von der Herangehensweise... Angenommen in jeder Serienproduktion ist eine Aufräumzeit von einer Stunde (oder einer halben) eingerechnet. Wenn man nun mehrere Folgen direkt hintereinander produzieren lässt (alles geplante abdrehen), wüsste der Studioleiter, dass ein Aufräumen zwischen den Drehs nicht nötig ist. Die Aufräumzeit kann also entfallen und die Folge steht früher zur Verfügung.
Dreht man jede Folge einzeln, muss hinterher aufgeräumt werden, da der Studioleiter ja nicht wissen kann, dass es mit der nächsten Folge weitergeht.

**Comment by GWRon** [comment]
Der aktuelle Masterstand sollte das Problem beheben. Allerdings ist die hier hinterlegte Diskussion ja doch wichtig und interessant. Auflassen bis entgueltig geklaert, oder in einen neuen Thread/Issue ueberfuehren?

**Comment by nittka** [comment]
Folgende Sachen sind mir bei dem Fix aufgefallen
* Im Studio ist das Datenblatt-Feld für die Anzeige der Produktionszeit zu klein - es werden immer nur die Minuten angezeigt. D.h. auch bei einem Film steht dann 18m, obwohl die Produktionszeit 10h18m wäre
* für alte Spielstände mit schon gekauften Drehbüchern für Live-Shows passen die Zahlen nicht zusammen (Produktionszeit war 0) - zu ignorieren, problematischer ist eher, dass auch wenn man bei einem alten Spielstand die Morgenshow neu holt dasselbe Problem auftritt ("Inkompatibilität" der mit jedem Speichern persistierten alten Datenbank?)

Zum Thema Diskussion wann welche Kosten. Ich würde die Punkte im Ticket offenen Kosten Vorproduktion einfach nochmal zusammenfassen, auf dieses Ticket verlinken. Je nachdem was zu den beiden obigen Punkten sagst, kann dieses Ticket dann zugemacht werden.

**Comment by GWRon** [comment]
Ich weiss nicht inwieweit wir uns so grosse Sorgen machen muessen - die vordefinierte Produktionszeit war nur bei 2 Drehbuechern relevant ...

Aber man kann es auch reparieren und als "entfernen ab Version X" markieren...


Die Anzeige der Produktionszeit: dann stellen wir es auf einen anderen modi um ("da stuende dort dann "~10,5h") - bzw geben dem Feld mehr Platz.

**Comment by nittka** [comment]
Vordefinierte Produktionszeit: Ich habe kein Problem damit, es beim aktuellen Stand zu lassen. Ich wollte aber zumindest darauf hinweisen.
Ich würde dem Feld mehr Platz geben: "~10,5h" würde immer noch Probleme bereiten, wenn nur für 3 Zeichen Platz ist.

**Comment by GWRon** [comment]
Ich weiss auch nicht wie notwendig die Tilde ist...
