### ISSUE TITLE
Änderungen auf Hinweistafel werden nicht in den Fahrstuhlzielplaner übernommen

### ISSUE THREAD

**Issue by jukey** [TVTower/TVTower#305]
Wenn ein Anschlag auf eine der Botschaften angekündigt ist, ändern KI-Mitspielerja gern mal die Beschriftungen im Fahrstuhlzielplaner. Wenn ich selbst zur Hinweistafel im Erdgeschoss fahre und dort die Schilder tausche, fide ich diese Änderungen hinterher nicht im Fahrstuhlzielplaner.

Gut: Der Attentäter hält sich an die Konfiguration auf der Hinweistafel.
Schlecht: Ich selbst verliere im Fahrstuhlzielplaner den Überblick.

**Comment by GWRon** [comment]
Hmm also im Fahrstuhl sollte der Raumplan zu sehen sein...

Der wird nach Anschlaegen wieder korrigiert, sollte bis dahin aber Deine Aenderungen wiederspiegeln.

**Comment by jukey** [comment]
> Der wird nach Anschlaegen wieder korrigiert, sollte bis dahin aber Deine Aenderungen wiederspiegeln.

Es dauerte auch mehr als 24h bis nach dem Anschlag der Raumplaner wieder die wahre Belegung anzeigte.
Ich spiele einfach mal weiter und melde mich hier, wenn sich meine Beobachtung beim nächsten Attentat bestätigt oder widerlegt.

**Comment by GWRon** [comment]
Also ...
- Spielstart ... "strg links" + "r" -> Raumplan
- Schilder Psychiater und Chef Rot vertauscht
- raus aus dem Raum und auf die Fahrstuhltuer im Erdgeschoss geklickt
- Fahrplan klappt auf und zeigt folgendes Bild: 
![image](https://user-images.githubusercontent.com/2625226/111042146-2b0b5800-843c-11eb-902f-0dae053b3b36.png)

Soweit scheint es ja zu funktionieren. Zwecks "wahrer Belegung" (Reset) schau ich mir das auch noch an - vielleicht kann ich das auch in den Debug-Bereich ("Tab"-Taste) mit integrieren.

**Comment by GWRon** [comment]
Der Raumplan wird sofort nach einem Bombenanschlag zurueckgesetzt. Vielleicht verwechselst Du die Vornachrichten (Streit, Terrorist im Haus abgetaucht...) mit dem eigentlichen Attentat auf die VR oder FR Duban (bzw die falschen Zimmer).

Weiterhin wird jeden Tag um Mitternacht zurueckgesetzt ("Pfoertner erledigt seine Pflicht")

**Comment by jukey** [comment]
Ich habe folgendes gespeichertes Spiel verwendet:
- [bugreport.zip](https://github.com/TVTower/TVTower/files/6135620/bugreport.zip)

Nach `Strg`+`r` lande ich im Raumplan:
![raumplan](https://user-images.githubusercontent.com/295928/111045903-e63bed00-844c-11eb-90b0-84e6359db35d.png)

Ich habe die Schilder con 'Pförtner' und 'Bettys Büro' vertauscht und bin zu Fahrstuhl im EG gegangen: Beide Schilder waren entsprechend meiner Aktivität zuvor am Raumplan vertauscht. -> Korrektes Verhalten

Nun bin ich wieder zum Raumplan gegangen und habe 'Konsulat der VR Duban' und 'Wäscherei' getauscht. Dann bin ich wieder zum Fahrstuhl im EG und diesmal waren die Änderungen nicht zu sehen:
![fahrstuhl-eg](https://user-images.githubusercontent.com/295928/111047990-72e6ab00-844d-11eb-815f-a6b0e75b5a90.png)

Das Problem scheint also nur zu existieren, wenn ich den Raum 'VR Duban' tausche. Bitte lass mich wissen, wenn ich weitere Sachdienliche Hinweise liefern kann. :)

**Comment by GWRon** [comment]
In der Tat - also in Deinem Savegame kann ich das nachvollziehen - bei mir ist schon der Tausch "Betty <-> Pförtner" im Fahrstuhlplan nicht mehr zu sehen obwohl frisch im Raumplan umgestellt.

Da hab ich wenigstens n Ansatz zum genauer gucken.

**Comment by GWRon** [comment]
OK, also deine Anleitung hat dafuer geklappt. Und was ich interessant fand, ist dass der Raumplan was anderes anzeigte, als der Fahrstuhlplan. Die nutzen eigentlich die gleiche "Datengrundlage" - nur dass man bei dem einen nix "verstellen" kann. Hmm ... gibt mir was zum Gruebeln :-)

**Comment by jukey** [comment]
Ich glaube ich habe die Lösung gefunden:
Wenn ich Strg+r verwende und Schilder tausche klappt es.
Wenn ich den Shortcut **nicht** verwende und per Mausklick den Raumplan aufsuche, werden Änderungen **nicht** gespeichert.

**Comment by GWRon** [comment]
Nein, leider hilft das bei mir nicht. Da muss irgendwas anderes noch passieren ... da ich es nur selten "gebuggt" bekomme.

**Comment by GWRon** [comment]
OK also fuer mich nun "nachvollziehbar":
- Dein savegame einladen
- strg+r
- Raumplan und "Nachrichtenstudio Spieler rot" (an Position Archiv) vertauschen
- zum Fahrstuhl: korrekte Anzeige "ist vertauscht"
- wieder zum Raumplan (egal ob laufen oder mit strg+r)
- die beiden Schilder wieder vertauschen
- zum Fahrstuhl: erneutes Vertauschen wird nicht angezeigt (also noch alter Zustand).

**Comment by GWRon** [comment]
Fehler gefunden - Regression herbeigefuehrt durch eine kuerzliche Aenderung. Hab einfach vergessen, eine Cache-Liste zu leeren/zu entfernen (Cache fuer die "visuelle Sortierung").

**Comment by GWRon** [comment]
Wichtig auch: Die Terroristen, die beiden Pfänder Czwing und Czwang ... orientieren sich nur am Raumplan, die nutzen nicht den Fahrstuhlplan.

**Comment by jukey** [comment]
Vielen Dank für den Fix und gut zu wissen, dass der Raumplan ausschlaggebend für Terroristenund Pfänder ist! :-)
In welcher Version ist dieser denn enthalten? Und können Savegames mit neueren Versionen weiterverwendet werden?

**Comment by GWRon** [comment]
Im naechsten DevPatch wird er enthalten sein... kompatibel sind die Speicherstaende bisher noch ;-)
