### ISSUE TITLE
Raumbeschilderung wird bereits vor der Ankündigung eines Anschlags durch KI Spieler:innen geändert

### ISSUE THREAD

**Issue by jukey** [TVTower/TVTower#306]
## Schritte zur Reproduktion
1. Spiel mit min. einer KI starten und 
2. spielen, bis eines Tages die Beschilderung im Fahrstuhlziel-Planer angepasst durch ein:e KI-Mitspieler:in angepasst wurde

## Erwartung:
Es gibt eine Nachricht, die den Anschlag ankündigt und hilft zu verstehen, welches Raumschild umgehangen werden sollte

## Was wirklich passiert:
Est nach einigen Stunden taucht in den Nachrichten die erste Information zu den Anschlagsplänen auf.

## Mögliche Lösung des Problems:
- Die Nachricht, dass ein Anschlag geplant ist, erscheint immer kurz nach Mitternacht des betroffenen Tages
- Die Schilder werden auch durch die KI erst 'umgehangen', wenn eine entsprechende Nachricht vorliegt

**Comment by GWRon** [comment]
Warum muss die KI warten? Die KI tauscht auch einfach mal so die Schilder aus. Also sozusagen zum Verwirren und als Prophylaxe.

Auch gibt es neben den Terroristen andere Typen die den Raumplan nutzen. Die Beamten, die FSK-18-Tagesausstrahlungen  ahnden etc

**Comment by jukey** [comment]
> Warum muss die KI warten? Die KI tauscht auch einfach mal so die Schilder aus. Also sozusagen zum Verwirren und als Prophylaxe. 

Ich empfinde es also logischer, wenn alle Spieler - ob KI oder Real, die gleichen Informationen vorliegen haben (können). 
Es ist aber natürlich auch kein Drama, wenn die KI einfach mal so die Raumbelegung ändert. Dann sollte sie es aber hin und wieder auch dann tun, wenn kein Anschlag zu erwarten ist.

> Auch gibt es neben den Terroristen andere Typen die den Raumplan nutzen. Die Beamten, die FSK-18-Tagesausstrahlungen ahnden etc

Das stimmt natürlich, war in meinem Spiel zu diesem Zeitpunkt aber nicht der Fall.

**Comment by GWRon** [comment]
Sie macht die Planaenderungen auch mal zufällig. Sie hat keine anderen Informationen als der Spieler. Sie entnimmt die Information auch den News (da ist ein spezielles auswertbares Stichwort neben der Nachrichr) hinterlegt.

Das Verwirrungstiften ist eine sehr niedrig priorisierte Aufgabe der KI.

**Comment by GWRon** [comment]
Falls der Fall damit fuer dich geklaert ist, mach hier ruhig zu - ansonstein einfach Meinungen/Fragen zum Thema hier reinstellen und ich versuche sie zu beantworten.

**Comment by jukey** [comment]
Vielen Dank für deine Erläuterungen. Mir genügt es vollkommen als Erklärung, dass die KI keine anderen Informationen als der menschliche Spieler besitzt.
