### ISSUE TITLE
Linux - Ubuntu 20.04: Fehlendes Anwendungs-Icon während Ausführung im 'Dock'

### ISSUE THREAD

**Issue by jukey** [TVTower/TVTower#307]
Ich spiele TvTower unter Ubuntu 20.04.

Wenn das Spiel läuft sehe ich in der Icon-Leiste ('Dock') nur ein leeres, schwarzes Anwendungs-Icon.
Ich kann dieses auch nicht als Favorit permanent in der Icon-Leiste verankern.
Ich vermute esliegt daran, dass ich das Spiel per binary aus dem Dateimanager starte und es keine '.desktop' Datei gibt, die normalerweise verwendet werden um Apps und ihre Meta-Infromationen bereitzustellen?

**Comment by GWRon** [comment]
Ja ich denke Deine Vermutung koennte richtig sein. Falls Du da beim Herumspielen was herausfindest, kannst Du mir dadurch gerne (aus-)helfen.

**Comment by nittka** [comment]
Gehe ich recht in der Annahme, dass für die .desktop-Datei die absoluten Pfade (normalerweise Installationspfade) bekannt sein müssten. In diesem Fall könnte eine generische Lösung schwierig sein, da TVTower ja nicht installiert sondern einfach entpackt und gestartet wird. Man kann ja auch mehrere Programmversionen parallel auf dem Rechner haben und spielen (und die Programmverzeichnisse umbenennen und verschieben). D.h. die .desktop-Datei muss vom Nutzer nachgepflegt werden.

**Comment by GWRon** [comment]
Jein ... also es gibt noch ein paar Variablen die man nehmen kann ..."%k" wuerde den "Pfad/dieDesktopDatei.desktop" zurueckgeben.
Gibt noch paar mehr aber .. .hmm

Was wir machen koennten: 
- TVTower_Linux64 legt selbst eine .desktop-Datei an und enthaelt den aktuellen Pfad
- Ein Bash/Shell-Script legt die Datei an ...

**Comment by GWRon** [comment]
OK, habe die Binary so erweitert, dass versucht wird eine "TVTower.desktop" anzulegen und diese mit dem aktuellen Pfad zu fuellen.

Also bei mir sieht das dann so aus:
```

[Desktop Entry]
Name=TVTower v0.7.0
Exec=/home/ronny/Arbeit/Projekte/TVTower/Current/TVTower_Linux64
Icon=/home/ronny/Arbeit/Projekte/TVTower/Current/tvtower.png
Type=Application
Categories=Games;
```

![image](https://user-images.githubusercontent.com/2625226/111041472-a1a65680-8438-11eb-9380-f8a9abf299bf.png)


Die Datei solltest Du dann in Dein Dock ziehen koennen.

**Comment by GWRon** [comment]
Kannst du dir mal die Desktop-Datei kopieren (und die Pfade anpassen) - und mir sagen, ob Dein Dock dann ein Icon anzeigt? Brauch ich hier nicht erst eines der Ubuntus virtualisieren.

**Comment by jukey** [comment]
Ich habe die .desktop Datei erzeugt und die Pfade angepasst. Ich konnte sie jedoch nicht direkt ausführen (auch nicht mit Änderung der Rechte). Ich habe sie dann einfach in den System-Ordner mit allen möglichen anderen .desktop Anwendungen kopiert:

```
sudo cp ~/Downloads/TVTower_v0.7.0_20210210/TVTower.desktop /usr/share/applications/ 
```

Jetzt taucht TVTower aus, sobald ich die 'Windows-Taste' drücke und danach 'tvt' eingebe:
![image](https://user-images.githubusercontent.com/295928/111044756-c86d8880-844a-11eb-811f-a8c96c6e07e9.png)

Es wird hier das TVTower.png verwendet, wie im .desktop file angegeben. Bei mir sieht es so aus:
![tvtower](https://user-images.githubusercontent.com/295928/111044787-f226af80-844a-11eb-9fa2-c23bf25b33fb.png)

Das Icon im Dock, scheint jedoch die Datei TVTower.ico zu sein, die bei mir quasi 'leer' oder durchsichtig zu sein scheint:
[TVTower.zip](https://github.com/TVTower/TVTower/files/6135607/TVTower.zip) (.ico Datein scheint man auf github nicht als Bild einbinden zu dürfen).

Ich verwende die Version aus diesem .zip:
`TVTower_v0.7.0_20210210.zip`, die ich vor einigen Tagen im Downloadbereich der TVTower Webseite gefunden habe.
Zumindest hier im Repository scheint die .ico Datei jedoch eine andere zu sein und mit der in deinem Beispiel übereinzustimmen.

**Comment by GWRon** [comment]
Die ".ico" ist die gleiche (nicht mit dem Bildbetrachter oeffnen, da kommt nur Pixelmatsch raus, da die ICO mehrere Groessen von Symbolen beinhaltet - in GIMP sieht man das etwas "besser").

Warum es aber das .ico und nicht das in der .desktop-Datei definierte PNG-Bild nimmt... weiss ich nicht.

Das Icon (bzw. eigentlich die PNG) aus meinem Screenshot ist neuer - das hab ich vorhin erst gespeichert.


Bei mir kam beim ersten Doppelklick auf die .desktop-Datei (im Dateimanager) die Nachfrage, ob ich die Datei als ausfuehrbar markieren woellte. Danach half der Doppelklick zum sofortigen Starten der Applikation.

**Comment by jukey** [comment]
Bei mir öffnen sich .desktop-Dateien immer mit gedit. Ich habe versucht dieses Verhalten zurückzusetzen, bin aber gescheitert. Ich werde bei Gelegenheit mal [hier](https://wiki.ubuntuusers.de/.desktop-Dateien/) nachsehen warum die .ico Datei verwendet wird. Bei der Gelegenheit kann ich gleich noch versuchen zu ermitteln, warum ich TVTower nicht im Dock 'verankern' kann. Bei Anderen Anwendungen gibt es dort immer die Option 'Zu Favoriten hinzufügen', um die Anwendung dauerhaft im Dock verfügbar zu machen.

**Comment by GWRon** [comment]
Ich bin Mint-XFCE-nutzer und ich koennte mir einfach eine Verknuepfung zur Binaerdatei in mein Menu ziehen. Die .desktop-Datei macht es natuerlich leichter (bezueglich Bild).

Mache mal Rechtsklick auf die .desktop-Datei und bei Eigenschaften markiere sie als ausfuehrbar - sollte wohl schon helfen.

Fuer dein "Standardmaessig oeffnen mit", koennte es sein, dass du die mimeapps.list (in ~/.local/...) anpassen musst, falls es das nicht direkt bei "oeffnen mit ... andere Anwendungen" abhakbar anbietet.

**Comment by jukey** [comment]
Das Ausführbar machen hatte ich schon probiert und es half nicht. Der Dateityp ist standardmäßig mit dem Texteditor verknüpft und wenn ich eine andere Standard-Anwendung auswählen will, sehe ich dort nur viele installierte Programme. Darüber hinaus gibt es noch 'Anwendung starten' was aber in einem endlosen Laden (angezeigt durch einen entsprechenden Mauscursor) endet - oder eben nicht endet.

Letztlich ist das alles kein Beinbruch für mich - ich könnte mir aber vorstellen, dass ein Installationsskript nach dessen Ausführung das Spiel einfach erreicht werden kann und ein Icon im Dock, das korrekt aussieht die Hürde zur Nutzung senkt.

**Comment by nittka** [comment]
Ich habe auch nochmal etwas rumprobiert:

* Wenn ich in der .desktop-Datei direkt die ico-Datei referenziere, wird direkt der Pixelmatsch angezeigt, d.h. sie scheint *nicht* statt der png-Datei verwendet zu werden - woher das alte Icon kommt ist unklar.
* Ich habe das Bild mal auf 96x96 skaliert, in eine xpm-Datei kopiert und diese in der .desktop-Datei eingetragen. Dann wird das Bild verwendet.
* Die Kategorie sollte Game und nicht Games sein, sonst funktioniert die Einordnung in Spiele bei mir nicht.
* In der Taskleiste erscheint dennoch nicht das richtige Icon.

Zum letzten Punkt habe ich noch keine Lösung gefunden. Vielleicht wird für die Taskleiste das anzuzeigende Icon aus einer anderen Quelle bezogen...

**Comment by GWRon** [comment]
Statt das gleich global verfuegbar zu machen, hab ich einfach nur `cp TVTower.desktop ~/.local/share/applications/` gemacht - und ja, die Kategorie sollte "game", nicht "games" sein.

![image](https://user-images.githubusercontent.com/2625226/111068866-c5b27800-84ca-11eb-86b7-fa37bb1cfb17.png)


Soll ich statt der "TVTower.desktop" ein "Linux_install_desktop.sh"-Skript anlegen - was dann die Datei direkt in obigem Verzeichnis (local/share...) anlegt? Oder beide parallel behalten?

**Comment by nittka** [comment]
Der Vorteil eines komplett separaten Installationsskripts wäre, dass dem Nutzer klar ist, dass eine "Installation" stattfindet. (Bräuchte man dann auch ein Deinstallations-Skript?)
Ich fände es nicht so gut, wenn als Nebeneffekt des Starts eine Datei irgendwo ins System geschrieben würde.

Mein Vorschlag also: Desktop-Datei bei Start ins TVT-Verzeichnis für manuelles Kopieren OK. Installationsskript für das Kopieren nach  ~/.local/share/applications/ oder einfach Hinweis auf diese Möglichkeit in die readme.

**Comment by jukey** [comment]
Ein Installationsscript als optionale Möglichkeit für Linux-Nutzer:innen finde ich auch gut. Perspektivisch ist es natürlich besser das Spiel komplett als Paket zu installieren. Wenn ich es richtig verstehe sind [Snaps](https://ubuntu.com/tutorials/create-your-first-snap#1-overview) so ein distributionsübergreifender Standard, so das nicht etwa verschiedene Pakete für verschiedene Distros nötig wären. Aber das ist natürlich ein anderes Thema und führt vom Icon-Problem weg. Danke für den beschriebenen Workaround dafür.

**Comment by nittka** [comment]
Soll bezüglich dieses Tickets noch etwas außer der Korrektur der Kategorie auf Game gemacht werden oder kann es danach geschlossen werden?

**Comment by GWRon** [comment]
Das Thema "appimage" (und snaps usw.) kann man spaeter nochmal aufgreifen, aber ansonsten ja, reicht die Genreanpassung.

**Comment by nittka** [comment]
Closed by commit  2b6c92267fc96f323ffa723e6312b66cffae341and PR #332
