### ISSUE TITLE
Bei Erstausstrahlung einer Live-Produktion sollte ein Studio blockiert sein

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#308]
Auslagerung von Diskussionsaspekten aus #302. Wenn ein Film produziert wird, ist das Studio bis zur Fertigstellung blockert. Bei Live-Produktionen gibt es zur Zeit nur eine (kurze) Vorproduktion. Beim Senden (der eigentlichen Produktion) ist aktuell kein Studio mehr involviert, obwohl es eigentlich benötigt wird. Umsetzungsvorschlag
* Wenn eine Live-Ausstrahlung erfolgt, wird ein leeres Studio blockert (und man wird ggf. rausgeschmissen).
* Wenn es kein leeres Studio gibt, wird ein anderes blockiert und die dort laufende Produktion verlängert sich entsprechend.
* Wenn es gar kein Studio gibt, kommt es zum Sendeausfall! Information des Spielers ist nötig
* Das Studio bleibt auch nach der Ausstrahlung noch eine (halbe) Stunde blockiert (Aufräumarbeiten). Oder anders ausgedrückt. Die Produktionszeit einer Live-Sendung ist Ausstrahlungszeit + X.
* Vorbereitungszeit und Aufwandsentschädigungen für Nicht-/Spätsenden ignorieren wir.

**Comment by GWRon** [comment]
Dalli per discord:
>Hier würde ich MadTV als Vorbild nehmen. Wenn eine Live-Sendung produziert wird, sollte das Studio bis zur Ausstrahlung vollständig geblockt sein.

>Warum?
>Du machst alles in einem Studio, alles wäre abgeschlossen und dann soll "irgendein" Studio blockiert werden, während der Ausstrahlung? Erm... so viele Praktikanten hat kein TV-Sender :smile:

>Das Studio kann somit auch gar nicht für andere Aufnahmen genutzt werden. Ist ja auch Logisch, die Kulissen für die Live-Produktion stehen in dem Ding drin und können nicht fix weggeräumt werden.



> vermutlich auch einfacher um zu setzen, weil kein freies Studio gesucht werden müsste vom Skript, sondern lediglich, nach dem die Live-Produktion dann seine erste Ausstrahlung hatte, eine Freigabe in "1 Stunde" signalisiert werden müsste (um das Aufräumen zu berücksichtigen)

**Comment by GWRon** [comment]
Der Ansatz "kann die Kulissen ja nicht mal eben wegraeumen" ... sehe ich durchaus ein

Allerdings koenne man auch eine Vorarbeit einerseits wollen - und fuer LiveProgramm 1 Stunde vor (theoretischer Live-)Ausstrahlung den Raum blockieren.


Wir muessen auf alle Faelle die Spielbarkeit im Vordergrund stehen haben. Also den "Spielspass".

**Comment by nittka** [comment]
Das Studio bei Live-Produktionen komplett bis zur Ausstrahlung zu blockieren wäre zwar vom Konzept einfach, hätte aber einige Auswirkungen. Wenn die Show erst in 3 Tagen läuft, wäre das Studio so lange blockert. Wenn man schon für mehrere Shows die Konzepte fertig hat und alle produziert, wäre das Studio ggf. für mehrere "Monate" blockiert.
Das könnte ein Anreiz sein, die Studio-Zeiten besser zu planen oder mehrere Studios anzuschaffen, aber realistisch wäre es nicht.

Wie wäre es mit folgendem "Kompromiss": Live-Sendung haben ja einen geplanten Sendetermin. Ist eine Live-Sendung selbstproduziert und nicht eingekauft, muss sie zu diesem Zeitpunkt produziert werden (auch wenn sie nicht sofort ausgestrahlt wird). Für den gesamten möglichen "Sendezeitraum" +/- eine Stunde (Vorbereitung, Nachbereitung) wird ein Studio blockiert bzw. die Produktionszeit einer gerade laufenden Produktion verlängert. Gibt es kein Studio verfällt die gesamte Produktion.

**Comment by nittka** [comment]
Um zu verhindern, dass kein Studio zur Verfügungs steht, kann man das Kündigen des Mietvertrags unterbinden, so lange noch Produktionen ausstehen. Bei der Vorproduktion merkt sich das Studio den Live-Termin und blockiert sich in der entsprechenden Zeit.

**Comment by GWRon** [comment]
hmm also zwecks Vorproduktion sehe ich noch ein paar Fallstricke:

- nur ein Studio
- zwei Liveprogrogramme fuer die gleiche Zeit  (weiss nicht, eigene Sportberichterstattung oder so)
- diese muessten sich ja blockieren
  - wer zu erst geplant wird hat Vorrang?
  - zweite Planung nicht zulassen ? ("Du hast derzeit nur 1 Sendestudio zur Verfuegung")
  - ... ?

**Comment by nittka** [comment]
Stimmt. Das sollte sich aber auflösen lassen. Selbst wenn mehrere Sendungen für dieselbe Zeit vorgesehen sein könnten, können sie nicht gleichzeitig gesendet werden. D.h. Vorrang für das Blockieren des Studios hätte die tatsächlich ausgestrahlte Sendung (ja, ich sehe das Problem kurzfristiger Programmänderungen). Außerdem gibt es ja bei der Blockiere-Methode das Flag, dass die Zeit der aktuellen Zeit hinzugefügt wird. Dieses Flag würde ich für Live-Produktionen einfach auf true setzen.

**Comment by GWRon** [comment]
> Wenn es kein leeres Studio gibt, wird ein anderes blockiert und die dort laufende Produktion verlängert sich entsprechend.
Und...wenn man zwei Studios mit aktiven Produktionen hat - WELCHE wird unterbrochen? Zufall?

**Comment by nittka** [comment]
Der vereinfachende Vorschlag (an anderer Stelle) war, dass **immer** das Studio genutzt wird, in dem die Vorproduktion stattgefunden hat. Dieses Studio kann nicht gekündigt werden, bis alle Live-Ausstrahlungen erfolgt sind (oder das Ergebnis "entsorgt" wurde).

Dieses Vorgehen hätte auch Vorteile, wenn die Studiogröße Auswirkung auf das Ergebnis bekommt. Dann muss man sich nämlich überlegen, in welchem man die Vorproduktion startet. (Und es gibt keine zufälligen Ergebnisse, weil beim Würfeln des zu verwendenden Studios das falsche gewählt wurde)

**Comment by nittka** [comment]
Fixed by #345
