### ISSUE TITLE
Serienfolgen nicht planbar

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#315]
Im Forum wurde beschrieben, dass die zweite Folge von Dancing Queen nicht planbar war. Ich kann das Problem mit einem neu gestarteten Spiel und einer beliebigen Serie reproduzieren.
* Serie holen
* zwei Folgen planen
* beide Folgen (einzeln) produzieren
* erste Folge im Programmplaner einsetzbar, zweite Folge nicht

Nach Speichern und Laden des Spielstands ist dann auch die zweite Folge planbar - scheinbar ist also ein nicht persistierter Status der Folge verantwortlich.

**Comment by GWRon** [comment]
Hmm ok. Reproduzierbar ist immer gut. Falls Du dich der Sache annehmen willst... Gib Bescheid, ansonsten schau ich mir das bei Gelegenheit an.

Hab mich an dem MacOS-Bug des einen Forennutzers zu knaubeln.

**Comment by nittka** [comment]
Ich denke, das ist wieder ziemlich involviert. Es sieht so aus, als ob das onTryDropUnownedElement-Veto zuschlägt. Warum aber die zweite Folge nicht in der Sammlung des Spielers auftaucht, ist mir noch unklar.

**Comment by nittka** [comment]
Ich habe das Problem möglicherweise lokalisiert: TPlayerProgrammeCollecion registriert einen EventListener (production.onFinish), der dafür sorgen soll, dass der Cache gelehrt wird. Diese Methode (onFinishProgrammeProduction) wird aber nach Abschluss der Produktion nicht aufgerufen - selbst wenn ich den aktuell noch auf String basierenden Schlüssel auf  GameEventKeys.Production_Finalize umstelle.

Ich denke mal, Du wirst schneller rausbekommen, woran das liegt.

**Comment by GWRon** [comment]
Ich denke, das Problem ist die von dir schon markierte Initialize().

Theoretisch werden alle Objekte mit einem neuen TGamestate initialisiert. Nur ... existieren die ProgrammeCollections der Spieler noch nicht - die werden erst beim Anlegen der Spieler erzeugt `new TPlayerProgrammeCollection.Create()` - es sollte da wohl reichen noch ein "initialize()" mit reinzuquetschen.

**Comment by GWRon** [comment]
Zwecks "onFinishProgrammeProduction" - auch aeltere Versionsstaende des Codes haben nur diese eine Codestelle mit dieser Zeile drin ... 
Ich find auf die Schnelle in aelteren Revisionen aber auch nicht die Fassung für die das mal gemacht wurde. Ich meine - ich hab das ja dort nicht aus "dummdidelei" reingeschrieben.

Production_Finalize sollte an sich passen - ab dann ists ja verfuegbar.


Caches sind ja schoen und gut - aber bei uns treiben sie so manchen Bug vor sich her...

**Comment by nittka** [comment]
Ein initialize im Create allein reicht nicht aus. Wenn man sofort nach Spielstart einen Spielstand lädt, wird die Collection scheinbar nicht über ein Create instantiiert. Damit würde der Registrierungscode gar nicht aufgerufen werden.
Wenn man aber in der CollectionCollection bei onSaveGameLoad ein Initialize aufruft, sind alle schon geholten und geplanten Einkaufslisten weg.

Problematisch sind hier also nicht nur die Caches sondern auch die Objektinstantiierung. Zudem ist im Commit zum Eventlistenerumbau noch das DeRegistrieren der Listener bei einem Reset der Collection hinzugekommen. D.h. wenn ein Reset ohne ein Initialize aufgerufen wird, sind die Listener weg (kann durchaus gewollt sein - komplettes Ersetzen einer alten Collection).
... Wenn man natürlich den licences-Cache nicht hätte, bräuchte man auch den Listener nicht...

**Comment by GWRon** [comment]
Man koennte es sich auch einfacher machen und den Event (Listener) auf die "CollectionCollection" uebertragen .... also nicht auf die einzelnen Instanzen.
Die wiederum informiert dann die einzelnen Instanzen (je nach Bedarf).

**Comment by GWRon** [comment]
Aber ... noch was anderes ... was mir hier nicht klar ist.

Also ... wenn es an diesem Event laege ... dann ... was sollte da passieren?
- Produktion beendet
- PlayerProgrammeCollection wird "informiert" und loescht den "_programmeLicences" cache

Mit welchem Effekt? Ich frage, weil ja beim Produktionsbeenden "PlayerProgrammeCollection.AddProgrammeLicence()" aufgerufen wird.
Und dort wird der Cache ja ebenfalls invalidiert - allerdings nicht, wenn es sich um eine Episode handelt.

Vielleicht liegt dort ja der eigentliche Hund begraben...

**Comment by GWRon** [comment]
OK ... wenn wir nun den Cache etc bei "AddProgrammeLicence" auch fuer hinzugefuegte Episoden ungueltig machen ... koennten wir generell auch gleich noch Unterstuetzung fuer "justAddedProgrammeLicences" hinzufuegen.

Was ich meine ist, derzeit wuerde die "Serie" blau hervorgehoben - wir koennten das aber ja auch fuer Episoden machen. (Dann natuerlich beim "Entfernen" einer Serie auch die Episoden entfernen).

**Comment by GWRon** [comment]
Ich glaube irgendwann hatte ich das Hinzufuegen der Lizenzen ueberarbeitet - derzeit wird bei einer neuen Episode der "Header" neu hinzugefuegt (also der Serienkopf). 

Damit bekommt die ProgrammeCollection nicht "wie frueher" direkt die Information der neuen Episode uebermittelt. Die Collection ignoriert dann (derzeit), dass eventuell neue Episoden hinzukamen ...

**Comment by GWRon** [comment]
Wenn wir es uns einfach machen, invalidieren wir den Cache bei jedem "addProgrammeLicence()" - egal ob "bekannt" oder "unbekannt" bzw ob "Serie oder nicht".

Die Funktion wird ja nicht hundertfach "einfach so, mit Duplikaten" aufgerufen. Entsprechend mit einem Kommentar versehen (warum in jedem Fall invalidiert wird). Koennte da voellig reichen. Was denkst Du?

**Comment by GWRon** [comment]
@nittka wolltest Du nicht eh, dass dieser "Neues Programm"-Status erst erlischt, wenn man es "benutzt" ?
Ich fuege jetzt AddJustAddedProgrammeLicence und AddJustAddedProgrammeLicence hinzu - man braeuchte da also nicht direkt "ClearJustAddedProgrammeLicence" aufrufen und koennte selektiv bei "Benutzung" die Markierung entfernen.

Rein so als Info fuer ein "Nachfolge-Ticket/Commit".

**Comment by nittka** [comment]
Bei der Anpassung für dieses Ticket sollte der Eventlistener für finalzeProduction in der Collection komplett entfernt werden. Das Vorhandensein suggeriert, dass der Listener funktioniert und aktiv ist, was ja nicht der Fall ist.

**Comment by GWRon** [comment]
Is schon raus :)
