### ISSUE TITLE
unterschiedliche Bilder für Sendeausfall, Eigenproduktion, Trailer

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#318]
* Wenn eine Werbung komplett ausfällt, wird trotzdem ein "Werbebild" gezeigt. 
* Bei einem Trailer wird im Hintergrund dasselbe Bild gezeigt wie bei einem Sendeausfall (schön wäre das Bild des beworbenen Programms - es wird ja ein Trailer-Hinweis drübergelegt).
* Bei einer selbst-produzierten Show wird auch dasselbe Bild wie beim Sendeausfall gezeigt.

Insb. würde ich mir ein explizites Bild für den Sendeausfall wünschen, das auch danach aussieht (Testbild).

**Comment by GWRon** [comment]
Hmm ja mit dem Overlay, das koennen wir wirklich so machen / aufsplitten.

**Comment by nittka** [comment]
Ich weiß nicht, welche Sendungen es sind, die das "Sendeausfall"-Bild bekommen. Selbstproduzierte Shows (Morning-Show)? Vielleicht stimmt da ja auch nur die Zuordnung nicht. Einfach nur "grau" mit Noise würde ja auch zu Sendeausfall passen.

**Comment by nittka** [comment]
Trailer habe ich angepasst, ausfallende Werbung schau ich mir noch an. Unterschiedliche Sprites für "Sendeausfall" und "noch kein Genre-Bild vorhanden" fände ich weiterhin sinnvoll - das sind einfach zwei völlig verschiedene Dinge.

**Comment by GWRon** [comment]
> Wenn eine Werbung komplett ausfällt, wird trotzdem ein "Werbebild" gezeigt.

Weiss nicht wie man das am Besten macht - Der Boss bemaengelt ja "Sendeausfaelle", meint da aber natuerlich eher Programm. Aber denke ... das geht schon in Ordnung.

**Comment by nittka** [comment]
Ich dachte eher an ein neues Bild für den Sendeausfall (ggf. wirklich einfach grau mit  Noise) als an eins für eine genrische Filmsituation.
Zum Werbeausfall - da war mein Hintergedanke auch weniger der Boss, sondern eher das visuelle Feedback für den Spieler. Wenn man keine Werbung sendet, sollte auch keine zu sehen sein.

**Comment by nittka** [comment]
Mein Problem ist ja, dass das Testbild *auch* bei regulären Sendungen gezeigt wird - für die nämlich noch kein explizites (oder wiederverwendetes) Sprite vorhanden ist. Das scheint im Moment die Genre show_talk, infomercial, newsspecial zu betreffen. Für newsspecial könnte man das News-Bild nehmen, für infomercial das Werbebild (die beiden sind im Moment noch gar nicht in Verwendung, oder?). Und für talkshow würde ich das Politik-Bild vorschlagen.

An die wenig unterschiedlichen Bilder für Werbung und Werbeausfall (siehe Edit oben) muss ich mich vielleicht einfach gewöhnen (mein Vorschlag ist wie gesagt Werbeausfall=Sendeausfall=Testbild).

**Comment by nittka** [comment]
Für fehlende Genres werden nun (auch) bestehende Bilder wiederverwendet.
