### ISSUE TITLE
Grafik-Ebenen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#330]
Gestern habe ich gesehen, wie die Putzkolonne hinter einer größeren Pflanze langgewischt hat. Könnte das eine Variante der Mac-Problematik sein, dass die Elemente im Programmplaner nicht sichtbar sind (Reihenfolge des Renderings)?

**Comment by GWRon** [comment]
Ein paar der Pflanzen stehen im Vordergrund.


Das Rendering beim mac...da muss eine Sortierung Fehlschlagen ...bzw. eine Berechnung (geclippter Viewport).

**Comment by nittka** [comment]
OK. Dann schließe ich dieses Ticket als invalid.
