### ISSUE TITLE
[Studio] Liveshows: Dialog offeriert nur "alle zu starten" 

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#331]
![image](https://user-images.githubusercontent.com/2625226/113706908-7c2b0680-96df-11eb-97bc-51f5cf3d27c7.png)

Sollte es nicht optional auch anbieten, nur die erste zu starten?

**Comment by GWRon** [comment]
[studio_morningshow.xml.zip](https://github.com/TVTower/TVTower/files/6264424/studio_morningshow.xml.zip)

**Comment by GWRon** [comment]
Beides sind Liveprogramme ... und es handelt sich nur um eine Vorproduktion (also schnell abgeschlossen). sollte es trotzdem nur "die naechste produzieren" anbieten?

**Comment by nittka** [comment]
Wegen der Kürze der Vorproduktionen hatte ich mich dagegen entschieden, das auch noch aufzuteilen. Wir können das Ticket offen lassen. Ich würde ihm aktuell aber eine geringe Priorität geben.

**Comment by GWRon** [comment]
Wenn das bewusst so ist...sehe ich da auch keine grosse Prio.
