### ISSUE TITLE
Mögliche Aktionen mit Generalschlüssel

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#339]
Wenn man den Generalschlüssel hat, kann man im Studio eines anderen Spielers auch auf die Senderkarte schauen. Es sind dann zwar keine Aktionen möglich, aber die Buttonbeschriftung ist nicht einheitlich und deaktiviert sind sie auch nicht.
Ich wäre dafür, den Zutritt zur Senderkarte ganz zu verbieten - dann muss man sich darum keine Gedanken machen. Wo die Sender stehen sieht man ja auch auf der eigenen Karte und Kabel- und Satellitenverträge sind, so glaube ich, auch erkennbar.

Im Archiv würde ich das Betrachten der Filme jedoch erlauben (analog Programmplaner) - wenn man stöbern will, wird man hier weniger wahrscheinlich erwischt.

**Comment by nittka** [comment]
Ich mache das Ticket nochmal auf, damit die noch nicht funktionierenden Feinheiten nochmal besprochen werden können:

* Archiv - Cursor bei Hover über fremdem Film wie im Büro (Zeigen statt Greifen), keine Aktion bei Klick (aktuell geht alles zu)
* Senderkarte - Filter rechts oben haben keine Auswirkung (Spieler deaktivieren, Sendertyp auswählen)
* Senderkarte - in der Liste scheinen auch in einem fremden Büro die eigenen Sender angezeigt zu werden (roomOwner statt player verwenden?)

**Comment by GWRon** [comment]
ja ...der player wurde damals wohl verwendet damit etwaige "Veraenderungen" beim Gegner nicht moeglich waren - das sollte ja aber nun auch so umsetzbar sein.

**Comment by GWRon** [comment]
Habe das jetzt angepasst und die Filter funktionieren wieder - und die Senderkartenliste enthaelt die Elemente des jeweiligen Bueroinhabers.

Derzeit sind die Filter "pro Buero" abgespeichert (man wuerde also mitbekommen, wenn die KI in unserem Buero die Filter umstellt).
Koennte man aendern (die Filter in die `TStationMapCollection` packen - vielleicht gleich als Bitmaske, dann kann jede StationMap die Info fuer andere Spieler abrufen, derzeit hat ja jede StationMap nur die Info fuer sich selbst)

**Comment by nittka** [comment]
Passt für mich.
