### ISSUE TITLE
Bug: Geschenke-Anzahl nicht im Speicherstand erfasst

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#343]
"newsreader" schrieb im Forum:
https://gamezworld.de/phpforum/viewtopic.php?pid=89458#p89458

> - Nach dem Laden eines Spielstandes ist die Anzeige von Bettys Geschenken im Supermarkt wieder komplett bei 0.

**Comment by nittka** [comment]
Ich habe den Eintrag gelesen und gestern auch schon einen Fix erstellt. Die Historie wird korrekt persistiert, aber nach dem Einlesen haben die Geschenke eine andere ID als beim Neustarten. Daher schlägt der Gleichheitsvergleich zwischen Geschenken fehl. Wenn man stattdessen den Index des Geschenks vergleicht, passt es.

**Comment by GWRon** [comment]
Alles klar.
