### ISSUE TITLE
DAYOFYEAR in Nachrichten

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#347]
In einigen Nachrichten wird für das Verfügbarkeitsdatum "TIME_DAYOFYEAR" mit den Werten 1 bis 12 verwendet. Die Anzahl der Tage pro Jahreszeit ist nun aber anpassbar und gibt es diese Tage ggf. gar nicht mehr.

Mein Vorschlag wäre, TIME_DAYOFYEAR nicht mehr zu erlauben und die Bestandsnachrichten anzupassen (z.B. Aufweichen auf Season).

**Comment by GWRon** [comment]
Dann muss der 1-12 Wert skaliert werden.

Der Gedanke hier ist Dezember... Weihnachtskram usw. Zu ermoeglichen. Eventuell also MonthOfYear nennen?

**Comment by nittka** [comment]
Das klingt erstmal gut. Ist sichergestellt, dass jeder Monat mal vorkommt (ich denke vor allem an den Fall daysPerSeason=1). Weiterhin muss ich mal analysieren, wie wichtig diese Konfiguration bei den aktuell verwendeten dayOfYear-Nachrichten überhaupt ist.
Wenn nämlich noch das Jahr auf einen bestimmten Wert eingeschränkt ist, kämen die Nachrichten ggf. gar nicht zum Zuge.

**Comment by nittka** [comment]
Ich werde mal prüfen, an welchen Stellen das DAYOFYEAR in dieser Form "zwingend" ist. Es gibt überhaupt ziemlich viele einmalige Nachrichten, bei denen auch das Erscheinungsjahr festgelegt ist. Das schränkt deren Sichtbarkein schon ziemlich ein - insb. wenn sie in frühen absoluten Jahren verfügbar sind (Spieler hat die Nachrichten noch gar nicht abonniert, Spieler hat ein späteres Startjahr gewählt).

Vielleicht kann man hier DAYSPLAYED oder YEARSPLAYED sinnvoll einsetzen. (Zu klären wäre natürlich in welchem Umfang ich in fremden Datenbanken rumkonfigurieren darf).

**Comment by GWRon** [comment]
Gute Nachrichten koennen auch in news.xml uebernommen werden. Da kann dann natuerlich auch rumgespielt werden. Generell ist dies...sofern "historisch plausibel" Anpassungen erfahren.

**Comment by nittka** [comment]
Dieselbe Problematik gibt es auch bei anderen availability-Einsätzen, bei denen aktuel von 12 Spieltagen ausgegangen wird.

**Comment by GWRon** [comment]
Das Problem haben wir bei allen Sachen die irgendwie versuchen an bestimmten "Momenten" zu geschehen. 
Wenn du 24 tage hast, liegt weihnachten an Tag 24. Hast du 36 Tage, dann aber an Tag 35.

Klar laesst sich das fuer manche Dinge "umstellen" (vielleicht nach "Kalendertag" fuer "day" und die angegebene Uhrzeit dann vom "Spieltag" - aber das kann zu verfruehtem Weihnachten fuehren). ... so richtig weiss ich noch nicht, wie wir das machen sollen.

Ist einfach --- zu viel Konfigurierbarkeit - 12 Tage und wir haetten kein Problem :)

**Comment by nittka** [comment]
Zumindest für die Bestandsdatenbankdaten wollte ich schauen, bei welchen Einträgen der konkrete Spieltag wirklich relevant ist.
Ich kann aber auch verstehen, dass 12 Tage pro Jahr ziemlich viel ist (wenn man nicht immer neue Spiele mit unterschiedlichen Startjahren starten möchte, um mal andere Filme zu sehen).
Was wären denn die negativen Auswirkungen von einem nicht änderbaren Standard von 4 Tagen pro Jahr (1 Tag pro Jahreszeit). Ich könnte mir vorstellen, dass das unschön wird, wenn man Inflation ins Spiel bringt (Studiomiete steigt jährlich). Typischerweise braucht man ja am Anfang mehr Zeit, um den Laden ans Laufen zu bekommen, wenn erstmal genug Geld da ist, würde das keine Rolle mehr spielen.

**Comment by GWRon** [comment]
4 ...wenn man da 100 Tage spielt, sind das schon 25 Jahre... Relativ heftig.

12 erlaubt halt Monate, Jahreszeiten...

**Comment by nittka** [comment]
Im aktuellen Datenbankbestand konnte ich DAYOFYEAR soweit erstetzen. Meistens war SEASON passend genug. An einigen Stellen habe ich happentime mit konkreten Daten verwendet.

Interessant wäre hier ob man den Zeittyp 4 (exaktes Datum z.b. 4,1990,10,5) auch mit undefiniertem Jahr angeben könnte (4,-1,10,5), um zu sagen, dass die Nachricht an einem 5.10. in einem beliebigen Jahr erscheinen soll... Damit wäre es möglich (einmalige) Nachrichten, die mit einem bestimmten Datum zusammenhängen, vom Startjahr unabhängiger zu machen.

**Comment by GWRon** [comment]
Hmm die einfachste Variante waere wohl, eine Art "Spieljahr"-Zeittyp zu nutzen. Also nicht "1990" sondern "1" (1. Spieljahr) und dann wuerde die News sich einfach immer selbst triggern koennen (aller 1 Jahr).

Will man, dass eine News nur "ab und zu" erscheint, muesste man wohl zwei News anlegen - die sich "or" triggern. Und die eine News ist eine unsichtbare und die andere eine sichtbare.

**Comment by nittka** [comment]
Hat sich mit #346 erledigt. Für die "regelmäßig im April"-Problematik würde ich ein neues Ticket aufmachen, wenn sie wirklich auftritt. Im Datenbankeditor habe ich eine Warnung eingebaut, wenn DAYOFYEAR verwendet wird, damit man darauf aufmerksam gemacht wird, dass es ein Problem geben könnte.
