### ISSUE TITLE
Github Workflows integrieren

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#349]
Ein Kollege empfahl mir gerade die Github workflow / actions. Damit bekommt man Zugriff auf cloud computer (eigene Instanzen) und kann dort alles moegliche anstellen.

Beispielsweise:
- letztes BlitzMax NG herunterladen
- letztes TVTower von "Master/main/..." runterladen
- kompilieren
- .exe bereitstellen

Eine weitere "action" kann diese .exe als "artifact" abholen und mit der Linuxbinary, der Macbinary... zusammen in ein "dailybuild.zip" packen und irgendwo hochladen / als github release verpacken ...

Die actions laufen auf virtuellen Macs, Windows und Linuxmaschinen.

Hiermit liessen sich also fixe Nightlybuilds realisieren - oder Builds die einfach immer bei jedem Commit "probiert" werden (also "passing" badges etc).

Klingt eigentlich ganz cool - auch wenn man sich da mehr an "github" bindet.

**Comment by nittka** [comment]
Ich halte das auch für eine gute Idee. Der für mich entscheidende Vorteil ist, dass man dadurch eine "ausführbare Dokumentation" der nötigen Schritte für das Erstellen der lauffähigen Anwendung hat (ich weiß es bislang nicht und kann mir nur selbst lokal eine Version bauen, die ich mit BlitzMax starten kann). Der zweite Vorteil ist, dass das Erstellen grundsätzlich vereinfacht wird und potentielle Beta-Tester ohne großen Aufwand an einen aktuellen Stand kommen (gemeldeter Bug gefixt - probier mal, ob das so passt).
Ich würde zunächst aber davon absehen, bei jedem Commit ein neues Nightly zu bauen. Insb. wenn klar ist dass eine neue Funktionalität noch nicht fertig ist, die Commits aber auf den master gepusht werden, fände ich das nicht gut. Die Actions kann man ja auch manuell anstoßen. Bei der aktuellen Entwicklungssituation halte ich das auch für ausreichend.

**Comment by MatthewForrester** [comment]
I know nothing about coding, but I also play [Simutrans](https://www.simutrans.com/en/) and we [started using GitHub Actions](https://github.com/jamespetts/simutrans-extended/actions) last year for the Simutrans-Extended version. It has not been an easy process because you must carefully manage the dependencies between the coders' systems, the GitHub containers, and the users. Simutrans-Extended already had its own Nightly build system and I think almost everybody still uses it.

I think it's a big advantage for TVTower because you don't have a Nightly build system yet. Finding and fixing bugs is earlier and easier with Nightly builds.

By the way, perhaps you should consult Brucey too? If the Action is downloading BlitzMax-NG from his website after every commit, then that could be a lot of data. Of course, you could build it from the BlitzMax GitHub, but that is even more dependencies to manage.....

**Comment by GWRon** [comment]
@Hezkore wrote some action already to fetch specific or latest NG releases.
So we could build upon it.


Blitzmax is rather self contained ..so once it is downloaded and unzipped (on wknxowst) you can compile the game.
On linux it just requires the build essentials and on mac then xcode.


What trouble did you experience with simutrans builds?

**Comment by MatthewForrester** [comment]
> What trouble did they experience with simutrans builds?

Reviewing old posts on the Simutrans forum and [the relevant commits](https://github.com/jamespetts/simutrans-extended/commits/master/.github) I think it seemed difficult because I was even more ignorant then. So maybe the problem was me, not GitHub Actions. :flushed: Ignore what I posted above, please.

>@Hezkore wrote some action already to fetch specific or latest NG releases.
> So we could build upon it.

[This one, right?](https://github.com/Hezkore/setup-blitzmax-action). Great, it looks like the most difficult part of the work has been done for you already.

**Comment by GWRon** [comment]
Yes I am talking about this action. Hezkore was the one suggesting the Actions to me ;-)

**Comment by nittka** [comment]
Ein erster Schritt wäre eine "minimale" Aktion:
* auf Knopfdruck (nicht automatisch)
* wird für eine Zielplattform gebaut
* und das lauffähige Ergebnis kann von Github runtergeladen werden

Die Verfeinerungen (automatisches Bauen, für alle Plattformen, Caching, Upload etc.) können angegangen werden, wenn das Bauen grundsätzlich funktioniert.

**Comment by nittka** [comment]
I have started working on a "minimal" action in my fork.
* the dependencies might not be minimal, but I had to add and add until there were no compile errors, anymore
* I don't know which artefacts are actually needed, so the current upload might not be runnable (have no Linux to test at the time of writing) and it might include too much
* there seem to be two identical binaries!?

https://github.com/nittka/TVTower/actions/runs/1238945824

**Comment by GWRon** [comment]
Ich habe auch eine Action in einem "privaten" repo...

Da wird alles runtergeladen und kompiliert...am ende kommt eine Zipdatei als Artefakt bei raus ... Also linux binary und alle assets wie in einem Release.

Ich kann den Inhalt der Action morgen mal hochladen...wenn die Ersatzteile fuer meinen Computer da sind ;-)

**Comment by GWRon** [comment]
Mein Script ist auf alle Faelle etwas laenger ...da ich wirklich alle Abhaengigkeiten installiere...


Auch ist es wichtig, ein aelteres Ubuntu zu nehmen, die neuesten haben eine zu neue glibc Version installiert...und dann laeuft die Binary nicht mehr auf einem aelteren Linux (wie meinem 19.3er Mint).

**Comment by nittka** [comment]
Vielleicht verstehe ich das Ticket auch nur falsch, aber es klingt als wäre eine native Unterstützung von 32-bit Linux bei den Actions nicht möglich (https://github.com/actions/runner/issues/1181).
Kann Blitzmax auch selbst auf einem 64-bit-System ausführbaren Code für 32-bit-Systeme erzeugen?

**Comment by GWRon** [comment]
Du musst die :i386 libs installieren...kann aber sein, dass es die x64 deinstalliert. Danach sollte es gehen. Muss ich mir mal angucken (hatte bzw hab die gleichen Bedenken wie Du schon im Kopf gehabt)

**Comment by GWRon** [comment]
Ich habe den Workflow aufgesplittet und momentan kompiliert es:
- win32
- win64
- linux32
- linux64
- und es stellt theoretisch noch die aufgeraeumte "Ordnerstruktur" bereit (also ohne source, .bmx, .github etc)

Es fehlt noch Mac OS X ... und natuerlich fehlt noch das Erstellen von "releases".
Gedanke ist: alle jobs im Workflow stellen die Binaries bereit, beim "Release" bzw "nightly build" (oder "on commit") werden die Dateien dann eingesammelt und korrigiert (der Artefaktupload entfernt das "x"-Ausfuehrbit der Binaerdateien). Danach kommen die Binaries zusammen mit den "Assets" in eine Datei und die soll planmaessig dann auf unseren Server "geschoben" werden (evtl FTP + "call" zu einem PHP-Skript, dass "neues" vorliegt). Bei "release" (wenn ein neuer "tag" committed wird) soll der workflow dann automatisch ein neues "Release" anlegen.

**Comment by GWRon** [comment]
Naja, man kann das ja auch so gestalten, dass man auf "Klick" einen Dev-Build zusammenstellt - also einfach das "onCommit" deaktivieren und nur auf die tags, bzw manuelles "klicken" etwas generieren. Auch kann man das so gestalten, dass ein solcher Build nicht "veroeffentlicht" wird - wir also bspweise nur an bestimmte Nutzer das "Package" weitergeben (diejenigen mit einem bestimmten Bug oder so).

Vorrangig ists aber zum "Release" zusammenstellen (wenn auch vlt nicht unbedingt automatisiert als github-release -> website-release)

**Comment by GWRon** [comment]
wenn wir in "branches" arbeiten, dann waeren "Features" ja erst vollstaendig umgesetzt, wenn in den "master" ueberfuehrt.

Alternativ waere darueber nachzudenken, noch einen branch zu haben - in dem man alles "veroeffentlichungswuerdige" reinbringt (also nur "releases" bzw "pre-releases" ... alpha, beta...)

**Comment by nittka** [comment]
"onClick" finde ich für nightly zunächst ausreichend. Wir kompilieren für unsere Tests ohnehin selbst (und ich habe auch wenig Motivation, alles immer auf mehreren Plattformen auszuprobieren).

Aufwändigeres Branching finde ich im Moment auch nicht nötig (Branch für jedes Release, damit man dort Bugs für genau diese Version beheben kann; das kann man bei einem größeren Entwicklerteam bei einem bezahlten Produkt machen). Bezüglich nightly, ging es mir eher um Commits auf dem Master, die aber noch nicht ausführlich getestet waren, so dass nochmal nachgebessert werden muss.

Eine Beta-Version zu veröffentlichen, die von mehr Spielern nochmal vor dem eigentlichen Release ausprobiert werden kann, ist vielleicht eine gute Idee. (Oder man veröffentlicht eine Version und schiebt kurz hinterher noch eine Bugfix-Version nach.)
Ob dafür ein separater Branch nötig ist oder ein Tag ausreicht, ist schwer zu sagen. Ich glaube jedenfalls nicht, dass wir vor einem Release auf dem Master noch große neue Features anfangen. Die bleiben eher auf einem Featurebranch, bis sie eben fertig sind.

**Comment by GWRon** [comment]
Ich habe meinen aktuellen Stand des workflows/der actions hochgeladen.

"onclick" erzeugt es eine "TVTower.Nightly" die aehnlich eines Releases alle notwendigen Dateien enthaelt:
- Windows 32bit, 64bit
- Linux 32bit, 64bit
- Mac OS X 64bit

Leider kommt es immer mal wieder vor, dass die Kompiliervorgänge mit "modul brl.irgendeins" abgebrochen werden, oder vorher kompilierte Dateien ploetzlich fehlen. Ich schaetze, das sind die runner (die OS images) und bei hoher Auslastung spinnts. Manchmal kompiliert dann nix fuer den Mac, mal nicht fuer Windows.

Wenn es einmal kompiliert hat, wird vieles davon "gecached" und es sollte bei einem weiteren Durchgang dann dort gut durchflitzen.

**Comment by GWRon** [comment]
Hab ich voll vergessen - in meinem workflow-test habe ich die base.util.string.bmx gefixt...

```
$ find . -name '*.bmx' -exec file -i {} \; | grep "utf"
./base.util.color.bmx: text/plain; charset=utf-8
./base.util.vector.bmx: text/plain; charset=utf-8
./base.gfx.gui.bmx: text/plain; charset=utf-8
./base.util.mersenne.bmx: text/plain; charset=utf-8
./base.util.string.bmx: text/plain; charset=utf-16le
./base.sfx.soundmanager.base.bmx: text/plain; charset=utf-8
./base.util.interpolation.bmx: text/plain; charset=utf-8
./base.util.persongenerator.bmx: text/plain; charset=utf-8
./base.gfx.bitmapfont.bmx: text/plain; charset=utf-8
./base.util.numbersortmap.bmx: text/plain; charset=utf-8
```
die ist naemlich derzeit UTF-16LE ... und das bringt den windows-runner zum stolpern

```
Compile Error: Can't find interface for module 'brl.retro'
[D:/a/WorkflowTest/WorkflowTest/source/Dig/base.util.string.bmx;51;0]
Build Error: failed to compile (-1) D:/a/WorkflowTest/WorkflowTest/source/Dig/base.util.string.bmx
Error: Process completed with exit code -1.
```
...darueber hatte ich im August auf dem BlitzMaxNG-discord server schon geschrieben - und nicht mehr dran gedacht.

**Comment by nittka** [comment]
Ich würde dieses Ticket ("initiale Integration") als gelöst betrachten. Weitere Funktionen können dann in neuen Tickets bearbeitet werden.
