### ISSUE TITLE
Spiel mit Originalfilm

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#354]
Der Post https://www.gamezworld.de/phpforum/viewtopic.php?pid=89486#p89486 im Forum hat mich auf die Idee gebracht, dass es mit wenig Aufwand möglich ist, ein Spiel mit Originalnamen umzusetzen.
* Zusätliches Flag DEV_PROGRAMM_USE_ORIG_NAMES mit Default-Wert false in die Config
* Beim Einlesen der Programme und Personen die Originalnamen (falls vorhanden) die normalen Namen überschreiben lassen
* Dokumentation der wichtigsten Config-Werte (analog Datenbank)

**Comment by GWRon** [comment]
Dann koennen wir auch gleich einen Ingameoptionsschalter anbieten...

Wir muessen uns soweit wie moeglich aus der rechtlichen Grauzone/Thematik "Originalnamen" raushalten. Deswegen nutzen wir in der DB ja auch nur die Originalnamen zur leichten Erkennung, wer gemeint ist (um Dopplungen zu vermeiden).

**Comment by nittka** [comment]
Aber wie will man sich denn bei Verwendung der Originalnamen raushalten?

**Comment by GWRon** [comment]
In dem es Aufwand bedarf, sich der Originalnamen zu bedienen.

Ansonsten kann man die auch gleich selbst bereitstellen und auf die Abmahnungen warten.
