### ISSUE TITLE
triggernews mit Zeit-Typ 4 geht scheinbar nicht

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#357]
Ein Ansatz beim Ersetzen von TIME_DAYOFYEAR in den Nachrichten war, die Zeit für Nachrichten/Effekt auf ein konkretes Datum zu setzen (Aktena mit Datumsangaben in der Nachricht). Die Erstnachricht bekommt ein happentime mit konkretem Datum (4,1987,5,1), die Nachfolgenachricht wird dann per Effekt mit gleichem Zeittyp und späterem Datum angestoßen.

Die Hauptnachricht wird auch veröffentlicht, aber ich habe es nicht geschafft, dass der Effekt mit konkretem Datum stattfindet. Für Tests habe ich sämtliche Nachrichten außer einer Handvoll gelöscht.

Der Workaround, den ich zunächst verwenden werde, ist die Steuerung nicht über Effekt zu machen sondern alle Nachrichten als Hauptnachrichten mit happentime umzusetzen (da sie ohnehin Einmalnachrichten sind).

(Ein möglicherweise verwandtes Problem ist der Abbruch der selbst auslösenden Börsennachrichten)

**Comment by GWRon** [comment]
Typ 4 ist `'4 = next year Y, month M, day D, hour H, minute I` (siehe game.world.worldtime.bmx) und wenn ich mir die dortige Logik anschaue:

```BlitzMax
			case 4
				if timeValues.length < 1
					return -1
				else
					Select timeValues.length
						Case 1   return CalcTime_ExactDate(nowTime, timeValues[0])
						Case 2   return CalcTime_ExactDate(nowTime, timeValues[0], , timeValues[1])
						Case 3   return CalcTime_ExactDate(nowTime, timeValues[0], , timeValues[1], , timeValues[2])
						Case 4   return CalcTime_ExactDate(nowTime, timeValues[0], , timeValues[1], , timeValues[2], , timeValues[3])
						Default  return CalcTime_ExactDate(nowTime, timeValues[0], , timeValues[1], , timeValues[2], , timeValues[3], , timeValues[4])
					End Select
				endif
```
und dann `CalcTime_ExactDate()` betrachte ...

Will man eine Nachricht 1 Jahr spaeter machen: "4,1,5,6" (1 < 1000, und somit relative Jahreangabe, >1000 und es ist eine exakte Jahresangabe)

Damit koennte bei Spielstart eine News als "fuer naechstes Jahr am X.Y." definiert werden.

Nun mal schauen, ob da irgendwo ein Fehler seine Deckung verlaesst.

**Comment by GWRon** [comment]
Ein erster Fix zum Thema ist "-1" bei GetDay(-1), GetYear(-1) ... wieder die aktuelle Zeit nutzen zu lassen (das fiel bei einer Korrektur fuer die KI-LUA: "Long, 64bit" leider der Bugschere zum Opfer).

Mein Testdatensatz ist der hier:
```XML
		<news id="ronny-news-test-01" type="0" thread_id="ronny-news-test" creator="5578" created_by="Ronny">
			<title>
				<de>Test 1</de>
			</title>
			<description>
				<de>Test</de>
			</description>
			<effects>
				<effect trigger="happen" type="triggernews" time="4,0,2,7" news="ronny-news-test-02" />
			</effects>
			<data genre="0" price="1.0" quality="48" happen_time="4,0,0,2" />
		</news>		
		<news id="ronny-news-test-02" type="2" thread_id="ronny-news-test" creator="5578" created_by="Ronny">
			<title>
				<de>Test 2</de>
			</title>
			<description>
				<de>Test</de>
			</description>
			<effects>
				<effect trigger="happen" type="triggernews" time="4,0,0,6" news="ronny-news-test-03" />
			</effects>
			<data genre="0" price="1.0" quality="48" />
		</news>		
		<news id="ronny-news-test-03" type="2" thread_id="ronny-news-test" creator="5578" created_by="Ronny">
			<title>
				<de>Test 3</de>
			</title>
			<description>
				<de>Test</de>
			</description>
			<data genre="0" price="1.0" quality="48" />
		</news>	
```
Die Erste wird nun auch am ersten Spieltag ausgeloest, die zweite (und dritte) News noch nicht.

**Comment by GWRon** [comment]
Ok - ein paar "nowTime" mussten noch gefixt werden  - und mein news-happen-effect hatte die Werte "4,0,2,7" -- Typ 4, Jahr 0, Monat 2 und Tag 7.
Typ 4 rief `CalcTime_ExactDate()` auf - und uebergab keinen "Stunde"-Wert. Damit wurden die "defaults" genutzt - und die waren dann eben "-1000000" - und der "happen"-Zeitstempel der getriggerten News lag dann im Jahr 1927 oder so.
