### ISSUE TITLE
Absturz bei modifyNewsAvailability

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#360]
Ich wollte mal das An- und Ausschalten von News durch einen Effekt ausprobieren (Branch mit reduzierten Nachrichten https://github.com/TVTower/TVTower/tree/testModifyNewsAvailable). Idee: eine explizit später laufende Nachricht deaktiviert die Teelichtnachricht.

Es kommt allerdings konsistent sehr früh im Spiel zum Absturz weil die Nachricht unter der GUID nicht gefunden wird.
* in TGameModifierNews_ModifyAvailability in der Run-Methode sollte wahrscheinlich nicht das Event sondern das Template geholt werden, oder?
* selbst wenn ich das Template hole, kommt es zum selben Absturz - nicht gefunden
* Meiner Ansicht nach wird die Methode viel zu früh aufgerufen - in den ersten Spielminuten, obwohl die Nachricht erst nach ein paar Stunden erscheinen soll und damit auch der Effekt erst dann auftreten darf
* In der Run-Methode sollte nicht nur ausgegeben werden, dass die Nachricht nicht gefunden wurde; die Bearbeitung muss enden, da sonst hinterher der SegmentationFault unausweichlich ist

**Comment by GWRon** [comment]
Ja es muesste das Template geholt werden.

Was auch zusaetzlich noch moeglich waere (aber halt noch mehr Code, der evtl kaum genutzt wuerde): alle derzeit "aktiven" Nachrichten die auf einem "nicht laenger verfuegbarem NewsEventTemplate" basierten, wuerden auch entfernt werden.

**Comment by GWRon** [comment]
Ich glaube - das "zusaetzliche" ist sogar noetig.

News1 loest News2 aus (News2-newsevent wird aus dem template generiert)
News3 will die availability von News2-vorlagen deaktivieren, aendert also das template ab - der NewsEvent von News2 waere davon unberuehrt.

Derzeit ueberpruefen NewsEvent, ob ein template existiert und dieses nicht verfuegbar waere - aber vielleicht will man das ja umgedreht machen? Also eine Nachricht "ermoeglichen" und danach das template sperren - fuer den Fall waere dann eine Ueberpruefung ob "template? und template available" nicht mehr so toll.

**Comment by nittka** [comment]
Wird bei der Auswahl der zu Spielbeginn gezeigten Nachrichten darauf geachtet, ob das Newstemplate verfügbar ist? Wenn ich nämlich eine Nachricht initial als nicht verfügbar markiere, um sie später zu aktivieren, erscheint sie dennoch zu Spielbeginn.
Analog sollten Nachrichten mit einer happen_time zu Spielbeginn ausgeschlossen werden (außer die Zeit liegt relativ zur Startzeit des Spiels berechnet in der Vergangenheit).

Ich hatte einer Nachricht eine Zeit "in 5 Stunden" konfiguriert und sie ist dennoch zum Spielbeginn verfügbar.

**Comment by nittka** [comment]
Und auch wenn ich alle Nachrichten mit available="0" konfiguriere (und ohne happen_time), werden die Nachrichen initial verwendet.

**Comment by GWRon** [comment]
game.database.bmx wertete "available" nur fuer die "broadcastFlag" aus.

Im Code wird derzeit "field available" ausgewertet (hab da zweigleisig eine Anpassung auf "broadcastFlag" bereits vorgesehen).

Bei "AdContract" wird ebenso verfahren (Nutzung von "field broadcastFlag") ... und auch das ist ja nix, was "ausgestrahlt" wird.

Eventuell also wirklich "field available" entfernen und den broadcastFlag auswerten?

Alternativ reicht es wohl, im Code von game.database.bmx
```Blitzmax
		Local available:Int = data.GetBool("available", Not newsEventTemplate.hasBroadcastFlag(TVTBroadcastMaterialSourceFlag.NOT_AVAILABLE))
		newsEventTemplate.SetBroadcastFlag(TVTBroadcastMaterialSourceFlag.NOT_AVAILABLE, Not available)
```
noch folgendes anzuhaengen:
```Blitzmax
		newsEventTemplate.available = available
```

**Comment by GWRon** [comment]
Ok, hab das entsprechend mal umgestellt - ist zwar nicht unbedingt "logisch" (vom Variablennamen her) aber stringent zu den anderen "Broadcast"-gehoerigen Objekten.

**Comment by GWRon** [comment]
> Ich hatte einer Nachricht eine Zeit "in 5 Stunden" konfiguriert und sie ist dennoch zum Spielbeginn verfügbar.

Kannst du dazu mal einen eigenen Issue inklusive dem genutzten "happen_time"-Wert machen?
