### ISSUE TITLE
Nachrichten mit happen_time nicht als Initialnachrichten

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#364]
Für Tests mit modifyAvailability habe ich einen Branch mit reduzierten Nachrichten angelegt. https://github.com/TVTower/TVTower/tree/testModifyNewsAvailable
Einer Nachricht habe ich die happen_time "1,5,6" gegeben (in 5 bis 6 Stunden); in der Erwartung dass das bei Spielstart so ausgewertet wird (ggf. wäre in 0 Spieltagen zwischen X und Y Uhr). Entgegen der Erwartung war die Nachricht aber unmittelbar bei Spielstart sichtbar.

Vorschlag: Nachrichten, bei denen happen_time definiert ist, können als "Startnachrichten" nur dann gewählt werden, wenn happen_time nicht definiert ist oder der Zeitpunkt bei Spielstart in der Vergangenheit liegt (z.B. Spielstart 1985, happen_time der Nachricht Dezember 1984).

Falls die Umsetzung zu aufwändig ist, sollten wir wenigstens dokumentieren welche Zeittypen (0-8) erwartungsgemäß funktionieren (z.B. es gibt nur eine einzige Nachricht in der Datenbank, happen_time Jahr 2000; wird sie dann dennoch als Startnachricht verwendet)

**Comment by nittka** [comment]
Vielleicht liegt es auch noch daran, dass ich die Zeitdefinitionen noch nicht richtig verstanden habe. Ich war immer davon ausgegangen, dass sich die Datumsangaben (in x Tagen, am Datum y...) auf die "schnell laufende Tage" hinter der Spielzeit beziehen, die Zeitangaben aber auf die Spielzeit. D.h. happen_time 1.2.1985 13:00 ist am ersten Spieltag um 13:00.
In 5 Stunden bedeute also von der aktuellen Spielzeit aus gerechnet 5 Stunden später.
Wenn sich die Zeit aber auf die im Hintergrund laufende Zeit bezieht, sehe ich überhaupt keinen Grund überhaupt Zeiten anzugeben, da die Zeit nichts mit der Spielzeit zu tun haben kann.

Wie sind denn hier eigentlich die korrekten Termini:
* Realzeit (Zeit in der der Spieler lebt)
* Spielzeit (Spieltag x, 13 Uhr)
* ? (Datum/Zeit die im Hintergrund hochtickert)

**Comment by GWRon** [comment]
So richtige Termini hab ich dafuer nicht.

Die verschiedenen "Vorlagen" (die erste Nummer im "happen_time"-Format) beziehen sich oft auf "in x-y Spieltagen" oder "in x-y Spielstunden".
Ausser fuer "4" und "5" beziehen sich die "Monate", "Wochentage", "nter Tag der Woche", "Jahr", ..."Season" beziehen sich auf die Spieltage.

mit "4" und "5" koennte aber sowas wie "24. Mai, 18:25, 1985" angegeben werden. Das koennte je nach Spieleinstellung aber auch der 3. Spieltag um 12:02 sein. Du hast hier recht, dass die Angabe der Uhrzeit da aber eher... Bloedsinn ist. Sie koennte aber dann notwendig sein, wenn man aus irgendwelchen Gruenden eine ganz bestimmte Spielzeit haben will (mit der Maus ueber die Uhr im Interface - da steht ja dann das "eigentliche Datum" - vielleicht will man, dass zu einer gewissen Spielzeit da ein spezielles Datum steht).

**Comment by nittka** [comment]
Bezüglich Termini liegt ein Missverständnis vor - da ging es mir nicht um die verschiedenen happen_time-Formate sondern um das Datum, das beim Hover über der Uhr hochzählt. Zusammengefasst gibt es also die Realzeit (die man beim Spielen vor dem Rechner verbringt), die Spielzeit (Jahr, Spieltag, Uhrzeit) und - in Ermangelung eines existierenden Terminus - die Tickerzeit. Tickerjahr und Spieljahr sind identisch und die Aufteilung der Tickertage auf Spieltage hängt von der Konfiguration (Spieltage pro Saison) ab.

0,1,2,3,6,7,8 beziehen sich eindeutig auf die Spielzeit, aber 4 und 5 auf das Tickerdatum, wobei die Interpretation des Zeitanteils noch Klärung bedarf. Als Tickerzeit ist sie (außer bei 90 Tagen pro Saison) nicht wirklich sinnvoll. Aber auch als Spielzeit ist sie problematisch. Man könnte es interpretieren als "Spieltag an dem das gesetzte Datum liegt zur definierten Spielzeit". Das geht aber irgendwie schief: 1.1.1985 23:00 ist nicht wirklich Neujahr und liegt im Gutfall überhaupt noch im Januar (1 oder 2 Tage pro Saison). Für einzelne Datumsangaben ist das noch nicht so kritisch. Wenn man aber Nachrichtenketten baut (Start der Märchentage im September und dann eine Nachfolgenachricht Ende der Märchentage triggert), kann es zu komischen Effekten kommen. Verwendet man eine Tickerdatumsdefinition (50 Tickertage nach einem konkreten Datum) kommt die Nachricht vielleicht schon am selben Tag, verwendet man "in 3 Tagen" ist ggf. schon mehr (oder viel weniger) Zeit vergangen, als man denkt - und der Nachrichtentext klingt komisch (nach 100 Tagen enden die Märchentage).

Aktuell wäre mein Vorschlag, den Zeitanteil aus Definition 4 und 5 zu streichen, damit erst gar keine Verwirrung auftreten kann. Egal in welcher Interpretation macht hier die Zeit Probleme und kann zu unerwarteten Effekten führen. Ich glaube auch nicht, dass in der Datenbank schon Einträge mit scheinbar relevanter Zeit existieren.

(Im Prinzip ist das alles nicht schlimm, man muss sich dessen beim Definieren der Texte und der Trigger nur bewusst sein. Entsprechend werde ich wohl die Dokumentation da erweitern. Naja und wie immer muss man die Bedeutung kennen.)

Der Ursprungspunkt des Tickets - Nachrichten mit happen_time in der Zukunft nicht als Initialnachrichten zu verwenden bleibt davon unberührt. Und Deine Antwort (in 5 Stunden = in 5 Spielstunden) bestätigt mir, dass es ein Bug in der Implementierung ist.

**Comment by GWRon** [comment]
> Zusammengefasst gibt es also die Realzeit (die man beim Spielen vor dem Rechner verbringt), die Spielzeit (Jahr, Spieltag, Uhrzeit) und - in Ermangelung eines existierenden Terminus - die Tickerzeit. Tickerjahr und Spieljahr sind identisch und die Aufteilung der Tickertage auf Spieltage hängt von der Konfiguration (Spieltage pro Saison) ab.

Ja. Wir haben "GameDate"-Time (Echtjahr + Spieltag/Spieltage-pro-Jahr + Spiel-24-Stunden-Uhr) und "RealDate"-Time (Echtjahr + Echttag + Echt-24-Stunden-Uhr).



@ Def von 4 und 5
Ja da kann die Uhrzeit gerne raus.
Und GERN kannst Du auch die Code-Stellen mit einer kleinen Kommentierung versehen, wenn das fuer dich sonst zu ... "schwammig" ist.

Auch kann gern ein neuer Typ eingefuehrt werden - wenn sich mit den bestehenden noch nicht alles abbilden laesst.

**Comment by nittka** [comment]
Die Uhrzeit bei 4 und 5 wird aktuell in der Datenbank nicht genutzt (überall weniger Parameter definiert, dadurch Fallback auf -1). Ich werde also Dokumentation, Editor und Einlesecode entsprechend anpassen.

Für regelmäßige Nachrichten könnte man sich einen zusätzlichen Typ vorstellen, aber das meiste sollte sich auch mit einem Trigger-Effekt auf sich selbst machen lassen.
Interessant könnte ein NewsFlag setUnavailableOnPublish in Kombination mit modifyAvailable sein. Das würde es erlauben, dass eine Nachricht frühestens nach einem definierten IntervalI (available-Trigger) wieder erscheinen kann.
Aber selbst für diese beiden mit Arbeit verbundenden Möglichkeiten müsste es erstmal überzeugende Anwendungsfälle geben.

**Comment by GWRon** [comment]
Ich habe jetzt den Code ein wenig umgeschraubt - Templates werden nun informiert, wenn die auf sie basierenden NewsEvents "passieren".

Definiert ein Template nun, dass seine HappenTime zurueckgesetzt wird (TVTNewsFlag.RESET_HAPPEN_TIME), so setzt das Spiel "happenTime = -1" sobald das NewsEvent "passiert".

```
			<data genre="0" price="1.0" quality="70" happen_time="1,5,6" flags="64" />
```
Diese Nachricht wird 5 oder 6 Uhr "passieren" - von da an, kann sie jederzeit erneut geschehen (wenn das Spiel die "bereits genutzten" wieder zuruecksetzt und somit als "verfuegbar" einstuft)

**Comment by GWRon** [comment]
Eine potentielle "Unklarheit" seh ich aber zusaetzlich noch

CalcTime_HoursFromNow (typ 1)
```
return nowTime + RandRange(hoursMin, hoursMax) * HOURLENGTH
```
da werden immer volle Stunden zurueckgegeben - will man "heute zwischen 5 und 6 Uhr" angeben, muss "2,0,0,5,6" genutzt werden.

**Comment by GWRon** [comment]
Falls der Fix nicht ausreichend funktioniert, mach den issue wieder auf :)

**Comment by nittka** [comment]
Von den Code-Änderungen sieht es plausibel aus. Ich werde das bei Gelegenheit ausprobieren.
Zum Typ 1: sollte das nicht eigentlich schon immer `return nowTime + RandRange(hoursMin * HOURLENGTH, hoursMax * HOURLENGTH)` gewesen sein?

Nur schonmal als Vorinformation, was mir neben dem Flag "setUnavailableOnPublish" im Kopf rumgeistert. Bei den Effekten gibt es ja neben der Zeit auch noch die Wahrscheinlichkeit. Neben dem resetHappenTime kann ich mir zusätztlich auch noch ein Flag reCalculateHappenTime in Kombination mit probability für eine Hauptnachricht vorstellen. D.h. es wird eine Veröffentlichungszeit berechnet, zu diesem Zeitpunkt aber nur mit der gegebenen Wahrscheinlichkeit veröffentlicht und das Flag (recalculate) sagt, dass in jedem Fall der nächste Zeitpunkt mit dem selben Ausdruck (relativ zur aktuellen Zeit) neu berechnet wird.
Das erlaubt eine leichtere Steuerung von "regelmäßigen" Nachrichten ohne dass sich die Nachrichten selbst triggern müssen, insb. wenn man sauber zwischen Initialnachrichten (0) und Nachfolgenachrichen (2) unterscheiden möchte. Die Börsennachrichten könnten so ohne Selbsttrigger auskommen, Festivals, Ausstellungen, Wahlen könnten unkompliziert regelmäßig zur richtigen Zeit stattfinden.

**Comment by GWRon** [comment]
Dazu muesste auf alle Faelle der originaere happen_time string-Wert im Template hinterlegt werden.
Dann kann gerne erneut berechnet o.ae. werden.

**Comment by GWRon** [comment]
> Von den Code-Änderungen sieht es plausibel aus. Ich werde das bei Gelegenheit ausprobieren.
> Zum Typ 1: sollte das nicht eigentlich schon immer return nowTime + RandRange(hoursMin * HOURLENGTH, hoursMax * HOURLENGTH) gewesen sein?

Ja ich denke es koennte geaendert werden....aber dann laesst sich Typ 1 ja eigentlich ohne Probleme mit Typ 2 abbilden... Oder?

**Comment by nittka** [comment]
Es ist ist tatsächlich die Frage, wie man Typ 1 definiert haben will. 1,1,3= "in 1 bis 3 Stunden" oder "in einer, zwei oder drei Stunden". Mir kommt die erste Interpretation natürlicher vor. Insb. vor dem Hintergrund wie alle anderen Intervalle behandelt werden.
Ist 1 dann überflüssig? Ja, genau wie 4, der durch 5 abbildbar ist, sowie 6 durch 7.

**Comment by GWRon** [comment]
Du kannst da gerne in den Aufraeumarbeiten konsolidieren.

Im Groben braucht man ja nur:
- absolute Realangabe
- absolute Gametimeangabe
- relative Realangabe
- relative Gametimeangabe

Realangabe = 1-365 Tage usw.
Gametimeangabe = 1-x Spieltage pro Jahr usw.



Der Vorschlag mit dem Randomize happen time (o.ae.) da muesste man schauen wie sich das verknuepfen laesst. Es klingt nach "wiederhole aller x-y" aber es laesst sich nicht abbilden "erstmals am x, danach aller y-z".
Eventuell einfach ein "next_happen_time" einfuehren? Loest zwar nicht alle Probleme, aber zumindest obiges liese sich damit abbilden.

**Comment by GWRon** [comment]
Allerdings laesst sich das letztere auch mit zwei Nachrichten abbilden. Erstere macht zweitere (mit dem abweichendem Intervall/happentime+randomreset) "available" und sich selbst "unavailable".

**Comment by nittka** [comment]
Ich probiere gerade die Zeitdefinitionstypen durch. Bei Typ 6 (Spieltag X) scheint bei der Umstellung auf Millisekunden ein one-off-Fehler reingekommen zu sein. Worldtim MakeTime Zeile 78- in der alten Variante wurde korrekterweise (day-1)*24h gerechnet. Nun ist es day*24, wodurch eine für Tag 1 definierte Aktion erst an Tag 2 stattfinden.
Erstmal zur Info. Ich werde eine entsprechende Korrektur im dbfix-Branch einbauen.

**Comment by GWRon** [comment]
>Bei Typ 6 (Spieltag X) scheint bei der Umstellung auf Millisekunden ein one-off-Fehler reingekommen zu sein. Worldtim MakeTime Zeile 78- in der alten Variante wurde korrekterweise (day-1)_24h gerechnet. Nun ist es day_24, wodurch eine für Tag 1 definierte Aktion erst an Tag 2 stattfinden.

![image](https://user-images.githubusercontent.com/2625226/121803639-e497e600-cc42-11eb-8a20-feb3f8f25033.png)

https://github.com/TVTower/TVTower/commit/9a837133fd579557de4f9aec0e21209240c31140

Sieht fuer mich eigentlich aequivalent aus - und davor wurde die Zeile 5 Jahre nicht angeruehrt (laut github). Muesste also schon einige Jahre "fehlerhaft" gewesen sein.

Der Fehler wird aber eher in den Calc-Funktionen (CalcTime_ExactGameDate etc) zu suchen sein - diese sollten bei "GameDay-1" weitergeben so.

**Comment by nittka** [comment]
Ich hatte im Eclipse nur gesehen, dass die Zeile zuletzt bei der Umstellung angefasst wurde und nicht weiter recherchiert - der Kommentar drüber "'old..." hat mich da in die Irre geführt, dass bei diesem Refactoring die Änderung gemacht wurde.
