### ISSUE TITLE
Probleme mit Spielstarteinstellungen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#367]
Bei der mehrfachen Verwendung des Punkts "neues Spiel" in einer Session (Spiel beenden durch zurück zum Hauptmenü und dann wieder neu starten) gibt es im aktuellen Masterstand folgende Probleme:
* bei Änderung der Sprache wird nicht für alle GUI-Elemente die korrekte Lokalisierung verwendet; z.B. wird das Label für den Spielnamen aktualisiert aber nicht die Optionen (24-h-Spiel)
* bei der initialen Auswahl eines Levels (schwer/leicht), wird dieses beim nächsten Start nicht korrekt zurückgesetzt (Popup-Wert und Selektion beim Öffnen passen nicht zusammen)
* etwas kniffliger: wenn man nach einem Spielstart sofort (Figuren fangen an zum Fahrstuhl zu laufen) Escape drückt, zum Hauptmenü zurückkehrt und dann erneut ein Spiel startet (kein Ändern der Spieloptionen nötig), kommt es sporadisch? (bei mir meist zuverlässig beim dritten Start) zu einem Segmentation fault. Die Logausgaben scheinen nicht sehr hilfreich. Ich habe die Soundeffekte im Verdacht. Aktuell habe ich Musik und Effekte angeschaltet. Wenn ich die Effekte ausschalte (Fußgetrappel etc.) tritt der Fehler nicht auf. Wenn sie aber eingeschaltet sind, geht das Getrappel auch weiter, wenn ich das Spiel beendet habe und wieder im Hauptmenü bin. Beim Neustart kommt es dann ggf. zum Segmentation fault.

**Comment by GWRon** [comment]
Spielstartabsturz: kann ich nachvollziehen - und danke fuer den Tipp mit den SFX und der Musik. Die hab ich naemlich sonst bei mir ... aus :)

**Comment by GWRon** [comment]
Absturz ist "ausserhalb" von BlitzMax - also irgendwo im C Code, da muss ich mit GDB mal ran.

**Comment by GWRon** [comment]
https://github.com/bmx-ng/sdl.mod/issues/33

Entweder ist in einem Modul ein Bug - oder irgendwie ziehen wir den Audiolibs die Daten unter den Fuessen weg (die wissen ja nix vom Garabage Collector usw.)

**Comment by GWRon** [comment]
Ok ... also wenn man ein neues Spiel ins Hauptmenue beendet - laeuft das "Fussgetippel" weiter ... was ja so nicht sein sollte.

**Comment by GWRon** [comment]
Ok ... also ich bin schon mal auf dem richtigen Weg ... die SFXChannels zu "stoppen" - derzeit passiert das aber beim "Initialisieren" (also Spieler-neu-machen) heisst die Schrittgeraeusche laufen, bis man erneut auf Einzelspieler klickt.

Aber das bekomm ich auch noch geaendert.

**Comment by GWRon** [comment]
OK ... weiterer "Fehler" war -- das die Laufgeraeusche im Startmenue vom dort herumwuselnden Hausmeister erneuert wurden ... denke dort sollte er ruhig sein.

**Comment by GWRon** [comment]
Alle 3 Punkte sollten nun abgearbeitet sein.

**Comment by nittka** [comment]
Eine Kleinigkeit gibt es noch beim Wechseln der Sprache. Das Anpassen der Höhe der Check-Box-Elemente klappt noch nicht 100%ig. Vor dem ersten Öffnen des Menüs für ein neues Spiel passt es. Wenn man dann aber ins Hauptmenü zurückwechselt, die Sprache umstellt und ein neues Spiel starten will, wird die Höheneinstellung der jeweils vorigen Sprache verwendet. Am besten erkennbar beim Wechsel zwischen Deutsch und Englisch.

**Comment by nittka** [comment]
Ich mache das Ticket mal zu. Das Problem mit den Checkbox-Höhen können wir im Zuge des Kredit-PRs lösen.

**Comment by GWRon** [comment]
Das Problem ist ja nicht, das Rendering der GUI-Elemente, sondern dass diese nicht abhaengig von einander aufgebaut sind - alle haben ihre eigene XY-Positionen.
