### ISSUE TITLE
GUI: Liste + Resize kann zu Problemen fuehren

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#368]
![Peek 2021-06-13 22-14](https://user-images.githubusercontent.com/2625226/121820753-c9ee5d00-cc94-11eb-8c8e-9e13368a555d.gif)

Im Studio mehrere Einkaufslisten vorraetig haben -- die unterste anklicken (es muss gescrollt sein), dann Rechtsklick und die Liste wird ja wieder "verlaengert". Alle Elemente sind unsichtbar / weggescrollt (und kein Scrollbalken vorhanden)

**Comment by nittka** [comment]
Ursache ist Zeile 1027 in game.screen.supermarket.production.bmx
Hier soll beim Vergrößern des Bereichs die Scrollposition wie in der kleinen Variante gesetzt werden. Dadurch sollte erreicht werden, dass bei vielen Einträgen (z.B. 10) - wenn der letzte bearbeitet wurde - der gesamte neu verfügbare Bereich genutzt wird. Wenn aber nur wenige Einträge existieren, führt das Setzen der Position aber offensichtlich zum Fehler. Ggf. müsste noch geprüft werden, ob nach der Größenänderung der Scrollbalken überhaupt sichtbar ist.
