### ISSUE TITLE
KI: Sendet viel Wiederholung

### ISSUE THREAD

**Issue by sushidelic** [TVTower/TVTower#37]
Die KI sendet sehr viel Wiederholung des Programms, bzw. habe ich aktuell ein Spiel, da hat die KI keine einzige Sendung am ersten Tag gekauft sondern das Startprogramm einfach Wiederholt. (alle 3 KI Spieler)

**Comment by GWRon** [comment]
Eventuell ist die Ursache in einer uebertriebenen Sparsamkeit begruendet? KI will sparen (Sendemastkauf) und sendet deswegen nur "Ramsch".

**Comment by sushidelic** [comment]
also die KI nimmt auch Kredit auf, ich weiss nur nicht für was :)
ach ja, Nachrichten Investiert die KI wohl fleißig, wobei ich denke das diese nicht so gut ausbalanciert ist also die Nachrichten selber ... da mag ich mich jetzt aber mal nicht zu sehr aus dem Fenster lehnen ;)

das lasse ich also derzeit auch aussen vor
das ist, denke ich mal, eine Sache für später mal, ersteinmal die Werbung in Angriff nehmen :)

wie war das, zu viele Baustellen verderben den Fahrspaß ;)

**Comment by GWRon** [comment]
Die KI sollte nun zumindest das Startprogramm selbststaendig auffuellen. Wiederholungen sind erzwungen, sobald es keine Alternativen gibt (zuwenig Programme im Portfolio).
