### ISSUE TITLE
Berlin vs. Brandenburg

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#372]
Ich glaube das im Forum gemeldete Problem mit den Kabelnetzen Berlin und Brandenburg hat auch mich erwischt. Ich glaube, der Fehler tritt nicht unmittelbar beim Buchen des Netzes auf. Ggf. beim Laden/Speichern, automatischen Verlängern... kommt es zum Fehler.

Ich glaube zu  einem früheren Zeitpunkt Brandenburg gebucht zu haben. Im Spielstand wird aber "Berlin" im Hover über dem Bundesland und in der Liste angezeigt. Wenn ich den Vertrag kündige, wird wieder korrekt Brandenburg angezeigt.

**Comment by GWRon** [comment]
Puhh. Ich waere fuer Tipps zur Nachvollziehbarkeit mehr als dankbar :)

**Comment by GWRon** [comment]
![image](https://user-images.githubusercontent.com/2625226/123395697-c9ad6600-d5a0-11eb-979e-36c5d491ea0e.png)

Den oberen Streifen da beim Sprite...schau ich mir nochmal genauer an

**Comment by GWRon** [comment]
![image](https://user-images.githubusercontent.com/2625226/123400537-295a4000-d5a6-11eb-8425-22c9dc7c3f9f.png)

Jopp - die Koordinate von Berlin innerhalb des Spritesheets schloss einen Teil einer anderen Grafik mit ein.

Entsprechend koenne es beim Platzieren der "Uplink-Grafik" (eines Sendemastes) dazu gekommen sein, dass die Koordinate beispielsweise den Rand da oben erwischte.

Neben dem Rand, kann es aber generell zu kleinen Ueberlappungen der sprites kommen (also ein Pixel von Berlin wird auch vom Brandenburgsprite genutzt usw.)
Wenn nun genau dieser Pixel ausgewaehlt wuerde ... und dann die "Bundesland-Liste" nicht immer gleich sortiert ist (also mal Berlin und mal Brandenburg zu erst "abgearbeitet" wuerde), dann .. koennte eben dieser ueberlappende Pixel falsch interpretiert werden

Der Pixel wuerde also sowohl Brandenburg als auch Berlin zugeordnet werden _koennen_ - aber beim ersten "Treffer" wird dieser zurueckgegeben.


Der einfachste Ansatz waere es wohl, fuer jedes Bundesland haendisch eine "Uplinkkoordinate" zu vergeben ... um "Unklarheiten" zu vermeiden.

Ein anderer Ansatz:
Die gewaehlte "Zufallskoordinate" muss sicherstellen, dass sie fuer kein anderes Bundesland "gueltig" ist (also ebenfalls "opacque")
Und wir sollten die Reihenfolge der Bundeslaender in der Liste "sicherstellen" (ueberpruefen ob da irgendeine Sortierung stattfindet)

**Comment by GWRon** [comment]
Entsprechend betrifft das uebrigens nicht nur "berlin - brandenburg", auch "brandenburg - sachsen" usw. ist eine Moegliche "Ueberlappung".

**Comment by GWRon** [comment]
Muss mich korrigieren ... die entsprechende Funktion wurde gar nicht dafuer genutzt - die ist nur fuer die KI im Einsatz.

Auch "SetSectionName" nutzte die "Pixel" um eine valide xy-Position fuer den "Uplink" zu ermitteln. Das wurde aufgerufen, wenn mit der Maus auf der Senderkarte interagiert wurde ... da haette eigentlich schon das andere Bundesland angezeigt werden sollen - wenn da was schief gelaufen waere.

hmm.

**Comment by GWRon** [comment]
Habe die Koordinaten der Sprites nachgebessert - hoffentlich fixt das da auch gleich den Fehler hier.

**Comment by nittka** [comment]
Das Problem ist leider noch nicht behoben. Ich habe jetzt aber einen Ablauf, der das ganze reproduzierbar machen sollte.

* neues Spiel 1990 starten
* Cheat Geld 10 Mio, Cheat Image 30%
* Spiel speichern (damit man das nicht immer wieder machen muss)
* Kabelnetzanbindung Brandenburg buchen
* Spiel (unter neuem Namen) speichern
* dieses Spiel wieder laden

Im aktuellen Masterstand wird nach dem letzen Laden in der Liste der Kabelnetzanbindungen "Berlin" angezeigt und wenn man den Listeneintrag anklickt wird auch der Kartenausschnitt von Berlin hervorgehoben. Der "Senderindikator" auf der Karte ist aber auf der Position von Brandenburg!

**Comment by nittka** [comment]
Wird für das Speichern im Spielstand ein "zufälliger" Pixel bzw. die Mitte des Bilds verwendet? Ist das überhaupt nötig oder könnte man nicht einfach für jedes Bundesland ein festes Pixel aus der DB nehmen. Fraglich ist, warum überhaupt Koordinaten verwendet werden sollten und nicht direkt eine ID des Kabelnetzes (falls Pixel für die Persistenz verwendet werden).

**Comment by GWRon** [comment]
> Der einfachste Ansatz waere es wohl, fuer jedes Bundesland haendisch eine "Uplinkkoordinate" zu vergeben ... um "Unklarheiten" zu vermeiden.

Ja... das waere halt die andere Option. Unabhaengig davon sollte die "ausgewuerfelte" Koordinate aber ja nun "save" sein (nicht mit einem anderen Bundesland kollidieren).

Deswegen ist nun erstmal herauszufinden, wo genau der Fehler liegt - danach, kann immer noch direkt in der DB definiert werden (und bei Nichtvorhandensein, faellt es auf den dann hoffentlich fehlerfreien Zufallsmodus zurueck).

**Comment by GWRon** [comment]
> Das Problem ist leider noch nicht behoben. Ich habe jetzt aber einen Ablauf, der das ganze reproduzierbar machen sollte.

Kann ich nachvollziehen. Danke.

**Comment by GWRon** [comment]
Habe die Berechnungen ueberarbeitet.
Wird in der map.xml (germany.xml) kein uplinkX und uplinkY definiert, wird eine zufaellige Position im Bundesland genommen (vorrangig aber die Mitte des Bundeslandes).
Gleiches gilt natuerlich auch fuer Speicherstaende.

In der map.xml kann nun
```xml
				<state name="brandenburg"		x="340" y="68"	sprite="map_brandenburg">
					<config uplinkX="100" uplinkY="30" />
				</state>
```
direkt die uplink-Position definiert werden.

Vielleicht hast Du ja ein paar gute "Koordinaten" im Sinn?
Alle Koordinaten sind "lokal" zur jeweiligen "sprite" zu sehen, und nicht global zur Senderkarte.

**Comment by nittka** [comment]
Die Antenne bei Potsdam war schon nachvollziehbar. Vielleicht muss sie nur etwas von Berlin wegwandern. config uplinkX="75" uplinkY="54"?

**Comment by GWRon** [comment]
Wir koennen sie ruhig so (alle) legen, dass sie sich (wenn alle genutzt sind) nicht unbedingt irgendwie ueberlagern.


Bei Bedarf kann ich denen auch ein eigenes Sprite pixeln.

**Comment by nittka** [comment]
Die anderen Bundesländer sind doch OK, oder? Da muss man sich nicht die Arbeit machen, andere Positionen zu suchen. Soll ich für den Brandenburg-Uplink einen PR stellen?

**Comment by GWRon** [comment]
Die anderen sind OK.. denke ich.

Einen PR erfordert es ja nur, wenn einem die ausgewuerfelte Position nicht zusagt. Aber ja, sollte an sich reichen

**Comment by nittka** [comment]
Ich wäre dafür, die Position für Brandenburg festzulegen. Das Auswürfeln der Position könnte verwirren -  insb. da sie sich nur in Brandenburg ändert, nicht aber in den anderen Bundesländern.

**Comment by GWRon** [comment]
Sachsen und Saarland hatten auch nicht die besten automatischen Positionen.

Kannst hier gerne zumachen, wenn die Sache hier damit erledigt waere.
