### ISSUE TITLE
Drehbuchvorlagen von Kasi

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#373]
Ich habe im Branch https://github.com/TVTower/TVTower/tree/kasiScripts mal die Drehbuchvorlagen von Kasi überarbeitet (Link zum Forum siehe erster Commit).

* erstes Korrekturlesen
* Übersetzung eines Großteils, der noch nicht auf Englisch vorlag
* ein paar Anpassungen Flags/Besetzung
* Auskommentieren der Skripte, die ich nicht so überzeugend fand

Ich habe die Originaldatei erstmal zum Vergleich mit daneben liegen lassen und Einzelcommits für jedes Drehbuch gemacht.

**Comment by GWRon** [comment]
https://github.com/TVTower/TVTower/blob/84773ad7b48e85a91974e51b420204c8e94784f8/res/database/Default/user/kasi.xml#L77

-> geradenen

**Comment by GWRon** [comment]
https://github.com/TVTower/TVTower/blob/84773ad7b48e85a91974e51b420204c8e94784f8/res/database/Default/user/kasi.xml#L350

-> Verfuegbarkeit auf "ab 200x" oder so? Geht um Streamingdienste...

https://github.com/TVTower/TVTower/blob/84773ad7b48e85a91974e51b420204c8e94784f8/res/database/Default/user/kasi.xml#L416
-> "und er" 58.

https://github.com/TVTower/TVTower/blob/84773ad7b48e85a91974e51b420204c8e94784f8/res/database/Default/user/kasi.xml#L426
-> "z.B. eein" hat ein e mehr als benoetigt

https://github.com/TVTower/TVTower/blob/84773ad7b48e85a91974e51b420204c8e94784f8/res/database/Default/user/kasi.xml#L436
-> "Profihynotiseur" -> "Profihy_p_notiseur"

https://github.com/TVTower/TVTower/blob/84773ad7b48e85a91974e51b420204c8e94784f8/res/database/Default/user/kasi.xml#L867
-> "paralelle" -> "parallele"

**Comment by GWRon** [comment]
https://github.com/TVTower/TVTower/blob/84773ad7b48e85a91974e51b420204c8e94784f8/res/database/Default/user/kasi.xml#L1085
-> "zum nacherzählen für alle" wuerde ich als "zum Nacherzählen für Alle" schreiben.

https://github.com/TVTower/TVTower/blob/84773ad7b48e85a91974e51b420204c8e94784f8/res/database/Default/user/kasi.xml#L1102
"Das Blondinen dumm sind, ist ein Mythos dies" -> "Das Blondinen dumm sind ist ein Mythos, dies"

Ab da ists eh noch "nur deutsch", da hast Du evtl noch vor, selber drueberzuschauen.

"Kasi-script-Metalsucher" koennte man eventuell reaktivieren, aber da muss eh noch einiges an der Rechtschreibung gemacht werden. Auch wuerde ich ueberlegen, diese "Pleitesache" kuerzer zu fassen (ohne den Wissenschaftler).

**Comment by nittka** [comment]
Ja, bei Comedy hat mir auch die Motivation gefehlt - da es im Englischen ggf. andere Standardwitze gibt. Ggf. kann man das komplett ohne Überseztung lassen.

**Comment by nittka** [comment]
Ich habe die Rückmeldungen eingearbeitet, Comedy korrekturgelesen und die Schatzsucher reaktiviert (beides ohne Übersetzung). Die darauffolgenden Templates hatte ich auch schon bearbeitet, wobei ich die magischen Wesen nicht übersetzt hatte.

Für Vorlagen wie "Sprich mit X", "Livekonzert von X" (und Programme wie Kochen mit Patty Glanson?) wäre es eigentlich cool, wenn auch die Besetzung eine Variable entalten könnte (`<job function="1" index="0" required="1" person="%GUID%"/>`, wobei person eine feste ID oder eine Variable sein kann). Dann kann die Variablendefinition mehrere IDs enthalten, bei der Drehbucherstellung wird dann eine Person zufällig ausgewählt und der Name steht via [1|full] automatisch im Titel zur Verfügung. Aktuell steht bei "Sprich mit X" zwar ein Name im Titel, aber bei der Besetzung wird die entsprechende Person nicht wirklich als Moderator dabei sein.

**Comment by GWRon** [comment]
Den letzteren Punkt verstehe ich jetzt nicht - bzw. bin ich mir nicht sicher.

Also du willst, dass man einen "Pool" an GUIDs definieren kann, und der wird dann benutzt?

Also so, dass man eine Person "vordefinieren" und im Titel/Text referenzieren kann?

Kochen mit 1|FULL
job von "1" definiert fuer Person (GUID1, GUID2, GUID3)
Beim Produzieren wird 1|FULL "ausgefuellt?


Ich haette das eher so angesetzt: 
- Enthaelt ein Titel einen "Variablenname", wird dieser bei Anzeige (Drehbuch) aufgehuebscht (`1|FULL` = `[Name des Stars]` also `Kochen mit [Name des Stars]` (woertlich, das ist kein Platzhalter))
- Alternativ "Anzeigetitel" in der DB hinterlegen (der wird solang angezeigt, bis die Produktion "angeworfen" wird)
- Anstatt GUIDs vorzudefinieren, koennte hier jeder x-beliebige genutzt werden

Weiterhin waere natuerlich auch ein "Sprich mit X" und einer limitierten GUID-Auswahl was anzufangen .... dann sollte die Person aber auch "am Leben" sein (bereits geboren und noch nicht gestorben). Muss man dann sicherstellen.
die Person waere dann bei Planung einer Produktion:
- vorauszuwaehlen
- zu fixieren (keine Aenderung moeglich, "disable" und "Dragndrop-Austausch" verhindern)

**Comment by nittka** [comment]
Die Thematik ID-Liste für eine Besetzung sollten wir in ein separates Ticket auslagern (mein Fehler). Ich behalte das mal im Hinterkopf.

Die Texte sind jetzt alle einmal überarbeitet. Ich mache noch ein paar Testproduktionen und schraube noch etwas an den Flags. Einen PR würde ich stellen, wenn ich damit fertig bin.

**Comment by GWRon** [comment]
Danke Dir.

**Comment by nittka** [comment]
Ich bin in den letzten Zügen der Überarbeitung. Mich stört etwas, dass bei fast allen Vorlagen "Kult" als Flag oder optionales Flag angegeben ist. Das halte ich für übertrieben. Ich finde, dass nur die drei oder vier besten Vorlagen ein optionales Flag bekommen sollten...

**Comment by GWRon** [comment]
Ja es sollte nicht "immer" gesetzt werden. Ist wie das inflatorisch genutzte "Trash".

**Comment by nittka** [comment]
In den letzten beiden Commits habe ich Kult (nun 4 von 20) und Trash (6 von 20) etwas ausgedünnt. Bei Trash fällt mir das schwerer, da viele der Serien wirklich eher Trash-Charakter haben.
(insb. bei therob gibt es noch vergleichsweise viel Trash und Kult)
