### ISSUE TITLE
Drehbuch Flagkombination Trash+Live

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#376]
Aktuell sieht es so aus, als ob eine Produktion, die sowohl das Flag Live als auch Trash hat in der Programmauswahl sowohl unter Live als auch unter Boulevard erscheint. Die Frage ist, ob eine solche Dopplung gewünscht ist, oder ob in diesem Fall "Live" den Vorrang bekommen sollte.

Weitere Fragen:
* Wird das Flag "live" automatisch nach der ersten Ausstrahlung in LiveOnTape umgewandelt? Denn eine Sendung kann ja nur einmal live ausgestrahlt werden und sollte danach nicht mehr in der "Live"-Programmauswahl erscheinen.
* Man kann ja einen Ausstrahlungszeitraum (Slot von bis) definieren, was bei Live-Sendungen sinnvoll einsetzbar ist. Aber es scheint keine Möglichkeit zu geben, diese Einschränkung für Wiederholdungen aufzuheben...

**Comment by GWRon** [comment]
Also es sollte "LiveOnTape" draus werden, und dann wird es in die jeweilige "normale" Genreschublade gesteckt (hier also vielleicht "Sonstiges" - bzw mit Trashflag dann halt Trash)


Der Ausstrahlungszeitraum sollte nur für Livesendungen Gültigkeit besitzen. Wiederholungen ("Live on tape") sollten davon ausgeschlossen sein. Ist dem nicht der Fall?

**Comment by nittka** [comment]
Also wenn ich Kasi's Livekonzert etwas anpasse (Live, Familie, Trash, 2 Ausstrahlungen), kann ich nach Spielstart die Show zwar sofort produzieren, aber erst am zweiten Tag senden, da am ersten Tag erst ab 23 Uhr ein grüner Slot angezeigt wird. Die Show wird wie erwartet bei Live eingeordnet.
Nach der ersten Ausstrahlung, ist die Einordnung aber noch immer in Live und der Ausstrahlungzeitraum bleibt eingeschränkt. Daher würde ich vermuten, dass das Umsetzen auf LiveOnTape nicht korrekt erfolgt.

```
<data flags_optional="16" flags="9" production_broadcast_limit="2" broadcast_time_slot_start="19" broadcast_time_slot_end="23"/>
<genres maingenre="9" />
```

**Comment by GWRon** [comment]
23 Uhr: Das liegt daran, dass die "Produktionszeit" da noch hinzugefuegt wurde ... stammt also noch aus der Zeit, in der es keine "Vorproduktionen + Liveproduktionen" gab.

Probleme seh ich auch fuer Drehbuchdatenblaetter - denn die wissen ja noch nicht den exakten fruehstmoeglichen Ausstrahlungszeitpunkt (verbesserbar bei Produktion mit gutem Team etc).

**Comment by GWRon** [comment]
Ich wuerde gern das Feld "liveTime" bei TScriptBase entfernen - das laesst sich ja ohne Probleme mit "broadcastTimeSlotStart" und "broadcastTimeSlotEnd" umsetzen.

Allerdings waere es ein groesserer Aufwand, Speicherstaende kompatibel zu halten (SaveGameLoaded-Event abfangen, "lifeTime" erstmal als "{nosave}" beibehalten, ... Werte uebernehmen - und irgendwann, nach einigen Versionen, das Feld entfernen). Fraglich ob ueberhaupt notwendig.

**Comment by nittka** [comment]
"live_time" wird in der Datenbank wird gar nicht verwendet. Wenn also liveTime aus dem Code heraus nicht exzessiv gesetzt/verwendet wird, sollte das Entfernen (ohne Abwärtskompatibilität) kein Problem sein.

Für Selbstgeschriebenes ist die Live-Ausstrahlungszeit ja ohnehin der erste Ausstrahlungszeitpunkt. Für automatisch erzeugte Sportprogramme und Programme wie den Ariane-Start sollte eigentlich die Kombination aus Live-Date und broadcastTimeSlot konzeptionell funktionieren - damit ist doch "Live-Programm muss 20 Uhr ausgestrahlt ausgestrahlt werden" abgedeckt, oder? Danach ist es dann einfach nicht mehr live, sondern liveOnTape.

Ich sehe auch keinen Mehrwert in der Forderung, dass eine Wiederholung zu einem bestimmten Zeitraum gesendet werden muss. Zu überlegen wäre, ob die broadcastTimeSlot-Vorgabe grundsätzlich nur für die erste Ausstrahlung gilt und Wiederholungen dann immer gesendet werden können (egal ob live oder nicht). Aktueller Vorschlag (nah am aktuellen Verhalten bleiben): Wenn live, dann entfällt die Slot-Vorgabe nach der ersten Ausstrahlung, wenn nicht live dann bleib sie bestehen.

**Comment by GWRon** [comment]
Eine weitere Option waere einfach ein neuer flag... "First broadcast removes broadcast slot restriction" (nur knapper beschrieben).

**Comment by nittka** [comment]
Daran habe ich auch gedacht, wollte es aber nicht vorschlagen. Vielleicht sollte man aber in Vorbereitung an ein solches neues Flag (wenn man es denn irgendwann brauchen sollte), das Verhalten jetzt schon vereinheitlichen, d.h. Slot gilt nur für Erstausstrahlung (spätere Einführung für "Keep broadcast slot restriction").

**Comment by GWRon** [comment]
Kommt halt drauf an, was so die Standardanwendung waere.

Denke aber auch, dass Standard die Entfernung der Restriktionen sein sollte.

**Comment by nittka** [comment]
Siehe Edit: für die Ted-Programme wäre das Entfernen als Standard nicht sinnvoll. Ggf. also lieber doch neues Flag (slotRestrictionOnlyForFirstBroadcast), welches man dann in der Datenbank sofort einbauen kann.

**Comment by GWRon** [comment]
An die Ted-Programme dachte ich auch.
im Groben sind die Zeitfenster ja eh nur fuer besondere Dinge ("Fruehstuecksfernsehen", "Abendshows") und da koennen wir die Flags entsprechend setzen.

**Comment by GWRon** [comment]
Das "von bis" beinhaltet nun NICHT mehr "bis" (also slots von 20-23 bei einem 2Block-Film bedeutet, man kann 20 oder 21 Uhr starten, vorher waere auch 22 moeglich gewesen, "end" also inklusiv, nicht exklusiv).

Weiterhin sollten nun die Datenblaetter "Drehbuch" und "Produktion" etwas genauere Angaben machen koennen - auch wenn natuerlich fuer Drehbuecher nur "geschaetzt" (Da dort das Produktionsteam noch nicht klar ist).



Das Problem "live -> live on tape" hab ich mir noch nicht angeschaut.

**Comment by GWRon** [comment]
Der neue Flag heisst "TVTBroadcastMaterialSourceFlag.KEEP_TIMESLOT_RESTRICTONS_ON_BROADCAST" und ich denke es ist sorum besser... also Programme die Live sind und explizit ein Zeitfenster gesetzt bekommen, sollten diesen Flag setzen.

Einfachere Live-Programme haben ein Zeitfenster und verlieren danach einfach diese Beschraenkung.

Die Beschraenkung wird entfernt, sobald die (Live-)Programmausstrahlung begonnen hat.

**Comment by GWRon** [comment]
Du muesstest jetzt mal schauen, was von dem Issue fuer dich noch "offen" ist - bzw ob das jetzt auch so funktioniert, wie du es dir vorgestellt hast.

Weiterhin braeuchten beide TEDs in der DB dann den neuen Flag -- das dies in Speicherstaenden nun nicht korrigiert ist, halte ich fuer "akzeptabel".

**Comment by nittka** [comment]
Die Änderungen sind ja schon ziemlich umfangreich. Ich werde mir das mal anschauen (testspielen - wird etwas dauern).

Ein print ist dringeblieben. Bei der Produktionszeit für Live-Produktionen ist mir die Basis-Produktionszeit noch nicht so klar: Es gibt die Vorproduktion, die relativ schnell geht und dann gibt es die Live-Sendung. Eine sonstige Produktionszeit mit Faktor gibt es doch nicht, oder? Man könnte lediglich das Studio im Anschluss an die Ausstrahlung zum Aufräumen blocken.

**Comment by nittka** [comment]
Die Änderungen sind ja schon ziemlich umfangreich. Ich werde mir das mal anschauen (testspielen - wird etwas dauern).

Ein print ist dringeblieben. Bei der Produktionszeit für Live-Produktionen ist mir die Basis-Produktionszeit noch nicht so klar: Es gibt die Vorproduktion, die relativ schnell geht und dann gibt es die Live-Sendung. Eine sonstige Produktionszeit mit Faktor gibt es doch nicht, oder? Man könnte lediglich das Studio im Anschluss an die Ausstrahlung zum Aufräumen blocken.

**Comment by nittka** [comment]
Beim kurzen Testspielen mit einer selbst produzierten Liveshow sieht es so aus, als ob die Auswertung der Flags Trash+Live nun passt.

Das Flag KEEP_TIMESLOT_RESTRICTONS_ON_BROADCAST wird aber scheinbar vom Template nicht ins Programm übernommen. Ich habe beim obigen Skript für die Gala  production_broadcast_flags="32768" gesetzt, damit auch die zweite Ausstrahlung im geforderten Slot stattfinden. Nach der LIve-Ausstrahlung kann die Show aber ohne Einschränkungen platziert werden.

Auf das Ausstrahlungslimit (2x erlaubt") wird zwar im Drehbuch-Datenblatt hingewiesen, im Programmplaner sieht man das aber nicht mehr. Das Programm verschwindet aber wie erwartet nach der zweiten Ausstrahlung.

Soll ich dafür ein separates Ticket aufmachen?

**Comment by GWRon** [comment]
Ja neues Ticket fuer Probleme mit dem Ausstrahlungslimit.


Den Flag schau ich mir dann noch mit an.

**Comment by GWRon** [comment]
Der neue Flag wurde gar nicht in "GetIndex" von  "TVTBroadcastMaterialSourceFlag" erfasst.
