### ISSUE TITLE
Programmdatenblatt Ausstrahlungslimit

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#377]
Wenn man eine Drehbuchvorlage mit Ausstrahlungslimit (z.B. 2x) definiert, wird beim Drehbuch darauf hingewiesen (nur 2 Ausstrahlungen möglich). Nach Fertigstellung der Produktion sind dann auch tatsächlich nur zwei Ausstrahlungen möglich und das Programm verschwindet aus dem Planer, aber im Datenblatt wird auf diese Einschränkung nicht mehr hingewiesen.

Wenn ich mich richtig erinnere, gab es ein solches Limit auch bei den Fußball-Liveübertragungen. Gibt es eine einfache Möglichkeit, für Tests das Vorhandensein einer Liga-Produktion zu erzwingen?

**Comment by nittka** [comment]
Ich habe Ted am Morgen mal ein broadcast_limit von 2 gegeben. Dieses wurde im Datenblatt angezeigt (und Programm verschwand nach der zweiten Ausstrahlung). data_broadcast_limit hingegen hatte scheinbar überhaupt keine Auswirkung.

**Comment by GWRon** [comment]
data_broadcast_limit -> setzt das Limit fuer ProgrammeData (also bspweise einen bestimmten Film X)
licence_broadcast_limit -> setzt das Limit fuer eine bestimmte Lizenz (also bspweise "Film X" einem Filmpaket, oder eine Spezialfassung).

Derzeit wird an sich beides gleichgesetzt, aber bei kuenstlich generierten (abseits der DB) kann das ja durchaus vorkommen. Oder dann spaeter auch per DB, im Zusammenhang mit Filmpaketen/Lizenzpacks.


Das Problem ist hier jetzt, dass Programmlizenzen noch nicht auch die Programmedata zwecks derer Limits anfragen - nur ihre eigenen.

**Comment by nittka** [comment]
Zumindest für die Show-Eigenproduktion funktioniert die Anzeige im Datenblatt nun.
Wenn ich dem Ted *jetzt* aber ein Limit geben möchte (egal in welcher Variante - data, licence oder direkt broadcast_limit), wird das Limit nun gar nicht mehr berücksichtigt (ggf. Anpassung DB-Einlesecode nötig?). Vor der Änderung hatte das noch funktioniert.

**Comment by GWRon** [comment]
Hmm ich hatte direkt mit TED ausprobiert und das ging.

Vlt kurz beschreiben, was genau nicht geht?

**Comment by GWRon** [comment]
Also mein Vorgehen:
- database_programmes.xml oeffnen
- "Ted am Morgen" raussuchen
- <data> erweitern `data_broadcast_limit="2"`
- speichern
- neues Spiel .. start 2005
- Enter ... "/dev givelicence 1 6cab2" ... Enter
- ab zum Filmhaendler/Buero/...

![image](https://user-images.githubusercontent.com/2625226/125201874-4f076a80-e271-11eb-9e5c-56431f240f0d.png)

**Comment by nittka** [comment]
OK. Das geht bei mir auch (noch). Aber wenn ich noch die broadcast-flags dazunehme, mit denen die Time-Slot-Beschränkung beibehalten werden soll, dann geht das Limit verloren. Also entweder das neue Flag geht oder das Ausstrahlungslimit, aber aktuell nicht beides gleichzeitig (bei Programmen in der Datenbank).

**Comment by GWRon** [comment]
Als Erinnerungshilfe fuer mich: Begrenzungen der Ausstrahlungszeit sollten lokalisiert werden.

Wenn nur die erste Ausstrahlung betroffen sein wird...
Erstausstrahlung nur zwischen...
Vgl mit
Ausstrahlung nur zwischen...


Wenn ein limit bei 1 ist...nicht ", Erstausstrahlung" nennen

**Comment by GWRon** [comment]
Der fehler lag im DB-Laden.

programmeData.broadcastFlags = data.GetInt("data_broadcast_flags", data.GetInt("broadcast_flags", programmeData.broadcastFlags))

-> wenn "broadcast_flags" definiert war, wurde dieser Wert gesetzt, der "vorherige broadcastFlags"-Wert wurde dann ignoriert (da nur als "fallback"-Wert uebermittelt).

**Comment by GWRon** [comment]
"Erinnerungshilfe" auch umgesetzt.

**Comment by nittka** [comment]
Die broadcast-Flags funktionieren noch nicht wie erwartet.
Verwendet man für ein Programm (Beispiel Ted) broadcast_flags für das Beibehalten der Slot-Beschränkung, dann passt es. Verwendet man data_broadcast_flags, steht im Datenblatt zwar, dass die Einschränkung nur für die Erstausstrahlung gilt, aber auch danach kann der Ted (korrekterweise) nur zwischen 6 und 11 Uhr gesendet werden (Datenblatt falsch). Verwendet man licence_broadcast_flags wird im Datenblatt zunächst korrekt angezeigt, dass die Ausstrahlung global begrenzt ist, aber nach der ersten Ausstrahlung verschwindet die Beschränkung dann fälschlicherweise.

Ist es für die Datenbank tatsächlich nötig, die Unterscheidung zwischen data_broadcast_flags und licence_broadcast_flags zu machen. Wenn man ein Programm (irgendwann mal) referenzieren würde und andere Flags als dort haben möchte, kann man sie doch überschreiben; d.h. ausschließlich broadcast_flags erlauben.

**Comment by GWRon** [comment]
Wie willst du die denn "ueberschreiben"?

Dazu muesste man ja immer noch bei TProgrammeLicence die Broadcastflags haben und bei TProgrammeData ebenso.

Ansonsten aendert man ja das zugrundeliegende ProgrammeData-Objekt, dass evtl von mehreren Lizenzen genutzt wird.


Bspweise eine Lizenz von FilmX, die aber halt nur zwei mal benutzt werden kann (dafuer aber billiger ist als die unbeschraenkte Lizenz...aber beide nutzen das zugrundeliegende Filmchen "ab").

**Comment by nittka** [comment]
Die naive Idee war, in der Datenbank ausschließlich broadcast_flags zu erlauben (die ja scheinbar ohnehin als Fallback verwendet werden). Wenn man ein anderes Programm in der Datenbank referenziert, "erbt" man die dort definierten Flags, außer in der Datenbank sind für den referenzierenden Eintrag selbst welche definiert. (D.h. es bleibt bei der Objekttrennung zwischen Lizenz und Data mit eigenen flags, nur dass diese Flags aus demselben Datenbankfeld befüllt werden.)
Spricht technisch etwas gegen diesen Ansatz? Gibt es Fälle, die dadurch nicht abgedeckt werden können? Falls das nämlich so passt, würde ich die broadcast_flags so in die Datenbank-Doku und den Editor einbauen. Da sind sie nämlich noch gar nicht behandelt.

**Comment by GWRon** [comment]
Hmm evtl koennte man das so machen. Wollte wohl damals mehr Flexibilitaet einbauen als notwendig.

Aendert aber dann nichts an der Sonderbehandlung (lizenz und data zwecks der flags und limits abfragen).

**Comment by nittka** [comment]
OK. Dann passe ich Dokumentation und Editor entsprechend an. Wenn es dann mit Referenzen auf Programmdaten ein Problem gibt, mache ich ein separates Ticket auf. Zunächst gibt es aber andere Baustellen.

**Comment by GWRon** [comment]
Ich mach das hier nochmal auf ... wir haben ja die individuellen broadcast_flags ... und auch die individualisierbaren broadcast_limits.

Fuer die DB waere die Unterscheidung zwischen `data_broadcast_limit` und `licence_broadcast_limit` ebenfalls nicht mehr notwendig oder?

>Die broadcast-Flags funktionieren noch nicht wie erwartet.
>Verwendet man für ein Programm (Beispiel Ted) broadcast_flags für das Beibehalten der Slot-Beschränkung, dann passt es. Verwendet man data_broadcast_flags, steht im Datenblatt zwar, dass die Einschränkung nur für die Erstausstrahlung gilt, aber auch danach kann der Ted (korrekterweise) nur zwischen 6 und 11 Uhr gesendet werden (Datenblatt falsch). Verwendet man licence_broadcast_flags wird im Datenblatt zunächst korrekt angezeigt, dass die Ausstrahlung global begrenzt ist, aber nach der ersten Ausstrahlung verschwindet die Beschränkung dann fälschlicherweise.

waere ja so oder so noch offen (es muessen die broadcastflags von data und licence herangezogen werden)

**Comment by nittka** [comment]
Meine Anfrage bezog sich ja insb. auf die Unterscheidung in der Datenbank. Dort unterstütze ich aktuell nur die "nicht individualisierten" Flags und Limits.

**Comment by GWRon** [comment]
Hmmm ... muessten wir das nicht eigentlich auch auf jeweils zwei Schluessel runterbrechen koennen?
broadcast_limit -> setzt "data" (licence bleibt bei "nutze das von Data, keine individuelle Einstellung")
licence_broadcast_limit -> setze individuelles Lizenzlimit (Data bleibt unberuehrt)

gleiches fuer flags.

Wenn die Lizenz bei "habe nix eigenes definiert" eh immer bei Data nachschaut ... waere das ja voellig ausreichend. 


Man braucht das selbst vielleicht nicht in der DB/Editor-Logik "bis jetzt" nicht zu unterstuetzen - wuerde aber besser die interne Spiellogik ("hab nix definiert, vielleicht aber hat Data ja was?") widerspiegeln.

**Comment by nittka** [comment]
Ja, den Gedanken, dass die data-Variante überflüssig ist, hatte ich auch. Eine globale (data+licence) und eine licence-spezifische Variante decken alles ab.

**Comment by GWRon** [comment]
zwecks "flags" bin ich mir nicht sicher, ob ein "licence_broadcast_flags" erweitern, oder komplett ersetzen sollte.
Denn es gibt ja kein "remove/unset flags" per DB. Es waere also derzeit immer nur ein "hinzufuegen" moeglich.
Oder halt der komplette Ersatz ("ist was definiert, wird die komplette Bitmaske ueberschrieben").

**Comment by nittka** [comment]
Ich wäre für Überschreiben - das ist für den Datenbankbearbeiter am einfachsten zu verstehen. Man schaut sich die Flag-Definition im Eintrag an und sieht, was gemeint ist.
Ich glaube nicht, dass man häufig in die Verlegenheit kommt, dass die data-flags erweitert werden und man das dann "vergisst", in den Einzellizenzen nachzuziehen.

**Comment by GWRon** [comment]
Ist alles n bisschen "kuddelmuddel". Bin da nicht ganz so zufrieden mit - aber wuesste auch nicht, wie wir das besser machen koennten.

Jetzt wird beim DB-Einladen nun neben "data" auch bei "licence" broadcastTimeSlotStart/End gesetzt (von "data" uebernommen).
GetBroadcastFlag() bezieht nun auch data mit ein - sofern KEIN einziger wert bei "licence" gesetzt ist (Gefahrenstelle !).

Irgendwie gefaellt mir nicht, dass die Bitmaske nur "aktiviert". Man braeuchte normalerweise zwei Stueck - um gezielt Einstellungen von "data" in "licence" deaktivieren zu koennen, ohne aber andere Werte "uebernehmen" zu muessen.

**Comment by GWRon** [comment]
Es braeuchte da also immer 3 Werte bei den Lizenzen:
data.broadcastFlags
licence.broadcastFlags -> aktuell gesetzte Flags "aufbauend" auf "data"
licence.broadcastFlagsModified -> welche wurden manuell "gesetzt" (also auch abweichend von "data")
licence.broadcastFlagsDisabled -> Flags die im Vergleich zu "data" manuell "nicht mehr" gesetzt sind

gefaellt mir nicht ganz so. Koennte man aber zur Not auch in ein eigenes Objekt ueberfuehren.

**Comment by nittka** [comment]
Vielleicht sehe ich das Problem noch nicht richtig, aber warum benötigt man das separate Ausschalten von Flags? Naiver Ansatz:
* eine Programmlizenz schaut während des Spiels ausschließlich auf die eigenen gesetzten Flags (nicht auf die Data-Flags)
* beim Einlesen der Daten zum Spielstart werden die Flags entsprechend der Datenbank gesetzt (wenn definiert - Fallbackwert könnte -1 sein, damit man flags=0 als Setzen der Flags erkannt wird)
* wenn ein Programm selbst keine Flags definiert (flags="" bzw. fehlend) aber Programmdaten referenziert, werden die dort gesetzten Flags genommen (bzw. dann 0 wenn auch die Daten keine Flags definieren)

**Comment by GWRon** [comment]
Das Problem ist..wir nutzen signed integer als bitmaske..da kann auch <0 moeglich sein..oder gezielt ein "0"...wenn man alle flags von data in licence ausgeschalten haben will.

Denke eine modifiedBitmask erlaubt es diese drei Zustaende (nix geaendert, an, aus) abzubilden.

Eine Lizenz kann ja bspweise sagen...ich nutze immer das, was die data sagt, aber an zwei Stellen, nehm ich meine Einstellungen.
Wenn ich aus der DB bei Start alle Daten uebernehme und dann in "data" eine Einstellung abaendere, dann bekommt das fie Lizenz nicht mehr mit, selbst wenn es da keine eigenen Einstellungen traf.

**Comment by GWRon** [comment]
Am saubersten waere wohl ein eigener TBitmask-Typ (bzw TIntBitmask extends TBitmask ...). jeweils mit eigener "Has/Set/Get"-Methode

Wird aber umstaendlich, wenn manchmal auf eine andere Information ein "Fallback" ausgefuehrt werden soll (licence.broadcastFlags -> data.broadcastFlags). Dafuer braucht es dann eigene Getter (in licence statt in "bitmask") oder aber die Getter akzeptieren ein Fallback-bitmask:
```
Type TBitmask
  Field values:Int
  Field modified:Int

  Method Get:Int(key:int, fallback:TBitmask)
    If not IsSet(key)
      If fallback Then Return fallback.Get(i)
      Return False
    EndIf
    Return values & key > 0
  End Method

  Method IsSet:Int(key:int)
      Return modified & key > 0 
  End Method
End Type
```
(nicht getestet, nur mal so hingeschrieben)

**Comment by nittka** [comment]
Ich sehe natürlich ein, dass ohne ein Blick auf die Daten-Flags Änderungen dort für die Lizenz unberücksichtigt bleiben würden. Dass man das technisch umsetzen kann, stelle ich auch nicht in Frage. Aber bei welchem der Ausstrahlungsflags siehst Du einen Anwendungsfall, dass sich das Flag des Programms während des Spiels ändert und eine (andere als die Haupt) Lizenz davon betroffen wäre?

**Comment by GWRon** [comment]
Bis jetzt "NOT_AVAILABLE" - falls eine Speziallizenz erst spaeter "sichtbar" wuerde.
Und "HIDE_PRICE" damit eine solche Speziallizenz keinen Preis anzeigen wuerde.

Ich verstehe aber absolut, dass "derzeit" keine wirkliche Notwendigkeit besteht, dass so "verkomplizierend" umzusetzen.

Theoretisch braeuchten Lizenzen derzeit gar keine eigenen "broadcatFlags" und koennten einfach die von "data" nutzen.

**Comment by nittka** [comment]
Zum aktuellen Masterstand: Der Ted ist wieder kaputtgegangen. Mit broadcast_flags wie aktuell definiert wird die Ausstrahlungzeitbegrenzung korrekt beibehalten aber im Datenblatt steht nur die Beschränkung für die Erstausstrahlung. Mit licence_broadcast_flags steht im Datenblatt korrekt (immer) die globale Beschränkung aber nach der Erstausstrahlung kann das Programm zu beliebigen Zeiten gesendet werden.

Gleiches gilt für eine Eigenproduktion. Wird das Slot-Beschränkungslimit gesetzt, gilt das Limit wie erwartet für alle Ausstrahlung, im Datenblatt erscheint allerdings nur die Beschränkung für die Erstausstrahlung.

**Comment by GWRon** [comment]
Ok, habe mal meine angesprochene Bitmaskenanpassung eingebunden. Damit kann nun genau erkannt werden, ob "an/aus" oder einfach "noch nicht gesetzt" (nicht modifiziert).

Gleichzeitig habe ich das ueberlagern der Bitmasken darauf angepasst. Bei "Lizenz + Data" wird die "data bitmaske" als Grundlage genommen und von der Lizenz wird nur das zum Ueberschreiben herangezogen, was als "modifiziert" (haendisch bei Lizenz "gesetzt") definiert ist.

> Zum aktuellen Masterstand: Der Ted ist wieder kaputtgegangen. Mit broadcast_flags wie aktuell definiert wird die Ausstrahlungzeitbegrenzung korrekt beibehalten aber im Datenblatt steht nur die Beschränkung für die Erstausstrahlung. Mit licence_broadcast_flags steht im Datenblatt korrekt (immer) die globale Beschränkung aber nach der Erstausstrahlung kann das Programm zu beliebigen Zeiten gesendet werden.

Das funktioniert damit scheinbar nun.


Ich habe auch fuer alte Speicherstaende einen "Konvertierer" (int -> TTriStateIntBitmask) eingebunden.

**Comment by nittka** [comment]
Funktioniert leider noch nicht vollständig:
* Die Kasi-Spendengala erscheint nach Abschluss der Vorproduktion nicht in der Programmauswahl (vermutlich Kombination aus Live-Flag und Ausstrahlungszeiteinschränkung verantwortlich; ohne Slotbeschränkung erscheint das Programm).
* TED: broadcast_flags (Slotbeschränkung beibehalten) allein OK
* TED: licence_broadcast_flags allein fast OK (Datenblatt richtig, Programm kann nach Erstausstrahlung weiterhin nur entsprechend gesetzt werden), aber nach der Erstausstrahlung werden die erlaubten Slots nicht mehr farblich hervorgehoben
* TED: broadcast_flags="32678 licence_broadcast_flags="0" (Einschränkgung für Lizenz nur bei Erstausstrahlung): Überschreiben der Programmflags durch die Lizenzflags nicht wie erwartet - Beschränkung bleibt für alle Ausstrahlung (als ob licence_broadcast_flags nicht definiert worden wären)

**Comment by GWRon** [comment]
Also der Punkt "broadcastflags=x und licenceflags=0" - das liegt daran, dass nur "gesetzte" Flags als "modifiziert" gespeichert werden. Bei "0" wird ja nix "gesetzt", es erkennt an der Stelle noch nicht, das explizit "nichts" gewollt ist.

Man muesste nun argumentieren, dass jedweges setzen der licence_broadcast_flags erfordert, alle Flags "neu" zu setzen (es also NICHTS von der etwaig definierten "broadcast_flags" uebernimmt). Nur dann laesst es sich ueberhaupt sinnvoll "umsetzen" (ohne noch mit "licence_add_broadcast_flags" und "..._remove_..." zu arbeiten.

**Comment by nittka** [comment]
TScreenHandler_ProgrammePlanner#onUpdateProgrammePlanner schaut nur auf programme.data nicht aber auf die Lizenz. Daher werden lizenzspezifische Werte komplett ignoriert. Warum Selbstgedrehtes mit Sloteinschränkung gar nicht erscheint, habe ich noch nicht analysiert.

Zum Überschreiben von Data-Flags: Für mich wäre das komplette Überschreiben der Flags am intuitivesten, technisch ggf. auch am einfachsten umsetzbar und in der Datenbank auch am einfachsten nachvollziehbar. Ich kann aber auch mit der aktuellen Variante leben. Man muss es halt wissen. Und es handelt sich ja aktuell noch um einen hypothetischen Fall, da datenbankseitig noch keine Data-Referenzen verwendet werden.

**Comment by GWRon** [comment]
Um die Daten komplett ueberschreiben zu koennen, muss der Code aber auch mit flag="0" klarkommen ("alle flags ausschalten"). Man kommt da also nicht um eine Spezialbehandlung oder ein eigenes "Objekt" herum.

**Comment by GWRon** [comment]
Die BroadcastTimeSlots lassen sich ebenfalls nicht ohne weiteres "ausschalten" - auch hier ist ja nicht erkennbar, ob etwas explizit keine Slots setzen will.

Also bspweise generisches Limit aber Lizenz will kein Limit haben:
data start=5 end=10
licence start=-1 end=-1

Nun sehen nach ob licence was definiert, und wenn nicht, fallback auf data? Wuerde hier zutreffen. Wie also fuer licence die timeslots "ausschalten"?
Den Fallback andersherum zu machen bringt auch nix.

Entsprechend muessten wir wohl weitere Flags/Felder einfuehren die eben statt der "-1" als "hat oder hat nicht"-Schalter herhalten koennen.

data:
broadcastSlotTimeStart=5
broadcastSlotTimeEnd=10
broadcastSlotEnabled=true


licence:
broadcastSlotTimeStart=-1
broadcastSlotTimeEnd=-1
broadcastSlotEnabled=true
-> licence hat ein Zeitfenster und definiert selbst nix? hole es von data

licence:
broadcastSlotTimeStart=-1
broadcastSlotTimeEnd=-1
broadcastSlotEnabled=false
-> licence hat kein Zeitfenster

licence:
broadcastSlotTimeStart=11
broadcastSlotTimeEnd=20
broadcastSlotEnabled=false
-> licence hat kein Zeitfenster

licence:
broadcastSlotTimeStart=11
broadcastSlotTimeEnd=20
broadcastSlotEnabled=True
-> licence hat eigenes Zeitfenster

Statt dem "broadcastSlotEnabled" koennte das auch mit in die "Flags" rein (um ein Feld zu sparen) (wie es auch schon mit `HasBroadcastFlag(TVTBroadcastMaterialSourceFlag.HAS_BROADCAST_LIMIT)` gemacht wird).

Bei "licence" wuerde "broadcastSlotEnabled" also generell das Zeifenster deaktivieren koennen. Start und Ende auf "-1" bedeutet dann "versuche es von data zu holen".

**Comment by nittka** [comment]
Für das Überschreiben der Flags müsste der DB-Einlesecode doch nur den Fallback -1 verwenden, oder? Eine in der Datenbank eingetragene 0 kann dann eindeutig erkannt werden.
Bei der Slot-Beschränkung könnte ich mir als naiven Ansatz vorstellen, dass diese überhaupt nur für eine Lizenz definiert werden kann und nicht für Data.
* es gibt überhaupt nur wenige Anwendungsfälle für Slotbeschränkungen
* es gibt aktuell keine Fälle (DB) von Data-Wiederverwendung
* wenn es mal Wiederverwendung gibt, wird der Anteil von Slotbeschränkungen verschwindend gering sein
* Die Slotbeschränkung dann für jede Lizenz zu machen sollte kein Problem sein.

Implementierungsaufwand bedeutet das natürlich trotzdem, da aktuell Anfragen an data gehen (ggf. kann man die aber durch "Fehlerwerfen" relativ schnell ausfindig machen und korrigieren. broadcastSlotStart ist dann einfach "licence_broadcastSlotStart"; Dokumentation kann entsprechend angepasst werden.

**Comment by nittka** [comment]
Wenn ich es richtig verstehe, ist das neue 65000er-Flag dafür da, die Slot-Beschränkung überhaupt zu aktivieren. Mit dem 32000er sagt man, dass das Limit beibehalten werden soll.

Wenn man die licence_broadcast_flags verwendet, passt die Farbmarkierung im Programmplaner noch nicht (wird anhand von data eingefärbt). Sollen ich dafür ein neues Ticket aufmachen und dieses hier zumachen?

**Comment by GWRon** [comment]
Genau.
Du kannst somit nun die Beschraenkung:
- "definieren" (Uhrzeit von bis)
- "aktiv schalten" (enable flag)
- "aktiv halten nach erster Ausstrahlung" (keep flag)

Ist bei "Licence" was nicht "definiert", aber "aktiv geschalten", dann schaut es bei "data" nach. "aktiv geschalten" schaut also explizit nur bei "licence" und uebernimmt "ist aktiv geschalten?" nicht von "data". Gleiches fuer "aktiv halten nach erster Ausstrahlung". Das ist ja nicht noetig, da die entgueltige "Hab ich eine Slot-Begrenzung" bei nicht-individueller-"licence_broadcast_flag"-Definition ja eh dann in allen Faellen auf "data"-Angaben zurueckgreift.


Das Einfaerben - das klaer ich hier noch im Ticket :)
