### ISSUE TITLE
Einschränkung Cast-Jobs

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#379]
Aktuell werden Cast-Jobs oberhalb von 128 (d.h. Politiker, Maler, Schriftsteller, Model, Sportler) "ausgeschlossen". Man kann sie zwar in der Datenbank in einer Drehbuchvorlage verlangen und sie tauchen dann auch in der Liste auf, aber der Job wird nicht übersetzt angezeigt (CAST_IDs, VISIBLECAST_IDs...?)

Für eine Show oder eine Live-Sendung kann ich mir aber schon vorstellen, dass man Prominente aus diesen Bereichen im Cast haben wollen würde. Die Frage ist also: sollte hier die Implementierung angepasst werden (mindestens Übersetzung der Berufe für den Supermarkt) oder ob ich die Validierung im Editor so verschärfe, dass der Cast wirklich nur bis 128 (bzw. 255 wegen Flagkombinationen) geht und damit der Intention in der Konstantendefinion entspricht.

**Comment by GWRon** [comment]
diese "anderen Berufe" sind keine "Besetzungsberufe". Sie dienen bzw sollen dazu dienen, andere Personengruppen in den Simulationen abbilden zu koennen. Sportler in der Sportsim, Musiker in einer Musiksim ... und Politiker.

Der Gedanke, sie nun in die Auswahl mit zu uebernehmen ... klingt verlockend, aber warum gibt es dann nur diese? warum keine Hausmeister, keine Koeche (Kochshows!). Man muesste dann also alle Berufe reinnehmen ,die irgendwie fuer eigene "Sendungen" praedestiniert sind. 

Die derzeitigen sind jedenfalls die, fuer die ich mir Simulationen vorstellen kann (Bei dem "Spezialfall" Maler -> neue Kunstausstellungsnews, Rekordversteigerungen, ... Kulturprogramm)

**Comment by nittka** [comment]
OK. Datenbankseitig fordern kann man die Nicht-Cast-Berufe jedenfalls. Mir war nur im Zusammenhang mit Tests der Gala-Show aufgefallen, dass die Übersetzung für den Model-Beruf gefehlt hatte.

Ich erweitere einfach die Validierung für die zu vergebenden Jobs.
