### ISSUE TITLE
Genre Animation

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#380]
Sollte das Genre Animation "entfernt" werden? Animation kann auch als Flag definiert werden und ist dort meiner Ansicht nach besser aufgehoben.
Vorschlag: Datenbank auf Genre Animation prüfen, ggf. stattdessen das Flag setzen und ein anderes passendes Genre verwenden.

**Comment by nittka** [comment]
Hm. Vielleicht hat sich die Frage erledigt. Trickfilme erscheinen unter Famile&Trickfilme also in dem Genre, wo man Trickfilme sonst wohl auch hinsortiert hätte.

**Comment by nittka** [comment]
Vom Code sieht es aus, als wäre die Entwicklung in die andere Richtung gewesen. Es gab das Flag und dann wurde das Genre eingeführt. Ich konnte aber den Code nicht finden, dass Animationsfilme bei Kindern einen Bonus bekommen.
Gibt es schon Code, der global festlegt welche Zielgruppe welches Genre bevorzugt?

**Comment by GWRon** [comment]
Glaube @STARSCrazy hatte damals "Animation" eingefuehrt, fuer mich war das damals noch "Trickfilm" - wobei eine "Animation" nicht unbedingt "Kinder" ansprechen muss (habe mir letztens "Gantz:O" angeschaut - und das hat doch eine andere Zielgruppe (mit uebertriebener Gewalt und unnatuerlich und permanent wackelnden CGI-Bruesten)).

Entsprechend gibt es bei "Animation" nicht unbedingt einen Bonus.

**Comment by nittka** [comment]
Bei der Dopplung in Genre und Flag wäre aber dennoch interessant, welche Auswirkungen es gibt (aus Sicht der Datenbankerstellung/Pflege). Das Animation-Flag scheint in der Programmplanung nirgends erkennbar zu sein (Test mit Abenteuerfilm, der das Flag gesetzt hat).
Und wenn keine Auswirkungen durch das Flag geplant/gewünscht sind, sollte man es dann außer Betrieb nehmen...

**Comment by GWRon** [comment]
Da fehlt einfach noch die passende Balancing-Anpassung.

Animation + Erotik = Nicht jeder mag "künstliche Brüste" (Wortspiel eingeplant)
Animation + Drama = Auch eher mau
Animation + SciFi = koennte klappen
Animation + ...

**Comment by nittka** [comment]
Eine ähnlich Dopplung besteht auch mit dem Serien-Flag und dem Produkt...
Ich hätte kein Problem, das Ticket einfach zu schließen (war ja erstmal nur eine Frage), außer Du möchtest es als Erinnerung offen lassen.
