### ISSUE TITLE
Personenauswahl bei Laien

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#383]
Wenn ich die Kasi-Spendengala komplett mit Laien besetze (unterschiedliche Berufe), wird für fast alle Jobs dieselbe Person verwendet (Moderator, Musiker, Gast...).
Wenn in einer Produktion mehrere Laien eingesetzt werden (auch bei selbem Beruf), sollten das dann immer unterschiedliche Personen sein.

**Comment by GWRon** [comment]
Das Problem ist hier folgendes:
Bei der Listenbefuellung wird nicht darauf geachtet, ob ein Amateur bereits genutzt wird. 

Es wird einfach ein zufaelliger Amateur "angefordert" (vielleicht noch mit Geschlechtseingrenzung) und wenn das ohne Rueckgabewert geschieht, legt es einen neuen Amateur an.


Ich sehe hier nun mehrere Moeglichkeiten:
A
- beim "Start" einer Produktionsplanung koennte ein Array initialisiert werden, der bereits "ausgewaehlte" Amateure (evtl mit jeweiligem "moeglichen Job") beinhalten kann
- beim Auffuellen der Listen wird das ganze "beachtet" und entsprechend reagiert

oder B
- bei "Planungsabschluss" wird durch den Cast gegangen und sichergestellt, dass sich jeder Amateur unterscheidet
- bzw es wird sichergestellt, dass innerhalb eines Berufs (sichtbare Person wie "Schauspieler") nur einmalig der Amateur verwendet wird, waehrend es zwischen den Berufen mit X Prozent erlaubt ist (Regisseur und Reportagemoderator ist der gleiche Amateur ... ) 
- Nachteil: eine "unscharfe Darstellung" etwaiger Talente/Attribute eines Amateurs (derzeit waeren keine vergeben, aber man koennte ja jeder Person ein Basispotenzial zusprechen und dies in der Darstellung nutzen) waere dann vor "Abschluss" nicht moeglich
- Nachteil: wenn man mehrere Produktionen plant und "kopiert" um den gleichen Cast zusammenzustellen, wuerde das bei Amateuren oft zu verschiedenen Personen fuehren (man kann also nicht eine Serie mit "Amateur 5" produzieren und ihn nach 10 Folgen zu einem "Star" gemacht haben)
- Vorteil: sehr leicht umzusetzen (einfach die Liste durchgehen und "ersetzen")

oder C
- wir erlauben die explizite Auswahl einiger Amateure ("Namen anzeigen lassen") 
- und stellen sicher, dass immer 3-4 Amateure pro "Job" zur Verfuegung stehen
- Vorteil: auch relativ leicht umzusetzen
- Vorteil: ergaenzt den von Dir (@nittka ) angebrachten (und umgesetzten) Vorschlag, dass garantiert werden muss, pro Job auch X Promis/Profis anzubieten 
- Vorteil: erlaubt die gezielte "mehrfach Besetzung" mit einem Amateur
- Nachteil: koennte gezieltere "Star-Erzeugung" mehr erleichtern als gedacht
- Nachteil: nimmt ein wenig die "Ueberraschung", wann und wie neue Stars geboren werden


ich denke letzteres ist am "zielfuehrendsten".

**Comment by nittka** [comment]
C klingt für mich auch nicht schlecht. Aktuell halte ich die Star-Erzeugung (gezielt oder ungezielt) für kein so zentrales Spielelement. Wenn man den Amateur eher als "Joker" versteht (man weiß nicht, was man bekommt, aber wenigstens kostet er nicht so viel), ist das Anzeigen der Namen (aber nicht der Attribute) OK.

P.S.: umgesetzt habe ich keinen Vorschlag, pro Job X Profis anzubieten

**Comment by GWRon** [comment]
Re PS: stimmt, das war Nalindir  :)
https://github.com/TVTower/TVTower/issues/122

**Comment by GWRon** [comment]
Hmm ich wuerde gar etwas weiter gehen.
Das System muss sicherstellen, dass fuer jeden "job" sogar 10 Personen existieren. Von denen werden dann halt X zur Auswahl bereitgestellt.
Damit werden nicht immer die gleichen Amateure angeboten (es haben sich nicht alle fuer das Casting beworben).

Wwenn moeglich, immer die gleichen - fuer die jeweilige Produktion:
- also einen Random-Seed anhand der ProduktionsID festmachen 
- oder die "gerade verfuegbaren Amateure" aller X Stunden durchmischen

**Comment by GWRon** [comment]
Wie sollten wir Amateure darstellen?

![castlist](https://user-images.githubusercontent.com/2625226/127784766-40bb131c-b4f6-4226-ac43-047d7364fd80.png)
![castlist2](https://user-images.githubusercontent.com/2625226/127784776-2c359f84-233c-471f-8ec3-8d17d41a49c3.png)

Oder leicht eingefaerbt? Bzw mit einem "schwarze/Schatten-Figur" (also eher ein "Icon") als Avatar/Gesicht ? Wieso wuerde man aber bei einem Amateur kein Gesicht haben? Wuerde man ja trotzdem als Castingchef rankommen...
Bleibt also ein "Einfaerben" oder anderweitig hervorheben ... vielleicht ein "halbtransparentes" grosses A als Personenbild? ... aber ist dies bei allen Lokalisierungen eindeutig - braeuchte also einen eigenen "Locale"-Eintrag.

Je nach Laenge der Namen koennte man auch das "Amateur" rechtsseitig auf dem Balken mit einzeichnen.


Im Datenblatt wuerde ich das dann wohl auch neben dem Namen mit einblenden.

**Comment by nittka** [comment]
Für die bereits ausgewählten Amateure gefällt mir die letzte Variante (rechtsbündige Beschreibung) gut. Das Gesicht kann ruhig mit rein.
Bei der Auswahl bin ich mir noch unschlüssig: nur Amateur hinschreiben und Gesicht anzeigen; Name aber nur im Datenblatt bei Hover sichtbar? Das macht die optische Erkennung und vielleicht Wiedererkennung in der Liste einfacher.

Wenn man mehr Amateure in die Auswahl nimmt, kann es sein, dass es für den Spieler nervig wird - insb. benn bei der Sortierung die Amateure immer am Anfang der Liste bleiben. Vielleicht sollten die Sortierfunktionen dann angepasst werden. Name und Gage entsprechend des Attributs (alle gemischt); Erfahrung je nach Sortierreihenfolge mal die Amateure vorn, mal hinten.

Im ersten Screenshot sieht es so aus, als wäre derselbe Amateur zweimal in der Liste. Das darf dann natürlich nicht vorkommen.

**Comment by GWRon** [comment]
Wenn der Name zu sehen ist...dann immer. Da hin- und herzuwechseln faende ich stoerend.

Ein Gesicht bekommen nur Promis zugewiesen ... Oder ich generiere einen Code auf Basis des Namens und ID...aber keine Ahnung wie gut das geht.


Doppelte Namen kommen jetzt nicht mehr vor...hab da schon n paar Funktionen geschrieben.

**Comment by nittka** [comment]
Passt für mich.

**Comment by GWRon** [comment]
Wuerde von https://github.com/TVTower/TVTower/pull/388 erledigt werden

**Comment by GWRon** [comment]
Wenn du hier nix mehr "offen" hast, kannst du gerne schliessen.
