### ISSUE TITLE
Live-Zeit-Berechnung, Ausstrahlungslimit bei Serien

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#385]
Ich bin gerade dabei, die Kasi-Skripte bezüglich des neuen Flags "Berücksichtige die Time-Slots" anzupassen und testzuspielen. Dabei sind mir folgende Dinge aufgefallen
* Auch wenn ein größerer Zeitraum für die Ausstrahlung vorgesehen ist (z.B. 2 Blöcke zwischen 19 und 22 Uhr), wird als Live-Zeit 19 Uhr angegeben und schon eine Ausstrahlung 20 Uhr ist LiveOnTape. Das Flag AlwaysLive zu setzen ist aber auch keine immer funktionierende Option. Wenn man ein Ausstrahlungslimit von 2 hat (Erstausstrahlung live + eine Wiederholung irgendwann), ist die Wiederholung eben nicht live. Für ein (fremdübertragenes) Konzert wäre das nachvollziehbar, für eine eigene Show passt das nicht.
* Wenn man eine Serie mit Ausstrahlungszeitbegrenzung (und Ausstrahlungslimit im Beispiel 1) produziert, passen die Datenblätter nicht so richtig: Datenblatt Drehbuch+Einkaufsliste Ausstrahlungszeitbegrenzung nicht angezeigt, Datenblatt Serienhead Ausstrahlungslimit (0-1 je nachdem ob eine Folge schon gesendet wurde oder nicht) und Erstausstrahlung (-1 bis -1) verwirrend - diese Limits sollten nur für die Einzelfolgen angezeigt werden

**Comment by nittka** [comment]
Mein Vorschlag für den ersten Punkt wäre, dass datenbankseitig entweder das AlwaysLive-Flag gesetzt oder ein live_date angegeben werden muss. Da im Code rumraten zu müssen ist nicht zielführend. D.h. code-seitig sind Ausstrahlungszeitbegrenzung und live-Zeit weniger eng gekoppelt.
Tatsächlich gibt es da aktuell aber dennoch einen Bug. Ich habe für die Spendengala als Datumsdefinition "in ein oder zwei Tagen 19 Uhr) angegeben. In der Drehbuchagentur wechselt dann die Angabe auf dem Datenblatt ständig zwischen "morgen" oder "in zwei Tagen". D.h. die Datumsangabe wird scheinbar permanent neu ausgewertet. Beim Erstellen des Drehbuchs aus der Vorlage sollte die Angabe aber "finalisiert" werden.

**Comment by nittka** [comment]
... und das AlwaysLive-Flag scheint auch nicht korrekt behandelt zu werden. Hat die Show das Flag und keine Slot-Beschränkung, wird scheinbar die nächstmögliche erste Ausstrahlungszeit genommen und sofort danach ist die Show nicht mehr live (bzw. als live im Programmplaner zu erkennen).

**Comment by GWRon** [comment]
Schau ich mir nach der Sache mit den Amateuren an.

**Comment by nittka** [comment]
Würdest Du hier mit Anpassungen noch warten, bis ich meine Gedanken zu dem Thema nochmal systematisiert habe? Wie sich rausstellt, ist es eben nicht nur ein kleiner Bugfix...

**Comment by GWRon** [comment]
Klar...da warte ich und schau mir die Amateur-Fehler an.

**Comment by GWRon** [comment]
> Auch wenn ein größerer Zeitraum für die Ausstrahlung vorgesehen ist (z.B. 2 Blöcke zwischen 19 und 22 Uhr), wird als Live-Zeit 19 Uhr angegeben und schon eine Ausstrahlung 20 Uhr ist LiveOnTape. Das Flag AlwaysLive zu setzen ist aber auch keine immer funktionierende Option. Wenn man ein Ausstrahlungslimit von 2 hat (Erstausstrahlung live + eine Wiederholung irgendwann), ist die Wiederholung eben nicht live. Für ein (fremdübertragenes) Konzert wäre das nachvollziehbar, für eine eigene Show passt das nicht.

Wir haben hier zwei Sachen:

Ausstrahlungszeitraum 19-22 Uhr und 2 Bloecke
- es bedeutet nicht, dass "live" 22 Uhr endet
- es bedeutet, dass die Ausstrahlung definiert, wann "live" endet - und die Ausstrahlung kann 19 oder 20 Uhr stattfinden
- ein Beispiel waere eine Live-Talkshow, die kann ja auch mal spaeter anfangen (unabhaengig von "externen Events" wie Raketenstarts)

Ausstrahlungslimits
- die besagen, wie oft ein Programm ausgestrahlt werden kann (unabhaengig von "live")
- AlwaysLive-Flags wuerden dann dazu dienen, auch die zweite Ausstrahlung "live" zu haben.

**Comment by nittka** [comment]
Erste Diskussionsgrundlage https://github.com/TVTower/Documentation/blob/liveLimit/developer/concepts/materialFlagsAndLimits.md

Im Prinzip schlage ich eine radikale Vereinfachung der Live-Zeit-Behandlung bei Drehbüchern vor (hier nur die Zusammenfassung; Argumentation siehe Konzept):

* AlwaysLive-Flag entfällt; zweite Ausstrahlung immer LiveOnTape
* kein Live-Date definiert bedeutet Erstausstrahlung live (unabhängig von Ausstrahlungszeitpunkt), Datenblatt "Liveausstrahlung" ohne Zeitangabe
* mehrere Folgen/Production-Limit > 0 - Live-Date nicht unterstützt

Für "Einzeldrehbücher" (nur ein Einkaufszettel) mit definiertem Live-Date
* Definition immer inklusive Uhrzeit
* Live-Zeit wird bei Drehbucherstellung festgelegt
* Datenblatt "Liveausstrahlung" mit Zeitangabe
* ist zum Live-Zeitpunkt die Vorproduktion noch nicht abgeschlossen, verfällt das Drehbuch; neue Instanz aus Drehbuchvorlage kann später wieder erscheinen

**Comment by GWRon** [comment]
Ich weiss noch nicht genau wo wir Deine "Diskussionsgrundlage" am Besten ausdiskutieren sollten :)

> AlwaysLive-Flag entfällt; zweite Ausstrahlung immer LiveOnTape
Empfand ich anfaenglich als Unding - aber dein Dokument stellt das ja ganz gut klar.
Und ja, das wird wohl mit TED am Morgen etc gekommen sein. Also ein Flag der ein einzelnes Programm (was nicht per Drehbuch produziert wird - sondern als "Programmlizenz" erworben wird) derart konfiguriert, dass es beliebig ausgestrahlt werden kann (ausser es hat Ausstrahlungszeitraeume definiert) und immer "live" ist.

Das Problem ist also - zusammengefasst: das dies (mit fertigen Programmlizenzen und nicht per Drehbuch->Eigenproduktion) ohne den Flag (derzeit) nicht abgebildet werden kann. 


> Live-Time/Live-Date
Live-Time war dafuer angedacht, nur eine Uhrzeit zu definieren ("18 Uhr") aber dies wurde ja mit der Moeglichkeit der Sendezeitbeschraenkung theoretisch obsolet. Allerdings ist fuer Drehbuecher mit "Zufalls-Blockanzahl" die Live-Ausstrahlungszeit (Uhrzeit, nicht "Tag") nun nicht mehr genau definierbar.
Will man ein Programm unbedingt nur 20 Uhr ausstrahlen lassen, waere ein "timeslots 20-22 Uhr" bei 2 Bloecken eindeutig (passt nur 20 Uhr). Wenn aber der Zufall das Drehbuch auf 1 Block oder 3 Bloecke umstellt, dann kann 20 oder 21 Uhr ausgestrahlt werden (1 Block) oder aber es passt nirgends (3 Bloecke).


> Episodes vs. Production-Limit
Eigentlich wollte ich genau vorschlagen, dass "episodes" ja doch mit "productionLimit" ersetzt werden koennte - und dann kommst du mit der passenden Begruendung (Sportschau vs Serienepisode 1von5) um das eben nicht zu machen. Gut so :)


> Ist die erste Ausstrahlung erfolgt oder der berechnete Live-Zeitpunkt überschritten, ist das Programm Live-On-Tape.
Ja, sehe ich auch so.


>  Es hätte aber schon seinen Reiz, wenn man bei seiner Planung auch gezwungen wäre, die Vorproduktion rechtzeitig zu starten, damit der beim Erwerb der Lizenz festgelegte Live-Zeitpunkt eingehalten werden kann (sonst verfällt das Drehbuch und muss/kann später neu erworben werden - mit dem dann neu berechneten Live-Zeitpunkt)

Das sollte immer nur fuer Drittparteienereignisse gelten. Ein Drehbuch ist ja erstmal nur eine Art "Ablaufplan". Wann nun die grosse Show der Volksmusikanten tatsaechlich "aufgezeichnet" (ich meine Live ausgestrahlt :D) wird, ist ja von den Sendern relativ frei definierbar. Raketenstarts und Live-Band-Aid-Uebertragungen hingegen haben feste "Termine". Hier waere aber auch weniger von einem "Drehbuch" zu sprechen als von einem "Uebertragungskonzept" (bzw gleich innewohnend die "Lizenz" um eben ein Konzert uebertragen zu koennen).


> Die Morgenshow käme gut mit der Ausstrahlungszeitbegrenzung und "live während der gesamten erlaubten Zeit" aus. Zu erzwingen, dass die Ausstrahlung nicht am selben Tag erfolgen darf erscheint überflüssig.

Ja, das ist organisch gewachsen - und einiges laesst sich nun sicher auch anders "abbilden". Bei all zu grossen Zeitfenstern (1 Block-Show und Zeitraum 10-20 Uhr) koennte es aber zu einer mehrfachen Ausstrahlung fuehren. Diesen Sonderfall koennen wir aber denke ich der Einfachheit halber ignorieren.

> Film -  broadcast_slot
Hmm man koennte theoretisch Filme fuer bestimmte Tage verbieten (Das Leben des Brian - an Pfingsten/Ostern). Aber das ist ein exotisches Beispiel. Genauso wie Speziallizenzen bei denen man Indy immer 23 Uhr auf Schatzjagd schicken muesste

> Film - episodes/children
Nein, StarWars etc wuerde ich da nicht drunter sehen. Fuer Filme einfach kein vernuenftiger Einsatz vorhanden.

> Feature - production_limit
Reportagen aus dem Sendegebiet Folge 212
Panda, Kaninchen und Co ...
Also generell so dieses "guenstige Nachmittagsprogramm"?

**Comment by nittka** [comment]
Die Diskussion fände ich am besten im Doku-Repo - Entweder Antworten direkt in die Datei schreiben (ronny: Meine Antwort). Oder die Datei kopieren und dort die Antworten Reinschreiben (Diff), oder direkt im Github im Commit kommentieren. Und ich arbeite das Feedback dann ein. In dieses Ticket passt eine längere Diskussion jedenfalls nicht.

**Comment by nittka** [comment]
Geschlossen durch PR #395
