### ISSUE TITLE
Liveproduktionen sollten laufende Produktionen verlängern

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#392]
* Unterbrechung einer Produktion durch Live-Ausstrahlung OK, aber die laufende Produktion verlängert sich nicht (selbe Fertigstellungszeit wie ohne Live-Ausstrahlung)

_Originally posted by @nittka in https://github.com/TVTower/TVTower/issues/388#issuecomment-902437004_

**Comment by nittka** [comment]
In diesem Zusammenhang kann auch noch umgesetzt werden, dass Vorproduktionen abgebrochen oder Scripte entfernt werden müssen, wenn die Vorproduktion nicht mehr vor dem festgelegten Live-Zeitpunkt fertiggestellt werden können (Behandlung in UpdateProductionStep?).

**Comment by GWRon** [comment]
Hmm oder ein dependsOnID einfuehren ...damit Reihenfolgen eingehalten werden koennen?

**Comment by nittka** [comment]
Für die Reihenfolge muss der Spieler schon selbst sorgen. Es werden ja sowohl Live-Datum als auch die Produktionsdauer angezeigt. Es geht ja auch nicht nur um Serien. Selbst bei einer Einzelshow, kann man das Konzept ja schon lange erstellt , dann aber die Vorproduktion nicht rechtzeitig gestartet haben.
(Ich habe diesen offenen Punkt aus dem aktuellen PR einfach in das passendste Ticket geschrieben, damit es nicht vergessen wird.)

**Comment by nittka** [comment]
zu testen und anzupassen:
* Live-Ausstrahlung muss aktuelle Produktion verlängern
* kein Studio vorhanden, wenn Live-Ausstrahlung erfolgen soll (Sendeausfall)
* Vorproduktion für Livesendung mit festem Live-Datum zu spät gestartet (Sendausfall/Abbruch/direktes Livesenden mit viel schlechteren Ergebnissen)
* nur ein Studio aber zwei Live-Sendungen mit gleichem Ausstrahlungstermin (z.B. auch Always-Live im Sendeplan, Live-Sendung mit aktuellem Ausstrahlungstermin oder zwei Sendungen mit gleichem, festen Ausstrahlungstermin)
* Drehbuch wird weggeworfen, obwohl Live-Ausstrahlung noch nicht stattgefunden hat (trotzdem senden können/Lizenz wird entfernt)

**Comment by nittka** [comment]
Einfacher Fall - ein Studio, Dreh im Gange, Live-Ausstrahlung startet:
* die aktuelle Produktion wird auf pausiert gesetzt und der Studio-Tooltip entsprechend aktualisiert
* wenn die Pausierung aufgehoben wird, wird die Pausierdauer aber wieder auf 0 gesetzt und damit der ursprüngliche Endtermin wiederhergestellt

Wenn man die Zeit nur bei setPaused(true) setzt, stimmt der Zeitpunkt der Beendigung des Drehs, aber das Ende der "Studioblockade" wird nicht angepasst. Das Studio kann auch während des Drehs betreten werden.

**Comment by nittka** [comment]
Im obigen Commit wurde (stattdessen nur) das Ende der Pausierung angepasst. Hier wird das Produktionsende nach hinten verlagert, bevor das Studio neu blockiert wird.

Die anderen (Sonderfälle) sind noch nicht berücksichtigt.

**Comment by nittka** [comment]
>     * Live-Ausstrahlung muss aktuelle Produktion verlängern
erledigt

>     * kein Studio vorhanden, wenn Live-Ausstrahlung erfolgen soll (Sendeausfall)
nicht relevant, da erstest Studio nicht gekündigt werden kann

>     * Vorproduktion für Livesendung mit festem Live-Datum zu spät gestartet (Sendausfall/Abbruch/direktes Livesenden mit viel schlechteren Ergebnissen)
die Lizenz steht zum Live-Termin noch nicht bereit - das ist meiner Ansicht nach OK. Nicht optimal aber für mich aktuell irrelevant: wenn die Produktion dann abgeschlossen ist, ist die Lizenz scheinbar auch nicht live-on-tape.

>     * nur ein Studio aber zwei Live-Sendungen mit gleichem Ausstrahlungstermin (z.B. auch Always-Live im Sendeplan, Live-Sendung mit aktuellem Ausstrahlungstermin oder zwei Sendungen mit gleichem, festen Ausstrahlungstermin)
würde ich aktuell ignorieren und auf Fehlermeldungen warten

>     * Drehbuch wird weggeworfen, obwohl Live-Ausstrahlung noch nicht stattgefunden hat (trotzdem senden können/Lizenz wird entfernt)
Die bereits vorproduzierte Sendung kann gesendet werden. Ist für mich OK.

Ich würde das Ticket für mich als gelöst betrachten, wenn es keine Einwände gibt.

**Comment by GWRon** [comment]
Im zweifel machen wir einfach ... die Issues neu auf. Denke auch, dass man das bis dahin erstmal als gelöst sehen kann.

**Comment by nittka** [comment]
Durch #535 erledigt.
