### ISSUE TITLE
Reset Globaler Zustande

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#398]
Dass so viel im globalen Zustand gehalten wird, macht den Start eines neuen Spiels schwierig. Bsp:
* neues Spiel 1985 starten
* Zurück zum Hauptmenü
* neues Spiel 1986 starten
* ich habe in mehreren Fällen sofort in den ersten Minuten den News-Sammy gewonnen

Beim Laden eines Spielstands sollte das keinen Unterschied machen (da werden die globalen Sachen doch auch überschrieben, oder?). Wenn man aber ein neues Spiel anfängt, wird aktuell nicht alles auf Anfang zurückgesetzt.

**Comment by GWRon** [comment]
Ohne jetzt nachzuschauen vermute ich, dass die "Beobachter"-Funktionen der Sammysachen im Speicherstand erfasst werden - bei "Spiel neu" hingegen aber keinen Reset erfahren.

**Comment by GWRon** [comment]
Oder aber, gleich zu Spielbeginn kommt noch ein altes "Event" rein - dann sollten die Events nicht korrekt (oder gar nicht) zurueckgesetzt werden (wenn "Spiel neu")

**Comment by GWRon** [comment]
OK ... also bei "Neues Spiel" werden die Awards noch nicht korrekt zurueckgesetzt ... 
```
	Method UpdateAwards()
print "UpdateAwards()"
		'=== CREATE INITIAL AWARD ===
		If GetWorldTime().GetDaysRun() = 0 And Not GetNextAward()
print "  Create Initial Award"
```
Das erste print kommt bei jedem neuen Spiel, das zweite hingegen nicht.

Das mit den Events ueberpruef ich dann wohl noch zusaetzlich.

**Comment by nittka** [comment]
Jedenfalls _sollte_ "Spiel neu" eigentlich alles komplett neu initialisieren; mit Ausnahme von aktuelle Sprache, Flag ob Hilfedialoge immer angezeigt werden - also eher Meta-Sachen, die nichts mit dem eigentlichen Spielverlauf zu tun haben.

Von der Prio ist das auch nicht so hoch, da es einen einfachen Workaround gibt: Wenn man ein komplett sauberes neues Spiel anfangen möchte, beendet man das Programm komplett und startet neu.

**Comment by GWRon** [comment]
Die Produzenten werden auch noch nicht zurueckgesetzt - in deinem Beispiel (1985 und 1986) erscheinen da gleich viele Produktionen.

**Comment by GWRon** [comment]
> Jedenfalls _sollte_ "Spiel neu" eigentlich alles komplett neu initialisieren; mit Ausnahme von aktuelle Sprache, Flag ob Hilfedialoge immer angezeigt werden - also eher Meta-Sachen, die nichts mit dem eigentlichen Spielverlauf zu tun haben.


Der Fehler lag bspweise darin, dass die Initialisierungsfunktion der "AwardCollection" (des Sammy-Managers) einige Felder nicht initialisierte. Das Savegame hingegen deserialisiert eben diese und ueberschreibt somit "alte" Werte (korrekt).

**Comment by nittka** [comment]
Wäre es nicht auch möglich, bei einem Spiel-Neustart in den "TXCollection" jeweils die globalen instance-Felder auf null zurückzusetzen? GetInstance würde dann eine neue Instanz erzeugen und automatisch alle Felder zurücksetzen. Falls dann irgendwann ein neues Feld dazukommt, muss man nicht darauf aufpassen, dass ggf. in einer initialize-Methode zurückzusetzen.

Für die Awards hattest Du schon einen Commit gemacht. Bist Du an den Produzenten noch dran?

**Comment by GWRon** [comment]
Ja so ein _instance=null koennte sicher auch funktionieren. 

Die Produzenten..mach ich noch, kam jetzt noch nicht dazu.

**Comment by GWRon** [comment]
Wenn das hier erledigt ist, gerne zumachen.
