### ISSUE TITLE
Bug beim Einlesen von Seriendaten

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#399]
Es gibt einen Bug beim rekursiven Einlesen der Daten für Serienfolgen.
Wenn man die Folgende Zeile

print "Episode" + episodeLicence.getTitle() + " "+episodeLicence.licenceType +" "+ episodeLicence.data.isHeader()

in Zeile 1425 des Datenbankeinlesecodes (Iterieren über '=== EPISODES ===) einfügt und ein Spiel startet, sieht man, dass die Programmdaten der ersten Folge nicht als Header markiert sind, die Programmdaten aller weiteren Folgen aber doch.

**Comment by nittka** [comment]
Das Problem ist aufgefallen, als ich eine existierende Serie in der Datenbank als live markiert hatte und außer der ersten Folge alle weiteren nach Ausstrahlung live blieben (im aktuellen Stand meines PR aktualisiere ich die Live-Flags für Serien-Header nicht, was ich auch für korrekt halte).

**Comment by GWRon** [comment]
ich guck gleich mal nach ob mir was auffaellt.

**Comment by GWRon** [comment]
Also das Problem lag erstmal darin, dass die Episoden ihre "TProgrammeData" von dem Header klonten - und damit auch dessen "dataType".

Und dann wurden nur fuer die Lizenzen die "licenceType" korrigiert - und die ProgrammeData.dataType blieben unveraendert.

An sich ist eh beides "das Gleiche" und koennte wohl in einem anderen PR mal "zusammengefuehrt" werden.
