### ISSUE TITLE
Pool refills limits

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#400]
Das Flag zum Auffüllen der Ausstrahlungslimits funktioniert nicht wie erwartet. Meine Interpretation, die durchaus falsch sein kann, ist wie folgt:
* Limit ist 2, ich strahle zweimal aus (automatische Rückgabe und Refill aktiviert), ich hole mir das Programm nochmal und kann erneut zweimal ausstrahlen
* Limit ist 2, ich strahle einmal aus (Refill aktiviert), verkaufe das Programm wieder, hole es mir erneut und kann wieder zweimal ausstrahlen

Wenn ich den Code und das Spielverhalten aber richtig verstehe, wird durch das Refill das Limit nur wieder auf 2 erhöht, ich habe aber schonmal gesendet und kann nicht wie erwartet weitere zweimal senden.

Meiner Ansicht nach müsste die Prüfung, wieviele Ausstrahlungen möglich sind, so erfolgen:
* konfiguriert ist ein Limit (LimitMax!)
* initial Limit = Gesamtanzahl der Ausstrahlungen + LimitMax
* angezeigte Anzahl möglicher Ausstrahlungen: Limit-Gesamtzahl
* exceeded: Gesamtzahl-Limit<=0
* bei Refill wieder Limit=aktuelle Gesamtzahl der Ausstrahlungen + LimitMax

Beispiel: Limit 2
* Programm geholt: MaxLimit=Limit=2, Ausstrahlungen 0
* eine Ausstrahlung: Limits unverändert, Ausstrahlungen 1; Anzahl möglicher Ausstrahlungen 2-1=1
* Programm zurück, Refill: MaxLimit=2; Austrahlungen 1; Limit 1+2 =3
* Programm geholt: Anzahl mögliche Ausstrahlungen 3-1=2
* ...

**Comment by GWRon** [comment]
Ja das Spielverhalten ist so wie es von mir mal angedacht war:
- Verkaufe mit "1 von 2 Ausstrahlungen" und du kaufst es spaeter auch wieder als ein solcher "Restposten".

Allerdings koennen wir gern beides umsetzen:
- neuer Flag "KEEP_CURRENT_USE_OF_BROADCASTLIMIT" (oder so)
- ist der Flag gesetzt, wird das von dir vorgeschlagene Limit entsprechend nicht um "LimitMax" sondern `LimitMax - (aktuelleGesamtzahlDerAusstrahlungen mod LimitMax)` erhoeht (also das, was "uebrig" war)

Ansatz waere dort: (game.programme.programmelicence.bmx Method GiveBackToLicencePool:int())
```Blitzmax
		'refill broadcast limits - or disable tradeability
		if GetBroadcastLimitMax() > 0 and (isExceedingBroadcastLimit() or GetSublicenceExceedingBroadcastLimitCount() > 0 )
			if HasLicenceFlag(TVTProgrammeLicenceFlag.LICENCEPOOL_REFILLS_BROADCASTLIMITS)
				SetBroadcastLimit(broadcastLimitMax)
			else
				SetLicenceFlag(TVTProgrammeLicenceFlag.TRADEABLE, False)
			endif
		endif
```


Deine Intention ist also, die "broadcast counts" zu behalten anstatt mit jedem Kauf eine "genullte" Version zu bekommen ?

**Comment by nittka** [comment]
Ich denke, ich habe die ursprüngliche Intention noch nicht verstanden... Mit einem gesetzten Limit (z.B. 2) und ohne andere Flags soll eine Lizenz insgesamt nur zweimal ausgestrahlt werden können - egal von wem, korrekt?
* Spieler 1 sendet einmal und verkauft
* Spieler 2 kauft und kann nur noch einmal senden

Es gibt nun aber schon das Flag LICENCEPOOL_REFILLS_BROADCASTLIMITS. Was soll damit erreicht werden (Ausgangspunkt Spieler 1 sendet einmal und verkauft)?
* Spieler 1 kauft erneut und kann wieder zweimal senden? (D.h. jeder Spieler kann nach jedem Kauf wieder 2x senden)
* Spieler 1 kauft erneut kann aber weiterhin nur einmal senden, aber Spieler zwei kann zweimal senden?

Ich fände den ersten Punkt intuitiver. Aktuell ist das Verhalten aber nicht so.

**Comment by GWRon** [comment]
Das Verhalten sollte so sein:
- Programmlizenz mit initialen 3 Ausstrahlungen
- Spieler 1 kauft und sendet 1x
- Spieler 1 verkauft
- Spieler x (1 oder jemand anders) kauft erneut
- Programmlizenz laesst sich noch 2 von 3 mal ausstrahlen
- Spieler strahlt die 2x aus
- Limit erreicht -> Lizenz wieder im Pool
- Lizenz setzt Ausstrahlungslimit auf 3x zurueck

Der Kaufpreis waere in Abhaengigkeit der "verfuegbaren Ausstrahlungen" natuerlich niedriger, wenn "angerissen".

**Comment by nittka** [comment]
D.h. mit dem Flag wird das Limit nur wieder auf den Initialstand zurückgesetzt, wenn alle verfügbaren Ausstrahlungen verbraucht sind. Damit kann ich leben und werde es nochmal testspielen.

**Comment by GWRon** [comment]
Exakt - und wie gesagt mittels eines neuen Flags koennte man eben auch Deinen Ansatz ermoeglichen.

**Comment by nittka** [comment]
OK. Funktioniert aktuell trotzdem nicht wie erwartet (erstmal nur Extremfall getestet):
* Morgenshow mit Limit 1, automatische Rückgabe und Refill
* eine Ausstrahlung - verschwindet OK
* In der Filmagentur taucht es dann aber auf mit: "keine weiteren Ausstrahlungen möglich"

**Comment by nittka** [comment]
Wenn man statt broadcast_limit das Limit nur für die Lizenz setzt, geht zumindest der obige Fall. Das Problem scheint darin zu liegen, dass beim Setzen des Limits in der Basisklasse nicht bekannt ist (sein kann), dass ein analoges Flag auch noch in den Programm-Daten existiert und die beiden verheiratet werden müssen (damit dann die Daten konsistent aus Lizenz oder Daten genommen werden).

Vielleicht ist es damit getan, die SetBroadcastFlags-Methode in der Lizenz zu überschreiben und dort die Lizenz- und DatenFlags korrekt zu synchronisieren.

**Comment by nittka** [comment]
Die Reparatur ist möglicherweise noch einfacher: GiveBackToLicencePool in TProgrammeLicence verwendet für das Zurücksetzen des Limits das limitMax-Feld selbst anstatt den Getter. Mit dem scheint es zu klappen.

Bei einem Limit größer 1 sehe ich noch ein "fachliches" Problem. Der "Restwert" der Lizenz nach einer Ausstrahlung müsste (stärker) an die Anzahl der verbliebenen möglichen Ausstrahlungen gekoppelt sein. Angenommen das Limit ist 3, ich strahle zweimal aus, warte bis die Aktualität wieder beim Maximum ist und verkaufe die Lizenz dann. Der nächste muss kann nur einmal ausstrahlen, danach gehen aber wieder drei Ausstrahlungen...

**Comment by GWRon** [comment]
Du meinst, bei einem Limit, sollte die Anzahl der Restausstrahlungen ... sowohl absolut (Anzahl) als auch relativ (aktuell dividiert durch maximal) eine gewichtigere Rolle spielen.

Wir muessten ermitteln / raussuchen, wie viele Ausstrahlungen man machen kann, bis die max.Aktualitaet im Keller ist / nicht weiter absinkt.
Das kann ins Verhaeltnis zum Ausstrahlungslimit gesetzt werden. Und hier ein wenig staerker beeinflussen lassen, da die Limitierten schon guenstiger sind, aber einfach immer Abwechslung bringen.

**Comment by nittka** [comment]
In dem "großen" PR wurde die Flagauswertung ja grundsätzlich überarbeitet. Das Thema "Auffüllen bei Serien" würde ich dennoch gern nochmal ansprechen. Vom Gefühl her würde ich sagen, dass nur dann aufgefüllt werden sollte, wenn sämtliche Limits erreicht sind (also nicht wie aktuell, wo Einzelfolgen aufgefüllt werden). Daraus ergeben sich dann natürlich andere Probleme - alle außer einer Folge haben ein Limit, das Ausstrahlungslimit der Gesamtserie wäre also nie gerissen. Aber wo wäre der Anwendungsfall bei einer Serie nur partiell Limits zu setzen, dann aber ein Refill zu wollen...
Wie ist Dein Standpunkt? Als Alternative steht ja auch noch - bei gesetztem Flag immer alle Limits wieder hoch. Auch das wäre ein konsistentes und nachvollziehbares Verhalten.

**Comment by nittka** [comment]
Zur Dokumentation ein möglicher Ansatz zwischen den Extremen "immer alles auffüllen" und "erst auffüllen, wenn alle Limits erreicht wurden": Fülle alle Limits auf das Maximum auf, wenn ein Ausstrahlungslimit erreicht wurde. Relevant ist diese Betrachtung aktuell nur für Serien.
Dieser Kompromissansatz würde auch den Fall abdecken, dass gar nicht alle Folgen ein Ausstrahlungslimit haben.
