### ISSUE TITLE
Ausstrahlungszeitbegrenzung mit Tageswechsel

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#401]
Auch schon im aktuellen Masterstand funktioniert die Anzeige im Programmplaner und das Drop-Veto nicht 100%ig, wenn die Zeitbeschränkung tagesübergreifend ist:
Bsp. Morning-Show mit 6 Blöcken von 20-6 Uhr:
* im Programmplaner werden nur die Blöcke von 20 bis 23 grün angezeigt, die Blöcke 0 bis 6 nicht
* die Sendung kann auch mit Startzeit 15 bis 19 Uhr sowie 2 bis 5 Uhr gesendet werden

Da noch keine tagsübergreifenen Slot-Beschränkungen im Einsatz sind, ist das noch nicht kritisch, aber ein Teil des Codes kümmert sich ja schon um diesen Fall.
(Sollte erst angegangen werden, wenn der Live-Zeit-PR gemergt ist)

Weniger dramatisch. Für Live-Programme werden die Werbeblöcke vor dem Live-Zeitpunkt als nicht verwendbar markiert, obwohl ein Trailer schon vor der eigentlichen Live-Ausstrahlung gesendet werden kann.

**Comment by nittka** [comment]
Das Problem mit der falschen Trailer-Markierung dürfte ein Methodenaufruf mit vertauschten Parametern gewesen sein. Das Hauptproblem ist noch unbearbeitet.

**Comment by GWRon** [comment]
> die Sendung kann auch mit Startzeit 15 bis 19 Uhr sowie 2 bis 5 Uhr gesendet werden

Kannst Du mir das bitte nochmal anders umschreiben? Ich habe das nicht ganz verstanden.

**Comment by nittka** [comment]
Morning-Show wie beschrieben umdefinieren. Erwartung ist, dass als Startblock nur die Zeiten 20 bis 0 Uhr funktionieren, alle anderen nicht. Neben der fehlerhaften Blockmarkierung können aber auch die abweichenden Startblöcke 15 bis 19 Uhr sowie 2 bis 5 Uhr gewählt werden.

**Comment by GWRon** [comment]
Sollte eigentlich nun funktionieren - aber schau lieber nochmal nach (falls ich was falsch verstanden hatte).

Durch einen "Variablendreher" ("start - ende" -vs-  "ende - start") sind diese "Luecken" entstanden.

**Comment by nittka** [comment]
Die Anzeige im Programmplaner passt jetzt. Aber der Drop eines Programms wird noch nicht in allen Fällen korrekt verhindert.
Mögliches Testsetup:
Papierflieger auf 6 Blöcke verlängern und den Folgen Ausstrahlungszeitbegrenungen verpassen:
* start 0 end 10
* start 8 end 18
* start 16 end 0
* start 20 end 4

Die letzten beiden Fälle werden noch nicht korrekt behandelt und man kann auch so senden, dass nur ein Block in der vorgeschriebenen Zeit liegt.

**Comment by GWRon** [comment]
Konnte ich nachvollziehen und habe die entsprechende Funktion ueberarbeitet

**Comment by nittka** [comment]
Die Prüfung, dass die Startzeit >= Startslot ist, passt nicht in allen Fällen:
* Beschränkung 20 Uhr bis 4 Uhr
* 2 Blöcke
* Start um 0, 1, 2 auch möglich

Außerdem hast Du die "exposedToLua"-Methde umbenannt, ohne den KI-Code anzupassen. Da fliegen nun Segmentation-Faults.

**Comment by GWRon** [comment]
> Die Prüfung, dass die Startzeit >= Startslot ist, passt nicht in allen Fällen:
> 
> * Beschränkung 20 Uhr bis 4 Uhr
> * 2 Blöcke
> * Start um 0, 1, 2 auch möglich

Ich denke "hour" sollte einfach im Falle des Falles von "< startzeit" auch um 24 erhoeht werden ... oder aehnlich

**Comment by GWRon** [comment]
Ich hoffe nun erwische ich alle "Moeglichkeiten".
