### ISSUE TITLE
Berufsfilter Laien

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#406]
Wenn ich bei der Besetzungsauswahl vom konkreten Beruf auf "alle Berufe" umschalte, verschwinden z.T. Laien, die beim konkreten Beruf verfügbar waren. Ich hätte erwartet, dass dort auch die Laien aller Berufe verfügbar wären. Man kann natürlich argumentieren, dass dann die Anzahl der Laien zu hoch wäre, aber es gibt ja noch andere Sortiermöglichkeiten und schließlich hat man ja "alle Berufe" gewählt...

**Comment by GWRon** [comment]
Ich finde, es sollte nicht alle moeglichen Amateure gelistet werden.

Man muesste sonst alle auflisten, die zu einer der Kategorien passen. Also nicht nur "haben Interess an irgendwas", sondern "haben Interesse an Schauspieler, Regisseur, Musiker, ... oder Moderator).

Ich verstehe das grundsaetzliche Anliegen, verwehre mich aber dem Gedanken, da 25 Amateure aufzulisten.

**Comment by nittka** [comment]
Kann ich verstehen. Dann konkretisieren ich die Frage: Ich soll die Regie besetzen. Dann werden mir 5 Amateur-Regisseure angeboten. Ich wechsle auf "Alle Berufe" - dann werden mir fünf andere andere Amateur-Regisseure angeboten !?

(In diesem Zusammenhang als kleiner Bug vielleicht relevanter: wenn man die Sortierung wechselt und dann einen Filter - Männer/Frauen oder Berufe, wird zwar das Icon der Sortierung nicht geändert, aber die tatsächliche Sortierung entspricht nicht dem Icon).

**Comment by nittka** [comment]
Wenn ich es mir recht überlege, fände ich es auch nicht schlimm, bei "alle Berufe" gar keine Amateure zu sehen. Wenn man Laien will, sucht man sie sich in den konkreten Berufen.

**Comment by GWRon** [comment]
Das ist eine gute Idee.

Bei "alle" aber die Amateure herauszusuchen, die beim "originaeren" Beruf gelistet wuerden, waere auch leichf umzusetzen (die Variable dafuer ist ja mit uebergeben).
