### ISSUE TITLE
unterschiedliche Filter für Programmplaner und Archiv

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#409]
Im Archiv sollten alle eigenen Lizenzen angezeigt werden, nicht nur die verfügbaren. Konkreter Anwendungsfall sind Lizenzen, für die das Ausstrahlungslimit erreicht ist. Diese können zwar nicht mehr gesendet werden (Ausblenden im Programmplaner), aber sie könnten durchaus noch gehandelt werden (Holen im Archiv, Verkauf beim Filmhändler).

Die Filter haben schon ein checkAvailability, das für diese Unterscheidung genutzt werden könnte.

Ich betrachte das als Verbesserung und nicht als Bug, da es aktuell Fälle gibt, in denen das einen Unterschied macht.

**Comment by GWRon** [comment]
"checkAvailability" - das ist zu "generisch", denn auch Programme die man zwar hat, aber die bspweise temporaer nicht verfuegbar sind wuerden dann gelistet werden.

Oder vereinfacht: Lizenzen die man zwar schon hat, aber vielleicht erst zu einem bestimmten Zeitpunkt "freigeschalten" werden.


Ich denke, man muss da dann doch feingranularer vorgehen - "tradeable und available" oder aehnliches.

**Comment by nittka** [comment]
Ich würde argumentieren, dass alle Lizenzen in meinem Besitz im Archiv angezeigt werden sollten. Wenn sie nicht handelbar sind, werde ich sie in der Filmagentur auch nicht los.
LIzenzen, die erst später freigeschaltet werden, sollte es im normalen Spielverlauf ja gar nicht geben (sonst hätte man sie ja gar nicht bekommen). Das passiert eher bei den Dev-Kommandos (Lizenz zuweisen).
