### ISSUE TITLE
Studio: Verboten-Cursor bei Drehbuch-Drag über leerem Koffer

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#410]
Wenn man im Studio aktuell mit einem Drehbuch, das vorher im Studio stand, über dem leeren Koffer hovert, wird der Verboten-Cursor angezeigt. Der Drop selbst ist möglich. Ursache ist wohl ein Problem in der `guiListSuitcase.CanDropOnCoord(MouseManager.currentPos)`-Implementierung, wenn noch zusätzliche Slots zur Verfügung stehen würden.

**Comment by GWRon** [comment]
Da fehlte nur die "setminSize()"-Angabe, alle Slots da drin waren mit 0*0 versehen (ausser ein Element war dort platziert ... dann hatte es DESSEN Groesse).
