### ISSUE TITLE
Datenbank bei Einlesen eines Spielstands nachladen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#419]
Mittelfristig sollte es möglich sein (automatisch) beim Laden eines Spielstands den aktuellen Datenbankstand zu integrieren
* Übernahme neuer Filme
* Übernahme neuer Personen
* Ersetzung bzw. Aktualisierung der Drebuchvorlagen
* Übernahme neuer Nachrichten
* Übernahme neuer Werbung
* Anpassung von Bestandsdaten muss man genau betrachten, da sich Attribute im Laufe der Zeit ja auch verändern

Es gibt zwar schon das Kommando loaddb, ich glaube aber, dass die nicht dasselbe macht (zu prüfen).
Ob die Datenbank aktualisiert wird, kann durch einen Config-Schlüssel gesteuert werden.

Warum halte ich diese Funktion für sinnvoll:
* Man möchte nicht bei jeder neuen Version ein neues Spiel starten müssen, um neue Filme/Drehbücher zu sehen.
* Für Testzwecke (Balancing) kann es sehr praktisch sein, wenn man Spielstände von unterschiedlichen Zeiten (Reichweite, Erfahrung der Personen) etc. verwenden kann, um Werte für Filme/Serien/Drehbücher auszuprobieren.

**Comment by GWRon** [comment]
Das Problem von Balancingdaten ist...das die ja durchaus im Spielverlauf Änderungen erfahren.
Eine neugeladene DB kann also "Laufdaten" anpassen. Der Grund, warum ich das noch ne so angegangen bin.

**Comment by nittka** [comment]
Das Problem mit sich ändernden Daten sehe ich auch. Ich dachte insb. an die Werte bei Drehbuchvorlagen (und eben neue Einträge, die man auch im laufenden Spiel mitbekommt). Die Drehbücher haben ja bei jedem Startstand dieselben Ausgangswerte und da kann man schon Preis, Kritik etc. ausprobieren...

**Comment by nittka** [comment]
ReloadDb ist ja schon als Kommando möglich. Mindestens beim Einlesen der Drehbuchvorlagen gibt es allerdings einen Bug. Bei Serien kommen neue Folgen hinzu - die alten werden nicht "korrigiert".

**Comment by nittka** [comment]
Ich schließe dieses Ticket. Auch wenn es schön wäre, neue Datenbankeinträge nachladen zu können, ist der Implementierungsaufwand prohibitiv. Einfaches Hinzufügen ist ja nicht das Problem, aber Änderungen von IDs bestehender Einträge, geänderte Nachrichtenketten, Konsistenz von Variablendefinitionen etc. würden zu viel Aufwand bedeuten.
