### ISSUE TITLE
Mischen von live/nicht live in Serien

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#424]
Aktuell gibt es in der Datenbank keine solche Konstellation, aber wenn man einer Serie "live" als optionales Flag mitgibt oder Einzelfolgen einzeln live/nicht live setzt, geht das schief.
Der Studiodialog geht davon aus, dass immer alles live oder nicht live ist. Schlimmer ist aber, dass dass trotz erfolgter (Vor)-Produktion die Serie im Programmplaner nicht auftaucht. Außerdem kommt es zu einem Segmentation Fault bei der Datenblatt-Anzeige.
Das kann durchaus mit dem Umbau des Live-Verhaltens zu tun haben, in dem diese Konstellation nicht berücksichtigt wurde.

Zu klären wäre zuerst, ob ein solches Mischen überhaupt unterstützt werden sollte. Die Prüfung im DB-Editor könnte verschärft werden, um das auszuschließen.

**Comment by GWRon** [comment]
Ich kann mir vorstellen, dass eine "Premiere" / Pilotfolge durchaus "Live" sein kann und alle anderen dann eben nur noch "live on tape" oder so (oder andersherum).

Also muesste im Studio entsprechend alles an Zahlen nur live-Elemente beinhalten.


Einfacher ists natuerlich, den Misch-Masch nicht zu erlauben.

**Comment by nittka** [comment]
Eine erste Reparatur ist im Episodes-PR enthalten. Für Drehbücher mit Kindern, wird das Live-Flag anhand der Kindelemente ermittelt.

**Comment by nittka** [comment]
Das Mischen von Live- und Nicht-Live-Folgen in einer Serie ist prinzipiell möglich.
