### ISSUE TITLE
(Sport)-Producer testen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#426]
Ich mache gerade Testspiel (aktuell Tag 17 bei 12 Tagen pro Jahr) und frage mich, wie ich erkennen kann, ob die Producer aktiv sind und funktionieren. Die Log-Dateien werden ja beim Neustart eines Spiels überschrieben (ich hatte nicht daran gedacht, die immer wegzusichern).

**Comment by nittka** [comment]
Ich habe nochmal neue Spiele gestartet und vorgespult. Bei denen kommen am fünften Tag konsistent die Fußball-Live-Übertragungen in die Auktion. Wenn ich mir beim Laden eines Spielstands die Live-Übertragungen ausgeben lasse, kommt beim ersten "normalen" Spiel nur die Sommerolympiade; bei den Vorspulspielen auch die Fußballspiele.
Es sieht so aus, als ob im ersten Spiel irgendwas schiefgegangen ist.

**Comment by nittka** [comment]
Aufgrund seltsamer Umstände (siehe unten) musste ich ein neues Testspiel starten (aktuell Tag 7, ohne Vorlauf, mit Zwischenspeichern). Und erneut gibt es die Live-Übertragungen nicht. Kann es sein, dass beim Speichern (mit Beenden und Neustarten) die relevanten Informationen nicht mit persistiert werden (Producer/Liga-Informationen/...)? Ich habe die Sportnachrichten nicht abboniert (hatte ich in den Vorlaufspielen aber auch nicht).

Im Zuge der Vorlauftests hatte ich mal die Tage pro Saison auf 1 gesetzt und ein neues Spiel gestartet. Es gab dann zwar Fußballübertragungen, aber die Spiele der Saison 1985 wurden dann ein Jahr später live gesendet. Zumindest die Ligen sind also noch nicht auf kürzere/längere Jahre eingerichtet.
Noch seltsamer war aber folgendes (unklar ob Zusammenhang besteht). Ich habe ohne Zurücksetzen der Saison-Länge mein originales Testspiel geladen und weitergespielt. Irgendwann wurde es dann extrem langsam. Speichern und Laden haben über 30 Sekunden gedauert und ich hatte tonnenweise Sportnachrichtenduplikate in den Nachrichten. Das gespeicherte Spiel hatte eine Größe von mehreren 100MB. Es sieht so aus als wäre die Erzeugung von Fußballspielergebnissen Amok gelaufen.
Ist die Anzahl der Tage der Saison Teil des Spielstands oder wird sie immer nur aus der Config übernommen? Das würde nämlich zu inkonsistenten Spiele führen können.

**Comment by nittka** [comment]
* Spiel starten
* Schnellvorlauf zum vierten Tag
* Speichern
* zum fünftenTag weiterlaufen lassen -> Fußball-Live-Übertragungen bei der Auktion verfügbar
* Spiel beenden und Spiel laden
* zum fünften Tag weiterlaufen lassen -> Fußball-Live-Übertragungen nicht verfügbar

Hier geht also beim Speichern Information verloren.

**Comment by GWRon** [comment]
Ich schau mir das an. War vorhin unterbrochen worden...Sohnemann hat nun mit mir spontan Fahrradfahren gelernt (endlich ;-)).
