### ISSUE TITLE
Programmlizenzen: Datenblatt überfüllt

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#428]
![datenblatt_lang](https://user-images.githubusercontent.com/2625226/137801909-4fba69c1-a937-4c6a-a355-b0339f4cf269.png)

Ich glaube wir muessen uns da was ueberlegen ... im Zweifel koennte evtl die Beschreibung gekuerzt werden, oder weniger Darsteller anzeigen...

ODER ... Dinge wie "Im Programmplan" bekommen ein Icon in einer oberen Ecke des Datenblattes (aehnlich dem Message-Icon). denn "im Programmplan" enthaelt immer nur diese Information, nie weitere Angaben.

**Comment by nittka** [comment]
* "Programm im Sendeplan" ist überflüssig, wenn man im Programmplan hovert (dazu muss dann natürlich die API angepasst werden)
* Das Datenblatt kann noch x Punkte nach oben verschoben werden (gleicher Rand wie zu den Seiten)
* Live-Ausstrahlung als Ribbon geht nur, wenn das Always-Live-Flag vorhanden ist - die Ausstrahlungszeit muss sonst angezeigt werden
* Die Beschreibung grundsätzlich zu kürze, halte ich für problematisch, da sie an keiner anderen Stelle in gelesen werden kann. Wenn man natürlich die Höhe berechnen kann, kann der leere Teil vermieden werden.
* Der zweizeilige Titel verbraucht natürlich auch viel Platz
* Und die Spendengala vereinigt (fast) alles, was Platzprobleme verursachen kann.

**Comment by nittka** [comment]
Wird als behoben betrachtet. Mehr Platz entsteht ggf. auch durch eine erhöhte Grundauflösung.
