### ISSUE TITLE
Generierung eindeutiger Titel

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#430]
Sowohl im letzten Release als auch im aktuellen Entwicklungsstand funktioniert das Erzeugen eindeutiger Titel nicht 100%ig. Beispiel Morgenshow (4 Produktionen aufgrund eines Scripts möglich).
* 2 Produktionen planen, Vorproduktionen abschließen und erste Folge ausstrahlen
* 2 neue Einkaufszettel holen - die neuen Titel sind nicht wie erwartet `#3` und `#4`

Wenn man sich sofort 4 Einkaufszettel holt, passt es aber.

**Comment by nittka** [comment]
Ich werde kurzfristig nichts an diesem Ticket machen. Man könnte zwar die Namen der vorhandenen Konzepte aufsammeln und dafür sorgen, dass es keine Duplikate gibt. Aber sobald ein Programm ausgestrahlt wurde, ist das ehemals vorhandene Konzept weg. Man müsste dann also auch noch alle Programme raussuchen, die auf Basis des Scripts erzeugt wurden und deren Namen abgleichen.

**Comment by GWRon** [comment]
Du kannst auch die "ProtectedTitles" durchgehen...nicht perfekt, aber an zentraler Stelle erreichbar.

**Comment by nittka** [comment]
Die ProtectedTitles sind scheinbar auch keine Lösung, denn "Goldene Morgenstunden" wären schon geschützt, weil der Scriptname geschützt wurde, d.h. beim Ermitteln des Namens der ersten Produktion ist der Name schon vergeben und man würde mit der Zählung anfangen. Auch kommt der Name der zweiten Produktion nicht in die Liste.
Man müsste nicht die ProtectedTitles (der Drehbücher) durchgehen, sondern die Namen aller vorhandenen Programme.

**Comment by GWRon** [comment]
Der Schutz kann natuerlich auch in Klassen unterteilt werden..drehbuecher, programme...

**Comment by nittka** [comment]
Versehentlicher Push auf den Master
