### ISSUE TITLE
Fahrstuhlgeschwindigkeit

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#437]
Das nächste große Thema, an dem ich mich zumindest mal versuchen möchte, ist die KI (nach dem nächsten Release). Ein Problem, dass ich sowohl für das Testen als auch für reguläre Spiele sehe, sind die Wegzeiten zwischen den Räumen. Wird die Spielgeschwindigkeit erhöht, hat ein KI-Spieler in einen nicht kompensierbaren Nachteil. Als menschlicher Spieler kann ich "Vorspulen", wenn ich weiß, dass alles so ist, wie ich es mir wünsche. Dann warte ich und muss nicht im Haus rumfahren. In derselben Zeit, hat die KI aber wirklich zu tun und schafft wegen sonst locker umsetzbare Aufgaben nicht, da die Wegezeiten nicht entsprechend der Spielgeschwindigkeit kleiner sind.
Mein Vorschlag wäre, dass ab einer bestimmten Spielgeschwindigkeit die Fahrstuhlgeschwindigkeit auf "unendlich" und die Wartezeit der Tür auf Null gesetzt werden und erst wieder die "normalen" Werte annehmen, wenn die Spielgeschwindigkeit wieder unter diese Schwelle fällt.

Das sollte insb. beim Testspielen von KI-Änderungen helfen, da man schneller realistische Aussagen über die gemachten Anpassungen bekommt. Man möcht ja nicht den Rechner über Nacht in Normalgeschwindigkeit spielen lassen, um sich morgens die Ergebnisse anzuschauen.
Aber auch im normalen Spiel, wo man vielleicht kurzzeitig vorspult, verringert sich der dadurch entstehenden Nachteil für die KI.

**Comment by GWRon** [comment]
OK, also ab einer gewissen Spielgeschwindigkeit -- bzw generell, wenn man "vorspulen" moechte, springt dann der Fahrstuhl direkt alle Punkte an.
Damit sollte auch das derzeit noch moegliche "Zusteigen" (man erreicht den Fahrstuhl noch gerade rechtzeitig, bevor die Tueren schliessen) nicht noetig sein, da ja nach 2-3 Updatezyklen der Fahrstuhl eh "wieder da" ist.

Aehnlich kann auch mit den Figuren vorgegangen werden ... ich meine damit nicht das direkte Beamen in die "Raeume" sondern das beamen zum Fahrstuhl ... und spaeter vom Fahrstuhl zum Raum. Damit verhindert man, dass bspweise zeitgleich zwei Figuren zum Filmhaendler "beamen" - und einer dabei auf der Etage drunter, mit gerade wartendem Fahrstuhl startet - und ein anderer 5 Etagen entfernt.
Sprich die "Reihenfolge" wuerde beibehalten.

Problematischer ist aber die Bearbeitungsgeschwindigkeit der KI. Wenn die an manchen Stellen zu lange braucht (da sie im Normalfall ja "genug Zeit hat - auch fuer komplexes"), muesste man hier wohl etwas wie ein "warte auf mich" Signal der KI einfuehren.
Immer wenn sie "tickt" und eine Aufgabe innerhalb einer gewissen "Spielzeit" (also bspweise 10 Hochhaus/Spielminuten) stattfinden muss, schaltet sie ein "ich hab was gestartet"-Flag auf True bzw eine "Warte in X Minuten auf mich"-Stoppuhr an.
Ist die Aufgabe beendet, wird die Stoppuhr ausgeschalten / Flag deaktiviert.

Damit wuerde es im Zweifel beim Schnellvorlauf manchmal "ruckeln", weil sichergestellt wird, dass die KI ihre Aufgaben auch angemessen erledigen kann.

**Comment by nittka** [comment]
Ich habe mir die Synchronisationsmechanismen noch nicht angeschaut. Für die KI würde ich aber zunächst auch den Brain-Speed massiv erhöhen; ob dann ein "Warte auf mich"-Flag wirklich nötig ist, kann ich aktuell noch nicht abschätzen. Mechanismen für das "Schlechtermachen" kann man aktivieren, wenn die KI anfängt zu gut zu spielen. Im Moment gibt es dieses Problem aber noch gar nicht. 

Über die Wege vom/zum Fahrstuhl hatte ich mir noch keine großen Gedanken gemacht. Aber ja, die "Laufgeschwindigkeit" muss auch bedacht werden. Wie würdest Du denn zwischen Spielgeschwindigkeit erhöhen und Vorspulen unterscheiden? Wenn ich an das "Nicht-Dev-Spiel" denke, in dem die rechte Pfeiltaste gedrückt gehalten werden muss, um kuzzeitig die Spielgeschwindigkeit sehr viel höher zu setzen: Da würde ich nämlich zwar die Fahrstuhlgeschwindigkeit hochsetzen, aber nicht unbedingt die Laufgeschwindigkeit auf unendlich, sonst könnte man sich ggf. als menschlicher Spieler "fast" beamen (Tastenkürzel für Werbeagentur, kurz vorspulen und man wäre in Spielminuten vielleicht viel schneller da, als wenn man normal geht). Das sollte auf alle Fälle vermieden werden.

Deiner Antwort entnehme ich aber, dass Du Anpassungen in dieser Richtung offen gegenüberstehst.

**Comment by GWRon** [comment]
Ja ich bin da relativ offen eingestellt.

Die "Steps/Brainspeed/..." waren damals auch notwendig, da die KI nicht in Threads ablief - und wenn da was aufwaendiges gemacht wurde, konnte es zu Mikrorucklern kommen.


Bezueglich Geschwindigkeiten hat mich immer die fehlende "Synchronisation" von Laufgeschwindigkeit, Spielgeschwindigkeit und Hochhausgeschwindigkeit (Fahrstuhl etc) "gestoert" -- allerdings war eine moegliche Entkopplung notwendig um ein Balancing zu erleichtern ("vielleicht sollte das Spiel die Zeit schneller ablaufen lassen, aber Bewegungen sollten gleich schnell bleiben").
Da einige Dinge von der "Physik" abhaengig waren (Figur muss "ankommen"), und das damals noch nicht ganz so getrennt ablief, ... ist da einiges "organisch" gewachsen ... kann also gern ueberarbeitet werden.

**Comment by nittka** [comment]
Die Hinweise zur Entwicklungsgeschichte waren sehr hilfreich für das Verständnis. Die Sachen für die KI könnten also durchaus vereinfacht werden (außer man lässt Brainspeed noch als zukünftige Stellschraube drin).

Die Auftrennung in Lauf-, Spiel- und Fahrstuhlgeschwindigkeit finde ich aber gar nicht schlecht. Bei den drei Spielgeschwindigkeiten werden sie ja auch alle drei gemeinsam geändert. Und im Nicht-Dev-Modus kann man beim Vorspulen auch nur alles gemeinsam anpassen. Da haben wir also Einfluss auf die Synchronisation. Nur im Dev-Modus sind links/rechts/oben/unten und die Geschwindigkeitsänderungen mit den Zahlen vielleicht unverständlich/nicht intuitiv.

**Comment by nittka** [comment]
Um es bei der Fahrstuhlgeschwindigkeit nicht zu kompliziert zu machen, könnte man auch einfach eine "KI-Debug"-Geschwindigkeit definieren (Debug-Screen oder eine vordefinierten Vorspulgeschwindigkeiten), in der die Gebäudezeit analog zur Weltzeit hochgesetzt wird. Da spielt eine "angenehme Animation" ja keineRolle. Analog würde ich in der Nicht-Dev-Variante die Gebäudezeit beim Vorspulen anheben, damit die KI dort nicht so startk benachteiltigt wird.
Bei den 3 Geschwindigkeitsleveln kann es ja so bleiben, wie es ist, da alle Spieler gleich behandelt werden (beim Vorspulen eben nicht, da der menschliche Spieler das nur macht, wenn er selbst nichts zu tun hat).

**Comment by nittka** [comment]
Mein Vorschlag wäre, die Geschwindigkeitsanpassungen etwas zu vereinfachen und 2 Fälle zu unterscheiden: die 3 Presets wie bisher und Vorspulen.
Bei den Presets wird unverändert die Spielgeschwindigkeit stärker erhöht als die Gebäude-/Laufgeschwindigkeit.
Beim Vorspulen wird aber immer alles in gleichem Maß angepasst. Das Vorspulen ist für das Überbrücken von Zeit gedacht, in der der menschliche Spieler nichts machen möchte, die KI aber weiterhin zu tun hat und nicht durch künstlich reduzierte Laufgeschwindigkeit behindert werden darf.

Auch die Manipulationsmöglichkeiten sollten entsprechend vereinfacht werden:
* Pfeiltaste hoch und runter entfallen (nur Anpassung der Weltgeschwindigkeit)
* alle anderen Möglichkeiten (5,6,7,8,9, Pfeiltasten mit/ohne Ctrl) werden auf dieselbe "Vorspul"-API umgestellt

**Comment by GWRon** [comment]
Die Tasten waren urspruenglich auch zum Ausbalancieren der Geschwindigkeiten gedacht.

Kann aber gern deaktiviert /auskommentiert werden.
