### ISSUE TITLE
Optionale Flags bei Serien

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#440]
Ich bin mir bei der Behandlung von optionalen Flags bei Serien unschlüssig (Hintergrund "Abgezockt").
Wenn im Header optionale Flags definiert sind, sollten diese dann für jede einzelne Folge neu ausgewertet werden oder sollten diese Flags dann einmalig ermittelt werden und für alle Folgen gelten?

Aktuell werden sie für jede Folge neu ermittelt. Aber gerade für das Live-Flag scheint mir das seltsam. Warum sollte (nur) eine einzige Folge der Serie live sein? X-Rated oder Trash könnten sich ja durchaus unterscheiden...

**Comment by GWRon** [comment]
Episoden koennen die optionalen Flags doch ueberschreiben oder?

Bei "mehrfach produzierbaren" Dingen wie Shows...hmm da koennte man es immer neu auswuerfeln.

Oder.. komplexer machen und dynamic_optional_flags und static_optional_flags einfuehren. Letzteres gilt fuer alle Elemente, dynamic wird immer neu ausgewuerfelt

**Comment by nittka** [comment]
Ein Überschreiben ist möglich. Wenn aber die Flags nur beim Header definiert sind, scheint es mir natürlicher, wenn dann alle Folgen die Flags des Headers bekommen (für Live mehr, für X-Rated weniger). Noch komplexer machen würde ich es nicht. Es kann auch so bleiben, wie es aktuell ist.
Bei der Abgezockt-Serie finde ich es eben nur etwas verwirrend, wenn nur eine von 5 Folgen live ist...

**Comment by GWRon** [comment]
Falls jemand unbedingt spezifische Flags braucht, kann man das noch einfuehren (sie _ersetzen (nicht ergaenzen!) dann die Flags des Headers).
Kannst das also gern so umsetzen, dass "einmalig" die Flags ausgewuerfelt werden.
