### ISSUE TITLE
LoadImage() usage without passing flags

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#444]
@Hezkore wrote:
> You've used LoadImage in quite a few places
Some specify a flag by using `data.GetInt("flags", 0)` while others don't specify any flags
`data.GetInt("flags", 0)` defaults flags to `0`, which means that there won't be any filtering on those images, which is good!
(At least for figures? Maybe interface should use some filtering?)
BUT!
All the LoadImage that doesn't specify any flags will use flag `-1`, and that in turn will use whatever `AutoImageFlags` is set to, which defaults to `MASKEDIMAGE | FILTEREDIMAGE`
So you're getting filtering on some images (figures) and others don't have any filtering

Think we need to ensure that eg an "copy" within sprites or via imagehelper reuses the existing flags - or overrides them if specified so.

**Comment by nittka** [comment]
Ist das Problem mit be49d21ce7db71d791500cf72c6da6bc339dba36 behoben oder gibt es weitere relevante Stellen?

**Comment by GWRon** [comment]
Ich denke ... es kann maximal sein, dass manche Sprites manuell einen Flag uebergeben haben sollten (damit sie immer "pixelig" bleiben oder aehnliches)
