### ISSUE TITLE
Sammy-Benachrichtigung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#448]
Aktuell wird der Spieler nur informiert, wenn er selbst den Sammy gewonnen hat. Es muss auch eine Benachrichtigung geben, wenn ein KI-Spieler einen Sammy gewinnt (z.B. News-Sammy).

"<X> hat den <Y>-Sammy gewonnen."

**Comment by GWRon** [comment]
Frage: Muss man wirklich per "Toastmessage" informiert werden - oder reicht es, sich den Missmut vom Chef anzuhoeren ("Sie Taugenichts... jemand anderes hat den Sammy für ... gewonnen.") ?

**Comment by nittka** [comment]
Ich glaube, selbst wenn es einen täglichen Zwangsbesuch beim Boss gäbe, fände ich es besser, wenn eine Toastmessage kommt.
Es gibt alle paar Tage einen Sammy, da tut diese eine Benachrichtigung nicht weh - wenn man nie zum Chef oder zu Betty geht, kekommt man so zumindest mit, dass es sowas wie den Sammy gibt. Außerdem kann man dann in den archivierten Nachrichten nochmal nachschauen.

(Überflüssige Nachrichten: "Ihr Kontostand ist negativ" und eine Werbung später "Ihr Kontostand ist wieder positiv" - das bekommt man meist selbst schnell mit, wenn man Filme oder Nachrichten holen will; Hier würde eine Nachricht reichen, wenn man ernsthaft in Gefahr ist: "Wenn Sie nicht innerhalb von 12 Stunden einen positiven Kontostand...)

**Comment by nittka** [comment]
Im Zuge dieses Tickets (testen muss ja einfach sein) könnte die Debug-Ansicht ergänzt werden: Sammy-Verleihung anstoßen, unterschiedliche Sammys starten (Politik-Simulation?)

**Comment by GWRon** [comment]
Bin an der DEV-/Debug-Ansicht dran.

**Comment by nittka** [comment]
Beim Kultur-Award könnte es eigentlich auch ein paar Betty-Prozentpunkte geben.

**Comment by GWRon** [comment]
also die DEV-Ansicht ist ja nun drin ... koennen wir uns also um das Ticket kuemmern:

- Benachrichtigung auch beim Gewinn anderer Spieler
- Anpassung "Gewinn" bei Kultur-Award

**Comment by nittka** [comment]
Die Benachrichtigung funktioniert fast - es wird Betty 200 statt 2% angezeigt; und sie werden immer angezeigt.
Betty-Liebe gibt es nun aber bei allen Sammys. Angezeigt werden immer 200, aber es werden so viele Prozentpunkte wie beim Image vergeben.

**Comment by GWRon** [comment]
Es sollen auch keine Prozente angegeben werden...ich fuege ja 200" hinzu...nicht 0.02 mal Maxwert.

**Comment by nittka** [comment]
Aber beim Image wird ja auch 0.5 % hingeschrieben und hinterher sind es 0.5% mehr im Interface!?
DIe Betty-Punkte bei den anderen Sammys sind in jedem Fall noch ein Problem.

**Comment by GWRon** [comment]
Wenn Du eine Idee hast, wie man "ausbalanciert" die Anzahl/Qualitaet/... der Kultursendungen mit reinnehmen kann - bspweise direkt den "Score", koennte die Betty"-liebe" davon abhaengig gemacht werden. Also ein dynamischer Bonus (den Wert bei "finish" anpassen ...).


Image:
Ja, da wird ja auch ein relativer Zuwachs von bspweise "0.5" angegeben
```
	Field priceMoney:Int = 50000
	Field priceImage:Float = 2.5
	Field priceBettyLove:Int = 0
```
Money: absoluter Wert
image: 2.5 "%"
Love: absoluter Wert

Man kann aber wenn du das magst, die 200 bei der "Ausgabe" in Prozent umrechnen lassen.

**Comment by nittka** [comment]
* ich würde die Betty-Punkte gar nicht in die Sammy-Beschreibung oder die Toastnachricht nehmen (bei Nachrichten und Filmen aus dem Bereich Kultur steht ja auch nicht dabei, dass es Betty-Punkte gibt)
* ich würde zunächst einfach pauschal 0.5% (nur) bei Kultur-Sammy-Gewinn vergeben
* ich habe mir die Gewinnerermittlung noch nicht angeschaut, mindestens gibt es da ja ein Verhältnis zwischen den Spielern (Punktestand); der könnte ja auch bei der Berechnung herangezogen werden - wenn nur ein Spieler Kultursendungen gebracht hat, bekommt er mehr Punkte als wenn es ein Kopf-an-Kopf-Rennen gab.
* Wenn bei Ausstrahlung einer Kultursendung "Sammy-Punkte"  anhand der Qualität vergeben werden (gute Sendung mehr Punkte als "schlechte"), könnten auch diese Punkte direkt in den zusätzlichen Liebesgewinn umgerechnet werden

(Langfristig könnte es natürlich auch Betty-Punkt-Abzug geben, wenn ein Spieler nur Kultursendungen bringt, wenn ein Sammy winkt ;-) )

**Comment by GWRon** [comment]
> * ich würde zunächst einfach pauschal 0.5% (nur) bei Kultur-Sammy-Gewinn vergeben

0.5% generell - oder nach jetzigem Stand - also 0.5 von 10.000?
Es geht darum, ob man hier einen relativen Zugewinn macht, oder einen absoluten?

Gern koennen wir auch folgenden Wert addieren:
`Ceil((1.0 - GetInLovePercentage(playerID)) * baseValue)` (baseValue waere dann bspweise die 200).
Am Anfang ist sie damit noch leichter zu beeindrucken als spaeter.
Der "Faktor" kann auch gern nochmal quadriert werden um den Effekt nichtlinear abzuschwaechen.

**Comment by nittka** [comment]
Zunächst einfach halten und absoluten Zugewinn? Den Sammy gibt es ja ohnehin nur alle paar Tage. Verschnörkeln lässt sich das später immer noch (Ausgangspunkt des Tickets war ja die Benachrichtigung aller Spieler).

**Comment by GWRon** [comment]
Sollte nun bei 0.5% (50 von 10000) sein - und nicht mehr angezeigt werden.

**Comment by nittka** [comment]
Eine letzte Verbesserungsmöglichkeit wäre eine Information, wenn niemand den Sammy gewonnen hat. Ich glaube, auch bei MadTV kam dann : Der X-Sammy wurde nicht vergeben.
Ansonsten passt es für mich.
