### ISSUE TITLE
Raumanzeige Aufzug vs. Raumplan

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#451]
Meldung aus dem Forum: nach Anmieten eines Studios wird das im Aufzug nicht angezeigt. Zu prüfen:

* Änderungen nach Miet-Aktionen
* Änderungen nach manuellem Umhängen am Raumplan
* automatisches "Zurückhängen" einmal am Tag

**Comment by GWRon** [comment]
Auch wuerde ich noch hinzufuegen: Dev-Ansicht vom Raummakler sollte ein bequemes "Freiraeumen" (Kicken des Mieters) erlauben. Damit laesst sich dann auch spaeter prima ueberpruefen, was passiert, falls eine Laufende Produktion durch sowas betroffen wird.

**Comment by nittka** [comment]
Ich kann das Problem bei mir bislang nicht reproduzieren. Nach Anmieten eines Studios wird die richtige Bezeichnung sowohl im Fahrstuhl als auch beim Raumplan angezeigt (Fehlermeldung zu alter Version/Vermietung beim Makler nicht bestätigt scheinen aber auch eher unwahrscheinlich...).

Allerdings sind mir dabei andere Kleinigkeiten aufgefallen:
* Debug Send Terrorist sollte keinen zufälligen Raum nehmen sondern den Raum, der laut Raumplan dran sein soll
* Hat man ein neues Studio gemietet und der Terrorist geht dorthin, erscheint in der Meldung der ursprüngliche Mieter und nicht "Studio ..."

**Comment by GWRon** [comment]
Aarne per Discord:
> Die KI vertauscht die Schilder, das sehe ich am Fahrstuhl (-Menü). Wenn ich die dann selber vertausche ändert sich das nicht am Fahrstuhl..

**Comment by nittka** [comment]
Auch dieses Problem kann ich lokal nicht reproduzieren. Dasselbe Problem hattest Du übrigens für #305 im letzten Release behoben. Wenn ich den entsprechenden Commit rückgängig mache, sehe ich das beschriebene Verhalten - meine Änderungen an der Tafel sind nicht im Fahrstuhl sichtbar und Anmieten eines Studios führt nicht Änderung der Schilder.

Beziehen sich die Fehlermeldungen wirklich auf die neuste Version - dann bräuchten wir genauere Hinweise zum Reproduzieren.

**Comment by nittka** [comment]
Arbeitshypothese: Es wurde mit einem "alten" Spielstand weitergespielt und es gab noch keinen Grund, die persistierten Schilder zu aktualisieren (weiteres Studio anmieten).
Das sollte sich lokal einfach nachstellen lassen:
* Reparaturcommit rückgängig machen
* Spiel starten und Studio mieten
* speichern
* aktuellen Codestand wiederherstellen
* Spiel laden
* Fahrstuhl betrachten und dann weiteres Studio mieten
* im Besten Fall stimmt die Anzeige dann und das Ticket ist gelöst

(ggf. gleichzeitig Schildervertauschen mitprüfen) Hier wäre interessant, ob die vor dem Speichern getauschten Schilder nach dem Laden korrigiert sind oder nicht)

**Comment by GWRon** [comment]
Aarne per Discord:
> Tatsächlich.. wie es aussieht habe ich das Spiel tatsächlich am Samstag den 13.11. runter geladen.. erfreue mich jetzt der frischen Version 7.1 xD

**Comment by nittka** [comment]
Ich konnte beide Probleme nicht mit der neuen Version reproduzieren. Das bequeme Kicken der Mieter ist noch nicht implementiert.
