### ISSUE TITLE
Drehbuchvarianten: Bessere Titel

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#458]
Quelle: https://www.gamezworld.de/phpforum/viewtopic.php?pid=89605

Ronny:
> Das die Titel unschoen sind, daran werden wir denke ich bis zur naechsten Version arbeiten.
Neben dem "Jahr" oder einer Nummer, kann es auch "NAME's Dracula" (bzw in Deutschland dann "NAMEs Drakula" sein). Dazu muessten die Produzenten aber auch einige kurze Namen zugewiesen bekommen.
Andere Ideen hab ich mit Nittka schon kuerzlich besprochen.

Eventuell sollten wir hier knapp ueberlegen, wie wir die Titelproblematik angehen sollten. Derzeit habe ich folgende Vorschlaege:
- Drehbuchtitel %JAHR%
- Drehbuchtitel #%NUMMER%
- %GENERIERTER_VORNAME%s Drehbuchtitel

Generell sollten diese Drehbuchtitel aber vielleicht schon definieren, welche der Varianten "moeglich" sind. Manche Optionen klingen bei bestimmten Titeln sonst einfach bloed.

Auch betrifft die Problematik vorwiegend Drehbuecher mit "fixem" Titel (nicht bestehend aus "template variables").

**Comment by nittka** [comment]
Weitere generelle Überlegungen:
* Anzahl der Produzenten in Config einstellbar
* Bei der Auswahl der Drehbuchtitel stärker filtern, wenn ein "#" drin vorkommt
* schon bei der Drehbucherstellung noch besser Duplikate wegfangen (wenn ein Drehbuch aus einer Vorlage erstellt wurde, dann aber nie verwendet wird, kann es nach einer gewissen Zeit komplett gelöscht werden, damit muss auch der Titel nicht mehr geschützt werden und kann für für ein neues Drehbuch verwendet werden)

**Comment by nittka** [comment]
Die Produzenten versuchen nun Titel mit Zähler zu vermeiden. Die Konfigurierbarkeit der Produzenten ist weiter offen.

**Comment by nittka** [comment]
Beim längeren eigenen Testspielen ist mir aufgefallen, dass z.B. Goldene Morgenstunden in Version 4 in der Drehbuchagentur angeboten wurde. Ich habe sie selbst einmal geholt, habe sie aber nicht beim Filmhändler gesehen (Vermutung wäre also, dass sie nicht von einem der Produzenten geholt wurden).
Wie oben beschrieben wäre zu prüfen, ob die anderen Drehbücher noch "verfügbar" sind also auch nochmal in der Drehbuchagentur auftauchen können; also Ablauf der Drehbucherstellung prüfen: Vorlage nur verwenden, wenn gerade kein Drehbuch dieser Vorlage existiert.

**Comment by nittka** [comment]
Die Produzenten schauen jetzt nach Zählern im Titel und die Drehbuchvorlagen wurden an einigen Stellen um Variablen erweitert, wodurch diese zusätzlich reduziert werden sollten.
