### ISSUE TITLE
Programmproduzenten: Haeufigkeit

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#459]
https://www.gamezworld.de/phpforum/viewtopic.php?pid=89605

> Menge der Produktionen:
Eventuell sollten die Produzenten ihre Taetigkeit anfaenglich auch runterfahren  - und abhaengig von der verfuegbaren Menge an Lizenzen machen (so dass im jahrestechnisch spaeteren Spiel mehr produziert wird, als in den 80ern - da gibt es ja einiges an Material).

Heisst die Programmproduzenten holen die Information, welche / wie viele Lizenzen ueberhaupt derzeit zur Verfuegung stuenden (gern auch nicht fuer "jetzt", sondern einen Zeitstempel, der 1-2 Spieltage in der Zukunft liegt) - ist es zu wenig, wird was produziert. Wenn also die DB fuer ein Spieljahr nicht genug im Angebot hat, machen die Produzenten etwas mehr Dampf.

**Comment by nittka** [comment]
... nicht ganz trivial, denn die Anzahl allein ist nicht alles (Angebot in allen Preis-/Qualitätssegmenten).

**Comment by nittka** [comment]
Ggf. Anzahl der Producer in die Config.

**Comment by GWRon** [comment]
Und vielleicht auch in die "Starteinstellungen" (Neues Spiel) ?

**Comment by nittka** [comment]
Auch hier wäre mein Vorschlag, zunächst aufzuräumen, was offiziell konfigurierbar sein soll und dann eine GUI dafür bauen.

**Comment by GWRon** [comment]
Eventuell sollte das aber nicht in user.settings.xml oder die DEV.xml ... sondern sowas wie eine "game.settings.xml" (und spaeter dann direkt ein Verzeichnis mit bestimmten "Settings" / Missionen ...)

**Comment by nittka** [comment]
Ich finde die Idee einer separaten Settings-Datei gut. Dort könnte man dann auch unterschiedliche Parameter für die Schwierigkeitsstufen umsetzen. Vorschlag: sofort Unterverzeichnis gamesettings mit Standarddatei default.xml

**Comment by nittka** [comment]
Ein Vorschlag für die Konfigurierbarkeit der Anzahl der Produzenten liegt vor. Das Refactoring der Spielkonfiguration (neue Datei) würde ich in ein separates Ticket auslagern.
