### ISSUE TITLE
Abokosten Nachrichten

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#466]
Bei der Ermittlung der laufenden Nachrichtenkosten muss es noch ein Problem geben. Wenn ich unmittelbar nach Spielstart sämtliche Abos deaktiviere und vorspule, bekomme ich an den Folgetagen dennoch immer 10000 in Rechnung gestellt.

**Comment by GWRon** [comment]
Da muesste man wohl initial den abotimer setzen..damit es wie "frisch angeschaltet" wirkt.
