### ISSUE TITLE
Börsennachrichten verschwunden

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#472]
Ich hatte ja die Börsennachrichten so umgebaut, dass es einen initialen Trigger gibt und sich die Nachrichten dann selbst triggern. Zusammen mit einer anderen Änderung für die initialen Nachrichten scheint das Ergebnis aber zu sein, dass gar keine Börsennachrichten mehr kommen - möglicherweise weil der initiale Trigger nie mehr feuert.

**Comment by nittka** [comment]
Könnte mit Commit https://github.com/TVTower/TVTower/commit/a11b43c6e188046fd55cc9bc4015539b80c579a4 und Ticket #364 zusammenhängen.
Wenn ich in ScheduleTimedInitialNews die getriggerten Nachrichten ausgebe, erscheint dort der Börsennachrichtentrigger. Allerdings scheint dessen happen_time 0 in diesem Fall nicht wie erwartet zu funktionieren. Wenn ich stattdessen "1,2,3" (in zwei bis drei Stunden) eintrage, erscheinen die Nachrichten dann am nächsten Werktag...

**Comment by GWRon** [comment]
ScheduleTimedInitialNews - hat ja in seinem Kommentar schon stehen, dass es um _zukuenftige_ Ereignisse mit fixem Zeitpunkt geht. 

Hier ist fuer den Trigger aber ja `happen_time="0"`.
Wenn nun nach "kommenden Ereignissen" geschaut wird, ist die Funktion diese:
```
	'returns (and creates if needed) a list containing only initial news
	Method GetUpcomingNewsList:TList(genre:Int=-1)
		'create if missing
		If Not _upcomingNewsEvents Then _InvalidateUpcomingNewsEvents()

		If Not _upcomingNewsEvents[genre+1]
			_upcomingNewsEvents[genre+1] = CreateList()
			For Local event:TNewsEvent = EachIn newsEvents.Values()
if event.GetGUID().Find("news-stockexchange-trigger") >= 0
	print "DDD stock exchange: hasHappened()="+event.HasHappened()+"  happenedTime="+event.happenedTime
endif
				'skip events already happened or not happened at all (-> "-1")
				If event.HasHappened() Or event.happenedTime = -1 Then Continue
				'only interested in a specific genre?
				If genre <> -1 And event.GetGenre() <> genre Then Continue
				_upcomingNewsEvents[genre+1].AddLast(event)
			Next
		EndIf
		Return _upcomingNewsEvents[genre+1]
	End Method
```
mit der obigen "DDD"-schnell-in-den-logs-per-ctrl+f-zu-finden Debugausgabe findest Du: "hasHappened()=1" - entsprechend wird die Nachricht nicht als "kommend" hinzugefuegt.

Dazu muesste sie "-1" haben (aber dann wuerde sie ja auch nicht stattfinden.

Man muesste wohl neben den "timed" einfach noch alle initial-already-happened news abarbeiten (Effekte ausloesen)

**Comment by GWRon** [comment]
```Blitzmax
	Method ScheduleTimedInitialNews()
		Local scheduledCount:int = 0
		Local happenOnStartNews:TNewsEvent[]
		For local n:TNewsEventTemplate = EachIn GetNewsEventTemplateCollection().GetUnusedInitialTemplates()
			If n.happenTime >= 0 and n.IsAvailableAtHappenTime()
				local news:TNewsEvent = New TNewsEvent.InitFromTemplate(n)
				If news
					scheduledCount :+ 1
					Add(news)

					if n.happenTime = 0 'planned to execute right on start
						scheduledCount :- 1
						happenOnStartNews :+ [news]
					EndIf
				EndIf
			EndIf
		Next
		
		For local n:TNewsEvent = EachIn happenOnStartNews
			n.doHappen(GetWorldTime().GetTimeGone())
		Next
		
		TLogger.Log("ScheduleTimedInitialNews()", "Pre-Created " + scheduledCount + " news happening at fixed time in the future.", LOG_DEBUG)
		TLogger.Log("ScheduleTimedInitialNews()", "Pre-Created " + happenOnStartNews.length + " news and let them happen right now.", LOG_DEBUG)
	End Method
```
Damit war dann die Boersennachricht auch wieder drin.

![image](https://user-images.githubusercontent.com/2625226/145712336-9e7ecda3-b651-422e-b28c-19151d8c96f3.png)


Alternativ kann man natuerlich auch `LetGameStartInitialNewsHappen()` oder so einfuehren ... und dort entsprechend alle `happenTime = 0` hinzufuegen und dann `doHappen()` fuer sie ausfuehren. `ScheduleTimedInitialNews` sollte dann aber den happentime check von `>= 0` auf `> 0` abaendern.

**Comment by nittka** [comment]
Ich bin etwas hin- und hergerissen, ob es am Ende nicht doch einfacher ist, für diesen Spezialfall einfach die Triggerzeit in der Datenbank anzupassen. Es spielt ja keine Rolle, ob der Trigger sofort bei Spielstart zuschlägt oder eine Stunde später.

**Comment by GWRon** [comment]
Ja mir kam es auch etwas "unperfekt" vor. Allerdings braucht es denke ich so oder so eine Funktionalitaet um "direkt zum Spielstart" was mit den Nachrichten anzustellen ...

**Comment by nittka** [comment]
In ScheduleTimedInitialNews würde ich das doHappen der Events mit happenTime 0 direkt beim Drüberiterieren machen (if happentime = 0 then event.doHappen else add(event) end). Soll ich einen entsprechenden PR machen oder möchtest Du (ist ja schließlich Deine Lösung).

**Comment by GWRon** [comment]
Ich habe das in einem Extraschritt gemacht, falls doHappen Seiteneffekte hat. Theoretisch muesste es also vor dem Einplanen der spaeteren Nachrichten passieren.

Ich meine damit, dass eine Spielstartnews eine initale News freischalten/generieren koennte, die dann getimed werden kann.
Derzeit wuerde das in doHappen und den Effekten passieren...dann wuerde aber der Iterator der newsevents.values() evtl geaendert werden... Und dann ueberspringt es evtl eines der newsevents.
Deswegen hier die Trennung.


Kannst du aber gerne als PR machen.

**Comment by nittka** [comment]
Wenn die Trennung aufgrund möglicher Nebeneffekte beabsichtigt war, passt es für mich auch so. Ich war davon ausgegangen dass das add und das event.doHappen an sich dasselbe machen, nur dass eben das happenTime 0 bei add nicht funktioniert.

**Comment by GWRon** [comment]
"add()" fuegt die Nachrichten einfach hinzu - sie sind dann in den "allnewsevents" und "newsevents"-Maps.

Wenn dann die Nachrichtenagentur "GetUpcomingNewsEvents()" abruft, dann wird durch diese Maps (newsevents) gegangen und geschaut, welche bereit ist, aber noch nicht passiert. "happentime = 0" ist aber halt schon "happened" - und so wuerde ein nur per "add()" hinzugefuegtes Newsevent dann nicht bei "Upcoming" auftauchen.
Nur die "Upcoming" sind aber die, die ausgefuehrt wuerden (wenn der Zeitpunkt ran ist).

Wir haben also
"happentime = -1" fuer "noch nie passiert",
"happentime = 2132343242" fuer "passiert zum Zeitpunkt 2132343242" und
"happentime = 0" - was einfach zum Spielstart passieren soll (was ja 1985 oder 1990 sein kann).

**Comment by GWRon** [comment]
Vermutlich waer es "sauberer", der Triggernews ein "Ausloesen zum Spielstart"-Flag mitzugeben.

**Comment by nittka** [comment]
Für Initialnachrichten (Typ des Datenbankobjekts) ist meiner Ansicht nach happenTime 0 genau dieses Flag. Es sagt "unmittelbar ausführen", genau wie "in 3 Stunden" ja auch vom Spielstart gesehen in 3 Stunden ausgeführt wird. Datenbankseitig passt es also.
