### ISSUE TITLE
Musiksterne nicht live

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#474]
Olby1980 per Forum:
> Ein Fehler was mir aufgefallen ist, die Eigenproduktion "Musiksterne am Abend" die eigentlich -live- taucht nach der Vorproduktion nicht auf im -LIVE ORDNER- beim Programm gestalten, auch sonst nirgends, nur wenn die vorgegebene geplante Sendezeit dann vorbei ist, taucht es als gesendet unter Shows auf - ohne eben nie -live- gesendet worden zu sein.

**Comment by nittka** [comment]
Ich kann das Problem aktuell nicht reproduzieren:
* Version 0.7.1
* Vorspulen bis Musiksterne beim Drehbuchautor verfügbar
* Einkaufsliste, Konzeption, Produktion starten
* unmittelbar nach Abschluss der Vorproduktion ist das Programm unter "Live" und kann geplant werden.

**Comment by GWRon** [comment]
Wenn das nicht nachvollziehbar ist... schliessen?

**Comment by nittka** [comment]
Wahrscheinlich schon. Ich habe in der Zwischenzeit auch keine anderen Ideen gehabt, in welcher Konstellation das Problem auftreten könnte (ggf. neue Version mit Uraltspielstand).
