### ISSUE TITLE
Vorschlag: Programme - Kritik, Tempo... per Zufall

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#475]
Stukov per Forum:
> Wäre es eventuell in der Zukunft einmal moeglich die Werte für Kritik, Tempo und Kinokasseneinnahmen zufällig zu erstellen? Eventuell durch Eingabe von zB -1 in der Datenbank oder eventuell auch einfach für alle Filme über einen Button in den Settings?

Quelle: https://www.gamezworld.de/phpforum/viewtopic.php?pid=89624

Meine Replik:
> [...] Was [...] moeglich waere, ist fuer diese Werte "min und max" angebbar zu machen, und das Spiel wuerfelt dann beim Einlesen finale Werte aus.
> Also statt "speed=10" macht man "speed_min=5 speed_max=15" und es kann alles von 5 bis einschliesslich 15 final ausgewuerfelt werden.
> Ein "speed=-1" _koennte_ dann auch als "min=0 und max=100" interpretiert werden.
>
> Der Min/Max-Ansatz kommt ja schon bei einigen Elementen zum Einsatz (Qualitaeten beim Drehbuch, Attribute von Personen) - da waere es durchaus nur fair, dies auch bei "fertigen Programmen" anbieten zu koennen.

**Comment by nittka** [comment]
Ich schließe mich dem Wunsch an - er war auch auf meiner Langzeitspielspaß-Liste. Ohne Randomisierung kennt man irgendwann seine Filme und kann das Ergebnis abschätzen. Mit einer Randomisierung muss man beim Bewerten wieder genauer hinschauen.

(Ausschließlich) Der Min-Max-Ansatz würde aber verlangen, dass man für alle existierenden Programme Werte angibt, damit überhaupt randomisiert wird. Warum nicht einen oder mehrere Randomisierungsparameter in der Config erlauben, die bestimmen wie stark randomisiert wird (z.B. "Grad der Abweichung" vom definierten Wert). Je näher ein Wert an einem der Extreme liegt, desto kleiner sollte die mögliche Abweichung sein. Aus 0% oder 100% soll nicht 50% werden können. Auf diese Weise wird die "Charakteristik" eines Programms beibehalten.

Man könnte entweder einen globalen Randomisierungswert verwenden, der für alle Parameter gilt, oder einen Wert pro Parameter (Outcome nicht Verändern aber Kritikerbewertung sehr stark). Nicht vergessen, dass auch der Preis angepasst wird (unabhängig von den anderen Werten - es kann ja auch ein schlechterer Film teurer werden...)

**Comment by StukovTTV** [comment]
Genau das war auch meine Vorstellung dahinter, dass man nach x Monaten immer noch nicht roboterartig spielen kann und man auch weiterhin die Filme genauer ansehen muss

**Comment by nittka** [comment]
(@StukovTTV: Die Datenbank mit Filmen/Drehbüchern etc. liegt in diesem Repository und in Deinem TVT-Verzeichnis unter res/database/Default und hat eine ausführliche Dokumentation mit Startpunkt https://github.com/TVTower/Documentation/blob/master/database_de/main.md falls Du den Drehbuchvorschlag ausbauen und in die passende Form bringen möchtest; möglichst mit Variablen, damit man nicht immer "dasselbe" dreht).

**Comment by StukovTTV** [comment]
Vielen Dank, habe das mal probiert zu erstellen, derzeit noch ohne Variablen, mal schaun ob es im Spiel auftaucht :)

**Comment by nittka** [comment]
Vielleicht kann man die Anpassung "mathematisch einfach" halten. Randomisierungsparameter 0.2 heißt (bei einer Skala von 0  bis 1): der resultierende Wert kann um 0.2 vom Originalwert in beide Richtungen abweichen (liegt aber weiterhin zwischen 0 und 1). D.h. bei Ausgangswert von 0.5 zwischen 0.3 und 0.7, bei Ausgangswert von 1 zwischen 0.8 und 1.
Wenn man nämlich die mögliche Abweichung nach unten  kleiner macht, je näher der Wert an 1 ist, bedeutet das nur, dass schlechte Filme tendentiell nur schlechter werden und gute Filme tendentiell nur besser.

**Comment by nittka** [comment]
Vorschlag für die Randomisierung der Filmattribute bei Spielstart ist implementiert. Konfiguration über Dev.xml wäre möglich.
