### ISSUE TITLE
KI Falsche Ermittlung der Mindestzuschauerzahl

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#477]
Ich habe ein Problem, bei dem ich aktuell überhaupt nicht weiterkomme. Im angehängten Spielstand hat Spieler 3 aktuell eine Werbung, die nicht erfüllt ist. Selbst wann man den Schedule-Task explizit nochmal anstößt, wird die Werbung nicht erstetzt.
Die Werbung ist für Männer und 48000 schauen gerade zu. Bei der Prüfung des Werbevertrags wird aber 41000 Männer als Mindestzuschauerzahl zurückgegeben anstatt der 55000, die es tatsächlich sind. Daher wird auch auch nicht erkannt, dass die Werbung ausgetauscht werden müsste.

[quicksave.xml.zip](https://github.com/TVTower/TVTower/files/7675955/quicksave.xml.zip)

TaskSchedule um Zeile 1800 rum

**Comment by nittka** [comment]
Die Mindestzuschauerzahl eines Vertrags muss mit Parameter TVT.ME ermittelt werden. Nach dieser Änderung wurde im angehängten Spielstand die Werbung wie erwartet ersetzt.

**Comment by GWRon** [comment]
Ja - die KI sollte wohl alles "fix" setzen, wo default-Werte genutzt werden.

Method GetMinAudience:Int(playerID:Int=-1) {_exposeToLua}
Method GetTotalRawMinAudience:Int(playerID:Int=-1) {_exposeToLua}
...
All das wird eben NICHT als "-1" verstanden, wenn die KI "bla.GetMinAudience()" aufruft.

**Comment by nittka** [comment]
Jetzt müsste man nur die gesamte API im Kopf haben, um im lua-Code sofort zu sehen, wo das noch überall zuschlägt.

**Comment by GWRon** [comment]
Naja, prinzipiell waere es wohl "sinnstiftender", wenn die KI vorrangig die "TVT.***"-Methoden nutzt, und nicht die Methoden der Objekte ("contract.GetPrice()"). Dann waere fuer jede Abfrage "klar", was gemeint ist.

Oder aber aus:
```
	'returns the non rounded minimum audience
	Method GetTotalRawMinAudienceForPlayer:Int(playerID:Int)
		Return GetRawMinAudienceForPlayer(playerID, True)
	End Method


	Method GetTotalRawMinAudience:Int(playerID:Int=-1) {_exposeToLua}
		If playerID < 0 Then playerID = owner
		Return GetTotalRawMinAudienceForPlayer(playerID)
	End Method
```
wird
```
	'returns the non rounded minimum audience
	Method GetTotalRawMinAudienceForPlayer:Int(playerID:Int)
		Return GetRawMinAudienceForPlayer(playerID, True)
	End Method


	Method GetTotalRawMinAudienceForOwner:Int() {_exposeToLua}
		Return GetTotalRawMinAudienceForPlayer(owner)
	End Method
```

und der Lua/blitzmax-Code wird entsprechend angepasst.


Fuer solche "nur ein parameter"-Funktionen liesse sich evtl auch innerhalb der lua-blitzmax-Bindung was abfragen (lua_gettop -> schauen wieviele parameter aufm Stack sitzen, bei "0" wird der default genommen)

**Comment by GWRon** [comment]
Eventuell koennte ich auch LUA-Fehler ausspucken lassen, wenn eine Funktion aufgerufen wird (die Parameter erwartet - selbst wenn "defaults" definiert) aber Lua weniger Parameter uebergibt. Sprich Lua-Skripte muessten immer ALLE parameter explizit setzen.

**Comment by nittka** [comment]
Letzteres wäre doch in jedem Fall sinnvoll, oder? Gerade wenn die Defaults nicht verwendet werden.

**Comment by GWRon** [comment]
Bin schon dran - also dass es die Fehler in die Logs ausspuckt (Notify/throw war dann doch zu haeufig :D)

**Comment by GWRon** [comment]
```
[20:57:51] DBG      | TLUAENGINE: [Engine 1] LuaEngine._Invoke() - TPlayer.GetMoney() called with 0 params but 1 params required.
[20:57:51] DBG      |           : [Engine 1] LuaEngine._Invoke() - TPlayer.GetCredit() called with 0 params but 1 params required.
[20:57:52] DBG      | TLUAENGINE: [Engine 3] LuaEngine._Invoke() - TAdContract.GetTitle() called with 1 params but 0 params required.
[20:57:52] DBG      | TLUAENGINE: [Engine 2] LuaEngine._Invoke() - TAdContract.GetTitle() called with 1 params but 0 params required.
[20:57:53] DBG      | TLUAENGINE: [Engine 1] LuaEngine._Invoke() - TProgramme.GetBlocks() called with 0 params but 1 params required.
[20:57:53] DBG      |           : [Engine 3] LuaEngine._Invoke() - TNews.GetTitle() called with 1 params but 0 params required.
[20:57:53] DBG      | TLUAENGINE: [Engine 2] LuaEngine._Invoke() - TAdContract.GetMinAudience() called with 0 params but 1 params required.
[20:57:53] DBG      |           : [Engine 2] LuaEngine._Invoke() - TProgramme.GetAudienceAttraction() called with 4 params but 6 params required.
[20:57:54] DBG      |           : [Engine 3] LuaEngine._Invoke() - TAdvertisement.GetBlocks() called with 0 params but 1 params required.
[20:57:54] DBG      | TLUAENGINE: [Engine 1] LuaEngine._Invoke() - TAdvertisement.GetAudienceAttraction() called with 4 params but 6 params required.
[20:57:55] DBG      | TLUAENGINE: [Engine 1] LuaEngine._Invoke() - TLuaFunctions.of_GetBroadcastMaterialInProgrammePlanCount() called with 3 params but 5 params required.
[20:57:55] DBG      |           : [Engine 2] LuaEngine._Invoke() - TPlayer.GetProgrammeCollection() called with 1 params but 0 params required.
[20:57:55] DBG      |           : [Engine 2] LuaEngine._Invoke() - TPlayerProgrammeCollection.GetSuitcaseProgrammeLicenceCount() called with 1 params but 0 params required.
[20:57:55] DBG      |           : [Engine 2] LuaEngine._Invoke() - TPlayerProgrammeCollection.GetSuitcaseProgrammeLicencesArray() called with 1 params but 0 params required.
[20:57:55] DBG      |           : [Engine 2] LuaEngine._Invoke() - TProgrammeLicence.GetQuality() called with 1 params but 0 params required.
[20:57:55] DBG      |           : [Engine 2] LuaEngine._Invoke() - TProgrammeLicence.GetPrice() called with 2 params but 1 params required.
....
```
Aber mal schauen was ich da so an "Fehlalarmen" drin hab

**Comment by GWRon** [comment]
Puhhh... also das Problem ist:
TVT.GetTimeGoneInMinutes()
vs
TVT:GetTimeGoneInMinutes()
(Punkt vs Doppelpunkt)

In Lua ist der "Doppelpunkt" (colon) das Anzeichen fuer "Methode", der einfache "Punkt" die "Funktion". Der Unterschied liegt darin, dass bei der "Methode" noch als erster Parameter die Instanz mitgegeben wird (also ganz klassisch).

Im C/BlitzMax-code ist aber nicht herausfindbar, wie nun wirklich aufgerufen worden ist. Wenn also eine BlitzMaxmethode `GetMoney(playerID:int)` waere, und im Lua per `TVT:GetMoney()` aufgerufen werden koennte, dann wuerde "TVT" wohl als erster Parameter uebergeben werden - und in BlitzMax steht da dann "1 Parameter erwartet, 1 bekommen ... OK"
Wenn nun aber eine Blitzmax Methode keinen Parameter haette, waere es "0 erwartet, 1 bekommen ... FAIL". Wenn man nun als `TVT.GetMoney()` aufriefe, wuerde das Fehlen des Parameters auffallen.

Weiss nur nicht, wie man "erzwingen" kann, dass bestimmte Konstellationen genutzt werden.

**Comment by GWRon** [comment]
oeffne base.util.luaengine.bmx und fuege bei der "Method _invoke" einen kleinen Check ein:

```
	Method _Invoke:Int()
		Local obj:Object = lua_unboxobject(getLuaState(), LUA_GLOBALSINDEX - 1)
		Local funcOrMeth:TMember = TMember(lua_tolightobject(getLuaState(), LUA_GLOBALSINDEX - 2))
		If Not TFunction(funcOrMeth) And Not TMethod(funcOrMeth) Then Throw "LuaEngine._Invoke() failed. No function/method given."
		If Not obj Then Print "LuaEngine._Invoke() failed to run ~q"+funcOrMeth.name()+"~q. Invalid parent given."
		Local func:TFunction = TFunction(funcOrMeth)
		Local mth:TMethod = TMethod(funcOrMeth)
		Local tys:TTypeId[]

		If func Then tys = func.ArgTypes()
		If mth Then tys = mth.ArgTypes()
		Local args:Object[tys.length]

		
		Local passedArgumentCount:Int = lua_gettop(getluaState())
		'for methods the instance is the first on the stack
		if mth then passedArgumentCount :- 1

		If args.length <> passedArgumentCount
			TLogger.Log("TLuaEngine", "[Engine " + id + "] LuaEngine._Invoke() - "+TTypeID.ForObject(obj).name()+"."+funcOrMeth.name()+"() called with " + passedArgumentCount+" params but " + args.length +" params required. Invoke method with ~q:~q not ~q.~q.", LOG_DEBUG)
			'Notify("TLuaEngine [Engine " + id + "] LuaEngine._Invoke() - "+funcOrMeth.name()+"() called with " + passedArgumentCount+" params but " + args.length +" params required.")
'			Return False
		EndIf
```

Dann muesste jede der gemeldeten Methoden im Lua-Code ueberprueft werden (ob Aufruf als Methode oder Funktion - bzw ob Defaultparameter)

**Comment by GWRon** [comment]
Ich wuerde das wohl alles mal durchgehen (falls Du das nicht machen moechtest):
- jetzt (aber dazu brauch ich entweder die Freigabe den originalen KI-Code anzufassen - da sicher Mergekonflikte drohen)
- spaeter (wenn deine Basisaenderung drin ist - dafuer aber vielleicht mit Code der gar nicht haette angepasst werden muessen)

**Comment by GWRon** [comment]
```Blitzmax
	Method methodTest(a:int = -1, b:String="Hello")
		Print "METHOD TEST a="+a+" b="+b
	End Method

	Function functionTest(a:int = -2, b:String="World")
		Print "FUNCTION TEST a="+a+" b="+b
	End Function
```

Aufruf von jeweils als function, function+1param, function+2params, method, method+1param, method+2params
```Lua
	TVT.functionTest()
	TVT.functionTest(1234)
	TVT.functionTest(-100, "Welt")
	TVT:functionTest()
	TVT:functionTest(1234)
	TVT:functionTest(-100, "Welt")
	TVT.methodTest()
	TVT.methodTest(1234)
	TVT.methodTest(-100, "Hallo")
	TVT:methodTest()
	TVT:methodTest(1234)
	TVT:methodTest(-100, "Hallo")

```

Ergebnis (gegenuebergestellt:
```
TVT.functionTest()                  a=0 b=
TVT.functionTest(1234)              a=1234 b=
TVT.functionTest(-100, "Welt")      a=-100 b=Welt
TVT:functionTest()                  a=0 b=
TVT:functionTest(1234)              a=0 b=1234
TVT:functionTest(-100, "Welt")      a=0 b=-100
TVT.methodTest()                    a=0 b=
TVT.methodTest(1234)                a=1234 b=
TVT.methodTest(-100, "Hallo")       a=-100 b=Hallo
TVT:methodTest()                    a=0 b=
TVT:methodTest(1234)                a=0 b=1234
TVT:methodTest(-100, "Hallo")       a=0 b=-100

```
Wie Du siehst, kommt es hier zu Verschiebungen, sobald etwas als Methode aufgerufen wird. Wir muessen also alles per "." aufrufen und nicht per ":".
Da wir nicht per reflection abrufen koennen, ob ein funktions/method-parameter in Blitzmax einen Defaultwert hat, nuetzt uns `lual_optstring()` (etc.) nix. Also koennen nur eine Log-Ausgabe fuer "Parameter gegeben <> Parameter gebraucht"  einbauen und dann entsprechend alle Codestellen ueberpruefen.

**Comment by nittka** [comment]
> Ich wuerde das wohl alles mal durchgehen (falls Du das nicht machen moechtest):
> 
>     * jetzt (aber dazu brauch ich entweder die Freigabe den originalen KI-Code anzufassen - da sicher Mergekonflikte drohen)
> 
>     * spaeter (wenn deine Basisaenderung drin ist - dafuer aber vielleicht mit Code der gar nicht haette angepasst werden muessen)

Ich bin für Variante 2: Review/Testspiel der ersten KI-Anpassungen, dann aufräumen, dann weiter an der KI arbeiten. Ich habe gerade einen sauberen Stand (PR) ohne weitere Änderungen auf der Werkbank und würde in der Zwischenzeit nichts weiter an der KI machen.

**Comment by GWRon** [comment]
Ich habe heute ein wenig herumgeschrieben und probiert. Ganz perfekt bekomme ich die Methoden/Funktions-Call-Erkennung von seitens Lua nicht hin.
Was derzeit als "ambiguous" abgewiegelt wird, ist eine BlitzMax Methode die ihr Elternelement als ersten Parameter erlauben wuerde.

```Blitzmax
Type TTest
  Method PassMe(t:TTest = Null)
  End Method
End Type
```

hier wird in BlitzMax nicht ersichtlich, was da genau in Lua passiert, wenn man in Lua schreibt:
```
Test.PassMe() --als Funktion, also ohne "self" als erster Param
Test:PassMe() --als Methode, "Test" wuerde an PassMe als erster Parameter weitergegeben
```

Weiterhin habe ich den Code so umgestellt, dass immer alle Parameter angegeben werden muessen. Wir koennen keine "defaults" nutzen (also Parameter weglassen). Reflection in BlitzMax kann das eh nicht, man wuerde also da sonst immer "Null" bzw "0" uebergeben, was ja durchaus doch eine Bedeutung haben kann.

Entsprechend kommt es mit den Aenderungen erstmal zu weiteren Logeintraegen (error bzw debug) - oder, wenn Rueckgabewerte nicht auf "nil" geprueft werden, zu segfaults/lua-Fehlern.


Code waere in https://github.com/TVTower/TVTower/pull/479
um trotz fehlerhafter Argumente "weiterzumachen" (dann hat man die Logs, aber nicht gleich Abstuerze) einfach in Zeile 881 den If anpassen.
```
		'stop execution if an argument did not fit
		if invalidArgs > 0
			TLogger.Log("TLuaEngine", "[Engine " + id + "] _Invoke() failed to call ~q" + TTypeID.ForObject(obj).name() + "." + funcOrMeth.name() + "()~q. " + invalidArgs + " invalid argument(s) passed.", LOG_ERROR)
			Return False
		EndIf
```

**Comment by nittka** [comment]
Ist im KI-Branch behoben.
