### ISSUE TITLE
Spielerbankrott

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#483]
Geht ein Spieler bankrott, muss er zunächst aus dem Raum geworfen werden, ansonsten ist der Raum weiter blockiert und kann von den KI-Spielern nicht betreten werden.

**Comment by nittka** [comment]
Der Code zum Verlassen des Raums im Falle eines Bankrotts ist schon vorhanden, funktioniert aber scheinbar nicht wie erwartet. Der Fehler kann nachgestellt werden, wenn man unmittelbar bei Spielstart wartet, bis die erste KI die Filmagentur betreten hat und diesen Spieler dann bankrott setzt.
Die alte KI verlässt das Gebäude, die neue kommt. Die Filmagentur kann prinzipiell betreten werden, aber der Status ist so, dass einer oder mehrere KI-Spieler ewig vor der Agentur warten oder in einem Raum sind und sich nicht bewegen können (Debug - cannot move)

**Comment by nittka** [comment]
In diesem Zusammenhang könnte auch geändert werden, dass die KI-Spiler vor einem Raum warten, bis sie zum nächsten Ziel gehen. Dann blockieren sie diesen nicht für andere (sowas sollte Teil einer Spielstrategie sein und nicht Teil der Spielmechanik). Auch kann man argumentieren, dass das Warten am Start ungünstig ist, wenn man vor dem Ziel wartet ist man zumindest schon da...

**Comment by GWRon** [comment]
Kannst Du mal schauen, ob der Bug noch relevant ist?
Eventuell hat der Fix (nicht mehr alle Spieler-KIs im Falle eines Bankrotts zu stoppen) das schon behoben - denn ich bekomme es hier nicht nachgestellt (die anderen Spieler sind alle artig nach dem Bankrott zum Filmhaendler rein und haben dort gewerkelt)

**Comment by nittka** [comment]
Ist behoben.
