### ISSUE TITLE
KI Verkauf von Filmen geht nicht

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#487]
Wie in #478 beschrieben, funktioniert der Sell-Job im MovieDistributor-Task nicht. Selbst wenn im Archiv eine Lizenz in den Koffer gelegt wird, ist diese beim Filmhändler dann verschwunden.
In meinem Test hatte ich die API für's holen analog zum Holen der Filme erweitert. Das Array hat dann auch einen Eintrag enthalten, angekommen im Lua-Code war das Ergebnis dann aber leer... (Nicht mit zwei zu verkaufenden Filmen getestet, denn das ist ein echter Unterschied.)

**Comment by GWRon** [comment]
Der Fehler ist einfach ... und zwar verlaesst die Spielfigur den Raum "forcefully" (um zum Filmhaendler zu gehen).

Beim erzwungenen Verlassen kommt "game.roomhandler.archive.bmx" : "onForcefullyLeaveRoom" zum tragen:
```
	'called as soon as a players figure is forced to leave the room
	Method onForcefullyLeaveRoom:int( triggerEvent:TEventBase )
		if not super.onForcefullyLeaveRoom(triggerEvent) then return False

		local figure:TFigure = TFigure(triggerEvent.GetSender())
		if not IsRoomOwner(figure, TRoom(triggerEvent.GetReceiver())) then return False

		'=== FOR ALL PLAYERS ===
		'
		print "room owner forcefully leaves archive: roomID="+TRoom(triggerEvent.GetReceiver()).id+"  figure="+figure.name

		'instead of leaving the room and accidentially removing programmes
		'from the plan we readd all licences from the suitcase back to
		'the players collection
		GetPlayerProgrammeCollection( figure.playerID ).ReaddProgrammeLicencesFromSuitcase()
```

Und siehe da - in diesem Fall werden alle Programmlizenzen vom Koffer wieder zurueckgelegt.

**Comment by nittka** [comment]
Der Fix ist im Branch für die Filme integriert.
