### ISSUE TITLE
Spielgeschwindigkeit vs Laufgeschwindigkeit

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#490]
@nittka - Du hattest ja letztens die Spielgeschwindigkeiten "vereinheitlicht".

Die Trennung war damals (bei Mad TV) so, da (zumindest bin ich der Meinung) die "Hochhauszeit" (also Laufgeschwindigkeit usw) nicht direkt an die "Uhrzeit" im Interface gekoppelt war.
Anders ausgedrueckt: Bei Spielgeschwindigkeit "schnell" hatte man weniger Zeit, die Raeume zu erreichen, da man immer "gleich schnell" lief - nur die Uhr tickte schneller.

Bei uns muesste man - wenn man das auch umsetzen woellte - die Sache trennen zwischen:
* unten die drei  Buttons ("Schnellere Uhr bei gleichbleibender Laufgeschwindigkeit")
* "Vorspulen" (das wuerde die gegebene "Uhrgeschwindigkeit-Laufgeschwindigkeit" jeweils erhoehen - um das Verhalten "Uhr-Laufen" konstant zu halten)

Derzeit ist es so, dass Spielstufe "schnell" irgendwie unnatuerlich schnell aussieht (die "flitzen" halt herum, statt zu "wuseln"). Ich verstehe aber auch den originaeren Ansatz von Dir (die Dinge "konstant zueinander" zu halten)

**Comment by nittka** [comment]
Tatsächlich sollte es bei den drei Geschwindigkeitsstufen schon so sein, dass die Laufgeschwindigkeit vergleichsweise weniger stark ansteigt. Und eigentlich war meine Intention auch, dass sich bei den Presets gar nichts ändert - nur beim Vorspulen sollte eine "Flitzgeschwindigkeit" verwendet werden, damit die KI nicht benachteiligt wird.

(Siehe History von Method SetGameSpeedPreset). Dort wird der boolean übergeben der dafür sorgen soll, dass genau dieselben Werte wie vor der Änderung verwendet werden. Auf die Schnelle kann ich mir nicht erklären, warum das nicht funktioniert.

**Comment by GWRon** [comment]
Flitzgeschwindigkeit kommt schon fast an "Mopsgeschwindigkeit" heran :)

**Comment by GWRon** [comment]
Derzeit wird auch per "cursor rechts/links" die Geschwindigkeit um "+- 10" geaendert. Das ist nach den Aenderungen jetzt durchaus... ein wenig "viel". Nun reicht ein kurzes Antippen von "links" um die Spielgeschwindigkeit auf 0 zu setzen.

Entweder man macht das "progressiv" oder "linear":
- linear: nur noch Aenderung um "1"
- progressiv: Zeit von `KeyManager.GetDownTime(KEY_LEFT)` abgreifen und die Aenderung an das gehaltene Anpassen (mit Obergrenze natuerlich), laenger gedrueckt = groessere Schritte

**Comment by nittka** [comment]
Das mit den Pfeiltasten betrifft die "Dev-Version". Wenn die Dev-Keys deaktiviert wären (Wunsch für's nächste Release), würde nur noch das Vorspulen während man drückt gehen.
Bei mir kompiliert der Master nicht. Die im Debug-Screen anzuzeigende _profilerKey_AI_MINUTE-Variable wird nicht gefunden.

**Comment by GWRon** [comment]
achso ja, wollte die main.bmx-Aenderung nicht uebernehmen :D ... committe gleich

**Comment by nittka** [comment]
Ich habe die Geschwindigkeit gerade nochmal in der 0.7.1 angeschaut - da hat sich nichts verändert (sollte also schon seit einiger Zeit so sein)... In Stufe 3 rasen die Spieler auch dort schon durch die Gänge.
Soll das Thema dennoch angegangen werden oder ist das ein Won't Fix?

**Comment by GWRon** [comment]
Hmm ... also wir sollten es zumindest irgendwie ausdiskutieren - bzw uns da einfach an Mad TV orientieren.
