### ISSUE TITLE
Bei AI-Spielerbankrott AI-Event-Count immer höher

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#492]
Setze einen AI-Spieler Bankrott - die AIEvents steigen und steigen
![image](https://user-images.githubusercontent.com/2625226/146683431-1e44cfb3-1444-4a68-929c-6ea8b997c18e.png)

Das sorgt natuerlich fuer ... Probleme.

**Comment by nittka** [comment]
Werden der alten KI vielleicht noch Events geschickt?

**Comment by GWRon** [comment]
Ich hab noch nicht weiter geguckt ... Abendessen vorbereiten etc.

**Comment by nittka** [comment]
Ich entwickle an einem langsameren Rechner, daher kommte es schon etwas früher zu Performance-Engpässen. Bei mir gehen auch bei niedrigen Vorspulgeschwindigkeiten die Eventzahlen für onMinute und onRealTimeSecond stark in die Höhe.
In der aktuellen KI-Implementierung werden diese Events gar nicht mehr benötigt. Daher wäre ich dafür, sie nicht mehr an die KI weiterzuleiten (insb. onMinute). Das reduziert die Last enorm und würde die höheren Vorspulgeschwindigkeiten überhaupt erst ermöglichen.

**Comment by GWRon** [comment]
Du brauchst ja nur in den events...nix zu machen.

Es obliegt der KI ja, die zu ignorieren.

**Comment by GWRon** [comment]
Also ich habe jetzt eigentlich ... einen anderen "Bug" behoben - und im Nachhinein gesehen, dass der wohl auch der Grund fuer das hier war ...

Ich bin eigentlich nur drueber gestolpert, dass beim Bankrottsetzen irgendwie alle KI-Spieler eine "Stopping AI..."-Nachricht hatten. Und tatsaechlich, da hab ich wohl in einer Schleife nicht nur die KI informiert, sondern jeweils noch gestoppt.

Entsprechend war klar - dass die durch das Stoppen die Events nicht mehr abgearbeitet hatten und es sich dort ansammelte.
Ich weiss jetzt nur nicht, ob man einer gestoppten KI keine Events mehr zustellen sollte - oder ob man die weiterhin "aufhebt", so dass eine dann fortgesetzte KI die nachholen koennte.
Ich wuerde wohl die Event-Zustellung erstmal deaktivieren, wenn "deactivated" / gestoppt.

**Comment by GWRon** [comment]
Der "bug" klingt jetzt an sich trivial - aber hatte enorme Auswirkungen - denn es bedeutete, dass mit dem Bankrott eines KI-Spielers die anderen lahmgelegt wurden, bis man speicherte und einlud (laden = starten der KI)

**Comment by nittka** [comment]
Bzgl. nichts machen: vielleicht liegt das Problem tatsächlich nicht in den Events an sich (d.h. sie haben sich aus einem anderen Grund angesammelt; siehe weiter unten). Mir ist nur nicht klar, wieviel Overhead ein Aufruf verursacht, der dann potentiell nie was machen wird.

Kurz zur aktuellen Beobachtung. Bei mir blockiert die KI bei hohen Geschwindigkeiten (ca 1000). Was ich nun gemacht habe, ist den AdAgency-Task komplett leer zu machen. D.h. getNextJobInRoom ruft sofort done auf. Dennoch bleibt die KI z.T. mehrere Sekunden im Raum. Aktuell hat es den Anschein, als würde die Prüfung, in welchem Raum sich der Spieler befindet nicht 100%ig funktionieren und immer noch den Raum betreten wollen, anstatt loszuarbeiten... Es sollte sich um ein Engine-Problem handeln, denn ähnliche lange Wartezeiten gibt es auch im Büro/Nachrichtenagentur/Archiv/Filmhändler/Roomboard; aber eben nicht immr.

**Comment by GWRon** [comment]
Hmm
```Lua
function TaskAdAgency:GetNextJobInTargetRoom()
	self:SetDone()
	return nil
--[[

	if (MY.GetProgrammeCollection().GetAdContractCount() >= 8) then
		self:SetDone()
		return nil
	elseif (self.CheckSpots.Status ~= JOB_STATUS_DONE) then
		return self.CheckSpots
	elseif (self.AppraiseSpots.Status ~= JOB_STATUS_DONE) then
		return self.AppraiseSpots
	elseif (self.SignRequisitedContracts.Status ~= JOB_STATUS_DONE) then
		return self.SignRequisitedContracts
	elseif (self.SignContracts.Status ~= JOB_STATUS_DONE) then
		return self.SignContracts

	elseif (self.IdleJob.Status ~= JOB_STATUS_DONE) then
		return self.IdleJob
	end

--	self:SetWait()
	self:SetDone()
]]--
end
```
Spieler geht rein ... 100ms spaeter geht er wieder raus.

**Comment by GWRon** [comment]
Vielleicht ... hast Du hier Deine Wartezeit:
AIEngine.lua: 
```
function AIPlayer:TickProcessTask()
	-- start new tasks or continue the current
	if (self.CurrentTask == nil)  then
		self:BeginNewTask()
	else
		if self.CurrentTask.Status == TASK_STATUS_DONE or self.CurrentTask.Status == TASK_STATUS_CANCEL then
			-- wait until the NEXT task has a priority > 35 (idle a bit)
			local tasksPrioOrdered = SortTasksByPrio(self.TaskList)
			local nextTask = tasksPrioOrdered[1] -- 0 = current, 1 = next
			if nextTask ~= nil and nextTask.CurrentPriority > 35 then
				self:BeginNewTask()
			end
...
```
Wenn da noch noch kein anderer Task eine hohe Prio hat ... wartet er. Denke hier sollte der Raum verlassen werden...

**Comment by GWRon** [comment]
Ich habe mal noch in "master" eingefuegt, dass nun geloggt wird, wie lange eine Spielerfigur in einem Raum war.

(adagency task noch auf sofort-"done")

Normalgeschwindigkeit:
```
[10:04:36] DBG      |        : AI 1 left room "Agentur fuer Werbung" [roombase-adagency-0] after 2683 ms (core time: 988ms)
[10:04:53] DBG      | TPLAYER: AI 4 left room "Film-Agentur" [roombase-movieagency-0] after 7683 ms (core time: 5996ms)
[10:05:03] DBG      | TPLAYER: AI 3 left room "Film-Agentur" [roombase-movieagency-0] after 9350 ms (core time: 7653ms)
```

Vorspulen (strg + rechts):
```
[10:07:17] DBG      | TPLAYER: AI 1 left room "Agentur fuer Werbung" [roombase-adagency-0] after 217 ms (core time: 188ms)
[10:07:18] DBG      | TPLAYER: AI 4 left room "Film-Agentur" [roombase-movieagency-0] after 566 ms (core time: 534ms)
[10:07:19] DBG      | TPLAYER: AI 1 left room "Film-Agentur" [roombase-movieagency-0] after 884 ms (core time: 856ms)
```

Man sieht, dass die "Betreten/Verlassen" Zeit korrekt beschleunigt wird, und auch das "denken" findet schneller statt - allerdings dauert es immer noch eine gewisse Zeit.

Vielleicht hilft Dir das aber schon, um Optimierungen "abschaetzen" zu koennen.

**Comment by nittka** [comment]
Ich habe einen potentiellen Übeltäter gefunden, bevor ich diese neue Funktion gesehen habe - AIJobGoToRoom:Tick

Wenn die KI nicht wartet, aber der Job noch nicht abgeschlossen ist, geht die Methode davon aus, dass der Raum noch nicht erreicht wurde, da das OnEnterRoom-Event noch nicht kam. Wenn ich mir an dieser Stelle aber den aktuellen Raum ausgeben lasse, bekomme ich Tonnenweise Meldungen, dass ich doch schon im Raum bin.
Hypothese: bei mir bekommt die KI bei hoher Geschwindigkeit so viele Tick-Events, die erst abgearbeitet werden müssen, dass das OnEnterRoom-Event sehr lange untergeht.

* zu prüfen: sind die AIEvents als FiFo oder LiFo implementiert
* sollten die AIEvents aufgeteilt werden (Hochpriorisierte Events, ConditionalTicks), so dass erst die Prio-Events feuern

Wenn ich in AIJobGoToRoom:Tick selbst nochmal den Raum prüfe und die OnEnter-Methode selbst aufrufe, kommt es nicht mehr zu Blockaden!
Die Eventschlange füllt sich trotzdem mit haufenweise ConditionalTicks. Möglicherweise sollte man einfach die Anzahl der ConditionalTicks beschränken. Wenn sie nicht abgeholt werden, will die KI halt nichts machen. Wenn sie abgeholt werden, bekommt die KI sie auch in der aktuellen Rate weiter zur Verfügung gestellt.

**Comment by GWRon** [comment]
AIEvents sind FiFo,

"Ticks" koennte man aufteilen ... die sind ja dazu da, die KI auch im Falle von "nix passiert" zu triggern - bzw damit sie Arbeiten in "Teilen" erledigen kann (um "Spielerverhalten" zu simulieren ... einen Film angucken, ... den naechsten Film ueberpruefen ... und noch einen ...)

Diese Ticks muessen nicht mit "Arbeit" abgeholt werden, die koennen auch einfach nur "gefressen" werden (nix tun). In dem Moment wo Arbeit in "Teilen" passiert ("steps"), wuerde ohne die Ticks die Arbeit nicht beendet werden koennen.
Das weglassen geht da nur, wenn die KI das auch "kann", also Aufgaben anderweitig fertigstellt - oder "in einem Rutsch" die Arbeit erledigt (was dann aber "nicht-menschliches" Verhalten waere).
Das Vorgehen war damals auch notwendig, da die KI viel Rechenzeit brauchte - und ohne Threading blockierte dies dann die Hauptschleife (es "ruckelte")


Das Hauptproblem bleibt fuer mich: Warum dauert das "abarbeiten" der Ticks (bei dir?) zu lange, was laesst sich da verbessern?

**Comment by GWRon** [comment]
Du koenntest ueberlegen, von den "Conditional Ticks" abzukommen. Du koenntest fuer jede KI ein field "manualTriggerAtTime:Long" einfuehren und die KI kann dann diesen Wert selbsstaendig setzen (`SetTriggerAtTime(x)` bzw `SetTriggerAgainInTime(timeTillTrigger)`).

Dann kann die KI selbsstaendig bestimmen, wann sie wieder "geweckt" werden will (zusaetzlich zu besonderen Events).

Aber wie gesagt - Hauptproblem ist denke ich, die Zeiten der "ticks" etc runterzubekommen.

**Comment by nittka** [comment]
Es kann sein, dass der Rechner einfach vergleichsweise langsam ist!
* Aktuell ruckelt mein Stand auch schon in der ersten Preset-Geschwindigkeit. Da muss ich noch prüfen, ob das an meinen Anpassungen zur KI liegt.
* Der Blitzmax-Code bekommt doch mit, ob ein Tick-Event abgeholt wurde, oder? Insofern wäre es doch unproblematisch keine neuen Ticks zu schicken. Das Flooding-Problem bekommt man potentiell bei jeder Tick-Verarbeitungszeit, da man die Spielgeschwindigkeit ja immer weiter erhöhen kann und damit immer mehr "onMinute-Conditional-Ticks" erzeugt werden.

**Comment by GWRon** [comment]
Die KI versucht die komplette Queue abzuarbeiten

```
	Method CallUpdate()
		if GetNextEventCount() = 0
			delay(1)
			return
		endif

		Local nextEvent:TAIEvent = PopNextEvent()
		While nextEvent
			HandleAIEvent(nextEvent)
			nextEvent = PopNextEvent()
		Wend
	End Method
```

Das heisst, pro "Rutsch" sollte alles abgearbeitet werden (parallel koennten aber schon neue hinten "rangehangen" werden).

Klar kann man nun sagen "nur ein ConditionalTick" darf in der Queue sein ... aber dann kannst du in der KI nix schreiben, was in 5 Teilschritte unterteilt wurde - und pro "tick" einer dieser Schritte abgearbeitet wird (bspweise der ProgrammeScheduler).

**Comment by GWRon** [comment]
> * Aktuell ruckelt mein Stand auch schon in der ersten Preset-Geschwindigkeit. Da muss ich noch prüfen, ob das an meinen Anpassungen zur KI liegt.

Hmm, da musst Du mir mal sagen, was Du da alles brauchst um Dinge einzuschraenken.

**Comment by nittka** [comment]
Ich denke, das Problem liegt in meinen Anpssungen für die KI-Verbesserungen. Da hatte ich nämlich brainSpeed auf 1000 gesetzt, damit die Ki nicht ewig einen Raum blockiert. Dadurch werden pro Tick-Aufruf natürlich 1000 Ticks abgearbeitet...
Das werde ich mal zurücknehmen und schauen, wie sich das ganze dann verhält. Natürlich ist Brainspeed zwischen 2 und 4 schon "gemein", wenn eine KI nur halb so schnell ist wie eine andere. 5 bis 7 erscheint ausgewogener.

Zum Thema "nichtmenschliches Verhalten" wenn alles in einem Rutsch abgearbeitet wird. Man darf dabei aber nicht vergessen, dass der menschliche Spieler die Raumgeschwindigkeit stark runtersetzen kann - beim Vorspulen kann die KI das nicht.
Am Ende ließe sich das auch simulieren - die eigentliche Verarbeitung wird in einem Tick gemacht und dann muss die KI eine gewisse Anzahl Spielminuten warten, bis sie das nächste Thema angeht (mit demselben Unfairness-Problem Raumgeschwindigkeit).

Ich glaube, mein Problem ist erstmal behoben. Potentielle Optimierung kann dann komplett separat behandelt werden.

**Comment by GWRon** [comment]
Habe jetzt trotzdem die KI so erweitert, dass sie selbst "OnTick" anstupsen kann (also in die event-queue anhaengt).

Exemplarisch geschieht dies nun im Skript, wenn ein Raum "fertig" betreten ist. Anstatt nun auf den naechsten Tick zu warten (also nach 1 Echtsekunde, oder 1 Spielminute), faengt sie nun direkt mit der Aufgabe an ... 

Dadurch verkuerzt sich die "Leerlaufzeit" der AdAgency-Task (wenn sofort "setdone") auf ca 90ms im Raum bei Normalgeschwindigkeit (+1800ms fuer "rein/raus").

Kannst Du aber gern wieder rausnehmen (die `ScheduleNextOnTick()` im Lua-Skript)
