### ISSUE TITLE
(Bug) KI: Was tun, wenn nichts zu tun?

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#493]
Derzeit gammelt die KI herum, wenn noch keine andere Aufgabe eine "genuegend hohe" Prio hat.

```Lua
function AIPlayer:TickProcessTask()
	-- start new tasks or continue the current
	if (self.CurrentTask == nil)  then
		self:BeginNewTask()
	else
		if self.CurrentTask.Status == TASK_STATUS_DONE or self.CurrentTask.Status == TASK_STATUS_CANCEL then
			-- wait until the NEXT task has a priority > 35 (idle a bit)
			local tasksPrioOrdered = SortTasksByPrio(self.TaskList)
			local nextTask = tasksPrioOrdered[1] -- 0 = current, 1 = next
			if nextTask ~= nil and nextTask.CurrentPriority > 35 then
				self:BeginNewTask()
			end
		else
			local nowTime = os.clock()
			self.CurrentTask:Tick()
			self.CurrentTask.TicksTotalTime = self.CurrentTask.TicksTotalTime + (os.clock() - nowTime)
		end
	end
end
```
~~Das sorgt dafuer, dass eine Figur auch mal einen Raum blockiert - naemlich für den gesamten Zeitraum "keine Prio hoch genug"~~
Edit:  noe, passiert nicht, da "Task:SetDone()" schon den Raum verlaesst

Meine Vorschlaege:
- nix tun erlaubt, wenn man im eigenenBuero ist (...ist ja der eigene "Arbeitsort")
- ~~andere Raeume in jedem Fall verlassen~~
- zum eigenen Buero schicken??
- Edit: Man koennte den "Priowert" auch Tick fuer Tick nach unten setzen ... die Person bekommt also "Hummeln im Hintern" (will was machen). Dieser Wert koennte sogar AI-individuell ("Charakter") sein.

Wenn wir nun den Figuren noch ein "herumgammeln" mitgeben (Zufallsziele oder zum Buero) haette das Auswirkungen auf die Fahrstuhlauslastung ... muesste man bedenken.

Edit: Habe "Task:SetDone()" nicht durchgeguckt - da werden Raeume schon verlassen. Entsprechend ist der Issue hier .. doch weniger Bugreport als gedacht

**Comment by nittka** [comment]
Über dieses Thema würde ich mir erst Gedanken machen, wenn alle Tasks implementiert sind. Aktuell kümmert sich die KI noch nicht um Eigenproduktionen oder Betty.

**Comment by nittka** [comment]
Ich habe natürlich noch viele Ideen, was die KI angeht. Die aktuelle Taskauswahl basiert ja darauf, dass im Laufe der Zeit Prio-Punkte angesammelt werden. Das funktioniert ganz gut im dem Sinne, dass jeder mal drankommt. Aber wie bei der Budgetverteilung, kümmert sich jeder Task nur um sich selbst und versucht sich durch höhere Werte in den Vordergrund zu rücken. Eine Auswertung der Gesamtsituation findet nicht statt.

Langfristig wäre mein Ziel, dass es einen Strategie-Task gibt, der einen Gesamtüberblick hat und dann die nächsten Tasks und die Budgetverteilung zentral übernimmt. Denn auch die einmalig festgelegten Werte für Brainspeed und Schwellwert für Aktivität benachteiligen den Spieler mit schlechten Werten dauerhaft. Der Strategietask könnte feststellen, dass das Programm gut gesetzt, genügend Werbung vorhanden und zu wenig Geld für Einkäufe da ist (oder ich war erst vor 30 Minuten bei der Filmagentur, da lohnt es sich jetzt noch nicht wieder). Dann sagt er einfach "Warten bis Zeit x" zur nächsten Analyse der Situation.

Das grundsätzliches Thema ist also noch offen, die Frage aber beantwortet. Ich mache das Ticket mal zu. Für weitere KI-Anpassungen gibt es dann spezifische Tickets oder PRs.
