### ISSUE TITLE
Persistence: Absturz beim Speichern

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#494]
Ich wollte gerade den KI-Branch Test abspeichern (glaube Tag 48, ueber Nacht bei Spielgeschwindigkeit 200 laufen lassen) als mich eine Exception einholte:

![image](https://user-images.githubusercontent.com/2625226/146887334-1b5eb48f-0c67-42ae-88cc-af3477001ccc.png)

```
	Method ToString:String()
		Return "Persist Collision. Matching ref '" + ref + "' for different objects"
	End Method
```

Aufgetreten scheinbar bei der Serialisierung einer Person:
![image](https://user-images.githubusercontent.com/2625226/146886935-fc1a5112-ca5f-4870-bf95-40864c7859a8.png)

![image](https://user-images.githubusercontent.com/2625226/146887037-f8c370d4-fc86-4559-af83-158573186f9b.png)

Ich vermute, dass es zu viele Objekte gab ... und wir da an ein Limit fuer die "Keys" der Persistence kamen ... oder Aehnliches.

**Comment by nittka** [comment]
Wenn Du das Spiel über Nacht anlässt, würde ich den AI-Game-Modus empfehlen (tägliches Zwischenspeichern). Die Geschwindigkeit kannst Du ja in der Debug-Klasse anpassen. Interessant ist dann nämlich auch die Entwicklung der Spielstandgrößen. Und im Falle einer Exception kann man ab dem letzten Tag weiterspielen.

**Comment by GWRon** [comment]
Den Fehler wurde schon gefunden (@davecamp war so nett und hat mir per discord gleich die fehlerhafte Zeile identifziert).

Wenn man einen "long" in Blitzmax (Quellcode) explizit ("numerisch") angibt, muss man den Typ anhaengen, da sonst von einem "int" ausgegangen wird (genau so, wie bei "double" von einem "float" ausgegangen wird):

Local l:long = 12345678901234:long
Local d:double = 1.000001:double

und dort im Serializer fehlte die entsprechende Kennzeichnung

**Comment by nittka** [comment]
Bleibt das Laden alter Speicherstände trotzdem unproblematisch?

**Comment by GWRon** [comment]
Ja ... es haette sonst beim Speichern schon gemeckert.

Der Fehler war, dass die ersten 8 Byte eines Longs (also 32 bit der 64bit insgesamt) ignoriert wurden - und somit den gleichen Schluessel ergaben

```BlitzMax
print "first: " + TPersist.Base36($000000000182c980:long)
print "second:" + TPersist.Base36($00007f7b0182c980:long)
```
da wurde nur der Teil ab "0182..." herangezogen. Ich hatte den Fehler noch nie - sprich ich hatte noch nicht den Fall, dass TVTower-Objekte im Speicher die letzten 8 Bytes "gemeinsam" hatten.

**Comment by nittka** [comment]
Mit dem letzten Commit sollte das Ticket doch gelöst sein, oder?

**Comment by GWRon** [comment]
Ja.
