### ISSUE TITLE
KI Filmkauf

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#501]
* nicht immer kaufen, wenn Geld da ist (ggf. länger warten und bei mehr Geld noch was besseres oder 2 Sachen holen)
* bei Auktionen scheint derzeit gar nicht geboten zu werden
* Genre in Kaufentscheidung einbeziehen
* Kauf (Requisition), wenn bestimmte Werbung geschafft werden muss
* Investitionsbudget auch bei Filmkauf verwenden
* Verkauf schlechter Filme (schon früher, um Qualität zu steigern)

Im Zusammenhang mit Strategiewechsel (Senderausbau/Fundusverbesserung):
* Minimalanzahl Filme bis Start Senderausbau
* Minimalanzahl Filme bis Senderausbau oberhalb von 5 Mio (danach ist Fundusausbau schwer, da die Filme sehr teuer werden)
* danach weitere, einzelne Verbesserungen (Verkauf schlechter Filme), Nachkauf von "Schnäppchen"

**Comment by nittka** [comment]
Die obigen Punkte sind noch nicht wirklich angegangen. Was aber schon ansatzweise umgesetzt ist:
* Versuch, die Qualität des Fundus zu verbessern (nur Lizenzen holen, die besser als der aktuelle Durchschnitt ist)
* Kaufentscheidung nicht immer nach demselben Kriterium (mal Qualität unabhängig vom Preis, mal Preis pro Block, mal Attraktivität)
* Erhöhung des Budgets für Lizenzen

Das führt zumindest dazu, dass nicht mehr alle guten Filme für den Spieler zur Verfügung stehen und dass der jeweilige Fundus der KI-Spieler eine höhere Qualität hat.

**Comment by GWRon** [comment]
Dein Muttiheft braucht langsam eine Erweiterung fuer die ganzen Fleissbienchen die Du Dir mit den ganzen Commits verdienst :)

Danke dafuer.

**Comment by nittka** [comment]
Eine bessere Koordinierung des Budgets ist auch deshalb notwendig, weil zu dem Zeitpunkt wo das erste Bundesland mit Sendern ausgestattet ist, plötzlich lange kein Geld für Sender ausgegeben wird und damit die Ersparnisse steigen. Dann sind die Lizenzen aber schon so teuer, dass das Geld eigentlich verschwendet ist (und für den Senderausbau fehlt).

Aktuelle Idee:
* Mindestanzahl von Lizenzen bis Senderausbau über 2.5 Mio erlaubt ist
* Mindestanzahl bis Senderausbaue über 5 Mio erlaubt ist
* Gesamtmaximalanzahl von (gekauften?) Lizenzen
* Mindestanzahl von Lizenzen, ab der schlechte Lizenzen aktiv abgestoßen und durch bessere ersetzt werden

Wichtig wäre auch eine Statistik über Lizenzen, die "dauerhaft" zu Imageverlust führen und daher ersetzt werden sollen. "Das Geflügel" scheint ein Kandidat zu sein, der von der KI aufgrund seiner Attribute gern und oft gesendet wird, das Image aber am Boden hält.

**Comment by nittka** [comment]
Schlechte Filme werden jetzt häufiger verkauft. Der Kauf von Filmen nach Genre ist vorbereitet (aktuell weniger Horror). Die Koordinierung von Fundus- und Senderausbau wurde etwas verbessert.

**Comment by nittka** [comment]
Im aktuellen Masterstand wird auch schon der Reichweitezuwachs beim Senderkauf berücksichtigt (Anstieg des Reichweitelevels). "Optimal" wird das Ergebnis erst, wenn nicht jeder Task selbst über seinen Budgetanteil entscheidet, sondern eine "Strategie-Engine".
In Testspielen habe ich gesehen, dass auch Auktionen berücksichtigt werden. Die Genre-Präferenzen beim Kauf benötigen noch Nacharbeit.

**Comment by nittka** [comment]
Ich mache dieses Ticket zu. Die verbliebenen Punkte wandern ins Wiki und tauchen dann für die konkrete Umsetzung als PR oder Implementierungsticket wieder auf.
