### ISSUE TITLE
Fernsehfamilie

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#503]
Die Auswahl der angezeigten Zuschauer könnte verbessert werden. Z.B scheint der Arbeitslose aktuell immer vor dem Fernseher zu sitzen und es sind manchmal auch 3 Zuschauer sichtbar, wenn die Einschaltquote gar nicht so hoch ist. Vorschlag: 

* zunächst Anzahl der Personen nach Zuschauerquote (ggf. unterschiedliche Quoten je nach Tageszeit) bestimmen (ggf. auch mal niemanden)
* wer gezeigt wird nach Zielgruppenquote entscheiden (absolute Zuschauerzahlen schwierig, da die Zielgruppen sehr unterschiedliche groß sind)
* wenn es mehr Bilder für die Zuschauer gibt (m/w für alle Zielgruppen), können die Bilder auch nach Geschlecht differenziert werden

**Comment by nittka** [comment]
Vorschlag. Unterscheidung nach Tages und Nachtprogram (Gesamteinschaltquote).
Tag (10-22Uhr);
* 0-5%: niemand
* 5-10%: schlafender Arbeitsloser
* 10-20%: eine Person
* 20-30%: zwei Personen
* >30%: drei Personen

Nacht (23-9 Uhr):
* 0-3%: niemand
* 3-7%: schlafender Arbeitsloser
* 7-15%: eine Person
* >15%: zwei Personen

Es wird dann bei Programmänderung ermittelt, wer sichtbar (Zielgruppen sortiert nach Einschaltquote) und die Sitzpsoition gewürfelt. Eine eizelne Person muss ja nicht immer in der Mitte sitzen. Nach der Werbung kann man sich ja mal umgesetzt haben (Klobesuch in der Werbepause).

**Comment by GWRon** [comment]
Du kannst da gerne "dranrumspielen".
Wenn wir mal andere Grafiken bekaemen ... koennte auch das schon im Code vorbereitete "feedback" ausgewertet werden.

Sprich der Arbeitslose von dem wir schon die "Schlafgrafik" haben, kann auch bei "Schlechtem Feedback" schlafen (er guckt zwar ... aber ist gelangweilt).
Das machen wir ja derzeit schon mit der Gesamtquote ("er guckt mit geschlossenen Augen" :)).

**Comment by nittka** [comment]
Der Prototyp sieht (für mich) schon sehr vielversprechend aus. Es gibt nun natürlich mehr Bewegung auf der Couch. Aktuell wird strikt nach Quote sortiert (links nach rechts, bis auf den Arbeitslosen, der immer am Rand sitzt). Optisch besser wäre natürlich, wenn Personen in aufeinanderfolgenden Programmen an ähnlicher Position sitzen bleiben (Hausfrau und Opa wechseln bei Werbung und Film die Plätze).

**Comment by nittka** [comment]
Wenn dann mehr Bilder da sind, muss man an den angepassten Code nochmal ran. Im Moment wird das Geschlecht ja nach Verteilung innerhalb der Zielgruppe gewählt. Ich könnte mir vorstellen, dass das dazu führt, dass dann immer nur noch "Männer" oder nur noch "Frauen" gleichzeitig vor dem Fernseher sitzen. Hier muss dann noch etwas randomisiert werden.
* Geschlecht zufällig wählen
* nur wenn Quotendifferenz >30 % (35 zu 65) ist, Geschlecht festlegen
* Geschlecht für eine Sendung über mehrere Blöcke nicht ändern
