### ISSUE TITLE
KI Strategie bei geringem Image

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#505]
Bei den KI-Testspielen ist aufgefallen, dass meist ein Spieler beim Image stark zurückbleibt. Vom Gefühl her liegt das vorrangig an der Auswahl des Startprogramms. Sind dort nämlich Filme dabei, die das Image reduzieren (Horror/Familienfilme zur falschen Zeit? ggf. auch Filme deren Outcome als besonders schlecht konfiguriert ist), werden diese dennoch immer wieder gesendet und verhindern eine Erholung des Image.

Das Image-Ergebnis einer Ausstrahlung sollte also berücksichtigt werden und ggf. zum Verkauf der Lizenz führen. Zunächst müsste wohl aber geschaut werden, ob die Tageszeit eine Rolle Spielt (Horror)...

**Comment by nittka** [comment]
Ein erster Ansatz wäre, dass bei Image-Verlust durch Ausstrahlung eine Sendung nur dann erneut gesendet wird, wenn sie wieder volle Aktualität erreicht hat.

**Comment by nittka** [comment]
Ich weiß nicht, ob es hier eine grundsätzliche Lösung geben kann. Im Extremfall kommt nach einem Bankrott eine neue KI ohne Image, Feld und Filme. Solange die Ermittlung des Imagezuwachs (zu stark) anhand der Performance der anderen Spieler ermittelt wird, besteht hier keine Chance.
Ohne Geld keine guten Nachrichten und keine guten Filme undd damit wenig Imagegewinn.

**Comment by GWRon** [comment]
Vlt sollte die Imageaenderung auch in Relation zum eigenen Image stehen?
Sprich - die Erwartungshaltung ist hier von anteiliger Rolle statt ignoriert zu werden.

Wenn jemand ein "Image von 50%" hat, dann ist bei dem einfach "mehr" erwartet, als bei einem, wo es eh nicht schlimmer geht. 
Du bist also vom "Ramschsender" eher positiv ueberrascht, wenn dem ein Coup gelingt - bei gut angesehenen Sendern waere das Ausstrahlen einer Werbesendung schon fast ein "Todesstoss"

Vereinfacht:
```
positive Imageaenderung = (1 - Senderimage) * 0.75 * Zugewinn + 0.25 * Zugewinn

negative Imageaenderung = Senderimage * 0.75 * Verlust - 0.25 * Verlust
```

**Comment by nittka** [comment]
Ja, in die Richtung ging meine Überlegung auch. Es sollte nach hinten kein Selbstläufer sein, ein immer besseres Image zu bekommen. Und wie in einem anderen Ticket beschrieben, habe ich bei 100% Image keinen Verlust mehr erlitten, obwohl ich tagelang Sendeausfall hatte.

**Comment by nittka** [comment]
Ja, aber vielleicht lässt es sich unmittelbar bei Spielstart reduzieren, indem man das Image auf 100% setzt und dann vorspult, ohne Programme zu planen.

**Comment by nittka** [comment]
Ich habe die wichtigsten Punkte bezüglich Imageberechnung in das verlinkte Ticket gepackt und das Debugbildschirm-TODO auf meine private Liste gesetzt. Das ist ja von der Prio nicht so hoch, da das Image per Chat leicht angepasst werden kann.

KI-Anpassungen für eine Strategie bei geringem Image sind erst sinnvoll möglich, wenn die Imageberechnung an sich geändert wurde.

**Comment by nittka** [comment]
... Bist Du Dir sicher, dass ein Image>100 nicht möglich ist? In dem Spielstand bei mir schien es nämlich tatsächlich der Fall gewesen zu sein, dass das Image größer war und deshalb der Sendeausfall "keine Auswirkung" hatte. Und an Schummeln kann ich mich nicht erinnern ;-) Da kann man jedenfalls Werte größer 100 provozieren (bei Image 100 einfach noch was dazutun - im Chat sieht man dann den Wert)

**Comment by GWRon** [comment]
Sicher bin ich mir nicht ... aber der Code sagt zumindest, dass er zwischen 0 und 100 limitiert.
```
		'avoid negative values -> cut to at least 0
		'also avoid values > 100
		ImageValues.CutMinimumFloat(0).CutMaximumFloat(100)
```

Wenn das allerdings umgangen wird, ist >100 moeglich - sollten wir per debugscreen ja gut erkennen

**Comment by GWRon** [comment]
Das Image kann bis zu 200% sein - wohl weil beim "Bearbeiten" die Werte auf die Geschlechter (m/w) aufgeteilt werden - wir dort also "100% Maenner + 100% Image bei Frauen" haben. Muss ich mir nochmal anschauen.

**Comment by GWRon** [comment]
Ich denke wir muessen uns "TPublicImage" nochmal angucken ... das Problem ist, das ich da mit Manuel damals versucht habe "clever" zu sein.
Wenn also fuer bestimmte Zielgruppen keine Angaben vorlagen, dann wurde nur nach "Maenner/Frauen" unterteilt (die aber wiederum ja auch Zielgruppen sind - und somit bei "TAudience" hinterlegt sind).
ein 5% Zuwachs wird dann auf die Zielgruppen runtergebrochen, so dass sie "in Summe" den Gesamtwert um 5% erhoehen sollten.

Denke ... da muessen wir nochmal drueber gucken.
