### ISSUE TITLE
Auswirkungen Terrorist

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#507]
In MadTV verursachte der Terrorist auch einen finanziellen Schaden. Das wäre ein stärkerer Anreiz, auf die Bedrohung zu achten. Ein Angriff auf ein Archiv hat auch zur Zerstörung einer Lizenz geführt. Außerdem könnte man darüber nachdenken, dass die Dauer der Sperrung im Laufe der Zeit steigt.

**Comment by GWRon** [comment]
- Bei Zerstoerung einer "Serie" (aua!) muss etwaiges noch in Produktion befindliches Zeug gestoppt und um die Drehbuecher sollte sich auch gekuemmert werden
- der finanzielle Schaden bei Raeumen koennte abhaengig von der Raumgroesse sein (so ...Studios...)
- beim Newsstudio koennte neben der Raumblockade auch zufaellig die Nachrichtenshow "vernichtet" werden (alle 3 Bloecke "nach links")

**Comment by nittka** [comment]
Der Einfachheit halber würde ich die Zerstörung entweder auf gekaufte Lizenzen beschränken oder abgeschlossene Produktionen. Serien könne man auch komplett ausschließen, sonst muss man sich die Frage stellen, ob Einzelfolgen oder nur die gesamte Serie betroffen sein kann.

**Comment by nittka** [comment]
* immer Raumrenovierung für ? Geld * Faktor (abhängig von Schwierigkeitsstufe und Reichweite)
* Raum blockiert (ist relevanter für Nachrichtenstudio und Büro); Zeit abhängig von Schwierigkeitsstufe
* Büro keine weitere Auswirkung (keine Programmplanung machen zu können ist schlimm genug - Zeit muss relevant sein, vom Gefühl her bis zu 2 Stunden) 
* Nachrichtenstudio Entfernung der geplanten Nachrichten (Studio kaputt - Nachrichten können nicht produziert werden)
* Boss Halbieren der Boss-Stimmung
* Archiv eine Lizenz wird auf unavailable gesetzt (nicht zurück zum Händler); ich würde hier keine Einschränkungen machen - man muss einfach aufpassen, wenn das Terrorlevel steigt

**Comment by GWRon** [comment]
Archiv: die Lizenz wird also unwiderruflich "zerstoert" (fuer niemanden mehr zugaenglich)?


Emofaende das ala unschoen, es braucht ja nur eine neue VHS und man ist wieder am Start.

Oder willst Du die Lizenz fuer X Zeit blockieren?

Am 19. Oktober 2022 07:35:25 MESZ schrieb Alexander Nittka ***@***.***>:

**Comment by nittka** [comment]
Ja, eigentlich war das die Idee. Alternativ kann auch nur der Owner zurückgesetzt werden - man muss sie wieder neu kaufen. Kann ich auch gut mit leben.

**Comment by nittka** [comment]
In der obigen Liste fehlt noch Studio - länger blockiert, aktuell laufende Produktion "abgebrochen" Einkaufszettel zerstört und muss neu geholt werden, partielle Kosten für Gagen etc. müssen trotzdem bezahlt werden.

**Comment by GWRon** [comment]
Bei den teuren Sachen: Lizenz zerstoert, Produktion abgebrochen/zerstoert muessen wir aufpassen, dass sie vlt "optional" sind (Schwierigkeitsgrad schwer)...da sie vor allem zu Anbeginn ja durchaus starken Einfluss haben ("ne, da fang ich lieber neu an / lade ein").

**Comment by nittka** [comment]
Wenn was nicht klappt, werden viele ohnehin einen Spielstand neu laden.
Aktuell kann man den Terroristen praktisch ignorieren, da er "keine" Auswirkungen hat (ich kann kurz nicht zum Boss). Nur die KI rennt dauernd runter und verschwendet Zeit. Es muss schon weh tun, damit man sich um diesen Spielaspekt kümmern muss.

(besonders fies bei neu angemieteten Studios wäre, wenn man die dann auch neu mieten muss - fremde Studios für sich frei machen ;-))

**Comment by GWRon** [comment]
Du meinst soetwas?:
- liegt nur ein Drehbuch drin -> Drehbuch zerstoert
- liegen zusaetzlich Einkaufslisten drin... Wird die letzte davon zerstoert (oder eher sogar...alle Listen)
- laeuft eine Produktion, wird diese abgebrochen und auf "Vorauszahlung noch nicht geleistet" gesetzt
- leeres Studio ... Vertrag wird gekuendigt (Ausnahme "letztes Studio des Spielers", dann nur Raumsperrung fuer einige Stunden)

Gemein waere natuerlich, wenn ALLES passiert..aber das koennte dann finanziell schon sehr sehr weh tun (Seriendrehbuch, sechs volle angezahlte Einkaufslisten..). Inwieweit das Lizenzkosten uebertrifft...
Eventuell waere da ein wenig "Zufall" noch hilfreich. Also, dass nicht alle Schritte oben ausgefuehrt werden (von unten nach oben vorgehen, wurde ein Schritt ausgefuehrt, ist der naechste Vorgang etwas unwahrscheinlicher. Folgeschritte nur ausfuehren, wenn der Vorgaenger ausgefuehrt wurde).

**Comment by nittka** [comment]
Ich denke, "Studio wieder anmieten müssen" sollten wir erstmal nicht weiterverfolgen. Man könnte die Auswirkung zwar abschwächen, wenn ein ggf. darin befindliches Drehbuch in den Koffer kommt, aber der kann ja auch voll sein. Blockieren und ggf. laufende Produktion weiter verlängern ("die Darsteller mussten sich erstmal von dem Schock erholen") oder aber Produktion abbrechen und neu machen müssen, reichen völlig aus.

**Comment by nittka** [comment]
Prototyp für Auswirkung des Terroristen ist fertig. Lediglich die Sonderbehandlung für Studios steht noch aus.
