### ISSUE TITLE
KI Logging

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#508]
* Logging zunächst stark reduzieren
* Möglichkeit schaffen, Logging für den gerade interessanten Task zu aktivieren
* Spielzeit des Loggings mit ausgeben (Tag 01, 05:29); das könnte automatisch vor den Text geschrieben werden

**Comment by GWRon** [comment]
Auch koennte eine Art "LogLevel" interessant sein.
Der Aufruf des movieDealer-Tasks waere Level1, "Kaufe Filme" dann Level 2, "Kaufe Film XYZ" dann Level 3.

Damit waere konfigurierbar, wie detailliert die Ausgabe erfolgen sollte.

**Comment by nittka** [comment]
Ja, Loglevel hatte ich auch im Sinn. Ich würde gern einfach ein Level pro Task festlegen können, um schnell umschalten zu können.

**Comment by nittka** [comment]
Die Basisfunktionalität wurde mit #521 eingeführt. Restaufräumarbeiten in den einzelnen Tasks/Jobs erfolgen bei den weiteren KI-Anpassungen.
