### ISSUE TITLE
Zuschauermarkt: Optimierung

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#511]
@nittka aeusserte die Anregung, dass die derzeitige Umsetzung des Zuschauermarktes (und wann Dinge berechnet/erstellt werden muessen) einer Optimierung beduerfen koennten.

Hier koennen wir ja ein wenig ausdiskutieren, was wir da verbessern koennten, und auf was zu achten waere (u.a. Spielmodifikatoren die durch News getriggert werden und temporaer die Zuschauerverhaeltnisse veraendern)

**Comment by GWRon** [comment]
1 Tag mit 4 AI-Spielern (AI Game):
AscertainPlayerMarkets() 298x aufgerufen

Wenn die ganze Zeit die DevScreen-Broadcastuebersicht laeuft:
AscertainPlayerMarkets()   2503x aufgerufen

und beim "Auto-Save" ist mir nun das Spiel stehngeblieben.

**Comment by nittka** [comment]
Abgesehen davon, dass die Markterstellung/-Aktualisierung wesentlich seltener passieren müsste, ist AudienceMarkets aktuell eine TList. Sie wird bei der Aktualisierung immer gelehrt und dann wieder aufgefüllt.
Wäre es nicht sinnvoller, ein Array zu verwenden? Die Größe ist doch konstant. Außerdem könnte man dann bei einer Aktualisierung immer genau einen Eintrag ersetzen, da die verschiedenen Schnittmengeneinträge immer in derselben Reihenfolge erstellt werden. (Man gibt dem AddMarket einfach den Index mit.)

**Comment by GWRon** [comment]
Du muesstest schauen, wie oft ein TBroadcast erneut genutzt wird - und wie oft einfach nur "geleert" wird obwohl die Liste eh gerade erst angelegt worden ist.


Bezueglich Array und Ersetzen: Wenn da parallel Zugriffe moeglich "waeren", dann wuerden dann ja alte "noch nicht ersetzte" und neue "bereits ersetzte" in einem Array stecken koennen - und bei Berechnungen wuerden alte und neue Daten zusammengewuerfelt werden.

**Comment by GWRon** [comment]
Ich habe zumindest fuer den Dev-Screen die refreshMarkets()-Aufrufe ordentlich eingekuerzt.

**Comment by nittka** [comment]
Abgesehen von den ohnehin möglichen Optimierungen ist für die KI-Vorhersage der aktuelle Mechanismus ja "Overkill" (insb. wegen der Berechnungshäufigkeit: mehrfach pro Stunde für mehrere Sendetermine). Für das Raten der eigenen Zuschauerzahl muss ja nicht die gesamte Marktsituation auf die Einzelperson vorhergesagt werden (das passiert ja eher wegen "Code ist sowieso schon da"). An sich würde ja eine grobe Schätzung - potentielle Zuschauer zu dieser Zeit * geratene Einschaltquote reichen. Vielleicht kann hier mittelfristig ein vereinfachtes Modell verwendet werden.

**Comment by nittka** [comment]
Ich würde dieses Ticket zumachen und falls nötig, ein auf die neue Kartenlogik zielendes neu aufmachen.
