### ISSUE TITLE
Savegames bei hohen Spielgeschwindigkeiten : Freeze

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#513]
- starte ein AI game
- warte bis Mitternacht und nach dem Auto-Save ... gehe wieder ins Hauptmenue
- starte ein weiteres AI game
- warte bis kurz vor Mitternacht - beim Auto-Save bleibt das Spiel stecken

(getestet im "master" branch)

**Comment by GWRon** [comment]
Es reicht schon, beim AI-game vorher mittels F5 einmalig ein Quicksave angelegt zu haben. Ich vermute also, der Fehler liegt in der Art, wie der Debugscreen-Code das Auto-Save macht.

**Comment by GWRon** [comment]
Hmm im Debug-Build ist mir nun auch ein "F5"-Quicksave eingefroren.

**Comment by GWRon** [comment]
OK, also ich hab hier ein neues Spiel gestartet (debug)  ... die Spielgeschwindigkeit ein wenig erhoeht (180 in etwa - bei mir) und dann im Sekundentakt F5 gedrueckt ... nach dutzenden erfolgreichen Speicherungen ... fror es ein - reproduzierbar.

Geschieht bei mir auch im Release bei Spielgeschwindigkeiten von 500 ... Ich vermute es entsteht irgendwo ein Deadlock von Mutexen.

**Comment by GWRon** [comment]
Ohne jetzt in den Code geschaut zu haben ... die KI wird ja beim Speichern gestoppt - eventuell verarbeitet sie dann keine ankommenden Befehle und versperrt da irgendwie den Mutex ... muss ich mir ueber den Mittag mal anschauen.

**Comment by nittka** [comment]
Einen Deadlock gab es bei mir ganz selten auch mal beim "normalen" Vorspulen, einmal in einem gdb-Lauf. Leider reagierte da der Rechner überhaupt gar nicht mehr, so dass ich im Debugger das Spiel auch nicht unterbrechen konnte. (Auch meine Vermutung wäre da gegenseitige Mutex-Blockierung durch 2 KIs)

**Comment by GWRon** [comment]
Bei mir blockt es innerhalb von `player.PlayerAI.CallOnSave()` (game.game.bmx -> Function onSaveGameBeginSave:Int(triggerEvent:TEventBase))

**Comment by GWRon** [comment]
Ich habe mal vor und nach jedem LockMutex fuer CallLuaFunction (sowie UnlockMutex) eine debugausgabe machen lassen:
```
        AI2 "OnMinute" - Locking Mutex
        AI2 "OnMinute" - Locking Mutex. Done
        AI2 "OnMinute" - Unlocked Mutex
            AI3 "OnBeginEnterRoom" - Locking Mutex
            AI3 "OnBeginEnterRoom" - Locking Mutex. Done
            AI3 "OnBeginEnterRoom" - Unlocked Mutex
            AI3 "OnReachTarget" - Locking Mutex
            AI3 "OnReachTarget" - Locking Mutex. Done
            AI3 "OnReachTarget" - Unlocked Mutex
            AI3 "OnEnterRoom" - Locking Mutex
            AI3 "OnEnterRoom" - Locking Mutex. Done
            AI3 "OnEnterRoom" - Unlocked Mutex
            AI3 "OnTick" - Locking Mutex
            AI3 "OnTick" - Locking Mutex. Done
            AI3 "OnTick" - Unlocked Mutex
            AI3 "OnMinute" - Locking Mutex
            AI3 "OnMinute" - Locking Mutex. Done
            AI3 "OnMinute" - Unlocked Mutex
OnBeginSave
        AI2 "OnSave" - Locking Mutex
        AI2 "OnSave" - Locking Mutex. Done
                AI4 "OnTick" - Locking Mutex
                AI4 "OnTick" - Locking Mutex. Done
...
        AI2 "OnBeginEnterRoom" - Unlocked Mutex
            AI3 "OnSave" - Unlocked Mutex
                AI4 "OnSave" - Locking Mutex
            AI3 "OnRealTimeSecond" - Locking Mutex
            AI3 "OnRealTimeSecond" - Locking Mutex. Done
            AI3 "OnRealTimeSecond" - Unlocked Mutex
```
Wie hier erkennbar ist, hat AI4 fuer einen  "OnTick" den Mutex gelockt - und verweilt gerade in der Funktion dort ... dann kommt "onSave" und will auch locken ... und an der Stelle wartet es "fuer immer" - scheinbar kann das Lua-Skript irgendwas nun nicht ausfuehren (wartet wohl auch auch auf einen Lock ...)

**Comment by GWRon** [comment]
```
OnBeginSave
        AI2 "OnSave" - Locking Mutex
        AI2 "OnSave" - Locking Mutex. Done
                AI4 "OnTick" - Locking Mutex
                AI4 "OnTick" - Locking Mutex. Done
                AI4 "OnTick" - Unlocked Mutex
                AI4 "OnMinute" - Locking Mutex
                AI4 "OnMinute" - Locking Mutex. Done
                AI4 "OnMinute" - Unlocked Mutex
            AI3 "OnTick" - Locking Mutex
            AI3 "OnTick" - Locking Mutex. Done
        AI2 "OnSave" - Unlocked Mutex
            AI3 "OnSave" - Locking Mutex
            AI3 "OnSave" - Locking Mutex failed - still in use by "OnTick" ?. Waiting...
```
Hier sieht man wohl sehr gut einen ... moeglichen Bug-Kandidaten.

Waehren der Mainthread "onSave" rausschickt, holen sich die KIs noch "onTick" und "onMinute" events ab.
Dadurch dass wir mit hoher Spielgeschwindigkeit "spielen", staut sich ja manches Mal ein wenig die eventQeue auf.

Unabhaengig vom "freeze" sollte hier abgeklaert werden, ob die KI ihre Events "aufheben" sollte (und nach einem Einladen bzw. Speichervorgang-abgeschlossen abarbeiteT), oder ob noch vor dem Speichern offene Events zu beackern waeren - ich tendiere jetzt mal zu letzterem. Entsprechend ist das aktuelle "onTick"-Bearbeiten noch waehrend der Speicheranfrage "OK".
Man koennte jetzt auch ueberlegen, ob man eine Funktion einbaut, bei der auf alle KIs wartet und erst fortfaehrt, wenn alle eventQueues abgearbeitet sind. Also eine Art "Synchronisierung".

**Comment by nittka** [comment]
Ich fände es für das Speichern auch sinnvoll, einen "sauberen" Stand zu hinterlassen. D.h. die KI erst auf gestoppt zu setzen, wenn die aktuellen Events abgearbeitet sind.
(Problemkandidat Programmplanung, bei der stauen sich bei mir typischeweise die meisten Events)

**Comment by GWRon** [comment]
Also ... viel Gebuddel bisher ... und 'ne Menge Debugausgaben.

Ich habe nun die KI vor dem "CallOnSave" die Events abarbeiten lassen und wenn das nicht innerhalb von XXX Millisekunden geschafft wird, wird fuer die entsprechenden noch beschaeftigten KIs versucht etwaige Fehler vom Lua ausgeben zu lassen:

Ich bekomm da verschiedene --- "trying to call a string value", "trying to call a boolean value" ...

```
	'run when starting saving a savegame
	Function onSaveGameBeginSave:Int(triggerEvent:TEventBase)
		TLogger.Log("TGame", "Start saving - inform AI.", LOG_DEBUG | LOG_SAVELOAD)
'TLuaEngine.debugInvoke = True
		'wait for all AIs to have finished with their events
		local allDone:Int
		Local t:Int = Millisecs()
		Repeat
			allDone = True
			For Local player:TPlayer = EachIn GetPlayerCollection().players
				If player.isLocalAI() 
					if player.PlayerAI.GetNextEventCount() > 0
						print "waiting for player: " + player.playerID +"  events:"  + player.PlayerAI.GetNextEventCount() + "   " + GetWorldTime().GetFormattedGameDate()
						LockMutex(player.PlayerAI._eventQueueMutex)
						for local ev:TAIEvent = EachIn player.PlayerAI.eventQueue
							print " - event.id="+ev.id + "  " + ev.GetName()
						Next
						UnlockMutex(player.PlayerAI._eventQueueMutex)

						allDone = False
					endif
				EndIf
			Next
			if Millisecs() - t > 500
				For Local player:TPlayer = EachIn GetPlayerCollection().players
					If player.isLocalAI() 
						if player.PlayerAI.GetNextEventCount() > 0
							print "Dump for AI : " + player.playerID
							player.playerAI.GetLuaEngine().DumpError()
						endif
					endif
				Next
				end
			endif
			If not allDone then delay(100)
		Until allDone
		
		'inform player AI that we are saving now
		For Local player:TPlayer = EachIn GetPlayerCollection().players
			If player.isLocalAI() Then player.PlayerAI.CallOnSave()
		Next
'TLuaEngine.debugInvoke = False
	End Function
```


```
Dump for AI : 3
[16:16:12] ERR      | TLUAENGINE: #### ERROR #######################
[16:16:12] ERR      |           : Engine: 2
[16:16:12] ERR      |           :
[16:16:12] ERR      |           : attempt to call a boolean value
stack traceback:
	[C]: in function 'doLeaveRoom'
	res/ai/CommonAI/AIEngine.lua:623: in function 'SetDone'
	res/ai/DefaultAIPlayer/TaskMovieDistributor.lua:119: in function 'GetNextJobInTargetRoom'
	res/ai/CommonAI/AIEngine.lua:478: in function 'StartNextJob'
	res/ai/CommonAI/AIEngine.lua:534: in function 'Tick'
	res/ai/CommonAI/AIEngine.lua:241: in function 'TickProcessTask'
	res/ai/CommonAI/AIEngine.lua:222: in function 'Tick'
	[string "--res/ai/DefaultAIPlayer/DefaultAIPlayer.lu..."]:844: in function <[string "--res/ai/DefaultAIPlayer/DefaultAIPlayer.lu..."]:836>
```

Hatte das aber auch schon bei `TVT.of_setAdvertisementSlot()` usw.  ...
Ich weiss nun bisher noch nicht, was das hervorruft - vielleicht wird der Stack vom Lua nicht richtig "aufgeraeumt" bzw beinhaltet da noch Sachen, die er nicht beinhalten sollte ...

**Comment by GWRon** [comment]
OK ... ich hatte nun mal "invoke()" mit Mutex versehen (so wie im "WIP").

Nun ists mir beim Dumpen des Errors haengen geblieben ?!

```
[17:04:02] ERR      | TLUAENGINE: #### ERROR #######################
[17:04:02] ERR      |           : Engine: 1
[17:04:02] ERR      |           : 
```

**Comment by nittka** [comment]
Im Event-Mutex-Commit gibt es eine Stelle, die mir Sorgen bereitet. In GenerateEventKey wird derselbe Mutex zweimal hintereinander verwendet. Sollte ein Methodenaufruf nicht eher "atomar" sein, damit nicht jemand mittendrin dazwischenfunkt?

```
		LockMutex(_changeMutex)
		local existingKey:TEventKey = TEventKey(eventKeyIDMap.ValueForKey(e.id))
		if existingKey 
			UnlockMutex(_changeMutex)
			Throw "GenerateEventKey(): key for ID="+e.id+" already exists. Hash collision?"
		endif

		eventKeyTextMap.Insert(e.text, e)
		eventKeyIDMap.Insert(e.id, e)
		UnlockMutex(_changeMutex)
```

**Comment by GWRon** [comment]
Die zitierte Stelle gibt ja nur den Mutex frei, bevor es eh ...das Programm mit einem throw beendet.

Ansonsten setze ich die Mutexe eigentlich so knapp wie moeglich..also nur, wenn der zu schuetzende Teil beackert wird.

**Comment by nittka** [comment]
Ja, hat bei mir auch keinen Unterschied gemacht. Jedenfalls hat es aktuell den Anschein, dass es
* mit den Locks bei den Events keinen Segmentation-Fault gibt, aber das Programm beim Speichern hängen bleibt
* ohne die Locks bei den Events Segmentation-Faults vorkommen, aber das Speichern funktioniert

Sind die Locks beim "GetEventKey" (reine getter) etc. nötig? Problematisch sind doch eher ändernde Operationen.

**Comment by GWRon** [comment]
Naja valueForKey iteriert denke ich ueber die Keys...da waere es unpraktisch, wenn gleichzeitig der tree der maps geaendert wird...also durch ein map.insert.

Andere Sprachen bieten readMutexes..also damit bspweise das gleichzeitige Lesen moeglich waere.

Hier muesste man da wohl zwei Mutexe nutzen..und beim Schreiben beide locken, beim Lesen allerdings nur einen.

**Comment by GWRon** [comment]
OK ... also meine "Theorie":
Das Event-System nutzen wir ja auch als eine Art "Callback-System" bei dem sich Dinge "anonym" (also ohne die Dateien zu importieren) fuer bestimmte Dinge interessieren koennen ("player.onEnterRoom" - ohne TPlayer kennen zu muessen).

Mit dem LockMutex hier:
```
		Local listeners:TObjectList = GetListeners(triggeredByEvent.GetEventKeyID())
		If listeners
			LockMutex(_changeMutex) '<--------- HIER ---------
			'use a _copy_ of the original listeners to avoid concurrent
			'modification within the loop
			'listeners = listeners.Copy()
			For Local listener:TEventListenerBase = EachIn listeners
				listenersCalled :+ 1
				listener.onEvent(triggeredByEvent)
				'stop triggering the event if ONE of them vetos
				If triggeredByEvent.isVeto() Then Exit
			Next
			UnlockMutex(_changeMutex)
		EndIf
```
passiert nun folgendes:
- KEY_F5 -> TSavegame.Save()
- Event `GameEventKeys.SaveGame_OnBeginSave` wird getriggert
- Lock wird gesetzt, und unter anderem `TGame.onSaveGameBeginSave()` ausgefuehrt
- in TGame wird nun jede PlayerAI mit `CallOnSave()` losgeschickt -> LUA-Skripte machen nun ihre Speichervorbereitungen
- eine der dortigen Funktionen ruft BlitzMax-Funktionalitaeten auf
- der Eventmanager fuehrt "triggerEvent()" von Fremd-Threads (wie also dem Lua-AI-Thread) derzeit nicht mehr sofort aus, sondern registriert sie fuers naechste Update() - eventuell ist aber die dazugehoerige Funktion davon ausgegangen, dass der Event sofort getriggert und irgend ein Objekt "bearbeitet" wurde.
- und falls es doch irgendwie zur sofortigen Ausfuehrung kommen soellte - dann kann die Funktion nicht ausgefuehrt werden, da ja obiger LockMutex() noch aktiv ist
- in dem Fall: deadlock (subthread wartet auf onEvent-Ausfuehrung, main thread wartet auf Beendigung des Calls)

**Comment by nittka** [comment]
Kann dieses Ticket zugemacht werden?
