### ISSUE TITLE
Balancing späterer Spielstart

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#518]
Das Problem ist ja schon mehrfach angesprochen worden. Im Forum gab es wieder eine Meldung: https://www.gamezworld.de/phpforum/viewtopic.php?pid=89651#p89651

Da die Zuschauerreichweite der Sendemasten in späteren Jahren sinkt, sind Spielestarts in späteren Jahren problematisch, da durch die Werbeeinnahmen nicht reichen **können**, um die Senderkosten und nötigen Filmkäufe zu finanzieren. Für dieses Problem wird ein Lösungsansatz benötigt.

* Bevölkerungsentwicklung und Wechsel auf Kabel/Satellit zeitlich nach hinten verschieben - möglich aber nicht realistisch
* später gebaute Sender haben geringere Bau- und Unterhaltskosten (technischer Fortschritt) und ein größeres Einzugsgebiet - damit kann man erreichen, dass für ähnliche Kosten ähnlich viele Zuschauer mit Antenne erreichbar sind
* spätere Spiele starten mit einem billigen Kabelvertrag (vergleichbare Startzuschauerzahl bei vergleichbaren Kosten)

Ich glaube aber, dass man um geänderte Antenneneigenschaften in späteren Jahren nicht herumkommt (Preis Genehmigung für andere Bundesländer) oder es ist eben nicht mehr so abwechslungsreich, da man einfach sparen muss, bis man sich den nächsten Kabelvertrag leisten kann.
Jedenfalls sollten die Unterhaltskosten eines Senders nicht so sein, dass sich ein Kauf nicht lohnen kann.

**Comment by nittka** [comment]
Ich habe zumindest erfolgreich ausprobiert, dass das Hochsetzen von antennaStationRadius die Reichweite einer Antenne tatsächlich erhöht. Damit allein wäre es aber noch nicht getan, da auch die Berechnung von Kaufpreis- und laufenden Kosten angepasst werden muss. Bei einem Start im Jahr 2000 wären aktuell die laufenden Kosten bei einer Antenne mit Radius 40 bei nahezu 1Geld pro Zuschauer und damit dramatisch höher als bei Kabel oder Satellit.

**Comment by GWRon** [comment]
Ja der flexible Radius war damals schon so von mir vorgesehen - noch als "upgrade"-Moeglichkeit fuer Sendemasten.

Fuer die Kosten gibt es ja die GetPrice()-Methode, da liesse sich ja gut die Spielzeit/Echtzeit mit integrieren. Gleiches fuer die "RunningCost"-Methoden.

**Comment by nittka** [comment]
Wäre folgendes möglich? Bei einem späteren Spielstart ist für eine Antenne in einem anderen Bundesland keine Sendelizenz nötig, d.h. der Ausbau mit Antennen geht deutschlandweit, nur die Kabellizenzen bräuchten eine höhere Einmal-Investition.
Auf diese Weise könnte man noch immer mit Antennen starten (größerer Radius, geringere Kosten) man muss (und kann) zunächst in kleineren Schritten die Reichweite ausbauen.

**Comment by GWRon** [comment]
Dazu muesste die entsprechende Methode angepasst werden:
```
	'returns whether a channel needs a permission for the given station type
	'or not - regardless of whether the channel HAS one or not
	Method NeedsBroadcastPermission:int(channelID:int, stationType:int = -1)
		return True
	End Method
```
Dort dann Startjahre usw. ueberpruefen.

Allerdings muss bedacht werden, ob dann bei Startjahr 1999 keine Genehmigung gebraucht wird, aber bei 1998 ist sie noch erforderlich - wer wuerde dann 1998 starten wollen?

**Comment by nittka** [comment]
Ich habe gerade mal ein Testspiel im Jahr 2000 angefangen und den Antennenradius auf 60 gesetzt. Das allein und kostenlose Sendelizenzen würden aber auch nicht reichen. Der Großteil des Antennenpreises ergibt sich aus der maximalen Reichweite, die unabhängig von den eigentlichen Antennennutzern ist und zu astronomischen Preisen führt.

Ich sehe hier zwei mögliche Ansätze: das aktuelle Jahr zu berücksichtigen (sinkende Fixkosten durch technischen Fortschritt) oder die Maximalreichweite für die Kostenberechnung "radiusunabhängig" zu machen. D.h. auch bei Radius 60 wird für die Maxreichweite Radius 20 zugrunde gelegt. Das könnte man auch als technischen Fortschritt interpretieren. Jedes Jahr steigt der Radius einer neu gebauten Antenne um 2 Pixel. Die technische Reichweite steigt, aber immer weniger Leute nutzen Antenne.

**Comment by nittka** [comment]
Ich habe in dem Branch mal einen absolut minimalen Ansatz implementiert (ohne Prüfung der Plausibilität der Werte). Das Umschalten von Sendegenehmigung nötig ja/nein ist für Antennen dann schon ziemlich drastisch. Ich sehe aber auch auf die Schnelle nicht, wie man einen graduellen Übergang machen sollte.

**Comment by nittka** [comment]
Ich habe gerade ein paar KI-Testspiele mit den angepassten Startradien und unterschiedlichen Startjahren angeschaut. Dabei habe ich die Werte lokal noch etwas angepasst. Der erste Eindruck ist, dass eine Startreichweite zwischen 1 Mio und 1.2 Mio ganz gut für die KI funktioniert. Wenn es deutlich darunter liegt, sind werden die Kreditfixkosten vergleichsweise zu hoch, um von der Stelle zu kommen.

Was man also generisch machen könnte (wenn es geht), wäre zu Spielstart einen Radius zu ermitteln: temporäre Station mit Startkoordinaten und den Radius so lange von 20 erhöhen, bis der Wert in diesem Bereich liegt. Dann muss man keine festen Jahreszahlen und Radien vorgeben.
