### ISSUE TITLE
normales Speichern nicht mehr möglich

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#527]
Im aktuellen Masterstand soll die KI noch Events abarbeiten, bevor gespeichert wird (OK). Wenn man das Speichern über das Esc-Menu anstößt, wird die KI aber zunächst pausiert. Dadurch kommt es dann beim Speichern zum Fehler. Am besten wäre es wohl, wenn die KI generell erst alle offenen Events abarbeitet, bevor sie in pausiert wird.

**Comment by GWRon** [comment]
Die ki muss vorher entpausiert werden.

Das Abarbeiten der Events fuer die Ki...das hab ich nicht ohne Grund schon erweitert...denn das kann glaube ich auch haengen...oder hing mal in einer meiner mutex-Tests.

Generell musst du mal schauen, welche Events trotz Pause noch an die KI "gequeued" werden (onmoneychange).

Allerdings dachte ich der masterstand hat schon einen pausecheck drin und ueberspringt dann das Abarbeiten der Events...

**Comment by nittka** [comment]
Ja. Zum Zeitpunkt des Reports hatte ich noch nicht den aktuellen Master.
