### ISSUE TITLE
Rechtsklick mit "angezahlter" Einkaufsliste

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#533]
Eine 1.000 Euro News mit Rechtsklick wegzuloeschen bedarf vielleicht keiner "Nachfrage" ... anders sieht es meiner Meinung nach aus, wenn man eine teure Einkaufsliste angezahlt hat.

Man koennte nun entweder den Rechtsklick nur fuer "wieder zurueckholbares" nutzen (Programme im Planer usw.) und bei allen anderen einen Papierkorb hinzufuegen / nutzen.
... oder man fuehrt ein Nachfragefenster ein ("wirklich vernichten? Erneuter Rechtsklick zur Bestaetigung!")

Gedanken / Ideen dazu ?

**Comment by nittka** [comment]
Sollte hier Rechtsklick überhaupt Löschen bedeuten? Man könnte auch einfach an die Ursprungsstelle zurückfallen lassen. Ein explizites Löschen ist ja mit dem Mülleimer möglich.

**Comment by GWRon** [comment]
Das ist ja die Frage.

Muss die Nachrichtenplanung auch einen Muelleimer bekommen..oder braucht es eine Abfrage beim entgueltigen Loeschen von teuren Sachen mittels Rechtsklick.

**Comment by nittka** [comment]
Hier würde ich zunächst die "Inkonsistenz" beibehaletn: Rechtsklick bei den Nachrichten=Löschen, Rechtsklick woanders Zurückfallen lassen. Ich finde es im Nachrichtenstudio eher angenehm, alte und uninteressante Einträge leicht löschen zu können. Nur ganz selten lösche ich mal aus Versehen eine Nachricht, die ich eigentlich behalten wollte.

**Comment by nittka** [comment]
Ich weiß nicht, wie oft überhaupt Einkaufslisten im Studio aufgehoben werden (egal ob für Umsortieren, Löschen oder Studioleiter fragen).
Ich könnte hier gut mit beidem leben: Rechtsklick=wegwerfen beibehalten oder grundsätzlich Ändern auf Zurückfallen lassen.

**Comment by nittka** [comment]
Wenn Du es auf Zurückfallenlassen änderst, würde ich das konsistent für alle machen. Der Mülleimer ist da und sichtbar.

**Comment by GWRon** [comment]
Bin hier gerade ein wenig coronabelastet (also "unausgelastete" Kinder zuhause und selbst mit Unbehagen erfuellt :D) ... kannst Du mir nochmal zusammenfassen, was wo geaendert werden soll?

**Comment by nittka** [comment]
Ausgangspunkt ist PR #530 und dieses Ticket sollte auch (nur) zusammen mit diesem PR bearbeitet werden.
Im Zuge der Aufräumarbeiten wolltest Du das Verhalten von Rechtsklicks geradeziehen. Mein Kompromissvorschlag war, dass Rechtsklick nicht überall dasselbe machen muss, aber in einem Screen nicht je nach Situation unterschiedliche behandelt werden soll. Also
* Nachrichtenstudio: Rechtsklick bei aufgehobenem Nachrichtenitem = Wegwerfen der Nachricht, kein Mülleimer einbauen
* Studio: Rechtsklick bei aufgehobener Einkaufsliste = auf Ausgangsposition zurückfallen lassen; Mülleimer für Wegwerfen verwenden

Die Frage war, ob nach Anzahlung eine Einkaufsliste erst nach Rückfrage weggeworfen werden sollte. Aber da der Mülleimer schon da ist, kann man ihn ja auch nutzen.

**Comment by GWRon** [comment]
OK, also den PR auf den Masterstand aktualisieren, dann schauen, dass im Nachrichtenstudio weiter weggeworfen wird, im Studio allerdings ein "drop back" stattfindet und das Entfernen nur beim Fallenlassen auf den Muelleimer.

Eine "Nachfrage" bei angezahlten Einkaufslisten koennte man im Nachgang noch einbauen - bei den Nachrichten im Nachrichtenbuero gibts das allerdings auch nicht (klar, weniger "Kosten" ... )... es waere hier also nur stringend, ein "Wegwerfen ohne Bestaetigung" beizubehalten.
