### ISSUE TITLE
Studiokündigung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#536]
Aktuell kann ein eigenes Studio gekündigt werden, in dem noch ein Drehbuch liegt oder in dem gerade eine Produktion läuft.
In diesen beiden Fällen sollte das Kündigen grundsätzlich nicht möglich sein - man kann ja vorher immer das Drehbuch in den Koffer legen oder das Produktionsende abwarten. Die Prüfung "Drehbuch in Studio" sollte ausreichen, da das ja eine Vorbedingung für eine Produktion ist.

Da das erste eigene Studio scheinbar gar nicht gekündigt werden kann, sollte auch das Problem "kein Studio für Live-Produtkion" entschärft sein. Den Supersonderfall zwei Live-Produktionen zur selben Zeit (eine gesendet die andere mit festem Termin zur selben Zeit) würde ich weiterhin ignorieren.

**Comment by nittka** [comment]
Könntest Du einen Blick auf dieses Ticket werfen. Es sollte eigentlich eine Kleinigkeit sein, die Aktion zu unterbinden.

**Comment by GWRon** [comment]
Mir ist der Fehlerbericht hier durch die Lappen gegangen, sorry.

Also zum eigenen Studio: das Problem ist derzeit damit zwar umschifft, aber es hat nur "Größe 1" und was dann tun, falls eine Liveproduktion Größe 3 anfordert?
Man koennte nun ueberlegen, ob man sowas wie "erzwingen" einfuehrt - wenn eine Produktion "gezwungen wird", in einem kleineren Studio stattzufinden, gibt es einen Modifkator, der das Endergebnis abschwaecht: also von 3 auf 2 -> auf 75%, von 3 auf 1 -> auf 50% (oder aehnlich).

Die Kuendigung kann ich mir gerne anschauen  - kurz: hier einfach nur Unterbinden, dass ein Studio mit laufender Produktion gekuendigt wird.
Aus welchem Grund soll das auch fuer "in dem noch ein Drehbuch liegt" gelten? Koennte man nicht Studios mit "laufende Produktion/Planung" (also die Zeit zwischen zwei "angetriggerten" Produktionen von "alles was da ist produzieren") vermerken bzw das herausfinden --- und nur dort "blockieren"?

Wenn rein im Studio ein Drehbuch laege ... muesste man ja kuendigen koennen. 

Obwohl -- hier waere wieder der Sonderfall: Koffer ist voll und in dem zu kuendigenden Studio liegt noch ein weiteres Drehbuch.
Da ist es wohl doch einfacher, einfach beim Kuendigungsversuch zu sagen "Das Studio wird von dir noch aktiv benutzt. Beende erstmal dort laufende Produktionen bzw. entferne abgelegte Drehbuecher".

**Comment by nittka** [comment]
Genau wegen des Sonderfalls wollte ich das Kündigen bei Vorhandensein eines Drehbuchs generell unterbinden (geringster Aufwand). Den Fall Live-Produktion benötigt größeres Studio könnte man im Ticket Studiogrößen (#167) mit berücksichtigen.

**Comment by GWRon** [comment]
OK, also bauen wir einen Rueckgabewert ein, der sagt ob eine Kuendigung durchgefuehrt wurde (mit Hinweis auf "weil noch ein Drehbuch dort war") - und gleichzeitig auch eine "CanBeCancelled()"-Methode, die wir auch der KI zur Verfuegung stellen

Jetzt besteht nur die Frage - ob ein Studio ueber explizit die Drehbuecher "im Raum" Bescheid wissen muss (also TRoom kennt TScript ...) oder ob wir dem TRoom einen Flag mitgeben, dass es nicht gekuendigt werden kann - und/oder einen Flag, dass ein Nutzgegenstand im Raum platziert ist. Der Raum weiss dann nicht, dass es sich um ein Drehbuch handelt - ist auch nicht von Bedeutung. Der Flag sagt einfach: "Hol was auch immer aus dem Zimmer raus, dann kannst du kuendigen". Die "UI" hingegen kann einem ja dann sagen, dass es sich um ein Drehbuch handelt ... auch fuer die KI kann entsprechend uebermittelt werden, welches Drehbuch in welchem Studio "liegt".

**Comment by nittka** [comment]
Ein CanBeCancelled im Raum klingt für mich besser.
