### ISSUE TITLE
TVT.of_GetRandomAntennaCoordinateInPlayerSections() liefert keine Ergebnisse

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#544]
Im aktuellen Masterstand und auch mit der Optimierung liefert die obige Funktion keine verwertbaren Ergebnisse (nil im Original, die Koordinaten 0,0 mit der Optimierung).

* kommt man ggf. komplett ohne die Funktion aus, da ja auch komplett zufällige Koordinaten verwendet werden
* oder soll die Funktion repariert werden; erste kurzes Probieren deutet darauf hin, dass gar keine Kartenteile zurückgegeben werden, in denen man nach Zufallskoordinaten suchen könnte

**Comment by GWRon** [comment]
Das passiert, wenn man ein "local sections:TStationMapSection" hat und gleichzeitig ein "self.sections" ..-

**Comment by GWRon** [comment]
Ich habe hier gleich mal noch ein wenig "erweitert" und die TList mit einem Array ausgetauscht ... sollte ein paar Nanosekunden sparen (index-Zugriff)
