### ISSUE TITLE
Debugscreen Modifiers

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#559]
Es gibt ja schon eine Seite für die Anzeige von Modifier-Werten. Diese würde ich gern erweitern.
* Auflistung aller Werte für die vordefinierten Schwierigkeitsgrade und die entsprechenden Werte für den aktuellen Spieler
* ggf. Änderungsmöglichkeit für diese Werte, um Auswirkungen im laufenden Spiel ausprobieren zu können
* Auflistung, Anpassungsmöglichkeit weiterer Werte (GameRules...)

**Comment by nittka** [comment]
Es gibt nur wenige explizit gesetzte Modifier-Werte (GameConfig) - die angezeigten. Für alle anderen greift der Default (1.0). Wenn man den Default beim Abrufen persistiert, werden es so viele, dass nicht alle angezeigt werden können. Zwar ist eine Gruppierung technisch möglich - aber per default ausgeschaltet.

Bei Arbeiten an diesem Thema sollte zunächst die Debugseite "rausgezogen werden".

**Comment by GWRon** [comment]
Man koennte ueberlegen, die Modifier in einer Liste zu platzieren (aehnlich bspweise der Bundeslaender in der Semderkarte/Infobutton).

Auch waere theoretisch eine art "paging" moeglich....

Weiss nicht, wie wichtig die Anzeige ist

**Comment by nittka** [comment]
Es gibt nur wenige GameModifier mit Nichtstandardwert (aber sehr viele über den Code verstreute Abfragen). Und es gibt keine Übersicht, welche Modifier aktuell im Einsatz wären. Der Debug-Screen wäre eine Möglichkeit. Prio für diesen Teil niedrig.

Werte für Schwierigkeitslevel werden ja nun umgesetzt.
