### ISSUE TITLE
Namen für Antennen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#561]
Wie wäre es, statt des globalen Zählers, die Stationen nach Bundesland(Kürzel) + Zähler zu benennen. In der Tabelle hätte man dann bei vielen Sendern zumindest eine Vorinformation, wo der Sender steht.

**Comment by GWRon** [comment]
Dann braucht es fuer jedes Bundesland Abkuerzungen - und die jeweilige Lokalisierung, falls es dafuer Abweichungen gibt (glaube aber nicht).

https://www.destatis.de/DE/Methoden/abkuerzung-bundeslaender-DE-EN.html

**Comment by nittka** [comment]
Auf die Lokalisierung würde ich tatsächlich verzichten. Die Kürzel könnten direkt mit der Karte gepflegt werden.
