### ISSUE TITLE
[Dev] PublicImage-Screen mit detaillierten +/- Buttons

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#563]
Von PR #562 

@nittka:
> Kurz zum Image-Debug-Screen: Vielleicht kann man die Anpassung des Image auf den aktuell gewählten Spieler beschränken (Wechsel mit 1-4 ist ja leicht möglich). Dann wäre ein +/- für alle Zielgruppen (optisch) auch gar nicht so schwer umsetzbar.
Mein einziger aktueller Anwendungsfall für das Ändern des Image ist allerdings die Senderkarte (Geld+Image manipulieren, um Kabelvertragsabschluss zu prüfen...)

@GWRon:
> Ich hatte erst ueberlegt, einfach "+" und "-" neben den jeweiligen Zielgruppen zu ermoeglichen (muss ja nicht per "button" sein- einfach Maus"bereiche" + "klick"-Checks) ... Wenn das fuer dich so von Interesse ist, bau ich das heute Abend mal noch mit ein.

**Comment by GWRon** [comment]
Ist dieser Punkt nicht eigentlich schon umgesetzt?

**Comment by nittka** [comment]
Mir reicht die aktuelle Umsetzung. Ich denke, hier ging es darum, nicht nur das Image global anzupassen zu können, sondern gezielt für eine Zielgruppe. Das geht noch nicht.
Von mir aus kann das Ticket auch als won't fix zugemacht werden - Umsetzung nicht nötig.

**Comment by nittka** [comment]
Ich schließe das Ticket. Wenn weiterer Anpassungsbedarf besteht, gibt es ein konkretes neues.
