### ISSUE TITLE
Debug Build: KI-Guess immer 0

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#564]
Im aktuellen Masterstand ist die Zuschauervorhersage der KI in einem Debug-Build bei mir immer 0. Ohne Code-Änderung ohne Debug-Option sind die Werte plausibel.
(Laut Anzeige im Debug-Screen für die Programmübersicht)

**Comment by nittka** [comment]
Dieses Verhalten ist mit Commit 155902f Refactor debugscreen reingekommen. Vorher gab es auch im Debug-Modus Nicht-0-Werte.

**Comment by nittka** [comment]
Ursache ist der Aufruf guessedAudience = guessedAudience.MultiplyFloat in TaskSchedule Zeile 1011. Kommentiert man diese Zeile aus, kommen "Werte".
Explizites Setzen des Faktors 12 kommt im normalen Modus an, im Debugmodus ist der Faktor im BXM-Code immer 0.
(Ich habe noch nicht die neue Blitzmaxversion oder aktualisiserte Module; warum der Debugmodus einen Unterschied macht, verstehe ich trotzdem nicht)

**Comment by GWRon** [comment]
Du kannst ja fuer dich mal MultiplyString() reaktivieren..das war ja drin, weils in brl.Reflection da mal Fehlverhalten erzeugte...bei mir aber das nicht mehr nachvollziehbar war.

**Comment by nittka** [comment]
Und Reflection hat sich im Debug-Build anders als im normalen Build verhalten?

**Comment by GWRon** [comment]
Keine Ahnung ... aber ich meine explizit diesen Commit hier:
https://github.com/TVTower/TVTower/pull/514/commits/53a428a27da26393c497cea5fb99fbb54e64e09c
(einfach bei den Lua-Skripten nach "MultiplyFloat" suchen und dort "MultiplyString(tostring( ))" draus machen).

**Comment by nittka** [comment]
Und wichtig wäre wohl, dass der GitHub-Actions-Build dann auch die reparierte Variante verwendet, damit es in der Auslieferung keine Probleme gibt.

**Comment by GWRon** [comment]
Man muesste schauen was genau der bug ist/war - evtl ist es dieser "trifft nicht auf jedem Rechner"-Zu- bug den wir mit Dalli schon mal hatten - weswegen wir auf die "Long"-Time umgestiegen sind.

**Comment by nittka** [comment]
Problem trat nicht nur bei mir auf - entweder Fix oder (temporärer) Rückbau auf MultiplyString.

**Comment by GWRon** [comment]
OK, das Problem laesst sich hier ganz gut reproduzieren:
```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.Reflection

Type TTest
    Method Hello(f:Float)
        Print "Hello() f = " + f
    End Method
End Type

Local t:TTest = New TTest
Print "via direct:"
t.Hello(1.2345:Float)

Print "via invoke:"
Local m:TMethod = TTypeId.ForObject(t).FindMethod("Hello")
m.Invoke(t, [String(1.2345:Float)])
```

**Comment by nittka** [comment]
Vom TVT-Code her scheinen alle Varianten betroffen zu sein (1./2. Paramter, mit/ohne Defaultwert) - aber eben nur im Debug-Build. Im Releasebuild kommen die richtigen Werte an.

**Comment by GWRon** [comment]
Ich kann das auch temporaer "fixen" und wir korrigieren das dann, sobald ein offizieller Fix dafuer da ist (reflection.mod).
