### ISSUE TITLE
FirstToUpper bei RandomCity

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#568]
Bei der Erzeugung von zufälligen Stadtnamen wird der erste Buchstabe nicht (mehr?) groß geschrieben.

**Comment by nittka** [comment]
Das Problem ist mit Commit 434dedee5 reingekommen. (Mit etwas Geduld sieht man es beim Austauschen der Drehbücher im Debug-Screen - Kaffeefahrt nach..., Guten Morgen ...)

**Comment by GWRon** [comment]
Hatte ich alles getestet, dann aber den "length" Parameter rausgenommen und da wohl nicht aufgepasst.
