### ISSUE TITLE
Nachwirkung Image m/w

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#569]
Durch die neue Image-Aufteilung funktioniert gerade der Sammy und die Imageanpassung via Chat nicht. Statt der angekündigten x Prozent gibt es nur noch x/2.

**Comment by nittka** [comment]
Da bist Du mir mit dem Fix wohl ein paar Minuten zuvorgekommen ;-)

**Comment by GWRon** [comment]
Aellebaetsch :dagger: 

Musste vorher sogar noch "aufraeumen", da ich noch am "stationmap"-debug-screen dran bin

**Comment by nittka** [comment]
In Zukunft werde ich die Bugs erst einstellen, wenn ich die Lösung schon fertig habe ;-)

Ich mache diesen nochmal auf, da es noch eine weitere Nebenwirkung gegeben haben könnte. Mir scheint, die Zuschauerzahlen sind im Vergleich zu 0.7.1 ziemlich hochgegangen. Das merkt man nach dem Spielstart schon bei der Eröffnungsshow. Zum Vergleich habe ich auch noch im letzten Release und im aktuellen Masterstand um 20 Uhr (vorher nur Sendeausfall) Zwei wie Teer und Gänsefedern ausgestrahlt
* 0.7.1: 450.000 mögliche Zuschauer, Quote 27%, Zuschauer 120.000
* 0.7.2: 700.000 mögliche Zuschauer, Quote 25%, Zuschauer 170.000

Das Senderimage war jeweils 0%. Die so deutlich höhere Anzahl möglicher Zuschauer macht mich schon stutzig. 700000 bei 1.2Mio !?

**Comment by GWRon** [comment]
![image](https://user-images.githubusercontent.com/2625226/158427692-e555e149-8f9b-4505-b1df-85212c27783c.png)

![image](https://user-images.githubusercontent.com/2625226/158427745-785a0bef-a8b4-4d13-9666-f863aa1ffc75.png)


In 0.7.2 ist die initiale Reichweite bei mir 50% hoeher ... die anderen Werte sehen "sehr aehnlich" aus - natuerlich nur die Prozente, nicht die absoluten Zahlen ;D

**Comment by nittka** [comment]
Im Commit vor der WeightedAverage-Korrektur sind die Werte meiner Ansicht nach noch vergleichbar.

**Comment by nittka** [comment]
Der Quotenbildschirm und die Zuschauerinformation im Interface zeigen unterschiedliche Reichweiten an: 1.22 wie erwartet im Interface, 1.84 im Quotenbildschirm. Letzteres kann nicht stimmen, denn die Antenne hat nur eine Reichweite von 1.22

**Comment by GWRon** [comment]
Sollte wieder gehen... hatte faelschlich von 100% "nix" abgezogen (null-Variable) statt "frauen".
Wir hatten also bei jeder Zielgruppe 100% Maenner plus X% Frauen...
