### ISSUE TITLE
Männer/Frauen für Bonus bei Werbung nicht als Zielgruppe zählen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#573]
Bei der Berechnung des Zielgruppenbonus sollten die Zielgruppen Frauen und Männer nicht zählen - zumindest nicht, wenn es nur einen Bonusfaktor für Werbung mit Zielgruppe gibt.
Bestimmte Zahlen bei Kindern und Managern dürften viel schwieriger zu erreichen sein, als Männer und Frauen. Außerdem dürften bei einer angenommenen 50:50-Aufteilung die Mehreinnahmen aufgrund der Mindestzuschauerzahl hier schon attraktiv genug sein (ohne Zielgruppenbeschränkung wären doppelt so viele Zuschauer nötig gewesen, die mit dem Film beim anderen Geschlecht nicht erreicht worden wären).

Lässt man diese Zielgruppen raus, kann der Faktor für Werbung mit Zielgruppe erhöht werden und macht das gezielte Suchen nach Zielgruppenwerbung oder Filmen für eine bestimmte Zielgruppe interessanter.

**Comment by GWRon** [comment]
Es ist doch egal, wie die Zielgruppen aufgeteilt sind...ob 53 zu 47 (glaube 47,2% Frauen...)... Oder 10 zu 90.

Denn... Frauen gucken andere Filme als Maenner. Entsprechend ist eine "Frauen"-Anforderung relevant...da sie mit einem Erotikfilm schwerer zu erreichen ist, als mit einem Drama.

**Comment by nittka** [comment]
Was ist meine Intention? Eine Werbung mit Zielgruppe soll sich nicht nur durch die abhängig vom Zielgruppenanteil kleinere Mindestzuschauerzahl unterscheiden. Es soll einen *relevanten* Faktor bei der Prämie geben. Bei "Normalfilmen", die eine 50:50-Aufteilung bei den Zuschauern hat, könnte man Männer-/Frauenwerbung dann aber wie eine Werbung mit doppelter Mindestzuschauerzahl einsetzen, nur dass es eben mehr Geld gibt.
Zugegeben ist das für andere Zielgruppen nicht viel anders, aber aufgrund des viel geringeren Anteils an der Bevölkerung ist es eben erheblich schwieriger, die Werbung "optimal" einzusetzen (Werbung verlangt 5000 Jugendliche, es schauen aber 15000 zu - Verschwendung).

Und da das "optimal einsetzen" für Männer-/Frauenwerbung so viel einfacher als für andere Zielgruppen ist, schlage ich vor sich nicht als "Zielgruppenwerbung" zu zählen.

Ein alternativer Ansatz wäre, den Bonus für die Prämie vom Anteil der Zielgruppe an der Gesamtbevölkerung abhängig zu machen. Je weiter man von 50% gegen 0 geht, desto größer ist der Zuschlag.

**Comment by GWRon** [comment]
Ja der Zuschlag sollte eine Art Schwierigkeitsfaktor enthalten...der je nach Anteil an der Bevoelkerung ausfaellt.

Allerdings sollten Frauen und Maenner weiterhin eine moegliche Zielgruppe fuer Werbung sein. Sie sollte dann aber halt so gestaltet werden, dass die Anforderung "ueber den Durchschnitt" geht. Sprich ein Standardfilm-fuer-alle wuerde dann das Ziel nicht unbedingt erfuellen. Es braucht dann schon einen Actionfilm fuer Maenner oder einen Liebesfilm fuer Frauen.

**Comment by nittka** [comment]
Ich wollte auch gar nicht die Zielgruppen infrage stellen oder entfernen, sondern nur die Berechnung des Flags "handelt es sich um Zielgruppenwerbung" anpassen (kommt der Zielgruppenwerbungfaktor zu tragen); falls es nur einen "Modifier" für Zielgruppenwerbung gibt (wie aktuell der Fall). Falls die "Schwierigkeit der Zielgruppe" zusätzlich in die Prämienberechnung eingeht, kann das natürlich entfallen. (z.B. spontanes Bauchgefühl: Männer und Frauen Schwierigkeitsfaktor 1, Rentner, Arbeitslose und Hausfrauen 1.2, Manager 1.3, Jugendliche 1.4, Kinder 1.5; oder man berechnet den Faktor wirklich am Anteil der Bevölkerung).

**Comment by nittka** [comment]
Der Commit enthält erstmal eine naive Lösung (es gibt maximal eine Zielgruppe und Männer/Frauen zählen gar nicht). Besser wäre:
* x=Anteil der Bevölkerung, die zur Gesamtzielgruppe gehören
* je kleiner x (unter 0.5) ist, desto mehr vom limitedToTargetGroupMultiplier wird multipliziert

**Comment by nittka** [comment]
Man muss es nicht komplizierter machen als nötig. Es sollte auch ausreichen, pro Zielgruppe einen festen Faktor in die GameConstants zu packen.

**Comment by nittka** [comment]
Die Änderung im PR #554 wurde erstmal zurückgenommen, da auch für Männer und Frauen ein Bonus existieren soll. Vorschlag ist, (1-Zielgruppenanteil) * Modifier als Bonus zu geben. Dafür muss aber der Zielgruppenanteil festgelegt/ermittelt werden.
Vorschlag wäre für alle Zielgruppen feste Faktoren zu verwenden, anstatt sie dynamisch zu ermitteln. Die Unterschiede wären fast vernachlässigbar. Unklar ist aber der Umgang mit kombinierten Zielgruppen (wenn diese verwendet würden); z.B männliche Rentner.
Die Logik müsste hier nochmal geprüft werden (Flags mit und/oder verknüpft, also Männer + Rentner oder männliche Rentner).

**Comment by GWRon** [comment]
Wir haben doch feste Werte fuer die einzelnen Zielgruppen?

Koennen wir nicht auf die zurueckgreifen?

**Comment by nittka** [comment]
Dann muss ich die wohl mal suchen. Mir ist auch noch eingefallen, dass der Anteil nicht der einzige Faktor ist. Manche Zielgruppen haben auch ein größeres Zeitfenster, in dem sie fernsehen (Arbeitslose länger als Manager oder Kinder). Und die Prime-Time ist für Kinderwerbung nicht gut geeignet...

**Comment by nittka** [comment]
Erste einfache Umsetzung mit einem Faktor, der (allein) von der Zielgruppengröße abhängt, ist erfolgt.

**Comment by nittka** [comment]
Mit  obigem PR behoben. Bonus für Frauen/Männer fällt geringer aus als für Kinder/Manager.

**Comment by GWRon** [comment]
Die einfache Schwierigkeitsermittlung ist anhand der Bevölkerungsverteilung. Schwerer wird es, wenn man noch das Angebot an Filmmaterial mit reinnimmt (wenn es kein Managerprogramm gibt..is die Erfuellung sehr schwer).
Oder auch Images bei den jeweiligen Zielgruppen (schwerer zu ueberzeugen...vs gucken eh)

**Comment by nittka** [comment]
Ich denke, die Fernsehzeiten der einzelnen Gruppen sind schon vorhanden. Was ich meinte war die Berücksichtigung dieser Zeiten für die "Schwierigkeit" einer Werbung. D.h. selbst bei gleich großen Gruppen, kann die eine wesentlich schwerer zu erreichen sein, weil sie z.B. nur nachmittags fernsieht (wo die Grunderreichbarkeit aber auch wesentlich niedriger ist).

Ausgangspunkt für dieses Ticket war ja der "immer gleiche" Bonus für eine Werbung mit Zielgruppe. Mit der aktuellen Anpassung spielt die Größe der Zielgruppe eine Rolle aber noch nicht ihre "Schwierigkeit" bezüglich Fernsehzeiten. Das halte ich aktuell aber auch nicht für nötig.
