### ISSUE TITLE
Antennen mit unterschiedlichem Radius unterstützen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#582]
Einen Punkt, den ich beim Erweitern der Schwierigkeitslevel gern umsetzen würde, ist eine unterschiedliche Startreichweite. Das ließe sich auf verschiedene Arten erreichen:
* die Position der ersten Antenne ist gleich, aber die Radien unterscheiden sich, so dass die Reichweite variiert
* die Radien der Startantennen sind gleich, aber die Startposition wird zufällig ermittelt
* eine Kombination aus beidem

Die Zuschauerzahlen ändern sich im Laufe der Jahre und man kann daher schlecht mit fixen Startradien in der Levelkonfiguration arbeiten. Der Preis einer Antenne ergibt sich aus einem Fixpreis (auf Basis der Maximalreichweite in einem festen Radius) und einem variablen (aktuelle Reichweite im tatsächlichen Radius der Antenne). Aktuell wird in der DEV.xml die gewünschte Startreichweite für alle Spieler festgelegt und derselbe konstante Antennenradius aller Spieler wird initial ermittelt.

Aktuell habe ich folgendes Zielbild vor Augen:
* Level definiert "Basisradius" (ausschließlich für die Berechnung des Antennenpreises; aktuell konstant 20) - unabhängig vom eigentlichen Radius; damit lassen sich die Ausbaukosten zusätzlich steuern
* Level definiert Startreichweite
* Zu Beginn eines Spiels wird daraus die Position und der Radius der jeweiligen Startantennen ermittelt. (Fest im Code hinterlegte Positionen dürften schwer für alle möglichen Karten und Startjahre funktionieren. Fest in der Karte hinterlegte Positionen könnten funktionieren, aber gewürfelte Werte verlangen vom Spieler Anpassung bei der Ausbaustrategit)
* Wenn das Level zweier Spieler gleich ist, sind die Ergebnisse gleich (gleicher Radius, gleiche Position).
* Zwischen den Antennen aller Spieler gibt es eine möglichst große Reichweiteüberlappung (die Antennen stehen alle in derselben Region)
* Die Differenz der Radien der Antennen darf einen gewissen Wert nicht überschreiten, da das beim weiteren Ausbau eine zu große Benachteiligung bedeuten kann (RadiusLeicht 30, RadiusSchwer 10 ist auch nicht fair) - im besten Fall sind die Radien nur leicht unterschiedlich; dabei RadiusLeicht>=RadiusMittel>=RadiusSchwer
* Eine Änderung von Antennenradien im Laufe des Spiels würde ich im Zuge dieses Tickets noch nicht berücksichtigen. 

Ein Knackpunkt bei dieser Erweiterung ist die Berechnung der Überlappung der erreichten Zuschauer (und alles was damit zusammenhängt: Berechnung der möglichen und tatsächlichen Zuschauer etc.). Bei der Erstellung der Überlappungsinformation darf nicht mehr von einem festen Radius ausgegangen werden. Es muss der tatsächliche Radius einer Antenne verwendet werden.

Der zweite Knackpunkt wäre die Ermittlung der Startparameter (Position und Radius). Zu berücksichtigen ist dabei, dass die Startantenne in einem Bundesland liegen sollte, das groß genug ist, damit ein weitere Ausbau erfolgen kann, bevor man genug Geld hat, um in andere Bundesländer zu expandieren (zumindest in den Jahren bevor ein Antennenausbau ohne Lizenz in alle Bundesländer möglich ist).

Ich denke, Punkt 1 muss implementiert sein, bevor man sich der restlichen Dynamisierung widmen kann.

**Comment by GWRon** [comment]
Der groesste Knackpunkt ist, dass die Quotenberechnung ja Maerkte nutzt.
Maerkte fuer Personen in der Bevoelkerung, die von Spieler 1 exklusiv bedient werden, oder von Spieler 2, 3 bzw 4.
Aber auch Spieler 1 und 2 ohne 3 und 4, 2 und 3 ohne 1 und 4 usw.
Wenn man in einem Sendegebiet keinen Mitbewerber hat, bedeutet dies einen Bonus auf die effektive Attraktivitaet eines dort ausgestrahlten Programms (in der Not frisst der Teufel Fliegen.... Bevor Herr Mustermann garnix angucken kann, schaut er lieber den einzigen Sender im Angebot)
Klar, es gibt genug die dann die Kiste auslassen..aber eben nicht alle.

Du kannst ja einfach mal eine aehnliche Position finden..und die anderen drei dort platzieren...und dann Deine und deren Quoten beim Startprogramm vergleichen.


Diesem Punkt kann man nur entgehen, wenn man ein, zwei "oeffentlich rechtliche Sender" simuliert. Also gern als richtige Marktteilnehmer (mit Programmlizenzerwerb) oder als "Grundrauschen" mit einfacher simulierter Programmqualitaet (keine Titel, Schauspieler...einfach nur "Programmattraktivitaet").
Damit wuerde man auf allen Maerkten und Kanaelen "Konkurrenz" haben..mal mehr, mal weniger.
Das kann gerne in einem eigenen Ticket eroertert und angegangen werden. Sobald das existiert, besteht kein Zwang mehr, an einem gemeinsamen Standort zu starten (auch wenn die Hochhausthematik dazu ja gut passt).

**Comment by nittka** [comment]
Ich finde, die Marktargumentation für die Startpunkte ist gar nicht so problematisch. Einerseits hat ja ein Spieler sofort auch einen Vorteil, wenn er eine weitere Antenne in Betrieb nimmt (exklusiver Markt). Das "Problem" besteht also schon jetzt. Wenn die Startzuschauerzahlen unterschiedlich sind, gibt es automatisch Bereiche, in denen nicht alle Sender aktiv sind. Zudem war das Zielbild ja, dass die Überlappung am Start möglichst groß ist; im einfachsten Fall also gleicher Startpunkt mit unterschiedlichen Radien oder die Spieler mit Schwierigkeitslevel leicht starten in einer Metropole und ein Spieler mit schwer hat denselben Radius, liegt aber im Randgebiet.

Der technische Knackpunkt ist also, die korrekte Marktberechnung mit variablen Radien, der fachliche Knackpunkt die Ermittlung der Startparameter.

Zum Grundrauschen: Ich hätte angenommen, dass in der Berechnung der potentiellen Zuschauer zu einer Zeit und in der Ermittlung der Einschaltquote schon berücksichtigt ist, dass nicht alle einschalten oder was anderes machen. Die Summe der Einschaltquoten ist ja nicht immer 100%. Weitere simulierte Sender sollten also nicht nötig sein; bzw. bräuchten die vorhandenen Parameter nur angepasst werden.

**Comment by GWRon** [comment]
Die Berechnung mit dynamischen Radien sollte machbar sein...am Ende werden ja einfach nur die Kreise "eingemalt" und davon betroffene "x,y"-Koordinaten gespeichert. Ob der Radius da 20 oder 30 ist .... sollte keine Rolle spielen


@Grundrauschen
Nun, es gibt einfach "Zeiten" in denen Zielgruppen zuhause sind. Dann kommt noch das Wetter, was etwaige Manipulationen vornimmt ("schoenes Wetter = Leute sind draussen").
Simulierte Sender haetten aber ein leicht varierendes Angebot ... haben also mal eine Sendung fuer Rentner, mal einen Film fuer Frauen ... dies kann im Groben und ganzen "fix" sein (also Morgenmagazin, Nachmittagstalk) aber dennoch gibt es hier und da Abweichungen - mal ein Film fuer Rentner, mal Kinderprogramm, mal was altes, mal was neues.
Das muss man nicht alles simulieren ... aber koennte die "Zielgruppenspezifische Attraktivitaet" entsprechend generieren. Es braucht dann keinen Film - es kommt einfach nur eine Attraktivitaet raus, die bei der Quotenberechnung  mit einberechnet wird.

Vereinfacht ausgedrueckt: Fuer jede Stunde (oder gern auch mal 2 oder 3 in Folge - also "Film") wird fuer die 1-2 simulierten Sender eine Programmattraktivitaet (10% fuer maennliche Kinder, 12% fuer weibliche Kinder, 8% fuer Manager, ...) "ausgewuerfelt" (oder halt doch irgendwo hergeholt...also 90% fix und 10% dynamisch) .... und die wird dann bei der Quotenberechnung mit eingewoben.
Das ist meiner Meinung nach nicht das gleiche, als einfach nur 10% der Leute nicht vor den TV-Empfaenger zu setzen.

DENN ... ist dein Programm besser als das des simulierten Senders, schauen sie eher Dich, ist das der Konkurrenz schlechter, verlieren die Zuschauer an den "oeffentlich rechtlichen".

Es ist nicht das gleiche, einfach einen kleineren Kuchen zu backen und durch vier zu teilen - oder einen großen Kuchen zu machen und dann durch sechs.

**Comment by nittka** [comment]
Keine Kontra. Ich wollte nur ausdrücken, dass aus meiner Sicht keine vollständige Simulation weiterer Sender nötig ist. Eine Manipulation der Zuschauergruppen sollte ausreichen. Wie feingranular und konsistent (Film dauert 3 Stunden, also "gleiche" Werte für diesen Zeitraum) das dann ausgestaltet ist, ist eine andere Frage.

**Comment by GWRon** [comment]
Bezueglich unserer Unterhaltung ueber "globaler Antennenradius in Berechnungen":

Das sollte nur diese Methode hier betreffen (in game.stationmap.bmx):
```BlitzMax
	Method GetAntennaShareGrid:Byte[]()
...
			Local antennaStationRadius:Int = GetStationMapCollection().antennaStationRadius
			Local antennaStationRadiusSquared:Int = antennaStationRadius * antennaStationRadius
...
			For Local map:TStationMap = EachIn GetStationMapCollection().stationMaps
...
					For Local station:TStationAntenna = EachIn map.stations
...
						circleRectX = Max(0, stationX - antennaStationRadius)
						circleRectY = Max(0, stationY - antennaStationRadius)
						circleRectX2 = Min(stationX + antennaStationRadius, rect.GetW()-1)
						circleRectY2 = Min(stationY + antennaStationRadius, rect.GetH()-1)
...
						For posX = circleRectX To circleRectX2
							For posY = circleRectY To circleRectY2
								'left the circle?
								If CalculateDistanceSquared( posX - stationX, posY - stationY ) > antennaStationRadiusSquared Then Continue
```

Wenn also die zwei `local antenna...` entfernt und unterhalb der Zeile `For local station` dafuer folgendes platziert wird:
```BlitzMax
						Local antennaStationRadius:Int = station.radius
						Local antennaStationRadiusSquared:Int = station.radius * station.radius 
```
Dann sollte es die "globale" nur noch nutzen, wenn "ohne" Antenne was von der Senderkarte abgefragt wird ("Was ist der Zuwachs bei X,Y, (optional: radius=....)")

**Comment by GWRon** [comment]
Wie schaut es hier aus?

**Comment by nittka** [comment]
Ausgangspunkt war ja, für unterschiedliche Schwierigkeitslevel die Antennenreichweite unterschiedlich machen zu können. Aktuell halte ich das nicht mehr für nötig. Es sollte ausreichen, die Ausstrahlungs- und Anschaffungskosten sowie die Einnahmen anzupassen.
Als Idee würde ich das Ticket aber offen lassen.

**Comment by nittka** [comment]
Abweichend vom Startkommentar würde ich die unterschiedlichen Radien nun nicht mehr vom Schwierigkeitsgrad abhängig machen - da gibt es mittlerweile genügend andere Stellschrauben.
Wichtig wäre hingegen, dass der Radius einer neuen Antenne im Laufe der Jahre immer mal wieder neu berechnet wird. Gestartet im Jahr 1985 gehen die Zuschauerzahlen für den Startradius sonst so stark runter, dass sich Antennen überhaupt nicht mehr lohnen.

Die Frage wäre wann eine solche Neuberechnung stattfinden soll und auf welcher Basis. Denkbar wäre hier den Code für die Berechnung des Startradius wiederzuverwenden. Wenn die Bevölkerungszusammensetzung berechnet wird, wird auch ein hypothetischer Startradius berechnet. Wenn der 5 Pixel gößer ist als der aktuelle, wird der Radius neu gesetzt. Ab dann werden neue Antennen mit diesem Radius gebaut.

**Comment by nittka** [comment]
Nach den ersten Testspielen mit der neuen Kartenlogik sehe ich die Notwendigkeit, sich ändernder Radien nicht mehr. Der Initialradius sollte sich am Startjahr orientieren - das haben wir ja schon.
Es ist wichtiger, dass die Kaufpreisberechnung und die für die laufenden Kosten besser an die sich ändernde Abdeckung durch Antenennen angepasst wird.
