### ISSUE TITLE
Einnahmenentwicklung Werbeverträge

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#583]
Bei der Analyse der Preisentwicklung der Filme habe ich mir beispielhaft auch die Entwicklung der Werbeeinnahmen angeschaut - nur beispielhaft für Berliner Pilsner und Fluchomat. Dass die Einnahmen pro Zuschauer nicht 1:1 mitwachsen können (innerhalb eines Reichweitelevels), ist mir klar, aber ein mulmiges Gefühl bei den aktuellen Werten habe ich dennoch.
* 1.2Mio Zuschauer: Bier 80K/34K€ , Fluchomat 160K/46K€
* (1.8Mio Zuschauer: Bier 120K/55K€)
* 2.5Mio Zuschauer: Bier 160K/70K€, Fluchomat 320K/95K€
* 5.xMio Zuschauer: Bier 340K/150K€, Fluchomat 675K/200K€

Während sich die benötigte Zuschauerzahl also zwischen Bier und Fluchomat verdoppelt, ist der Faktor der Einnahmen pro Spot 1.3. Betrachtet man das nur innerhalb einer Zuschauerreichweite, wirkt das noch nicht so seltsam. Vergleiche ich aber Fluchomat bei einer Reichweite von 1.2 Mio mit Bier bei 2.5 Mio, werde ich stutzig...
Ich muss die gleiche absolute Zuschauerzahl erreichen. Bei doppelt so vielen potentiellen Zuschauern ist das aber **wesentlich** einfacher und ich bekomme dafür **gleichzeitig** 50% mehr Geld !? Und diese Verhältnisse bleiben so bestehen. Finanziell scheint es gar keinen echten Anreiz zu geben, schwierige Werbung zu schaffen.

Vergleiche ich Fluchomat bei 1.2Mio mit Bier bei 1.8Mio sieht es ebenso seltsam aus. Ich erreiche potentiell 50% mehr Zuschauer, benötige weniger Zuschauer (was leichter ist), bekomme aber trotzdem mehr Geld dafür...

Man hat natürlich bei mehr Zuschauern auch mehr laufende Kosten. Für die ersten zusätzlichen 600K Zuschauer waren das im Testspiel 80K€ pro Tag. Mit 2 Blöcken Bierwerbung habe ich dieses Geld aber schon wieder rein, d.h. 22h lang kann ich mit gleicher Zuschauerzahl mehr Geld verdienen (oder mit höhrer noch mehr).

**Comment by nittka** [comment]
Ich habe lokal etwas rumgespielt. Abgesehen von einem Bug in der Berechnung der Werbeeinnahmen würde ich die Berechnung leicht anpassen. Kurzzusammenfassung: Finanziell sind die laufenden Senderkosten und die Werbeeinnahmen die beiden Hauptfaktoren. Nachrichten, Lizenzkosten, Eigenproduktion, Geschenke und Senderausbaukosten können in einer vereinfachten Betrachtung vernachlässigt werden (zu klein, einmalig, nicht essenziell) und werden vom Gewinn bezahlt, der sich aus der Differenz aus Senderkosten und Werbeeinnahmen ergibt.
Entwickeln sich beide linear wie bisher, wird der Gewinn immer größer und der Ausbau geht immer schneller. Aktuell wird das durch die Deckelung der Werbeeinnahmen pro Spot abgefangen, an der sich viele Spieler (zurecht) stören.

Mein Vorschlag ist, den Deckel komplett abzuschaffen und stattdessen die Werbeeinnahmen nicht mehr linear ansteigen zu lassen. Ab einer gewissen "Marktsättigung" (z.B. 10% der Reichweite), verdoppeln sich die Werbeeinnahmen pro Block nicht mehr bei einer Verdoppelung der Reichweite. Stattdessen muss man die Reichweite zum Beispiel vervierfachen, bevor sich die Einnahmen verdoppelt haben. Faktisch hat man damit noch immer eine Deckelung, aber Schrottwerbung liefert pro Block eben nicht dieselben Einnahmen wie gute.

Im Zuge des Umbaus der Schwierigkeitsgrade könnte man so eine nichtlineare Basiskurve definieren und dieser je nach Schwierigkeitsgrad wie bisher einen Faktor mitgeben - und den festen Deckel wäre man sofort los. Den linearen Anstieg bis zu einem Schwellwert würde ich drinlassen, damit der frühe Ausbau unterstützt wird.

Man könnte noch damit experimentieren, die Mindestzuschauerzahlen mit steigender Reichweite prozentual zu erhöhen. Man erzeugt damit zwar auch höhere Werbeeinnahmen, zwingt den Spieler aber auch zu einem besseren Programm, da im Grenzfall für dieselbe Werbung eine höhere Einschaltquote nötig ist.

**Comment by GWRon** [comment]
Das nichtlineare Ansteigen hatten wir frueher drin..dazu hatte ich bei dig/base.util.math... logistische Funktionshelfer integriert...

Die sind aehnlich dem Wurzelquotienten eine Funktion die schnell ansteigt und dann abflacht um gegen einen Zielwert zu streben.

Im Zuge von Gast2s Balancing kam es zu dem linearen Vorgehen.
Ich bin selbst eher ein Freund von "Rabatten" und "zw. 80.000 und 90.000 ist der Unterschied essenzieller als zwischen 8 und 9 Millionen".

**Comment by nittka** [comment]
Codemäßig ist der nichtlineare Anstieg immer noch drin. Aber Typfehler bei der Berechnung (Division von Integern statt Floats) etc. führen dazu, dass das Ergebnis praktisch linear ist. Ein wichtiger Knackpunkt sind aber die festen Deckel, die störend auffallen. Ein guter Werbeblock bringt 1Mio, und ein weiterer Senderausbau führt nur dazu, dass mit schlechter Werbung auch zu früheren Sendezeiten 1Mio an Einnahmen erreicht werden können.

**Comment by nittka** [comment]
Deckel ist entfernt. Profitzuwachs nimmt mit steigender Reichweite ab.
