### ISSUE TITLE
Bug Sammy-Belohnung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#585]
Im Forum wurde gemeldet, dass die Sammy-Belohnung (Geld und Image) nicht funktionieren. https://www.gamezworld.de/phpforum/viewtopic.php?pid=89715#p89715

Unter Windows habe ich reproduzieren können, dass das Geld tatsächlich nicht ausgezahlt wird. Die Image-Punkte hingegen werden gutgeschrieben. Test unter Linux steht noch aus. Beim Reparieren sollte nochmal geprüft werden, dass der "Finish"-Mechanismus im Debug-Screen identisch mit dem im normalen Spiel verwendeten ist.

**Comment by GWRon** [comment]
In a265c67248cf83b76900e77d6e2b2e99bd985846 gefixt
