### ISSUE TITLE
Handbuch öffnet sich nicht / Text verschwindet

### ISSUE THREAD

**Issue by Pampelmops** [TVTower/TVTower#587]
Version 0.7.2, Windows 64

Mit dem Handbuch sind zwei Probleme aufgetreten.

1. Wenn man zum ersten Mal ins Büro geht, kommt ein Hilfetext mit dem Button für das Handbuch. Wenn man dort drauf drückt, kommt folgende Fehlermeldung: 
![grafik](https://user-images.githubusercontent.com/82060856/161401395-4ba7e0c6-6f24-4c47-8378-8df6b7e01f30.png)

2. Ich habe im Hauptmenü über F1 das Handbuch erreicht. Die erste Seite wurde regulär angezeigt. Beim Runterscrollen kam kein weiterer Text und beim erneuten Hochscrollen, wurde der vorher angezeigt Text abgeschnitten:
![grafik](https://user-images.githubusercontent.com/82060856/161401463-1ae7442c-e3fc-4e5f-acdf-bf7dfc744947.png)

**Comment by nittka** [comment]
Vielen Dank für die Meldung. Ich kann das Problem mit Win64, Win32 und auch unter Linux bestätigen. Das Handbuch wird nicht korrekt angezeigt. Scrollen mit Pfeiltasten und PageUp/Down sollte eigentlich auch gehen.
Zudem werden bei F1 in den Räumen nicht die raumspezifischen Hilfetexte angezeigt. Hier ist irgendwas fundamentales kaputt gegangen.

**Comment by GWRon** [comment]
Ich habe im Discord den Bug schon bestaetigt. 

Schaue mir das an.

**Comment by GWRon** [comment]
Der Fehler tritt auch schon in der v0.7.2 auf .. es koennte sich um einen Bug im Compiler/generierten Code handeln.
Oder meine "Bitmapfont"-Klassen haben einen Fehler der in Kombination mit dem Compiler zu einem Problem fuehrt. 

Wenn ich die `parseInfo:STextParseInfo`-structs nicht per Referenz uebermittle, laeufts.

**Comment by nittka** [comment]
Für mich sieht es so aus, als würde es demnächst nochmal eine Bugfix-Version geben. Da der Entwicklermodus nun standardmäßig deaktiviert ist (machst Du das manuell beim Zusammenbauen der Distribution?), würde ich das Handbuch dahingehend nochmal gegenlesen.

**Comment by GWRon** [comment]
Der Entwicklermodus ist "haendisch" ausgeschalten.

Der Bug ist denke ich im Compiler... da ich Probleme hab hier was zu debuggen. Nehme ich die " var"-pass-by-reference-Sachen raus, dann zeigt es mir den Text an ... aber natuerlich miesere Performance (da jedesmal die Blocktextinformation kopiert wird) und ploetzlich liefern die Zeilen im Startmenu keine Dimensionen mehr zurueck (die Forenlinks etc sind "aufeinander")

**Comment by nittka** [comment]
Willst Du dieses Ticket offen lassen, wegen der eigentlich ungewollten Änderung von Struct nach Type? Denn zumindest das Handbuch funktioniert ja jetzt wieder.

**Comment by GWRon** [comment]
Wir (@davecamp und ich) haben eine Weile an dem Bug gesessen ... viel Grübelei später und es scheint, als wenn man lieber keine "objekte" in structs unterbringt. (dynamische) Arrays sind allerdings Objekte. Und so sind die Einträge der Arrays nicht vom GC "geschützt" worden und gingen Richtung Nirvana.

Brucey wird nun wohl den Compiler entsprechend anpassen und die Objektnutzung in structs verhindern. Man kann zwar auch manuell Objekte dem GC zum managen übergeben (GCRetain(obj)) aber das brauchen wir denke nicht erst umsetzen. Man könnte statt Arrays eigene Speicherblöcke belegen usw .... 
Aber dank meiner lokalen Umbauten, wird das eh nicht viele der Structs (bzw nun Types) brauchen ... und die werden "wiederverwendet".
