### ISSUE TITLE
Reproduzierbarer Segmentation Fault bei Senderkauf

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#599]
Ich bin gerade dabei, den Antennenkauf der KI anzupassen. Für Tests (wo werden die Antennen platziert) habe ich die Kauf-API direkt bei der Analyse angesprochen. Wenn ich dabei zwischen den API-Aufrufen nicht warte, kommt es nach ca. 15 Aufrufen *immer* zum Segmentation Fault; allerdings nur im regulären Build - im Debug-Build tritt der Fehler nicht auf.
Branch mit einem reduzierten Beispiel: stationSegFault
* Spiel starten
* /dev exec script
* Debugansicht Commands
* KI für Spieler 1 aktivieren
* direkt den StationMap-Task anstoßen
* bei mir Absturz mit Segmentation Fault nach Kauf der 15. Antenne

Kannst Du dieses Problem bei Dir reproduzieren? Da der Fehler im Debugbuild nicht auftritt, hättest Du eine Vermutung, welche Codeteile Verursacher sein könnten (neue Arraygröße nach x Erweiterungen führt zu parallelem Zugriff...)?
Da der Fehler schon beim Kauf erfolgt, kann ja eigentlich nicht die Marktberechnung ursächlich sein. Die dürfte ja erst erfolgen, wenn der Sender wirklich steht.

Ein anderer Bug, der mir dabei aufgefallen ist: die KI könnte Antennen leicht außerhalb der Karte kaufen. Ggf. hätte sie dann sogar kostenlos zusätzliche Zuschauer (Preis negativ aber positive Reichweite).

**Comment by GWRon** [comment]
In Debugbuilds werden Objekte "laenger" behalten -- sind also noch an "Ort und Stelle" - das koennte vor Segfaults schuetzen.

![image](https://user-images.githubusercontent.com/2625226/163769113-80a9d758-eaed-4dcd-bec8-9c503e963e82.png)

Bis auf einen enormen Lag (hab denke so 20x auf den Stationmap-Task geklickt ... 1000 Sendemasten mit Tooltips :D
Gabs keinen Absturz -- unter Linux, kompiliere gerade alles auf dem alten Windowslaptop mit der "release" BlitzMax-Fassung.

**Comment by GWRon** [comment]
Im Zweifel --- und gut "zu haben":

- habe 7zip im Standardverzeichnis installiert
- lad dir ne curl.exe, schieb die Datei in ein neues Verzeichnis 
- platziere folgende .bat-Datei daneben: https://gist.github.com/fightlessbirds/1e74565faa32e8e514294c6752625a31
- fuehre die .bat aus (gern auch aus "cmd", damit du den Verlauf siehst)
  - es laedt das letzte Windowsrelease
  - und laedt auch Module, BCC, BMK
  - kompiliert das ganze
  - am Ende hast du ein neues BlitzMaxNG-Verzeichnis was dem Stand von "heute" entspricht

Wenn es damit nicht mehr abstuerzt, war es ein Bug in NG :)

**Comment by GWRon** [comment]
Windows - "official release" ... absturz (kein segfault... spiel steckt fest und Musik spielt immer die gleichen "50 ms" ab)

**Comment by GWRon** [comment]
windows - "latest release" - absturz

**Comment by GWRon** [comment]
Es stuerzt uebrigens innerhalb des Eventhandlings ab ... vom Event der dort in "AddStation" getriggert wird ...
Was mit Sicherheit zum Thema "threadsicherheit" fuehren wird ... um an meine dort getaetigten "koennte noetig sein" Aussagen zu erinnern.

**Comment by GWRon** [comment]
Ok ... denke ich habs schon seehr seehr stark eingegrenzt :-)

Ich wette Du hast bei dir "SFX" nicht gemuted?

Hier mal was wohl passiert:
- Antenne wird gekauft -> `Method AddStation:Int(station:TStationBase, buy:Int=False)`
- `AddStation()` triggert `TriggerBaseEvent(GameEventKeys.Stationmap_AddStation, New TData.Add("station", station), Self )`
- Der Event wird von main.bmx `Function StationMap_OnAddStation:Int(triggerEvent:TEventBase)` verarbeitet
- `StationMap_OnAddStation()` erstellt nun eine Toastmessage ("Neue Antenne im Bau")
- Erstellte Toastmessages erzeugen ein entsprechendes Event `TToastMessageCollection.eventKey_ToastMessageCollection_onAddMessage`
- auf dieses Event hoert main.bmx `onToastMessageCollectionAddMessage()`
- und dort drin wird ... ein Sound abgespielt ("neues Fenster ploepp")

Und das ... sorgt fuer den Absturz.

Unter Linux hab ich meine SFX immer "mute" ... und gemutete SFX spielt die Engine gar nicht erst ab ... ergo kein Crash.

**Comment by GWRon** [comment]
bei Key_Y reicht nun das fuer den Absturz:
```
				For local i:int = 0 until 15
					print "playing " + i
					AppEvents.SimpleSoundSource.PlayRandomSfx("gui_open_window")
				Next
```

Hab schon paar Mutexe reingemacht - glaube der Fehler ist "grundliegender" (mein Audio-"engine"-Zeug oder gar in den Backends)

**Comment by GWRon** [comment]
```
SuperStrict
Framework Brl.StandardIO
Import Brl.Audio
Import Audio.AudioSDL
Import Brl.OGGLoader
Import Brl.GLMax2D


Graphics 800,600

Global test:TSound=LoadSound("mein audio.ogg") ',SOUND_LOOP)

For local i:int = 1 until 17 '18 will segfault ...
	Local channel:TChannel = AllocChannel()
	if not channel then print "channel #"+i+ " failed."
	print "playing sound #"+i+"."
	PlaySound(test, channel)
Next

Repeat
	Cls
		DrawText("playing ?", 0,0)
	Flip 0
Until AppTerminate() or KeyHit(KEY_ESCAPE)
```
erhoehe auf 18 (also dann 17 sounds) ... und du bekommst n Segfault.

Da wir schon andere Kanaele offen hatten, reichen im obigen beispiel halt schon "10" von den "gui_open_window".

**Comment by GWRon** [comment]
Ein erster Fix waere - manuell die Maximale Anzahl an "voices/streams" fuer Soloud (Audio backend) hochzusetzen:
```
Local driver:TSoloudAudioDriver = TSoloudAudioDriver(GetAudioDriver())
if driver then driver._soloud.setMaxActiveVoiceCount(64)
```
Das waere aber erstmal nur zur Absturzvermeidung :D


Weiterhin sollten wir ueberlegen, ob wir fuer bestimmte "playlists" Limits einfuehren ... damit wir eine "Kackophonie" vermeiden. Also bei 10x Geldeingang in 100ms brauchst du nicht 10 Audioeffekte mit 10ms Versatz.
Eventuell koennte man einfach abspeichern, wann ein SFX "getriggert" wurde - und dann je nach Bedarf die Ausspielung verhindern ("wenn letzter Zeitpunkt < 100 ms, dann ignorieren") ?

**Comment by nittka** [comment]
Gibt es überhaupt Playlists, bei denen gleichzeitiges mehrfaches Abspielen sinnvoll wäre (abgesehen von Überblenden)?

**Comment by GWRon** [comment]
Playlist heisst ja nur... mehrere Varianten zur Auswahl.
Und es koennen ja verschiedene Tueren geschlossen werden ... Gleichzeitig.

**Comment by nittka** [comment]
Ich habe bei mir Musik und SFX mal im Spiel deaktiviert (vorher habe ich einfach nur den Rechnerlautsprecher leise gemacht). Danach fliegt der Segmentation Fault nicht mehr sofort. Wenn ich als Nicht-KI im obigen Szenario aber auf die Karte gehe und vorspule, kaufen die KIs irgendwann Sender. Die tauchen dann live auf der Karte auf und es gibt irgendwann einen Segmentation Fault - wahrscheinlich Multi-Threading-Problem beim Listenupdate in der GUI.

Da die meisten Spieler nicht dauerhaft vorspulen, wird der "Channel-Segmentation-Fault" wohl nicht das Hauptproblem sein - schade eigentlich.

Ggf. sollte man die Soundeffekte ab einer bestimmten Geschwindigkeit überhaupt komplett unterdrücken - sie liefern da ja kaum Mehrwert.

**Comment by GWRon** [comment]
> Ggf. sollte man die Soundeffekte ab einer bestimmten Geschwindigkeit überhaupt komplett unterdrücken - sie liefern da ja kaum Mehrwert.

Ich denke man koennte im FastForward - bzw ab einer bestimmten Geschwindigkeit ueberlegen die SFX auszublenden.
Die Alternative ist aber wirklich, einfach bestimmte Soundeffekte nur "aller x Millisekunden" zu erlauben. Da dies "Echtzeit" ist, spielt die Spielgeschwindigkeit (bzw der Grund fuer die Vielzahl an Effekten) keine Rolle.

**Comment by GWRon** [comment]
> Ich habe bei mir Musik und SFX mal im Spiel deaktiviert (vorher habe ich einfach nur den Rechnerlautsprecher leise gemacht). Danach fliegt der Segmentation Fault nicht mehr sofort. Wenn ich als Nicht-KI im obigen Szenario aber auf die Karte gehe und vorspule, kaufen die KIs irgendwann Sender. Die tauchen dann live auf der Karte auf und es gibt irgendwann einen Segmentation Fault - wahrscheinlich Multi-Threading-Problem beim Listenupdate in der GUI.

```
			If KeyManager.IsHit(KEY_Y)
				For local pID:Int = 1 to 4
					GetPlayer(pID).GetFinance().CheatMoney(500000000)
					GetPlayer(pID).GetPublicImage().ChangeImage( New TAudience.InitValue(50.0, 50.0))
				Next
'				DebugScreen.DEV_SetPlayerAI(1, True)
'				GetPlayer(1).playerAI.AddEventObj( New TAIEvent.SetID(TAIEvent.OnChat).AddInt(1).AddString("CMD_forcetask StationMap 1000").AddInt(CHAT_COMMAND_WHISPER))
				GetPlayer(2).playerAI.AddEventObj( New TAIEvent.SetID(TAIEvent.OnChat).AddInt(1).AddString("CMD_forcetask StationMap 1000").AddInt(CHAT_COMMAND_WHISPER))
				GetPlayer(3).playerAI.AddEventObj( New TAIEvent.SetID(TAIEvent.OnChat).AddInt(1).AddString("CMD_forcetask StationMap 1000").AddInt(CHAT_COMMAND_WHISPER))
				GetPlayer(4).playerAI.AddEventObj( New TAIEvent.SetID(TAIEvent.OnChat).AddInt(1).AddString("CMD_forcetask StationMap 1000").AddInt(CHAT_COMMAND_WHISPER))
```
Dann wartet man nicht all zu lange...

**Comment by GWRon** [comment]
Eine Alternative waere noch, dass die derzeitig "game.screen.stationmap.bmx"-Event handler bei "CurrentThread() <> MainThread" den Event nicht behandeln, sondern gezielt an sich selbst erneut losschicken - aber mit der Limitierung auf den "channel = 1" (Systemthread/Hauptthread).
Dazu muessten die Events natuerlich "kopiert" werden (Data koennte man "sharen").

**Comment by GWRon** [comment]
Die Alternative laesst sich so umsetzen:
```
	Function OnChangeStation:Int( triggerEvent:TEventBase )
if triggerEvent.GetData().GetInt("isCopy") = 1 then print "OnChangeStation received copy"
		if CurrentThread() <> MainThread()
print "OnChangeStation redirect to main thread"
triggerEvent.GetData().AddNumber("isCopy", 1)
			TriggerBaseEvent(triggerEvent.GetEventKey(), triggerEvent.GetData(False), triggerEvent.GetSender(), "TScreenHandler_StationMap", 1)
			Return False
		EndIf
```

bzw "clean":
```
	Function OnChangeStation:Int( triggerEvent:TEventBase )
		if CurrentThread() <> MainThread()
			TriggerBaseEvent(triggerEvent.GetEventKey(), triggerEvent.GetData(False), triggerEvent.GetSender(), "TScreenHandler_StationMap", 1)
			Return False
		EndIf

		'do nothing when not in a room
		If Not currentSubRoom Then Return False
...
	End Function
```

sowie:
```
	Function OnChangeStationMapStation:Int( triggerEvent:TEventBase )
		if CurrentThread() <> MainThread()
			TriggerBaseEvent(triggerEvent.GetEventKey(), triggerEvent.GetData(False), triggerEvent.GetSender(), "TScreenHandler_StationMap", 1)
			Return False
		EndIf
	
		'do nothing when not in a room
		If Not currentSubRoom Then Return False
...
	End Function
```

Die Aenderungen schicken den Event erneut auf Reise ... aber Diesmal kann nur eine "TScreenHandler_StationMap" (bzw eine Instanz davon) den Event empfangen, die "1" sorgt dafuer, dass dies nur im Mainthread geschieht.

in meinem Test gab es da nun keinen Absturz - aber bei sowas muss man dann wohl aufpassen, keinen "nicht GUI"-Code auszuschalten (bzw zu verzoegern).

**Comment by GWRon** [comment]
Und eine weitere Loesung bestuende in diesem Fall darin..die GUIwidgets threadsafe zu machen..also das sortieren etc zu mutexen. Gleiches gilt fuer Elemente in GUIlisten usw. ..also alles wo nen array, ne liste... Genutzt wird

**Comment by GWRon** [comment]
@nittka : 
Welchen Weg wuerdest Du bevorzugen?

**Comment by nittka** [comment]
Kurzfristig wird es keine allumfassende Lösung geben. Ein Ansatz wäre auch, dass die GUI gar nicht auf den "Originalobjekten/-Listen" arbeitet, sondern für die Anzeige Kopien anfertigt. Der Senderkauf wird nicht die einzige Stelle sein (bei mir auch schon mal Absturz am ersten Tag, wo wohl weniger Sender gekauft werden).
Im Gegensatz zum Programmplaner wird man sich auf der Karte ja nicht ständig und ewig herumtreiben und die Anzahl der Änderungen pro Zeiteinheit dürfte auch überschaubar sein. D.h. von der Performance her dürfte es OK sein, für die Anzeige der Antennen Kopien der Listen anzufertigen.

Lokal überall Mutexe einzubauen bedeutet ziemlich viel Codedopplung. Schön wäre eine performante ConcurrentTList, die Getter, Adder etc. hat und sich intern um Parallelzugriffe kümmert.

Ist beim wiederholten Senden der Events für den Hauptthread sichergestellt, dass nicht "immer mehr" kopierte Events von allen Nebenthreads erzeugt werden (4 Threads sagen dem Hauptthread er soll die Liste aktualisieren)?
(Langfristig) Warum werden die Events nicht sowieso schon an alle Threads (oder nur den Bestimmungsthread) geschickt, und jeder entscheidet, ob er damit was machen will? Die GUI könnte z.B. gar nicht direkt auf die "Backendevents" reagieren. Stattdessen gibt es einen GUI-Event-Verteiler, der aus den BackendEvents GUI-Events weiterschickt.

... Welchen Weg würde ich bevorzugen? Aktualisierungen in der GUI sollten eigentlich nur stattfinden, wenn es wirklich sein muss. Es bringt kaum Vorteil, wenn immer alles auf Stand gehalten wird, sich aber nie jemand dafür interressiert. Und wenn eine Änderung stattfindet, während man im Raum ist, muss sowieso auch live aktualisiert werden. Auf das Event mit dem Umsetzen eines Flags "MapNichtMehrAktuell" zu reagieren, wäre meiner Ansicht nach also nie falsch. Gleichzeitig muss dann natürlich dafür gesorgt werden, dass es bei einer "Liveaktualisierung" nicht zum SegFault kommt (KI kauft Antennen, während man die Karte betrachtet).

**Comment by GWRon** [comment]
Das Problem sind ja nicht nur konkurrierende Zugriffe auf Listen ... es kann auch soweit kommen, dass Threads in Dingen herumpfuschen (durch die Events) die nur aus einem Mainthread erfolgen duerfen (frueher war das immer die OpenGL-Grafikausgabe).

Auch wuerde das im Endeffekt "nur" bedeuten, die GUI multithreading-faehig zu machen - zumindest von ihrer "Logikseite" aus betrachtet.

> kopierte Events in Nebenthreads

Ja in der Tat muss man sicherstellen, dass dann an anderer Stelle ein Event eben "ignoriert" wird. Entweder gibt man der Kopie einen `GetData().AddBool("iscopy", True)` mit auf den Weg - oder erzeugt sogar einen neuen Event-Typ/Key fuer solche Sachen. Schoen ist das nicht.

Das entspricht auch ein wenig Deinem "Backend-Event-Verteiler". Sprich es gibt eine Stelle, die in Nebenthread erzeugte Events nach irgend einer Regel filtert und sie in eine Queue fuer den Mainthread packt.
Aber das wirkt halt alles ... "aufgestoepselt"


> Gleichzeitig muss dann natürlich dafür gesorgt werden, dass es bei einer "Liveaktualisierung" nicht zum SegFault kommt (KI kauft Antennen, während man die Karte betrachtet).

Das macht man dann mit einem Mutex der Aenderungen an allen GUI widgets dann auf den jeweiligen Thread "lockt" (mehrfache Mutex-Locks aus dem gleichen Thread sind ja moeglich - und unlocks in gleicher Anzahl natuerlich erforderlich).

Zielfuehrender und auf lange Sicht irgendwann notwendig ist aber einfach das asynchrone Vorgehen: Command -> Action -> Reaction. 
also KI: "Will Film X kaufen" ... und das kommt in eine "Command queue" (die man auch auf Ticks "binden" kann), dann arbeitet der Mainthread die Queues ab und reagiert `commandResults :+ [KaufeFilm(x)]` - und die KI wird entsprechend informiert. Damit geht allerdings einher, dass die KI an getrennter Stelle ueber das Ergebnis des Kaufversuchs informiert wird (man also bspweise `onBuyMovie()` aufruft und dort mitteilt, welche Lizenz, und das Ergebnis ... oder halt `onBuyMovieFailed()` falls man das getrennt machen will)

Dieses Entkoppeln ist auch fuer Mehrspieler interessant, da dann nur die Commands fuer spezifische "ticks" (bzw "command tick" - die dann aller 50ms hochzaehlen oder so) synchronisiert werden muessten.

**Comment by nittka** [comment]
Ich bin von der Notwendigkeit von Command->Action-Reaction noch nicht überzeugt, nicht nur, weil es die KI-Programmierung erheblich erschwert. Bleiben wir beim Beispiel Filmkauf: Es kann nur ein Spieler gleichzeitig beim Filmhändler sein. Soll ein Kauf erfolgen, kann unmittelbar geprüft werden, ob das möglich ist und der Kauf abgewickelt werden. Ob im Hintergrund Listen/Informationen threadsicher oder asynchron aktualisiert werden müssen, ist ein anderes Thema.
Der Ablauf  mittels Events für einen asynchronen Kauf ist ungleich (und unnötig) komplizierter (ich übertreibe mal).
* Film soll gekauft werden
* ist Geld da?
* Im Prinzip ja
* Geld abziehen und Film an Spieler und Spieler informieren
* Geld konnte doch nicht abgezogen werden, weil in der Zwischenzeit wegen etwas anderem der Kontostand reduziert hat
* Film wieder zurück und Spieler erneut informieren

Auch für den Mehrspielermodus sehe ich nicht unbedingt, dass alles asynchron laufen muss. Der eigentliche Filmkauf kann synchron erfolgen (es kann nur ein Spieler in der Filmagentur sein). Nach der Kaufabwicklung müssen natürlich alle informiert werden, dass sie stattgefunden hat. Aber das ist reiner Informationsfluss.

**Comment by GWRon** [comment]
Zu Deiner Uebertreibung:

- Command: Will Film kaufen....
- ein paar Millisekunden vergehen (maximal 1 Zeitschlitz der bei Inputs denke so ~50ms sein sollte ..weniger bei FastForward...)
- Commands werden im Mainthread fuer Zeitschlitz XY abgearbeitet (Film wird gekauft, Geld verringert...)
- Spieler (Mensch oder KI) bekommt das Ergebnis des Wunsches "Will Film kaufen"..also Ok, Error X,... Mittels "onBuyMovieResult"-Event oder so mit

Natuerlich kann die KI selbst vorher schauen, ob sie genuegend Geld hat und bei mehreren Filmen wuerde sie selbst Buch fuehren...

Und ja, es macht alles komplizierter...aber einfach durch den Grundansatz halt auch threadsicher bzw weniger absturzanfaellig.


Der andere Ansatz ist, die GUI komplett von der Spiellogik zu entkoppeln. Sprich die GUI hoert nicht selbst auf bestimmte Spielevents...sondern halt - wie von dir auch schon angesprochen - einen Dispatcher, der die Spiellogikevents verarbeitet, und GUI-Events erzeugt. Und das gleiche andersherum auch. 
Der GUI-Teil kann dann im mainthread laufen bzw mutex usw...

**Comment by nittka** [comment]
Für den aktuellen Fall wäre ich dafür, die Listen nicht sofort beim Empfang des Events neu zu sortieren, sondern nur ein "updateNecessary"-Flag zu setzen. Die Sortierung kann dann erfolgen, wenn die Kartengui wirklich aktiv ist.

**Comment by GWRon** [comment]
> Ist beim wiederholten Senden der Events für den Hauptthread sichergestellt, dass nicht "immer mehr" kopierte Events von allen Nebenthreads erzeugt werden (4 Threads sagen dem Hauptthread er soll die Liste aktualisieren)?

Das ist in der Tat ein valider Punkt.

> ... Welchen Weg würde ich bevorzugen? Aktualisierungen in der GUI sollten eigentlich nur stattfinden, wenn es wirklich sein muss. Es bringt kaum Vorteil, wenn immer alles auf Stand gehalten wird, sich aber nie jemand dafür interressiert.

OK, also ein "isValid=False"-Flag.

> Und wenn eine Änderung stattfindet, während man im Raum ist, muss sowieso auch live aktualisiert werden. Auf das Event mit dem Umsetzen eines Flags "MapNichtMehrAktuell" zu reagieren, wäre meiner Ansicht nach also nie falsch. Gleichzeitig muss dann natürlich dafür gesorgt werden, dass es bei einer "Liveaktualisierung" nicht zum SegFault kommt (KI kauft Antennen, während man die Karte betrachtet).

Da es sich ja um Aenderungen an "anderer Spieler"-Sendestationen handelt, sollte das gehen - man braucht dort ja keine "Listen" aktualisieren. Ausnahme ist hier, wenn man die KI beobachtet bzw "mitsteuert"...hmmm ... also wenn die interaktiven Elemente aktualisiert werden sollen (ausgewaehlter Sendemast wird von der KI verkauft und so).

**Comment by GWRon** [comment]
Ein Problem seh ich aber noch mit dem "isValid".

Es reicht nicht, einfach nur "isValid = False" zu machen. Viel mehr muss die Aenderung "isValid = False" in einen Mutex gepackt werden (validationMutex). Und beim Validieren muss der Mutex ebenfalls gelockt werden.

Warum?
Andernfalls koennten 3 KIs nahezu gleichzeitig eine Invalidierung setzen, der Mainthread bearbeitet die erste Invalidierung aber.. und setzt den Zustand auf "Valide" waehrend die anderen zwei KIs kurz vorher ebenfalls invalidiert haben, aber die dazugehoerige Aenderung noch nicht "durchgedrungen" ist. Fuer den Mainthread waere es alles wieder "valide" obwohl die Aenderungen der zwei KIs nicht eingeflossen sind.

Mittels Mutex waere sichergestellt, dass die KIs ihre Invalidierung zur Not "nach" der Revalidierung absetzen (und dann einen Update-Zyklus spaeter erneut Revalidiert werden koennte - also falls der aktive Spieler "live" auf dem Bildschirm zuschaut )


Oder hab ich hier einen Denkfehler und mach es mir komplizierter als notwendig?

**Comment by GWRon** [comment]
Ein weiteres Problem ist das "indirekte" Verarbeiten.

Wenn ich nun "invalid" gesetzt habe und folgenden Code vorher per Event verarbeiten konnte:
```Blitzmax
		if TScreenHandler_StationMap.selectedStation
			if triggerEvent.GetEventKey() = GameEventKeys.StationMap_RemoveStation
				'reset action mode (so also "selection") if the
				'station just got removed/sold
				if TScreenHandler_StationMap.selectedStation = TStationBase(triggerEvent.GetData().Get("station"))
					TScreenHandler_StationMap.ResetActionMode(0)
				endif
			endif
		endif

		TGameGUIBasicStationmapPanel(guiAccordeon.GetPanelAtIndex(0)).RefreshList( currentSubRoom.owner )
		TGameGUIBasicStationmapPanel(guiAccordeon.GetPanelAtIndex(1)).RefreshList( currentSubRoom.owner )
		TGameGUIBasicStationmapPanel(guiAccordeon.GetPanelAtIndex(2)).RefreshList( currentSubRoom.owner )
```
Dann kann ich damit prima die letzten drei Zeilen ersetzen -- einfach nur "refreshen", wenn:
- ich auf dem Bildschirm "Senderkarte" bin
- und die Aenderung eine der drei Listen betrifft

Nun gibt es dort aber ja auch den "ResetActionMode()"-Teil. Ich koennte nun eine weitere Variable einfuehren, die ein "doResetActionMode" auf 1 setzt ... also aehnlich dem "isValid".
Oder ich muesste beim Revalidieren ueberpruefen, ob die "selectedStation" noch im Besitz ist ... und wenn nicht, ResetActionMode(0) ausfuehren.


Ich denke letzteres ist "naeher am Geschehen".
