### ISSUE TITLE
Enter bei Spiel speichern

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#604]
Report Cherry: https://www.gamezworld.de/phpforum/viewtopic.php?pid=89729#p89729

> Spiel speichern: Entertaste ohne Funktion

Wenn man den Speicherndialog öffnet und einen neuen Namen eingibt, erfolgt bei Enter kein sofortiges Speichern. Dass es mit einem zweiten Enter gehen würde ist aber nicht gleich ersichtlich (kein Hervorheben des Buttons).

Wenn man einen alten Spielstand auswählt und Enter drückt, geht zwar der Bestätigungsdialog auf. Wenn man aber nun Enter drückt, passiert nichts - Mausklick nötig,

**Comment by nittka** [comment]
Weiterhin sollten die Spielstandnamen validiert werden (Namen mit einem Punkt).

**Comment by nittka** [comment]
Und Enter aus dem Nummernblock sollte sich genauso verhalten wie normales Enter...

**Comment by GWRon** [comment]
> Und Enter aus dem Nummernblock sollte sich genauso verhalten wie normales Enter...

das liegt an deinem alten Blitzmax NG ... das hab ich schon vor einigen Monaten in den Modulen gefixt.

https://github.com/bmx-ng/sdl.mod/pull/34

**Comment by nittka** [comment]
Die Meldung zum Nummernblock kam aber nicht von mir sondern von Cherry; so habe ich seine Meldung jedenfalls verstanden.

**Comment by GWRon** [comment]
Ich wollte damit nur sagen, dass dieser Punkt als "bereits erledigt" anzusehen ist - es braucht nur ein neues offizielles Release von NG.
