### ISSUE TITLE
Kabelreichweite Bremen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#605]
Report Cherry: https://www.gamezworld.de/phpforum/viewtopic.php?pid=89729#p89729

> Die Kabelnetzreichweite in Bremen ist nur etwa 10% von der Hamburgs (=Verhältnis unzutreffend)

**Comment by GWRon** [comment]
Die Zahlen sind denke generell nicht ganz exakt - bzw auch schon ein paar Jahre aelter. 
Berlin - denke knapp 1 Million zu wenig (kenne den Speckguertel nicht - nur die "Einwohnerzahl")
Hamburg - da fehlen denke auch 200.000
Muenchen ebenfalls

Entweder wir schrauben den Algorithmus um (mehr Bevoelkerung in dicht besiedelten, weniger in laendlichen) ... oder Faerben ein paar Pixel in der Bevoelkerungsdichtekarte um.

**Comment by nittka** [comment]
Vermutlich wird beides nötig sein (wenn die Zahlen so stark abweichen). Gegebenenfalls können für die Berechnung auch Nachbarpixel betrachtet werden (1 schwarzer Punkt allein "weniger dicht" als 1 schwarzer Punkt umgeben von weiteren).

**Comment by nittka** [comment]
Dieses Ticket sollte sich mit der neuen Kartenlogik erledigt haben.
