### ISSUE TITLE
Pause im Produktivmodus unterstützen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#606]
Report Cherry: https://www.gamezworld.de/phpforum/viewtopic.php?pid=89729#p89729

> Neben dem Schnellvorlauf wünsche ich mir einen Pausenknopf, um die Zeit anzuhalten.

Wie im Entwicklermodus könnte 0 für Geschwindigkeit 0 unterstützt werden. Wichtig ist wohl, dass Pause und Geschwindigkeit 0 nicht dasselbe sind...

**Comment by GWRon** [comment]
Wie ich bereits im Forum schrieb:

Wir haben diese Buttons:
Escape-Menu (mit automatischer Pause)
?-Hilfe
Geschw. 1
Geschw. 2
Geschw. 3

Der Unterschied zwischen einem "Pause Button"  im Sinne von "Setze Geschwindigkeit auf 0" und einem Pausieren mittels "Escape-Menue" ist die Interaktionsmoeglichkeit.
Mit geoeffnetem Menu kann man keine Tooltips begutachten (Quoten) oder das Maennlein irgendwo hinschicken (die "ich suche und ueberlege wo ich hin gehe"-Zeit wird eingespart).

**Comment by nittka** [comment]
Das im Forum gemeldete Problem war vorrangig, das bei Verwendung des Esc-Menüs (mit Maus) der Zielort der Figur geändert wurde. Da dieses Problem behoben ist, wird ein separater Pausenmodus nicht weiterverfolgt.
Es wäre zwar für den Spieler interessant, bei reduzierter Geschwindigkeit Sachen prüfen zu können (welche Werbung, Filme gibt es...), aber Interaktion sollte nicht möglich sein (Schummeln).
Hierfür einen separaten Pausenmodus umzusetzen, wäre aktuell zu viel Aufwand.
