### ISSUE TITLE
Toast Reichweitelevel gesunken bei neuem Spiel

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#609]
Cherry https://www.gamezworld.de/phpforum/viewtopic.php?pid=89733#p89733

>  Beim Start eines neuen Spiels bekam ich sofort die Nachricht, das Reichweitenlevel sei von 4 auf 1 gesunken

Wenn man nach laufendem Spiel ein neues Spiel startet, werden Objekte weiterverwendet. Durch die zurückgesetzte Reichweite sinkt die Reichweite und führt zur "fehlerhaften" Meldung.

**Comment by nittka** [comment]
Mit der gemachten Änderung erscheint nun häufiger die Meldung Reichweitelevel erhöht. Durch das Zurücksetzen auf 0 scheint nun das "vorige Level" auch immer 1 zu sein: "Level erhöht sich von 1 auf 4"

**Comment by GWRon** [comment]
Ja das liegt wohl am "wenn invalid dann reachBefore=0". 
Irgendwo wird die Reichweite auf "nicht _laenger_ gueltig" gesetzt ... was aber ja nicht bedeutet, dass die alte Reichweite 0 ist.

**Comment by GWRon** [comment]
Habe gleich noch "max" und "last" mit in die Historie genommen - kann fuer spaetere Versionen eine nuetzlicher Information sein (und dann haben wir die gleich mit in "alten" Savegames).
