### ISSUE TITLE
Esc-Menü Klick auf Spiel fortsetzen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#610]
Ich kann das von Cherry beschriebene Verhalten reproduzieren.
* stehe vor eigenem Büro
* Klick auf Archiv
* Menü aufmachen
* Klick in der Mitte unten des "Spiel Fortsetzen"-Buttons (nicht Esc zum Schließen)
* Die Figur steigt in den Fahrstuhl und fährt in die nächste Etage

Klickt man an eine andere Stelle des Fortsetzen-Buttons, passiert das nicht.

**Comment by GWRon** [comment]
Dann einfach schauen - ob der Klick nicht korrekt "resetted" wird. Also ob man sozusagen "durcklickt".

**Comment by GWRon** [comment]
Die Funktion "onClickHotspot" in game.building.bmx wird ausgeloest ...und schickt die Figur dadurch dort hin
