### ISSUE TITLE
Reload AI-Script scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#616]
Änderungen in den Lua-Scripten wirken sich nicht aus, wenn man in der Debug-Ansicht den Reload AI-Knopf drückt. (Vielleicht war er dafür auch gar nicht gedacht? Ich hatte ihn bisher so verstanden.)
Wunsch:
* Auf der Commands-Seite wird der Pfad des Hauptscripts angezeigt, mit dem die gerade angezeite KI arbeitet (...falls man mehrere KI-Implementierungen gleichzeitig im Einsatz hat)
* Bei Reload werden auch diese Scripte neu geladen (siehe oben)
* Bonus: Man kann auf der Commandsseite direkt auf eine andere Implementierung umschalten (nicht nur über DEV.xml)

**Comment by GWRon** [comment]
Also der Befehl wird ausgefuehrt... denke "GetLuaEngine().SetSource()" schafft es noch nicht, das alte rauszuschmeissen...

**Comment by GWRon** [comment]
Ok, hab das jetzt an sich laufen - denke aber wir sollten ein wenig den "Start()" der KI aufraeumen ... ist ein wenig "verquirlt" 

Start() -> LoadScript()
ReloadScript() -> LoadScript() (und muss als Fix auch Start() aufrufen damit der neue Code registriert wird)

Denke wir sollten "start()" und "LoadScript" entkoppeln ... schaue mir das am Wochenende hoffentlich mal an.

**Comment by nittka** [comment]
Wird beim Laden der Scripte eigentlich ein Unterschied zwischen  "Logik" und Daten gemacht? Denn es macht ja schon einen Unterschied, ob beim Neuladen nur eine geänderte Funktionsimplementierung aktiv wird oder ob dadurch auch der gesamte KI-Zustand zurückgesetzt wird.

**Comment by GWRon** [comment]
Die KI "speichert" vorher ..und danach "laedt" sie.

**Comment by nittka** [comment]
Wegen der Verbesserungsvorschläge für die Debugansicht würde ich das Ticket nochmal aufmachen.

**Comment by GWRon** [comment]
Sorry, ja, machen wir das spaeter zu.

**Comment by nittka** [comment]
Ich mach' das Ticket jetzt doch zu. Wenn die Verbesserungen am Debugscreen akut benötigt werden, fällt das sicher.
