### ISSUE TITLE
Berechnung mögliche Zuschauer

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#622]
Ich glaube, es gibt einen bösen Bug in der Berechnung der möglichen Zuschauer im Sendegebiet...

![zuschauerzahl](https://user-images.githubusercontent.com/2562651/168970409-49cecc12-475b-4e87-a161-efe49e263896.png)

**Comment by GWRon** [comment]
Also wenn wir die im Tooltip angezeigten Zahlen addieren, kommen wir auf so rund 40 Millionen.

Die Zuschauerzahl ist 20 Millionen. 22% Marktanteil...

Evtl wird der Marktanteil nicht korrekt ausgerechnet (Maerkte, die wir alleine bedienen vs Bereiche mit Ueberlappungen zu anderen Sendern).


Ist das reproduzierbar? Was passiert bei gecheateter MaxAudience ?

**Comment by nittka** [comment]
Solange ich keine Kabelverträge hole, passen die Zahlen auch bei starker Überlappung der Antennen. Dann habe ich 4 Kabelverträge geholt und für einige Tage waren Sendegebiet (Tooltip) und Bevölkerung (Quotenbildschirm) gleich. Dann aber war die Bevölkerung plötzlich fast doppelt so hoch (13 Mio vs. 7 Mio).

**Comment by nittka** [comment]
Vielleicht hilft bei der Analyse auch der cableFirst-Branch. Darin möchte ich umsetzen, dass ein Spieler zum Start einen "kleinen" Kabelvertrag bekommt, falls die Antennenreichweite zu niedrig ist. Bei der aktuellen Konfiguration (950K Zuschauer) ist das im Startjahr 2000 der Fall. Und sofort sieht man, dass etwas nicht stimmen kann. Reichweite 1.1Mio Zuschauer, mögliche Zuschauer 1.2 Mio und der Spieler erreicht sofort die ersten Erfolge für Journalismus und erreichte Zuschauer.

(Achtung: eine fachliche Änderung musste ich im StationMap-Code vornehmen. Beim Initialisieren der Kabelanbieter habe ich unmittelbar ein Update eingefügt, da der erste Spieler sonst keinen Kabelvertrag bekommen hat - der Launch hatte noch nicht stattgefunden, so dass der TemporaryUplink null war.)

**Comment by nittka** [comment]
Ein Fehler ist in GetCableNetworkPopulationShare. Dort wird "population" gesamt als Wert gesetzt, d.h. die Gesamtbevölkerung des Bundeslands anstatt nur der aktuelle Kabelanteil der Bevölkerung. Aber auch danach ist (im cableFirst-Branch) die Bevölkerung im Quotenbildschirm viermal so hoch wie erwartet (für jeden Spieler nochmal addiert?).

**Comment by nittka** [comment]
Die Kabelbevölkerung scheint überhaupt falsch in den Markt gepackt zu werden. Wenn ich im cableFirst-Branch nur für Spieler 1 die Kabelalternative aktiviere (game.game.bmx Zeile 804 nicht nur Reichweite sondern auch playerID prüfen), bekomme ich für Spieler 1 im Quotenbildschirm nur auf eine Bevölkerung von 550000 statt 1.17 Millionen.

**Comment by GWRon** [comment]
> Ein Fehler ist in GetCableNetworkPopulationShare. Dort wird "population" gesamt als Wert gesetzt, d.h. die Gesamtbevölkerung des Bundeslands anstatt nur der aktuelle Kabelanteil der Bevölkerung. Aber auch danach ist (im cableFirst-Branch) die Bevölkerung im Quotenbildschirm viermal so hoch wie erwartet (für jeden Spieler nochmal addiert?).


Dort wird "population" genutzt, da Dinge wie die "CurrentPopulationCableShare"-Werte dynamisch sind.
Es werden also die Werte gespeichert, die bei "100% der Bevoelkerung nutzen Kabel statt Antenne, Satellit..." entstehen wuerden.

Um den "effektiven" Wert zu bekommen, muss man `GetCableNetworkReceiverShare` nutzen ... also "Receiver" statt "Population".
Gleiches gilt fuer "GetAntennaReceiverShare".


Ich glaube aber, dass die Satelliten in die `GetReceiverShare()` nicht eingehen, koennte auch ein Fehler sein.

**Comment by nittka** [comment]
Ich weiß nicht, wie es mit den Satelliten gedacht ist. Die haben ja keine Bundeslandgrenzen. Vielleicht werden sie deshalb nicht im GetReceiverShare der TStationMapSection berücksichtigt und dann immer separat dazuaddiert.
Die obige Erklärung leuchtet mir ein. Auf dem cableFirst-Branch mit Startjahr 2000 ist die für die Quotenbildschirm verwendete Zahl der Bevölkerung jedenfalls achtmal so groß wie sie eigentlich sein sollte.
(Wenn nur Spieler 1 den Kabelvertrag bekommt, stimmt die Zahl, wenn auch Spieler 2 den Vertrag bekommt, ist die Zahl doppelt so groß, wenn auch Spieler 3 den Vertrag bekommt ist sie viermal so hoch).

Stimmt da was mit den include-Exclude-Masks nicht, so dass die Zuschauerzahlen des Vertrags für Spieler 2 auch für Spieler 1 verwendet werden und umgekehrt?

**Comment by GWRon** [comment]
> include-Exclude-Masks

Guter Gedanke ... schau ich mir dann an (baue mir eh einen "Test" um da nicht jedesmal das ganze Spiel starten zu muessen ;D).


> Satelliten

Ja ... die sind ohne Grenzen und entsprechend braucht es die "Share"-Informationen nur auf "gesamte Map"-Ebene.

**Comment by nittka** [comment]
Achtung. Dasselbe Problem betrifft auch die Satellitenverträge.
* Spielstart, alle KIs deaktivieren und Image für alle hochsetzen
* Spieler 1 holt Sat-Vertrag - nach Fertigstellung stimmen die Zahlen im Quotenbildschirm
* Spieler 2 holt Sat-Vertrag - nach Fertigstellung ist bei beiden Spielern die Bevölkerungszahl im Quotenbildschirm zu hoch
* usw.

**Comment by nittka** [comment]
Ich habe mich zunächst gewundert, warum dieser Fehler noch nicht früher aufgefallen ist, aber er tritt ja nur auf, wenn mehr als ein Spieler denselben Vertrag hat und die KI schließt ja erst neuerdings Kabel- und Satellitenverträge ab. Weiterhin tritt er normalerweise erst spät im Spiel auf, wenn dann überhaupt die "teuren" Verträge für den Ausbau interessant werden. Und da ist dann die Antennenreichweite schon so hoch, dass die doppelt gezählten Zuschauer zunächst nicht ins Gewicht fallen. Und den Quotenbildschirm hat man auch nicht ständig offen oder rechnet die Prozentwerte im Tooltip nach.

**Comment by nittka** [comment]
Im PR habe ich einen Ansatz implementiert, der mir plausibel vorkommt und bei ersten Tests zu funktionieren scheint. Bitte mal auf Herz und Nieren prüfen.

**Comment by GWRon** [comment]
Mein Ansatz sieht so aus (jetzt mal fuer Kabelnetze):

```
		'== GENERATE CACHE ==
		If Not result
			Local includedChannelsWithCableNetwork:Int = 0
			Local excludedChannelsWithCableNetwork:Int = 0

			'count how much of the "mentioned" channels have at least
			'one active uplink there
			For Local channelID:Int = 1 To GetStationMapCollection().stationMaps.Length
				If includeChannelMask.Has(channelID)
					If GetStationMap(channelID).GetCableNetworkUplinksInSectionCount( name, True ) > 0
						includedChannelsWithCableNetwork :+ 1
					EndIf
				ElseIf excludeChannelMask.Has(channelID)
					If GetStationMap(channelID).GetCableNetworkUplinksInSectionCount( name, True ) > 0
						excludedChannelsWithCableNetwork :+ 1
					Endif
				EndIf
			Next

			result = New TStationMapPopulationShare
			If includedChannelsWithCableNetwork > 0
				'total - if at least _one_ channel uses a cable network
				result.value.total = population

				'as soon as one "excluded" has an uplink there, we know
				'the "included" won't be exclusive
				'(with only 1 network you cannot only use 50% of it)
				If excludedChannelsWithCableNetwork = 0
					result.value.shared = population
					'ratio is defined by how many "to include" channels
					'have an active uplink
					result.value.populationShareRatio =  includedChannelsWithCableNetwork / Float(includeChannelMask.GetEnabledCount())
				EndIf
			EndIf

			'store new cached data
			If shareCache 
				LockMutex(shareCacheMutex)
				shareCache.insert(cacheKey, result)
				UnlockMutex(shareCacheMutex)
			EndIf

			'print "CABLE uncached: "+cacheKey
			'local dbgString:String = "ChannelMask: incl=" + LSet(includeChannelMask.ToString(), 12) + "  excl=" + LSet(excludeChannelMask.ToString(), 12)
			'dbgString :+ "  channelsWithCableNetwork: " + includedChannelsWithCableNetwork + " included, " + excludedChannelsWithCableNetwork + " excluded"
			'dbgString :+ "  -> CABLE share:  total="+int(result.value.total)+"  shared="+int(result.value.shared)+"  populationShareRatio="+(result.value.populationShareRatio*100)+"%"
			'print dbgString
		Else
			'print "CABLE cached: "+cacheKey
			'local dbgString:String = "ChannelMask: incl=" + LSet(includeChannelMask.ToString(), 12) + "  excl=" + LSet(excludeChannelMask.ToString(), 12)
			'dbgString :+ "  -> CABLE share:  total="+int(result.value.total)+"  shared="+int(result.value.shared)+"  populationShareRatio="+(result.value.populationShareRatio*100)+"%"
			'print dbgString
		EndIf
```

Was ist hier anders?
- fuer die eigentliche Berechnung sollten nun weniger Variablen genutzt werden
- Nur "aktive" Uplinks werden beachtet (die koennen aus diversen Gruenden inaktiv sein - Sturmschaeden oder so)
- Ergebnisse sollten so sein wie "geplant":
  - sobald in "exclude" ein Sender drin ist, der ebenfalls einen Uplink im Bundesland hat, ist "shared" 0 und "ratio" auch 0, total aber weiterhin "was moeglich waere/Bevoelkerung im Bundesland"
  - gibt es im "include" einen Sender der keinen Uplink hat, reduziert er die "ratio" und "shared" entspricht weiterhin dem "total" Wert ("Sender 1 und 2 erreichen zusammen 'total' Menschen im Bundesland, aber nur 50% dieser beiden Sender haben einen aktiven Uplink). Damit kann interpretiert werden, ob "alle" in include einen Uplink haben oder nicht

Beispiel 1: nur Sender 1 hat einen Uplink in Bremen:
```
ChannelMask: incl=(1)           excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2)        excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=50.0000000%
ChannelMask: incl=(1, 2, 3)     excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=33.3333359%
ChannelMask: incl=(1, 2, 3, 4)  excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=25.0000000%
ChannelMask: incl=(1)           excl=(2)           channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1)           excl=(2, 3)        channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1)           excl=(2, 3, 4)     channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1)           excl=(3, 4)        channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2)        excl=(3, 4)        channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=50.0000000%
```

Beispiel 2: Sender 1 und Sender 2 haben einen Uplink in Bremen:
```
ChannelMask: incl=(1)           excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2)        excl=()            channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2, 3)     excl=()            channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=66.6666718%
ChannelMask: incl=(1, 2, 3, 4)  excl=()            channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=50.0000000%
ChannelMask: incl=(1)           excl=(2)           channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2, 3)        channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2, 3, 4)     channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(3, 4)        channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2)        excl=(3, 4)        channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
```

Beispiel 2: Sender 1 und Sender 3 haben einen Uplink in Bremen:
```
ChannelMask: incl=(1)           excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2)        excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=50.0000000%
ChannelMask: incl=(1, 2, 3)     excl=()            channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=66.6666718%
ChannelMask: incl=(1, 2, 3, 4)  excl=()            channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=50.0000000%
ChannelMask: incl=(1)           excl=(2)           channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1)           excl=(2, 3)        channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2, 3, 4)     channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(3, 4)        channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2)        excl=(3, 4)        channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%

'extra um zu zeigen, dass hier shared nicht 0 ist, aber die ratio < 100%:
ChannelMask: incl=(1, 2, 3)     excl=(4)           channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=66.6666718%

```


Maerkte in der Quotenberechnung nutzen dieses "Sender 1 oder 2" (include = 1 + 2) nicht, da ists immer: 
include(Sender X)
exclude(alle ausser Sender X)

Ausgewertet wird dort nur "shared", also wie viele Zuschauer erreichen die Sender in "include" gemeinsam (gibt nur einen).

**Comment by GWRon** [comment]
Da das allerdings eine Aenderung bei game.broadcast.base.bmx erfordern wuerde:
```
	Method AddMarket(includeChannelMask:SChannelMask)
...
		Local audienceCableNetwork:Int = GetStationMapCollection().GetTotalCableNetworkReceiverShare(includeChannelMask, excludeChannelMask).shared
```
("shared" wie gesagt > 0 obwohl im letzten Beispiel nach dem Markt gefragt wurde, den "1,2,3" zusammen haben --- und die haben eben 0 gemeinsam, und nicht "267488")
Die Aenderung muesste hier sein, dass `audienceCableNetwork` auf `0` gesetzt werden muesste, sobald die `populationShareRatio` < 100% ist (nicht alle "include" Sender haben einen Uplink).

Oder man nimmt folgenden Code:
```
'....
			result = New TStationMapPopulationShare
			'all included channels neet to have an uplink ("and" instead of "or" connection)
			If includedChannelsWithCableNetwork > 0 and includedChannelsWithCableNetwork = includeChannelMask.GetEnabledCount()
				'total - if at least _one_ channel uses a cable network
				result.value.total = population

				'as soon as one "excluded" has an uplink there, we know
				'the "included" won't be exclusive
				'(with only 1 network you cannot only use 50% of it)
				If excludedChannelsWithCableNetwork = 0
					result.value.shared = population
					'ratio is defined by how many "to include" channels
					'have an active uplink
					result.value.populationShareRatio =  includedChannelsWithCableNetwork / Float(includeChannelMask.GetEnabledCount())
				EndIf
			EndIf
'....
```

Dann wird fuer den Fall "Sender 1 und Sender 3 in Bremen":
```
ChannelMask: incl=(1)           excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2)        excl=()            channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=0  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2, 3)     excl=()            channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=0  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2, 3, 4)  excl=()            channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=0  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2)           channelsWithCableNetwork: 1 included, 0 excluded  -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1)           excl=(2, 3)        channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2, 3, 4)     channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(3, 4)        channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=267488  shared=0  populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2)        excl=(3, 4)        channelsWithCableNetwork: 1 included, 1 excluded  -> CABLE share:  total=0  shared=0  populationShareRatio=0.00000000%

'extra um zu zeigen, dass hier shared 0 ist und die ratio 0%:
ChannelMask: incl=(1, 2, 3)     excl=(4)           channelsWithCableNetwork: 2 included, 0 excluded  -> CABLE share:  total=0  shared=0  populationShareRatio=0.00000000%
```

**Comment by GWRon** [comment]
Hier nun die Gegenueberstellung von deinem Fix und meinem Fix:

Sender 1 und Sender 3 haben in Bremen einen Kabeluplink:
```
'Mein Fix
ChannelMask: incl=(1)           excl=()            -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2)        excl=()            -> CABLE share:  total=267488  shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2, 3)     excl=()            -> CABLE share:  total=267488  shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2, 3, 4)  excl=()            -> CABLE share:  total=267488  shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2)           -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1)           excl=(2, 3)        -> CABLE share:  total=267488  shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2, 3, 4)     -> CABLE share:  total=267488  shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(3, 4)        -> CABLE share:  total=267488  shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2)        excl=(3, 4)        -> CABLE share:  total=267488  shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1, 3)        excl=(2, 4)        -> CABLE share:  total=267488  shared=267488  populationShareRatio=100.000000%
ChannelMask: incl=(1, 2, 3)     excl=(4)           -> CABLE share:  total=267488  shared=0       populationShareRatio=0.00000000%

'Dein Fix
ChannelMask: incl=(1)           excl=()            -> CABLE share:  total=0       shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2)        excl=()            -> CABLE share:  total=0       shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2, 3)     excl=()            -> CABLE share:  total=267488  shared=0       populationShareRatio=100.000000%
ChannelMask: incl=(1, 2, 3, 4)  excl=()            -> CABLE share:  total=267488  shared=0       populationShareRatio=75.0000000%
ChannelMask: incl=(1)           excl=(2)           -> CABLE share:  total=0       shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2, 3)        -> CABLE share:  total=0       shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(2, 3, 4)     -> CABLE share:  total=0       shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1)           excl=(3, 4)        -> CABLE share:  total=0       shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1, 2)        excl=(3, 4)        -> CABLE share:  total=0       shared=0       populationShareRatio=0.00000000%
ChannelMask: incl=(1, 3)        excl=(2, 4)        -> CABLE share:  total=267488  shared=267488  populationShareRatio=150.000000%
ChannelMask: incl=(1, 2, 3)     excl=(4)           -> CABLE share:  total=267488  shared=0       populationShareRatio=100.000000%
```
Die Faelle "incl(1)" sollten "shared<>0" sein, wenn "3" nicht verboten/ausgeschlossen ist

**Comment by nittka** [comment]
Ziel für mich war eigentlich nur eine Kombination zu finden, in der die Zuschauerzahlen bei mehreren Verträgen für ein Bundesland nicht nach oben gehen, damit ich mit meinen Langzeit-Ertrag-Kosten-Statistiken weiterkomme. Dass bei meiner Variante was nicht stimmen kann, sieht man ja an in der vorletzten Zeile, wo ShareRation  150 ist.
Ignoriere also gern meinen PR und pushe einen Branch, den ich testen kann.

**Comment by GWRon** [comment]
Ich wollte nicht vorwurfsvoll klingen oder deinen Fix schmaelern. Hab einfach nur die Stelle "neu" aufgesetzt und versucht durchzutesten.

**Comment by nittka** [comment]
Keine Sorge, ich habe es auch nicht als Vorwurf verstanden. Und das mit dem Ignorieren war schon so gemeint - nicht versuchen, meinen Reparaturversuch zu fixen.
Im Code kommen eigentlich nur die Include/Exclude-Kombinationen vor, in denen excl = negate(incl) ist, oder?

**Comment by nittka** [comment]
Ist mit dem PR behoben.
