### ISSUE TITLE
Vertrag läuft weiter, wenn Satellit abstürzt

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#625]
In einem Testspiel über 100 Tage sah es so aus, als würden Verträge nicht sauber beendet werden, wenn ein Satellit "abstürzt". In der Liste steht dann 4/3, ein Satellitenname war '#3' (Screenshot folgt).

**Comment by GWRon** [comment]
Bestaetigt - es gibt im Code bisher nur eine Codestelle die auf `GameEventKeys.StationMapCollection_RemoveSatellite` reagiert.
und in `Method RemoveSatellite:Int(satellite:TStationMap_Satellite)` selbst, wird auch nix mit den Vertraegen gemacht.

**Comment by GWRon** [comment]
Zwar gibt es im Code ein `UpdateSubscriptions()` (auch eines fuer Satelliten) aber da bei "Absturz" der Satellit ja aus der Liste verschwunden ist ...

**Comment by nittka** [comment]
Meinst Du, dass bei einem Satellitenabsturz auch Antennen, die an dieser Position stehen kaputt gehen können?... die fallen ja nicht senkrecht vom Himmel und sollten vorher verglühen.
Wenn Du aber meinst, dass dieser Satellit die einzige Sendequelle eines Spielers ist - das kann nicht passieren, die erste Antenne oder der erste Kabelvertrag sind aktuell nicht verkäuflich/kündbar. Und selbst wenn sie es wären - ein Spieler, der nicht genug Bargeldreseven hat oder keinen Kredit aufnehmen kann, nur noch einen Sender hat und diesen dann verscherbelt (oder verliert), hat es nicht besser verdient...

**Comment by GWRon** [comment]
Ich meinte letzteres ...
Ein menschlicher Spieler koennte das wollen: "ich verkauf erstmal alles, und kauf dann das Neue".
Die KI hingegen, koennte durch einen Fehler in ihrem "Denken" aber auch ein Problem bekommen.

Natuerlich ist das Resultat dann am Ende die Pleite und ... dann ists halt so :D
