### ISSUE TITLE
Licence PriceModifier doppelt verwendet

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#629]
Ich versuche gerade hinter die extremen Preisunterschiede der Lizenzen zu kommen. Unabhängig vom Reichweitefaktor gehen auch schon die Basispreise ziemlich auseinander. Unabhängig von den Einflüssen von Qualität und Aktualität scheint aber der in der Datenbank hinterlegte PriceModifier zweimal angewendet zu werden: im Basispreis der Programmdaten (programmedata.bmx getPrice Zeile 1371) und in der Lizenz selbst auch noch einmal (programmelicence.bmx getPriceForPlayer Zeile 1972).

Das scheint mir ein Fehler zu sein. Der Modifier sollte nur einmal berücksichtigt werden (in data?)

**Comment by nittka** [comment]
Wenn man abweichende Price-Modifier in Licence und Data unterscheiden möchte, müsste man wohl beim Einlesen der Datenbank den Default-Modifier aus Data ggf. durch den spezifischen aus den Lizenzdaten ersetzen. Dazu muss man aber erkennen, dass die Lizenz einen definiert hat (1.5 aus data durch 1.0 aus Lizenz überschreiben).
In diesem Fall dürfte der Modifier nur in getPriceForPlayer berücksichtigt werden und im Basispreis der Daten entfallen.

**Comment by GWRon** [comment]
2016: Einfuehrung vom "Modifier" bei ProgrammeData:
https://github.com/TVTower/TVTower/commit/0360340a53fab6a61920c587b642f5f33f679d5a

215: Einfuehrung bei den Lizenzen:
https://github.com/TVTower/TVTower/commit/52e254c21a1a61a421d0e33e097eaed9211daad6


Generell ist es so zu verstehen:
- der "pricemod" bei "Data" definiert fuer den "Programmdatensatz" einen Preismodifikator ("ist teurer als die Attribute erlauben").
- der "pricemod" bei "Lizenz" definiert einen etwaigen "Rabatt" fuer eine Sonderlizenz basierend auf dem gleichen Datensatz (denk dran: Du kannst 5 Lizenzen haben, die sich alle den gleichen "Film" teilen)

sie "ueberschreiben" sich also nicht - sondern ergaenzen sich multiplikativ
`Lizenzpreis = PreisDatenRoh * PreisDatenMod * X * PreisLizenzMod`

**Comment by GWRon** [comment]
> Wenn man abweichende Price-Modifier in Licence und Data unterscheiden möchte, müsste man wohl beim Einlesen der Datenbank den Default-Modifier aus Data ggf. durch den spezifischen aus den Lizenzdaten ersetzen. Dazu muss man aber erkennen, dass die Lizenz einen definiert hat (1.5 aus data durch 1.0 aus Lizenz überschreiben). In diesem Fall dürfte der Modifier nur in getPriceForPlayer berücksichtigt werden und im Basispreis der Daten entfallen.

Eher muesste man fuer die Lizenz in der DB "licence_price_mod" hinzufuegen (Aehnlich der Unterscheidung von "broadcast_flags" und "licence_broadcast_flags")


Bisher ist das einfach noch nicht noetig gewesen, da die DB "Data" und "Licence" vermischt (es wird immer 1:1 verwendet)

**Comment by nittka** [comment]
Dann ist das Einlesen der Datenbank aber meiner Ansicht nach falsch. Dort wird ja typischerweise nur die Lizenz definiert und die Daten werden implizit abgeleitet. Ein in der Datenbank angegebener PriceModifier wird aktuell aber sowohl in Data als auch in der Lizenz verwendet. Aus einem PriceModifier 1.7 wird also effektiv 2.89 und aus 0.7 wird 0.49 - ich glaube nicht, dass das so gewünscht ist.

**Comment by nittka** [comment]
Ja. Ich muss bei meinen Log-Ausgaben und den gemachten Codeänderungen durcheinander gekommen sein. Die Auswertung der Modifier ist OK.
