### ISSUE TITLE
Mehrfache Berücksichtigung der Aktualität bei Preisberechnung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#630]
In der Basispreisberechnung (programmedata) wird die Aktualität bei hohen Werten mehrfach berücksichtigt:
```
'=== FRESHNESS ===
'this is ~1 yrs
If (maxTopicality >= 0.98) Then priceMod :* 1.35
'this is ~2 yrs
If (maxTopicality >= 0.96) Then priceMod :* 1.30
'this is ~3 yrs
If (maxTopicality >= 0.93) Then priceMod :* 1.25
```
Wenn der Wert 0.99 ist, wird erst mit 1.35, dann noch einmal mit 1.3 und dann mit 1.25 multipliziert (Gesamtfaktor 2.2), da kein else verwendet wird. Später wird dann ja nochmal maxtopicality^4 verwendet, was ja auch ein Maß der Freshness ist (bei 1 kein Abzug).
Vom Gefühl her ist das eine Überbewertung der Aktualität (3 Jahre alter Superfilm vs. aktueller OK-Film), die möglicherweise auch bei Eigenproduktionen zu ziemlich hohen Preisen (Verkauf und insb. Wiederkauf) führt.

Alternativ könnte man statt maxTopicality direkt zu verwenden zunächst 0.1 addieren und dann nur die Formel mit Exponent verwenden.  Und/oder man addiert auch bei der Qualität (vor dem Potenzieren) noch was drauf, um gute Filme zu belohnen anstatt sie nur weniger stark zu bestrafen.

Meine Hauptanliegen sind die extrem großen Preisunterschiede insb. später im Spiel. Ein Film für 33 Mio ist nicht so wirklich sinnoll, selbst wenn Werbeeinnahmen von 3Mio pro Block möglich sind.

**Comment by nittka** [comment]
Wie telefonisch besprochen ist die Mehrfachmultiplikation für die Aktualität ja so gedacht.
Ich schaue mir gerade die Basispreisberechnung an. Ohne die Zusatzfaktoren für Aktualität (bis zu Faktor 2.2), die Faktoren für Live/Paid/Kult etc. und den konfigurierten Preisfaktor kommt man bei der aktuellen Formel auf eine Preisspanne von 6500 bis 1.2Mio (bzw. realisischerweise 600000) pro Block - für den Startzustand mit maximalen Werbeeinnahmen um 40000 pro Block. Der Ausreißer nach oben ist der unendlich spaßige Film mit Qualität und Aktualität 1, die nächstteuren haben eine Qualität um 0.75 bis 0.9.

Ich halte diese Preisspanne (Faktor 100) für viel zu groß, wenn die Lizenzpreise sich im Laufe des Ausbaus auch vervielfachen. Denn das bedeutet, dass man in späteren Spielphasen praktisch keine Lizenzen mehr kauft, da sich diese finanziell nie lohnen werden. Es gibt nun 2 Lösungsansätze.

Ansatz 1 ("Abschaffung Reichweitelevel" #572):
Die Preisberechnung bleibt prinzipiell unverändert, die Preisspanne zwischen schlechten alten und guten neuen Filmen bleibt bei Faktor 100; die Preissteigerung bei Reichweitelevelerhöhung wird aber dramatisch verringert. Die Werbeeinnahmen pro Block steigen dann beim Ausbau in Bereiche an, dass sich die teuren (ich meine besseren) Filme rentieren können. Am Anfang bräuchte man 20 Ausstrahlungen um das Geld wieder reinzuholen, bei hoher Reichweite dann nur noch zwei oder eine - selbst wenn man den Film bei der Reichweite kauft.

Ansatz 2:
Die Preisspanne für den Basispreis wird drastisch verringert, z.B. auf eine Maximalpreis von 150000 pro Block (der Aktualitätsfaktor kommt dann ja noch dazu). Die Lizenzen werden initial also wesentlich günstiger. Das erhöht den Anreiz, neue Filme zu kaufen, macht aber die Strategie sich vor einem Reichweitelevelanstieg mit Filmen einzudecken, vielleicht zu offensichtlich/attraktiv.

Ansatz 3:-) :
Man lässt die Preisberechnungen und -änderunge wie sie sind, erzwingt aber auf andere Weise, dass man auch später im Spiel neue Filme kaufen (oder produzieren) muss. Schließlich kann man überteuerte Filme ja auch senden, abwarten und bei erholter Aktualität wieder verkaufen (und dadurch Gewinn gemacht haben). In der Zwischenzeit bindet die Lizenz halt Kapital. Allerdings ist auch hier fraglich, ob man bereit ist, für 30Mio eine Lizenz zu kaufen, 6Mio an Werbeeinnahmen zu haben und dann tagelang zu warten, um durch den Verkauf keinen Verlust zu machen.
Die Frage ist auch, wie man das erzwingen kann: massiv sinkende Zuschauerzahlen bei Wiederholungen, maximale Ausstrahlungshäufigkeit...

Wenn ich mir die Alternativen anschaue, tendiere ich aktuell zum ersten Ansatz. Hohe Preisunterschiede gibt es ja im echten Leben auch. Und ein kleiner Sender kann sich eben nicht (oft) Blockbuster leisten. Man wächst, um ein besseres Programm senden zu können. Die Lizenzkosten steigen aber nur sehr wenig, so dass die Auswahl der Lizenzen mit vertretbaren Kosten immer größer wird. Auch der Faktor für hohe Aktualität (Faktor 2) kann so problemlos erhalten bleiben. Entweder man zahlt, weil man den aktuellen Film unbedingt senden möchte oder man wartet bis die Kosten sinken.

**Comment by GWRon** [comment]
Die Vorgehensweise, mehrfach zu multiplizieren, war absichtlich so gestaltet (sollte auch an anderen Codestellen so aehnlich ablaufen). Da kann man bequem "und"-Bedingungen hinzufuegen, die fuer alle Faelle/Cases gueltig sind.

Du kannst das aber gerne umstellen (if elseif) und auch die Werte anpassen.
Ziel war hier, das gaaaanz frisch rausgekommene Kinokracher nicht nur ein paar Prozent teurer sind, als aeltere (aber leicht bessere) Filme.
Sonst sendet einfach niemand mehr den alten Kram ;-).
