### ISSUE TITLE
Marktkalkulation: Cache einführen/umbauen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#633]
https://github.com/TVTower/TVTower/pull/627 : 

> Beim Markt ist schon der finale Stand enthalten:
> - GameModifiers (mehr Zuschauer durch Regenwetter)
> - aktuelle Aufteilung zw. den Empfangsmoeglichkeiten
>
>
> Entsprechend muessten die Caches dann invalidiert werden, wenn etwas eines der benutzten Faktoren aendert:
> - entsprechende GameModifiers
> - einer der Share-Ratio-Werte
> - eine der "Stations" aller vier Spieler
> 
> Waere moeglich ...weiss nicht wie cpu-Intensiv die Marktberechnung ist.

Die Idee ist, die Marktberechnung mit einem Cache zu versehen. Allerdings muss dieser Cache bei allen den Markt beeinflussenden Dingen invalidiert werden. Also Spielmodifikatoren die durch Trigger in Nachrichten ausgeloest werden, Sendemastkäufe eines jeden Spielers, Auslaufen von Uplinkverträgen (die onChange...-Events).
Bei Spielmodifikatoren wäre ein "onChangeGameModifier" dann eventuell interessant - also nur zu reagieren, wenn der Wert sich aendert.
Je nach Haeufigkeit der Aenderung (vlt fuegt man irgendwann etwas hinzu, was fuer eine Stunde minuetlich einen Wert anpasst ...warum auch immer) kann das natuerlich den Cache unnoetig "zu haeufig" invalidieren. Allerdings bedeutet invalidieren aber nicht, das immer gleich auch neu zu berechnen.

Ob sich der Aufwand dafuer lohnt, haengt von der Performanz der Marktzusammenstellung ab. Der aufwaendigste Teil war ja die Ermittlung der Ueberschneidungen fuer die Sendemasten/Antennen - und die werden ja derzeit schon gecachet.

**Comment by nittka** [comment]
siehe auch #511
Zu prüfen wäre nochmal, ob die Anzahl der "Markterstellungen" vertretbar ist. Für Antennen und Kabel gibt es schon Caching, für Satelliten noch nicht. Da hier die Berechnung etwas aufwändiger geworden ist (Vertrag existiert, Senden schon möglich), was ja durch die inklude/exclude-Kombination mehrfach aufgerufen wird, ist weitere Optimierung möglich.

Die Idee war, dass ja "der Markt" für alle Spieler identisch ist und jede Änderung eine Änderung für alle Spieler bedeuten kann. Deshalb Markt einmal bauen, bei Änderung invalidieren.

**Comment by nittka** [comment]
Ich gehe davon aus, dass sich das Thema mit dem Refactoring erledigt hat. Die Performance-Thematik, die ich in einem anderen Ticket angesprochen hatte, ließ sich auf die Programmplanung zurückführen. Bei vielen Programmen kostet das Filtern der passenden Lizenzen und das Sortieren viel Zeit. Wenn man hier Anpassungen vorgenommen hatte, lief auch auf meinem langsamen Rechner an Tag >100 im KI-Spiel die Uhr mit wenig Stocken.
