### ISSUE TITLE
zweiter Modus für den Quotenbildschirm

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#638]
Neben der genauen Zuschauergruppenaufschlüsselung für einen Spieler wäre ein zweiter Modus für den Quotenbildschirm nett:
* alle 4 Spieler nebeneinander
* was wird gerade gesendet
* wie ist die Reichweite
* wie ist die Gesamt Einschaltquote
* wie ist die Aufteilung und pro Zielgruppe
* wie ist das aktuelle Image
* wie ist das Image nach der Ausstrahlung

Ziel wäre, leichter einen Überblick über alle gerade gesendeten Programme zu bekommen (wie verteilen sich die Zuschauer, welche Imageänderungen ergeben sich daraus). Entweder man wechselt den Modus immer mit Q oder packt ein Strg davor, je nachdem welcher Modus gewünscht ist.

**Comment by nittka** [comment]
Ich baue gerade an einem Prototypen. Welche Variante für das Umschalten der Quotenbildschirme wäre am besten?
* mit Q "durchblättern": aus->Q->Einzelspieleransicht->Q->Spielergesamtübersicht->Q->aus
* Q für Standardansicht, Shift-Q für Spielergesamtübersicht

Da Ctrl-Q das Spiel beendet, scheint mir die Variante 2 etwas "unsicher".

**Comment by GWRon** [comment]
Hmm bei aktivem Quotenbildschirm koennte man auch Shortcuts fuer den Wechsel der "Modi" einfuehren. Oder Buttons...

Ctrl+Q ... Ja, das kann unschoen sein, wenn man da nicht aufpasst, allgemein ist aber der Quotenbildschirm eh "Dev/Debug"-Zeug und fuer den normalen Spieler eigtl. nicht zugaenglich

**Comment by nittka** [comment]
In dem Fall wäre ich für die erste Option. Ich möchte eigentlich keine Tastensonderbehandlung je nach Status des Quotenbildschirms (oder Buttons - Tastaturbedienung erforderlich). Bei nur zwei Modi ist das "Durchwechseln" noch kein Problem.

**Comment by nittka** [comment]
Mit #673 erledigt.
