### ISSUE TITLE
Suggestion: random AI names, channels, colors and looks

### ISSUE THREAD

**Issue by Nasher73** [TVTower/TVTower#642]
As the title says, it could be great to have randomly generated (or picked from a long list) names for AI players and channels.
The same goes for their looks and colors.
It would help making a new game slightly different from the previous one.

Maybe this could be integrated in the seed number ?

**Comment by GWRon** [comment]
We could also think of adding a little "dice" icon next to the AI player boxes - clicking on it and it shuffles:
- name
- channel name
- maybe even player colour (... but think it wont be needed)

Of course it needs some good suggestions for:
- player names
- channel names


I could use our name generator for it too ... in connection with the interface language it might even use "localized" names if existing: So French players would play against Pierres, Maries, ... while English ones play against a James or Jeanne.

**Comment by nittka** [comment]
I also prefer an explicit action rather than an implicit shuffling. I'd like to see what the player configuration will be, before actually starting the game.
* Should there be one button for all AI players or a button for each one? Both versions have disadvantages.
* Should there be a "reset to defaults" button?
* (An additional DEV-option could be added controlling whether the AI player values should be randomized before the configuration screen is shown.)

**Comment by nittka** [comment]
I have no good idea where to put a global "randomize AI players" button. How about the following approach:
* add a dice-button next to the player name for randomizing that particular player
* DEV.xml option for randomizing all AI players whenever the menu is opened
That should cover most cases. I think, there will be few players who want to randomize all players, but only once every few weeks.

**Comment by nittka** [comment]
I think only a dice next to each AI player name (making clear that a click affects only this player) is a good compromise. You don't start a new game every five minutes so clicking a few times until you are satisfied with each player should not be too much trouble.
I am not sure about the reset-functionality. If you are not happy, click again for the next version of a single player. If everything is messed up, just go back to the main menu and start game again with the defaults. If every second click just restores the default value, you need twice as many clicks to go through all combinations.

A list of channel names could be hard-coded, the person generator could create player names.

**Comment by GWRon** [comment]
Having to go back to main for a hard reset...will reset all other custom settings in the screen too.
Might be something they do not want to happen.

**Comment by nittka** [comment]
True, but there are hardly any other relevant settings. Your own name, channel and start year will probably have been defined in the settings screen. There is a way to restore the defaults. In the current implementation, you have no other way to restore them, either, if you changed the values yourself. The new dice-buttons are just a shortcut for changing the values.
