### ISSUE TITLE
KI Sendeausfall an Tag 1

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#645]
*Frohnus per Forum:*
> Ansonsten hatte ich Sendeausfall der KI am ersten Tag mehrere! Stunden lang. Das muß m.E. nicht sein. Spielstand ist gespeichert, falls Bedarf besteht (Spieler - schwer, KI - alle auf leicht).

https://gamezworld.de/phpforum/viewtopic.php?pid=89780#p89780

**Comment by nittka** [comment]
Wie im Forum schon kurz angerissen, ist das ein ziemlich involviertes Problem, wenn man nicht gerade eine komplette Sonderbehandlung für Tag 1 implementieren möchte (sowohl KI als auch Engine).
* die KI soll als Starprogramm nicht alles kaufen (zu schlecht - Hände weg)
* die KI kauft im aktuellen Ansatz so viel wie möglich auf einmal (d.h. wer zuletzt kommt hat ggf. nur noch echten "Schrott" zur Auswahl und kauft deshalb gar nichts)
* die Angebote des Filmhändlers werden nur alle x Stunden neu gewürfelt (neue Inhalte kommen also in einem gewissen Zeitraum nur, wenn jemand anderes etwas kauft)
* die KI soll Sachen möglichst nichts mehrfach am Tag senden

Wenn die KI innerhalb der ersten Stunden nichts kaufen konnte/wollte, ist einfach nichts da, was gesendet werden kann. In dem Fall ist es vielleicht sogar besser, einen Sendeausfall in Kauf zu nehmen anstatt schlechte Lizenzen zu kaufen. Denn die würden dann auch später weiterverwendet und nicht sofort wieder abgestoßen werden, was zu schlechterer Langzeitperformance führt.

**Comment by nittka** [comment]
Mit den letzten KI-Anpassungen sollte die Wahrscheinlichkeit massiver Sendeausfälle am ersten Tag verringert worden sein. Ich fände es noch sinnvoll, wenn das Filmhändlerangebot anfangs noch häufiger ausgetauscht wird.

**Comment by nittka** [comment]
Ein weiterer Grund für Sendeausfall am ersten Tag kann auch sein, dass die KI gute Lizenzen (insb. Serien) gekauft hat (weil keine passenden "schlechten" da waren) und dann nicht genügend Material für die niedrigen Level vorhanden sind (problematische Programmauswahl aufgrund fester Qualitätslevel).

**Comment by nittka** [comment]
Neben der Problematik der Anzahl der verfügbaren Lizenzen habe ich noch Fehler in der Programmplanung der KI gefunden. Insb. das Erkennen von Sendeausfällen war kaputt. Das sollte mit der nächsten KI-Optimierung behoben sein.

**Comment by nittka** [comment]
Behoben mit den Commits zu #692
