### ISSUE TITLE
Attraktivität von Liveprogramm überprüfen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#648]
*Guybrush41 per Forum:*
> 2) Live-Ausstrahlungen sollten nach dem Sendetermin entweder sich ganz aus dem Angebot verabschieden oder dramatisch an Attraktivität und damit an Preis verlieren.
Die Fußball-WM Finale 1986 und 1990 mögen im Nachhinein noch interessant sein, das 100m Finale der Olympischen Sommerspiele 1988 weniger.

https://www.gamezworld.de/phpforum/viewtopic.php?pid=89787#p89787

**Comment by nittka** [comment]
Die beiden Punkte sollten tatsächlich separat betrachtet werden.

a) Livesendungen nach dem Termin gar nicht mehr kaufen können? Das fände ich gar nicht schlecht. Es gar nicht so viele Lizenzen, die betroffen wären und man spart sich dann die Diskussion, warum 2002 überhaupt noch die Sommerolympiade 1988 angeboten wird. Aufpassen muss man ggf. bei den Sportübertragungsserien, falls diese nicht nur als Auktion zu bekommen wären (zählt der erste oder der letzte Live-Termin). Ausprobieren müsste man auch das Verhalten Live-Lizenz gekauft, nicht gesendet und nach Live-Termin wieder verkauft.

b) Attraktivität einer LiveOnTape-Ausstrahlung: Hier muss man etwas aufpassen, denn es kann schon einen Unterschied machen, wieviel später die Ausstrahlung stattfindet und ob es eine Erstausstrahlung ist. Ich denke hier z.B. an ein (selbst produziertes) Konzert, das mit einer Stunde Verspätung seine Erstausstrahlung hat. Ähnlich könnte es bei den Fußballspielen sein, bei denen ja immer zwei zur selben Zeit laufen.

Selbst produzierte Programme mit einem festen Live-Datum darf man natürlich auch nicht vergessen.

**Comment by nittka** [comment]
Ein erster Ansatz für die Problematik ist durch die Reparatur im PR vorhanden. Live-Programme verlieren nach ihrer "Live-Zeit" automatisch an Maximal-Attraktivität. Eine weitere Konfigurationsoption bieten die Modifier für age (schneller altern) und firstBroadcast (Verlust an Maximal-Attraktivität durch die Erstausstrahlung).
Mit der Unterstützung von Modifiern für Drehbücher hat man damit eine Reihe von Stellschrauben zur Verfügung.

**Comment by nittka** [comment]
Betrachte ich mit dem PR als erledigt.
