### ISSUE TITLE
Filmagentur: Startfilmangebot sehr ähnlich

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#650]
*Guybrush41 per Forum:*
> 1) Es wäre schön wenn zu Beginn eines jeden Spiels die Programme in der Film- und Ramschkisten-Liste besser durchgewürfelt würden. Viel zu oft finden sich dort die selben 13 Items wieder - öfters sogar in der Reihenfolge wie sie in den Dateien gelistet sind. (Bei Serien haben ich das Problem weniger bemerkt)

https://www.gamezworld.de/phpforum/viewtopic.php?pid=89787#p89787

weitere Kommentierung:
>  Ich habe die unveränderte 0.73 Version gerade 5x im Jahre 1985 gestartet und 5x war "...sie waren sich der Konsequenzen nicht bewusst" der erste Film von links in der Ramschkiste. Zudem gehörten Aschenputtel, Asian Queen und die beiden Laurel & Hardy Filme fast immer zu den ersten Filmen in der Gruppe.
>
> Ein ähnliches Bild ergibt sich mit 1899 (...), Computerkrieg und 2002 in der Film-Kiste.

**Comment by nittka** [comment]
1985 könnte das Gesamtfilmangebot tatsächlich zu klein sein - auch in Hinblick auf die Startprogrammauswahl der KIs (Sendeausfall, da zu wenige Filme gekauft).
Für (wesentlich) später liegende Startjahre sollte die Gesamtauswahl allerdings größer geworden sein. Hier müsste man sich für die jeweiligen Startjahre mal die Anzahl der Lizenzen, die die jeweiligen Filter erfüllen anschauen.

Wenn alle vier Spieler am ersten Tag 8 Lizenzen kaufen wollen, braucht man schon mindestens dafür 32 Lizenzen, plus diejenigen, die das Regal auffüllen. Und es sollen ja auch nicht immer dieselben sein...

**Comment by GWRon** [comment]
Das es mehr Programme braucht, ist denke ich "klar".

Inhalte im Sinne von 

Titel,
Beschreibung
Genre

kann ich denke ich schnell "viel" erstellen. Nur die Muße, das ins "DB-Format" zu bringen, die muss ich noch suchen :P

**Comment by nittka** [comment]
Verwandtes Thema ggf. separates Ticket. Ich denke, es werden mehr Programme (und Drehbuchvorlagen) mit Kultur-Flag benötigt. Aktuell gibt es im Startjahr '85 fast ausschließlich "Maler vergangener Zeiten", d.h. der Spieler, der sich diese Serie holt und regelmäßig was sendet, kann fast "konkurrenzlos" Betty-Punkte sammeln. Geschenke und Kulturnachrichten bringen zwar auch ein bisschen, aber Programmausstrahlungen sind weit wirkungsvoller.

Die Idee mit dem fiktiven Material und relativem Produktionsjahr gefällt mir gut, da man dadurch ziemlich genau steuern kann, dass es x Lizenzen mit einer gewissen Qualität und Aktualität gibt.
