### ISSUE TITLE
KI: Fahrstuhl der aktuellen Etage als Navigationsziel erlauben

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#657]
Die KI-Performance leidet z.T. massiv under dem häufigen Schilderumhängen (Werbevertrag nicht erfüllt wegen zu langer Wartezeiten beim Hoch- und Runterfahren). Der Roomboard-Task sollte aufgeteilt werden in "Status prüfen" (muss ich mich verteidigen) und Änderung machen (wenn man sich entschieden hat, einen anderen Spieler zu ärgern).

Aktuell gehen die KI-Spieler immer zur Übersichtstafel, um den Status der Schilder zu prüfen. Es wäre aber sinnvoll, wenn sie vorher beim Fahrstuhl prüfen würden, ob überhaupt eine Änderung nötig ist (so wie es ein menschlicher Spieler auch machen könnte). Dafür ist der Fahrstuhl als Navigationsziel aber eine technische Voraussetzung.

**Comment by nittka** [comment]
Kurzfristig würde ich dieses Thema zurückstellen. Es scheint ein größerer (langfristig sinnvoller) Umbau nötig zu sein.

Für die Verbesserung der KI-Performance gibt es temporäre Workarounds, z.B. den RoomPlanTask massiv runterpriorisieren. Da die Auswirkungen des Terroristen zur Zeit nahezu vernachlässigbar sind, ist der potentielle Verlust für den Verursacher (mehrfach keine Programmoptimierung möglich, da man permanent am Fahrstuhl wartet) viel höher als für das Opfer (einmalig Büro nur kurzzeitig blockiert; oft ist ja auch gar nicht das Büro das Ziel). Im Grunde lohnt es sich also gar nicht, sich überhaupt um den Raumplan zu kümmern.

**Comment by GWRon** [comment]
Wir koennen es auch ganz trivial loesen ...

Wir fuehren den event "onReachElevator" ein ...der wird ausgeloest, wenn sich eine Figur zu einem Raum auf einer anderen Etage bewegt und den Fahrstuhl "anklickt" damit er zur Figur faehrt.

Dann aendern wir "ep_***" (also die kopierten "roomboard"-Funktionen)  so ab, dass sie auch ausgefuehrt werden koennen, wenn man "am Fahrstuhl" ist.

Ergo kann dann die KI innerhalb von "onReachElevator" einfach den Raumplan checken - und nach Bedarf die Prio fuer den "RoomBoard"-Task hochschrauben.


Was haeltst Du davon?

**Comment by nittka** [comment]
Das klingt nach einem interessanten Ansatz.
Folgende Nachteile sehe ich allerdings: Wenn man bei der Umsetzung nicht aufpasst, prüft die KI die Schilder viel häufiger, als das im normalen Spiel der Fall wäre (+tatsächlicher Zeitaufwand für die ganzen Pfrüfungen). Und als normaler Spieler muss man eben den Fahrstuhl anklicken um die Schilder zu sehen. Wenn man eine Tür anklickt, kann mandie Prüfung nicht durchführen. Die KI würde also "schummeln", da die Navigation aktuell ja eben nicht aufgeteilt ist in "gehe zum Fahrstuhl" und "wähle das Zielschild und klicke drauf".

Vielleicht nehme ich mir den ersten Commit einfach nochmal vor und schaue, ob das Überschreiben des GoToRoom-Jobs für die Fahrstuhlprüfung mit wenig Aufwand umsetzbar ist.

**Comment by GWRon** [comment]
Hmm, ja es waere ein Cheaten. Der Spieler kann nicht auf den Fahrstuhl warten und gleichzeitig den Raumplan studieren.

Die KI cheatet ja momentan eh schon - in dem sie Raeume "direkt" anzielen kann, ohne vorher den Fahrstuhlplan zu benoetigen. Der Spieler kann nur innerhalb der sichtbaren Etagen "anklicken" und benoetigt fuer anderes den Fahrstuhlplan.

An der Stelle koennte man den "goto Room" generell umbauen: ist es eine andere Etage, muss der Plan genutzt werden (anklicken und raussuchen). An der Stelle kann natuerlich immer gleich der Plan analysiert werden (oder eben nicht).

Der gotoRoom-Job waere also manchmal zweigeteilt (gotoElevator + gotoRoom).

**Comment by nittka** [comment]
Die von der KI direkt angesteuerten Räume sind auch über Tastenkürzel ansteuerbar. Insofern würde ich das nicht mehr als Cheaten der KI bezeichnen. Das würde ich nicht noch verkomplizieren!
