### ISSUE TITLE
Spiel bleibt beim Wechsel ins Hauptmenü hängen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#671]
Relativ reprozierbar bleibt bei mir das Spiel hängen:
* neues Spiel starten
* Spieler 1 auf KI setzen
* Geschwindigket mit "5" auf 1800 setzen
* ein paar Sekunden warten (5 Uhr Spielzeit)
* Mit Esc Menü öffnen
* Zurück ins Hauptmenü wählen -> Spiel bleibt hängen

**Comment by GWRon** [comment]
Ungetestet: eventuell hat die KI noch offene "events" abzuarbeiten, wird aber nicht mehr "aufgerufen"

**Comment by GWRon** [comment]
Ich bekomme das hier nicht nachvollzogen .. auch mit Taste 6 oder 7 nicht (ich sehe bis zu 4 oder 5 Events in der "Queue/Warteschlange").

Du muesstest also wohl oder uebel alleine den Fehler eingrenzen.

**Comment by nittka** [comment]
Ich habe bei mir mal einige Module aktualisiert (außer SDL da gab's Compile-Fehler, sah so aus als wäre mit dem File-Encoding wieder was kaputt).
Nach der Aktualisierung ließ sich der Fehler nicht mehr nachstellen. Ich mache das Ticket wieder zu.
