### ISSUE TITLE
Absturz Produktion "Episode 9"

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#672]
*Vicusfeli per Forum*:
> Hallo,
>
> ich hatte gerade in folgender Situation einen Absturz:
> 
> Ich habe eine 9 teilige Serie produziert. Die Teile 1-8 hintereinander weg. Als ich dann Teil 9 nach Abschluss der Teile 1-8 in die > Einkaufsliste legen wollte, hat sich das Programm beendet.
> 
> Leider hat das Programm keinen Autosave, weshalb ich 5 Tage verloren habe :-(.
> 
> Bitte implementiert einen Autosave am Tagesende :-).
> 
> LG
> 
> Felix

**Comment by nittka** [comment]
Ich habe (erfolglos) versucht, den Fehler im veröffentlichten Spiel nachzustellen.
* Spiel gestartet
* Serie mit 9 Folgen gekauft
* 8 Einkaufszettel geholt, geplant und in einem Rutsch produziert

Im Studio war dann ein "freier" Einkaufszettel sichtbar, den ich mir vom Studiomanager geholt habe... Ging. Im dümmsten Fall ist das Programm nur zufällig zu diesem Zeitpunkt abgestürzt.

Mit der RandRangeArray-Änderung sollte der Absturz (in der geschilderten Situation) nichts zu tun haben, denn der Fehler tritt beim Erstellen der Drehbücher aus den Vorlagen auf, also wenn das Drehbuch neu zum Händler kommt.

**Comment by nittka** [comment]
Ich mache dieses Ticket mal zu. Autosave ist nun möglich. Der konkrete Fehler konnte nicht reproduziert werden.
