### ISSUE TITLE
Drehbuch: Variablen abhängig von gewählter Elternvariable machbar?

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#675]
```XML
		<scripttemplate product="2" licence_type="3" guid="scripttemplate-random-ron-test">
			<title>
				<de>%TEST%</de>
			</title>
			<description>
				<de>Serie über %TEST% -- %%TEST%_SUB%</de>
			</description>

			<children>
				<scripttemplate index="0" product="2" licence_type="2" guid="scripttemplate-random-ron-test01">
					<title>
						<de>%%TEST%_SUB%</de>
					</title>
				</scripttemplate>
				<scripttemplate index="1" product="2" licence_type="2" guid="scripttemplate-random-ron-test02">
					<title>
						<de>%%TEST_SUB%% - %TEST_SUB%</de>
					</title>
					<variables>
						<test_sub>
							<de>KindTest_SUB1|KindTest_SUB2</de>
						</test_sub>
					</variables>
				</scripttemplate>
			</children>

			<variables>
				<TEST>
					<de>Wein|Bier|Reise</de>
				</TEST>
				<Wein_SUB>
					<de>Schaumwein|Sekt|Rotwein</de>
				</Wein_SUB>
				<Bier_SUB>
					<de>Schwarzbier|Helles|Malz</de>
				</Bier_SUB>
				<Reise_SUB>
					<de>Italien|Frankreich|Deutschland</de>
				</Reise_SUB>
			</variables>

			<jobs>
				<job index="0" function="1" required="1" />
				<job index="1" function="2" required="1" />
				<!-- there might be up to 2 additional roles without
				     further specifications -->
				<job index="2" function="32" required="0" />
				<job index="3" function="32" required="0" />
			</jobs>

			<genres maingenre="0" />
			<blocks value="1" />
			<price min="15000" max="26000" />
			<potential min="50" max="70" slope="45" />
			<outcome min="25" max="35" slope="40" />
			<review min="45" max="65" slope="40" />
			<speed min="35" max="65" slope="50" />
		</scripttemplate>
```

Damit erzeuge ich zumindest in der Beschreibung der Serie zum Beispiel:
```
Serie über Bier -- Malz
```

Bei den Episoden hingegen noch:
```
%%TEST%_SUB%
```
und
```
%KindTest_SUB1% - KindTest_SUB1
```

**Comment by GWRon** [comment]
Generell sollte es an sich klappen -- nur funktioniert "dig/base.util.string.bmx" StringHelper.ExtractPlaceholder() noch nicht ganz - bzw brauchen wir eine Moeglichkeit um "Marker" innerhalb von "Markern" zu erlauben.

```
%VAR%VAR2%%
```
das System liest hier "%Var%" + "(uninteressant)VAR2" und "%%".

Einfach waere hier wohl, wenn man ein zweites Spezialzeichen fuer "innerhalb" festlegt.

```
%VAR$VAR2$%
```
Oder... wenn vom "Einzelzeichen" hin zu "<V>inhalt</V>" umgewechselt wuerde - durch das "ende"-Markieren hat man ja kein Problem mit dem Nesting.
```
<v>VAR<v>SUB</v></v>
```
Daraus erzeugt es in der ersten Runde nur den Inhalt von "SUB" (da fuer das andere nix definiert waere)
Bspweise "Reise"
Beim naechsten Loop (bis zu 20 moeglich - derzeit) steht nun dort `<v>VARReise</v>` - und dort koennten ja Sachen definiert sein.

**Comment by GWRon** [comment]
```XML
			<children>
				<scripttemplate index="0" product="2" licence_type="2" guid="scripttemplate-random-ron-test01">
					<title>
						<de>|v|Titel|v|variant|/v||/v|</de>
					</title>
					<description>
						<de>|v|Inhalt|v|variant|/v||/v|</de>
					</description>
				</scripttemplate>
			</children>
..
			<variables>
				<variant>1|2</variant>
				<Titel1>Wein|Bier|Saft</Titel1>
				<Titel2>Schnitzel|Obst|Gemüse</Titel2>
				<Inhalt1>Heute probieren wir |v|Titel|v|variant|/v||/v|</Inhalt1>
				<Inhalt2>Heute essen wir |v|Titel|v|variant|/v||/v|</Inhalt1>

```

In der Richtung muesste das machbar sein (hier mit dem "pipe" anstatt "open/closing-tag" bzw "groesser/kleiner als"-Zeichen (was bei XML ja encodiert werden muesste)

**Comment by nittka** [comment]
Ich muss mir das nochmal in Ruhe am richtigen Rechner anschauen. Dass kombinierte Variablen im Haupteintrag schon "funktionieren" wäre ja schon was. In Anführungszeichen schreibe ich das, weil man ja für einen Subeintrag für jede Sprache bräuchte (Bier_SUB und Beer_SUB), was das ganze etwas aufbläht. Außer man verwendet eine Workaround wie
`<country>de|en</country> <de_name>Deutschland|...</de_name> <de_ajd>Deutsche|...</de_adj>`

Warum funktioniert die Verwendung genau derselben Variablendefinition in den Subtemplates nicht? Wenn eine Variable einmal aufgelöst wurde, sollte sie doch immer gleich gesetzt werden. Warum erfolgt für das Subtemplate ein erneut komplett neuer Auflösungsversuch, selbst wenn es keine eigene Variablendefinition gibt? Ist das nicht ein Bug? Werden die Variablen nicht korrekt an die Kindelemente weitervererbt? Wenn es keine eigene Definition gibt, sollten die Elternvariablendefinitionen inklusive der bereits gemachten Entscheidungen/Ersetzungen an die Kinder weitergeben werden. Und wenn es eigene Definitionen gibt, sollten sie die Elternvariablen ergänzen (bei gleicher Benennung ersetzen, aber das sollte in der Bestandsdatenbank kaum vorkommen).

Eine alternative Syntax für zusammengesetzte Variablen wäre eine Option. Wie wäre es denn mit vorhandenen "Standards"?
${Titel${variant}}
Zweigleisig zu fahren ist sicher keine schöne Option (Escaping für zwei Varianten), alles auf eine neue Syntax umzustellen ist auch keine schöne Option (Fehleranfälligkeit, Migration von Spielständen mit Bestandstemplates...).

Ich glaube, wir kämen schon ziemlich weit, wenn der erste Punkt geklärt/repariert wäre.

**Comment by GWRon** [comment]
```
	'extracts and returns all placeholders in a text
	'ex.: Hi my name is %NAME% and also ${NAME} or ${NAME${SUB}} (which only sees "SUB")
	Function ExtractPlaceholdersNew:String[](text:String, stripPlaceHolderTag:Int = False)
		Global escapeCharCode:Int = Asc("\")
		'since we hardcoded the tags we can simply use two variables..
		Global placeHolderOpenTagCharCode1:Int = Asc("$")
		Global placeHolderOpenTagCharCode2:Int = Asc("{")
		Global placeHolderCloseTagCharCode:Int = Asc("}")

		Local result:String[]
		Local escapeCharFound:Int = False
		Local placeHolderTagOpen:Int = False
		Local placeHolderStartPos:Int = 0
		Local placeHolderEndPos:Int = 0
		local charCode:Int
		
		For Local i:Int = 0 Until text.length
			charCode = text[i]
			
			'found the start of an escape char: "\${}"
			If charCode = escapeCharCode And Not escapeCharFound
				escapeCharFound = True
				Continue
			EndIf

			'found a placeholder start ("$") but not an escaped one ("\$")
			If charCode = placeHolderOpenTagCharCode1 And Not escapeCharFound
				'and also found the opener ("{")
				If i < text.length and text[i+1] = placeHolderOpenTagCharCode2
					placeHolderTagOpen = True
					placeHolderStartPos = i
				EndIf
			'closing the "inner" one? ("${hello${world}}" - close on last but one "}")
			'-> so finds "${world}"
			ElseIf charCode = placeHolderCloseTagCharCode 
				'add found placeholder
				If placeHolderTagOpen
					placeHolderTagOpen = False
					placeHolderEndPos = i

					if stripPlaceHolderTag
						result :+ [ text[placeHolderStartPos + 2 ..  placeHolderEndPos] ]
					else
						result :+ [ text[placeHolderStartPos ..  placeHolderEndPos + 1] ]
					endif
				EndIf
			EndIf
			
			escapeCharFound = False
		Next
		
		Return result
	End Function
```

Scheint die gewuenschten Platzhalter zu finden:
```
Local test:String = "Hallo ${MAIN${SUB}} \${MAIN${SUB}} \${MAIN\${SUB}}."
Local placeHolders:String[] = StringHelper.ExtractPlaceholdersNew(test, True)
For local p:String = Eachin placeHolders
	print p
Next


print "--- nun mit tags:"
placeHolders = StringHelper.ExtractPlaceholdersNew(test, False)
For local p:String = Eachin placeHolders
	print p
	test = test.replace(p, "hallo")
Next

print "replaced : " + test

placeHolders = StringHelper.ExtractPlaceholdersNew(test, False)
For local p:String = Eachin placeHolders
	print p
Next
```

ergibt:
```
SUB
SUB
--- nun mit tags:
${SUB}
${SUB}
replaced : Hallo ${MAINhallo} \${MAINhallo} \${MAIN\hallo}.
${MAINhallo}
```

Ich koennte nun die 4-5 Codestellen, die ueberhaupt die Platzhalterextraktion verweden erweitern, so dass eben "beide" Varianten ausgelesen werden (`%VAR%` und `${VAR}`).
Wir koennten aber auch die gesamte DB "umschreiben" (auf ${VAR}) und im Spiel dann nur noch den alten Code zusaetzlich abrufen, sofern es sich um einen alten Spielstand handelt (sprich bereits alte "Strings" existieren).

Ebenfalls koennten wir alte XMLs beim Einlesen korrigieren (alte Platzhalter extrahieren und dann mit den neuen ersetzen) - diese Reparatur koennte auch nach dem Einlesen von Spielstaenden durchgefuehrt werden (dazu muesste man aber schauen, welche Objekttypen davon betroffen sind ... Scripts, Licences...)

**Comment by nittka** [comment]
Ich würde das zunächst auf einem Branch liegen (bzw. das Ticket mit dem Snippet offen) lassen. Die Prio ist nicht extrem hoch, da man auch die Drehbuchvorlagen so gestalten kann, dass die neue Funktionalität nicht zwingend erforderlich ist. Der Umbau der gesamten Datenbank/Spielstandkorrektur ist mir dafür zu aufwändig. Es gibt im Moment auch noch wichtigere Themen.
(Hast Du beim Ersetzungscode auch an die "Spielvariablen" für Namensgenerierung etc. gedacht?)

**Comment by GWRon** [comment]
Es ist doch nur eine andere Art der Variablennamen-Extraktion. Es sollte also mit allem funktionieren. 
Kann auch gern beide Funktionen zusammenfuehren, dann sollten fortan beide Varianten moeglich sein...ergo 100% kompatibel.

Fuer bestehende Savegames muesste dann aber besagte Reparatur eingefuehrt werden.

**Comment by nittka** [comment]
Mit der vorgeschlagenen Änderung kann schon vieles gemacht werden. Das ist prima. RANDOMCITY und WORLDTIME belegen ja, dass eine aufwändigere Auswertung prinzipiell möglich ist.
Ausgangspunkt meiner Überlegung war ja, ein Land zu würfeln und dann das dazu passende Adjektiv verwenden zu können. Das geht nun, erfordert aber eine Variable für jedes Land. (Variable country=en|de und dann name_de, adj_de, name_en, adj_en), was bei vielen Ländern entsprechend viele Variablen mit genau einem Wert bedeutet. Komfortabler und syntaktisch kürzer wäre, wenn man den Index der Auswahl einer Variable festlegen könnte:

```
<variant><de>1|2|3</de></variant>
<country><de>Deutschland|Spanien|Frankreich</de></country>
<adj><de>deutsche|spanische|französische</de></adj>

<description><de>In ${country:atIndex(${variant})} gibt es viele ${adj:atIndex(${variant})} Autos.</de></description>
bzw.
<description><de>In ${atIndex(country,${variant})} gibt es viele ${atIndex(adj,${variant})} Autos.</de></description>
```
Auch kleinere Transformationen (firstUpper, firstLower) könnten hilfreich sein.

Alternativ denkbar wäre, in einer Variable alles auf einmal als Liste zu definieren und dann über eine Transformation nur noch das passende Listenelement auszuwählen zu können

```
<data><de>Deutschland,Deutsch,deutsche,deutsches|Spanien,Spanisch,spanische,spanisches</de></data>
<country><de>${split(${data},",",1)}</de></country>
<language<de>${split(${data},",",2)}</de></language>
<adj_neutr><de>${split(${data},",",4)}</de></adj_neutr>
<subj><de>Essen|Fernsehen</de></subj>

<description><de>In ${country} spricht man oft ${language}. ${firstUpper($adj_neutr)} ${subj} gilt als eines der schlechtesten der Welt.</de></description>

Das split ließe sich auch noch vereinfachen, wenn man ein festes Zeichen als Datentrenner festlegt (z.B. ";", d.h. man schreibt nur noch ${split(${data},3)}).

**Comment by GWRon** [comment]
Evtl koennte man auch die scriptexpressions enkodieren und in die variablen packen. Damit waeren dann auch komplexere Dinge umsetzbar

**Comment by nittka** [comment]
Ich würde die Expression-Unterstützung in einem neuen Ticket weiterverfolgen und dieses mit dem PR zumachen.
