### ISSUE TITLE
[DB] "availability" fuer Programmlizenzen einfuehren?

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#678]
Yoshi aus dem Forum:
> Ahoi, ist es möglich Filme so einzustellen dass sie ab einem bestimmten Jahr nicht mehr erscheinen? Bei Werbungen oder Drehbüchern hab ich damit keine Probleme, Filme in der database scheinen aber auf availability nicht zu reagieren.

Meine Replik:
> Wenn man "availability" auswerten wuerde, sollte das natuerlich NUR beim Filmhaendler Relevanz zeigen - wollen ja nicht, dass einem Spieler die Filme entrissen werden

**Comment by nittka** [comment]
Mir fehlt etwas der Anwendungsfall (für den Aufwand, den eine konsistente Umsetzung bedeutet). Wenn etwas einmal erschienen ist, verschwindet es ja typischerweise nicht wieder (ich vernachlässige jetzt mal die Dr Who Classics, von denen ein Großteil nicht mehr existiert).
Wenn es um "Sommerolympiade 1988" geht, glaube ich eher, dass das hätte ein Drehbuch mit beschränkter Ausstrahlungsanzahl sein sollen. Denn ja, es ist nicht so sinnvoll, die 2005 noch im Angebot zu haben. Vielleicht kann man sie einfach viel schneller altern lassen...

**Comment by nittka** [comment]
Im Debug-Bildschirm für den Filmhändler wird der "Crap-Filter" ja schon angezeigt. Vielleicht sollte der einfach schon etwas früher zuschlagen. Ggf. sollten die möglichen Startjahre dafür aber auch nach hinten eingeschränkt werden. Wenn man 2040 startet gibt es keine "guten" Filme mehr.

**Comment by nittka** [comment]
Ist mit #1059 umgesetzt - ein Ausschalten erfolgt allerdings nicht über einen Automatismus (Filme eines bestimmten Alters nicht mehr anbieten), sondern wie bei den Nachrichten als Effekt. D.h. der DB-Parameter wird jetzt ausgewertet. Hauptanwendungsfall dürfte aber das Anschalten mittels Effekt sein (Staffel 2,3,4 erst angeboten, wenn Staffel 1 ausgestrahlt).

Wie geschrieben sorgt der Filter schon dafür, dass zu schlechte Filme nicht mehr angeboten werden. Man muss allerdings auch bedenken, dass z.B. bei einem KI-Bankrott genügend Billigangebote vorhanden sind. Eine Neubewertung sollte auch mit Berücksichtigung der stark erweiterten Datenbank erfolgen.

Ich schließe das Ticket. Ggf. erwünschte Anpassungen am "Crap"-Filter sollten in einem neuen Ticket erfolgen.
