### ISSUE TITLE
erweiterte Unterstützung von Ausdrücken in Templatevariablen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#684]
Nachfolgeticket zu #675. Es gibt nun eine erweiterte Syntax für Variablen, die geschachtelte Variablen unterstützt `${subj_${variant}}`. Schon jetzt werden bestimmte einfache Ausdrücke (GameExpression), die nicht als Variable in der Datenbank definiert werden, aufgelöst. Z.B. `${TIME_YEAR}` analog zu den Spielinformationen `${WORLDTIME:YEAR}`.

Interessant wäre die Möglichkeit, einfache String-Operationen zu unterstützen
* FirstLower
* FirstUpper
* Split

Da diese Operationen Parameter benötigen, stellt sich die Frage, wie die Syntax aussehen könnte. In Anlehnung an die Spielinformationen könnte man die Funktion mit Doppelpunkt von den Parametern trennen und die Parameter mit Komma voneinander:
* `${FirstLower:Bla}` ergibt bla
* `${FirstLower:${otherVar}}` wertet zuerst otherVar aus und macht dann den ersten Buchstaben klein
* `${Split:${otherVar},3} wertet otherVar aus, interpretiert diesen String als "CSV" (Semikolon) und nimmt den dritten Teil; d.h. `${Split:a;b;c,3}` ergibt c.

Für komplexere Logische Ausdrücke sehe ich aktuell keine Notwendigkeit.

**Comment by GWRon** [comment]
"Befehle" wuerde ich gern mit einem Sonderzeichen beginnen lassen ... dann laesst sich das auf einen Blick (bzw mit dem ersten "char") unterscheiden.
Alternativ gaenge auch das Erzwingen von Klammern.
`${.UCFirst:${var}}`
`${.Split:${var},3}`

oder
`${.LCFirst(${var})}`
`${.UCFirst(${var})}`
`${.CSV(${csvVar}, ${indexVar})}`
...

Denke praktisch waere:
LCFirst(s) - "Hello" => "hello"
UCFirst(s) - "hello" => "Hello"
CSV(s, index) - "a,b,c" und "2" ergibt "b" (Kommazeichen als String nicht legitim...)

Wichtig: solche "Funktionen" werden nicht ersetzt, solange sie ein "${...}" enthalten (also unaufgeloeste Variable...) (Ausname "escaped $")

**Comment by nittka** [comment]
Ich habe mir den Auflösungsmechanismus noch nicht genau angeschaut. Aber eine Expressionbehandlung erfolgt ja bereits. Die Idee mit dem vorangestellten Punkt gefällt mir. Eine weitere Klammerung würde ich vermeiden wollen (komplizierteres Parsen). Die Variablenklammern sollten ausreichen und die Auswertung erfolgt ja immer von innen nach außen.
Wie wäre es mit folgendem: Funktionsaufrufe sind an ".fkt" erkennbar, danach folgt der Funktionsname und danach die Parameter für die Funktion. Auf diese Weise müsste für die Auswertung nur auf ".fkt" geachtet werden und der Handler parst dann den Rest (welche Funktion und welche Parameter) und liefert immer einen String zurück.
Anführungszeichen machen die Sache kompliziert, weil man dann für einen String-Parameter aufpassen muss, die Anführungszeichen entweder in den Aufruf zu packe oder in die TemplateVariable (`${.fkt,csv,"a,b,c",2` bzw. `${.fkt,csv,"${variable}",2}`). Listen würde ich immer mit Semikolon trennen (`${.fkt,csv,a;b;c,3}` bzw. `${.fkt,csv,${variable},2}`).

**Comment by GWRon** [comment]
Das fkt-Schluesselwort ist 
- deutsch
- mMn nicht noetig

Solange keine Funktionsaufrufe direkt in anderen Funktionsaufrufen integriert werden (ohne sie in `${}` zu verpacken), ist der Punkt ausreichend.
Eine Funktion wird daran erkannt, dass der "Tag-Inhalt" an erster Stelle den Punkt hat... Braucht also nur eine einzige Ueberpruefung (byte).

Das Klammerparsen hat den Vorteil, dass ein Ende definiert ist.
Bei der csv-Sache wird es problematisch, wenn man Texte erlauben will..die duerfen dann eben nicht den "Trenner" nutzen.

**Comment by nittka** [comment]
* Punkt - OK. 
* Klammern - das Ende braucht nicht extra erkannt zu werden. Wenn Funktionsaufrufe immer in "${}" stehen, ist die Parameterliste bei der schließenden Klammer zuende
* csv - man könnte zwei Varianten anbieten `${.csv,2,${string}}` mit impliziten Trenner Semikolon und `${.split,§,3,${string}}`, d.h. einer Variante, in der man den Trenner definieren kann. Wenn man Trenner und Index an den Anfang der Parameterliste stellt, könnte man selbst Komma als Trenner erlauben, da ja klar ist, wo die "Liste" anfängt. Dann muss man den Trenner natürlich escapen können.

**Comment by GWRon** [comment]
Eventuell hier die Syntax nochmal komplett durchdefinieren:

```
${.functionName:param1:param2}
-> functionName(param1, param2) aufrufen

${.functionName:&quot;string1&quot;:&quot;string\&quot;with quots\&quot;&quot;}
-> functionName("string1", "string ~qwith quots~q") aufrufen

${.functionName:param1:${.otherFunctionName:param1:param2}}
-> otherFunctionName(param1, param2) aufrufen -> otherFunctionResult
-> functionName(param1, otherFunctionResult) aufrufen
```

fuer Personen waere das dann:
```
${.roleName:&quot;die-guid-von-interesse&quot;}
${.roleLastName:&quot;die-guid-von-interesse&quot;}
...
```
also so "flach" wie moeglich vom Aufbau (keine "Untermethoden") ? Oder wie wuerden "Untergruppen" angesprochen werden - ohne neue Trennzeichen einzufordern?

Das gaenge dann, wenn statt Doppelpunkt das Komma oder Semikolon (wiederrum bloed fuer &quot; ...) dabei waere:
```
${.functionName, param1, ${.otherFunctionName, param1, param2}}

${.role:Name, &quot;die-guid-von-interesse&quot;}
${.role:LastName, &quot;die-guid-von-interesse&quot;}
...
```

**Comment by nittka** [comment]
Ich denke, Diskussion im Ticket reicht hier nicht mehr aus (analog Drehbuch-Cheat). Hier braucht es die Erarbeitung eines "Gesamtkonzepts", das man diskutieren kann. Die relevanten Aspekte sind meiner Ansicht nach

* welche "Funktionen" (`${.fncWithParameters}) soll es neben dem Auflösen von in der Datenbank definierten Variablen (`${heroName}`) geben
* an welchen Stelle werden Expressions eingesetzt (und wo soll man sie eingesetzen können)
* welche Kontextinformation ist jeweils vorhanden/nötig (konkrete Licence, damit "cast" ausgewertet werden kann, globale PersonCollection, damit "person" ausgewertet werden kann...)
* welche Syntax ist gewünscht (problematische Fälle), insb. Trenner für Parameter

Persönlich will ich auf keinen Fall Html-Entitäten als Teil der Syntax (`&lt;` oder `&quot;`). Man muss einen guten Kompromiss zwischen Lesbarkeit, einfacher Parsebarekeit. Ich denke auch nicht dass die Entitäten wirklich nötig sind. Dazu müsste man aber eben genauer analyiseren, was wo sinnvoll eingesetzt werden kann.

**Comment by nittka** [comment]
Ich mache dieses Ticket mal zu, da die initiale Umsetzung für Expressions erfolgt ist.
