### ISSUE TITLE
Optimierung: Einige Types mit Structs ersetzen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#693]
Durch den PR #692 ist mir aufgefallen, dass einige der "TVT Aufrufe" von Lua aus Typ-Instanzen erzeugten.

Typ-Instanzen sind "GC verwaltet" und bedeuten somit einen gewissen "Overhead".

Beispiel:

Teil 1:
 `TLuaFunctions.getPotentialAudiencePercentage()`
```
		'percentage of each group in the population
		Local population:TAudience = New TAudience.InitWithBreakdown(1)
		'GetPotentialAudienceModifier returns percentage watching now
		population.Multiply(TBroadcast.GetPotentialAudienceModifier(time))

		'-> GetTotalSum() contains the total percentage of the population
		'   watching TV now
		Return population.GetTotalSum()
```

Teil 2:
Das obig aufgerufene `TBroadcast.GetPotentialAudienceModifier(time)` sieht folgend aus:
```
	Function GetPotentialAudienceModifier:TAudience(time:Long = -1)
		Local modifier:TAudience = New TAudience.InitValue(1, 1)

		'modify according to current hour
		modifier.Multiply( GetPotentialAudiencePercentage_TimeMod(time) )

		'modify according to weather
		'ATTENTION: uses current modificator, not the one at "TIME"
		modifier.Multiply( GetPotentialAudiencePercentage_WeatherMod(time) )

		Return modifier
	End Function
```

Teil 3:
`GetPotentialAudiencePercentage_TimeMod` und ` GetPotentialAudiencePercentage_WeatherMod` wiederum geben auch `Return New TAudience` (mit angepassten Werten) zurueck.

Das bedeutet nun fuer das Zurueckgeben des Prozentwerts (Float -- nicht aufgesplittet als "TAudience") werden 4 Objekte angelegt, und irgendwann danach wieder geloescht (GC ...)
Teil 1: 1x "new TAudience"
Teil 2: 1x "new TAudience" selbst  und zwei "new TAudience" durch die Mod-Aufrufe

Wenn wir nun TAudience umstellen wuerden auf einen "Wrapper" `TAudience ... Field data:SAudience`) und die eigentliche Funktionalitaet in eine Struct `SAudience` packen - dann wuerde dies fuer solch kurzlebige Objekte bedeuten, dass 4 GC-verwaltete Objekte _pro_ Aufruf wegfielen.
(Edit: und da innerhalb von "TAudience" jeweils noch 2 Instanzen von "TAudienceBase" erzeugt werden, sparen wir gar 4+8 also 12 GC-verwaltete Objekte _pro_ Aufruf!)

Nachteil: Derzeit sind "Structs" nicht mit brl.reflection erfassbar, "TAudience"-Objekte braeuchten also eine eigene Serialisierungsfunktion - muss bei der Abaenderung von "Type" zu "Struct" beachtet werden (damit es mit den Speicherstaenden dann kein Problem gibt).

Dadurch, dass TAudience(Base) eben diese Serialisierung schon umgesetzt hat, sollte dies hier einfacher von statten gehen koennen. Waere es nicht der Fall, braeuchte es wohl "TAudienceOLD" oder sowas (und dann greift eine der "Kompatibilitaetshelfer" und man deserialisiert "Savegame-TAudience" nach "TAudienceOLD" und erzeugt dann ein "TAudience.data" aus eben "TAudienceOLD").
Alternativ muesste die Savegame-Funktionalitaet erweitert werden um das Einladen aller Nodes des Objekts in eine "TData" und dann entsprechend eine TAudience-Erzeugung aus eben dieser TData. Sowas klappt aber nur bei "flachen" Objekten gut (also mit Zahlenwerten und keinen "Kinderobjekten" usw.).
Aber wie gesagt ... da hier TAudience(Base) schon die Serialisierung uebernimmt, klappt das denke ich hier gut.

Interessant waere nun, noch andere solche "Datencontainer" zu finden -- und ob die haeufig genug (kurzlebig) im Einsatz sind um eine Optimierung zu rechtfertigen

**Comment by nittka** [comment]
(Ein Problem des konkreten Aufrufs ist ja auch, dass er pro Tag sehr oft ungecachet an bmx geht. Fachlich sinnvoller wäre eine lua-interne Statistik Mo-Fr 0-23 Uhr mit den möglichen Zuschauerzahlen - x% der Gesamtbevölkerung vor dem Bildschirm.)

**Comment by GWRon** [comment]
Diese Werte koennen aber durch GameModifier angepasst werden (bspweise Wettereinfluss). Deswegen gibt es da nicht einfach nur konstante Werte in einer Tabelle ;-)

Am 4. Oktober 2022 07:57:06 MESZ schrieb Alexander Nittka ***@***.***>:

**Comment by nittka** [comment]
(Aber... in der Methode, die aus den Zuschauerwerten das Level ermittelt, stehen dann auch konstante Werte. Ich habe den Code ja auch noch dringelassen. Die Frage ist, ob die KI den Wettereinfluss auf die Zuschauerzahlen einfach abfragen können soll oder ob sie ihn aufgrund eigener Statistiken erst lernen müsste.)

**Comment by nittka** [comment]
Ist dieses Ticket mit PR #694 behoben oder möchtest Du es noch für weitere Optimierungen offen lassen?

**Comment by GWRon** [comment]
Na es gilt auf alle Faelle noch, die im initialen Beitrag erwaehnte Codestelle zu ueberarbeiten:
```
	Method getPotentialAudiencePercentage:Float(day:Int = - 1, hour:Int = -1)
		If day = -1 Then day = GetWorldTime().GetDay()
		If hour = -1 Then hour = GetWorldTime().GetDayHour()
		Local time:Long = GetWorldTime().MakeTime(0, day, hour, 0, 0)
		'percentage of each population group watching now
		'local percentage:TAudience = TBroadcast.GetPotentialAudiencePercentageForHour(hour).GetAvg()

		'percentage of each group in the population
		Local population:TAudience = New TAudience.Set(1, AudienceManager.GetTargetGroupBreakdown())
		'GetPotentialAudienceModifier returns percentage watching now
		population.Multiply(TBroadcast.GetPotentialAudienceModifier(time))

		'-> GetTotalSum() contains the total percentage of the population
		'   watching TV now
		Return population.GetTotalSum()
	End Method
```
-> TAudience wird da nicht mehr gebraucht
