### ISSUE TITLE
Schummeln bei News möglich

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#699]
Wenn man ein Newslevel 3 abonniert, wird dieses erst nach 30 Minuten für das Tages-Max-Level aktiv. Nachrichten, die in diesen 30 Minuten aktiv werden, sind aber sofort für den Spieler sichtbar. Damit ist es (mit Zeitaufwand) möglich, aktuelle Nachrichten zu senden, ohne ein Abonnement bezahlen zu müssen.

**Comment by nittka** [comment]
Die wahrscheinlich einfachste Lösung wäre, das Abonnementlevel 0 zurückzugeben, solange der Set-Zeitpunkt für das Genre in der Zukunft liegt.

**Comment by GWRon** [comment]
Schoen waere es vlt auch, den Abolevel zu fixieren, sobald man eine solche Nachricht kauft.
Klar bliebe es weiterhin ein Problem, dass der Spieler die Nachricht schon ohne Zeitverzug bekommen hat (also "sieht" ob eine Nachricht ankam... auch wenn er sie nicht gekauft hat).

Schaetze aber, dein Ansatz ist da praktikabler und stimmiger.

**Comment by nittka** [comment]
(Ich hab's jedenfalls auf die Schnelle nicht hinbekommen.)
