### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#705]
Auch im Forum wurde das Thema automatisches Speichern schon angesprochen. Mit dem AI-Spiel haben wir ja den Nachweis der technischen Machbarkeit. Bleibt die Frage der Umsetzung (initial über Wert in der DEV.xml)

* Konfigurierbar ja/nein: Speichern zu festem Zeitpunkt (z.B. zu Tagesbeginn)
* Konfigurierbar Zeit (Zeit im Spiel): -1=aus, 6 alle 6 Spielstunden, 24 = einmal am Tag
* Konfigurierbar Realzeit: -1=aus, 15 alle 15 Echtzeitminuten

Vorgeschlagener Dateiname: autosave.xml; beim KI-Spiel würde ich das automatische Speichern dann deaktivieren

**Comment by GWRon** [comment]
oder "autosave_%gameid%" (die Seednummer aus dem Startscreen).

Allerdings kann sich da am ende auch was ansammeln.

Vielleicht auch folgend:
"autosave" fuer Spiele, die noch nicht gespeichert worden
"savename_autosave" fuer Spiele, die als "savename" gespeichert worden (sprich erstmaliges manuelles Speichern ersetzt "autosave" mit "%savename%_autosave")

**Comment by nittka** [comment]
Das klingt nach einer guten Idee. Und was ist Deine Tendenz bezüglich Speicherzeitpunkt?

**Comment by GWRon** [comment]
Meine Tendenz ist...kein Autosave als Standard. Dazu nerven mich die Speicherzeiten zu stark, vor allem, wenn es mitten in einer Interaktion (Programmplaner etc) stattfindet.

Habe dazu also keine allgemeingueltige Praeferenz ;-)

**Comment by GWRon** [comment]
Zwecks Speicherintervall...hm wie machen es denn so die "normalen Spiele"…?

An denen orientieren. Denke Spieltag waere das zu erwartende Intervall.

**Comment by nittka** [comment]
D.h. wir bieten zunächst ausschließlich ein an/aus, wobei zu Tagesanfang gespeichert wird.

**Comment by nittka** [comment]
Mit PR #707 umgesetzt.
