### ISSUE TITLE
Segmentation Fault bei Sortierung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#716]
Es sieht so aus, als würde bei der Sortierung nur berücksichtigt werden, wenn das zweite Objekt null ist.

![sortNPE](https://user-images.githubusercontent.com/2562651/198981040-3e8d4d9a-945a-4a47-9ec5-2611815a461d.png)

**Comment by nittka** [comment]
(führte aber nicht zum Absturz)

**Comment by nittka** [comment]
Der PR behebt erstmal nur das inkonsistente Verhalten der Sortiermethode. Die Grundproblematik, dass der LUA-Aufruf ein GUI-Update auslöst ist davon unberührt.

**Comment by GWRon** [comment]
der PR ist uebernommen. Das urspruengliche Problem ist denke ich das nun schon oft als Problemursache auftretende Multithreading.

Jede "Sicherheitsaktion" die wir einbinden - also bspweise das "deferren" der "RefreshGUIElements_Suitcase()"-Aufrufe zu einem "guiElementsSuitcaseValid = False" (und entsprechendem Refresh-Aufruf im Mainthread sobald die Variable "gecheckt" wird) behebt nicht wirklich das Problem - sondern bekaempft nur die Auswirkungen.
Wir werden immer wieder ueber erratische Fehlerchen stolpern die am Ende eben auf die KI und deren "Agieren" mit den Mainthread-Dingen zu tun haben. Nicht immer laesst sich das dann einfach auf eine bestimmte Stelle zurueckabwickeln.

**Comment by GWRon** [comment]
Der Fehler hier sollte an sich nur auftauchen, wenn Du gerade den KI-Spieler beobachtet hast - hast Du ?

**Comment by nittka** [comment]
Ja, im KI-Spiel wird immer der aktuelle Spieler beobachtet. Es kann sogar sein, dass die KI dadurch behindert wird. Vieleicht sollte man da das "freie im Hochhaus rumscrollen" aktivieren.

**Comment by nittka** [comment]
Ich schließe das Ticket nach den beiden Merges. Bei einem "neuen" beobachteten Segmentation Fault gibt's dann ein neues.
