### ISSUE TITLE
Modus "niemanden beobachten"

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#724]
Die Abstürze mit Segmentation Fault tauchen aktuell ja vor allem in den KI-Schnellspielen auf (zumindest beobachtet man sie dort naturgemäß wesentlich häufiger). Wenn es einen Modus "No Building Rendering" gäbe, in dem man nicht den aktuell ausgewählten Spieler verfolgt sondern einfach nur zwischen den Debug-Bildschirmen (und den Quotenbildschirmen Q) wechseln kann, hätte man einen Teil der Probleme ggf. wegdiskutiert.
* weitere Performancesteigerung für KI-Spiele, da Berechnungszeit für das Rendering entfällt
* potentiell noch weniger Abstürze, da diese Anteile der Zugriffe auf gemeinsame Resourcen entfallen

**Comment by GWRon** [comment]
Unabhaengig von "niemanden beobachten" kann es aber Events geben, die wiederum Events erzeugen ...
Man behebt dort die Auffaelligkeiten die entstehen, wenn das Spiel auf "die Aenderung ist visuell sichtbar" reagiert: also GUI-Erzeugung. Sowas muss halt nur noch indirekt ablaufen ("haveToRefreshGUI = True").

Vielleicht kannst du probieren, dem "zu rendernden Screen" einen "override" zu spendieren - so dass die Figur meint in Bildschirm 1 zu sein, aber DU als Beobachter Bildschirm 2 siehst - also bspweise Debugbildschirme statt Hochhaus/Programmplan/...

**Comment by nittka** [comment]
Sollte es nicht auch einfacher gehen? Drei andere KIs rennen doch ggf. ganz woanders im Haus rum, betreten Räume, die nicht gerendert werden. "Nichtspieler 5", der einfach nur das Hochhaus sieht, in dem alles rumwuselt (wenn man das Rendern nicht komplett unterbinden kann).

**Comment by nittka** [comment]
Hausmeister ist eine gute Idee! Die Tasten H oder J (Hausmeister/Janitor) sind ja auch noch nicht belegt.

**Comment by GWRon** [comment]
```
				GameConfig.observerMode = True '1 - GameConfig.observerMode
				TVTGhostBuildingScrollMode = True '1 - TVTGhostBuildingScrollMode
				GameConfig.SetObservedObject( MainMenuJanitor )
```
Dann beobachtet man keinen "aktiven" Hausmeister.
Eventuell koennte man auch Dinge wie die "Toastmessages" ausschaltbar gestalten - bzw die Toastmessages nur noch hinzufuegen, wenn `player.IsLocalHuman()` - gerade im Schnelldurchlauf denke ich praktikabel.

**Comment by nittka** [comment]
Das mit den Nachrichten ist eine gute Idee. Sie für die KI komplett abzuschalten ist vielleicht zu rigoros - auch beim KI-Spiel sind ja Sachen wie "Werbevertrag fehlgeschlagen", "Sendemast im Bau", "Produktion abgeschlossen", "Sammy ging an..." für die Beobachtung interessant. Tatsächlich ist "Werbung abgeschlossen" die einzige Nachricht, die permanent kommt und "unnötig" ist.
Auch der Sound könnte im KI-Spiel komplett unterdrückt werden.

**Comment by nittka** [comment]
Das obige Snippet geht schon in die richtige Richtung. Für die Debug-Bildschirme würde ich dann mit 1-4 natürlich weiterhin zwischen den Spielern wechseln können. Aktuell wechsele ich dann den beobachteten Spieler (unerwünschtes Folgen in die Räume) und nicht den aktiven (Anzeige des Programmplans).

Das bekomme ich aber hin. Im Prinzip ist das ein weiterer Modus (TVTHighSpeedObservationMode).

**Comment by nittka** [comment]
Mit diesen Änderungen lief das Debug-Spiel wesentlich länger und flüssiger. Höhere Geschwindigkeiten im normalen schnellen Spiel scheinen noch nicht möglich zu sein. Hier gehe ich davon aus, dass nicht das Rendering an sich das Problem ist.
Es könnte sein, dass die Fahrstuhlzeiten (Tempo, Warten) dafür sorgen, dass die KI oft nicht schnell genug im Büro ist, um Werbeausfälle zu verhindern.

Hier plane ich als einen der nächsten Schritte eine Auswertung der Logdateien: durchschnittliche Zeit pro Task, wieviele Tasks jeder Sorte pro Tag, durchschnittliche Zeit, bis man nach Taskstart im Raum war etc.
Wenn man diese Auswertung für lange Spiele mit unterschiedlichen Geschwindigkeiten gegeneinanderhält kann man vielleicht was erkennen.

Auch für Update-Performance-Verbesserungen ist dieser Modus wohl geeignet, da der Rendering-Einfluss verringert ist.

**Comment by GWRon** [comment]
Du kannst Funktionen/Methoden, bei denen Du _SICHER_ bist, dass sie nicht crashen (bzw dir es bei einem Crash egal waere, nicht zu wissen wo es gecrasht ist) hinten ein `NoDebug` anfuegen --- dann erzeugt der Compiler keine Debuginformationen in dem "Block".

Vor allem bei heftigen For-Loops kommt da einiges an Millisekunden zusammen:
https://github.com/bmx-ng/bcc/issues/602

**Comment by nittka** [comment]
Bei mir im Debugmodus komme ich nie auf hohe FPS-Zahlen und auch stabile 5 wären ja OK. Entscheidend ist für mich ja auch, bis zu welcher Geschwindigkeit ich komme und aktuell (mit den Änderungen) sind es ca 800 auch bei langem Spiel. Wie vergleichsweise flüssig es läuft, erkenne ich an der laufenden Uhrzeit. Wenn die schön hochtickert, ist alles gut, unschön sind Sprünge über mehrere Minuten (manchmal 20).

NoDebug wie Du es beschreibst will ich eigentlich nicht benutzen. In den produktiven Code sollte es nicht rein und ich möchte nicht immer alle Dateien anpassen (und neu kopmilieren) müssen. Den Debug-Modus nutze ich aktuell eigentlich nur dafür, Segmentation-Faults auf die Spur zu kommen, die im regulären KI-Spiel auftreten. Vielleicht gehen die mit diesem Beobachtungsmodus aber auch noch weiter zurück, weil ja insb. Thread-Probleme zwischen GUI und KI verantwortlich waren.
