### ISSUE TITLE
Spielstand aus Unterverzeichnis laden

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#733]
Ich habe einen KI-Lauf mal in einem Unterverzeichnis gespeichert, um ihn nicht zu verlieren. Im Laden-Dialog werden die Spielstände dann angezeigt (tmp/...xml). Bei einer Auswahl wird der Spielstand dann aber nicht gespeichert (augenscheinlich weil das Unterverzeichnis beim Ladenaufruf verloren geht).
Ich bestehe nicht auf der Möglichkeit des Ladens (oder direkten Speicherns in einem Unterverzeichnis - missions/money1_schwer.xml mit automatischem Verzeichnisanlegen), aber wenn es nicht funktioniert, sollten beim Laden Unterverzeichnisse nicht mit angezeigt werden.

**Comment by GWRon** [comment]
Schau ich mir an. Sollte kein Problem sein, Unterverzeichnisse zu erlauben (unter Nutzung von Schraegstrichen/Slashes)
