### ISSUE TITLE
[Persistenz] Enum-Felder werden im XML überhaupt nicht serialisiert

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#742]
Ich hatte die Missionsschwierigkeit als Enum statt als Typ mit Konstanten modelliert. Das war wohl keine gute Idee. Nicht nur dass Blitzmax selbst Probleme mit Arrays von Enum-Werten hat (funktinieren nicht), auch die XML-Unterstützung fehlt. Das Feld fehlt im Spielstand komplett.

Ich vermute, dass wir kurzfristig von Enum nach Typ umstellen müssen. Die Frage wäre, ob sich das Ansprechend der XML-Unterstützung lohnt.

**Comment by GWRon** [comment]
Enums werden von brl.reflection ("noch") nicht unterstuetzt - entsprechend auch in den Speicherstaenden nicht erfasst.

Du kannst da derzeit nur ueber den Umweg manueller Serialisierung der "Elternklasse" gehen.

**Comment by nittka** [comment]
Ich stelle den Wert auf Int um und lebe mit der fehlenden Typsicherheit.

**Comment by nittka** [comment]
Ein Test sagt mehr als tausend Worte. Ich kann aber nicht sagen, ob das alles ist, was nicht funktioniert, da es ja noch mehr Optionen bei den Enums gibt.

```
Enum TestEnum
	NONE = 0
	VAL1 = 1
	VAL2 = 7
End Enum

Local value:TestEnum = TestEnum.VAL2
Local array:TestEnum[] = [ value]
Local ordinalArray:Int[] = [ value.ordinal() ]

print "value toString: " + value.toString()
print "value casted: " + TestEnum(value).toString()
print "value ordinal: " + value.ordinal()

print "array toString: " + array[0].toString()
print "array casted: " + TestEnum(array[0]).toString()
print "array ordinal: " + TestEnum(array[0]).ordinal()

print "ordinal array casted: " + TestEnum(ordinalArray[0]).toString()
print "ordinal array ordinal: " + TestEnum(ordinalArray[0]).ordinal()
```

**Comment by GWRon** [comment]
Sieht danach aus, als wenn `Local array:TestEnum[] = [ value]` das Problem ist - wie bei mir im Issue schon geschrieben. Also das "auto assignment"

**Comment by nittka** [comment]
Ich mache dieses Ticket mal zu. Enums sind derzeit nicht einsetzbar. Und der Fix wird nicht hier stattfinden.
