### ISSUE TITLE
Figur geht durch Wände

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#748]
Beim Laden eines Spielstands von 0.7.3 (https://www.gamezworld.de/phpforum/viewtopic.php?id=14019) ist aufgefallen, dass man wohl durch die Anpassung der Pixelrepräsentation in allen Etagen links und rechts aus dem Haus rauslaufen kann!

**Comment by GWRon** [comment]
Du meinst wenn Du im Savegame herumspielst passieren Dinge, die im normalen Spiel nicht passieren?

Ich sehe das nicht direkt als Bug.

**Comment by nittka** [comment]
Nein, ich meine, wenn ich den zur Verfügung gestellten 0.7.3-Spielstand mit der aktuellen Snapshotversion lade, kann ich im Spiel dann links und rechts aus dem Haus rauslaufen.

Auch bei den Drehbüchern haben wir einen Fall nicht berücksichtigt, nämlich dass akuell Produktionen in einem Einer-Studio laufen könnten, die nur in einem Zweier-Studio erlaubt sind. Oder ein solches Drehbuch gerade schon im Studio steht.
Jedenfalls ergeben sich ziemlich seltsame Effekte, wenn ich Spielstand Alt aus dem Ticket lade. Zu dem zweiten noch verfügbaren Drehbuch im Spielstand kann ich mir gar keinen Einkaufszettel geben lassen.

(Ich gehe mal davon aus, dass der Spielstand nicht manipuliert ist.)

**Comment by nittka** [comment]
Das Ursprungsproblem betrifft auch einen definitiv nicht manipulierten Spielstand aus 0.7.3. Es scheint, dass im Spielstand relevante Koordinaten enthalten sind, die dazu führen, dass die "Wände durchlässig werden".

**Comment by GWRon** [comment]
Meines Erachtens liegt das an keinem Savegame - viel mehr wird das an einer der Vec2 oder TargetRoom-Aenderungen liegen - denn auch ein "Neues Spiel" hat diesen Fehler.

**Comment by nittka** [comment]
Ich gebe zu, in einem komplett neu gestarteten Spiel habe ich das gar nicht probiert :-)

**Comment by nittka** [comment]
Kann es sein, dass hier die Umstellung von null auf Position mit negativen Werten (für ungültiges Ziel) ursächlich ist?

Ich habe noch nicht die Stelle rausgefunden, wo der Mausklick in ein Laufziel für die Figur umgewandelt wird. Wenn der Klick außerhalb des Gebäudes erfolgt, sollte gar nicht erst losgelaufen werden. Die Modifikation des Ziels (x-Position des Mausklicks auf innerhalb des Gebäudes umwandeln) wäre möglich, fände ich aber nicht so gut.

**Comment by GWRon** [comment]
Ich finde die Ursache schon... muss aber erstmal noch n Moebelstueck fertigbauen, sonst ist hier wenig Platz fuer ... Deko.

**Comment by nittka** [comment]
closed by #754
