### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by gentilvirus** [TVTower/TVTower#76]
Sorry I don't speak German.
Linux Mint 18 - 64 bit / nvidia GeForce 325M

`[20:20:03] INFO     | CORE: Starting TVTower, v0.3.4.2 Build "01.09.16 21:22".

[20:20:03] LOAD     | TEVENTMANAGER.INIT(): OK
[20:20:03] DBG      | APPLYSETTINGS(): SetFullscreen = 1
[20:20:03] DBG      | SOUNDMANAGER.SETAUDIOENGINE(): initialized with engine "AUTOMATIC".
[20:20:03] DBG      | GRAPHICSMANAGER.INITGRAPHICS(): Initializing graphics.
[20:20:03] DBG      |                               : SetGraphicsDriver "OpenGL".
Segmentation fault
`

**Comment by GWRon** [comment]
Did you use v0.3.4.2 ? I fixed issues with custom user settings which were introduced in v0.3.4.

**Comment by gentilvirus** [comment]
Yes, I use v0.3.4.2
Note that when I use the integrated graphics (GMA HD 500), the game works perfectly fine. It's only when I use the nvidia chip that I get the Segmentation fault error (both on the 32 & 63-bit versions).

**Comment by GWRon** [comment]
Pheeew... I do not have access to such a configuration (multi-gpu).

Do you use the proprietary driver blob from nvidia, or the open source one? Maybe there is a flaw / incompatibility with the ancient way of using OpenGL in TVTower and the driver you use.

**Comment by GWRon** [comment]
Another thing:  could you try if an older TVTower release (0.2.x) works flawless with your nvidia gpu?
Just want to see, if it has to do with the engine itself, or some changes we made during the last months (optimized a bit, how renderers are selected).

**Comment by GWRon** [comment]
I uploaded a new patch (v0.3.4.3) and this time the Linux64-variant uses SDL.

Does that binary work for you? (if so, then it might be an issue with the OGL-renderer).


Download via
http://www.digidea.de/files/TVTower_v0.3.4.3_20160905.Patch.zip

**Comment by GWRon** [comment]
Dawlane from the Blitzmax.com forum:
> The user hasn't given you a lot to go on with the hardware, but it sounds like they are using a machine with a Hybrid graphics system. Not the best supported under Linux.

> Make sure that they have the latest nvidia binary driver (nvidia-361) from the repository and the nvidia-prime package installed.

> General guide for Trusty, but easily adapted for xenial:
https://mintguide.org/video/508-easily-switch-nvidia-hybrid-graphics-nvdia-intel.html 


If not done, you might give that a try

**Comment by gentilvirus** [comment]
Hello,

Sorry if I didn't provide enough info, it's just that I don't really know what could be useful to you.

I use a [Asus N61Jv](https://www.asus.com/Notebooks/N61Jv/specifications/) laptop with hybrid graphics (windows was replaced with Linux Mint 18 64-bit). 
For the Nvidia GeForce GT 325M, I use nividia binary (closed source) drivers 340.96; this is the latest version supported by this GPU.

The nvidia prime package is installed out of the box with linux mint, so I can easily switch between the intel integrated graphics and the nvidia GPU (I just have to log off / log on to restart the X server as unfortunately PRIME/Optimus support isn't as good as on windows but it's not the end of the world!).

I did try the new patch v0.3.4.3 and the game now starts fine with the nvidia GPU but when I quit the game, the screen resolution isn't changed back to 136x768 but remains the one of the game.

I haven't tried v0.2.x. Just let me know if you want me to give a try !

I did just raise this problem to allow you to improve the game for other players and I can provide all the info you ask to help solving this issue (I can live with this "bug", I just try to help).

PS: Thanks for this tribute game, very good job. It reminds me good memories :+1:

**Comment by GWRon** [comment]
> I did try the new patch v0.3.4.3 and the game now starts fine with the nvidia GPU but when I quit the game, the screen resolution isn't changed back to 136x768 but remains the one of the game.

You are talking about `TVTower_Linux64`? Just to clarify things: `TVTower_Linux32` is build with the classic OpenGL-renderengine of BlitzMax while the 64bit variant is using "BlitzMax NG" and "SDL".

If you are OK, I would create some simple test binaries (32bit/64bit, windows, fullscreen) and we would check if they work, and if they reset the desktop resolution correctly.


Meanwhile: in the game you should be able to set up a "windowed mode" resolution - if you pump that up to your screens one, it should help a bit.

**Comment by GWRon** [comment]
Some hours ago a blitzmax.com forum user pointed out the following thread as potential help for your issues:
https://bbs.archlinux.org/viewtopic.php?id=204800

Maybe you could have a look?

**Comment by kyrios123** [comment]
Sorry for the late answer.

It didn't help for this particular problem, but thanks :)

**Comment by nittka** [comment]
Can this ticket be closed? It refers to an outdated version (of TVT and probably BlitzMax as well). If similar problems exist with the current version, a new ticket with updated information can be opened.
