### ISSUE TITLE
"Langer Klick" umbenennen ?

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#763]
Dalli im Discord war verwirrt ueber den "Langen Klick" in den Einstellungen und hat vorgeschlagen, das eindeutiger / sinnstiftender umzubenennen.

"Touchscreen-Steuerung" ?
"Rechtsklick-Emulation" ?

**Comment by nittka** [comment]
Ich wäre für die zweite Variante. Der Beschreibungstext passt schon (Simulation Rechtsklick). Die Feldbeschriftung müsste dann noch entsprechend angepasst werden (Zeit bis Rechtsklick/Rechtsklick nach X ms).

**Comment by nittka** [comment]
Statt Rechtsklick-Emulation vielleicht auch "Alternative für Rechtsklick".
