### ISSUE TITLE
Livesendung unterbricht Serienproduktion in zweitem Studio

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#770]
Meldung im Forum: https://www.gamezworld.de/phpforum/viewtopic.php?id=14022
Der Ablauf Live-Vorproduktion und Serienproduktion während der Ausstrahlung im ersten und einem zusätzlichen Studio müssen nochmal geprüft werden.

**Comment by GWRon** [comment]
Zur schnelleren Nachlesbarkeit (Commithistorie und Co)

_scr0llbaer per Forum:

> Aber zuerst funktionierte es, im Studio, dass man schon beim Spielstart hat.
>
> - Drehbuch für Live-Sendung kaufen und vorproduzieren.
> - Dann ein Drehbuch für einen Film kaufen und so ausstatten, dass die Produktion länger dauert als bis zum Termin der Live-> Sendung, und natürlich im *selben* Studio produzieren
> - Keine Warnung, dass das nicht geht, es funktionert. Im realen Leben kann die Film-Crew ja eben auch mal für die Live-Sendung freimachen. Dachte mir, schön, dass das Spiel das berücksichtigt und so intelligent ist. Produktionszeit für den Film darf dann natürlich dementsprechend länger sein.
> 
> Ein paar Spieltage probierte ich es also wieder, diesmal mit einer Serie und in einem beim Makler gekauften 3er-Studio.
> 
> Leider leider ging es diesmal schief, und das Programm befindet sich in einem fucked-up Status.
> 
> - Die Live-Sendung wurde gesendet
> - Danach war das Studio wieder frei zugänglich
> - Die erste Folge der Serie, die am produzieren war, ist verschwunden.
> - Die Einkaufsliste der ersten Folge ist nicht mehr da, die anderen schon.
> - Der Produktionsleiter meint der erste Teil wurde bereits produziert.
> - Leider ist aber nichts in meinem Archiv
> - Ich kann die Einkaufsliste für die zweite Folge benutzen und versuchen zu produzieren
> - Nach Einkauf im Supermarkt will man ganz normal die Produktion starten
> - Aber es passiert nichts, es wird nichts produziert, und das Studio bleibt betretbar
> - Versuch mit einem neuen Drehbuch: gleiches Phänomen
> - Das Studio wird also unbenutzbar und ich müsste es verkaufen und ein neues kaufen.
> 
> Hoffe das könnt ihr auch nachstellen so.

**Comment by nittka** [comment]
Da Du das wahrscheinlich viel schneller hinbekommst: könntest Du den Dev-Bereich für die Produktionen erweitern (eigene Produktionen.
* Auflistung der Studios
* Drehbuch pro Studio
* Status pro Einkaufsliste (in welchem Studio; nichts/Anzahlung erfolgt/in Produktion/vorproduziert)

Das Bereinigen wäre dann ein weiterer Schritt, aber um den Spielzustand überhaupt erstmal analysieren zu können, wäre das schon wahnsinnig hilfreich.

**Comment by GWRon** [comment]
kann ich gerne machen.

**Comment by nittka** [comment]
Ich konnte den Fehler bislang noch nicht nachstellen (über debug-screen Wäscherei freigemacht und dort die Vorproduktion gestartet und dann eine Serie produziert; hat wie erwartet funktioniert).

Allerdings ist folgender Fehler aufgetreten: Wenn nach der Vorproduktion das Studio wieder abgestoßen wurde (nun freies Studio), wurde die Livesendung dann trotzdem dort produziert und die Serienproduktion im Ursprungsstudio ohne Verlängerung weiterproduziert. Erwartetes Verhalten wäre gewesen, dass die Liveproduktion das eigene Studio verwendet.

**Comment by nittka** [comment]
Im Forumsbeitrag ist ein Spielstand für das Reproduzieren hinterlegt. Wenn man die Produktion für die Serienfolgen startet, wird die Produktion bei Ausstrahlung des Konzerts korrekt unterbrochen. Nach der Ausstrahlung wird aber nicht wie erwartet weiterproduziert. Stattdessen ist das Studio begehbar (und die Einkaufszettel sind seltsam umsortiert).

**Comment by nittka** [comment]
Die Aussage zum kaputten Ausgangszustand war vermutlich falsch (mit falschem Spielstand losgespielt).
Ursache scheint zu sein, dass nicht alle Live-Produktionen das GetProductionManager().StartLiveProductionInStudio(production.GetID()) verwenden um die laufende Produktion zu pausieren.

**Comment by nittka** [comment]
Wenn der ProductionManager sich um alle Live-Produktionen kümmert, tritt das Problem nicht mehr auf; insb. darf sich eine Live-Produktion nicht selbst starten.
