### ISSUE TITLE
[Werbemakler] Sortierung und Einfärbung der Verträge

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#779]
_Cujo per Forum_:

> Im Werbebüro sind im Koffer ja auch schon Ordner aus vorherigen Besuchen drin. Diese Ordner sind aber nicht rot gefärbt, wenn die Werbung am nächsten oder übernächsten Tag fällig sind. Gibt es dafür einen Grund?
>
> Außerdem wäre es schön, wenn die Ordner im Werbebüro-Koffer die gleiche Sortierung hätten wie die Werbeordner im Büro smile

**Comment by GWRon** [comment]
Welche der zwei Sachen wollen wir umsetzen?

Die Sortierung halte ich selbst an sich nicht fuer notwendig, aber machbar.

Die Roteinfaerbung ist ebenso umsetzbar.

Aber spricht etwas dagegen?

**Comment by nittka** [comment]
Ein Sortieren und Einfärben der Werbeverträge hat schon seine Berechtigung. Wobei ich die Sortierung wie die in der Werbeagentur machen würde.

Um schneller zu entscheiden zu können, ob man neue Werbeverträge holt, ist ja die Übersicht über das, was man schon hat wichtig. Und wenn man es nicht auswendig weiß, sind Sortierung und Einfärbung für schnelleres "Hovern" hilfreich.
