### ISSUE TITLE
Autosave: Probleme

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#785]
_lonk per discord_:
> Die Autosaves funktionieren nicht, wenn man verschiedene Spielstände anlegt?
> Ich wechsele öfter mal beim Speichern: Game1 , dann Game2. Seitdem hab ich die Auto-Speichern-Funktion nie wieder gesehen. Die > kam sonst auch bei jedem Verlassen des Nachrichten-Studios.

> Am Beginn des Spielstandes lief sie wie gewünscht, wenn auch viel zu oft (wie erwähnt nach jedem Verlassen des Nachrichten-Studios). Jetzt gar nicht mehr. Ich behalt es mal im Blick

Ronny:
> vlt stimmt bei dir was mit dem Timing von Sachen nicht ... also im Sinne von "Rucklern" ...

lonk:
> Das war mal meine Anfangsvermutung, weil ich oft die Spielgeschwindigkeit herauf- bzw. heruntersetze

**Comment by nittka** [comment]
Das Autospeichern erfolgt immer x Minuten nach dem letzten Speichern. Wenn man selbst also zwischendurch speichert oder neu lädt, wird wieder neu gezählt. So jedenfalls die Theorie.

**Comment by GWRon** [comment]
_lonk per discord_:
> Als die Autosave-Funktion noch bei mir lief, speicherte es viel zu oft, aber damit konnte ich leben. Im fortgeschrittenen Spielstand hab ich sie zum letzten Mal vor x Spieltage gesehen. Sie ist völlig disabled, ohne daß ich sie ausgeschaltet hätte
>
> Ich checke, daß alles bei Gelegenheit und versuche es reproduzierbar zu machen

**Comment by nittka** [comment]
Im laufenden Spiel mal in den Einstellungen nachschauen, ob die Zeit für das Autospeichern zumindest noch drinsteht (ggf. ändern und prüfen, ob es dann wieder geht).

**Comment by GWRon** [comment]
> aha, ist auf 0 gesetzt worden, aber nicht von mir

**Comment by nittka** [comment]
Kann dieses Ticket wieder zugemacht werden? Ich habe auf die Schnelle nicht feststellen können, dass die Einstellungen durch Laden eines alten Spielstands geändert werden. Außer Überschreiben der Settings-Datei/Nochmalrunterladen fällt mir erstmal nichts ein, was den Autosave-Wert wieder auf 0 gesetzt haben könnte.

**Comment by GWRon** [comment]
Dann zumachen.
