### ISSUE TITLE
Negatives Ausstrahlungsdatum

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#790]
siehe Bild:
Ausstrahlung in -4 Tagen

https://ibb.co/3rSTmVd

**Comment by nittka** [comment]
Hatte ich auch noch nicht gesehen... Live-Sendungen mit festem Ausstrahlungstermin sollten in der Agentur rausgefiltert werden, wenn das Datum nicht mehr weit genug in der Zukunft liegt (z.B. 24 Stunden - man muss ja noch Zeit für die Vorproduktion haben).

**Comment by nittka** [comment]
Der PR ist doch noch gar nicht gemergt...
