### ISSUE TITLE
Inkonsistenter Abstand Prozentzeichen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#791]
_lonk per discord_:
![image](https://user-images.githubusercontent.com/2625226/210324984-8b1fd54d-48a2-4c42-9d13-312f7658943f.png)

> das Prozentzeichen hat ein Space davor
> die beiden anderen Anzeigen (Betty & Image) haben keines

Vielleicht betrifft das noch weitere Stellen im Spiel (Statistiken und Co).

**Comment by nittka** [comment]
Immer mit oder immer ohne Leerzeichen anzeigen (mit verbraucht mehr Platz bei kompakten Übersichten)? Die Suche könnte sich schwierig gestalten da % auch für Variablen in der Lokalisierung verwendet wird...

**Comment by GWRon** [comment]
Deswegen hatte ich es auch als Issue aufgemacht.

Ich persoenlich lasse dss Prozentzeichen gerne ohne Leerzeichen der Zahl folgen.
...spart einfach Platz ;-)

Aber die Frage betrifft ja auch Dinge wie

€1000,00
1000,00€
1000,00 €
...

**Comment by nittka** [comment]
Bei den Währungen ist es ja noch "problematischer", da die Position des Währungssymbols von der Währung abhängen kann... (wie wäre es denn mit einer ausgedachten, nicht sprach-/längerspezifischen Währung für das Spiel?)

**Comment by nittka** [comment]
Ich möchte dieses Fass eigentlich auch gar nicht aufmachen. Ggf. genügt es (zunächst), dass die Anzeige innerhalb eines Kontexts (z.B. InGameInterface) konsistent ist und nicht global über alle Räume, Screens, Datasheets.

Ich wäre auch für % ohne führendes Leerzeichen.

**Comment by nittka** [comment]
Das Fass ist schon offen. Unterschiedliche Sprachen verwenden in den Lokalisierungen eigene Währungszeichen, die z.T. nicht zu der Währung im Interface passen.

**Comment by nittka** [comment]
Fix für's Interface vorgeschlagen.
