### ISSUE TITLE
Bug: falsche Programminfo im Sendeplaner

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#798]
Video und Testspielstand:
https://www.file-upload.net/download-15071145/Bug_Programmauswahl_linkes_Fenster.rar.html

Passiert nicht immer, aber ziemlich häufig, daß er Programminfos für das darunterliegende Fenster (Programmplaner) anzeigt, anstatt für die Programme im Koffer.
Schaut man nicht genau hin und achtet lediglich auf Aktualität/Preis, kann es schnell zu Fehlentscheidungen kommen.

**Comment by nittka** [comment]
Auf meinem Linux kann ich den Fehler nicht reproduzieren. Könnte das was plattformspezifisches sein oder mit der Rendering-Engine zu tun haben?

**Comment by lonk0123** [comment]
Es tritt scheinbar nur bei Serien auf, da das "Serien-Auswahl-Menü-Fenster" direkt über dem "Filme-Kategorien-Fenster" liegt, welches wiederum über dem Programmplaner eingeblendet wird. Da scheint irgendetwas durcheinander zu kommen und das Programm weiß zu einem bestimmten Zeitpunkt nicht, daß die beiden letzteren Fenster noch eingeblendet sind. 

Ich könnte mir einen Fehler derart vorstellen, daß zwischen den beiden letztgenannten Fenstern (werden ja nebeneinander eingeblendet) ein Zwischenraum existiert, der beim Mausdrüber-Hovern auf den Programmplaner zurückschaltet.

**Comment by nittka** [comment]
Ich weiß nicht, ob es einen Zusammenhang gibt, aber frameworkseitig könnte die Unterstützung für Mausinteraktion+mehrere Ebenen bzw. Probleme haben. An welchen Stellen merkt man das noch?
* Einblenden Debugscreens - eigentlich legt sich dann eine komplett neue Ebene vor den gesamten Hochhausbereich. Klicks gehen aber doch manchmal auf das Hochhaus (kein Button im Debugscreen, Klick -> Figur läuft an die entsprechende Position)
* Cursoraussehen bei eingeblendetem Menü - im Spiel ist gerade eine Aufheben verboten (Cursor mit Verbot); Menü aufmachen z.B. für Speichern -> der Cursor zeigt noch immer das Verbot, was verwirrend sein kann (Speicher unter diesem Namen nicht möglich?)

Die Information für Hover und Klick wird ja oftmals innerhalb der update-Methoden anhand der Mausposition ermittelt. Hier werden aber nur x und y geprüft. Eigentlich müsste auch noch die aktuelle Ebene (z) einbezogen werden (oder "bin ich überhaupt der aktive Kontext").

**Comment by nittka** [comment]
Ich habe den Fehler bei mir jetzt auch erstmals gesehen. Auslöser könnte das Update des Plans zur vollen Stunde sein:
* in der Programmplanung Programmliste offen (man muss gar keine Kategorie gewählt haben)
* kurz vor voller Stunde (mit der Maus hoch und runter über die Kategorien ohne das Popup zu verlassen, alles OK)
* die Uhr springt auf die neue Stunde
* beim Hoch- und Runterfahren kommen jetzt die Infos zu den Programmen
