### ISSUE TITLE
zu hohe Varianz bzw. unklare Kalkulation der Preise und Zuschauerzahlen von Eigenproduktionen

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#799]
Momentan wirkt es, als würde jemand mit dem Zufallskalkulator auswürfeln, welchen Preis/Zuschauerzahlen die Eigenproduktionen bekommen:
z.B. Serie: Die Abenteuerbande:
1. Folge (Pilot)    5.27 Mio. Zuschauer -->   410.000
2. Folge              8.58 Mio. Zuschauer --> 3.000.000
3. Folge              7.59 Mio. Zuschauer --> 1.400.000
4. Folge              4.34 Mio. Zuschauer --> 3.750.000
usw.

Es scheint so, als ob die Berechnung des Preises die Kategorien Tempo, Kritik, Zuschauer, Aktualität als Basis heranzieht, was auch OK ist.

Wenn dem so ist, scheint mir die Anzahl der Zuschauer fehlerhaft kalkuliert: Wenn die 3. Folge tatsächlich schlechtere Produktionsdaten hervorgebracht hat (was an den Balken zu erkennen ist), dann hätten die Zuschauerzahlen dies auch widerspiegeln müssen im Vergleich zur 4. Folge.

Es kann ruhig etwas Zufall mit im Spiel sein, aber ich vermisse die Nachvollziehbarkeit der Werte.

Bsp.-Spielstand: https://www.file-upload.net/download-15071153/Bug_Einschaltquote_bzw_Preis_von_Eigenproduktionen.zst.html

**Comment by nittka** [comment]
Folge 3 wurde 19 Uhr gesendet, Folge 4 17 Uhr, wo es wesentlich weniger potentielle Zuschauer gibt. Die absoluten Zuschauerzahlen lassen sich also nicht wirklich vergleichen (auch wenn zwischendurch noch Sender gekauft wurden - nicht geprüft). Ein echter Vergleich wäre nur möglich, wenn man die unterschiedlichen Folgen im selben Slot ausstrahlen würde (neu laden, andere Folge senden) und selbst dann hätte man noch Zufallsfaktoren drin. Besser als die absolute Zuschauerzahl wäre noch die Zuschauerquote. Aktuell wird die "beste Quote" aber noch nicht ermittelt und im Datenblatt angezeigt.

Durch die Spielstandgrößenoptimierung sind die Statistiken für die Ausstrahlungen nicht mehr vorhanden, aber aus den noch vorhandenen Statistiken kannst Du ersehen, dass die potentielle Zuschauerzahl 19 Uhr annähernd doppelt so hoch ist wie 17 Uhr.

Der Preis von Folge 4 dürfte auch noch durch die Aktualität beeinflusst sein. Zwischen 90 und 100 % gibt es nochmal Extra-Multiplikatoren für "neu und deshalb teurer" - warten bis hier die Aktualität gleich Folge 2 ist und dann nochmal den Preis vergleichen.

Die Pilotfolge hätten meiner Ansicht nach von den Qualitätszahlen ruhig auch weniger Leute sehen können, aber der Unterschied von 5.3 auf 8.6 Mio zwischen Folge 1 und 2 ist schon deutlich und nachvollziehbar.

Das soll alles nicht heißen, dass der aktuelle Stand der Berechnungen perfekt ist, nur dass die Belege für Fehlberechnungen ungünstig gewählt sind.
Das grundsätzliche Thema Preisberechnung für Eigenproduktionen im Vergleich zu den Produktionskosten haben wir ja auch nochmal an anderer Stelle.

**Comment by nittka** [comment]
Noch ein Hinweis: Die Berechnug der Preise und Einschaltquoten unterscheidet sich nicht zwischen Eigenproduktionen und Filmen aus der Datenbank. Kann das Ticket damit geschlossen werden oder gibt es konkrete Anpassungsvorschläge?

**Comment by lonk0123** [comment]
> Der Preis von Folge 4 dürfte auch noch durch die Aktualität beeinflusst sein. Zwischen 90 und 100 % gibt es nochmal Extra-Multiplikatoren für "neu und deshalb teurer" - warten bis hier die Aktualität gleich Folge 2 ist und dann nochmal den Preis vergleichen.

Folge 4 hat volle Aktualität. Folge 5 fehlt noch ein kleiner Prozentsatz.

Ich finde die Zahlen stellen schon deutlich das Problem dar. Der Unterschied ist halt, Du verteidigst die Zahlen innerhalb des jetzigen Preis-Ermittlungssystems, ich kritisiere das ganze System bzw. halte es für verbesserungsbedürftig, ohne daß ich als "Außenstehender" auf die Schnelle einen Verbesserungsvorschlag präsentieren könnte.
Wahrscheinlich sollte man für Eigenproduktionen die Quoten stärker heranziehen und die Preise generell etwas nach unten korrigieren.

Alle Serienteile haben zur jeweiligen Sendezeit ungefähr die gleichen Riesenquoten gebracht (um die 50%).
Auch der Pilot. Er sollte nicht nur 1/10 des Preises der anderen Teile ausmachen.
Bzw. wenn er tatsächlich bei Tempo, Kritik, Zuschauer, wesentlich schlechter einzustufen ist, als alle anderen produzierten Teile danach (was der Fall ist), hätte die Zuschauerzahl nicht derart hoch ausfallen dürfen. 
Pilot vs. Folge 1:
Preis 14%, Zuschauer 61%

Thema kann aber geschlossen werden, da das momentan implementierte System funktionsfähig (im Sinne von es liefert Zahlen) ist. Für eine Wirtschaftssimulation denke ich, ist noch Spielraum nach oben.

**Comment by nittka** [comment]
Nur nochmal zur Einordnung. Das Ursprungsticket klang nach "es gibt gar kein System und die Zahlen wirken alle gewürfelt" mit Beispielen aus dem Spielstand. Ich habe dann die Zahlen tatsächlich auch nur innerhalb der bestehenden Implementierung als konsistent und "nachvollziehbar" verteidigt (insb. nicht dass es die perfekte Lösung ist, und ich mit allem zufrieden bin). Insofern fand ich es gerechtfertigt, das Ticket als "Frage beantwortet" zuzumachen.

Ich denke, wir sind uns alle einig, dass Verbesserungspotential da ist. Ich glaube aber nicht, dass das komplexe Thema Filmalter/Qualität/Preise/Einschaltquoten (von der Problematik Eigenproduktion und deren Preisen ganz zu schweigen) in einem einzigen Ticket ausdiskutierbar und lösbar ist. Mein Vorschlag wäre daher analog den Personenattributen im Dokumentationsrepo einen Branch aufzumachen und in einem/mehreren Dokumenten mal ein Zielbild, grob den aktuellen Stand, die Bauchschmerzen aufzulisten und Lösungsansätze zu sammeln.
Das kann dann diskutiert und verfeinert werden, bis wir uns auf einen Satz von möglichen Anpassungen geeinigt haben, die dann in einem Ticket/PR hier umgesetzt werden.

**Comment by GWRon** [comment]
Eventuell kann auch der Bereich "discussions" dafuer genutzt werden..bin da flexibel.

**Comment by nittka** [comment]
Ein Thread in discussions entspricht ja etwa einem Ticket. Deshalb würde ich das Doku-Repo bevorzugen (mit dem Ziel einen Satz strukturierter Dokumente zu erstellen, aus denen sich am Ende dann Implementierungstickets ergeben).
Da es um so viele miteinander verwobene Themen geht, zerfasert sonst eine "lineare" Diskussion zu leicht und wichtige Punkte/Ideen aus der Mitte gehen ggf. verloren.
