### ISSUE TITLE
Wie verhält sich die Quotenberechnung (und das Image) wenn ein Spieler ausscheidet / Pleite geht?

### ISSUE THREAD

**Issue by STARSCrazy** [TVTower/TVTower#8]
Wie verhalten sich die Algorithmen wenn ein Spieler (oder eine KI) ausscheidet Pleite geht?

Zu prüfen, wenn irgendwann möglich:
- Quotenberechnung (Market-Aufteilung)
- Image-Berechnung
  usw.

**Comment by GWRon** [comment]
Momentan werden Spieler nach ihrem Bankrott von neuen Sendern ersetzt.
