### ISSUE TITLE
Bug: kaputter Savegame

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#800]
https://www.file-upload.net/download-15071210/DDR_NEU5.zst.html

Beim Einladen:
EXCEPTION_ACCESS_VIOLATION

**Comment by GWRon** [comment]
Ich habe versucht den Speicherstand mit "unzstd" (command line) zu entpacken:
`Decoding error (36) : Corrupted block detected`

Dann habe ich das ganze byte-per-byte entpacken lassen und nach knapp 32MB XML war "schluss", hoerte mittendrin auf.

Das Archiv selbst ist 2,5MB ... so aehnlich wie DDR_NEU4.zst - was sich entpacken liess.
Wenn man nun nach obigem Fehler sucht ... kann es durchaus sein, dass es sich um einen Fehler in den Komprimierungsalgorithmen handelt.
Dann wuerden wir auf einen anderen Kompressionsalgorithmus ausweichen muessen.

**Comment by GWRon** [comment]
Ich habe lokal mal auf "gzip" umgestellt (2 Zeilen Aenderung...) ... was langsamer als zstd ist. Wobei "langsamer" hier zwar 10% sein koennen, aber am Ende macht es bei mir einen Unterschied von 20ms aus (450 vs 420 oder aehnliches), gleiches beim Entpacken.

"Einladen" kann bequem um die Unterstuetzung mehrerer Kompressionsformate erweitert werden (es probiert dann die "aktivierten" aus). 
Kurzum: wir koennten auf ein anderes Format umsteigen - und "zst" per Konfiguration einstellbar machen.

Allerdings waere das alles nicht noetig, wenn der Fehler nicht in der Bibliothek/Algorithmik laege ... bisher konnte ich _meine_ Savegames und die gemailten ja alle einladen. Nur dieser hier tanzte aus der Reihe.

**Comment by nittka** [comment]
Ist dieses Ticket mit dem gzip-Commit gelöst, oder soll hier noch etwas passieren?

**Comment by GWRon** [comment]
Ich warte noch ab, ob das Problem in den naechsten Tagen erneut auftritt.

**Comment by lonk0123** [comment]
Heute keine Probleme mehr. Sollte sich damit erledigt haben.
