### ISSUE TITLE
Bug: Serienteil 4 von 3

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#801]
Screenshot + Spielstand:
https://ibb.co/17ZFGcP
https://easyupload.io/xcq0bt

Irgendwie hat das Studio scheinbar nicht in der "richtigen" Reihenfolge produziert oder ich hab es nicht in der Reihenfolge 1,2,3...
in Auftrag gegeben.

Ist jetzt nichts Schlimmes, sieht aber komisch aus. 
Evtl. sind aber auch Arraygrößen betroffen...

**Comment by nittka** [comment]
Ohne draufgeschaut zu haben liegt es vermutlich an der Auftragsreihenfolge. Zuerst wird die Folgennummer angegeben, dann die Anzahl schon vorhandener Folgen.

**Comment by lonk0123** [comment]
Ja, kam mir auch gerade in den Sinn. 
Sieht halt sehr merkwürdig aus.

**Comment by lonk0123** [comment]
ok, ist überall so (auch im Programmplaner):
https://ibb.co/MnmjzH4
