### ISSUE TITLE
2x gleicher Hauptdarsteller bei Eigenproduktion

### ISSUE THREAD

**Issue by Marathony** [TVTower/TVTower#807]
Mir ist bei einer Eigenproduktion (Die Geisterakademie #2) aufgefallen, dass der gleiche Schauspieler zwei Hauptrollen übernehmen kann. Es gibt schon Filme, bei denen ein Schauspieler mehrere Rollen übernommen hat, aber im Grunde ist das sehr selten. Ich bin mir daher nicht sicher, ob es Absicht oder ein Fehler ist.

Ich persönlich fände es besser, wenn ein Schauspieler nur eine Rolle pro Film übernehmen könnte.

**Comment by GWRon** [comment]
Das ist Absicht. Es gibt ja die Eddie Murphy -Filme etc 


Was man aber machen kann ...ist eben die Chance auf einen Erfolg einer solchen "in Personalunion"-Produktion ein wenig zufaellig zu gestalten.

Oder man verbietet es, mehrere "Rollen" einer Person zuzuweisen. Betrifft denke nur Hauptdarsteller, Nebendarsteller, Gast und Musiker. Also einfach um eine Talkshow mit 3x Betty zu vermeiden.

Ich weiss nicht, ob man "Person uebernimmt drei Rollen" auch visualieren muss...
Waere nur relevant, wenn das auch eine Rolle spielt, dass hier jemand alles alleine stemmt.

**Comment by Marathony** [comment]
Also, bei einer Talkshow sollte man es auf jeden Fall verbieten.

**Comment by lonk0123** [comment]
Die Filme, in denen ein Darsteller mehrere Rollen übernimmt, stellen ja die absolute Seltenheit dar.
Insofern bin ich dafür, Doppelbesetzungen (der Einfachheit) generell zu verbieten, da es momentan scheinbar auch zu überzogenen Einschaltquoten führt (zumindest sollte es so sein, daß die Produktionskosten inkl. Darstellern sich im momentanen System hauptanteilig in der zu erreichenden Quote widerspiegeln).

Ich habe des Öfteren von Doppelbesetzungen zu Testzwecken Gebrauch gemacht, was zwar, wie geschildert, die Produktionskosten in die Höhe treibt. Dafür hat bis auf eine einzige Eigenproduktion bisher noch keine unter 40% Einschaltquote gelegen.

Das jetzige System führt m.M. zu folgendem Spielsystem, welches dem Spieler praktisch keine Entscheidungen abverlangt und daher "schlecht" konzipiert ist (schlecht, i.S. von zu einfach):
1) Wähle den Schauspieler, der am meisten kostet (die Genrespezialisierung spielt eine zu geringe Rolle) 
2) Wähle, wenn möglich, diesen Schauspieler doppelt (da keine Mali)
Quotengarant fertig.

Ich kenne halt die internen Zahlen nicht, aber es sollte z.B. schon so sein, da ein Komödien-Spezialist, der 25.000 kostet, annähernd einem doppelt so teuren Schauspieler gleichzustellen ist, der nicht auf Komödie spezialisiert ist.
