### ISSUE TITLE
30. Februar

### ISSUE THREAD

**Issue by Marathony** [TVTower/TVTower#808]
TVTower ist seiner Zeit voraus...da gibt es sogar einen 30. Februar :)

![screenshot_002](https://user-images.githubusercontent.com/47776686/211213234-79fdc1f6-9e66-4c7d-a50d-68caa77958f0.png)

**Comment by GWRon** [comment]
Das ist als Ausgleich fuer den Mangel an Schaltjahren gedacht... Oder so.

**Comment by nittka** [comment]
Ich frage mich, ob das genaue Datum eine Rolle spielt. Man könnte auch einfach "Monat: 1986-02" hinschreiben. Dass intern noch ein Tag hochtickert, ist für den Spieler irrelevant.

**Comment by nittka** [comment]
Das Spiel geht der Einfachheit halber (wie Banken) von einem Jahr mit 12 Monaten mit je 30 Tagen aus. Ich halte das grundsätzlich für unproblematisch.
... Ich würde das Ticket gern ohne Änderung zumachen. Meinungen?

**Comment by Marathony** [comment]
Ich finde den Vorschlag gut, den Tag wegzulassen. Es ist zwar keine große Sache, aber es wäre eine Möglichkeit unnötige Verwirrung zu vermeiden.

**Comment by Marathony** [comment]
Ich verstehe auch nicht, was Tag des Jahres: 2/12 bedeuten soll.

**Comment by nittka** [comment]
Na das ist der zweite Spieltag in diesem Jahr (von 12). In der Standardkonfiguration gibt es pro Jahreszeit 3 Tage (4*3=12, was einem Spieltag pro "Realmonat" entspricht). Man kann aber auch andere Werte konfigurieren. Ein "Jahr" vergeht dann schneller oder langsamer.

**Comment by Marathony** [comment]
Spieltag des Jahres bzw. Jahresspieltag wäre dann eindeutiger. Könnte vom Platz her aber eng werden :)

**Comment by Marathony** [comment]
Eigentlich könnte die Angabe auch entfallen. Oben steht der Spieltag. Unten der Monat. Das sollte reichen.

**Comment by GWRon** [comment]
"Spieltag" ist fortlaufend, 
"Tag des Jahres" = startet jedes Jahr aufs Neue

Das Weglassen der "Tage" in der Datumsangabe ist an sich OK, war aber enthalten fuer den Fall, dass man bspweise 365 Spieltage pro Jahr moechte (soll ja Interessenten fuer sowas geben). Die wollen dann denke ich ungern ausrechnen, welcher Juli denn nun der 189. Spieltag des Jahres ist. (Wer mit 365 Spieltagen pro Jahr spielt, will vielleicht sein Programm auch am 24.12. anders gestalten - einfach so als "Rollenspieler").

**Comment by Marathony** [comment]
Könnte man es nicht optional machen? Dass die Tage nur dann angezeigt werden, wenn jemand 365 Tage spielen will?

**Comment by nittka** [comment]
Den Aufwand möchte ich jetzt vermeiden. Wenn überhaupt jemand an den Tagen pro Jahr schraubt, dann eher, um die Anzahl zu reduzieren, nicht um in "Realzeit" zu spielen.
