### ISSUE TITLE
Fernsehfamilie sitzt übereinander

### ISSUE THREAD

**Issue by Marathony** [TVTower/TVTower#809]
![screenshot_003](https://user-images.githubusercontent.com/47776686/211224247-b026afe0-dde4-4fb3-9e94-99c018499c36.png)

Der Manager sitzt auf dem Schoß des Jugendlichen :)

Das Savegame findet ihr hier:

https://www.file-upload.net/download-15073085/Cujo24.xml.html

**Comment by Marathony** [comment]
Im laufenden Spiel. Es ist danach auch öfters passiert. Vorher aber nicht.

**Comment by nittka** [comment]
Nach dem Laden des obigen Spielstands sitzen sie bei mir "richtig". Ich habe aber in einem Vorspulspiel bei der KI auch (sehr selten) mal jemanden auf dem Schoß sitzen sehen. Die Schwierigkeit wird sein, die Konstellation nachzustellen (wer saß vorher wo).

**Comment by nittka** [comment]
Ursache gefunden - richtige Position wurde berechnet, dann aber nicht verwendet.
