### ISSUE TITLE
Verkaufserlös der Antennenstandorte wird teilweise abgezogen

### ISSUE THREAD

**Issue by Marathony** [TVTower/TVTower#810]
Beim Verkauf der Antennenstandorte wird der Erlös teilweise abgezogen.

Bei diesem Savegame:

https://www.file-upload.net/download-15073085/Cujo24.xml.html

wird bei den Standorten 2, 3 und 4 der Erlös abgezogen. Bei 5 und 7 addiert (so wie es sein soll).

**Comment by nittka** [comment]
Ich habe mir den Spielstand noch nicht angeschaut, aber wenn die Antennen zu alt sind, gibt es keinen Erlös sondern Verschrottungskosten. Im Spiel sollte die Zahl dann rot sein (als Indikator, dass es etwas kostet).

**Comment by GWRon** [comment]
das rot ist vielleicht doch zu schwer zu erkennen. Evtl sollte ein "Minus" da besser sein (dann wuerde es aber von anderen Finanz-Anzeigen abweichen).
![sendemasten](https://user-images.githubusercontent.com/2625226/211322579-7097d928-de78-4cb1-b76c-f884494c9e80.gif)

**Comment by nittka** [comment]
Im konkreten Fall (Verkauf Sender) finde ich Minus und rot OK. Bei der Zuschauerzahl steht ja schließlich auch ein Minus (so viele werden es weniger), beim Verschrottungskosten ist es eben "so viel Geld wird es weniger".

**Comment by Marathony** [comment]
Ich fände ein zusätzliches Minus auch besser. Der Unterschied zwischen rot und schwarz ist nicht allzu groß.

**Comment by nittka** [comment]
PR ist gestellt. Ich würde mich tatsächlich zunächst auf die Senderkarte beschränken. An anderen Stellen ist es ja weniger so, dass das Vorzeichen im selben Feld wechselt, was bei den Antennen zu Verwirrung geführt hat.

**Comment by GWRon** [comment]
Im PR schlug ich vor, die Geldbox auch noch rot einzufaerben
![image](https://user-images.githubusercontent.com/2625226/211666664-c5b17bd6-9157-43f5-8a51-d2be5092566d.png)

An anderen Stellen wird das aber fuer "schiefgelaufen" genommen - und auf der Senderkarte, wenn man sich etwas nicht leisten kann (Sendemast zu teuer).

Was die Frage aufwirft: darf man einen Sendemast verschrotten, wenn das Geld dafuer nicht ausreicht? Sollten wir das "blockieren" wollen, waere der rote Hintergrund fuer eben diesen Fall einzusetzen
