### ISSUE TITLE
13 Werbeverträge nutzen

### ISSUE THREAD

**Issue by Marathony** [TVTower/TVTower#812]
Es gibt einen schönen Trick, wie man (mindestens) 13 Werbeverträge nutzen kann, obwohl nur 12 in den Koffer passen:

Werbevertrag A in den Koffer legen
Werbevertrag B nehmen und auf Werbevertrag A legen
Der Werbevertrag B ist jetzt im Koffer und der Werbevertrag A in der Hand
Jetzt rechte Maustaste drücken
Der Werbevertrag A wird nicht zurückgelegt, sondern wandert in die linke obere Bildschirmecke. Dort bleibt er auch hängen, wenn ich das Werbebüro verlasse.
Wenn ein Werbevertrag erfüllt ist, rutscht der 13. Werbevertrag automatisch nach :)

Ihr müsst den Bug übrigens nicht unbedingt fixen, wenn ihr nicht wollt :)

BS: Ubuntu 22.04 Vers. 0.8

![screenshot_005](https://user-images.githubusercontent.com/47776686/211414732-24fa4086-8ea7-4170-92f5-b22895266079.png)
![screenshot_006](https://user-images.githubusercontent.com/47776686/211414738-596a3b9c-b623-4b0e-9dda-ef89166034a7.png)

https://www.file-upload.net/download-15073643/Cujo28.xml.html

**Comment by nittka** [comment]
Das könnte auch Drehbücher, Filme und Geschenke betreffen. Am einfachsten wäre eigentlich, dass ein Drop auf ein existierendes Element unterbunden wird, wenn der Koffer schon voll ist.

**Comment by Marathony** [comment]
> Am einfachsten wäre eigentlich, dass ein Drop auf ein existierendes Element unterbunden wird, wenn der Koffer schon voll ist.

Das wäre für den Spieler aber ziemlich umständlich. Er müsste den Ordner in den Hand zurück zum Tisch bewegen und ihn dort fallen lassen. Dann zurück zum Koffer den dortigen Ordner nehmen, zum Tisch bringen und dort fallen lassen. Den tatsächlich gewünschten Werbevertrag kann er erst jetzt nehmen und zum Koffer bringen.

Eine gute Usability sieht anders aus :)

**Comment by nittka** [comment]
Ich habe nicht gesagt, dass es die schönste Lösung ist - Ansatz mit dem vermeintlich geringsten Implementierungsaufwand. Nicht zu unterschätzen sind die Probleme die sich ergeben, wenn das gerade in der Hand befindliche Objekt kein DefaultDropTarget hat (Koffer voll, kann aber nicht zurückgegeben werden). Wenn dann nämlich ein KickFromRoom kommt, ist man sofort in einem inkonsistenten Zustand.
Insofern ist das Problem schon ziemlich involviert.

Betreffen wird es vor allem auch die Studios. Da kann der Koffer nämlich erlaubterweise voll sein, das Studioskript muss aber tauschbar sein - da hatten wir schonmal eine längere Probierphase, bis das halbwegs stabil war...

**Comment by nittka** [comment]
@GWRon Ich weise Dir das Ticket mal zu, da hier mehr Framework involviert ist.
