### ISSUE TITLE
Anpassung von 2 Farben bei kundenspezifischen Werbeverträgen

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#813]
Könnte evtl. für 2 Gruppen: 
1) Rentner vs. Unternehmer (blau)
2) Jugendliche vs. Frauen (beide grün, siehe https://ibb.co/NpnmNh6)
das eingefärbte Kästchen angepaßt werden, so daß man die einzelnen Zielgruppen deutlicher an der unterschiedlichen Farbe erkennen kann.

Gelb, Violet (Frauen) und Braun oder Grau sollten z.B. noch zur Verfügung stehen.

**Comment by nittka** [comment]
Die Farbdefinitionen sind in config/screen_elements.xml (gfx_contracts...), die Zielgruppendefinitionen in gameconstants.bmx (https://github.com/TVTower/TVTower/blob/1417a00063d43d836c98657696520d0338d4219b/source/game.gameconstants.bmx#L1612).

Wie wäre es, wenn Du bei Dir lokal einen Vorschlag erarbeitest und einen Pull-Request erstellst?

**Comment by lonk0123** [comment]
Kann kein Pull Request erstellen (da kommt immer nur ein "compare changes"), darum schreib ich die Änderungen hier:


Arbeitslose, Jugend & Frauen hatten bisher die gleiche Farbe (grün):
Die Jugend behält grün, da sie noch ganz grün hinter den Ohren ist.
Änderung: 
Arbeitslose -> Braun
Frauen -> Pink

Rentner und Arbeitnehmer hatten bisher blau
Änderung:
Rentner -> Grau (Haarfarbe)

neuer Code (Änderung der RGB-Werte in contracts_base & contract_base_dragged):

`
			<scripts>
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_1"		x="22"		r="200"		g="60"		b="40" />
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_2"		x="43"		r="40"		g="200"		b="40" />
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_3"		x="64"		r="100"		g="100"		b="200" />
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_4"		x="85"		r="20"		g="140"		b="180" />
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_5"		x="106"		r="185"		g="125"		b="90" />
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_6"		x="127"		r="150"		g="150"		b="200" />
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_7"		x="148"		r="170"		g="170"		b="170" />
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_8"		x="169"		r="255"		g="95"		b="255" />
				<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_9"		x="190"		r="90"		g="90"		b="150" />

				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_1_dragged"	x="22"		r="200"		g="60"		b="40" />
				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_2_dragged"	x="43"		r="40"		g="200"		b="40" />
				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_3_dragged"	x="64"		r="100"		g="100"		b="200" />
				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_4_dragged"	x="85"		r="20"		g="140"		b="180" />
				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_5_dragged"	x="106"		r="185"		g="125"		b="90" />
				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_6_dragged"	x="127"		r="150"		g="150"		b="200" />
				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_7_dragged"	x="148"		r="170"		g="170"		b="170" />
				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_8_dragged"	x="169"		r="255"		g="95"		b="255" />
				<script do="AddCopySprite"	src="gfx_contracts_base_dragged"	dest="gfx_contracts_9_dragged"	x="190"		r="90"		g="90"		b="150" />
			</scripts>`

**Comment by GWRon** [comment]
Einfach drei Backticks 
\`\`\`OptionalerProgrammiersprachenName(Lua,Blitzmax,...)
code
\`\`\`
nutzen.

Koennen gern zum Thema "PR" telefonieren.

**Comment by nittka** [comment]
Der Unterschied zwischen Manager und Rentner ist mir noch nicht groß genug (wenn man schon mal dabei ist). Auch Männer und Hausfrauen könnten sich noch stärker unterscheiden.

**Comment by GWRon** [comment]
Als "followup" koennten wir die Farbcodes auch anderweitig noch definieren und im Spiel direkt nutzen - bspweise als "Rahmen" um die Zielgruppen im Tooltip oder so - damit man schneller passiv "lernt".

**Comment by lonk0123** [comment]
Wenn stärkere Unterschiede gewünscht sind, setz ich mich sofort noch mal ran. Ich glaube gelb konnte auch noch vergeben werden...

**Comment by nittka** [comment]
Von mir aus gern.

**Comment by nittka** [comment]
![werbung_farben](https://user-images.githubusercontent.com/2562651/212391927-4b8c56e7-34fe-4866-8534-afee8c0ff2b8.png)

sieht für mich OK aus. Grundsätzlich vorgesehen sind ja auch noch Werbeverträge mit Genreeinschränkungen. Vermutlich sollten die dann eine andere Kennzeichnung bekommen. Oder man sieht eine weitere Farbe schon für diese Kategorie von Verträgen vor.

**Comment by lonk0123** [comment]
Aha. Klingt ja interessant. 
Sportfans wären als Kategorie (ala Empire TV-Tycoon) auch noch vorstellbar.
Das mit den Einschränkungen muß man dann ganz besonders markieren. Bei den Farben sehe ich keine Möglichkeiten mehr.

Hier müßte man vermutlich den gesamten Ordner farblich umrahmen, als Hinweis, das dann im dazugehörigen Werbe-Beschreibungsfenster weitere Hinweise bzgl. der Einschränkungen zu finden sind.

**Comment by GWRon** [comment]
Man kann auch overlays einfuehren... N kleinen Stern oder aehnliches.

**Comment by nittka** [comment]
@lonk0123: möchtest Du den PR für diese Änderung stellen oder soll das jemand von uns machen?

**Comment by lonk0123** [comment]
Ich glaube, daß ich vorerst kaum zu Codeänderungen größeren Umfanges in lua bereit sein werde. Ich verstehe zwar alles (Code lesen), könnte aber noch keinen neuen Code verfassen, da ich auch die Möglichkeit zu debuggen (Einzelschritt-Tracing etc.) bisher noch nicht in Blitzmax gefunden habe.

Von daher wäre es ganz lieb, wenn Du das für mich machen könntest.

Vielen lieben Dank!

**Comment by GWRon** [comment]
Nur als Nebeninfo:
in MaxIDE (oder VS Code) den Code aufmachen, an der gewuenschten Eintrittstelle ein "debugstop" einfuegen, kompilieren, ausfuehren. Im DebugBuild wuerde dann an der Stelle gestoppt und du kannst "step by step" vorwaerts gehen.
Etwas notduerftig, aber fuer viele Sachen ausreichend.

**Comment by nittka** [comment]
Diese Änderung wären ja wirklich nur die Farbdefinitionen in der XML-Datei gewesen - kein Lua, kein Blitzmax. Aber ich kann den PR natürlich auch machen.

**Comment by nittka** [comment]
Ist durch den PR gelöst. Für die Verwendung der Zielgruppenfarben an anderer Stelle wurde ein neues Ticket aufgemacht.
