### ISSUE TITLE
alte Spielstände inkompatibel

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#821]
mit https://github.com/TVTower/TVTower/commit/1417a00063d43d836c98657696520d0338d4219b sind alte Spielstände inkompatibel geworden (nicht alle, aber einige).

**Comment by GWRon** [comment]
Kuemmer ich mich drum ... denke einfach Variablen umbenennen sollte reichen.

**Comment by nittka** [comment]
Ja, aber neu gespeicherte Spielstände werden scheinbar auch nicht zum Laden angeboten.

**Comment by GWRon** [comment]
Liegt an dem Commit, der "isCompressed" in "Function GetGameSummary:TData(fileURI:String)" noch nicht angepasst hat.
