### ISSUE TITLE
Währungszeichen konsistent machen?

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#822]
Nachfolgeticket zu #791. Im Code wird teilweise die Währungskonstante für Euro und teilweise das Currency-Locale der Sprache verwendet (derzeit fast überall Euro, so dass es nicht so auffällt). In den Spielinformationen wird für die deutsche Währung dann noch nach Jahr unterschieden. Zunächst zu klären wäre, ob die Währung an der Karte hängen oder anhand der Sprache ermittelt werden sollte.

In jedem Fall sind unterschiedliche Währungen nicht unproblematisch, da auch dann eigentlich auch noch eine Währungsumrechnung gemacht werden müsste (Karte für Indien).

**Comment by GWRon** [comment]
Die "deutsche Währung" im Sinne der DM kommt bei Nachrichten zum tragen. Ab Euro-Einfuehrung wird daraus dann "Euro".

Im Spiel selbst wird konsistent nur eine Waehrung eingesetzt. Man koennte hier nun ueberlegen, wirklich alle Preise bei der "Anzeige" zumindest auf "DM/Euro" umstellbar zu machen. Der Einfachheit halber waere hier ja wirklich der Kurs "2 DM = 1 Eur" angesagt. Da entstehen dann auch keine wirklich krummen Preise. 

Die Umrechnung sollte optional sein.

Bei Transport Tycoon konnte man im Interface die Waehrung anpassen.

![image](https://user-images.githubusercontent.com/2625226/211770189-f19f9e22-b068-4eae-912b-a8c1ddc44ec3.png)

![ttd](https://user-images.githubusercontent.com/2625226/211770454-479b9047-390b-49a9-960d-95b6899dca69.gif)

Wie ersichtlich, passte es nicht nur das Zeichen an, sondern auch die Werte.
Intern wird aber vermutlich mit einer fest definierten Waehrung gerechnet.

Kurzum: bei "Ausgabe" von Zahlenwerten muessten die dann vorher ueber eine zu schaffende Funktion wie  `ToLocaleCurrency:Long(value:long)` geschleift werden. Die kann ja als `inline` deklariert sein, um dem Compiler zu sagen, er soll den enthaltenen Funktionscode in den Code packen und keinen Funktionsaufruf machen.

**Comment by nittka** [comment]
Wäre für mich eher was für's Backlog. Ein erster Schritt wäre wohl, die Euro-Konstante zu ersetzen und die Währung immer aus dem Locale zu holen. Bisher haben sich ja keine brasilianischen Spieler beschwert, dass ihnen die Preise zu hoch sind.

**Comment by auge8472** [comment]
@GWRon Das Währungssystem von TTD gibt es natürlich auch in OpenTTD. Dort, wie wohl auch in TTD selbst, handelt es sich um feste Umrechnungswerte. Speziell für die Währungen, die einstmals durch den Euro ersetzt wurden, gibt es den (optional abschaltbaren) Wechsel zum Euro, der, wenn ich mich recht erinnere, zum historisch korrekten Zeitpunkt erfolgt.

Ob die Umrechnungswerte zwischen den Währungen korrekt oder gar flexibel sind, ist wohl eher eine Frage für Nitpicker.

**Comment by auge8472** [comment]
@GWRon Ich halte das für eine irrelevante Frage. Es ist ein Spiel, das eine Angabe der Ausgaben und Einnahmen braucht und, weil wir das aus dem realen Leben so gewohnt sind, eine Währungsangabe. Wer sich an das zugrundeliegende Spiel MadTV erinnert *und* aus Deutschland kommt, kennt auch noch die D-Mark aus eigenem Erleben, wer nicht, der nicht.

Aber mal ehrlich, der Euro wurde ("in echt") vor nunmehr 20 Jahren eingeführt. Wen interessiert es noch, die DM im Spiel benutzen zu können? Im Spiel braucht es prinzipiell irgendeine Währungseinheit. Das kann die den meisten Spielern geläufige Einheit Euro sein, die Währungseinheit könnte aber genausogut Diggeldaggeldu (DDD) oder sonstwie heißen.

Aber selbst wenn es im Spiel die D-Mark gibt und eine Umstellung auf Euro implementiert würde, wäre es wohl nicht nötig, den korrekten Umrechnungskurs (von 1.95583 zu 1 (Warum merke ich mir sowar über so lange Zeit?)) zu benutzen. Nicht nur wegen der Vermeidung von krummen Werten, sondern auch weil sich wohl die meisten Leute eh nur das ungefähre Verhältnis von zwei zu eins gemerkt haben.

Von anderen Währungen, die (im Laufe der Zeit) auf den Euro umgestellt wurden, gar nicht erst anzufangen.

**Comment by nittka** [comment]
Ich denke auch nicht, dass wir den Aufwand mit Umrechnungskursen treiben sollten. Es wäre aber schon schön, wenn dieselbe Währung konsistent verwendet würde (in Nachrichten kann man ja explizit germanCurrency abfragen; das kann ruhig so bleiben).

Die Hauptlösungsansätze:
* es gibt eine feste Währung, die für alle Sprachen und alle Karten verwendet wird
* es gibt eine Währung, die durch die Sprache festgelegt wird (bestehendes CURRENCY), die für alle Karten verwendet wird
* die Karte definiert eine Währung, die für alle Sprachen verwendet wird

Alle Ansätze haben ihre Nachteile.

**Comment by auge8472** [comment]
Meine unmaßgebliche Meinung dazu:

- Eine feste Währung für alles ist wohl die einfachste Lösung. Dann sollte man aber vielleicht auf eine neutrale Phantasiewährung umstellen. Muss ja nicht gleich so etwas abstruses wie Diggeldaggeldu sein.
- Eine durch die Vorgabe der Sprache festgelegte Währung ist meiner Meinung nach Mist. Schon ein Schweizer könnte sich bei der Währung Euro, die wohl für die Mehrzahl der deutschsprachigen Spieler gültig ist, vor den Kopf gestoßen fühlen. Anderssprachige Spieler aus einer Vielzahl von Ländern mit einer Vielzahl von Währungen könnten da wohl erst recht konsterniert sein. Schon für die englische Sprache dürfte es (in der Realität) eine recht hohe Anzahl möglicher Währungen geben.  
Eine von der Sprache unabhängige Einstellung der Währung sollte, wenn ihr euch für die Lösung einer durch den Spieler festgelegten Währung für alle Karten entscheidet, machbar sein. Nochmal der Vergleich zu OpenTTD: UI-Sprache und Währung sind zwei unabhängige Einstellungen, die für alles gelten, bis möglicherweise die Einstellungen geändert werden.
- Die Währung als Eigenschaft des konkreten Spiels hat auch seinen Reiz. Namentlich dann, wenn man ein Szenario spielen kann, das in einem bestimmten Land spielt (z.B. Entwickle den Markt in …!). Wenn es solche vorgefertigten oder vorfertigbaren Szenarien nicht gibt, hat diese Lösung (zumindest für mich) keinen Reiz.

**Comment by nittka** [comment]
Tatsächlich wird aktuell aber in den meisten Fällen die Währung durch die gewählte Sprache festgelegt. Allerdings ist es bis auf eine Ausnahme (glaube ich) Euro.
Sinnvoll wäre meiner Ansicht nach die Karte (aktuell nur Deutschland). Für weitere Karten sind einige Umbauten nötig, aber wenn man dann ein Land mit deutlich abweichendem "Kurs" hat, sähen die Preise schon seltsam aus.

Vom Gefühl her ist es aber eher was für's Backlog - es gibt aktuell dringendere Baustellen.
