### ISSUE TITLE
Daten hochladen?

### ISSUE THREAD

**Issue by Marathony** [TVTower/TVTower#824]
Ich habe eine XML-Datei mit vielen Daten erstellt. News, Filme, Personen usw. Wie kann ich die hierhin hochladen? Ich wollte sie direkt ins Datenverzeichnis hochladen, scheine aber keine Rechte dafür zu haben.

**Comment by nittka** [comment]
Erstelle einen Fork des Repository (oben rechts), lade die Daten in Dein Repo und erstelle dann eine Pull-Request. Im besten Fall erstellst Du einen Branch für Deine Daten (damit Dein Master nicht Daten enthält, die der TVTower-Master nicht hat).

Der PR kann dann kommentiert werden, Du machst Reparaturen und ggf. gibt es einen Merge hierher.

Wenn das zu knapp war, gern nochmal nachhaken.

**Comment by Marathony** [comment]
Ich habe es versucht. Siehst du, ob es geklappt hat?

**Comment by Marathony** [comment]
Zweiter Versuch...hat es jetzt geklappt?

**Comment by GWRon** [comment]
Wenn Du unserem Repo einen Schritt voraus bist, sollte dir github beim Besuch unseres Repos eigentlich vorschlagen, daraus einen Pull Request zu machen.

**Comment by nittka** [comment]
Der Commit ist nun direkt auf dem Master in Deinem Fork. Auch das ist nicht der gewünschte Zielzustand.
Das Problem ist aber weiterhin: Selbst wenn Du jetzt einen PR von deinem Master nach TVTower/TVTower master stellst, wird es Korrekturen geben und am Ende wird der Hauptmaster anders aussehen (so dass Du Deinen Master reparieren musst).

Der korrekte Ablauf wäre
* Fork erstellen
* Branch erstellen
* auf dem Branch die Änderung machen
* PR von Deinem Branch auf TVTower/TVTower master (NICHT Marathony/TVTower master) stellen
* dann sehen wir den PR hier im Repo und können kommentieren und irgendwann mergen

**Comment by Marathony** [comment]
Wo gebe ich denn ein, dass der PR zu TVTower/TVTower master muss?

Momentan sieht es bei mir so aus:
![Pull Request](https://user-images.githubusercontent.com/47776686/211865687-59e71441-13e8-4aa0-8e74-8375620155d2.png)

**Comment by nittka** [comment]
vorn sollte statt "base:master" dieses Repository stehen "TVTower/TVTower:master" o.Ä.

**Comment by GWRon** [comment]
Nur als Seitennotiz: Wenn ich in meinem Fork (github.com/GWRon/TVTower) was hochlade und danach das Repo von hier aufrufe: https://github.com/TVTower/TVTower
Dann fragt mich Github eigentlich gleich, ob ich nicht einen PR machen moechte. Eventuell macht es das aber nur, wenn man in einem gesonderten Branch arbeitet...

**Comment by Marathony** [comment]
Ich weiß nicht genau wie ich es gemacht habe, aber es hat jetzt wohl geklappt :)

**Comment by GWRon** [comment]
Genau ... nun kann man sich das anschauen, und direkt im PR "kommentieren".
Wenn Du nun Aenderungen machst und auf deinen Fork hochlaedst ("pushst") dann wird das automatisch im PR eingefuegt.

Am Ende koennen wir all die kleinen Aenderungen aber auch zu einer grossen Aenderung zusammenfuehren (sprich es steht am Ende nur da "[DB] Added new data by Cujo"

**Comment by Marathony** [comment]
Okay, dann freue ich mich auf eure Kommentare :)

**Comment by Marathony** [comment]
Ich habe noch einige neue Daten erfasst. Wie kann ich die jetzt integrieren? Soll ich die hochgeladene Datei ändern oder eine neue Datei hochladen?

**Comment by Marathony** [comment]
Okay, ich habe die Änderungen jetzt eingebaut :)

**Comment by nittka** [comment]
Ich mache dieses Ticket mal zu. (Sein Hauptanteil hat inhaltlich ja nichts mit dem laufenden PR zu tun.)
