### ISSUE TITLE
Bug: Filmagentur (manuelles Abstellen in falsches Regal)

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#828]
Manchmal entscheidet man sich um, nachdem man etwas gekauft hat und versucht den Film dann ins Regal zurückzustellen. Daher denke ich, ist dieser Bug durchaus relevant, falls man dabei das falsche Regalteil erwischt.

Video größer als die erlaubten 10MB, daher:
https://www.file-upload.net/download-15075786/Folie5-0-50.mp4.html

Vergessen zu erwähnen:
Außerdem scheint er beim Verkauf (wenn die 3 Teile verschwinden) nur für einen den Verkaufspreis anzurechnen.

**Comment by nittka** [comment]
... war mir bislang noch nie aufgefallen, da ich auch beim Umentscheiden die Filme immer beim Händler habe fallen lassen. Die einfachste Lösung dürfte sein, das Regal als Dropbereich auszuschließen (oder aber eben nur das passende Regalfach zuzulassen.

**Comment by nittka** [comment]
Bei kurzem Probieren konnte ich den Fehler "Regalfach bleibt bei Wiederbetreten leer" und "nur Teil des Geldes zurück" noch nicht nachstellen.
Fehlerhaft ist auf alle Fälle, dass beim Versuch, eine Kassette ins falsche Fach zurückzustellen, diese wieder im Koffer landet, der Preis aber gutgeschrieben wird.

**Comment by nittka** [comment]
Bezüglich des Preises bitte nochmal prüfen: wird das Geld wirklich nicht gutgeschrieben oder sieht es im Interface nur so aus (weil die 20K bei 1.5Mio zu keiner optischen Änderung führt).

**Comment by lonk0123** [comment]
ja, es scheint nur so auszusehen, als ob die Preise durcheinander kommen, Da das Interface teilweise nicht updatet, dann plötzlich mehrere Transaktionen tätigt....

**Comment by GWRon** [comment]
Das Interface muss nicht aktualisieren, da es bei solchen Sachen keinen "Cache" hat. Es zeigt den aktuellen Kontostand an.

Wenn die Anzeige dort nicht stimmt, passt es woanders schon nicht.
