### ISSUE TITLE
Bug: Supermarkt - kategorienübergreifendes Drag'nDrop möglich

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#829]
Man weiß nie, ob es später mal eine Zugriffsverletzung geben kann, weil der Regisseur dann nicht in der Liste der weiblichen Hauptdarsteller gefunden wird...

https://user-images.githubusercontent.com/121659400/212292580-ecbba6dc-58fc-4caa-8525-9c34ec353470.mp4

**Comment by GWRon** [comment]
Du kannst auch generell bei der Auswahlliste das Geschlecht wieder auf "alle" stellen.

Das Drehbuch sieht einfach an der Stelle eine weibliche Person vor. Ein Abweichung wird bei der Produktion mit sehr hoher Wahrscheinlichkeit bestraft - aber, halt nicht immer ("Glueckstreffer").

Ist also kein Bug - sondern Absicht.

**Comment by lonk0123** [comment]
Naja, es ist ja nicht nur geschlechterspezifisch falsch, wenn ich den Regisseur für alle 5 Rollen einteilen kann.
Es ergibt halt auch keinen großen Sinn.
Irgendwann will das Programm halt mal berechnen, wie gut die Produktion ist und sucht dann evtl. nach Werten, die der Regisseur, der dann in jeder Kategorie zugeteilt ist, nicht mitbringt, stürtzt evtl. ab oder berechnet Unsinn etc.

Zumindestens war das meine Sorge.

**Comment by GWRon** [comment]
Der Regisseur kann auch "Woody Allen"-like Schauspieler werden ... oder andersherum.
Gleiches gilt fuer Sportler, die zu Moderatoren werden, oder Politiker zu Saengern.

Was nicht klappt, ist eine Person lange genug "weiblich" zu besetzen und auf einen Geschlechtswechsel zu hoffen.

Das Spiel berechnet bei der Produktion die Eignung ("castFit") der Person ... anfaenglich wird der Regisseur also nur knapp ueber Amateurniveau sein (Schauspielerskill: 0, Kenntnis des Genres XX% - waehrend Amateure hier niedriger sein koennen).
Ein Regisseur kennt ja das "Filmgeschaeft", hat schon Schauspieler gesehen usw. Gleiches andersherum. Auch kann ein Nebendarsteller einen Hauptdarsteller mimen (auch wenn es da nicht nur im "Abspann" eine Rolle spielt). Hier sollte man eher auch an "kann der Schauspieler den Film alleine tragen" denken. Gibt ja Leute, die funzen einfach nur als klassischer "Handlanger" in Actionfilmen. Dafuer aber halt "sehr gut".

**Comment by lonk0123** [comment]
Ja, ich verstehe schon, daß das alles Sinn ergeben kann.
Ich hab mal testweise dies hier in Auftrag gegeben: 5x Regisseur

![Regisseur_in_allen_Kategorien](https://user-images.githubusercontent.com/121659400/212303336-699a3797-3cdf-4f8e-8070-710430cd2ccc.png)

Das Ergebnis: 37% Einschaltquote!
Wahrscheinlich über 40%, aber ich hab 11 Punkte in die Produktionsgeschwindigkeit gesteckt.

Ist halt nicht sehr realistisch, daß ein Western-Regisseur, der noch nie als Schauspieler tätig war, alle Rollen besetzt und dann einen Mega-Erfolg abliefert.

Wenn es aber so beabsichtigt ist, dann schließe ich das Issue.

**Comment by GWRon** [comment]
Die Kosten sind nur ein "Ergebnis", sie werden nirgends in die Qualitaet der Produktion einbezogen.

Allerdings beruhen die Kosten auf einem wichtigen Eingangsfaktor, die auch die Produktion beruecksichtigt: der Erfahrung generell, der Erfahrung im entsprechenden Beruf und der Erfahrung im Genre (Westernregisseur als Erotikdarsteller ist schlechter, als Westernregisseur als Westerndarsteller, manche Genre sind "artverwandt" - Action, Thriller, ... usw.)


Das die Produktion mit "Regisseur fuer alles" so viel "ausspuckt", liegt am bereits angesprochenen mangelnden Balancing. Ich habe irgendwo noch eine art "test-App" fuer die Eigenproduktionen. Eventuell kann man dort besser simulieren, wie sich Dinge "entwickeln", was fuer Ergebnisse welcher Einfluss hat usw.
