### ISSUE TITLE
Not enough space to display year

### ISSUE THREAD

**Issue by scr0llbaer** [TVTower/TVTower#832]
In this screenshot, the country information "GB/USA" (which I think is a common combination) takes up too much space, and the arguably more important information, the release year, disappears.

![Screenshot from 2023-01-06 04-43-08](https://user-images.githubusercontent.com/122231074/212449975-acd94a1d-b1d5-4d99-8e29-e608909f0a4c.png)

Maybe the year should be displayed first if there is not enough space to make room for a separate field for the year information?

**Comment by nittka** [comment]
I think the genre could do with a bit less space - however, there are cases with a longer list (3 or 4 items?)

**Comment by nittka** [comment]
This has been fixed in the meantime.
