### ISSUE TITLE
Director is not displayed if combined flags are used in the staff data

### ISSUE THREAD

**Issue by scr0llbaer** [TVTower/TVTower#833]
Besides the missing year information, we also have the problem here that the director is not displayed, because he was defined with `function="5"` (director and writer).

![Screenshot from 2023-01-06 04-43-08](https://user-images.githubusercontent.com/122231074/212450056-9aff5110-6bb0-410a-bec9-92a867371f66.png)

**Comment by nittka** [comment]
This has not been addressed. The current interpretation for a cast job is that it is "exclusive" (one job per slot). For database programmes, use two cast entries.

**Comment by nittka** [comment]
As there is a workaround for programmes, at least for now.

**Comment by nittka** [comment]
Ich würde es nicht zum Standard machen wollen. Insb. für Drehbücher würde ich weiter auf eindeutigen Jobs bestehen, aber für die Anzeige im Datenblatt spricht meiner Ansicht nach nichts gegen Doppelfunktionen.
