### ISSUE TITLE
References to staff index numbers higher than 6 break the description text of a programme

### ISSUE THREAD

**Issue by scr0llbaer** [TVTower/TVTower#834]
![Screenshot from 2023-01-06 15-15-42](https://user-images.githubusercontent.com/122231074/212450180-ae2d62bd-3b5b-4a99-9c9d-44addd855ffd.png)

I "corrected" this in the data by rearranging the order of the staff in such cases, but still it is unexpected and undocumented behavior.

**Comment by nittka** [comment]
I have to check, but I think the current implementation has a limit for the index of the person/role in the cast.

**Comment by nittka** [comment]
The limit was raised. However, the reference mechanism is currently refactored. With the planned syntax changes, no such limitation will exist.

**Comment by nittka** [comment]
... The limit is raise in the PR for person references, so it will probably not be part of the next release. However, the syntax of the references will change in the long run.
