### ISSUE TITLE
Vanished issues/PR ... 

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#840]
Seems in the past github "flagged/banned" users if they posted too many links/urls ... maybe scr0llbaer's stuff is not deleted but "hidden" by github until he sorts out with them.

https://github.com/streamlink/streamlink/issues/622

here someone had this issue:
https://a-habakiri.hateblo.jp/entry/20161208accountflagged

scr0llbaer: if you read it, hope you get it sorted out. If you need help, drop me an email.

**Comment by nittka** [comment]
Nachdem der Account scheinbar kurzzeitig wieder aktiv war, ist er jetzt wieder weg.

**Comment by GWRon** [comment]
Account nun wieder freigeschalten
