### ISSUE TITLE
Stationmap: Optimierung

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#849]
Basierend auf: https://github.com/TVTower/TVTower/issues/644#issuecomment-1399050891_

Der Ausdruck "Layer" hat mich auf ein hoffentlich plausibles Grundkonzept gebracht:
- Type `TPopulationCanvas`
- beherbergt einen Array aus Type `TPopulationLayer`
- die Canvas hat `SetValue(x,y, value, layerIndex)` und `GetValue:Int(x,y)`, `GetSumValue:int(x,y)`
- GetValue geht "von oben nach unten" und schaut in jedem Layer, ob er "x,y" hat und gibt den ersten gefundenen Wert zurueck
- GetSumValue geht "von oben nach unten" und addiert bzw subtrahiert den Wert aus jedem Layer (der "x,y" hat) und gibt das Ergebnis
- (zu GetSumValue): Layer koennen definieren ob sie "addieren" oder "subtrahieren"
- Optional: die Canvas kann Layer zusammenfuehren (fuer komplexeres Caching / Vereinfachungen ...), so koennte jeder hinzugefuegte Sendemast mit dem Basislayer zusammengefuehrt werden (um so die Werte dort zu erhoehen)
- Optional: Layer koennen "invisible" gemacht werden

-> zwei Sendemaste die sich ein Gebiet teilen, wuerden, wenn in einem gemeinsamen Layer genutzt, in den "geteilt"-Gebieten eine 2 haben ("2 Sendemasten die dort ausstrahlen)

Fuer "gebaute Antennen" ("nicht-temporaeres") wuerde man einen Basislayer nutzen. Der Basislayer haette also Werte wie "1" (nur ein Sendemast sendet in dieser Koordinate), "2" fuer zwei ueberlappende Sendemasten usw.

Wenn nun eine neue Antenne gebaut werden soll:
- neue TPopulationCanvas
- extern gespeicherter BasisLayer einfuegen
- Zweiten Layer "on top" in dem neue Antenne eingetragen wird (deren "Pixel") - mit dem Wert "1"
- Fuer jeden "Pixel"  im Bereich der neuen Antenne (bzw. fuer jede Position, die der Layer nutzt) wird `GetSumValue()` abgerufen
- alle zurueckgegebenen Werte die nun "1" sind (also nur im neuen Layer vorkommt) sind Zuwaechse

Wenn nun eine Antenne verkauft werden soll:
- neue TPopulationCanvas
- extern gespeicherter BasisLayer einfuegen
- Zweiten Layer "on top" in dem neue Antenne eingetragen wird (deren "Pixel") - mit dem Wert "1", Modus "Subtraktion"
- Fuer jeden "Pixel"  im Bereich der neuen Antenne (bzw. fuer jede Position, die der Layer nutzt) wird `GetSumValue()` abgerufen
- alle zurueckgegebenen Werte die nun "0" sind (kamen in beiden Layern vor, im Basislayer nur 1x - sprich genau unsere zu verkaufende Antenne) sind Verluste beim Verkauf

"Marktsituationen" sollten sich aehnlich berechnen lassen.

**Comment by nittka** [comment]
Ich muss es mir noch ein- zweimal durchlesen, aber auf den ersten Blick sieht es plausibel aus. Gehe ich recht in der Annahme, dass bei der Aktualisierung der Bevölkerungszahlen alles neu berechnet wird?

**Comment by GWRon** [comment]
Es muss nichts neu berechnet werden, da die Aenderung der Bevoelkerungszahlen ueber einen Modifikator ablaeuft. Sprich die Bevoelkerung der Senderkarte aendert sich ueberall "gleichmaessig".
10% Zuwachs = 1.1
Bevoelkerung im Sendegebiet JETZT = berechnete Basis * 1.1

**Comment by GWRon** [comment]
Ich bin da noch immer am Konzept und Code dran.

Auch bedacht werden muessen "Masken" fuer Gueltigkeitsbereiche (sprich "wohnt da jemand" / "ausserhalb des betroffenen Bundeslands").
Und da dann die Frage, wann gefiltert wird: Erstmal blind alles berechnen und am Ende die Maske "auflegen", oder schon beim jeweiligen Eintragen filtern?

Ich denke es kommt halt immer drauf an, was langsamer ist: unnoetige Berechnungen von spaeter auszufilternden Punkten vs dem Filtern aller einzelnen Layer.

Weiterhin musste ich noch umstrukturieren, da bestimmte Layer ja von KI und Mainthread gleichzeitig genutzt sein koennten - also Mutexe einbauen.
Um nicht fuer jeden einzelnen Punktsetzer einen Mutex zu brauchen gibt es noch Overloads um Punktarrays zu setzen - oder gleich x,y,radius ...


Der Basiscode fuer Layer, Canvas und Co steht und ich kann Setzen/Lesen.

**Comment by GWRon** [comment]
Ein "MemAlloc"-Block-Layer (also "2D Array") kann nun auch genutzt werden und das Fuellen kann mittels TPixmap-Maske erfolgen.

Beispiel:
Ein Sender ist "rot", ein Sender ist "gruen". Ueberlappungen sind "gelb"
![image](https://user-images.githubusercontent.com/2625226/223871772-39a15604-afb0-4513-92f3-7ba59196797e.png)

Und nun das ganze "maskiert":
![image](https://user-images.githubusercontent.com/2625226/223872224-abf386d4-3f5e-42c4-a82d-a53f202f64f8.png)

Im Falle des Spiels heisst das:
- fixer Layer "Spieler 1"
- Layer 2 waere "dynamisch" (da kommen die hinzufuegenden Sendemasten rein - oft also nur 1 Mast)
- fixe Maske "Bundesland"

**Comment by GWRon** [comment]
Schwarzer Kreis = Alles im maskierten Bereich, bei dem NICHT der Layer von "Spieler 1" etwas bedeckt (aka "wo der seine Sendemasten hat"). 
![Peek 2023-03-12 10-06](https://user-images.githubusercontent.com/2625226/224535123-1ceb4916-d4e0-4870-9e1b-c6387881d2db.gif)

Der Aufbau dazu sieht derzeit so aus:
```
Local increaseCanvas:TPopulationCanvas = new TPopulationCanvas
Local layer_newStations:TPopulationCanvasLayer = new TPopulationCanvasLayer_Map
'keep and cut rest
increaseCanvas.InsertLayer(layer_section1, 0, EPopulationCanvasMode.BinaryMask)
'cut out existing stations
increaseCanvas.AddLayer(layer_stationsPlayer1, EPopulationCanvasMode.NegativeBinaryMask)
increaseCanvas.AddLayer(layer_newStations)

...

	layer_newStations.Clear()
	layer_newStations.SetValue(1, MouseX(), MouseY(), 30)
	increaseImg = GeneratePopulationCanvasImage(increaseCanvas)
```


Die bestehenden Daten koennten so hier abgebildet werden:
```
Local densityPixmap:TPixmap = LoadPixmap("../res/maps/germany/germany_densitymap.png")
Local densityImg:TImage = LoadImage(densityPixmap)
Local mask_all:TPixmap = LoadPixmap("../res/maps/germany/germany_collision.png")
Local mask:TPixmap = mask_all.window(424,0, 262, 127)
Local maskImg:TImage = LoadImage(mask)

local shareCanvas:TPopulationCanvas = new TPopulationCanvas
Local layer_stationsPlayer1:TPopulationCanvasLayer = new TPopulationCanvasLayer_Map
Local layer_stationsPlayer2:TPopulationCanvasLayer = new TPopulationCanvasLayer_Map
shareCanvas.AddLayer(layer_stationsPlayer1)
shareCanvas.AddLayer(layer_stationsPlayer2)

'add antennas
Local offsetX:Int = 85
Local offsetY:Int = 51
layer_stationsPlayer1.SetValue(1, 50 + offsetX, 50 + offsetY, 30)
layer_stationsPlayer1.SetValue(1, 80 + offsetX, 65 + offsetY, 30)
layer_stationsPlayer1.SetValue(1,110 + offsetX, 50 + offsetY, 30)
layer_stationsPlayer1.SetValue(1,140 + offsetX, 65 + offsetY, 30)
layer_stationsPlayer1.SetValue(1,170 + offsetX, 50 + offsetY, 30)
layer_stationsPlayer2.SetValue(2, 50 + offsetX, 80 + offsetY, 30)
layer_stationsPlayer2.SetValue(2, 80 + offsetX, 65 + offsetY, 30)
layer_stationsPlayer2.SetValue(2,110 + offsetX, 80 + offsetY, 30)
layer_stationsPlayer2.SetValue(2,140 + offsetX, 65 + offsetY, 30)
layer_stationsPlayer2.SetValue(2,170 + offsetX, 80 + offsetY, 30)

'federal state layer - TStationMapSection
Local layer_section1:TPopulationCanvasLayer = new TPopulationCanvasLayer_2DArray
layer_section1.binaryMode = True '0 or 1
layer_section1.SetValue(mask, offsetX, offsetY)
'keep and cut rest
shareCanvas.InsertLayer(layer_section1, 0, EPopulationCanvasMode.BinaryMask)
'or cut out...
'shareCanvas.InsertLayer(layer3, 0, EPopulationCanvasMode.NegativeBinaryMask)


Local layer_populationdensity:TPopulationCanvasLayer = new TPopulationCanvasLayer_2DArray
layer_populationdensity.SetValue(densityPixmap, 0,0, 2) 'rgbchannelindex = 0 (red)

'image preview
shareImg = GeneratePopulationCanvasImage(shareCanvas)
```

**Comment by nittka** [comment]
`layer_stationsPlayer1.SetValue(...` würde ich eher "AddValue" nennen, denn so wie es aussieht, wird ja eine Antenne hinzugefügt und nicht exklusiv ein Wert gesetzt.
Würde man für das Entfernen einer Antenne das Layer komplett neu erzeugen oder denkst Du an ein Remove?

**Comment by GWRon** [comment]
Wenn man das folgende Szenario abbilden will, dann ergibt sich der Canvas-Aufbau direkt daraus:
- bestehende Antennen
- hinzuzufuegende Antennen
- zu entfernende Antennen

Es braucht dann diese drei Layer. In den allermeisten Faellen braucht es nur zwei...um auszulesen, was durch einen Verkauf an Reduktion stattfindet..oder an Anstieg durch einen Kauf.
Der Kauf einer Antenne und gleichzeitige Verkauf einer anderen...ist denke ich selten, aber eben halt mit drei Layern erledigbar.

Kurzum entspricht jeder Layer einer "Art an Information" (Zuwachs, Verlust, Gemeinsame Sendegebiete...)

Masken dienen dazu, Bereiche einzugrenzen. In unserem Fall kann eine Maske einerseits den rechteckigen Rahmen definieren in dem gesucht wird...und mit seinen Inhalten dann die genaue Kontur. Also Bundeslaender, Bevölkerungsdichtekarte...
Natuerlich kann eine Maske aber auch aus einer mathematischen Formel (x,y, radius... Oder x,y,x2,y2...) bestehen.
Da muss ich schauen, wo dann optimiert werden muss bzw sollte.

Da jeder Layer seine eigene derzeitige maximale Groesse kennt, ist bei Berechnungen mit weniger "Lookup-Aufwand" zu rechnen. Aber auch da liesse sich dann noch optimieren (bspweise Weglassen, wenn der unterste Layer eh eine Maske ist und man ganze Zeilen/Reihen dadurch sparen kann).

**Comment by nittka** [comment]
Ich glaube, der Ansatz mit unterschiedlichen Layern für hinzugefügte und entfernte Antennen funktioniert nicht.
* Kauf einer Antenne an Position 1
* Verkauf der Antenne 
* Kauf einer neuen Antenne an derselben Position (weil die Inflation die Kosten so in die Höhe getrieben hat, dass man die alte Antenne abgerissen und eine neue hingestellt hat)

**Comment by GWRon** [comment]
Das sind doch zwei voellig "getrennte" Aktionen?

Kauf:
- bestehende Antennen
- die hinzukommende auf Layer 2
- ... Berechnung

Verkauf:
- bestehende Antennen
- die wegfallende Antenne auf Layer 2
- ... Berechnung

> Auch der Verkauf einer Antenne die sich mit einer anderen noch vorhandenen überlappt, dürfte ein fehlerhaftes Gesamtbild geben.

Der Layer "deine Antennen" hat pro Antenne einen Wert von "+1", bei Ueberlappung zweier Antennen also "2", bei drei dann "3" usw.

Der Verkauf (Layer 2) zieht dann nun einfach "-1" ab. Ist das Ergebnis > 0 ... dann gibt es dort noch mindestens einen Sendemast.

Beim Auswerten der Layer kann man die Sache auch "binary" setzen, dann wird aus "0 = 0" und aus ">0 = 1". Je nach "Wunsch".

**Comment by nittka** [comment]
OK. Dann hatte ich die Layer noch nicht richtig verstanden. Ich war von Ja/Nein ausgegangen, nicht vom Zählen von Antennen pro Punkt.

**Comment by nittka** [comment]
Dieses Ticket sollte mit dem Umbau der Kartenlogik erledigt sein. Spezifische Optimierungen der neuen Logik würde ich in einem neuen Ticket behandeln.
