### ISSUE TITLE
GUI: input field needs "edit everywhere" capability

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#85]
Reminder through "DannyF".

- handle clicks on active input to move cursor
- handle "left right" to move by one character
- handle "ctrl left right" to move by words (until next space)

**Comment by nittka** [comment]
Getestet beim Editieren der Titel im Supermarkt. Die obigen Punkte funktionieren, soweit ich das sehe. Bei ctrl left right könnte man noch überlegen, an den Anfang des ersten / das Ende des letzen Wortes zu springen, wenn kein weiterer Space zu finden ist.

Hat man Zugriff auf die Zwischenablage? In diesem Fall könnte ein ctrl v noch ganz nett sein (Filmtitel/Beschreibung von extern kopieren und einfügen). Praktisch wäre es auch für das Testen (Cheat-Kommandos in den Chat kopieren statt sie immer wieder neu eingeben zu müssen).

**Comment by GWRon** [comment]
Ich koennte ein clipboardmodul integrieren...

**Comment by GWRon** [comment]
Sollte das "paste" in jedem input-Feld funktionieren, oder eher "spezifisch" ?

Gibt es auch Stellen, an denen wir "in die Zwischenablage" kopieren wollen?

**Comment by GWRon** [comment]
https://blitzmax.org/docs/en/api/brl/brl.clipboard/
wuerden wir dann nutzen...

**Comment by nittka** [comment]
Spricht etwas gegen paste in jedem Eingabefeld?
Bzgl. Kopieren: Das erhöht wahrscheinlich den Aufwand enorm (Text selektieren mit Maus, Tastatur). Ich würde es erstmal weglassen.

**Comment by GWRon** [comment]
Habe ein das Clipboardmodul gewrappt und Basisfunktionalitaet zu den GUI-Widgets hinzugefuegt.

Wir koennen einerseits Texte von und zum "OS-Clipboard" schicken... aber Widgets koennten auch ein App-internes Clipboard nutzen.
Wozu? Nun, ein "Copy" von einem Schauspieler in der Eigenproduktion koennte entweder die cast-ID kopieren, oder eine cast-GUID ... und sich selbst als "source".

Geht man dann ueber eine Liste und will "pasten", koennte diese anhand von "source + guid" wissen worum es geht ... und automatisch die Person auswaehlen.

Soweit aber erstmal ... bitte die Zwischenablagefunktion austesten und das Issue hier schliessen.

Copy auf "gehovertem Input": kopiert Inhalt
Copy auf "gerade bearbeitetem Input": kopiert Inhalt
Paste auf "gehovert": ersetzt Inhalt
Paste uaf "bearbeitet:" fuegt Inhalt an aktueller Stelle ein.

**Comment by nittka** [comment]
Das Copy funktioniert noch nicht ganz wie erwartet (Filmtitel editieren)
* Filmtitel löschen
* "Film" eingeben
* Copy
* Beschreibung löschen
* Paste

Erwartet ist, dass der gerade eingegebene Titel kopiert wird. Im Moment muss das Eingabefeld aber erst den Fokus verlieren und wiederbekommen, damit der aktuelle Wert kopiert wird.
Beim Chatfenster fällt das auch auf. Anwendungsfall gerade eingegebenen Befehl kopieren, um ihn ein zweites Mal abzusetzen. Wenn man aber einen Befehl eingibt und kopiert, liefert das darauffolgende paste nicht das erwartete Ergebnis.

Kritischer: strg-c an einer Stelle, an der kein paste erlaubt ist, beendet das Programm. Das war vorher wahrscheinlich auch schon so, aber da gab es ja auch noch keinen anderen Grund, diese Tastenkombination zu nutzen.

**Comment by GWRon** [comment]
ctrl+c ist in main.bmx als "force quit" drin ... wie halt bei anderen Programmen ueblich.

Muessten wir wohl ... auf eine andere Taste umlegen ... ctrl+q oder so ?

**Comment by GWRon** [comment]
Beides erledigt.
