### ISSUE TITLE
Verkauf Sendemasten/Networks KI

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#851]
Meldung nur wegen Ausschlusses, daß es zu Problemen beim Verkauf von Antennmasten durch die KI kommen kann etc.

Wenn ich z.B. zu KI 4 wechsele und dann versuche Antennenmasten zu verkaufen, so scheint ein Verkauf stattzufinden, aber die Masten werden in der Liste rechts nicht gelöscht und können bei Auswahl dort wiederholt verkauft werden.
Das gleiche passiert auch bei Kabel- und Satellit. Das Reichweitenlevel wird sofort angepaßt, es findet also sofort etwas statt, aber ich kann einen Satellit z.B. 10 mal hintereinander kündigen und erhalte dadurch 10x die Kosten aufgebrummt.

Ich will bloß ausschließen, daß eine KI in Finanznot eine Antenne etc. mehrfach verkauft und diese letztlich aber nie loswird.

[DDR_NEU12.zip](https://github.com/TVTower/TVTower/files/10472042/DDR_NEU12.zip)

**Comment by nittka** [comment]
Ich habe mir den Spielstand noch nicht angeschaut, aber zum Verständnis des Ablaufs. Stimmen die folgenden Aussagen?
* Du spielst im Entwicklungsmodus.
* Du wechselst mit Taste 4 auf die KI, deaktivierst sie aber nicht (die KI spielt weiter).
* Während die KI im Büro ist, öffnest Du die Karte und tätigst die Verkäufe.

Das Spiel unterscheidet zwischen aktivem Spieler und beobachteten Spieler. Im Entwicklermodus hatte ich es so eingestellt, dass durch die Tasten 1 bis 4 nicht nur "beobachtet" wird, sondern auch der aktive Spieler gewechselt wird, damit man in den Debug-Screens die Daten des gerade gewählten Spielers sieht. Ggf. sind nicht alle GUI-Aktionen gegen fälschliche Ausführung abgesichert (nur Prüfung, ob beobachtet, aber nicht, ob KI-Spieler). Alternativ müsste man das "Debug-Konzept" anpassen und die Daten nicht für den aktiven sondern den beobachteten Spieler anzeigen.

**Comment by lonk0123** [comment]
Ja Entwicklermodus, wo ich die Räume per Shortcut wechseln kann bzw. per tab die erweiterte Debug-Anzeige habe.
Ich wechsele auf KI 4 und kann sie jetzt aktivieren oder deaktivieren (spielt keine Rolle) für den fehlerhaften Verkauf, 
Ich wechsele den Raum mit 'O' auf Büro, gehe dann auf die Karte und versuche zu verkaufen.
Der Verkauf funktioniert nicht bzw. ist mehrfach möglich.

**Comment by nittka** [comment]
Wenn man den Sendemast verkauft, dann die Karte verlässt und wieder betritt, ist die Antenne verschwunden. Es sieht so aus, als würde beim Verkauf die Liste nicht korrekt aktualisiert werden.
