### ISSUE TITLE
negative Vertragslaufzeit bei unverkäuflichen Sendestationen

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#854]
Wieder nur, um evtl. im Spielverlauf auftretende Fehler auszuschließen:

Hatte gerade einen Fehlklick beim Hamburger Kabelnetzwerk, was einem ab Spieljahr xxxx als Default-Netzwerk vorgegeben wird.
"Automatisch verlängern"-Option versehentlich rausgenommen, führt nach 12 Tagen zu negativen Minuten- sowie Stundenwerten bei der Vertragslaufzeit.

![negative Vertragslaufzeit](https://user-images.githubusercontent.com/121659400/213911044-da43d166-78b6-4a7b-9a88-b84abcf60936.png)

**Comment by nittka** [comment]
Ja. Bei unverkäuflichen  Kabelnetzwerken sollte die Option gar nicht deaktivierbar sein.
