### ISSUE TITLE
Werbung - Fixed Price

### ISSUE THREAD

**Issue by StukovTTV** [TVTower/TVTower#857]
Hallo Freunde,

ich habe mich an Werbungen gemacht und wollte welche erstellen die einen Fixen Betrag geben unabhängig von der derzeitigen Reichweite Image oder ähnlichem

`<conditions min_audience="3.7024" min_image="0" max_image="71" target_group="312" allowed_genre="2"/>`

`<data quality="4" repetitions="7" duration="4" fix_price="1" profit="11418" penalty="39281" infomercial="1" infomercial_profit="306" fix_infomercial_profit="1" pro_pressure_groups="4" contra_pressure_groups="8" />`

so wie ich das verstanden habe, hätte  fix_price="1" den Profit auf 11418 pro Block begrenzen sollen ... das Angebot war aber 559.482 für 7 Blöcke

Ein weiteres ... allowed_genre kann man derzeit nur 1 Genre angeben .. wenn man zB 2,17 eingibt wird im Spiel ebenfalls nur das erste Genre angezeigt als
![screenshot_008](https://user-images.githubusercontent.com/95760822/213921906-acd987ae-9a65-46b8-901b-246fd702b253.png)

**Comment by nittka** [comment]
FixPrice wird derzeit wohl nicht so häufig verwendet... Der Basispreis wird aktuell an zwei Stellen mit SpotCount multipliziert. 11000*7*7 kommt dann auf den angezeigten Wert.

Aktuell wird ausschließlich ein Genre (keine Liste) unterstützt.

**Comment by StukovTTV** [comment]
Ich glaube FixPrice wird gar nicht verwendet derzeit

**Comment by nittka** [comment]
Die Option scheint ja auch nicht so attraktiv zu sein, da es nur einen verhältnismäßig kleinen Reichweitebereich gibt, für den sie interessant ist. Meist ist entweder die Zuschauerzahl nicht erreichbar oder aber andere Werbung bringt mehr Einnahmen.

**Comment by StukovTTV** [comment]
Ich finde es dennoch eine interessante Alternative. Deine Argumente sind natürlich stichhaltig

**Comment by nittka** [comment]
Das Fixpreisproblem ist in #858 behoben. Wenn Die Genre-Einschränkung wichtig ist, bitte ein separates Ticket aufmachen.
