### ISSUE TITLE
Supermarkt: Produktionsfokus ausgrauen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#861]
Wenn man den Supermarkt zwecks Eigenproduktion betritt - und KEINE Produktionsfirma ausgewaehlt ist, sollten die Slider deaktiviert/ausgegraut werden.

Damit ist automatisch der "Du musst erst eine Firma auswaehlen"-Hinweis mit enthalten.

**Comment by nittka** [comment]
Wenn keine Firma gewählt ist, wird beim Cast unten was angezeigt. Vielleicht ist das einfach die falsche Stelle.
