### ISSUE TITLE
GUI-Einkaufsliste aus altem Spiel noch in neuem Spiel: Absturz

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#862]
- Einladen "studio-bug-reproduced"
- In das Studio gehen (sechster Stock)
![image](https://user-images.githubusercontent.com/2625226/214285951-78c91043-d79a-4187-9d4a-ff3767e3d14c.png)

- Spiel beenden ins Hauptmenu)
- Neues Spiel starten
- per S gleich ins Studio wechseln
![image](https://user-images.githubusercontent.com/2625226/214286060-feba47ec-6905-48fc-8758-0206af798e59.png)

Ein Mouseover fuehrt zum Absturz.
[studio-bug-reproduced.zst.zip](https://github.com/TVTower/TVTower/files/10489303/studio-bug-reproduced.zst.zip)
(.zip am Ende entfernen)

**Comment by GWRon** [comment]
RefreshGuiElements() des studio-roomhandlers fuegt dieses Element nicht hinzu, es existiert also "ausserhalb" der Kollektionen.

Also ist das "TGuiProductionConceptListItem"-Element wohl nicht mehr korrekt zugeordnet. Eventuell sollten solche Dinge beim Einladen "entfernt" werden.

**Comment by GWRon** [comment]
Was ich hier mit diesem Savegame auch oft "sehe" ist:
- Speicherstand einladen, ins Studio gehe
- Rechtsklick raus
- Escape druecken und Menue kommt nicht (auch nicht per Button)
- Speicherstand mit F8 nochmal einladen... Menu poppt automatisch auf

passiert aber nicht immer - nur haeufig

**Comment by GWRon** [comment]
Bezueglich dem nicht entfernten TGuiProductionConceptListItem:
Es gibt meines Erachtens nur zwei Stellen
- RemoveItem() 
  - guiEntriesPanel.removeChild(item)
  - _SetSlot
- SetItemToSlot()
  - wenn slot schon besetzt:
    - If dragItem._parent Then dragItem._parent.RemoveChild(dragItem)
    - Self._SetSlot(slot, Null)
  -  in jedem Fall:
    - guiEntriesPanel.addChild(item)
    - Self._SetSlot(slot, item)

**Comment by GWRon** [comment]
Genau da bin ich gerade dran.

**Comment by GWRon** [comment]
Der Speicherstand liefert beim studio-roomhandler RefreshGUIElements:

```
	Method RefreshGuiElements:Int()
...
			'insert them again (in the numeric order of their original slots)
			For local pc:TProductionConcept = EachIn toReAddConcepts
				guiListDeskProductionConcepts.addItem(block, String(pc.studioSlot))
print "guiListDeskProductionConcepts.addItem(" + block._id +" , slot=" +  String(pc.studioSlot) + ")  list.slots length=" + guiListDeskProductionConcepts._slots.length
```
```
guiListDeskProductionConcepts.addItem(771 , slot=1)  list.slots length=5
guiListDeskProductionConcepts.addItem(772 , slot=2)  list.slots length=5
guiListDeskProductionConcepts.addItem(773 , slot=3)  list.slots length=5
guiListDeskProductionConcepts.addItem(774 , slot=4)  list.slots length=5
guiListDeskProductionConcepts.addItem(775 , slot=5)  list.slots length=5
```
Die "slot"-Werte sollten aber 0-basiert sein.


Wenn beim Aufraeumen EmptyList() aufgerufen wird:
```
Slotlist.EmptyList() : Super.EmptyList()  self.type=TGUIProductionConceptSlotList  id=420
Slotlist.EmptyList() : for all 5 _slots
  i = 0
  i = 1
    RemoveItem()  self.type=TGUIProductionConceptSlotList  slot=1   id=420
  i = 2
    RemoveItem()  self.type=TGUIProductionConceptSlotList  slot=2   id=420
  i = 3
    RemoveItem()  self.type=TGUIProductionConceptSlotList  slot=3   id=420
  i = 4
    RemoveItem()  self.type=TGUIProductionConceptSlotList  slot=4   id=420
```

Denke das ist mit dem Fehlerbild verbunden.

**Comment by GWRon** [comment]
slotlist.SetItemToSlot() ueberprueft nicht, ob die Slotnummer ausserhalb einer Limitierung liegt.
```
	'may return a object which was on the place where the new item is to position
	Method SetItemToSlot:Int(item:TGUIobject,slot:Int)
		If slot < 0 or slot >= _slotAmount Then Throw "SetItemToSlot: slot " + slot + " out of valid range: 0 - " + (_slotAmount-1)
```
und schwups fliegt man beim Betreten des Studios (beim Savegame) mit entsprechendem Fehler raus.

**Comment by GWRon** [comment]
Ich glaube weiterhin ist das Problem, wie "studioSlot" gespeichert und dann interpretiert wird.

@nittka Du hast da ja glaube ich mal dran herumgeschraubt (das "Nachruecken") - meine Vermutung ist, dass durch die Produktion eines Serienelements ja die Liste verkuerzt wurde. die "studioSlots" aber sind hier nicht korrekt "nachgerutscht".

slot/concept
0 = Episode 1/6
1 = Episode 2/6
2 = Episode 3/6
3 = Episode 4/6
4 = Episode 5/6
5 = Episode 6/6

Dann passiert irgendwas mit Episode 1/6 ... und die Slotliste wird auf 5 Elemente verkuerzt. Allerdings enthalten die jeweiligen "concept.studioSlot" noch 1-5 (statt dann 0-4)

**Comment by nittka** [comment]
... ich kann mich nicht erinnern, ob ich die gesamte Implementierung gemacht oder mir nur das Verhalten gewünscht habe. Aber ja, bei Serien war die Frage, ob Lücken in der Liste entstehen sollen (Slot 1, 2, 4, 5 besetzt aber Konzeption noch nicht fertig, Slot 3 konzipiert ->Produktion gestartet). Ziel war, dass die hinteren Slots vorrücken, damit eine neu geholte Einkaufsliste ans Ende eingefügt wird und nicht in die Mitte.

**Comment by GWRon** [comment]
Jedenfalls wird eventuell der Fehler dort zu suchen sein. Oder irgend eine Stelle kann Dinge "entfernen" ohne dass sich der Rest anpasst.
Wenn ich nun die SlotListe entsprechend "absichere", wird ohne "Korrektur" des "studioSlot"-Verhaltens ein Seiteneffekt entstehen (Concept-Eintrag wird nicht hinzugefuegt oder aehnliches).

Weiss also nicht, ob wir das alles in einem PR abhandeln, oder gesplittet.

**Comment by GWRon** [comment]
Wenn ich das Setzen auf einen Slot "out of bounds" (hier slot 5 - also indexmaessig der 6te) unterbinde, landet beim Betreten des Studios das Concept fuer slot 5 nun "irgendwo"
![image](https://user-images.githubusercontent.com/2625226/214348796-a4118cc1-6a29-4a79-b509-4d9902ef31bc.png)

Ich koennte mir vorstellen die Slotlistenaenderung so zu committen ... und dann koennen wir gesondert einen Fix fuer den hiesigen Umstand machen (also bspweise alle studioSlots vorher zu ueberpruefen und "nachzuruecken" falls noetig - falls sie nicht mehr reinpassen).

**Comment by nittka** [comment]
Was spricht denn eigentlich dagagen beim GameStart statt nur ein Initialize aufzurufen alle "HauptObjekte"/Collections komplett neu zu instantiieren? Dann hätte man komplett saubere Objekte, die beim Load ggf. befüllt werden.
(unabhängig davon, dass ein Bug in der Slotbehandlung ist)

Der Bug scheint ja vorrangig beim "Spielwechsel" aufzutreten, sonst hätten wir schon mehr Meldungen, dass es Probleme mit Eigenproduktionen gibt.

**Comment by GWRon** [comment]
Der Bug betrifft eigentlich nicht den Spielwechsel - denn es wird ja ein falscher Slot "visuell" belegt (der fuer "slotindex 5" vorgesehene landet visuell bei "slotindex 0").

Das komplette Neuinitialisieren / kompletter "Gamestate" wuerde ich jetzt ungern hier im Issue abhandeln. Es spricht an sich nichts dagegen - nur muessten evtl noch einige Dinge abgekapselt werden. Hatte auch schon mit dem Gedanken gespielt, denke aber es ist ein groesseres Projekt.

**Comment by nittka** [comment]
Nicht für dieses Ticket, aber es gibt immer wieder Probleme, weil ein "eigentlich nicht nötiges Aufräumen" unvollständig ist, weil Datenreste eines anderen Spiels vorhanden sind.

**Comment by GWRon** [comment]
Nochmal kurz: Der Fehler hier ist:
- "slotlist.AddItem()" hat 
  - nicht komplett ueberprueft, ob der slot valide ist
  - danach einfach das Item dem "panel" hinzugefuegt (fuers Scrolling, Layout, ...)
  - danach "SetItemToSlot" aufgerufen
- "slotlist.SetItemToSlot()" hat
  - nicht komplett ueberprueft ob der slot valide ist 
  - ebenfalls das Element dem "panel" hinzugefuegt (was eigentlich schon erledigt ist ...hmm)
  - "_SetSlot" aufherufen - was schlussendlich das Setzen NICHT erledigte (da es korrekt die Limits prueft)

Am Ende landet also das Element in "panel" und wird dadurch beim Rendern/update korrekt behandelt (also mit Mouseover, Dragging...)

Ist also kein Fehler "zwischen verschiedenen Spielen", sondern ein genereller.

**Comment by nittka** [comment]
Dieser Fehler ist doch mit der TGUISlotList-Anpassung behoben? Sollen wir das Ticket zumachen und ein neues aufmachen, wenn das Problem in einem "neuen" Spiel auftaucht?

**Comment by GWRon** [comment]
Ich dachte die Einkaufsliste ist dann noch immer links oben im Screen. Also issue noch offen.

**Comment by GWRon** [comment]
> Dieser Fehler ist doch mit der TGUISlotList-Anpassung behoben? Sollen wir das Ticket zumachen und ein neues aufmachen, wenn das Problem in einem "neuen" Spiel auftaucht?

Stimmt, betrifft ja dann wohl nur "verbuggte" alte Spiele.
