### ISSUE TITLE
Zielgruppenfarben in XML definieren

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#865]
Aus dem PR #864 

Es waere vielleicht sinnstiftend, Zielgruppenfarben in den XML definieren zu koennen, so dass man sie im Spiel referenzieren kann.

Dann kann der "Text" statt dem "Dreieck mit Ausrufezeichen" partiell eingefärbt werden. Da manche Farben sich vielleicht schlecht lesen lassen, wäre es praktischer die Einfärbung zu nutzen, die wir auch bei den "Toastmessages" drin haben:
`|color="+col.r+","+col.g+","+col.b+"|"+Chr(9632)+"|/color|Zielgruppename|color="+col.r+","+col.g+","+col.b+"|"+Chr(9632)+"|/color|`

config/settings_colors.xml  enthaelt ja bereits Spielerfarben, hier koennte man noch die Zielgruppen einbauen - und dann im naechsten Schritt diese in den anderen XML referenzierbar machen.
```XML
<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_8"		x="169"		r="40"		g="200"		b="40" />
/* becomes */
<script do="AddCopySprite"	src="gfx_contracts_base"	dest="gfx_contracts_8"		x="169"		color="targetgroups::manager" />
```
so in etwa.

**Comment by nittka** [comment]
Ist dieses Ticket durch #866 gelöst?

**Comment by GWRon** [comment]
Ja.
