### ISSUE TITLE
KI-Bankrott und Fernsehtastenfarben

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#874]
Wahrscheinlich werden die Farben der KI-Spieler nach einem Bankrott neu ausgewürfelt. Dabei kann es zu unschönen Konstellationen, wie dieser kommen, die gleich beim ersten Mal bei mir auftrat.
Evtl. sollten daher nur die 8 Grundfarben für die KI-Konkurrenten benutzt werden (Schwarz und Weiß kann man auch noch ausnehmen)

![TV-Farben_Green_Green_Green](https://user-images.githubusercontent.com/121659400/215007878-8ea32832-7a19-4fa7-a853-6c656dc02cda.png)

Man beachte die Tasten am Fernseher...

**Comment by nittka** [comment]
Ja die Farben werden gewürfelt. Das Zielbild sollte sein, dass die Farben verwendet werden, die auch beim Spielstart zur Verfügung stehen, wobei dieselbe Farbe nicht zweimal verwendet wird.

**Comment by GWRon** [comment]
Ich hatte gestern schon ueberlegt, die Spielerfarben demnaechst generalzuueberholen. Im Sinne von freierer Auswahl und bei der automatischen Farbvergabe wird eine ausgewaehlt, die einen gewissen Abstand zu den anderen drei Farben hat.

**Comment by lonk0123** [comment]
Ja, das meinte ich mit würfeln aus einem vorgegebenen Set, in dem aber helles, normales und dunkleres Grün, als auch wahrscheinlich mehrere verschiedene Blautöne enthalten sein werden, die man praktisch halt nicht (oder nur schwer) unterscheiden kann und eigentlich nicht zusammen vorkommen sollten.

**Comment by nittka** [comment]
In der Auswahl bei Spielstart sehen die drei Grüntöne noch unterschiedlich aus. Bei den Fernsehknöpfen, sind sie schon sehr ähnlich. Vielleicht sollte das mittlere grün durch eine völlig andere Farbe ersetzt werden. Auch die beiden Orange-Töne könnten sich stärker unterscheiden.
