### ISSUE TITLE
KI-Bankrott und Neustart

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#875]
1) Testweise mal die KI Bankrott gesetzt und festgestellt, daß im Spielstand die neuen KIs jeweils mit komplett unterschiedlichen Geldbeträgen starten: 
2 scheinen mit rund 500.000.000 zu starten, die zuletzt Bankrottgesetzte immer mit 750.000.

Für die Letztere besteht daher nach dem Neustart keinerlei Überlebenschance.

2) Was außerdem auffällt ist, daß, obwohl KI 2 & 3 über rund 80.000.000 liquide Mittel verfügen, noch nie ein Film oder Live-Ereignis von diesen **ersteigert** wurde.

3) 500.000.000 erscheinen mir außerdem relativ viel, da scheinbar die ganzen Sendestationen des Vorgängersenders komplett übernommen werden und dafür kein Cent abgedrückt werden muß (Edit: Sehe gerade, daß dies ein Bug sein muß, da dies sonst nicht der Fall ist. Dann ist die obige Summe OK).
Weitere Unstimmigkeit bei dieser Liquidität: KI nimmt als erste Aktion einen Kredit über 500.000 auf: 

![KI-Kredit](https://user-images.githubusercontent.com/121659400/215013018-9138a11b-5d42-4579-8204-b59a364f0142.png)

4) nach dem KI-Neustart hat die KI manchmal auch nach >48h noch nicht eine einzige Investition in neue Verbreitungswege getätigt und hockt stattdessen auf 500.000.000.
(Nur zur Absicherung: ja, ich habe den Spieler gewechselt, so daß die KI etwas machen konnte)

[DDR_NEU12.zip](https://github.com/TVTower/TVTower/files/10515619/DDR_NEU12.zip)
einfach in .zst umbenennen

**Comment by nittka** [comment]
Wenn eine KI bankrott startet, fängt diese nicht bei 0 an sondern bekommt abhängig vom Geld/Fundus etc. der anderen einen Startgeldbetrag (Anteil des Durchschnitts der restlichen). Die neu gestarteten erhalten mit Absicht keine Filme/Sendestationen des "alten" Senders. Das ist vorrangig Faulheit, da sonst die KI-Programmierung darauf eingestellt werden muss, einen Bestandssender zu sanieren, anstatt einen frisch zu starten.

Die 500K Kredit werden nicht aktiv aufgenommen sondern sind der automatische Startkredit, der vom Schwierigkeitslevel abhängt.

Der Neustart nach Bankrott ist in der KI-Programmierung noch nicht optimiert. Hauptproblem ist die Budgetverteilung. Wenn nicht genügend Lizenzen vorliegen, darf man nicht zu viel Geld in Antennen stecken, da die Fixkosten durch "kein Programm" schlecht zu decken sind. Viel Geld in wenige teure Lizenzen stecken, ist ebenfalls problematisch. Hier den richtigen Mix zu finden, ist mit Aufwand verbunden, den ich aktuell nicht für diesen fast irrelevanten Fall investieren will. Insb. da sowieso geplant ist, einen grundlegenden Umbau der KI-Strategie für die Budgetverteilung anzugehen.

**Comment by lonk0123** [comment]
Danke für die Infos. Dann kann man nur hoffen, da die Fälle eines Bankrottes nicht allzu häufig auftreten, insbes. nicht der Bug, daß die KI nicht mit dem Durchschnitt der anderen KIs beginnt, sond. wie beschrieben mit einem viel zu kleinen Fixbetrag.

**Comment by GWRon** [comment]
500.000.000 waeren schon eine Hausnummer.

**Comment by lonk0123** [comment]
Ja, erschien mir auch etwas zu hoch gegriffen. Spieltag 51. Selbst abzüglich der Kosten für neue Sender bleibt da einfach zu viel übrig. 
Die KI bekommt ja auch zusätzlich dadurch, daß sie scheinbar die ersten Tage manchmal durchschläft und kaum Geld ausgibt (Filme sind ja Reichweitenlevel 0, da kaum Stationen gekauft werden, extrem günstig) auch noch 5.000.000 pro Tag an Zinsen...

**Comment by nittka** [comment]
Der Betrag reichtet sich nicht nur nach den anderen KIs sondern auch nach dem menschlichen Spieler. Wenn der also gut gewirtschaftet hat, profitiert die neu startende KI (kann im Moment aber noch nichts damit anfangen ;-)).

**Comment by lonk0123** [comment]
So, habe in PreparePlayerStep1 gefunden, woher die 750.000 für den letzten KI-Spieler herkommen, der bankrott geht.
```
'=== FINANCE ===
		'inform finance about new startday
		GetPlayerFinanceCollection().SetPlayerStartDay(playerID, GetWorldTime().GetDay())
		If Not GetPlayerFinance(playerID) Then Print "finance "+playerID+" failed."

		Local addMoney:Int = difficulty.startMoney
		If isRestartingPlayer
			Local avgMoney:Int = 0
			For Local i:Int = 1 To 4
				If i = playerID Then Continue
				avgMoney :+ GetPlayerFinance(i).GetMoney()

				'add monetary value of programme licences
				Local pc:TPlayerProgrammeCollection = GetPlayerProgrammeCollection(i)
				Local licenceValue:Int = 0
				For Local list:TList = EachIn [pc.GetSingleLicences(), pc.GetSeriesLicences(), pc.GetCollectionLicences() ]
					For Local l:TProgrammeLicence = EachIn list
						licenceValue :+ l.GetPrice(l.owner)
					Next
				Next
				avgMoney :+ licenceValue
			Next
			avgMoney :/ 3 '3 to ignore our player

			'adjust by difficulty and replace start money only if average is more
			avgMoney :* difficulty.restartingPlayerMoneyRatio
			If avgMoney > addMoney Then addMoney = avgMoney
			'print "avgMoney = " + avgMoney
		EndIf
```

Sein neues Startkapital errechnet sich scheinbar nur aus dem Wert der Filmlizenzen der anderen Spieler und da diese kurz zuvor selbst pleite gingen und ewig nichts kaufen bzw. das gekaufte Filmmaterial lange Zeit wertlos sein wird (da Reichweitenlevel 0 etc.), strebt bei den später zugrundegehenden KIs der Durchschnittswert der Filmlizenzen aller anderen KIs gegen 0, so daß das viel zu geringe neue Startkapital zustande kommt.
Hier könnte man evtl. einfach auch das Vermögen auf dem Bankkonto hinzufügen, dann startete die KI mit wesentlich mehr als 750.000.

Daß der menschliche Spieler hier im Durchschnitt einbezogen ist, bin ich mir nicht ganz sicher (sollte eigentlich lt. Code oben) da im Spielstand ja bei mir Lizenzen im Wert von Duzenden Millionen vorhanden sind, also niemals ein Durchschnitt von unter 1 Mill. errechnet werden kann.

**Comment by nittka** [comment]
Das Geld der anderen Spieler wird schon berücksichtigt. Um Zeile 10 `avgMoney :+ GetPlayerFinance(i).GetMoney()`

Es wird auch nicht der Durchschnitt genommen, sondern ein Anteil des Durchschnitts `avgMoney :* difficulty.restartingPlayerMoneyRatio`

Wenn man natürlich kurz hintereinander mehrere Spieler pleite gehen läßt, sinkt der Startbetrag. Dieses hochfrequente Pleitegehen ist aber auch kein realistisches Szenario.

**Comment by lonk0123** [comment]
Also restartingPlayerMoneyRatio ist vom Schwierigkeitsgrad abhängig und kann das Startkapital letztlich vielleicht halbieren.
Es ist in der Tat nicht realistisch, daß meherere hintereinander Bankrott gehen, trotzdem ist an der Berechnung momentan etwas krum, ansonsten könnte nicht dieser völlig verkorkste Wert von 750.000 auftreten. 
Ich habe ja allein Assets im Wert von 100.000.000, die anderen beiden KIs haben je eine Halbe Milliarde auf dem Konto und die KI, die jetzt Pleite geht, soll mit weniger als 1 Mio. starten....

**Comment by nittka** [comment]
Es kommt hier zum Überlauf. Durch den riesigen Funduswert von Spieler 1, erhalten die ersten beiden bankrotten KIs viel Geld. Für die Dritte ist aufgrund der Integerbeschränkung die Summe (und damit Avg.) negativ und es gibt nur noch das normale Startkapital.

**Comment by GWRon** [comment]
Also an sich sollte das Geld (21 mrd bzw 2.147.483.647) reichen, wir koennen aber gern alle Geldwerte auf "long" umstellen.

**Comment by nittka** [comment]
(2.1Mrd) Ich denke, das ist erstmal nicht nötig. Das Problem in der Berechnung ist ja eher, dass munter zusammenaddiert wird (nicht nur Bargeld, sondern auch Funduswert).
