### ISSUE TITLE
Noch keine Auswirkung, wenn Gerichtsvollzieher im falschen Raum landet

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#876]
Wie im Forumsthread angemerkt:
https://www.gamezworld.de/phpforum/viewtopic.php?pid=90047#p90047

hat das Umleiten der Gerichtsvollzieher (FSK18 gesendet...) keine Auswirkungen auf den Besitzer des faelschlich besuchten Raumes. Derzeit kommt einfach nur das eigentliche Ziel um die Beschlagnahmung herum.

game.figure.customfigure.bmx
```Blitzmax
	'override to try to fetch the programme they should confiscate
	Method FinishDelivery:Int()
		'try to get the licence from the owner of the room we are now in
		Local roomOwner:Int = -1
		If inRoom Then roomOwner = inRoom.owner

		'block other rooms for x hours - like terror attack ?
		If Not GetPlayerBaseCollection().isPlayer(roomOwner) or not inRoom.name = "archive"
			'TODO
		'when entering an archive, confiscate a licence
```

**Comment by nittka** [comment]
Ein Blockieren wegen Durchsuchung wäre auf alle Fälle sinnvoll. Das Beschlagnahmen eines beliebigen Films aber schon etwas seltsamer (geschickt wegen FSK-18-Film, beschlagnahmt Familienfilm).

**Comment by StukovTTV** [comment]
Er könnte ja statt irgendwas zu konfiszieren einen Strafzettel vorbeibringen?

**Comment by Dalli87** [comment]
Eine Blockierung wegen Durchsuchung finde ich gar nicht schlecht. Allerdings, welche Auswirkungen ergeben sich dann konkret? 12 Stunden sperre, würde dies die KI dann überhaupt beeinflussen? Wie weit plant die KI ihr Programmm voraus?
Den Spieler würde dies eventuell in der Anfangsphase etwas stören...  danach dann auch nicht mehr wirklich, da nun genug Filme und Serien vorhanden sind, um 2-3 Tage vor zu planen.

Interessanter wäre es vllt, wenn der Gerichtsvollzieher dann sauer ist und direkt alle Räume im Stockwerk blockieren würde, wenn er im Falschen raum landet? Also er stellt dann alles auf den Kopf.
Wenn er nichts findet, könnte es eine lustige News geben:

Katze/Hund/Hamster/Vogel vom Gerichtsvollzieher beschlagnahmt!

% griff Gerichtsvollzieher an, welcher die % anschließend beschlagnahmt. Chef von $ ist nun traurig/verwirrt.


@StukovTTV was meinst du mit Strafzettel?
