### ISSUE TITLE
Some text like "Einschaltquoten" and "Senderimage" in the Statistics view appear to be hardcoded

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#886]
When playing in English, this screen still has German titles "Einschaltquoten", "Senderimage" etc:

![Screenshot from 2023-01-30 00-44-01](https://user-images.githubusercontent.com/123826268/215363940-0f6297dc-6f56-4a66-ad48-3f3c1ac413ad.png)

The text seems to come from hardcoded strings in `game.screen.statistics.bmx`, and not from `res/lang` (maybe those pieces of text aren't defined there yet at all).

**Comment by nittka** [comment]
Um den Statistikbildschirm wurde sich schon lange nicht mehr gekümmert. Das sieht man insb. in den weiteren Reitern (Senderimage, Zielgruppen etc.)
