### ISSUE TITLE
Manager-Werbung

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#889]
targetgroup_managers:

![Target_Group_Managers](https://user-images.githubusercontent.com/121659400/216255627-16284bd9-aecb-4195-b078-f161e07c644a.png)

ebenso in der Zielgruppenauflistung mit 'ALT'

**Comment by GWRon** [comment]
"res/lang" nicht aktualisiert?

res/lang/advertisement/advertisement_de.txt:
```
TARGETGROUP_ALL        = Alle
TARGETGROUP_CHILDREN   = Kinder
TARGETGROUP_TEENAGERS  = Jugendliche
TARGETGROUP_HOUSEWIVES = Hausfrauen
TARGETGROUP_EMPLOYEES  = Arbeitnehmer
TARGETGROUP_UNEMPLOYED = Arbeitslose
TARGETGROUP_MANAGERS   = Manager     <----------------------
```

Sollte also funktionieren.


![image](https://user-images.githubusercontent.com/2625226/216258892-16e4fece-c86b-4d41-b386-100cd9f0bc26.png)

**Comment by lonk0123** [comment]
die sieht bei mir genauso aus, spiele allerdings mit Scr0llbaers DB, aber selbst dort steht:
```
TARGETGROUP_ALL        = Alle
TARGETGROUP_CHILDREN   = Kinder
TARGETGROUP_TEENAGERS  = Jugendliche
TARGETGROUP_HOUSEWIVES = Hausfrauen
TARGETGROUP_EMPLOYEES  = Arbeitnehmer
TARGETGROUP_UNEMPLOYED = Arbeitslose
TARGETGROUP_MANAGER    = Manager
TARGETGROUP_PENSIONERS = Rentner
TARGETGROUP_WOMEN      = Frauen
TARGETGROUP_MEN        = Männer
```

**Comment by GWRon** [comment]
schau nochmal hin ... das ist nicht das gleiche.
TARGETGROUP_MANAGER
TARGETGROUP_MANAGER**S**

**Comment by lonk0123** [comment]
jein, es sind die Daten von Sc0llbaer von gestern, da ist ihm wohl ein 'S' abhanden gekommen...

**Comment by scr0llbaer9000** [comment]
wo hattest du meine DB denn her? `:)`

in meinem aktuellen Branch/PR ist das bereits gemerget (aber der hat die ganzen neuen Filme noch nicht), aber in dem Branch/Version, die du hast, halt noch nicht.

**Comment by lonk0123** [comment]
Ich hatte die DB über den Forumslink runtergeladen, wahrscheinlich 2 Minuten bevor es ein neues Update gab :)

**Comment by scr0llbaer9000** [comment]
nop, dieses "Managers"-Update ist ziemlich neu, darum ist es nicht in dem ZIP-File im Forum.

Ich werde Updates nur bei den offiziellen Releases des Spiels veröffentlichen. `:)`
