### ISSUE TITLE
Bug Auswahl Produktionsfirma

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#891]
Hier das Video zum vorhin bereits mit Ron besprochenen Bug, daß die DropDown-Liste nicht ausklappt:

https://user-images.githubusercontent.com/121659400/216390135-9cdeec48-5c60-4e4f-90f3-d6513232d877.mp4

**Comment by nittka** [comment]
... auch in der aktuellen Version noch?

**Comment by nittka** [comment]
Im Video verlässt Du den Screen nicht. Als Korrektur wurde vorgenommen, dass die Aktivierung zumindest aktualisiert wird, wenn man eine neue Einkaufsliste auswählt, also auch, wenn man raus- und wieder reingeht.

**Comment by GWRon** [comment]
Es reagiert auf das Hover...aber zeigt nicht die Liste an.

Die Listen/Dropdowns in der Personenauswahl funktionieren da aber ?

Ich habe heute Nachmittag einen kleinen Fix zu den Dropdowns hinzugefuegt. Bitte damit probieren (falls noch nicht geschehen)

**Comment by nittka** [comment]
Ich war ursprünglich davon ausgegangen, dass der "enabled"-Status falsch ist und dass deshalb das Setzen, bei der Einkaufszettelwahl helfen würden. Das ist ja nun möglicherweise nicht so.
Welche anderen Gründe kann es denn haben, dass das Dropdown nicht reagiert:
* Mausclick wird von einem anderen Control abgefangen (z.B. eins, dass bei Sprung aus einem anderen Raum an der Stelle offen war und durch den Sprung nicht korrekt abgeräumt)?
* ein anderer Status des Dropdowns ist auch noch für das "Nichtöffnen" verantwortlich?
* eine Aktualisierung der Firmen (durch Produktion der KI oder Spielproducer) im Hintergrund beeinflusst den Status?

**Comment by lonk0123** [comment]
> Im Video verlässt Du den Screen nicht. Als Korrektur wurde vorgenommen, dass die Aktivierung zumindest aktualisiert wird, wenn man eine neue Einkaufsliste auswählt, also auch, wenn man raus- und wieder reingeht.

nein, Raum verlassen fixt es nicht, nur kompletter Spielneustart (hatte ich vergessen im Video zu zeigen)

Ich kompiliere gleich mal den DropDown-Fix von Ron und dann schauen wir mal...

**Comment by GWRon** [comment]
Im Video erkennt man:
Anfangs ist der Dropdown "aktiv/offen" (dunkles orange)
Wenn lonk dann den Personen-Popup auf macht deaktiviert es den Dropdown
Danach sind nur noch "hover"-Effekte zu sehen (also Maus drueber/nicht-drueber). Kein "Aktivieren".

Wenn also da _nach_ Oeffnen des Personenpopups (und Schliessen) drauf "geklickt" wurde, aktivierte dies nicht das GUIElement. Hast Du danach geklickt oder nur noch "gehovert" ?

**Comment by lonk0123** [comment]
Ich habe die ganze Zeit geklickt, wenn ich über der DropDown-Liste war.

**Comment by GWRon** [comment]
So ... "kleines" Gespraech mit lonk gehabt .... und wir haben erstmal festgestellt:
- mit "Mausscrollrad" kann man noch die Werte auswaehlen
- "isOpen()" wechselt bei den Klicks

Ergo wird es ein Problem mit der Anzeige der "Liste" sein. Da der Hintergrund ebenfalls nicht sichtbar ist, scheint sie generell nicht gerendert/gehaendelt zu werden. Muessen wir mal schauen, was bspweise "productionCompanySelect.list.GetScreenRect().ToString() in dem Falle ausgibt.

**Comment by nittka** [comment]
Wäre es möglich, dass das Dropdown tatsächlich offen ist, aber hinter dem Control mit Dropdown und Slidern gerendert wird? Wenn der "z-Wert" aus irgendeinem Grund einmal falsch ist und dann nicht wieder neu ermittelt wird...

Lokal ließe sich das vielleicht reproduzieren, wenn man das Dropdown mit Absicht falsch positioniert. Dann könnte man zumindest sehen, ob es sich analog vehält (Mausrad erlaubt Firmenauswahl, aber "kein Rendering").

**Comment by nittka** [comment]
Ich packe das Ticket mal in den Meilenstein für das Bugfix-Release. Das Problem scheint mir wichtig genug zu sein, dass eine Lösung gefunden werden sollte.
Spricht denn etwas dagegen, die Controls (oder zumindest einige), beim Verlassen des Raums abzuräumen und bei Betreten des Raums (Öffnen des Screens) neu zu erstellen?

**Comment by GWRon** [comment]
Das komplette GUI-Aufraeumen und -Neuerstellen hatte ich mit lonk auch bereits im Gespraech erwaehnt.

Allerdings "versteckt" es den eigentlichen Bug nur. Vielleicht muss @lonk0123 wirklich mal die Koordinaten anpassen:
game.screen.supermarket.production.bmx
```
		'=== PRODUCTION COMPANY SELECT ===
		If Not productionCompanySelect
			productionCompanySelect = New TGUIDropDown.Create(New SVec2I(600,200), New SVec2I(150,-1), GetLocale("PRODUCTION_COMPANY"), 128, "supermarket_customproduction_productionbox")
			productionCompanySelect.SetListContentHeight(4*35)
		EndIf
```
Dort die "600" mal so anpassen, dass der Dropdown nach links rutscht und man sehen wuerde, ob eine aufgeklappte Liste unterhalb der "Hintergrundrahmen" durchscheint (falscher ZIndex).

**Comment by lonk0123** [comment]
z bleibt immer 0, auch, wenn der Bug auftritt

**Comment by GWRon** [comment]
> z bleibt immer 0, auch, wenn der Bug auftritt. 600 anpassen hatte ich schon probiert, nachdem nittka gepostet hatte, es ändert aber die Position der Liste nicht.

Spaeter im Code gibt es noch:
```
			'reposition dropdown
			If productionCompanySelect.rect.x <> content.x + 5
				productionCompanySelect.SetPosition(content.x + 5, contentY + 20)
				productionCompanySelect.SetSize(content.w - 10, -1)
			EndIf
```
Da wird das Element "rumgeschoben" - hier muesste man wohl mal kurzzeitig alles auskommentieren.


> Ich kann ihn jetzt auch einfach reproduzieren, indem ich vom Supermarkt z.B. in die Drehbuchagentur wechsele und dann die Zeit mit Stufe 7 oder 8 einen Tag laufen lasse, dann in den Supermarkt gehe und dann ist er zuverlässig da mit diesem Spielstand:

Hilft hier nix - funzt trotzdem wie es soll.

**Comment by GWRon** [comment]
> Der normale Logikfluß der Anwendung geht folgendermaßen bei einem Klick auf die initialisierte Liste:
> ********************************************onClick START********************************************____
> ********************************************SetOpen START********************************************____
> ********************************************SetOpen END********************************************____
> ********************************************onClick END********************************************____
> ********************************************onClick START********************************************____
> ********************************************SetOpen START********************************************____
> ********************************************SetOpen END********************************************____
> ********************************************onClick END********************************************____

Das sieht aber eher aus, als wenn es den Klick zwei mal registriert haette.

**Comment by lonk0123** [comment]
ja, das hat mich auch gewundert. Es triggert aber immer 2x ohne Bug

**Comment by nittka** [comment]
... auch wenn es so aussieht, als würde man den Bug damit nur verstecken, fände ich das Neuerstellen der GUI vertretbar:
* im Moment gibt es keinen Selbstheilungsprozess - einmal kaputt scheint nur Speichern und Neustarten zu helfen
* das Verhalten ist aktuell nicht (von allen und zuverlässig) reproduzierbar, was die Reparatur erschwert
* wenn der Fehler mit Neuerstellen auftritt, sollte er wesentlich leichter reproduziert werden können, denn nur die Aktionen unmittelbar nach Raumbetreten können verantwortlich sein

**Comment by lonk0123** [comment]
Also bei mir ist er ziemlich genau reproduzierbar:
1) Einfach in dem Beispielspielstand Zeit vergehen lassen und dann breakt es nach 1 oder 2 Tagen...

Bei allen Drop-Down-Listen, die ich aktiviert habe, ändert sich der z-Wert, nur bei dieser tut er das nicht. Kann es wirklich damit zusammenhängen?

**Comment by GWRon** [comment]
hmm ... ohne KI.... da muesste man schauen, wie genau die Umsetzung der Eigenproduktion der KI aussieht.

**Comment by lonk0123** [comment]
Es scheint direkt der PROD_STATUS_SUPERMARKET (TaskScripts.lua) Job zu sein, also sm_PlanProduction (game.ai.bmx).

Wahrscheinlich ist das genau wie der Ruckler-/Antennen-Bug auch wieder ein Fehler in irgendeiner Bibliothek, der nur bei einigen wenigen Rechnern auftritt.
Die Programmlogik scheint soweit ich das aufs Erste überblickt habe i.O. zu sein.

**Comment by nittka** [comment]
Könntest Du bitte folgendes prüfen. Der Supermarkt reagiert auch auf Logikänderungen. Wenn Du an den Anfang  der Methode "onProductionConceptChangeProductionCompany" in game.screen.supermarket.production.bmx (um Zeile 500) ein "print" einfügst, solltest Du sehen, ob bei der Produktionsplanung der KI hier ein Update erfolgt. `print "UPDATE COMPANY TRIGGERED"`

Als nächsten Schritt könntest Du dann mal an den Anfang der Methode `If Not CheckObservedFigureInRoom("supermarket") then Return False` einfügen und schauen, ob das den Fehler behebt.

**Comment by GWRon** [comment]
@nittka das sieht nach einem guten Kandidat aus.

Die Listener ueberpruefen wirklich nicht, ob der Befehl sozusagen von dem kommt, der auch die GUI sieht.

Die ProgrammeProducer nutzen diese Funktion auch - sprich wenn die was produzieren und man gleichzeitig im Supermarkt ist ... reagiert man auf die Aenderung.

**Comment by lonk0123** [comment]
Der Bug entsteht auch, wenn es noch nicht ein einziges Mal getriggert ist.

**Comment by GWRon** [comment]
Unabhaengig davon:
`onProductionConceptChangeCast` -> wird getriggert und ausgefuehrt ohne Ueberpruefung ob es vom Spieler im Supermarkt kommt.

```
	Function onProductionConceptChangeCast:Int(triggerEvent:TEventBase)
		If Not GetInstance().currentProductionConcept Then Return False
		If GetInstance().currentProductionConcept <> triggerEvent.GetSender() Then Return False
```
wuerde das abfangen.

**Comment by lonk0123** [comment]
@Ron:
Der Bug tritt auch mit Deinen Codeanpassungen auf.

**Comment by GWRon** [comment]
Das es das fixt, davon bin ich auch nicht ausgegangen. War mehr als "das muessten wir dort eh noch einbauen" gedacht.

**Comment by GWRon** [comment]
> Der normale Logikfluß der Anwendung geht folgendermaßen bei einem Klick auf die initialisierte Liste: ********************************************onClick START********************************************____ ********************************************SetOpen START********************************************____ ********************************************SetOpen END********************************************____ ********************************************onClick END********************************************____ ********************************************onClick START********************************************____ ********************************************SetOpen START********************************************____ ********************************************SetOpen END********************************************____ ********************************************onClick END********************************************____

Nur kurz zur Info: lonk hat im Discord geschrieben, dass er das nun nicht mehr reproduzieren kann und Klicks wieder einfach/einmal ankommen. Sollten wir also bei der Bugsuche weniger beachten.

**Comment by nittka** [comment]
Es klingt ja auch plausibel, dass wenn der Listener zweimal registriert wird und damit zweimal feuert, das Dropdown gleich wieder zugeht. Die Frage wäre, warum der Listener doppelt registriert wird (oder zweimal aufgerufen wird; weil vielleicht zwei Registries aktiv sind.)

**Comment by lonk0123** [comment]
ja, die Doppelklicks traten auf, waren aber danach nicht mehr reproduzierbar. Das Programm erzeugte immer 8 Aufrufe für eine einzige Aktion (also Öffnen/Schließen) des DropDowns, obwohl nur 4 der obig genannten pro Aktion "normal" gewesen wären.

**Comment by GWRon** [comment]
> Es klingt ja auch plausibel, dass wenn der Listener zweimal registriert wird und damit zweimal feuert, das Dropdown gleich wieder zugeht. Die Frage wäre, warum der Listener doppelt registriert wird (oder zweimal aufgerufen wird; weil vielleicht zwei Registries aktiv sind.)

Er war ja nur einmal registriert. und der Status des Dropdowns wechselt bei lonk korrekt zwischen "open=1" und "open=0". Ist also kein "zu auf zu" oder so.

**Comment by GWRon** [comment]
lonk im discord: `"problem planning production" in den logfiles der KI ist normal oder?`

Ist zwar vielleicht nur ein Nebenschauplatz, aber evtl koennte der Logeintrag auch beschreiben, welches Problem da ist (den result-code auswerten)

**Comment by lonk0123** [comment]
Wenn ich in Method sm_PlanProduction:Int(budget:Int, oneBlockBudgetFactor:Float) aus game.ai.bmx
die innere Schleife auf
```
For Local i:Int = 1 To 1
```
setze, tritt der Bug nicht auf.
Bei 5 tritt er auch auf, bei höheren Werten (1000), verbringt die AI eine halbe Ewigkeit im Supermarkt und steht davor Schlange...

**Comment by GWRon** [comment]
Bevor du allgemein "bug" schreibst: bitte immer sagen ob Du den dropdown-bug meinst, oder die Logausgabe.

**Comment by lonk0123** [comment]
Ich meine den DropDown.

**Comment by nittka** [comment]
Der "konzeptionelle" Fehler wäre aber, dass die KI-API-Aufrufe überhaupt eine Auswirkung auf GUI-Elemente haben, die gerade gar nicht zu sehen sind.

**Comment by GWRon** [comment]
Wir hatten bei lonk ja auch einen GC-Fehler, den ich hier nicht nachvollziehen kann.

Wenn die KI API-Aufrufe macht ... dann geschieht das ja aus Threads. sprich wir erzeugen Events aus Threads.
Eventuell kommt sich da was ins Gehege.
Aber ... das muessten dann Dinge sein die permanenten Einfluss haben. Ein uebersehenes "guidropdown.update"-event oder so, wuerde ja ruckzuck "nachgeholt" werden.

Denke es waere einfacher, wenn - wie ich lonk bereits beschrieben hatte - geschaut wird an welcher Stelle die GUI sich entscheidet eben nichts zu rendern. 
Solange ich den Fehler nicht reproduzieren kann ist es halt ein mehr oder weniger stumpfes Herumstochern im Code.

**Comment by GWRon** [comment]
Wenn es an den Events + Threading laege:
```
					For Local i:Int = 1 To 15
						producer.ChooseProductionCompany(pc, pc.script)
						producer.ChooseCast(pc, pc.script)
						producer.ChooseFocusPoints(pc, pc.script)
```
-> ChooseProductionCompany sendet `GameEventKeys.ProductionConcept_SetProductionCompany` event
-> ChooseCast sendet `GameEventKeys.ProductionConcept_SetCast` event (fuer jede Person)
-> ChooseFocusPoints sendet `GameEventKeys.ProductionConcept_SetProductionFocus` event (fuer jeden "Aspekt")

Sprich da kommen pro "Durchlauf" einige Events zustande - und die jedesmal aus einem Subthread.

Alle diese Events sind direkt getriggert und werden sofort (vom Subthread heraus) ausgefuehrt.

**Comment by GWRon** [comment]
@lonk0123 zwei Dinge zum Ausprobieren:
- geschieht der Fehler auch, wenn du die KI mal nicht multithreaded laufen laesst (game.ai.base.bmx THREADED_AI_DISABLED = True) ?
- ich habe mal unter https://github.com/TVTower/TVTower/tree/misc_testdeferredevent ein paar Testaenderungen eingebaut, da wuerden diese obig beschriebenen Events nicht mehr direkt getriggert, sondern nur noch "registered" werden. Das bedeutet, der Hauptthread wuerde sie dann abarbeiten

Wenn damit der Bug "weg" waere bzw nicht auftaucht, koennte das unser Schuldiger Code sein.

**Comment by lonk0123** [comment]
> * geschieht der Fehler auch, wenn du die KI mal nicht multithreaded laufen laesst (game.ai.base.bmx THREADED_AI_DISABLED = True) ?
nein, dann tritt der Bug in mehreren Durchläufen nicht auf.

**Comment by GWRon** [comment]
Dann probiere auch noch den genannten branch.

**Comment by GWRon** [comment]
@nittka 
das reine Hinzufuegen der LockMutex/UnlockMutex brachte bei lonk keine Abhilfe - es bedurfte noch der Umstellung auf Register-Event statt Trigger-Event.
Vielleicht hilft uns das ein grundlegendes Problem in der "Producer"-Logik aufzuspueren. Will vermeiden, dass wir da jetzt zwar hier Abhilfe schaffen koennen, aber andere Stellen dadurch unerkannt bleiben.

**Comment by nittka** [comment]
Ist sicher, dass es ein Problem in der Producer-Logik ist? Kann ausgeschlossen werden, dass es nicht an der Auswertung von Events durch die GUI liegt, die sich für diese Events gar nicht interessieren bräuchte?

**Comment by GWRon** [comment]
ich meinte mit "Producer"-Logik generell Dinge die in den producer-Dateien stattfinden (also auch die Logik-GUI und GUI-Logik-Konnektoren)

**Comment by GWRon** [comment]
Ich habe lonk mal immer nur "einen" der 5 Events auf das "RegisterBaseEvent()" umstellen lassen - um rauszufinden ob ein spezieller Event "Kaputt macht".:

```
RegisterBaseEvent(GameEventKeys.ProductionConcept_SetScript, new TData.Add("script", script), Self ) --> DropDown kaputt
RegisterBaseEvent(GameEventKeys.ProductionConcept_SetProductionCompany, new TData.Add("productionCompany", productionCompany), Self ) --> kaputt
RegisterBaseEvent(GameEventKeys.ProductionConcept_SetCast, new TData.AddNumber("castIndex", castIndex).Add("person", person), Self ) --> NICHT kaputt
RegisterBaseEvent(GameEventKeys.ProductionConcept_SetProductionFocus, new TData.AddNumber("focusIndex", focusIndex).AddNumber("value", value), Self ) --> kaputt
RegisterBaseEvent(GameEventKeys.ProductionFocus_SetFocus, new TData.AddNumber("focusIndex", index).AddNumber("value", GetFocus(index)), Self ) --> kaputt
```

Natuerlich gibt es keine Garantie, dass es bei den anderen Events nicht auch "irgendwann/irgendwo" ein Problem gibt.

Wenn wir der Aussage oben glauben wollen (, dass es bei den anderen nicht zu dem Problem kommt) ... frage ich mich, was da schief gehen koennen soll:


Einziger Zuhoerer fuer dieses Event ist in game.screen.supermarket.production.bmx:
```
	'LOGIC -> GUI reaction
	'GUI -> GUI reaction
	Function onProductionConceptChangeCast:Int(triggerEvent:TEventBase)
		If Not GetInstance().currentProductionConcept Then Return False
		If GetInstance().currentProductionConcept <> triggerEvent.GetSender() Then Return False

		Local castIndex:Int = triggerEvent.GetData().GetInt("castIndex")
		Local person:TPersonBase = TPersonBase(triggerEvent.GetData().Get("person"))

		'do this before skipping without changes
		GetInstance().refreshFinishProductionConcept = True

		'skip without changes
		If GetInstance().castSlotList.GetSlotCast(castIndex) = person Then Return False
		'if currentProductionConcept.GetCast(castIndex) = person then return False

		'create new gui element
		GetInstance().castSlotList.SetSlotCast(castIndex, person)
	End Function
```
Das geht ja sofort auf "Return False", wenn die Einkaufsliste nicht die ist, die im Supermarkt hinterlegt ist (hatte mir dazu auch testweise mal `Notify "onProductionConceptChangeCast"` unterhalb der "<>"-checks hinzugefuegt.

```
	Function onProductionConceptChangeCast:Int(triggerEvent:TEventBase)
		If Not GetInstance().currentProductionConcept Then Return False
		If GetInstance().currentProductionConcept <> triggerEvent.GetSender() Then Return False
Notify "onProductionConceptChangeCast"
```

Wurde nur aufgerufen, wenn ich selbst was aenderte. Wenn das bei @lonk0123 auch "ohne herumspielen an der Besetzungsliste" aufploppt ... waere das ein neuer Hinweis.

**Comment by GWRon** [comment]
```
	Method sm_PlanProduction:Int(budget:Int, oneBlockBudgetFactor:Float)
		If Not _PlayerInRoom("supermarket") Then Return Self.RESULT_WRONGROOM
		Local result:Int = Self.RESULT_NOTFOUND
		Local producer:TProgrammeProducer = new TProgrammeProducer
'add
		Local eventsCallCount:Int = EventManager.listenersCalled
		Local eventsTriggerCount:Int = EventManager.eventsTriggered

...
'add
		Notify "sm_PlanProduction raised about " + (EventManager.eventsTriggered - eventsTriggerCount) +" events and called about " +(EventManager.listenersCalled - eventsCallCount) + " listeners."

		Return result
	End Method

```
Bei mir kommen in lonks Speicherstand nach dem Verlassen des Supermarktes fuer die 3 Spieler 3 Notifys ... die Werte sind dort unauffaelig (ein bis knapp zweistellig) wenn man "RegisterBaseEvent" nutzt und landen bei knapp 40 events und calls wenn "TriggerBaseEvent" genommen wird.

Es waere interessant, ob bei @lonk0123 (im Master-branch - also ohne den "Fix" mit RegisterBaseEvent) das Dropdown sofort kaputt ist, wenn die drei ihre "nach dem Einladen + Supermarkt-Verlassen"-Notifies abgesetzt haben - oder ob es einfach spaeter nicht mehr geht (ohne dass weitere "Notify") kamen.

**Comment by lonk0123** [comment]
Schleife in game.ai.bmx mal auf böse 100.000 gestellt:
```
For Local i:Int = 1 To 100000
```

1) Das Spiel erzeugt den DropDownBug nur, wenn producer.ChooseCast(pc, pc.script) so derbe aktiv ist.
2) Im Video sieht man, wenn ich zur KI 3 wechsele, die gerade im Supermarkt an Teil 2 plant, tatsächlich durch die 100.000 Versuche den passenden Cast zu finden, die KI tatsächlich an den GUI Elementen rumspielt.

Dies sollte auf gar keinen Fall passieren.
Es erklärt auch einen anderen Bug, der gelegentlich auftritt (auch in der 15er Schleife), daß, wenn man selbst eine Produktion planen will und den Supermarkt betritt, dann links auf eine Produktion klickt, plötzlich mehrere Schauspieler in der Hand hält.  

https://user-images.githubusercontent.com/121659400/216926227-22aa280d-61ea-4c47-a42e-2234d1af6356.mp4

**Comment by GWRon** [comment]
Wenn du einen Spieler beobachtest, reagiert die GUI entsprechend (du bist ja dann in dem Bildschirm).

_Vor_ dem aktuellen Masterstand hatte die GUI auch auf fremde Aenderungen reagiert. Waehrend Du im Supermarkt bist (und die GUI siehst) kann die KI keine Planung machen. Allerdings gibt es Dritt-Produzenten die immer mal wieder was produzieren und DIE sind nicht im Hochhaus. Ergo machen DEREN Aenderungen das von dir beschriebene Problem des geaenderten Casts.

Mit dem aktuellen Stand vom Master ist das aber behoben.

**Comment by GWRon** [comment]
Wenn die Fassung "von letztens" (also nicht aktueller Master-Stand) bei lonk buggt, dann ist "dropdown.list" nicht mehr im GUIManager.list.
```
			If KeyManager.IsHit(KEY_Y)
Local ObservedGUIObject:TGUIObject
If TScreenHandler_SupermarketProduction.productionCompanySelect
  ObservedGUIObject = TScreenHandler_SupermarketProduction.productionCompanySelect.list
EndIf
If ObservedGUIObject
  If Not GUiManager.List.Contains(ObservedGUIObject)
    print "ObservedGUIObject nicht mehr in der Liste"
  Else
    print "ObservedGUIObject ist in der Liste"
  EndIf

  Local state:TLowerString = TScreenHandler_SupermarketProduction.evKey_supermarket_customproduction_productionbox
  If GUIManager.haveToHandleObject(ObservedGUIObject,State,-1000, -1000)
    print "haveToHandleObject = True   (" + Millisecs() + ")" 
  Else
    print "haveToHandleObject = False   (" + Millisecs() + ")" 
  EndIf
  If ObservedGUIObject.Isvisible()
    print "ObservedGUIObject.Isvisible() = True   (" + Millisecs() + ")" 
  Else
    print "ObservedGUIObject.Isvisible() = False   (" + Millisecs() + ")" 
  EndIf
Else
  print "ObservedGUIObject nicht gefuellt"
EndIf
```

fuehrt bei verbuggtem Zustand zu:

```
ObservedGUIObject nicht mehr in der Liste
haveToHandleObject = False   (15816706)
ObservedGUIObject.Isvisible() = False   (15816706)
```


Das bedeutet, irgendwie verschwindet das "list"-Objekt aus der GUIManager.list.
Wenn das durch "Multithreaded"-Zugriff passieren sollte:

Vor der letzten Aenderung reagierte ja 
```
	Function onProductionConceptChangeCast:Int(triggerEvent:TEventBase)
```
Vom Supermarkt-Screen auf ALLE Aenderungen - egal ob es zum aktuell dort hinterlegten Script passt.
Mit der Aenderung reagiert es nur noch, wenn das "currentProductionConcept" mit dem Event-Sender uebereinstimmt.

Wenn also nun Drittproduzenten was machen, passiert nix mehr.


Was ist aber nun, wenn die KI was macht und wir sie beobachten?

- onProductionConceptChangeCast wird ausgeloest -> Da derzeit das originaere Event noch per "TriggerBaseEvent()" ausgeloest wird, laeuft "onProductionConceptChangeCast" hier auch im KI-Thread!
- am Ende der Funktion wird bei Aenderung folgender Aufruf durchgefuehrt: `GetInstance().castSlotList.SetSlotCast(castIndex, person)`
- das erzeugt ein neues GUI-Element (manipuliert also GUIManager.list). Das GUI-Element wird aus dem KI-Thread heraus angelegt

Und? Was passiert nun, wenn der Mainthread gerade auch diese Liste bearbeitet? Konkurrierender Zugriff - im Fall der "TObjectList" kann bspweise das Vergroessern des inneren Arrays das Problem sein (da das den Array "ersetzt").

Wieso da nun unbedingt die Dropdown-Liste rausfliegt weiss ich allerdings nicht. Jedenfalls ist es denke ich uncool, wenn ein anderer Thread das GUIElement anlegt und die GUIManager.list-Liste nicht geschuetzt ist.

**Comment by GWRon** [comment]
Ich muss zu obiger Theorie aber gestehen:

In "base.gfx.gui.bmx" habe ich bei "Type TGUIObject" mal folgendes hinzugefuegt:
```BlitzMax
	Method New()
		_lastID:+1
		_id = _lastID
'DAS HIER		
		If CurrentThread() <> MainThread()
			print "ChildThread creates " + TTypeID.ForObject(self).name() +"."
		EndIf
'----------
```

Jegliches GUIObjekt was von der KI angelegt wird (durch einen direkten TriggerEvent oder so) wuerde also eine solche Ausgabe erzeugen.

Nur den Supermarkt zu besuchen reicht allerdings nicht aus, man muss schon eine Einkaufsliste angeklickt haben / CastSlotList anzeigen (da sonst "GetAmount()" eben dieser Liste -1 ist und das Setzen durch die KI fehlschluege).

Wir haben hier also durchaus GUI-Elemente, die von der KI angelegt werden. Sind aber bis jetzt die einzigen, die ich aufgefunden habe.

**Comment by nittka** [comment]
Kurze Frage zum aktuellen Stand: ist das Hauptproblem durch Nichtberücksichtigung der Drittproduzenten schon behoben? Denn das Beobachten der KI im Supermarkt sollte im normalen Spiel ja nicht vorkommen. Weitere Arbeiten könnten dann unter "Verbesserung Multithreading etc." mit einer geringeren Priorität weiterlaufen.

**Comment by GWRon** [comment]
Naja schoen wäre es schon, wenn das Beobachten der KI nicht "manchmal" zu Abstuerzen fuehren koennte ;-)

**Comment by GWRon** [comment]
@lonk0123 kannst Du auch bitte mal den extra-Branch ausprobieren, ob nicht doch noch der Dropdown kaputt geht? Kurzum: Verifizieren, dass (zumindest scheinbar) der Branch den Bug fixt.

**Comment by lonk0123** [comment]
Ja, der Branch läuft ohne DropDown-Listen-Bug durch.

Warnung am Rande: Da ich mit Geschwindigkeit 8 die Zeit vergehen lasse, kommt es beim Beispielspielstand (der Tag 13 startet) so ungefähr ab Tag 40 zu Rucklern, die dann auch bleiben (also wie bei den Antennenrucklern). Auch hier wieder ganz besonders deutlich sichtbar im Nachrichtenstudio.
Dürfte aber erstmal irrelevant sein, da kaum jemand 30 Tage am Stück hintereinander durchspielen sollte.

**Comment by GWRon** [comment]
Bei den Rucklern waere wieder wichtig, ob es dann _wieder_ mit "GCSuspend()" aufhoert (also Ruckler durch den GC) oder nicht (Ruckler durch etwaig lange brauchende Berechnungen)

**Comment by lonk0123** [comment]
ja, die sind mit GCSuspend() wieder weg. Hatte ich schon ausprobiert.
