### ISSUE TITLE
Imageverlust bei Programmausfall aller Anstalten gleich 0

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#901]
Hab beim Testen des Supermarkt-Bugs mal die Zeit bei ausgeschalteter KI laufen lassen und festgestellt, daß die Imagewerte eingefroren sind.
Dies wird passieren, weil diese relativ zueinander berechnet werden, d.h. weil alle gleichzeitig Sendeausfall produzieren, ergibt es keine Änderung.

Ist im normalen Spielverlauf ein unrealistisches Szenario, ich weiß, aber Sendeausfall einer oder gar mehrerer KIs hats ja schon mal gegeben, wenngleich es jetzt sehr selten vorkommt.

Irgendwo fehlt noch eine Komponente, die bei Quoten unterhalb von 5 oder 10% generell etwas Image abzieht.

**Comment by nittka** [comment]
Dass bei Sendeausfall *aller* Stationen keine Imagaanpassung erfolgt ist explizit so gewünscht (irrelevant, da es wie bemerkt nicht vorkommt).

Für die Imageberechnung gibt es noch das offene Ticket #504. Eine erste Anpassung war, die Berechnung von absoluter Zuschauerzahl auf Quote umzustellen. Die Anpassung des Image gehört auchzu den Punkten, die in einem großen Balancing berücksichtigt werden müssen. Meine Vorstellung ist, der Zugewinn von Image am Anfang leichter sein muss (man fängt gerade an), später aber schwieriger wird (bei einem höheren Image haben die Leute auch mehr Erwartungen; Ausrutscher werden stärker bestraft).

Das generelle Abziehen von Image bei schlechten Einschaltquoten ist da einer der Aspekte.

**Comment by lonk0123** [comment]
OK, das Problem ist nämlich (zumindest in meinen Spielständen), daß das Image eigentlich nur einen Weg kennt - den nach oben, da es meist schon ausreicht, sein Image mit den Nachrichten aufzupolieren. 
Hier kann man bei Top-Nachrichten durchaus mal exorbitante 0.1 gewinnen. Bei schlechten Nachrichten geht es aber meist nur 0.01 nach unten...
