### ISSUE TITLE
Eigenproduktion: Kosten für Produktionsfirmen unabhängig von Blockanzahl

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#907]
Aus der Diskussion: https://github.com/TVTower/Documentation/commit/87018fb87d26a51a9a6964bbd1cba0ae867fad15#commitcomment-99947055
ging hervor

> Die Produktionsfirma ändert ihre Kosten aber nicht, sprich, sie produziert 1 Block für den gleichen Betrag wie einen Monumentalschinken von 5 Blöcken.

Das ist tatsaechlich derzeit der Fall - und nicht so gewollt.

**Comment by nittka** [comment]
Ähnliches sollte wohl auch für die Darsteller gelten. Ich weiß gerade nicht, inwieweit die Produktionsdauer an der Anzahl der Blöcke hängt, denn man könnte die Kosten natürlich auch (stärker) an die Produktionszeit koppeln (länger beschäftigt, mehr Gehalt/Gage nötig).
Dann bekämen auch die Punkte für die Produktionszeit eine ganz neue Bedeutung (etwas Mehrkosten für eine "schnelle" Produktion, mit der man dann an anderer Stelle viele Kosten spart, aber auch ein schlechteres Ergebnis erhält).

Im Ergebnis würden die Kosten also nicht an der Anzahl der Blöcke hängen, sondern an der Produktionszeit und die Anzahl der Blöcke hat aber starken Einfluss auf die Produktionszeit.

**Comment by GWRon** [comment]
Beim Cast werden die Bloecke schon einberechnet.

Aber ja, man koennte ueberlegen, die Produktionszeit statt der Bloecke anzusetzen. Allerdings muss man dann schauen, dass die Produktionsfirma entsprechend teuer ist (und nicht dass man fuer 10.000 Euro "mehr" bei der Produktionsfirma 50.000 an Castkosten spart)

**Comment by nittka** [comment]
Die Idee war, dass die Schauspieler ja für die "gesamte" Produktionszeit zur Verfügung stehen müssen und deshalb die Gage nicht nach Blöcken, sondern nach Zeit berechnet wird. Ich würde es nicht mal als Problem sehen, wenn durch 10K für die Firma, 50K Gage gespart würde... Denn die Punkte die man für die Zeitersparnis vergibt, können nicht für andere "Qualitätspunkte" ausgegeben werden, das Produktionsergebnis wird also schlechter. Preisersparnis=geringere Qualität (bzw. größeres Risiko geringerer Qualität).

Kurzfristig wäre es auf alle Fälle richtig, auch die Produktionsfirmakosten von den Blöcken abhängig zu machen und die vergebenen Punkte nicht mit 500 pro Punkt zu bewerten.

**Comment by nittka** [comment]
Ich mache dieses Ticket mal zu. Mit dem PR spielt die Blockanzahl eine Rolle. Mehr in Richtung Kostenbalancing erfolgt separat.
