### ISSUE TITLE
TemplateVariable.Copy() zur Verfügung stellen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#908]
Für die bessere Unterstützung von Variablen in Nachrichten-Threads wäre ein variables.copy() sehr hilfreich. Neue Nachrichten könnten aus dem Template initialisiert werden, indem ein Klon der Templatevariablen übergeben wird, der dann ohne Einfluss auf andere auf diesem Template basierenden Nachrichten verwendbar ist.

**Comment by GWRon** [comment]
Ein Problem sehe ich in `GetParentTemplateVariables()`

```
Type TScriptTemplateVariables extends TTemplateVariables
	Field parentID:int
	Field parent:TScriptTemplate {nosave}


	Method GetParentTemplateVariables:TTemplateVariables()
		if parentID and not parent
			parent = GetScriptTemplateCollection().GetByID(parentID)
		endif

		if parent then return parent.templateVariables
		return Null
	End Method
```

Wenn ich ein Kindelement kopiere ...  muss ich eigentlich auch das Elternelement kopieren.

```
							'if the parent stores this variable (too) then save
							'the placeholder there instead of the children
							'so other children could use the same placeholders
							'(if there is no parent then "self" is returned)
							local parent:TTemplateVariables = GetParentTemplateVariables()
							if parent and parent.GetVariableString(placeholder, "", False)
								parent.AddPlaceHolderVariable(placeholder, replacement)
							else
								AddPlaceHolderVariable(placeholder, replacement)
							endif
```
obiger Code zeigt, dass Elternelemente beeinflusst werden koennen. Elternelemente wissen aber nix von den Kindern (sonst koennte man "hochwandern" und dann Wurzel + Kinder kopieren).

Allgemein habe ich Bedenken, dass das doch "groessere Kaliber" werden koennten, die man hier kopiert.

**Comment by nittka** [comment]
Für den Start würde ich im copy eine Exception werfen (cannot copy variables if parent exists), wenn die parent-ID gesetzt ist.
Der Parent wird vorrangig für Serien (Script) verwendet, so dass Folgen gemeinsame Werte untereinander weitergeben können. Reguläre TemplateVariables haben gar keinen Parent.

Alternativ: copyWithoutParent() - dann ist klar, dass es keinen Parent geben darf (und trotzdem Exception werfen, wenn es einen gibt).

**Comment by nittka** [comment]
closed by #899
