### ISSUE TITLE
Segmentation Fault bei Auswahl: Online Game

### ISSUE THREAD

**Issue by jukey** [TVTower/TVTower#92]
Ich nutze die `TTTower_Linux64` Version v0.5.1 Build "05.06.17 14:39" unter Ubuntu Gnome 17.04. Das Spiel funktioniert soweit sehr gut. Wenn ich jedoch im Hauptmenü nach Spielstart "Online- oder Netzwerk-Spiel" auswähle stürzt es mit einem SegFault ab.

Wenn ich sachdienliche Hinweise zur weiteren Aufklärung liefern kann, bitte ich um einen entsprechenden Hinweis.

**Comment by GWRon** [comment]
Danke fuer den Hinweis. Ich werde den Button wohl deaktivieren muessen bis der Mehrspielermodus richtig integriert ist.

Kurz: momentan ist kein Mehrspielermodus moeglich.

**Comment by nittka** [comment]
Kann dieses Ticket geschlossen werden? Es bezieht sich auf eine alte Version. Falls der Mehrspielermodus eingeführt wird/ist und nicht funktioniert, kann ein Ticket mit den konkreten Informationen aufgemacht werden.
