### ISSUE TITLE
Auswahl Werbeverträge

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#920]
Aufgrund von https://www.gamezworld.de/phpforum/viewtopic.php?pid=90116#p90116 habe ich mal in die Ermittlung der neuen Werbeverträge geschaut. Es gibt zwei Refill-Methoden und aktuell wird immer Refill2 verwendet, wo es nur zwei Bereiche gibt (cheap und den Rest). Refill1 hat 6 Bereiche (finde ich etwas viel, 3 sollten eigentlich reichen - Cheap, Normal, Prime). Wenn man auf 1 umschaltet, ist gefühlt mehr Durchschnittswerbung verfügbar.

Es ist nicht so leicht zu erkennen, welche die "neuere" Version ist...

**Comment by GWRon** [comment]
Die aktuelle Methode sollte die von Gast2 gewollte sein.

Begruendungen finden sich irgendwo in den Tiefen des Forums.

Wir koennen das gerne abaendern, kombinieren, alternieren (zwei Werbemaklerfuzzis mit eigenem Angebot... Wechsel aller 6 Stunden...).

**Comment by nittka** [comment]
Ich glaube, es wäre gar nicht schlecht bei dem einen Werbemakler die Methoden zu wechseln, vielleicht gar nicht mal regelmäßig.
Wenn das Force-Flag gesetzt ist, wird die Methode gewürfelt (50:50) ansonsten wird die aktuelle Methode verwendet (nur Cheap und Rest). Die Variante mit mehr Filtern würde ich noch etwas ausdünnen.

**Comment by nittka** [comment]
Neben dem Wechsel der Auswahlmethode könnte auch die Berechnung der Filtermethoden verbessert werden. Aktuell werden bei jedem Auffüllen der Werbeagentur die Statistiken des Vortags neu geholt und ermittelt.
Mir erscheit es sinnvoller entweder nach der Ausstrahlung die Statistiken für die aktuelle Stunde zu aktualisieren und beim Auffüllen nur die lokal gehaltenen Statistiken zu verwenden oder aber bei Tagesbeginn die Statistik des Vortags einmalig komplett auszulesen (bzw. den Cache zu invalidieren) und diese dann den ganzen Tag über zu verwenden.

**Comment by nittka** [comment]
Mit der überarbeitetn Werbeauswahl wirkt es so, als würde die KI durchschnittlich höhere Werbeeinnahmen pro Tag erreichen. Das wäre auch intuitiv, da es mit dem Zufallsmodus eine höhere Chance auf Tageswerbung gibt.
