### ISSUE TITLE
Check validity of programmedatamods.xml

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#925]
As per https://github.com/TVTower/Documentation/issues/23

> Einige Bezeichnungen in der Datei `programmedatamods.xml` scheinen übrigens veraltet.
> 
> z.B.
> 
> * `audienceAttraction id="Manager"` - muss das nicht auch upgedatet werden zu "Managers"?
> * `genre id="6" name="documentation"` - an anderen Stellen im Spiel und auch in derselben Datei wurde das schon korrigiert zu "documentary".
> 
> Oder hier z.B. `<badFollower>action,scifi,thriller</badFollower>` werden die Genres per String referenziert, und nicht per Nummer. Der richtige definierte Name wäre aber `sci-fi` mit Bindestrich?

**Comment by nittka** [comment]
Das Einlesen der Daten erfolgt in TRegistryProgrammeDataModsLoader, das Erkennen der Genre aus Strings erfolgt mittels TVTProgrammeGenre#GetByString (https://github.com/TVTower/TVTower/blob/04e3f354d88ed686bcf4736502afb47870281acd/source/game.gameconstants.bmx#L1131).

Ich schaue mir den Code mal an, ob "Referenzfehlern" unbemerkt durchrutschen.

**Comment by nittka** [comment]
Im Masterstand ist "Manager" bereits "Managers". "documentation" ist eine interne ID, die meiner Ansicht nach auch so bleiben kann. Die Genre passen (siehe letzter Kommentar).

Ich habe den Loader-Code mal mit Exceptions versehen, wenn eine Referenz falsch ist. Aus meiner Sicht ist die Datei OK.

**Comment by nittka** [comment]
Ich mache das Ticket zu. Für diese Daten wurde ein Logging ergänzt, falls offensichtliche inhaltliche Fehler existieren.

**Comment by nittka** [comment]
Ich hatte nur die "Referenzen" geprüft (also followers...). Im Knotenheader (id=x name=y) gab es tatsächlich noch Inkonsistenzen (nicht nur sci-fi und documentation).
