### ISSUE TITLE
GUI-Update im Supermarkt

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTower#927]
Bei kurzen Tests mit Drehbüchern ist mir aufgefallen, dass sich (mindestens) der Produktion-Abschließen-Button im Masterstand seltsam verhält.
* Produktion konzipieren und abschließen - der Button wird deaktiviert und grün (OK)
* Supermarkt verlassen und frische Einkaufsliste holen
* Supermarkt betreten und frische Einkaufsliste wählen - der Abschließen-Button ist immer noch grün.

**Comment by nittka** [comment]
In der Releaseversion wechselt die Farbe des Buttons bei Wechsel zwischen Einkaufslisten mit unterschiedlichem Status korrekt die Farbe (und bleibt nicht die ganze Zeit grün).

**Comment by GWRon** [comment]
[Eventuell mit Einer dieser Aenderungen verbunden? https://github.com/TVTower/TVTower/commits/master/source/game.screen.supermarket.production.bmx

**Comment by nittka** [comment]
Ich denke, es hängt mit den Speicheroptimierungen zusammen. Wenn ich in RefreshFinishProductionConceptGUI im Supermarkt finishProductionConcept.SetSpriteName("gfx_gui_button.datasheet.positive") durch ".negative" ersetze wird der Button tatsächlich rot, bleibt dann aber auch immer rot.
Es sieht so aus, als würde die Farbe des gesetzten Sprites nicht akualisiert werden.

Ich denke, da siehst Du schneller, wo das Problem liegen könnte.

**Comment by GWRon** [comment]
Wenn dann liegt es sicher an TGUIButton.GetSprite() - da dort ein neues Cacheverhalten eingebaut wurde.

**Comment by GWRon** [comment]
SetSpriteName() funktioniert wie es soll ... evtl wird es nicht korrekt "resetted" wenn man eine andere Einkaufsliste aktiviert bzw den Raum betritt.

**Comment by nittka** [comment]
SetSpriteName sollte die Werte ggf. nur ändern, wenn der neue Name ungleich dem alten ist (sonst ändert sich ja nichts und es würden unnötig neue Sprites geholt).

Für mich sieht es auch so aus, als ob die gesetzten Sprites im Supermarkt die richtigen Namen haben ( gfx_gui_button.datasheet.informative.disabled wenn die Planung abgeschlossen ist). Die Farbe des Buttons ist dann aber weiterhin die von .positive!?

**Comment by GWRon** [comment]
```
	Method Render()
		'update finishProductionConcept-button's value if needed
		If refreshFinishProductionConcept
			RefreshFinishProductionConceptGUI()
		EndIf
```
Das wird solange aufgerufen, bis irgendwas "refreshFinishProductionConcept" mal auf false setzt. Das sollte die GUI aber machen. Muss nichts mit dem Fehler hier zu tun haben ...


SetspriteName ... ist ein stupider Setter, die Arbeit kommt in "GetSprite" - und die macht nur Aenderungen, wenn sich der Spritename geaendert hat.

**Comment by GWRon** [comment]
Das mag sein - und kann ich gerne "gleich mit" korrigieren. Allerdings sorgt da halt nur fuer ein erneutes Abholen aus der Registry - und sollte die Farbaenderung nicht verweigern.

**Comment by GWRon** [comment]
Ich habe eine Einkaufsliste geholt, die Produktion abgeschlossen ... und eine zweite Einkaufsliste (eines anderen Drehbuchs) angelegt ...
dann habe ich gespeichert.

Betrete ich nun den Supermarkt nach dem Einladen, kann ich das "nicht aktualisieren des Buttons" auch in einem Speicherstand reproduzieren.

Beim Betreten des Raumes und anklicken der "unfertigen" Liste sehe ich folgendes: 
```
RefreshFinishProductionConceptGUI
  -> set gfx_gui_button.datasheet.informative
RefreshFinishProductionConceptGUI
  -> set gfx_gui_button.datasheet (else)
```

**Comment by GWRon** [comment]
OK, der Fehler liegt daran, dass der neue "GetSprite()"-Code bei Nichtvorhandensein des "disabled"-Sprites (bspweise "gfx_gui_button.datasheet.disabled") den aktuell gesetzten Sprite beibehaelt.
Fuer "disabled" haben wir keine GUI-Dinge definiert, da wir da einfach den "normal-Button" (des "Themes") nehmen und mit 0.5 alpha rendern.

Denke das Verhalten muss ich nochmal umbauen.
