### ISSUE TITLE
Outcome issue with live production

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#928]
I made savegames with the issue I have with unexpected low outcome for live productions that I mentioned here. https://github.com/TVTower/TVTower/pull/918#issuecomment-1448446857

First savegame is immediately before the first live broadcast of "Tower Brandaktuell: Wirtschaft und Politik" starts.

Second savegame is one day later, just before the first non-live rerun starts. Despite significant loss of "topicality", the outcome will be much better.

[test-low-outcome-for-live-production.zip](https://github.com/TVTower/TVTower/files/10855599/test-low-outcome-for-live-production.zip)

The script template XML:

		<scripttemplate product="3" licence_type="1" guid="919f396e-c7c0-4191-abbc-01d559c0feef" creator="9551" comment="Perhaps some reciprocal effect with the corresponding news genre can be implemented? TODO: I am not happy with the titles and descriptions of these.">
			<title>
				<de>%tower% %latebreaking%: %title%</de>
				<en>%tower% %latebreaking%: %title%</en>
			</title>
			<description>
				<de>Politik aktuell. Jeden Tag neu. Wir analysieren die neuesten Entwicklungen in Wirtschaft und Politik.</de>
				<en>Politics up to date. New every day. We analyze the latest developments in business and politics.</en>
			</description>

			<variables>
				<tower>
					<de>TVT|Tower</de>
					<en>TVT|Tower</en>
				</tower>
				<latebreaking>
					<de>Brandaktuell|Aktuell</de>
					<en>Late-Breaking|Hot</en>
				</latebreaking>
				<title>
					<de>Politik|Wirtschaft und Politik|Fokus Politik|Polit-Klartext</de>
					<en>Politics|Business and Politics|Politics in Focus|Politics Plain Talk</en>
				</title>
			</variables>

			<jobs>
				<job index="0" function="1" required="1" />
				<job index="1" function="4" required="1" />
				<job index="2" function="8" required="1" />
				<job index="3" function="128" required="1" />
				
			</jobs>
			<data flags="1" production_limit="100" production_broadcast_limit="2" production_broadcast_flags="512" production_licence_flags="36" />
			<genres maingenre="300" subgenres="201,101" />
			<groups target_groups_optional="104" />
			<blocks value="1" />
			<price min="10000" max="20000" />
			<potential min="40" max="80" />
			<outcome min="40" max="80" />
			<review min="40" max="80" />
			<speed min="40" max="80" />
			<production_time value="60" />
			<programme_data_modifiers>
				<modifier name="topicality::age" value="5" />
				<modifier name="topicality::refresh" value="2" />
			</programme_data_modifiers>
		</scripttemplate>

**Comment by nittka** [comment]
Thanks for the report and the savegames. For the first broadcast the debug screen (Q) shows very low values for quality+topicality. For regular movies the values are determined on finishing the production. Live-Productions are (really) finished only after the broadcast ends. It looks like the values are calculated at the start of the broadcast (data sheet shows non-zero values) but after the audience has been determined.

This should affect all self-produced live-programmes.

**Comment by lonk0123** [comment]
Good Live-Productions (with high potential/actuality) usually deliver too high outcome of viewers.
I had games where i could reach max. 500.000 viewers with extraordinary expensive movies, then the live-productions kicked in with 1.5 Mill. viewers.
I guess this topic belongs to the still-to-balance-section.

**Comment by nittka** [comment]
Yes and no (depending which topic you referred to in the last sentence). Further balancing is definitely necessary. The actual bug to be fixed in any case is that the live production's quality data (speed etc.) must be calculated *before* the audience calculation takes place.
Currently, the qualtiy data is zero, audience is calculated and then the quality data is updated. With the proposed fix, the quality data is calculated at the right time.

The fix is a precondition for balancing. This ticket's bug affects only your own live productions, not programmes directly defined in the database or sports matches created by the game.

Can you tell me which live production had three times the viewers of an expensive programme? As far as I know the quality data is handled the same for all programmes and the live-flag only adds a bit on top...

**Comment by scr0llbaer9000** [comment]
> Can you tell me which live production had three times the viewers of an expensive programme?

I had mentioned this in the PR, other live scripts like `scripttemplate-ron-musiksterneamabend` work pretty well (already before this bug fix). Probably because that one uses a different syntax?

**Comment by lonk0123** [comment]
Hier mein Spielstand:
Tag 21/23 & 28 hatte ich mal Live-Konzerte reingenommen, da diese aufgrund der geringen Produktionskosten (kaum Darsteller nötig) praktisch unschlagbar günstig zu produzieren waren. Außerdem war die Aktualität halbwegs hoch, was im jetzigen Implementierungszustand des Spiels automatisch hohe Zuschauerzahlen garantiert. 

Man kann nun die Dinge immer nur mit Vorsicht miteinander vergleichen, wegen unterschiedlicher Sendezeiten, Genre-Bugs wie SciFi etc.

Tag 21: "Eroberung der der Affenerde" (das doppelte "der" ist mir heute zum ersten Mal aufgefallen) hat wesentlich größere Aktualität und erzeilt wegen SciFi (das Problem kennen wir ja von anderen Stellen) nur knapp 1/4 der Zuseher.

Tag 23: Sticht am deutlichsten hervor, wenn man sich das restliche Programm anschaut:
Die Komödie danach hat ungefähr die gleiche Aktualität und erzielt (wegen schlechter Sendezeit für Komödien) nicht mal ein Fünftel der Zuschauer.
Wenn man sich die Tage davor anschaut, sieht man, daß man sich über 500.000 Zuschauer echt freuen konnte. Insofern stechen die 1.7 Mio. schon deutlich hervor.

Tag 28: Wieder ein Livekonzert einer Lokalgröße (zumind. lt. Darstellerkosten), die aber wie eine Britney Spears zieht. Im Vergleich zum restlichen Programm (außer der Eigenproduktion direkt danach) deutlich über dem normalen Zuschauerschnitt.

Über die Eigenproduktionen (Don Rons) am Tag 29 wurde ja schon an anderer Stelle diskutiert.

Ich persönlich finde, daß gerade bei Livekonzerten mehr Rücksicht auf die Darsteller genommen werden sollte.
Die Musiker für "Jazz in der Dämmerung" kosteten mich praktisch nichts, sollten also Lokalgrößen darstellen. Sie ziehen aber Zuschauer an, wie Weltstars.

Ich denke auch, daß sich Eigenproduktionen/Livekonzerte lohnen sollten, aber ein gewisser Rahmen nur in Ausnahmefällen gesprengt werden sollte.

[DT64-Tag42.zip](https://github.com/TVTower/TVTower/files/10879686/DT64-Tag42.zip)

**Comment by GWRon** [comment]
Nebenschauplatz:

Ich denke, dass Genre bzw eher "Formate" die Besetzungsprioritaeten aendern koennen sollten.
Konzerte sind enorm von der Popularitaet der Musiker abhaengig (aber nicht vom Rest des Casts). Bei Reportagen hingegen spielt der Reporter kaum eine Rolle (Ausnahme hier Richard Attenborough usw.).

Man kann das feingliedrig implementieren (jedes Genre kann einen Mod fuer jeden Teil der Produktionsqualitaet beeinflussen...) Oder etwas einfacher halten: Genre bzw. das Programm selbst koennen definieren, ob hier die Popularitaet eines bestimmten Casts bzw Jobtyps wichtig/normal/unwichtig ist.


Allgemein kann natuerlich die Popularitaet des "Main casts" hoehere Gewichtung erhalten.

**Comment by scr0llbaer9000** [comment]
> das doppelte "der"

danke, werd ich in meinem nächsten PR aufnehmen.

> erzeilt wegen SciFi (das Problem kennen wir ja

ja, im Forum auch schon erwähnt. Eventuell sollten wir `programmedatamods.xml` beizeiten überarbeiten. Wobei es schon sein kann, dass das Genre nicht so beliebt ist, wie "unsereiner" vielleicht meinen mag (weil Rentner etc eben einen sehr großen Teil der Bevölkerung ausmachen).

Ich denke, dass Live-Produktionen schon sehr erfolgreich sein dürfen. Nicht nur die offensichtlichen Gassenhauer wie "Wetten, dass...?" sondern auch sowas wie "Dalli Dalli" am Donnerstag abend damals hatte durchaus meistens die Top-Filme auf den Konkurrenzkanälen ausgestochen. 

Speziell bei Musik-Live-Programmen verhält es sich aber durchaus anders, das interessiert nur Freaks, selbst bei Top-Acts (z.B. "Rockpalast" und Konsorten), und erst recht bei "Local"-Acts. Ausnahmen wären hier vielleicht sowas wie der Eurovision Song Contest (aber den sollte man sich ersteigern müssen) und wenige andere (sowas wie "Top of the Pops" war glaub ich nur in den 70ern ein Gassenhauer, sowas wurde irgendwann durch M-TV verdrängt; "Musikantenstadl" hätte sehr großen Zuspruch nur bei speziellen Bevölkerungsgruppen etc).
