### ISSUE TITLE
Incorrect compiler conditionals

### ISSUE THREAD

**Issue by woollybah** [TVTower/TVTower#93]
These probably want correcting...

https://github.com/TVTower/TVTower/blob/ca40e9234caec35627510c66826658e9660c0762/source/Dig/base.gfx.gui.bmx#L2231

https://github.com/TVTower/TVTower/blob/ca40e9234caec35627510c66826658e9660c0762/source/basefunctions_network.bmx#L1775

**Comment by GWRon** [comment]
Thanks.
