### ISSUE TITLE
AI sends trailers of programme it doesn't send

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#942]
Day n and day n+1

![Screenshot from 2023-03-09 18-56-58](https://user-images.githubusercontent.com/123826268/224226431-47178e1b-7b18-444a-87f2-f8733588c73e.png)

![Screenshot from 2023-03-09 18-57-28](https://user-images.githubusercontent.com/123826268/224226463-0258a710-7d41-4d60-842d-f1fbe6a49eaf.png)

"Die Adretten v." from 1st image 8am is sent 28 hours later (I don't know how the trailer influence effect lasts?). I strongly suspect it's just one of man reruns the AI typical does, and the AI rearranged the programme and forgot about the trailer. "Indianer James" from 2nd image 1am isn't sent on that day.

No save-file should be necessary, it happens often, easy to reproduce.

**Comment by nittka** [comment]
I noticed that too and ignored it when working on the other pressing issues of the UI. Trailers are used if no appropriate ad is present. Sent trailers are ignored when determining the programme.

Day n shows a long outage. Do you know what happened there (terrorist?). So far I could not reproduce these (note that I cannot really let the AI play in normal game time AND watch what it is doing...)

**Comment by scr0llbaer9000** [comment]
> Day n shows a long outage

Schedule of AI from more than 48 hours ago is deleted to save resources I've read somewhere? You mean that?

**Comment by nittka** [comment]
OK. This was not really an outage but "deleted data". (For regular games the entire AI broadcast history just takes up space, so it is truncated. You can specifiy the value in the DEV.xml)

**Comment by nittka** [comment]
Trailers are placed depending on the current schedule. If there are changes the trailers are not inspected again. At the moment it really is not worth the effort to optimize here.
