### ISSUE TITLE
DB: Jacky Gatess ... 

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#946]
Betrifft "kasi.xml"

![image](https://user-images.githubusercontent.com/2625226/224484011-21dd4531-1b1d-4977-a272-48e1f9dce07e.png)

Das muss wohl "Jacky Gates Schlaf Dich reich" heissen. (und im Englischen ebenfalls - und nicht Gates's)

Zwei Moeglichkeiten zur Loesung:
- sie einfach "Gate" nennen (und somit das "s" verhindern)
- mit Variablen arbeiten (einen Index "random" raussuchen - und dann fuer "Name mit 's" und "Name" getrennte Variablen nutzen)

```
			<title>
				<de>%Name1% %Name2_%Name2%b% Schlaf dich reich</de>
				<en>%Name1% %Name2_%Name2%b% Get rich sleeping</en>
			</title>

				<name1>
					<de>Jennifer|Carolin|Jacky|Maria|Hannah|Helene|Ivanka</de>
					<en>Jennifer|Carolin|Jacky|Maria|Hannah|Helene|Ivanka</en>
				</name1>
				<name2>
					<en>1|2|...</en>
				</name2>


				<name2_1a>
					<en>Miller</en>
				</name2_1a>
				<name2_2a>
					<en>Gates</en>
				</name2_2a>
...
				<name2_1b>
					<de>Millers</de>
					<en>Miller's</en>
				</name2_1a>
				<name2_2b>
					<de>Gates</de>
					<en>Gate's</en>
				</name2_2b>

```

Erst wird die interne Variable aufgeloest (und ergibt "1" oder "2" oder...) und dann ergibt sich erst der weitere Variablenname.

Allerdings bevorzuge ich _hier_ die einfache Loesung - "s" entfernen ;)

**Comment by nittka** [comment]
Ich wäre auch für den Quickfix. Noch richtiger wäre langfristig dann die Verwendung von Personenreferenzen (mit Casting). Es wird ja gesagt Jacky leitet die Show also Beruf Moderator. Hier müsste über eine Variable eine Person gewürfelt werden und diese automatisch für den Moderator-Slot geblockt werden.

Bei der Variablenauflösung hat man dann natürlich wieder dasselbe grammatische Problem (außer man lässt nur Personen mit unproblematischen Namen zu).

**Comment by GWRon** [comment]
Das Problem bei "vorbelegten Moderatoren" ist, dass dann bei Kauf des Drehbuchs noch nicht absehbar ist, wie viel der Moderator (der dann ja "fix" ist) kostet. Waere bloed, wenn der sauteuer ist...

**Comment by nittka** [comment]
Tja, da muss man sich dann eben vorher informieren.
