### ISSUE TITLE
Bug with TV family sitting on top of each other still happening with the latest release version

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#964]
![Screenshot from 2023-03-28 03-25-36](https://user-images.githubusercontent.com/123826268/228373221-adb5b75b-8745-4e54-9a2e-14024a0463a2.png)

But arguably, it's very very rare, I had it only once. And I can't reproduce it, saving and loading will fix it.

**Comment by nittka** [comment]
The change made in the last version fixed an obvious cause for this behaviour. Obviously, a less obvious one is still present.
