### ISSUE TITLE
Rearranging actors in Supermarket-Script view causes the software to freeze

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#965]
![Screenshot from 2023-03-28 23-35-26](https://user-images.githubusercontent.com/123826268/228373501-473fa53f-daea-4878-9d6a-c013274936bc.png)

Trying for example to swap "Benny Jameson" with "Samuel Löw" here directly (without right-click-removing and re-selecting) in this view will cause TVTower to freeze, unable to recover.

This should be easily reproducible, it happened with all scripts that I've tried.

**Comment by GWRon** [comment]
The issue lies in a recursing loop between events (logic -> gui -> logic -> ...) when setting the cast.
