### ISSUE TITLE
Senderkarte: Bevoelkerungskarte

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#966]
Es gibt ja schon die Bugmeldung, dass an manchen Stellen die Bevoelkerung "nicht hinhaut".

Unter
https://www.zensus2011.de/DE/Home/Aktuelles/DemografischeGrunddaten.html?nn=559100

Kann man sich eine Menge Daten herunterladen ... folgend auch "interaktiv" anschauen:
https://atlas.zensus2011.de/

Vielleicht sollten wir die Daten in ein "Bild" giessen und dann auf unsere Topokarte skalieren. Leider braucht es dann trotzdem noch einen "Modifikator" um die Zahlen dann in Einklang mit der "Gesamtbevoelkerungszahl" zu bringen.

Ich weiss noch nicht, wie die Performance der neuen Senderkartenfunktionen am Ende sein koennte - aber man koennte aus obigen Daten auch die Bevoelkerungsgruppen ein wenig "auslesen" und somit auf "Pixel" runterbrechen. Die Daten sind zumindest "unter 18", "ueber 65" und "maennlich/weiblich". Die Berechnungen erfolgen dann analog zur "Bevoelkerungszahl" - allerdings steigt der Rechenaufwand mit jeder Zielgruppe um den Faktor zwei (Teenager maennlich + weiblich).

**Comment by GWRon** [comment]
Die kleinere "1km"-Datengrid-CSV ist nicht ganz geeignet - sie fasst Bevoelkerungsdichten in "Gruppen" zusammen:

```
4	Einwohner	Bevölkerung
		von . . . bis unter . . . Personen
		 -1: Unbewohnt oder geheim zu halten
		1: 3 – 250
		2: 250 – 500
		3: 500 – 2 000
		4: 2 000 – 4 000
		5: 4 000 – 8 000
		6: 8 000 und mehr
```
Wenn ich die "gemittelt" ((Max-Min)/2) addiere komme ich nur auf 44Mio.

der 100m-Grid-Datensatz (1.2GB -- nur die Bevoelkerungszahlen, ohne Aufschluesselung fuer weiblich/maennlich):
```
./bmk makeapp -g x64 -t console -quick -r -x "/home/ronny/Arbeit/Projekte/Testcodes/TVTower_stuff/csv2densitymap/csv2image.bmx" 
Executing:csv2image
x: 4031350 - 4672550  = 641200m
y: 2684050 - 3551450  = 867400m
elements   = 35785840
population = 80324282
Compilation finished successfully.
```

die 80,3 Mio (2011) klingen relativ passend. Jetzt muss ich nur schauen, was rauskommt, wenn man die 100m auf die 1km heruntermixt. Bzw nicht 1km sondern eigentlich das gewuenschte "Ausgabeformat" (so dass es so gut wie moeglich zur Topo-Karte passt).

PS: Mittels "text.mod/csv.mod" dauert obige CSV-Einlesung und Berechnung so ca 5 Sekunden (bei mir :D).

**Comment by GWRon** [comment]
In zwei Stufen reduziert:
- erstmal eine "x_100m;y_100m;population"-CSV angelegt und dort die geheimen ("-1") weggelassen (53MB)
- "x_1km;y_1km;population"-CSV angelegt und dort alle drinliegenden Elemente "aufaddiert", 0er-Werte dann wegelassen (knapp 200.000 Zeilen mit insgesamt 1,2 MB)

Die "groesste" Zelle hat 23 50033 Einwohner - das waere beinem "Bild" dann also die "Graustufe 255".

**Comment by GWRon** [comment]
Ich habe aus der CSV dann "skaliert" ein PNG erzeugt (mit 255 skaliert) auf die 23533)

![image](https://user-images.githubusercontent.com/2625226/228569757-1782e54e-57cd-45e5-a016-5236e2389248.png)

**Comment by GWRon** [comment]
Ich sitze noch an einem Algorithmus um die Daten "skalieren" zu koennen.
Im Gegensatz zu Bildern kann ich hier die Werte ja nicht "verdoppeln" (wie "Pixel" beim Skalieren).

![image](https://user-images.githubusercontent.com/2625226/229157054-0600ca4d-7c71-4688-87e8-8d5f84ec7c91.png)

Dazu gibt es sicher einen Fachbegriff ... allerdings komm ich nicht drauf. Also muss ich das "haendisch" programmieren und Stueck fuer Stueck Werte ermitteln. Hatte auf eine schoene "Formel" gehofft.

**Comment by GWRon** [comment]
Davon abgesehen, dass obige Grafik inkorrekt ist (die Summe "aller Zellen" muss vor und nach Skalierung die gleiche sein - nicht die Summe der jeweiligen Zeilen bzw Spalten).

"4x4 Float" ist also Falsch (Summe 12 vs 24)


Ich habe jetzt (Danke an Brucey fuer die Ideengebung) eine Formel mit der das Stretching funktioniert und die Bevoelkerungszahl "gleich" bleibt.

Der Vollstaendigkeit halber ist das die hier:
```Blitzmax
Function StretchArray:Int[](array:Int[], arrayW:Int, arrayH:int, newW:Int, newH:Int)
	Local result:Float[] = New Float[newW * newH]

	Local rowRatio:Float = arrayW/Float(newW)
	Local colRatio:Float = arrayH/Float(newH)

	Local origSum:Int
	Local rescaledSum:Float
	For local i:int = EachIn array
		origSum :+ i
	Next
	

	For local destX:int = 0 until newW
		For local destY:int = 0 until newH
			Local totalWeight:Float = 0

			Local srcXStart:Int = int(destX * rowRatio)
			Local srcXEnd:Int = int((destX + 1) * rowRatio)
			Local srcYStart:Int = int(destY * colRatio)
			Local srcYEnd:Int = int((destY + 1) * colRatio)
			For local srcX:int = srcXStart to srcXEnd
				For local srcY:int = srcYStart to srcYEnd
                    Local xOverlap:Float = min((destX + 1) * rowRatio, srcX + 1) - max(destX * rowRatio, srcX)
                    Local yOverlap:Float = min((destY + 1) * colRatio, srcY + 1) - max(destY * colRatio, srcY)
                    Local overlapArea:Float = max(xOverlap, 0) * max(yOverlap, 0)
                    Local weight:Float = overlapArea / (rowRatio * colRatio)
                    totalWeight :+ weight
					result[destY * newW + destX] :+ array[srcY * arrayW + srcX] * weight
				Next
			Next
            result[destY * newW + destX] :/ totalWeight
            rescaledSum :+ result[destY * newW + destX]
		Next
	Next

	' Adjust the output array to preserve the total sum
    Local scalingFactor:Float = origSum / rescaledSum

	' cut the array down to integers
	Local resultInt:Int[] = New Int[newW*newH]
	Local integerSum:Int
    For local i:int = 0 until resultInt.length
		resultInt[i] = Int(result[i] * scalingFactor)
		integerSum :+ resultInt[i]
	Next

    print integerSum + "  scalingFactor="+scalingFactor + "  origSum="+origSum + " rescaledSum="+rescaledSum

    ' Distribute the difference among the array elements
    Local diff:Int = Int(origSum) - integerSum
    Local x:int, y:int
    while diff <> 0
		if diff > 0
			resultInt[y*newW + x] :+ 1
			diff :- 1
		Else
			resultInt[y*newW + x] :- 1
			diff :+ 1
		EndIf

        y :+ 1
        if y >= newH
            y = 0
            x :+ 1
        endif
	wend
	
	return resultInt
End Function
```

**Comment by GWRon** [comment]
Momentan fuehre ich die neue Bevoelkerungskarte mit dem neuen "Canvas"-System zusammen.

Wenn ich mit den groben Tests dazu durch bin, wuerde ich einen Draft-PR aufmachen. Dauert aber denke ich noch einige Tage.

**Comment by GWRon** [comment]
OK, wir koennen die Bevoelkerungsdichtekarten nun beliebig "stretchen". Das hat den Vorteil, dass bei einem flaechenmaessig sehr grossem Land nicht 3000x2000 Elemente sondern "standardisiert" bspweise auf einen fixen "Breitewert" (Beibehaltung des Bildverhaeltnisses - also 1500x1000 und nicht 1500x1500) herunter- bzw. hochskaliert wird.

Im Hinblick auf sich eventuell aendernde Bildschirmaufloesungen (von 800x600 auf eine hoehere "Interne Aufloesung") muss eh von "Pixelkoordinaten" weggegangen werden.
Antennen wuerden dann an "Kilometern" ausgerichtet werden und ein Skalierungsfaktor kann dann von "Kilometer" auf Pixel umrechnen.
Gleiches gilt fuer den Radius der Antennen.

Der Vorteil waere, dass die Antennen in groesseren Laendern automatisch "visuell kleiner" wuerden. und bei Inselstaaten entsprechend "groesser".

Alles muss natuerlich immer fein in "ganze Kilometer" gerundet werden um da etwaige "Wackler" zu vermeiden.

**Comment by nittka** [comment]
Bei den variierenden Antennenradien müssen wir dann bei der KI aufpassen. Aktuell wird die Abdeckung der Karte ja über den festen Radius der initialen Antenne berechnet (Abstand zwischen Antennen etwas kleiner wählen und dann in regelmäßigen Abständen Kreise auf die Karte setzen). Wenn jetzt Kilometer und Pixel auf der Karte nicht mehr gleich sind, wird diese Berechnung komplizierter.

**Comment by GWRon** [comment]
Die Senderkarte ist ein ... groesseres Umbauprojekt ... denn angenommen.

Irgendwie basiert ja vieles auf den fixen 800x600. Alles muss nun auf den internen "Bevoelkerungsdichtedatensatz" umgerechnet werden. Damit waeren wir am Ende aufloesungsunabhaengig(er).

Heisst die definierten "Kollisionsmasken" brauchen eine Bezugsgroesse ("Designgroesse") und eine aktuelle Groesse ("Rendergroesse"). Mit der Bezugsgroesse und dem Bevoelkerungsdichtedatensatz koennen die Masken dann skaliert werden (sozusagen in unserem Fall auch die horizontale Streckung "rueckgaengig machen").

Am Ende haben wir also "Layer" in neuen System, die "genau" auf den Bevoelkerungsdichtedatensatz draufpassen. Wir also fuer das Bundesland die jeweilige Bevoelkerung ermitteln koenn(t)en usw.

Da alles wieder eigene Origins/Offsets usw hat - komme ich da derzeit noch gut durcheinander und muss "Debug-Bilder" erzeugen um zu sehen, wie wo Daten inkorrekt skaliert oder verschoben sind.


Zieht sich einfach alles ein wenig wie Kaugummi.

**Comment by GWRon** [comment]
Genau. Intern wird in Kilometern gerechnet. Nach aussen dann umgerechnet in Pixel, also am Ende aufloesungsunabhaengig.

**Comment by nittka** [comment]
Hm. Aber im realen Leben steht der Sender an einem Punkt und die Reichweite ändert sich nicht mit der Flughöhe. Wäre es da nicht besser die Auflösung der Karte zu fixieren und dann zu schauen, auf welchen Kartenpunkt ein Bildschirmpunkt mappt?
Es klingt im Moment so, als würde sich die Reichweite eines existierenden Senders zu einem festen Zeitpunkt ändern können, je nachdem welche Auflösung man gerade einstellt (ggf. sogar beim Vergrößern/Verkleinern des aktuellen Fensters, in dem das Spiel läuft).

**Comment by GWRon** [comment]
Danach sollte bzw wollte ich aber nicht klingen 

Intern gibt es einen Datensatz der eingeladen wird und auf Bevoelkerungsangaben in fixen Rastern basiert (bspweise 1x1 km oder 100x100m).
Das wird auf einen Wert skaliert (Gesamtbevoelkerung bleibt gleich) um die Datenhaltung zu erleichtern (1500 als maximale Breite oder Hoehe).
Als Seitenverhaeltnis orientiert es sich am Seitenverhaeltnis der Topografiekarte (also Bilddaten). Das ist damit Antennen "rund" bleiben.
Am Ende gibt es einen Datensatz der die Landkarte in maximal 1500x1500 Datenpunkten enthaelt.

Die Bildpixel werden dann entsprechend skaliert auf die (im gleichen Seitenverhaeltnis abgelegten) Datensaetze gemappt.
Bildpunkt px,py landet dann auf datensatz,datensatzy usw.

Das ganze ist dann also aufloesungsunabhaengig ... 
Einziger Unterschied ist, dass bei geringer Auflösung nicht grafisch der gleiche "Datenpunkt" anvisiert werden koennte.

**Comment by GWRon** [comment]
Derzeit integriere ich die neue Senderkartenlogik ins Spiel - und behebe dabei auftretende Bugs bzw. bereite alles weiter in Richtung "Aufloesungsunabhaengigkeit" vor.

Derzeit mische ich neue Bevoelkerungszahlen (Zensus 2010) mit unseren "Pixel-Bundeslaendern" die nur gestretcht und "unvollstaendig" (bspweise Inseln) vorhanden sind. Auch passen scheinbar meine Topografie (und somit auch die Bundeslaender-Sprites) nicht ganz uebereinander (siehe folgende Grafik - dort Westen, Suedwesten und eventuell die Alpenregion im Sueden - oder da wohnt keiner :D).

![image](https://github.com/TVTower/TVTower/assets/2625226/fa55be0d-1819-4208-8010-4c0a7b70607e)


Folgend jedenfalls mal ein Vergleich der Einwohnerzahlen "derzeit"/old, "Zensus basiert"/new und "eurostat" (abrufbar bspweise mit https://datacommons.org/place/nuts/DE8?hl=de  -> dort dann das Bundesland eintippen) 

```
old population: 80339766
total population in density layer (zensus): 80324282
total population in sections (new): 80031720
Section bremen population: old = 267488    new = 703881   eurostat = 569396  -19.1%)
Section berlin population: old = 3734484    new = 3493549   eurostat = 3443000  -1.44%)
Section hamburg population: old = 2592512    new = 2163587   eurostat = 1774000  -18.0%)
Section bawue population: old = 9564438    new = 10402250   eurostat = 10744921  3.294%)
Section bayern population: old = 14385592    new = 12359162   eurostat = 12510331  1.223%)
Section saarland population: old = 879268    new = 936107   eurostat = 1022585  9.238%)
Section rheinlandpfalz population: old = 3890952    new = 3812374   eurostat = 4012675  5.253%)
Section hessen population: old = 5071950    new = 6529419   eurostat = 6061951  -7.15%)
Section thueringen population: old = 3156140    new = 2399220   eurostat = 2249882  -6.22%)
Section sachsen population: old = 4407000    new = 4170139   eurostat = 4168732  -0.03%)
Section sachsenanhalt population: old = 2491476    new = 2331394   eurostat = 2356219  1.064%)
Section niedersachsen population: old = 7827482    new = 7348458   eurostat = 7928815  7.897%)
Section schleswigholstein population: old = 1631240    new = 2185161   eurostat = 2832027  29.60%)
Section brandenburg population: old = 3731234    new = 2212660   eurostat = 2511525  13.50%)
Section nrw population: old = 14836614    new = 17304194   eurostat = 17872763  3.285%)
Section meckpom population: old = 1555996    new = 1680165   eurostat = 1651216  -1.72%)
```
wenn ich den Offset fuer die Bevoelkerungsdaten (die weissen Punkte) entsprechend nach links verschieben wuerde, waeren die Gesamtbevoelkerungszahlen wieder ein wenig naeher dran am Zensus.
Vermutlich sollte ich am Ende die Senderkarte generell noch ueberarbeiten - also die Grafiken. Heutzutage gibt es ja weit mehr offene Datensätze (Vektoren der Bundeslaender) und da laesst sich denke ich genauer arbeiten.

**Comment by GWRon** [comment]
Mit https://github.com/TVTower/TVTower/commit/d8a675a0d08ef0d68a46e5e697b9fa7b0f56151e erledigt

Neue Topografiekarten stehen noch aus
