### ISSUE TITLE
Choice: "Start production" missing after production review

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#97]
![prodbewertung](https://user-images.githubusercontent.com/57690824/68721813-f66f5e00-05b3-11ea-9cd9-c105094afb74.JPG)

After selecting a finished production list for review by the studio master the option "start production/start all productions" is missing in the speech bubble's multiple choice. You have to reselect the studio master again.

**Comment by nittka** [comment]
Ist behoben.
