### ISSUE TITLE
Most fictional people should have birthday relative to start year

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#970]
As discussed in https://github.com/TVTower/TVTower/issues/867

Programmes can be set to have a release year relative to the start year. Fictional people need that feature too. Obviously and most notably, Betty should always be the same age (25? 30?) at the beginning of a game, no matter if the game starts in 1980 or 2020.

**Comment by nittka** [comment]
With the PR, relative birth years can be specified for fictional persons. Existing productions with these persons have to be checked and made relative as well. Otherwise automatic age fixing will modify the year of birth.
