### ISSUE TITLE
Eigenproduktion: Drehbuch "availability" aendern, wenn anderes Drehbuch verfilmt wurde

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#972]
Ich kopiere mich mal von discord:
> Einfach eine eigene Kultreihe (mit Patty Glansen) aufziehen - dann kann man dazu auch Drehbuecher verfassen.
> Eventuell braucht es hier noch einen trigger um bei Fertigstellung von Drehbuch1 die availability von Drehbuch2 abzuaendern.

Sprich man dreht "Nackedei im Spessart" und nach Fertigstellung gibt es das Drehbuch (irgendwann mal ...) "Zwei Nackedeis im Spessart".

Umsetzung waere ueber die "effects".

**Comment by nittka** [comment]
Im verlinkten PR werden Effekte für Drehbücher ermöglicht. Aktuell ist zunächst nur "onBroadcast" etc. vorgesehen, d.h. man würde ein Drehbuch freischalten, wenn eine fertige Produktion ausgestrahlt wird. Das sollte für die meisten interessanten Fälle schon reichen. Ob wirklich Effekte "onFinishProduction" etc. nötig sind, wäre nochmal zu diskutieren.
