### ISSUE TITLE
Makler: Texthinweis bei unzureichendem Kontostand für Anmietung

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTower#975]
Eggi72 im Discord konnte einen Raum nicht anmieten.
Zwar ist der Geldbetrag "roetlich" aber ich musste auch zwei mal hingucken um zu erkennen, dass sein Kontostand ja bei 40.000 war ... und 44.000 gefordert.

![image](https://user-images.githubusercontent.com/2625226/229377008-998e3fb1-29d1-4f55-b717-2fe31895767d.png)

Eventuell koennten wir den Tooltiptext entsprechend anpassen, wenn der Kontostand unzureichend ist.

> Nicht genügend Geld
> 44.000 € erforderlich

so in der Art.

**Comment by nittka** [comment]
In dem Fall, dass ein Mieten (aufgrund des Kontostands) nicht möglich ist, sollte wohl auch der Mauszeiter durchgestrichen sein und ein Anklicken gar nicht erst erlaubt sein.
