### ISSUE TITLE
Typo in several movie descriptions 

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#98]
"MIR - auf der Suche nach dem UFO aus TVT""Wissen**S**wertem" - S is missing
![mir_typo](https://user-images.githubusercontent.com/57690824/68722386-92e63000-05b5-11ea-9d45-78d2214f6aee.png)

"Kommissar Wirsch" Ein**N**wohner "n" too much.
![wirsch_typo](https://user-images.githubusercontent.com/57690824/68722607-46e7bb00-05b6-11ea-906c-ec7afef2a795.png)

"Albino Wal" Kapitain = Kapitän (engl. Captain)
![wal_typo](https://user-images.githubusercontent.com/57690824/68722858-21a77c80-05b7-11ea-8d3e-cdb30679c3f2.png)

**Comment by GWRon** [comment]
Du kannst - dank Github account, sogar selbst solche Rechtschreibfehler fixen - einfach "Code" - dann "res ... database .. default ..." und die entsprechende .xml anfassen. Damit _koenntest_ Du online die tippfehler rausschmeissen und mir die Aenderung automatisch "vorschlagen".

**Comment by GWRon** [comment]
http://i.imgur.com/ChqjJW1.png
