### ISSUE TITLE
globale Variable oder data flag für scripttemplate für Nummerierung by default

### ISSUE THREAD

**Issue by nsalomon** [TVTower/TVTower#983]
Data flag für scripttemplate um eine mittels Drehbuch produzierte Serie (oder anderen Titel) von Anfang an mit #1 zu markieren.
So könnte der Name einer Serie gleich von Anfang an mit "Staffel #1" markiert werden,

Evtl. auch via globale Variable lösbar, welche immer die zum Titel passende, tiefstmöglichste Nummer ausgibt.

Beispiel: <titel>Das Boot %count%</title> oder <titel>Die Sendung mit der Maus - Staffel %count%</title>
Ausgabe: "Das Boot 1", falls "Das Boot 1" schon existiert = "Das Boot 2" usw.

**Comment by nittka** [comment]
Folgendes könnte schon jetzt funktionieren (bitte ausprobieren): `<title><de>Das Boot #1</de></title>`

Bei der ersten Produktion wird direkt der Titel verwendet, bei der zweiten wird festgestellt, dass der Titel bereits existiert und das automatische Counter-Hochzählen schlägt zu.

**Comment by nsalomon** [comment]
Getestet mit <de>${title} Staffel #1</de> und funktioniert:

Ergibt dann jeweils Drehbücher mit "Titel #1", "Titel #2" etc.
