### ISSUE TITLE
Content in `lang/en.xml` doesn't seem to resolve properly

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#985]
In [my current PR](https://github.com/TVTower/TVTower/pull/984) I've tried out the new localized people data feature. I've added these entries to `lang/en.xml`:

		<person id="1994aa3a-23c3-48ce-b20a-d1f021df8c63" first_name="Queen Svetlana" last_name="of Sweden" />
		<person id="2994ff3d-ffc4-f8ce-c25a-e1g0d1df8c64" first_name="a jobless man called" last_name="&quot;Woozy&quot;" />
		<person id="f14d6ba0-0db5-4a76-a4d3-daba1603e4f6" first_name="Johnny" last_name="Jobless" />
		<person id="f43f2b92-43cd-4fc8-93aa-25adc647fb63" first_name="Elmer" last_name="Rednose" />

However, in the game, when playing in English, these translated names won't show, the names still appear in German, and I don't quite understand why. The already existing entries in that file *are* working. My new ones are not, and I don't quite see any difference.

**Comment by nittka** [comment]
You have to use "guid" not "id" as attribute!

**Comment by scr0llbaer9000** [comment]
ah how did I miss that, thanks.

It's working now.

I have removed the affected name attributes from the `database_people_fictional.xml` file, as to not have them redundant. But that looks kinda weird too. Or what would you propose about that?

**Comment by nittka** [comment]
Leave the name attributes in place. The database should be complete. The localization files are "add-on".
