### ISSUE TITLE
Year still is cut off sometimes

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#986]
The fix for https://github.com/TVTower/TVTower/issues/832 solved most cases, but it still happens sometimes.

![Screenshot from 2023-05-19 18-23-28](https://github.com/TVTower/TVTower/assets/123826268/7e66bc87-a6fe-4a5e-ad71-de8539e59a19)

I guess the measuring of the necessary space isn't accurate enough. Alternatively, the year could be displayed first, as it is the more important information.

**Comment by nittka** [comment]
There is no measuring, just a naive heuristic allowing more space (fixed value) when the country list is long.
