### ISSUE TITLE
Italian programme titles seem to override default language

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#987]
Now this is a weird one.

![Screenshot from 2023-05-19 18-37-23](https://github.com/TVTower/TVTower/assets/123826268/49768fb9-aaed-461e-ab99-df949300236b)

The definition looks like this:

			<title>
				<de>Der gezähmte Widerspenstige</de>
				<en>The Taming of the Scoundrel</en>
				<it>Il Bisbetico Domato</it>
			</title>
			<description>
				<de>Kommerziell sehr erfolgreich in Europa. Der mürrische Elia wehrt sich gegen die Bemühungen seiner Haushälterin, ihn zu verkuppeln. Auch einer schönen jungen Frau, die wegen einer Panne auf seinem Hof übernachtet, zeigt er zunächst die kalte Schulter.</de>
				<en>Commercially very successful in Europe. The grumpy Elia resists the efforts of his housekeeper to set him up. Initially he also gives the cold shoulder to a beautiful young woman who spends the night on his farm because of a breakdown.</en>
			</description>

It does not happen for any other language like French `<fr>`. Only Italian.

It should be easy to reproduce.

**Comment by nittka** [comment]
Italian is not a supported language (res/lang/...), so it has not language ID. In case no language ID is found, the entry will be used for the "current" language (which is a bug).
Currently, there may be no fix that works globally. You can place the Italian entry at the very top so it will be overridden by the correct German one.
The database code should get a guard ignoring entries for unknown languages, but if somebody adds Italian localization, the title will only be present for a new game, not for an already started one...

**Comment by GWRon** [comment]
hmm maybe we should simply create the language (ingame) in case it is missing. (and drop a hint into the logs that we did so).

It _could_ be added to the getters so in case of "lang not found" it creates it (and logs this issue).

**Comment by nittka** [comment]
I'd prefer not dynamically adding a language which is practically not supported at all.

**Comment by scr0llbaer9000** [comment]
could have sworn Italian is supported, so similar to French. `:)`

I think it should be supported, so many Italian movies by now. I usually add the original titles of the original language of a film for the common European languages.

**Comment by nittka** [comment]
Not even French is really supported. Except for English and German the localization files are very much out of date.
