### ISSUE TITLE
No Birthday/age for several actors shown

### ISSUE THREAD

**Issue by Nalindir** [TVTower/TVTower#99]
Instead of birthday only *'s are shown for actors during production list shopping. Not all actors are affected. 

e.g. Babsi Angora, Betty Botterblom, Vera Zottorova 
![no-birthday](https://user-images.githubusercontent.com/57690824/68723244-51a34f80-05b8-11ea-8de8-82b47b5e7978.png)

**Comment by GWRon** [comment]
Planned behaviour - persons from DB might not have a birth/deathday stored. Could give them some ... if desired. But might look odd if someone created love/romance movies and then "Babsi Angora" becomes a 85 years old lady :)

Somewhere in the code I've buried some generation algorithm which checks for first movie appearance and uses this + some years added, as minimum.
