### ISSUE TITLE
References to roles with index larger than 5 or 6 seems unsupported

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#991]
Scripttemplate id `a3d2c98d-fbdb-45c1-a5f0-0e61cfa497e7`:

Similarly to https://github.com/TVTower/TVTower/issues/834, it seems role numbers larger than 5 or 6 are unsupported.

![Screenshot from 2023-05-21 15-56-57](https://github.com/TVTower/TVTower/assets/123826268/6e34ae05-ef17-4c4e-bca7-1ea84978eecb)

				<job index="5" function="2" required="1" role_guid="2d64c9b9-e668-4504-9a3b-f5a13a367d5f" />
				<job index="6" function="2" required="1" role_guid="67ffb376-8df4-46ed-ba50-65e31806326a" />
				<job index="7" function="2" required="1" role_guid="14cff5bd-6aee-444b-9f2c-a844220b3ed7" />
				<job index="8" function="2" required="1" role_guid="6c3e23b0-11e3-40fb-ab09-57b0d2f79c2a" />
				<job index="9" function="2" required="1" role_guid="e1dec1fa-300a-414b-acc9-fe587f1ba520" />

**Comment by nittka** [comment]
Role7 is the last supported one. I am reluctant to change the code at this moment (support 8 and 9 and then 10 will be missing). With the new expression support, such restrictions should be obsolete.

**Comment by nittka** [comment]
It looks like you could reorder the jobs such that there would be no problem with the current logic. Not all roles are referenced in title/description.
In this case I REALLY would like to ignore this issue until the new expression support is available.

**Comment by scr0llbaer9000** [comment]
yeah sure no prob
