### ISSUE TITLE
Text über Text im Supermarkt

### ISSUE THREAD

**Issue by lonk0123** [TVTower/TVTower#993]
![Text über Text](https://github.com/TVTower/TVTower/assets/121659400/7553720e-0564-4867-be2a-ffd4efe18333)

**Comment by nittka** [comment]
In diesem Dropdown wird wohl nicht mit so langen Texten gerechnet. Ggf. muss man die Titel in der Liste kürzen. Der volle Text ist ja im Datenblatt ablesbar. Ich weise das erstmal Ronny zu, falls da frameworkseitig was gemacht werden kann.

**Comment by scr0llbaer9000** [comment]
Diese Einträge sind von mir.

Die Episodentitel sind hier gar nicht lang.

Liegt also am Titel der gesamten Serie. Und da ist man ja bisher quasi angehalten, die recht variabel zu gestalten (damit die `#1`-, `#2`-Varianten weitestgehend vermieden werden), und so werden sie potenziell länger.

(Das hier wär auch ein Fall für ein Franchise, wenn das "Schutz"-Feature aktiviert ist, könnte man sich theoretisch den "Die Erzählungen vom Magischen Land"-Teil sparen.)

Generell scheint es aber in dieser Ansicht ausreichend zu sein, wenn man den Platz für den Titel der Serie auf zwei Zeilen und den für den Episoden Titel auf eine Zeile beschränkt und jeweils mit Pünktchen abkürzt.

**Comment by nittka** [comment]
Ich habe das Thema Franchise-Schutz noch nicht so richtig verstanden... Natürlich ließe sich beim Thema Titelschutz und Templateverfügbarkeit noch viel machen. Die Frage ist immer: mit welchem Aufwand für wieviele Fälle.
Für diese konkrete Template gäbe es aber auch aktuell schon Alternativen für kürzere Titel
* Staffel 1 weglassen
* X - %magische%
* X - Staffel \#1

Je mehr Templates es gibt, desto geringer ist jetzt schon die Wahrscheinlichkeit, dass ein Counter eingesetzt werden muss. Und selbst WENN. Ein Spieler kann den Titel im Supermarkt ändern.
