### ISSUE TITLE
More logging and validation of data entries

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#995]
For the moment I know of two types of issues concerning data entries, but there might be many more.

1. When accidentally putting the same XML attribute (like `comment`) into any entry (`person` or `programme`), the XML file won't load, and the logfile says: "version 2 is deprecated. Upgrade to V3 please." This is not very helpful and probably an inaccurate message. At least the offending line should be output.

2. When accidentally leaving `blocks=""` empty in a `programme` entry, the XML file will load fine, but the game will eventually hard-crash, probably when a (AI) player tries to put that programme into their schedule. The software should validate that `blocks` is always set to a reasonable value.

**Comment by scr0llbaer9000** [comment]
Slightly related to 2, I out-commented and activated `TheRob-Mon-TvTower-EinmonumentalerVersuch` in my recent PR, but in a 12 hour version instead of 24. I had play-tested, and as expected, 12 hours is the maximum value that works with the UI in the game. With more than 12 hours, the entry won't wrap over properly in the schedule planner, the wrapping-over functionality works only one time (although the rest of the functionality might still work out, but I haven't tried).

I don't think this should be "fixed" as more than 12 hour shows are an unlikely occurrence in reality (even marathon things like certain some sports events are broken up), but it should be validated or at least documented that `blocks` must be a value between 1 and 12.

**Comment by nittka** [comment]
Tooling for validation already exists (https://github.com/TVTower/TVTDatabaseEditor) and I use it to give the feedback. All the above issues are already covered there. I extend the editor and the validation whenever new issues arise (but as nobody else seems to use it so far, so I don't publish a new version after every change). 

(I will not transfer all the validation in place to a separate BMX-based database checker and putting it all into the game code seems overkill. The game itself should be allowed to assume that the database is valid.)

**Comment by scr0llbaer9000** [comment]
I don't think end users (who also will want to try out stuff in their user files) should be "encouraged" to install Eclipse.

I think any software needs to sanity-check all inputs.

A hard-crash should be prevented in any case.

And for the cases where invalid XML is recognized and the file is not loaded, I don't think it's a problem to also output the line number or affected guid/id where the reader/parser stopped (even if the exact reason won't be specified for the time being)?

**Comment by nittka** [comment]
See also #1042 which improved logging for invalid XML. Feel free to open tickets for specific database modelling problems you ran into (here or also for the database editor in case you want to continue using it).
